### ISSUE TITLE
ScrollView inside PanGestureHandler doesn't work correctly

### ISSUE THREAD

**Issue by ianmartorell** [software-mansion/react-native-gesture-handler#1001]
On iOS and Android, scrolling a ScrollView inside a PanGestureHandler works great, only triggering the corresponding handler depending on where you touch. But on web, scrolling the ScrollView will sometimes trigger the PanGestureHandler at high velocities. Releasing the ScrollView and then intentionally triggering the PanGestureHandler also makes it jump unexpectedly.

I'd investigate but I'm not sure how to go about it. If someone can give me some pointers I'd be more than happy to help.

Screen recording: 
[RPReplay_Final1583844877.MP4.zip](https://github.com/software-mansion/react-native-gesture-handler/files/4312528/RPReplay_Final1583844877.MP4.zip)

**Comment by EvanBacon** [comment]
Could you please provide a Minimal reproducible example?

**Comment by ianmartorell** [comment]
I'm a little busy at the moment but I'll try to get a repro up as soon as possible!

**Comment by jakub-gonet** [comment]
Closing until repro is provided.
