### ISSUE TITLE
Testing react-native-gesture-handler with jest and enzyme

### ISSUE THREAD

**Issue by HenryGorner** [software-mansion/react-native-gesture-handler#1009]
Hey guys, 

I need to test some of my components where I am using react-native-gesture-handler and react-native-reanimated. Upon clicking TapGestureHandler a modal opens up in my application which is driven by reanimated. 

For example, how can I simulate a press event on the TapGestureHandler in jest? Or how can I check that animation values are being changed after the TapGestureHandler was pressed in jest? Could someone please point me to an example, if possible? 

Cheers

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
If you need further help please reply.

**Comment by radelcom** [comment]
@HenryGorner were you able to find a solution/workaround for this scenario?

**Comment by agrawal-rohit** [comment]
Facing this issue as well

**Comment by jakub-gonet** [comment]
We're working on allowing firing touch events in Jest. You can track the progress in #1762.
