### ISSUE TITLE
TouchableNativeFeedback requires second click to take action

### ISSUE THREAD

**Issue by Bayramito** [software-mansion/react-native-gesture-handler#1010]
Hello
I have a strange issue, i made a simple button component with TouchableNativeFeedBack but  it requires second click to take action. ,
For example i give it to goBack function from the navigation, but it does not doing anything on my first click, instead working on the second click *BUT* acting like i pressed twice so going to 2 steps back.

This is how i use the component 
`     <IconButton
            name="arrow-left"
            size={30}
            color="black"
            onPress={() => {
              navigation.goBack();
            }}
          />`

and this is the inside of the component

```
import React, {Component} from 'react';
import Icon from 'react-native-vector-icons/FontAwesome5';
import {View} from 'react-native';
import {TouchableNativeFeedback} from 'react-native-gesture-handler';

export class IconButton extends Component {
  constructor(props) {
    super(props);
  }
  render() {
    const {name, size, color, onPress, style, ripple, background} = this.props;
    return (
      <View style={background}>
        <TouchableNativeFeedback
          background={
            ripple ? TouchableNativeFeedback.Ripple(ripple, true) : null
          }
          style={style}
          onPress={onPress ? () => onPress() : null}>
          <Icon name={name} size={size} color={color} />
        </TouchableNativeFeedback>
      </View>
    );
  }
}

export default IconButton;
```

Another interesting thing is, if i give to the parent element where i use this component "justifyContent: "center' it works fine but on any other case its not working.

**Comment by piaskowyk** [comment]
Hey, could you provide a repo to reproduce your issue?
