### ISSUE TITLE
Erro na criação de App com base num template.

### ISSUE THREAD

**Issue by marcelorafael** [software-mansion/react-native-gesture-handler#1012]
Na hora de criar um projeto com base num template dá esse erro: 

√ Downloading template
× Copying template
error Error: Couldn't find the "C:\Users\<nomeUsuario>\AppData\Local\Temp\rncli-init-template-cKMBnz\node_modules\<nomeTemplate>\template.config.js file inside "<nomeTemplate>" template. Please make sure the template is valid. Read more: https://github.com/react-native-community/cli/blob/master/docs/init.md#creating-custom-template

Falta alguma configuração?
Mesmo tentando usar um template de outra pessoa dá o mesmo erro

**Comment by douglaslondrina** [comment]
@marcelorafael Seu problema não está relacionado a esse projeto, por gentileza feche a issue que abriu aqui.
