### ISSUE TITLE
Gesture Handler Screen: regression in styling of buttons in main menu

### ISSUE THREAD

**Issue by rigdern** [software-mansion/react-native-gesture-handler#1014]
### Problem

You can see the styling of the buttons in the main menu is incorrect (for example, the buttons are too short and difficult to tap):

![image](https://user-images.githubusercontent.com/199935/77866291-46f3fa80-71e7-11ea-8337-3417a85d44e3.png)

### Cause

The styling was broken by 7048f6427a7d1a8fd3d5319e01535e99dfe11bc9. `RectButton` used to honor all of the styles passed to it but now it only honors a small subset.

cc @janicduplessis @osdnk

**Comment by janicduplessis** [comment]
Sorry about that, #1015 should fix it.

**Comment by gavrix** [comment]
Even with the fix examples doesn't seem to work at all — nothing taps on iOS.

**Comment by rigdern** [comment]
@gavrix That's true. Somebody reported this bug in #998.
