### ISSUE TITLE
Outdated examples for ScrollView with waitFor

### ISSUE THREAD

**Issue by gavrix** [software-mansion/react-native-gesture-handler#1017]
Some of examples showcasing `ScrollView` with `waitFor` feature are referencing string constants (are these ancient refs?) which are never mentioned anywhere in the repo. 
```
 <ScrollViewComponent
          ref={node => (this._scrollView = node)}
          waitFor={['dragbox', 'image_pinch', 'image_rotation', 'image_tilt']}
...
```

https://github.com/software-mansion/react-native-gesture-handler/search?q=image_tilt&unscoped_q=image_tilt

it's very confusing where are these constants coming from? Trying to use real refs for waitFor are causing runtime crash https://github.com/software-mansion/react-native-gesture-handler/issues/1016

**Comment by likern** [comment]
> Some of examples showcasing `ScrollView` with `waitFor` feature are referencing string constants (are these ancient refs?) which are never mentioned anywhere in the repo.
> 
> ```
>  <ScrollViewComponent
>           ref={node => (this._scrollView = node)}
>           waitFor={['dragbox', 'image_pinch', 'image_rotation', 'image_tilt']}
> ...
> ```
> 
> https://github.com/software-mansion/react-native-gesture-handler/search?q=image_tilt&unscoped_q=image_tilt
> 
> it's very confusing where are these constants coming from? Trying to use real refs for waitFor are causing runtime crash #1016

I agree. Also this `ScrollViewComponent` can be React Native's ScrollView which doesn't have `waitFor` property.
```ts
export const ComboWithRNScroll = () => <Combo ScrollViewComponent={RNScroll} />;
```

If these examples could be rewritten using Reanimated V2 it's awesome.
It's difficult to understand  which ScrollView to use and how to combine them all together.

Right now we have `Animated.ScrollView` coming from **react-native-reanimated** v2. It is used for [useAnimatedScrollHandler](https://docs.swmansion.com/react-native-reanimated/docs/next/api/useAnimatedScrollHandler) and uses React Native ScrollView component internally, so lack of `waitFor` property.

Also we have `ScrollView` from `react-native-gesture-handler` and original React Native `ScrollView`.
How to combine them, for example when multiple gestures are used?

The **most common** scenario is to use _swipable rows inside scrolled container_.

**Comment by jakub-gonet** [comment]
I planned on rewriting examples and organizing the repo after we clean up issues a bit and fix some most important issues. Examples are a bit outdated and weren't changed for a long time. I think categorizing examples by the difficulty of implementation may be a better idea than keeping everything in the same place so we may look into that as well.
