### ISSUE TITLE
null is not an object ( evaluating 'RNGestureHandlerModule.default.Direction') 

### ISSUE THREAD

**Issue by felipe-ssilva** [software-mansion/react-native-gesture-handler#1021]
I'm having this issue in mac os / ios with react-nagivation and react-native-gesture-handler latest release. kindly help!

![image](https://user-images.githubusercontent.com/4562886/78189219-01823800-7448-11ea-98eb-3e29efb1141b.png)

**My package.json config:**
```javascript
{
  "name": "appfinance",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "@react-native-community/masked-view": "^0.1.7",
    "@react-navigation/native": "^5.1.4",
    "@react-navigation/stack": "^5.2.9",
    "react": "16.8.3",
    "react-native": "0.59.9",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-reanimated": "^1.7.1",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.4.0",
    "react-navigation": "^4.3.6"
  },
  "devDependencies": {
    "@babel/core": "^7.9.0",
    "@babel/runtime": "^7.9.2",
    "babel-jest": "^25.2.3",
    "jest": "^25.2.3",
    "metro-react-native-babel-preset": "^0.59.0",
    "react-test-renderer": "16.8.3"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

**Comment by amazingmarvin** [comment]
Searching the react-navigation docs, I found [this](https://reactnavigation.org/docs/troubleshooting/#im-getting-an-error-null-is-not-an-object-evaluating-rngesturehandlermoduledefaultdirection)

**Comment by felipe-ssilva** [comment]
Hi @amazingmarvin . Not working for me :/

**Comment by rahulnainwal107** [comment]
Have a look on that, it work's for me :
[https://software-mansion.github.io/react-native-gesture-handler/docs/getting-started.html](url)

**Comment by rakki-cbe** [comment]
I am stuck with same issue.
```

"dependencies": {
    "@react-native-community/masked-view": "^0.1.9",
    "@react-navigation/native": "^5.1.5",
    "@react-navigation/stack": "^5.2.10",
    "base-64": "^0.1.0",
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-reanimated": "^1.8.0",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.4.0"
  }
```

Its working fine with react native app which is using ReactActivity(From scratch app ) 
but its not working with existing application which using ReactRootView and  ReactInstanceManager instance in activity 

OS: Android

**Comment by felipe-ssilva** [comment]
Hi @rahulnainwal107 . Thanks, but not working for me :/

**Comment by ilkka-es** [comment]
I opened and built the project in xcode, that fixed this error for me.

**Comment by amit00978** [comment]
Doing Pod Install and Restart the Xcode works for me.

**Comment by martinappberg** [comment]
Hi I am still getting this error. Pod install and restart of Xcode does not work.

**Comment by amit00978** [comment]
And also install react-native-gesture-handler and react-native link for the android.

**Comment by KevinFrazier** [comment]
Having this same issue for Windows on Android on version 0.62.0-0. Tried the following and has not worked:

1) unlinking react-native-gesture-handler
2) rm -rf node_modules && npm install && react-native run-android --reset-cache

**Comment by jakub-gonet** [comment]
Duplicate of #494.

**Comment by Wajahat049** [comment]
I have the same issue 
I ran command
npm i react-native-gesture-handler
and then it works

**Comment by soheil06791** [comment]
for solve this problem in android:
after create new project in react native go to:

**android/gradle/wrapper**

change **distributionUrl** in **gradle-wrapper.properties** to:

https\://services.gradle.org/distributions/gradle-6.0.1-all.zip

next react-native run-android

 my react-native detail:

**"@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/native": "^5.9.2",
    "@react-navigation/stack": "^5.14.2",
    "react": "16.13.1",
    "react-native": "0.63.4",
    "react-native-gesture-handler": "^1.9.0",
    "react-native-reanimated": "^1.13.2",
    "react-native-safe-area-context": "^3.1.9",
    "react-native-screens": "^2.17.1"**

**Comment by jakub-gonet** [comment]
Locking due to spam. If you still experience this problem, please open a new issue and provide a minimal repro.
