### ISSUE TITLE
PanGesture Not working. Error

### ISSUE THREAD

**Issue by Only-IceSoul** [software-mansion/react-native-gesture-handler#1025]
Error: Expected 'onGestureHandlerEvent' listener to be a function,  instead got a value of  object type.

i am using the same code from here: https://software-mansion.github.io/react-native-gesture-handler/docs/handler-pan.html

**Comment by Only-IceSoul** [comment]
not working with event.

**Comment by timbrandin** [comment]
I'm also getting this! version 1.6.1

**Comment by 8ui** [comment]
Use Animated.View component

**Comment by jakub-gonet** [comment]
Please provide a code example which is crashing.

Closing until more info is given.
