### ISSUE TITLE
Directional pinch

### ISSUE THREAD

**Issue by stevenmathers** [software-mansion/react-native-gesture-handler#1026]
Hi, Is there a way to get the direction of a pinch?

use case is being able to scale the XY of a grid in either axis independently.

thanks

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
If you need further help please reply.

**Comment by pavelbabenko** [comment]
I have the same use case

**Comment by Pipe-Runner** [comment]
Check the code in this issue. I think this is a good example:
https://github.com/software-mansion/react-native-gesture-handler/issues/1894

@pavelbabenko 
@stevenmathers
