### ISSUE TITLE
Using BottomSheet example w/ Reanimated

### ISSUE THREAD

**Issue by rkrueger11** [software-mansion/react-native-gesture-handler#1027]
I'm having some trouble using reanimated with the bottom sheet example. I'd use the example in the reanimated doesn't allow for the content of the bottom sheet to scroll. 

It looks like certain methods aren't supported in reanimated, does this mean that this example can't be recreated using reanimated?

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
If you need further help please reply.
