### ISSUE TITLE
content is showing over the overlay color if elevation is given in android

### ISSUE THREAD

**Issue by vinaygoyal20** [software-mansion/react-native-gesture-handler#1029]
While using drawerLayout of react-native-gesture-handler if i am have content which need some elevation the content is shown over the overlay color.
![img](https://user-images.githubusercontent.com/26671420/79064538-4d926f80-7cc7-11ea-888c-d8c563810f66.jpeg)

**Comment by kkafar** [comment]
Hi @vinaygoyal20 
Can you provide code to reproduce this issue? (Github repo / Snack / code snippet)
