### ISSUE TITLE
How to close the Swipeable on the other side? 

### ISSUE THREAD

**Issue by kopax** [software-mansion/react-native-gesture-handler#1032]
Hello, following https://github.com/software-mansion/react-native-gesture-handler/issues/977 ,

I would like to achieve a swipeable that close from the opposite side.

So far, if I swipe left, it triger the add to favorite action and the swipeable will close from the same (left) side.

I want the `<Swipeable />` to reappear from the right side will closing, how can I achieve that?

**Comment by buchereli** [comment]
Use the same logic as the instant close I showed in #977 except rather than closing instantly move it to the opposite side. Then call the normal close function and it will animate a close from the opposite side.

**Comment by kopax** [comment]
That's what I was trying to do. I think I only need to know how I can guess the `dragX` position I need from that method. Thank you so much for helping. Did you write this Swiper? It's awesome.

**Comment by rananajam1** [comment]
> Hello, following #977 ,
> 
> I would like to achieve a swipeable that close from the opposite side.
> 
> So far, if I swipe left, it triger the add to favorite action and the swipeable will close from the same (left) side.
> 
> I want the `<Swipeable />` to reappear from the right side will closing, how can I achieve that?

Can you please help in explaining how the close works, Im trying to close a row on an event and so far no progress

**Comment by mMajch** [comment]
Try this:

`class MySwipeable extends Swipeable {
  closeInstantlyLeft = () => {
    const { onSwipeableWillClose, onSwipeableClose } = this.props;
    const { dragX, rowTranslation } = this.state;
    dragX.setValue(0);
    rowTranslation.setValue(0);
    this.setState({ rowState: Math.sign(0) });
    if (onSwipeableWillClose) {
      onSwipeableWillClose();
    }
    if (onSwipeableClose) {
      onSwipeableClose();
    }
  };
  closeInstantlyRight = () => {
    const { rowWidth } = this.state;
    this.setState({ rowState: Math.sign(rowWidth) });
    this.closeInstantlyLeft()
  };
}`

closeInstantlyLeft was provided in #977. Check closeInstantlyRight if you want to have the same effect from the other side

**Comment by kopax** [comment]
Hi and thanks @mMajch . I am the author of #977, the difference between this one is that I do not ask to close instantly, I want to have the animation that close.

In other words, I want to close the swipe left with the list item reapparing from the right side and performing the closing animation.  What do you mean by instantly closing right? To me, it can only close right with animation, or it can close instantly.

**Comment by mMajch** [comment]
@kopax Sorry, I think I misunderstood your question. I only know how to have this item reaparing from right side after the swipe is fully open and item is deleted. Is this what you need?
```
class MySwipeable extends Swipeable {
  closeRightActions = () => {
    const { rowWidth } = this.state;
    this.setState({ rowState: Math.sign(rowWidth || 0) });
    this.close()
  };
}
```
![swipe](https://user-images.githubusercontent.com/44026723/82204870-f2771c80-9905-11ea-8338-e50bf2b22a97.gif)

**Comment by kopax** [comment]
Not exactly, I have two action:

1. swipe left : remove the row
2. swipe right: add the row to favorite

When I swipe left, I expect the row to slide up and disappear from the list

When I swipe right, I expect to keep the row, and make it reappear from the opposite side instead of having it close from the same it got opened after being opened.

The effect you have looks like what I need, except your's is the row below.

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
If you need further help please reply.

**Comment by kopax** [comment]
Hello @jakub-gonet , I was not able to fix this on my end. If you know how I can edit the position so it close from the opposite side, I would be glad, thanks for asking.
