### ISSUE TITLE
Move towards React host refs instead of findNodeHandle for compatibility react-native-web@next

### ISSUE THREAD

**Issue by jfrolich** [software-mansion/react-native-gesture-handler#1036]
`findNodeHandle` should not be used anymore and recently it breaks compatibility with new builds of `react-native-web`. I also think this will enable `react-native-reanimated` to be compatible with function components, so that would be nice!

See here for more info: https://github.com/necolas/react-native-web/issues/1219#issuecomment-614395504

Related: https://github.com/software-mansion/react-native-reanimated/issues/738

**Comment by jfrolich** [comment]
It seems not to be fixed yet. In the mean time react-native-web has reached a new stable version.

**Comment by WoLewicki** [comment]
Looking at the code here: https://github.com/software-mansion/react-native-gesture-handler/blob/2ae0c2079a3c81d0b3d3a3c2303973e8ee0c2353/src/handlers/gestureHandlerCommon.ts#L180 it seems like it is now handled on web. I will close this issue then. Feel free to comment if something is wrong and we can always reopen it.
