### ISSUE TITLE
Module not found: Can't resolve 'fbjs/lib/areEqual' in 'node_modules\react-native-gesture-handler'

### ISSUE THREAD

**Issue by pramish22** [software-mansion/react-native-gesture-handler#1040]
![image](https://user-images.githubusercontent.com/31245053/79685965-41278d00-825a-11ea-9db9-2a87663e429a.png)
Module not found: Can't resolve 'fbjs/lib/areEqual' in 'C:\Users\Pramish\node_modules\react-native-gesture-handler'

**Comment by MrRhodes** [comment]
Why was this closed?

**Comment by jakub-gonet** [comment]
@MrRhodes if you're affected by this try running `yarn run fbjs` and see if that helps. I see we don't have any direct dependency on fbjs, so it may be not installed.

**Comment by Macilias** [comment]
> @MrRhodes if you're affected by this try running `yarn run fbjs` and see if that helps. I see we don't have any direct dependency on fbjs, so it may be not installed.

yarn run fbjs
yarn run v1.22.15
error Command "fbjs" not found.

**Comment by jakub-gonet** [comment]
@Macilias, this should be `yarn add fbjs`, I mistyped it. It was fixed since gesture handler [1.9.0](https://github.com/software-mansion/react-native-gesture-handler/releases/tag/1.9.0) so consider upgrading.
