### ISSUE TITLE
Website Docs is Not updated 

### ISSUE THREAD

**Issue by yjose** [software-mansion/react-native-gesture-handler#1041]
Hey 👋.
I am Trying To help My friend To setup a react-native-gesture-handler for a.new project and Noticed that the website is not updated with the last `docs` folder version. 
Example :
Getting started Page:  https://software-mansion.github.io/react-native-gesture-handler/docs/getting-started.html

Getting Started from `docs` folder:  https://github.com/software-mansion/react-native-gesture-handler/blob/master/docs/getting-started.md 

You can check the linking section is Not the same.

**Comment by jakub-gonet** [comment]
Thanks for the report, after #1115 those should be always in sync
