### ISSUE TITLE
How to make TapGestureHandler work correctly in functional components?

### ISSUE THREAD

**Issue by jonwu** [software-mansion/react-native-gesture-handler#1045]
I have this very simple tap listener for:
- single tap
- double tap

written in functional component. 
```
const PressBox = () => {
  const doubleTapRef = React.createRef();

  const _onSingleTap = (event) => {
    if (event.nativeEvent.state === State.ACTIVE) {
      alert("I'm touched");
    }
  };
  const _onDoubleTap = (event) => {
    if (event.nativeEvent.state === State.ACTIVE) {
      alert('D0able tap, good job!');
    }
  };

  return (
    <TapGestureHandler onHandlerStateChange={_onSingleTap} waitFor={doubleTapRef}>
      <TapGestureHandler ref={doubleTapRef} onHandlerStateChange={_onDoubleTap} numberOfTaps={2}>
        <View style={styles.box} />
      </TapGestureHandler>
    </TapGestureHandler>
  );
};
```

Problem
---
Double-tap never gets fired. Only single taps

Expected
---
`_onDoubleTap` to fire on double tap

**Comment by ChronSyn** [comment]
For anyone who ends up here looking for a solution, `React.useRef()` hook is needed instead of `React.createRef()`;

```
import React, { useRef } from "react";
import { TapGestureHandler, State } from "react-native-gesture-handler";
import { View, Text } from "react-native";

export const PressBox = () => {
  const doubleTapRef = useRef(null)
  const _onSingleTap = (event) => {
    if (event.nativeEvent.state === State.ACTIVE) {
      alert("Hey");
    }
  };

  const _onDoubleTap = (event) => {
    if (event.nativeEvent.state === State.ACTIVE) {
      alert("Hey dbl");
    }
  }
  
  return (
    <TapGestureHandler
      onHandlerStateChange={_onSingleTap}
      waitFor={doubleTapRef}>
      <TapGestureHandler ref={doubleTapRef} onHandlerStateChange={_onDoubleTap} numberOfTaps={2}>
        <View style={{ width: 100, height: 100, backgroundColor: "red" }}>
          <Text>HEY!</Text>
        </View>
      </TapGestureHandler>
    </TapGestureHandler>
  );
}
```

**Comment by solominh** [comment]
react-native-gesture-handler: v1.10.0 
Project examples are not working on iOS devices (just tested on iOS simulator) and not working on Snack as well

**Comment by timurridjanovic** [comment]
For some reason it only works the first time for me.. The second time, the first TapGestureHandler doesn't wait for the double tap..

**Comment by timurridjanovic** [comment]
Made it work.. I had to abstract out all the logic into its own separate component.. That made it work.

**Comment by Souvik4444** [comment]
@timurridjanovic can you please share the code?

**Comment by Souvik4444** [comment]
I have done like this but singletap,doubletap both not working

import React,{useState,useRef} from 'react';
import {View, StyleSheet,Text} from 'react-native';
import { TapGestureHandler, State } from 'react-native-gesture-handler';

const Blank = () => {
  const doubleTapRef = useRef(null)
  const _onSingleTap = (event) => {
    if (event.nativeEvent.state === State.ACTIVE) {
      alert("Hey");
    }
  };

  const _onDoubleTap = (event) => {
    if (event.nativeEvent.state === State.ACTIVE) {
      alert("Hey dbl");
    }
  }
  
  return (
    <TapGestureHandler
      onHandlerStateChange={_onSingleTap}
      waitFor={doubleTapRef}>
      <TapGestureHandler ref={doubleTapRef} onHandlerStateChange={_onDoubleTap} numberOfTaps={2}>
        <View style={{ width: 100, height: 100, backgroundColor: "red" }}>
          <Text>HEY!</Text>
        </View>
      </TapGestureHandler>
    </TapGestureHandler>
  );
}

export default Blank;

**Comment by footios** [comment]
This is not working!

`"react-native-gesture-handler": "~2.2.1"`

```js
import React, { useRef } from "react";
import { StyleSheet, View, Dimensions } from "react-native";
import { TapGestureHandler } from "react-native-gesture-handler";
import Animated from "react-native-reanimated";

export default function L5DoubleTap() {
  const doubleTapRef = useRef();

  return (
    <View style={styles.container}>
      <TapGestureHandler
        waitFor={doubleTapRef}
        onActivated={() => {
          console.log("SINGLE TAP");
        }}
      >
        <TapGestureHandler
          maxDelayMs={250}
          ref={doubleTapRef}
          numberOfTaps={2}
          onActivated={() => {
            console.log("DOUBLE TAP");
          }}
        >
          <Animated.View
            style={{ width: 100, height: 100, backgroundColor: "red" }}
          />
        </TapGestureHandler>
      </TapGestureHandler>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center"
  }
});
```

**Comment by AmirSedaqat** [comment]
@footios  

Hi, I hope your problem is solved by now, if not, you should not use `View`, use `**GestureHandlerRootView** ` instead.

**Comment by atultiwaree** [comment]
> For anyone who ends up here looking for a solution, `React.useRef()` hook is needed instead of `React.createRef()`;
> 
> ```
> import React, { useRef } from "react";
> import { TapGestureHandler, State } from "react-native-gesture-handler";
> import { View, Text } from "react-native";
> 
> export const PressBox = () => {
>   const doubleTapRef = useRef(null)
>   const _onSingleTap = (event) => {
>     if (event.nativeEvent.state === State.ACTIVE) {
>       alert("Hey");
>     }
>   };
> 
>   const _onDoubleTap = (event) => {
>     if (event.nativeEvent.state === State.ACTIVE) {
>       alert("Hey dbl");
>     }
>   }
>   
>   return (
>     <TapGestureHandler
>       onHandlerStateChange={_onSingleTap}
>       waitFor={doubleTapRef}>
>       <TapGestureHandler ref={doubleTapRef} onHandlerStateChange={_onDoubleTap} numberOfTaps={2}>
>         <View style={{ width: 100, height: 100, backgroundColor: "red" }}>
>           <Text>HEY!</Text>
>         </View>
>       </TapGestureHandler>
>     </TapGestureHandler>
>   );
> }
> ```

I'm new to re animated please help me to understand, How's is this working ?
