### ISSUE TITLE
waitFor taps on web only works if the components overlap

### ISSUE THREAD

**Issue by miracle2k** [software-mansion/react-native-gesture-handler#1047]
See this example:

https://snack.expo.io/7ZTv9L6CR

You can click on either the orange area or the background on Android. You can no longer click on the background on web, presumably because it is waiting for a "rejected" message from that child handler which never arrives.

**Comment by miracle2k** [comment]
I note that the default behaviour on mobile seems to be that only one of the handlers triggers, even if `waitFor` is not used. This is not the case on the web, where both handlers trigger.

**Comment by Warus15** [comment]
Hi, this issue should be fixed in [2.6.1](https://github.com/software-mansion/react-native-gesture-handler/releases/tag/2.6.1).

Note that this change is available in new web implementation. To enable it, call `enableExperimentalWebImplementation()` in the root of your project

**Comment by j-piasecki** [comment]
I'll close the issue since the new web implementation is enabled by default starting with 2.10.0.
