### ISSUE TITLE
onHandlerStateChange never fired

### ISSUE THREAD

**Issue by Dellybro** [software-mansion/react-native-gesture-handler#1050]
I can't seem to get my onHandlerStateChange to fire

My code is the following

```
onZoomEvent = Animated.event(
        [{ nativeEvent: { scale: this.scale } }],
        { useNativeDriver: true }
    )
  
    onZoomStateChange = event => {
        console.log("Pincher", this.pincher);
        console.log("On zoom state change", event);
        if (event.nativeEvent.oldState === State.ACTIVE) {
            Animated.spring(this.scale, {
                toValue: 1,
                useNativeDriver: true
            }).start()
        }
    };

render() {
       const { style = {}, dimensions = {height: 0, width: 0}, media, ...rest } = this.props;

        const { width } = Dimensions.get('window');
        const containerWidth = width - (PagePadding * 2);
        const sizeStyles = { ...dimensions };
        if (dimensions.width > 0 && dimensions.height > 0) {
            const aspectRatio = containerWidth / dimensions.width;
            sizeStyles.width = containerWidth;
            sizeStyles.height = dimensions.height * aspectRatio;
        }

        dimensions.width = limitNumberWithinRange(dimensions.width||0, 320, 1080);
        dimensions.height = limitNumberWithinRange(dimensions.height||0, 750, 1350);
        
    return (
            <PinchGestureHandler
                ref={el => this.pincher = el}
                onGestureEvent={this.onZoomEvent}
                onHandlerStateChange={this.onZoomStateChange}
            >
                <AnimatedFastImage
                    style={[styles.image, sizeStyles, style, {                    
                        transform: [{ scale: this.scale }]
                    }]}
                    source={media}
                    {...rest}
                />
            </PinchGestureHandler>
        );
}
```

Here is my react native info
System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
    Memory: 231.28 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 11.4.0 - ~/.nvm/versions/node/v11.4.0/bin/node
    npm: 6.4.1 - ~/.nvm/versions/node/v11.4.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.4 => 0.61.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1

**Comment by jakub-gonet** [comment]
Could you please provide a small working example? Small snippets of code are fine for reading but don't really help with debugging the issue.

Closing until reproducible snippet is provided.
