### ISSUE TITLE
macOS support?

### ISSUE THREAD

**Issue by mgcrea** [software-mansion/react-native-gesture-handler#1052]
Since the macOS support for react-native looks like to be around the corner thanks to the [microsoft fork](https://github.com/microsoft/react-native), do you have any plans to add support to a macOS target?

Looks like the `<UIKit>` dep might be the biggest problem, there is a cross-platform [RCTUIKit](https://github.com/microsoft/react-native/blob/master/React/Base/RCTUIKit.h) used by the fork but some imports like `#import <UIKit/UIGestureRecognizerSubclass.h>` might be a bit more problematic.

**Comment by 0xmtn** [comment]
+1 on this. Are you planning to add macOS support in the near future?

**Comment by jakub-gonet** [comment]
We're not planning to support it in the near future, mostly because our team is too small to prioritize it.

However, we are happy to merge PR making RNGH work with `react-native-macos`
