### ISSUE TITLE
Is there any way to detect multiple fingers' coordinates?

### ISSUE THREAD

**Issue by nenjamin2405** [software-mansion/react-native-gesture-handler#1054]
Hi guys, I really appreciate your efforts in this library. I just want to ask is there any way for me to detect multiple fingers' coordinates when I tap on the device. Something like an array, for example, I tap 1 finger on the screen, the array will be `[[123,345]]`, then I use another finger to tap on the screen (now 2 fingers on the screen), the array will become `[[123,456], [345,234]]`, and when I move those 2 fingers, their coordinates are reflected correspondingly.

Currently, I only see this library supports us to get the `numberOfPointers` and `x,y` of one finger via `onHandlerStateChange`

**Comment by softgenicsShubham** [comment]
Hey, I also wanted to know about this. Could you explain it here?
