### ISSUE TITLE
Missing submodule 'React.React.RCTConvert'

### ISSUE THREAD

**Issue by desinl** [software-mansion/react-native-gesture-handler#1057]
Folks - newbie alert!
I wanted to upgrade react-native-navigation which triggered a dependency of RNGestureHandler. However, it does not compile. The project compiles and runs well if I don't use RNGestureHandler. 

```Missing submodule 'React.React.RCTConvert'```

Am I running into a compatibility issue? or perhaps some setting in Xcode? 

Shout out to all you experienced folks. Please help.

RNGestureHandler: 1.3.0
RN: 0.59.10

**Comment by jakub-gonet** [comment]
Please provide some repro example, we cannot take action without more info.

Closing until more info is given.
