### ISSUE TITLE
DrawerLayout always shows as open on system recents screen

### ISSUE THREAD

**Issue by Sergeeeek** [software-mansion/react-native-gesture-handler#1058]
On android when I open the recents screen, the app flickers and starts displaying the DrawerLayout menu, even though it was closed.

~~This bug affects versions 1.6.0 and 1.6.1. **Downgrading to 1.5.6 fixes the issue**, so I'm using that as a workaround for now.~~

~~I'm guessing the bug was introduced by #937, but not familiar enough with this library to confirm.~~

Edit: Never mind, it reproduces on 1.5.6 too...

**Comment by Sergeeeek** [comment]
Tracking down the issue slowly, I think it's related to `onLayout` triggering when you open the recents screen.

BTW, I'm using DrawerLayout on the right side, if that makes any difference

**Comment by systemride** [comment]
I'm able to repro this on the left side as well.

Note: for me this occurs only when I have drawerType set to "front".

**Comment by jakub-gonet** [comment]
Could you provide some gif and code example reproducing this issue?

**Comment by Sergeeeek** [comment]
Sorry, I removed the `DrawerLayout` from the project for now because of this issue and don't have time to repro it again.

From my findings I think it could be caused by some bug in React Native Animated and how it handles native surfaces, because no changes to the `DrawerLayout` js code seemed to help this issue.

**Comment by YangJonghun** [comment]
please repro with below conditions
- Android under API under 29 (Android 7~9)
- multi window
- focus other app
(it also occured in simulator too)

I guess the reason of API 29+ couldn't repro this issue is below
https://developer.android.com/about/versions/10/behavior-changes-10#foldables

**Comment by j-piasecki** [comment]
Hi! I couldn't reproduce this issue, but it looks very similarly to https://github.com/software-mansion/react-native-gesture-handler/issues/386. There is a chance that it will be fixed by https://github.com/software-mansion/react-native-gesture-handler/pull/2005.

**Comment by j-piasecki** [comment]
https://github.com/software-mansion/react-native-gesture-handler/pull/2005 is included in Gesture Handler 2.4.2.
