### ISSUE TITLE
RectButton ripple doesn't fill space when there are buttons of different sizes

### ISSUE THREAD

**Issue by matt-dalton** [software-mansion/react-native-gesture-handler#1059]
I have a list of Touchable items that I want to use `RectButton` for. They each contain text, which can fill multiple lines. Each item is therefore a different height.

Here is some minimal code for the Touchable component:

```
const TestTouch = ({ text }) => (
    <RectButton>
        <View accessible>
            <Text style={{ borderTopWidth: 1, borderTopColor: 'black' }}>{text}</Text>
        </View>
    </RectButton>
)
```

This works (i.e. the ripple fills the height):
```
<TestTouch text="dfbhjdbhbhdhbd dhjbhjvd jhdbcbhd jkbbv bjv dsbdvkv dvbdbdv kd" />
```

But this doesn't:
```
<TestTouch text="dfbhjdbhbhdhbd dhjbhjvd jhdbcbhd" />
<TestTouch text="dfbhjdbhbhdhbd dhjbhjvd jhdbcbhd" />
<TestTouch text="dfbhjdbhbhdhbd dhjbhjvd " />
<TestTouch text="dfbhjdbhbhdhbd dhjbhjvd jhdbcbhd" />
<TestTouch text="dfbhjdbhbhdhbd dhjbhjvd jhdbcbhd jkbbv bjv dsbdvkv dvbdbdv kd" />
<TestTouch text="dfbhjdbhbhdhbd dhjbhjvd jhdbcbhd cbjkdv dvb dkbjv djkbv sbd vkjdvskvd vvd " />
<TestTouch text="dfbhjdbhbhdhbd dhjbhjvd jhdbcbhd" />
```
In this case, when I press on the 2 line buttons, the ripple doesn't fill the space:
![image](https://user-images.githubusercontent.com/22496337/80821609-f9e1ba80-8bd0-11ea-8ff1-345f23b723d1.png)

Is there a workaround for this? Or am I doing something wrong?

**Comment by alexfov** [comment]
I had the same issue when border radius was set to rectbutton. Removing border radius on every rectbutton component solved the issue

**Comment by kkafar** [comment]
Hi @matt-dalton!
I've tried to reproduce your issue on latest `gesture-handler` version and it works perfectly fine for me. Can you please upgrade `gesture-handler` / confirm that this issue disappeared?
