### ISSUE TITLE
Swipeable row on web does crazy jump when scrolling

### ISSUE THREAD

**Issue by kopax** [software-mansion/react-native-gesture-handler#1064]
Using Swipeable components, I see my web application going crazy when I try not to swipe but to scroll down or up.

Touching the row cause the row to swipe even if I do a scroll down gesture.

Is there a way to prevent swipe when scrolling?

**Comment by kopax** [comment]
Any tought? It seems to be related to https://github.com/software-mansion/react-native-gesture-handler/issues/591 which seems to have a solution but is not explained anywhere.

While I scroll down on the list, the scroll down action is interfering with the swipeable causing all my swipeable rows to be touched and it look really bad for the end user.

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
If you need further help please reply.

**Comment by kartegi** [comment]
You have to use Flatlist or Swipeable provided by react-native-gesture-handler, in case if someone else will have the same issue
