### ISSUE TITLE
Documentation on animated input ranges?

### ISSUE THREAD

**Issue by vicary** [software-mansion/react-native-gesture-handler#1065]
In `Swipeable`, `renderLeftActions` and `renderRightActions` takes two arguments of `Animated.Interpolation`.

We would like to add some bouncing effect in the middle of dragging, but [the document](https://software-mansion.github.io/react-native-gesture-handler/docs/component-swipeable.html#renderrightactions) lacks exact behaviours.

Is it possible to add some description of how the animated values are applied on dragging open and close?

**Comment by jakub-gonet** [comment]
Could you please describe this better? I don't really see what do you want to achieve. You can provide your own `renderLeftActions` that will take start and end position of Swipeable, so you can provide your own animation.

Closing until more info is given.

**Comment by kovkev** [comment]
I don't understand AnimatedInterpolation objects. What do they contain? Can we get a summary of the class?

**Comment by vicary** [comment]
@kovkev Thanks for bringing this up again, I must be somehow missed the reply.

@jakub-gonet I was trying to understand what can be achieved, the following terms could really use a more extensive description on how they works.

For example `renderLeftActions`,
1. AnimatedValue: [startValue, endValue]
2. progressAnimatedValue: [0, 1]
3. dragAnimatedValue: [0, +]

The same question applies to `renderRightActions`,
1. AnimatedValue: [startValue, endValue]
2. progressAnimatedValue: [0, 1]
3. dragAnimatedValue: [0, -]
