### ISSUE TITLE
PanGestureHandler seem to be sharing state somehow, using multiple ones breaks once you start moving the other one ?

### ISSUE THREAD

**Issue by a-eid** [software-mansion/react-native-gesture-handler#1066]
Reproducible example:

https://snack.expo.io/@aeid/6d9488

for some reason it seem that changing one pangesture `translationXY` changes other PanGestures `translationXY`, 

TBH, I'm not sure if this a `reanimated` issue, they currently have a `diffClamp` issue which is related to sharing state as well.

**Comment by reggie3** [comment]
@a-eid Were you able to figure out a workaround for this problem.  I am running into the same issue.
