### ISSUE TITLE
transpile files for web 

### ISSUE THREAD

**Issue by alidlorenzo** [software-mansion/react-native-gesture-handler#1073]
ref: https://github.com/react-navigation/react-navigation/issues/8319

I'm trying to use react-native-gesture-handler in a Clojurescript web project, the issue I'm having is that rngh does not transpile its files and so it causes compile errors, and there's clojurescript build tool does not provide way to do it (it expects js libraries to be transpiled).

It'd be great if you could use a tool like [Bob](https://github.com/react-native-community/bob/issues?q=watch) to build for different platforms/targets.

**Comment by dalcib** [comment]
New and faster bundlers/compilers as [esbuild](https://github.com/evanw/esbuild) and [swc](https://github.com/swc-project/swc) don't have support for ```flow```, which makes it really hard to use this library on the web with these compilers/bundlers.
So, it would be nice if transpired files could be made available.

**Comment by dalcib** [comment]
In the case of someone else is needing the transpile files for this package, I published it on [react-native-gesture-handler-compiled/](https://github.com/dalcib/react-native-gesture-handler-compiled.git)

It is compiled using [@react-native-community/bob](https://github.com/react-native-community/bob), following react-navigation/react-navigation#8319

**Comment by jakub-gonet** [comment]
Fixed in #1360.
