### ISSUE TITLE
Android 'react-native-gesture-handler'

### ISSUE THREAD

**Issue by MuhammadAhmed1994** [software-mansion/react-native-gesture-handler#1079]
Getting this Error only in android.
**Library versions:**

   "react-native": "^0.61.1",
   "react-native-gesture-handler": "1.3.0",

<img width="354" alt="Screen Shot 2020-05-21 at 9 12 30 PM" src="https://user-images.githubusercontent.com/21235727/83521214-5a2d8a00-a4f8-11ea-8f37-d2a25253ce56.png">

**Comment by jakub-gonet** [comment]
Hi, could you provide some small repro for this error?

**Comment by MuhammadAhmed1994** [comment]
@jakub-gonet Issue is fixed. I have updated the react-native version to the latest.
