### ISSUE TITLE
fails with react-native-windows, cannot read property Direction of undefined

### ISSUE THREAD

**Issue by teclone** [software-mansion/react-native-gesture-handler#1081]
Hello, Excellent work by the team.

Please forgive me if my issue is not clear enough or does not follow the standard. I will provide further information if need be. Thanks in advance.

Here is my problem, I am running into this error message while trying out [react-native-windows](https://github.com/microsoft/react-native-windows) on a project.

I followed the instructions on the [react navigation webiste](https://reactnavigation.org/docs/getting-started) to get this installed on a bare react native project. All works well for android, but whenever I run `npx react-native run-windows` on windows, I get the following error message:

```
TypeError: Cannot read property 'Direction' of undefined
```

Project dependencies
```
"react": "16.11.0",
  "react-native": "0.62.0-0",
    "react-native-gesture-handler": "1.6.1",
    "react-native-reanimated": "1.9.0",
    "react-native-rss-parser": "1.4.0",
    "react-native-safe-area-context": "3.0.2",
    "react-native-screens": "2.8.0",
    "react-native-sqlite-2": "3.0.1",
    "react-native-webview": "10.2.3",
    "react-native-windows": "0.62.0-0"
```

**Comment by exotexot** [comment]
Having the same isssue. Its problematic as this package is part of react-navigation. :(

**Comment by adrien-prototype** [comment]
Yes, same here :( 

React-navigation says : 
```
To finalize installation of react-native-gesture-handler, add the following at the top (make sure it's at the top and there's nothing else before it) of your entry file, such as index.js or App.js:

import 'react-native-gesture-handler';
```
But this import brings "Direction of undefined" error every time. Didn't figure out why yet.

**Comment by willerpp** [comment]
I had the same problem, any solution at all?

**Comment by josesanchis16** [comment]
same problem here

**Comment by BrayanIribe** [comment]
Can confirm, same problem here.

**Comment by mnhthng-thms** [comment]
This issue is related to #494 and #1021. You should refer to them.

**Comment by BrayanIribe** [comment]
> This issue is related to #494 and #1021. You should refer to them.

**fails with react-native-windows**.

**Comment by mnhthng-thms** [comment]
@BrayanIribe both issues occurred because the packages we add into our project try to import from `NativeModules.Direction` of `react-native`, which doesn't exist.

**Comment by safadl** [comment]
Same issue!!!

**Comment by mnhthng-thms** [comment]
The official documentation at [this link](https://docs.swmansion.com/react-native-gesture-handler/docs/next/#bare-react-native) states that we have to use bare or managed workflow provided by `expo-cli` to install modules that `react-native-gesture-handler` needs. Personally I've not had enough experience with native code, so I have to stick with Expo for a while!

**Comment by Hawiie13** [comment]
try this use the web stubs
https://github.com/software-mansion/react-native-gesture-handler/issues/382#issuecomment-495018322
I have working navigation stack 

![image](https://user-images.githubusercontent.com/6790102/88742883-eb765100-d175-11ea-95cd-9aa8a5fd394e.png)
![image](https://user-images.githubusercontent.com/6790102/88742923-08128900-d176-11ea-8e51-59b2873be734.png)

Output:
![rnw-practice-2020-07-29-08-40-24](https://user-images.githubusercontent.com/6790102/88743808-36916380-d178-11ea-9493-da6ec5407913.gif)

**Comment by khanzzirfan** [comment]
The above recommendation works.. but still there are few more things to fix.  Here is my setup all together. 
```
"dependencies": {
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/netinfo": "5.5.1",
    "@react-native-community/toolbar-android": "^0.1.0-rc.2",   
    "prop-types": "^15.7.2",
    "react": "16.11.0",
    "react-native": "^0.62.0-0",
    "react-native-gesture-handler": "1.3.0",
    "react-native-reanimated": "^1.13.0",
    "react-native-safe-area-context": "^3.1.8",
    "react-native-screens": "^2.11.0",
    "react-native-vector-icons": "^7.1.0",
    "react-native-windows": "^0.62.0-0",
    "react-navigation": "3.5.1"
  },
```
update all four files mentioned above @Hawiie13 
Also updated react-native-safe-area-view -> index.web.js to index.windows.js.

**Comment by mrKorg** [comment]
I have the same issue with react-native.
`import "react-native-gesture-handler"` create error "Cannot read property Direction of undefined"

**Comment by capc0** [comment]
Someone has a working setup with latest version? package changed to ```@react-navigation/native```

**Comment by creambyemute** [comment]
@capc0 Yeah I just got it working. Follow the above comments of @Hawiie13 and @khanzzirfan .
I forked the repo and put the changes there for the moment (we're setting up RN-Windows): https://github.com/wwimmo/react-native-gesture-handler.

I was able to successfully load up our LoginScreen with the above changes.

**Comment by stmoy** [comment]
CC: @JonThysell @chrisglein

**Comment by davidwico** [comment]
same issue with react-native

**Comment by stereodenis** [comment]
same issue with 1.10.1
