### ISSUE TITLE
PinchHandler not working on Android in conjunction with scrollview/flatlist

### ISSUE THREAD

**Issue by stevenmathers** [software-mansion/react-native-gesture-handler#1082]
I am using RNGH 1.6.1  and RN 0.62.2

I am trying to use the PinchGestureHandler for my react native project.  I need a pinch for a scrollview/flatlist.
I have done the simplest test implementation, wrapping the flatlist, and connecting the event listeners to a console.log so I can observe the state changes in the handler as I make the gesture

On IOS this works fine.

On Android, I can see the gesture enter the BEGAN state but 95% of the time it then CANCELS.  Only very rarely, with infinite care with my gesture, can I get the pinch state to become ACTIVE.

From my observations, if the scrollview moves at all, it causes the cancel.  So it seems to me that the scrollview is receiving the gesture events simultaneously as the pinch handler, and recognising a scroll most of the time, resulting in the pinch getting cancelled.  on IOS, with the same code, its fine - the scrollview does not scroll while the pinch handler is interested in the gesture. 

I do not have two gesture handlers active, which would cause this according to your documentation.  Just a flatlist.  Something wrong with android impl?

**Comment by stevenmathers** [comment]
I could have this backwards.  It may be that the gesture handler simply gives up on the pinch in far, far too an unfogiving manner, thus the events are then being given to the scrollbar, that then scrolls.  Im not sure.  All I know is that its almost impossible for the pinch gesture to be recognized successfully.

**Comment by stevenmathers** [comment]
Lastly, I can confirm if I change the wrapped scrollView to a simple view, I see the expected behaviour - the pinch handler enters ACTIVE state and leaves as I would expect.

**Comment by ShaMan123** [comment]
#1034

**Comment by jakub-gonet** [comment]
Try using `simultaniousHandlers` after applying the #1034 patch – it should work.
If it's not, please post the repro code and we'll try to fix it.
