### ISSUE TITLE
Swipeable is making the deleted row 'close' the swipe

### ISSUE THREAD

**Issue by CyberMew** [software-mansion/react-native-gesture-handler#1092]
Run it here https://snack.expo.io/@cybermew/swipetodelete-layoutanimation

as seen in the snack, when swiping, the 'open' row with the delete button closes by itself. I don't think that is suppose to happen?

**Comment by jakub-gonet** [comment]
Unfortunately, I can't repro this one. Some time has passed, so if this is still a problem please reply or open a new issue.


https://user-images.githubusercontent.com/12465392/108228198-ecd19000-713e-11eb-9a03-4af35762f7ea.mp4

**Comment by ucheNkadiCode** [comment]
This happens to me as well. It's still a problem.

When I delete from the array, I'm simply using Array.filter(item.id == idToDelete). 

What I am expecting is the specific card will get deleted and nothing else.

What I'm getting is the behavior below

https://user-images.githubusercontent.com/20650058/192116222-e6eada44-33a2-4be6-8db3-0564df412c50.mov

@jakub-gonet would you mind reopening this?

**Comment by j-piasecki** [comment]
@ucheNkadiCode To clarify, the issue is that after deleting the topmost card, the next one runs the closing animation, right? If so, could you prepare a reproduction? It may be a repository with the app or a code snippet.
