### ISSUE TITLE
add hook for `isDragging` to Swipeable

### ISSUE THREAD

**Issue by chrisdrackett** [software-mansion/react-native-gesture-handler#1101]
right now its possible to tell when drag ends (`onSwipeableWillClose`) but there is no way to attach functionality to when dragging starts as far as I can tell. `onSwipeableWillOpen` is only called when opened programmatically, not when the user starts to drag the component

**Comment by jakub-gonet** [comment]
Resolved by #999.

**Comment by MoOx** [comment]
> onSwipeableWillOpen is only called when opened programmatically, not when the user starts to drag the component

Actually it's called when user finish the open gesture (release finger) and onSwipeableOpen is opened after the animation totally ended.
