### ISSUE TITLE
onGestureEvent not working on FlatList

### ISSUE THREAD

**Issue by neiker** [software-mansion/react-native-gesture-handler#1103]
I'm trying to get the gesture from a `FlatList` because I need the `translation.y` and not the `contentOffset.y` given by onScroll event. This is because I'm translating the `FlatList` and hiding the header as the user scrolls and using the offset provokes glitches ([video](https://drive.google.com/file/d/1xYRGUlbL85v1xvyeKP0NtCgS9c7aS30m/view?usp=sharing) and [source code](https://github.com/neiker/experiments/blob/master/src/twitter-header/index.tsx))

[Current FlatList types](https://github.com/software-mansion/react-native-gesture-handler/blob/master/react-native-gesture-handler.d.ts#L456)  says props can include `NativeViewGestureHandlerProperties`, this means `onGestureEvent` and `onHandlerStateChange` are available. So this is posible:
```tsx
import { FlatList } from "react-native-gesture-handler";

<FlatList
      onGestureEvent={() => console.log("onGestureEvent")}
      onHandlerStateChange={() => console.log("onHandlerStateChange")}
      keyExtractor={keyExtractor}
      data={data}
      renderItem={renderItem}
    />
```
The truth is neither onGestureEvent or onHandlerStateChange are called as you scroll. 

I'm using latest version of `react-native-gesture-handler` (v1.6.1) and this is my stack:

```  Expo CLI 3.21.12 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v12.14.1/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.12 
      react: ~16.9.0 => 16.9.0 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.21.12
```

**Comment by neiker** [comment]
To anyone reading this:

Is correct, types are wrong, `FlatList` by `react-native-gesture-handler` don't implements either `onHandlerStateChange`  nor `onGestureEvent`.

Anyway, you can wrap a `FlatList` (imported from `react-native`) using `PanGestureHandler` as described here:
https://github.com/software-mansion/react-native-gesture-handler/issues/492

```tsx
import { FlatList } from "react-native";
import {
  PanGestureHandler,
  NativeViewGestureHandler,
} from "react-native-gesture-handler";

<PanGestureHandler
  ref={panRef}
  simultaneousHandlers={listRef}
  onGestureEvent={gestureHandler}
>
  <NativeViewGestureHandler ref={listRef} simultaneousHandlers={panRef}>
    <FlatList
      keyExtractor={keyExtractor}
      data={data}
      renderItem={renderItem}
    />
  </NativeViewGestureHandler>
</PanGestureHandler>
```

**Comment by ShaMan123** [comment]
Did you try passing RNGH ScrollView via [`renderScrollComponent`](https://reactnative.dev/docs/virtualizedlist#renderscrollcomponent)  prop?

**Comment by MuhammadRafeh** [comment]
In PangestureHandler, onGestureEvent not called while we touch view. Can someone help me with it?
`class App extends React.Component {

  handleGesture = evt => {
    console.log('called')
    let {nativeEvent} = evt;
    console.log(nativeEvent)
  }

  render() {
    return(
      <View style={styles.container}>

        <PanGestureHandler onGestureEvent={this.handleGesture}>
          <View style={styles.circle}/>
        </PanGestureHandler>

        <Button title="asd" onPress={() => {console.log('asd')}}/>

      </View>
    );
  }
}`

**Comment by ArtemKosiakevych** [comment]
> To anyone reading this:
> 
> You can wrap a `FlatList` (imported from `react-native`) using `PanGestureHandler` as described here:
> #492
> 
> ```tsx
> import { FlatList } from "react-native";
> import {
>   PanGestureHandler,
>   NativeViewGestureHandler,
> } from "react-native-gesture-handler";
> 
> <PanGestureHandler
>   ref={panRef}
>   simultaneousHandlers={listRef}
>   onGestureEvent={gestureHandler}
> >
>   <NativeViewGestureHandler ref={listRef} simultaneousHandlers={panRef}>
>     <FlatList
>       keyExtractor={keyExtractor}
>       data={data}
>       renderItem={renderItem}
>     />
>   </NativeViewGestureHandler>
> </PanGestureHandler>
> ```
> 
> But, this issue stills valid. Types are wrong, `FlatList` by `react-native-gesture-handler` don't implements either `onHandlerStateChange` nor `onGestureEvent`.

Note that FlatList must be a child of NativeViewGestureHandler otherwise, it won't work

**Comment by hukpavlo** [comment]
@ArtemKosiakevych Thanks for your comment, works well now.

**Comment by kmagiera** [comment]
it seems like this issue was resolved. Also as per other suggestion the alternative would be to use [renderScrollComponent](https://reactnative.dev/docs/virtualizedlist#renderscrollcomponent) – FlatList is a virtual component that renders ScrollView under the hood and does not pass `onGestureEvent` et al. to it.

In case you still have problems with this one please respond with a comment, otherwise the issue will be closed automatically in a couple of weeks

**Comment by quangcao-offerup** [comment]
@kmagiera @ShaMan123  do you example of us renderScrollComponent?
 would love to see how that being done, I do see similar problem that it does not call onGestureEvent all the time when swipe vertically the scrollable flatlist that I think it might conflict with onScroll event of flatlist. and when setting scrollEnabled={false}, the pangesture work 100% of the time.

Package version: 
```
"react-native-gesture-handler": "1.10.3",
"react-native-reanimated": "2.3.1",
```
Here a snippet that also available here from a fork of reanimated-2-playground so that if you can play with that https://github.com/quangcao-offerup/reanimated-2-playground/blob/test/pangesture-nested-scrollable-flatlist/Screen.js#L87

````
<PanGestureHandler
        ref={panGestureHandlerRef}
        simultaneousHandlers={nativeViewGestureHandlerRef}
        onGestureEvent={gestureEventHandler}
        avgTouches
        minPointers={1}
        maxPointers={1}
        // failOffsetX={[-5, 5]}
        // activeOffsetX={[-10, 10]}
        // activeOffsetY={[-10, 10]}
        enabled>
        <Animated.View style={{flex: 1}} collapsable={false}>
          <NativeViewGestureHandler
            ref={nativeViewGestureHandlerRef}
            enabled
            simultaneousHandlers={panGestureHandlerRef}>
            <Animated.View style={{flex: 1}} collapsable={false}>
              <FlatList
                data={DATA}
                renderItem={renderItem}
                keyExtractor={(item) => item.id}
                bounces={false}
                // scrollEnabled={false}
              />
              {/* <ScrollView
                bounces={false}
                //scrollEnabled={false}
              >
                {DATA.map((item) => renderItem({item}))}
              </ScrollView> */}
            </Animated.View>
          </NativeViewGestureHandler>
        </Animated.View>
      </PanGestureHandler>
```

**Comment by j-piasecki** [comment]
@quangcao-offerup `FlatList` from `react-native-gesture-handler` already uses `renderScrollComponent` to insert `NativeViewGestureHandler` into the hierarchy and relevant props are passes to it. That being said, I've managed to get it to work using Gesture Handler 2.5.0. Here's the code:
```jsx
import Animated, {
  useSharedValue,
  useAnimatedStyle,
  useAnimatedGestureHandler,
} from 'react-native-reanimated';
import { SafeAreaView, StyleSheet, Text, View } from 'react-native';
import React from 'react';
import {
  GestureHandlerRootView,
  PanGestureHandler,
} from 'react-native-gesture-handler';
import { FlatList } from 'react-native-gesture-handler';

export default function AnimatedStyleUpdateExample(props) {
  const panGestureHandlerRef = React.useRef(null);
  const nativeViewGestureHandlerRef = React.useRef(null);

  const tracker = useSharedValue({ x: 0, y: 0 });

  const gestureEventHandler = useAnimatedGestureHandler(
    {
      onStart: (e) => {
        tracker.value = {
          x: e.absoluteX,
          y: e.absoluteY,
        };
        console.log('Onstart', e.translationX, e.translationY);
      },
      onActive: (e) => {
        tracker.value = {
          x: e.absoluteX,
          y: e.absoluteY,
        };

        console.log('onActive', e.translationX, e.translationY);
      },
      onCancel: () => {
        console.log('onCancel');
      },
      onEnd: (e) => {
        tracker.value = {
          x: 0,
          y: 0,
        };
        console.log('onEndTranslation', e.translationX, e.translationY);
      },
      onFail: (e) => {
        console.log('onFail', e);
      },
    },
    []
  );

  const animatedStyle = useAnimatedStyle(
    () => ({
      transform: [
        {
          translateX: tracker.value.x,
        },
        {
          translateY: tracker.value.y,
        },
      ],
    }),
    []
  );
  const trackerSize = 30;

  const DATA = [...Array(20)].map((u, i) => ({
    id: i,
    title: i,
  }));

  const Item = ({ title }) => (
    <View style={styles.item}>
      <Text style={styles.title}>{title}</Text>
    </View>
  );
  const renderItem = ({ item }) => <Item key={item.id} title={item.title} />;

  return (
    <SafeAreaView style={styles.container}>
      <GestureHandlerRootView style={{ flex: 1 }}>
        <PanGestureHandler
          ref={panGestureHandlerRef}
          simultaneousHandlers={nativeViewGestureHandlerRef}
          onGestureEvent={gestureEventHandler}
          avgTouches
          minPointers={1}
          maxPointers={1}
          enabled>
          <Animated.View style={{ flex: 1 }} collapsable={false}>
            <FlatList
              shouldActivateOnStart={true}
              simultaneousHandlers={panGestureHandlerRef}
              data={DATA}
              renderItem={renderItem}
              keyExtractor={(item) => item.id}
              bounces={false}
            />
          </Animated.View>
        </PanGestureHandler>

        <Animated.View
          style={[
            {
              width: trackerSize,
              height: trackerSize,
              borderRadius: trackerSize,
              position: 'absolute',
              backgroundColor: 'red',
              top: -trackerSize,
            },
            animatedStyle,
          ]}
        />
      </GestureHandlerRootView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    backgroundColor: 'white',
    flex: 1,
  },
  item: {
    backgroundColor: '#f9c2ff',
    padding: 20,
    marginVertical: 8,
    marginHorizontal: 16,
  },
  title: {
    fontSize: 32,
  },
});

```

**Comment by techgerm** [comment]
This saved me: https://github.com/software-mansion/react-native-gesture-handler/issues/1103#issuecomment-660695803

But with re-animated v3, it now looks a little different to implement it so here's an updated version in case it helps someone in the future:

In my case I was using a `SectionList` but the same applies for `FlatList` or `ScrollView`

```typescript
const nativeSectionScrollPan = Gesture.Native();

const pan = Gesture.Pan()
    .simultaneousWithExternalGesture(nativeSectionScrollPan)
    .onUpdate((event) => {
      ...
    })
    .onEnd(() => {
      ...
    });

return (
    <GestureDetector gesture={pan}>
      <GestureDetector gesture={nativeSectionScrollPan}>
        <SectionList
          ...
        />
      </GestureDetector>
    </GestureDetector>
  );

```
