### ISSUE TITLE
[IOS] Gesture Touchables don't clicks under layout

### ISSUE THREAD

**Issue by wanderbon** [software-mansion/react-native-gesture-handler#1105]
### Platform:
- IOS

### Actual behaviour
On android GH Touchables occupy the top layer and may be pressed.
But this does not work for ios.

### Excepted behaviour:
This does work on ios

**Comment by AKologreev** [comment]
same problem with touchables inside the TapGestureHandler on ios

**Comment by j-piasecki** [comment]
Hi! I tried your snack, but it seems to be working correctly for me. Could you check if updating your dependencies (mainly Gesture Handler and Reanimated) solves the problem?
