### ISSUE TITLE
Multiple gestures in a View

### ISSUE THREAD

**Issue by mrousavy** [software-mansion/react-native-gesture-handler#1106]
This is more of a question than an issue, since I haven't found a way to "nest" PanGestureHandlers in a single View.

I have an outer `<PanGestureHandler>` wrapping my whole View which is able to interpolate on `translation.y` so the user can dismiss the View by dragging down. That's working fine. Then I have a second `<PanGestureHandler>` wrapping the Images of the Ferrari which is used to interpolate on `translation.x` so the user can scroll through images.

Only problem is, they work individually. Once I use both of them in the same view, the outer PanGestureHandler won't work anymore, since the inner `<PanGestureHandler>` (the one used to swipe through images) swallows every gesture, even when I'm seemingly dragging down. Here's a Demo:

![nested_demo](https://user-images.githubusercontent.com/15199031/86794240-92326a80-c06c-11ea-9c9a-0a1b7c0e3471.gif)

> Dragging down on the Price tag does work, since that View is not part of the inner PanGestureHandler

Is it possible to let the outer `<PanGestureHandler>` handle all `translation.y` events, and the inner only `translation.x`?

I'm unsure on how I would implement this logic, since if I used a single Handler for both actions, the user could drag down and swipe at the same time, which would be a somewhat weird behaviour.

Any help appreciated, thanks!

**Comment by sa8ab** [comment]
Take a look at `waitFor` prop [link](https://docs.swmansion.com/react-native-gesture-handler/docs/interactions.html#awaiting-other-handlers)

**Comment by mrousavy** [comment]
I actually just played around with the [`activeOffsetX`](https://docs.swmansion.com/react-native-gesture-handler/docs/handler-pan.html#activeoffsetx) and Y values and it turned out fine. thanks
