### ISSUE TITLE
Android - DrawerLayout with useNativeAnimations={false} stacked after couple orientation change

### ISSUE THREAD

**Issue by bulatkhayrullin** [software-mansion/react-native-gesture-handler#1112]
I found the following problem on android, if you use next DrawerLayout:
`<DrawerLayout
drawerPosition={DrawerLayout.positions.Right} // Important to use Right drawer position  
useNativeAnimations={false}
...  
/>
`
and will change orientation from vertical to horizontal and vice versa, you will see next result (see attachment)
![Screenshot_1594304030](https://user-images.githubusercontent.com/40695315/87051199-ede52b00-c207-11ea-8132-58daca25cc3a.png)

**Comment by piaskowyk** [comment]
Hey, could you provide a repo to reproduce your issue?
