### ISSUE TITLE
Methods can't be called in newer react versions

### ISSUE THREAD

**Issue by YDaskaloff** [software-mansion/react-native-gesture-handler#1116]
The methods listed in the end of the description (close, etc..) can't be called if not using classes in React.

**Comment by jakub-gonet** [comment]
Which description? In the docs, in the README or in the other place?

**Comment by jakub-gonet** [comment]
Closing due to no response.

**Comment by ASilcox86** [comment]
I'm running into this issue as well for the Swipeable component. The documentation doesn't support using methods (close, openLeft, openRight, etc) inside functional components. README and https://docs.swmansion.com/react-native-gesture-handler/docs/component-swipeable#methods.

**Comment by adam-ashored** [comment]
@ASilcox86 - you're most likely just not using them correctly. There is some confusion around refs in functional components.

Here is a simple example:

```js
const MyParentComponent = props => {
    const ref = useRef();

    const handleClick = () => {
       // open the swipeable
       ref.current.open();
    }

    return (
       <>
            <Button onClick={handleClick}/>
            <Swipeable ref={ref} {...someProps}/>
       </>
    )
}
```

I'd be willing to be the issue you and others are running into is when your component is one or more levels deep and you need to [forward the ref](https://reactjs.org/docs/forwarding-refs.html). Here's an example of that:

```js
const MySwipeableComponent = forwardRef((props,ref) => (
   return <Swipeable ref={ref} {...props}/>
));

const MyParentComponent = props => {
    const ref = useRef();

    const handleClick = () => {
       // open the nested swipeable
       ref.current.open();
    }

    return (
       <>
            <Button onClick={handleClick}/>
            <MySwipeableComponent ref={ref} {...someProps}/>
       </>
    )

}
```

**Comment by YDaskaloff** [comment]
> @ASilcox86 - you're most likely just not using them correctly. There is some confusion around refs in functional components.
> 
> Here is a simple example:
> 
> ```js
> const MyParentComponent = props => {
>     const ref = useRef();
> 
>     const handleClick = () => {
>        // open the swipeable
>        ref.current.open();
>     }
> 
>     return (
>        <>
>             <Button onClick={handleClick}/>
>             <Swipeable ref={ref} {...someProps}/>
>        </>
>     )
> }
> ```
> 
> I'd be willing to be the issue you and others are running into is when your component is one or more levels deep and you need to [forward the ref](https://reactjs.org/docs/forwarding-refs.html). Here's an example of that:
> 
> ```js
> const MySwipeableComponent = forwardRef((props,ref) => (
>    return <Swipeable ref={ref} {...props}/>
> ));
> 
> const MyParentComponent = props => {
>     const ref = useRef();
> 
>     const handleClick = () => {
>        // open the nested swipeable
>        ref.current.open();
>     }
> 
>     return (
>        <>
>             <Button onClick={handleClick}/>
>             <MySwipeableComponent ref={ref} {...someProps}/>
>        </>
>     )
> 
> }
> ```

**Comment by YDaskaloff** [comment]
@adam-ashored Thank you! That's exactly what I meant!
