### ISSUE TITLE
TextInput not working properly with react-native-web on some browsers

### ISSUE THREAD

**Issue by sorakthunly** [software-mansion/react-native-gesture-handler#1142]
## Issue

TextInput event `onChange` and `onChangeText` doesn't invoke on the following browsers:
- Safari - Mobile
- Safari - Desktop
- Chrome - Mobile (iOS)

They seem to work fine on Chrome Desktop and Firefox Desktop

**Comment by GarettFogel** [comment]
Did you ever find a solution to this? I'm running into a similar problem.

**Comment by zachdixon** [comment]
Also running into this on `"react-native-gesture-handler": "~1.10.2",`
It only accepts one letter at a time and the cursor always shows up at the beginning on focus. So if you click the arrow to go to the next input, then the other arrow to go back, you could technically enter what you need to in reverse.
Going back to using `TextInput` from `react-native` for now which works fine

**Comment by CodalReef** [comment]
I'm still seeing this problem in Safari Desktop.  Is there a workaround?

**Comment by WayneWang98** [comment]
Same issue on IOS both chrome and safari.
`"react-native-gesture-handler": "^1.9.0",`

**Comment by Warus15** [comment]
Hi, this issue should be fixed in [2.6.1](https://github.com/software-mansion/react-native-gesture-handler/releases/tag/2.6.1)

Note that this change is available in new web implementation. To enable it, call `enableExperimentalWebImplementation()` in the root of your project

**Comment by j-piasecki** [comment]
I'll close the issue since the new web implementation is enabled by default starting with 2.10.0.
