### ISSUE TITLE
[Bug] Cannot open in Expo

### ISSUE THREAD

**Issue by filiptronicek** [software-mansion/react-native-gesture-handler#1143]
In the docs, on the index page, specifically here:
https://github.com/software-mansion/react-native-gesture-handler/blob/70c97119604529e30a9677e397cfd1d217d60939/docs/src/pages/index.js#L97-L104
Is a link, that leads to an Expo.io page; upon scanning the provided QR code, you cannot load the project, Expo has made it so you cannot open another user's app. Not sure if this is iOS-specific, but it should be at least noted in the docs.
![image](https://user-images.githubusercontent.com/29888641/88204780-16c7e000-cc4c-11ea-9783-f562c30b4735.png)

**Comment by jakub-gonet** [comment]
Seems like #1131 doesn't replace all the links, will fix that.

Try using [this](https://snack.expo.io/@adamgrzybowski/react-native-gesture-handler-demo) link

**Comment by filiptronicek** [comment]
Awesome, works
