### ISSUE TITLE
How do you `pod spec lint` successfully?

### ISSUE THREAD

**Issue by teo029** [software-mansion/react-native-gesture-handler#1151]
**Not an issue with react-native-gesture-handler, but more like a call for library-dev-camaraderie.**

I am also delivering a cocoapod with both '.m' and '.h' as source files. The problem is that having an '.m' file with an import like '#import <React/RCTConvert.h" will break my `pod spec lint` with 'Can't find <React/RCTConvert.h` (or any header, whatsoever). I am running `pod spec lint` against your .podspec (inside node_modules/react-native-gesture-handler) and it seems like it also doesn't pass.

How do you manage to publish the cocoapod without the `pod spec lint` passing or what is your local setup in order to have the `pod spec lint` pass and find these React headers?

Help really appreciated. Thank you.

**Comment by jakub-gonet** [comment]
We don't use pod spec lint in the CI or locally so that's why I think it isn't passing in the first place. We may check it sometime soon if it's fixable in a reasonable amount of time.

**Comment by jakub-gonet** [comment]
Seems like it isn't fixable, as we take React Native as a peer dependency. Other projects integrating RN also have this problem.
