### ISSUE TITLE
Touchable don't work in Android. 1.7.0

### ISSUE THREAD

**Issue by Knjaz89** [software-mansion/react-native-gesture-handler#1152]
`<TouchableOpacity
                                containerStyle={[
                                    Styles.stepContainer,
                                ]}
                                onPress={() => console.log('test')}
                            >
<Text> Press me</Text>
</TouchableOpacity>
`

**Comment by krakz999** [comment]
Same issue

**Comment by jakub-gonet** [comment]
Duplicate of #578.
