### ISSUE TITLE
BorderlessButton transparent background on Android when absolute positioned

### ISSUE THREAD

**Issue by scgough** [software-mansion/react-native-gesture-handler#1155]
I have a couple of instances of `BorderlessButton` that are absolute positioned. 

iOS: all works as expected
Android: The background color is seemingly ignored when the wrapping container is absolute positioned. When not absolute positioned background color is fine. 

Note: if I add any kind of background color to the `wrapper` container it works.
e.g. `backgroundColor:'rgba(0,0,0,0.01)'`

RN: 0.62.2
React: 16.11.0
react-native-gesture-handler: 1.6.1

code e.g. 

```
<View style={styles.wrapper}>
    <BorderlessButton
        style={styles.button}
        onPress={this.handlePress}
      >
          <Icon .../>
      </BorderlessButton>
</View>

wrapper: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    left: 0,
},

button: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    width: 30,
    height: 30,
    borderRadius: 6,
}
```

**Comment by hiteshSavkare** [comment]
hey any update here ? i am also facing same issue for android

**Comment by WoLewicki** [comment]
I tried to reproduce it with the code you provided @scgough on the newest version and it seems to work the same on both platforms. I will close this issue then. Feel free to comment if I am wrong and we can reopen it then, but I think it would require a snack or simple repo with the reproduction to show the exact issue.
