### ISSUE TITLE
" typeerror: null is not an object (evaluating 'nativemqtt.newclient)"

### ISSUE THREAD

**Issue by justhelpp** [software-mansion/react-native-gesture-handler#1157]
hi im using the mqtt protocol in my project , when i include the Mqtt protocol with "import * as Mqtt from 'react-native-native-mqtt" and

declare my client with "const client = new Mqtt.Client('mqtt://broker.mqttdashboard.com:8000');"

it pop up an error said " typeerror: null is not an object (evaluating 'nativemqtt.newclient)"

notes : im using expo

**Comment by jakub-gonet** [comment]
This is related to `react-native-native-mqtt`, not gesture handler.
