### ISSUE TITLE
null is not an object(evaluating '_RNGestureHandlerModule.default.Direction')

### ISSUE THREAD

**Issue by tanhao8** [software-mansion/react-native-gesture-handler#1159]
Ask for help, the project won't  @brunolemos 
![WX20200808-010435](https://user-images.githubusercontent.com/47964060/89670154-4ac12780-d913-11ea-9c1c-c5ba5dbcb9bd.png)

**Comment by tanhao8** [comment]
react-native:0.62.2
react-native-gesture-handler:1.6.1

**Comment by jakub-gonet** [comment]
Duplicate of #494.
