### ISSUE TITLE
TouchableOpacity disappears when we style position absolute

### ISSUE THREAD

**Issue by ndotie** [software-mansion/react-native-gesture-handler#1163]

**Comment by TiagoDanin** [comment]
Same problem in `import {TouchableOpacity} from 'react-native-gesture-handler'` and `import {TouchableWithoutFeedback} from 'react-native-gesture-handler'`. But used `import {TouchableOpacity} from 'react-native' ` and `import {TouchableWithoutFeedback} from 'react-native'` working view.

**Comment by ErikTillberg** [comment]
A very quick fix for this is to wrap your touchable opacity from rngh with a view. Put your absolute positions in the view container, and the rest of your stylings in the touchable opacity.

**Comment by Emekaer** [comment]
Use the containerStyle prop instead of the style prop for styling TouchableOpacity from react-native-gvesture-handler.

`<TouchableOpacity containerStyle={"whatever style object"}>`

**Comment by zacdemi** [comment]
@Emekaer Amazing answer. Thank you!

**Comment by WoLewicki** [comment]
The solution from @Emekaer is the correct approach to the issue, you can also see more information here: https://github.com/software-mansion/react-native-gesture-handler/issues/864#issuecomment-912519707. I will close this issue then. Feel free to comment if something is wrong and we can always reopen it then.
