### ISSUE TITLE
Web link for "Getting Started" is broken

### ISSUE THREAD

**Issue by tosvilakos** [software-mansion/react-native-gesture-handler#1170]
## Description

"Page not found" for Getting Started link

https://docs.swmansion.com/react-native-gesture-handler/docs/next/getting-started

First found it on npm page:
https://www.npmjs.com/package/react-native-gesture-handler#installation

Then by clicking on "Getting Started" on:
https://docs.swmansion.com/react-native-gesture-handler/docs/next/
![image](https://user-images.githubusercontent.com/10219697/90678762-cc944780-e267-11ea-92c1-bf517286c5ee.png)

**Comment by jakub-gonet** [comment]
Thanks for reporting, we are aware of this issue.

**Comment by jakub-gonet** [comment]
Fixed by #1185
