### ISSUE TITLE
It's not possible to set border radius of single corner of RectButton

### ISSUE THREAD

**Issue by dymank** [software-mansion/react-native-gesture-handler#1176]
## Description

I want to set border radius just of top left and bottom right corners of `RectButton`. To do this, I use `borderTopLeftRadius` and `borderBottomRightRadius`, but it looks like they're ignored. Using `borderRadius` on all corners works like a charm. I am working on managed Expo project. And I develop only for Android device, so I don't know if that's an issue on iOS.

### Screenshots
These are screenshots from code you can find below. And this is how it looks like on my device. First I press button that should have only two corners rounded and both in pressed and idle state no corners are rounded. Then, I press button that has all corners rounded by using `borderRadius` and everything looks and works fine.

![image](https://user-images.githubusercontent.com/11396814/91092641-9f290e80-e658-11ea-9b68-4bbacb73fd83.png)
![image](https://user-images.githubusercontent.com/11396814/91092681-abad6700-e658-11ea-8a7b-dc27dd44f777.png)

## Steps To Reproduce

Tap buttons in example below

### Expected behavior

First two buttons have rounded two corners (top left and bottom right) in idle state and, when pressed, ripple fills them correctly.

### Actual behavior

First two buttons don't have any corners rounded.

## Snack or minimal code example

```
import React from 'react';
import { View } from 'react-native';
import Text from 'components/Text';
import { RectButton } from 'react-native-gesture-handler';

function App() {
  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'space-evenly' }}>
      <RectButton
        style={{
          padding: 8,
          backgroundColor: '#266599',
          borderTopLeftRadius: 20,
          borderBottomRightRadius: 20,
        }}
        rippleColor="#c0d7e5"
      >
        <View accessible>
          <Text style={{ color: '#fff' }}>Not pressed</Text>
        </View>
      </RectButton>
      <RectButton
        style={{
          padding: 8,
          backgroundColor: '#266599',
          borderTopLeftRadius: 20,
          borderBottomRightRadius: 20,
        }}
        rippleColor="#c0d7e5"
      >
        <View accessible>
          <Text style={{ color: '#fff' }}>Pressed</Text>
        </View>
      </RectButton>
      <RectButton
        style={{
          padding: 8,
          backgroundColor: '#266599',
          borderRadius: 20,
        }}
        rippleColor="#c0d7e5"
      >
        <View accessible>
          <Text style={{ color: '#fff' }}>Not pressed</Text>
        </View>
      </RectButton>
      <RectButton
        style={{
          padding: 8,
          backgroundColor: '#266599',
          borderRadius: 20,
        }}
        rippleColor="#c0d7e5"
      >
        <View accessible>
          <Text style={{ color: '#fff' }}>Pressed</Text>
        </View>
      </RectButton>
    </View>
  );
}

export default App;
```

## Package versions

- React: 16.13.1
- React Native: 0.62.2
- React Native Gesture Handler: 1.6.0

**Comment by Andarius** [comment]
FYI, you can achieve this by wrapping the RectButton into a view with "overflow": "hidden" and setting the borderRadius props there. I had a lot of weird behaviors setting borderRadius directly on the RectButton.

**Comment by kkafar** [comment]
See [this comment](https://github.com/software-mansion/react-native-gesture-handler/issues/477#issuecomment-680017127) in #477
