### ISSUE TITLE
RectButton & TouchableOpacity (from react-native-gesture-handler) are pressable through overlay in a transparent modal

### ISSUE THREAD

**Issue by Kailash23** [software-mansion/react-native-gesture-handler#1178]
**Current Behavior**
-  I am using a transparent modal in my application [link](https://reactnavigation.org/docs/stack-navigator/#transparent-modals). The button components from `react-native-gesture-handler` are pressable through the overlay. Working fine with the Button components from `react-native`.

**Expected Behavior**

- They should not be pressable through the overlay.

**How to reproduce**

https://snack.expo.io/@kailash23/react-navigation-v5-modal-bug

I had also filed the same issue on react-navigation [link](https://github.com/react-navigation/react-navigation/issues/8706)

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android
| @react-navigation/native       | 5.6.1
| react-native                   | 0.62.2
| expo                           | 38.0.0
|react-native-gesture-handler | 1.6.0
| node                           |
| npm or yarn                    |

**Comment by jkadamczyk** [comment]
Can reproduce only on Android 🤖

**Comment by jkadamczyk** [comment]
CC @jakub-gonet Maybe you recall if we had something similar it seems quite obvious and weird

**Comment by rchaubey** [comment]
This is still a problem with 1.9.0 version.

Looks like its a problem most of the routing library, I'm using `react-router-native`

There is an old issue with similar problem:

https://github.com/software-mansion/react-native-gesture-handler/issues/514

**Comment by kmagiera** [comment]
This is an expected behavior unless the modal is configured to block touches. The events pass through views that are transparent with a certain transparency threshold. In order to avoid this make the transparent background capture touches (e.g. make it a button or set gesture detector that does nothing).
