### ISSUE TITLE
Android not work

### ISSUE THREAD

**Issue by DaiYz** [software-mansion/react-native-gesture-handler#1184]
## Description

      <PanGestureHandler
        onGestureEvent={(e) => {
          console.log(e);
        }}
        onHandlerStateChange={(e) => console.log(e)}>
        <View
          style={{
            flex: 1,
            backgroundColor: 'red',
          }}
        />
      </PanGestureHandler>

No response when touch. 

Platfrom: android

## Package versions

- React: 16.13.1
- React Native: 0.63.2
- React Native Gesture Handler: 1.8.0

**Comment by jakub-gonet** [comment]
Could you specify what "doesn't work" means? The handler doesn't respond to touch, it crashes or something else?

**Comment by jakub-gonet** [comment]
Also, have you followed [the installation instructions for android](https://docs.swmansion.com/react-native-gesture-handler/docs/#android)?
