### ISSUE TITLE
PanGestureHandler in React Native/Expo 0.38 doesn't animate after first drag

### ISSUE THREAD

**Issue by wadewadewadewadewadewade** [software-mansion/react-native-gesture-handler#1194]
## Description

On my actual Android 9 device:
* I can drag the object right after the app loads, and I see the object follow my finger as I drag it (correct behavior)
  * The touch bubbles up to the parent container, which is not ideal, but that's something for me to deal with after this larger issue is resolved
* On the second drag, while my finger is down, the object appears stuck, and when I release my finger from the screen the object jumps to the new location (incorrect behavior)

## Steps To Reproduce

1. Go to [the snack I created showing this issue](https://snack.expo.io/@aproximation/react-native-draggable), and view it on iOS (iOS at snack.expo.io seems to behave similar to what I see on my actual Android device)
2. Drag the circle once and see the correct behavior
3. Then try to drag it a second time and see the incorrect behavior

### Expected behavior

Every drag should have the same behavior

### Actual behavior

Only the first drag after the expo snack loads has correct behavior

## Snack or minimal code example

https://snack.expo.io/@aproximation/react-native-draggable

I've modified the README in that snack to describe what I'm seeing as well

## Package versions

- React: 16.11.0
- React Native: 0.63.2
- React Native Gesture Handler: 1.6.0
- React Native Reanimated: 1.13.0
- Expo: 38.0.10

**Comment by wadewadewadewadewadewade** [comment]
I've just cross-posted this issue in stackoverflow in case someone there knows the answer to this one: https://stackoverflow.com/questions/63961174/after-setting-state-second-drag-not-animated-react-native-expo-pangestureha

**Comment by latviancoder** [comment]
I encountered the same issue and it seems to work when rewritten using `useCode` and `call`.
 
https://snack.expo.io/@igvadaimon/react-native-draggable

Not sure what's happening but I guess the timings aren't quite right for `onHandlerStateChange`.

**Comment by wadewadewadewadewadewade** [comment]
Thanks for taking the time to look and reply, @latviancoder ! 

Unfortunately, I'm not sure I'm seeing what you're seeing. When i go to your snack and try it on iOS, I can indeed drag the dot around. Bout I don't see the console.log line, and the offset is wrong on drags 2->N. So I think `useCode()` may have just cut out the `setPosition()` method, and I think it's `setPosition()` updating state that's breaking things.

But I've never used Animated before, so I could very well be missing something...

**Comment by latviancoder** [comment]
No, I see what you mean. I was actually testing web version before (it's working fine).

**Comment by wadewadewadewadewadewade** [comment]
OK, good, I'm glad I'm not going crazy (or at least not crazy with respect to this item).

You seem pretty familiar with Animation: what would you do if you were in my position? Maybe I should try writing my own drag tracking behavior instead of using PanGestureHandler, using something like a regular view's onTouchStart, onTouchMove, and onTouchEnd? Or do you think that be going down a road that would only end in tears?

**Comment by latviancoder** [comment]
Your assumption about me being familiar with Animation is wrong 😄  I've only worked with this library.

**Comment by wadewadewadewadewadewade** [comment]
Well you fooled me! :)

I think you're right about the event handlers not getting attached properly. On my physical device, once in like 20 reloads I'll be able to drag the object properly. And that tells me that sometimes things load in the order PanGestureHandler wants, and most of the time they don't.

But I can't tell what to wait for to delay the gesture handler stuff for. I'm pretty new to React, and I'm sure there's something in the flow of things loading, rendering, setting state, re-rendering, etc. that I'm missing somewhere... The most common state where things work correctly is after I change the JSX.Element to add or remove a node. It's like that tells expo to reload everything "clean" and that's when the PanGesturehandler seems to work. Once. Then I'll save the .tsx file which causes expo to reload, and then it's back to not working.

Does that give you any clues as to where this n00b should look next? Thanks again!!!

**Comment by wadewadewadewadewadewade** [comment]
I ended up using Animated and PanResponder from react-native instead of PanGestureHandler, and that ended up working.
```
  const panResponder = PanResponder.create({
    onMoveShouldSetPanResponder: () => true, //Tell iOS that we are allowing the movement
    onPanResponderGrant: (e, gestureState) => {
      scale.setValue(1.2); // make the X a bit bigger to indicate interaction
      animatedValue.extractOffset(); // move the value back into the offset
    },
    onPanResponderMove: Animated.event([
      null,
      {dx: animatedValue.x, dy: animatedValue.y},
    ]), // Creates a function to handle the movement and set offsets
    onPanResponderRelease: () => {
      scale.setValue(1);
      animatedValue.flattenOffset(); // Flatten the offset so it resets the default positioning
      if (value.position) {
        const newPosition = addLocations(
          positionDelta, // position is a delta and not an x/y offset
          percentToPixels(value.position, figureDimensions),
        );
        animatedValue.setOffset({x: 0, y: 0});
        animatedValue.setValue(multiplyLocation(scaleShift, -1));
        const newPositionPercentage = pixelsToPercent(
          newPosition,
          figureDimensions,
        );
        // this should always be true, but TypeScript likes being explicit...
        const pixels = {
          start: percentToPixels(value.position, figureDimensions),
          end: newPosition,
        };
        const percent = {start: value.position, end: newPositionPercentage};
        console.log(
          'updating',
          {pixels, percent},
          {newPosition, positionDelta},
        );
        updateLocation({
          key: value.key,
          created: new Date(),
          position: newPositionPercentage,
        }); // only update the changed information
      }
    },
  });
[...]
return (
    <Animated.View
      onStartShouldSetResponder={() => onDoublePress()}
      onLayout={(e: LayoutChangeEvent) =>
        setLocationDimensions({
          width: e.nativeEvent.layout.width,
          height: e.nativeEvent.layout.height,
        })
      }
      style={[
        styles.location,
        pixelsToPercentViewStyle(
          percentToPixels(value.position, figureDimensions),
          figureDimensions,
        ),
        adjustForDesktop,
        {
          transform: [...animatedValue.getTranslateTransform(), {scale}],
        },
      ]}
      {...panResponder.panHandlers}>
[children]
     <Animated.Vew/>
    );
```
