### ISSUE TITLE
Unresponsive touchables inside accordion

### ISSUE THREAD

**Issue by MarioUnlam** [software-mansion/react-native-gesture-handler#1195]
## Description

Hi. I'm having problems with tappables in my project. My current setup has:
- React Navigation
- react-native-screens
- nativeScreens() enabled in App.tsx
- createNativeStackNavigator() enabled in my navigation routes
- react-native-gesture-handler
- react-native-collapsible

The problem is, when I enable createNativeStackNavigator, any buttons inside my Accordions (from react-native-collapsible) cannot be tapped. If I use the Touchable* from react-native instead of react-native-gesture-handler, they can be tapped, but they have no feedback.

I tried using gestureHandlerRootHOC() on the accordion content. This makes Touchables from gesture-handler work again. However, this causes other problems. For example, if I click something near the accordion, it closes, and the content layout breaks, rendering with 0 height.

If I disable createNativeStackNavigator, and use the React Navigation default stack, the touchables work fine, but the app is not as fast as with native stack.

Is there anything else I should to make these plugins work well together?

Any help would be appreciated

## Code

```js
import Accordion from 'react-native-collapsible/Accordion';
// [...]

export default function CustomAccordion(props: Props) {  
  
  // [...]
  
  const renderContent = (section: typeof singleSection) => {
    return <View style={{}}>{section.content}</View>;
  };
  
  // const renderContent = gestureHandlerRootHOC((section: typeof singleSection) => {
  //     return <View style={{}}>{section.content}</View>;
  // });

  return (
    <View style={styles.container}>
      <Accordion
        sections={sectionList}
        activeSections={activeSections}
        renderHeader={renderHeader}
        renderContent={renderContent}
        onChange={updateSections}
        disabled={false}
      />
    </View>
  );
}
```

### Package versions

- React: 16.13.1
- React Native: 0.63.2
- React Native Gesture Handler: ^1.7.0
- React Navigation Native: ^5.7.3
- React Navigation Stack: ^5.9.0
- React Native Collapsible: ^1.5.3
- React Native Screens: ^2.11.0

**Comment by jakub-gonet** [comment]
Could you provide a working repro? It's hard to verify this issue without it given that 4 external libraries are involved.

Closing until repro is given.
