### ISSUE TITLE
Migration from react-native-swipeout

### ISSUE THREAD

**Issue by rahamin1** [software-mansion/react-native-gesture-handler#1197]
I inherited code that is using react-native-swipeout, and, when running the app, I am getting the following warning:

> Please update the following components: Swipeout
> [Sat Sep 19 2020 10:06:23.294]  WARN     Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

When I looked in the react-native-swipeout documentation I saw the recommendation to use react-native-gesture-handler.

Can anybody who has done this save me time in the migration and suggest what I should do with the following code?   
(I didn't include the renderedItem's code since I didn't think it is important for the migration):

```
const CustomSwipeoutButton = () =>
    <Image
        style={{ height: 27, width: 21, marginLeft: "auto",
            marginRight: "auto", marginTop: "auto",
            marginBottom: "auto" }}
        source={require(trashcan)}
    />
```

....

`render() {`

...

```
<Swipeout
        autoClose: true,
        buttonWidth: 129,
        right: [
            {
                text: 'Delete',
                component: <CustomSwipeoutButton />,
                type: 'delete',
                backgroundColor: '#ff3b30',
                onPress: () => {
                    remove(skuUuid);
                }
            }
        ]
>
                    { renderedItem }
</Swipeout>
```

...

`}`

**Comment by jakub-gonet** [comment]
This is more like a SO question than Github issue.

react-native-swipeout author probably meant Swipeable component, you can read more about it [here](https://docs.swmansion.com/react-native-gesture-handler/docs/component-swipeable).
