### ISSUE TITLE
No event get fired when using React-Navigation and using event trigger outside Navigation Screen

### ISSUE THREAD

**Issue by Kirchesch** [software-mansion/react-native-gesture-handler#1201]
## Description

No event get fired when using React-Navigation and using event trigger outside Navigation Screen

### Screenshots

No screen shot needed

## Steps To Reproduce

1. Create a basic react-native navigation content
2. Create a screen with a button that calls an outside <view> with a react-native-gesture-handler component inside
3. Try to use that react-native-gesture-handler component and that's it

### Expected behavior
onPress or onGestureEvent should call their respective callback's

### Actual behavior
onPress or onGestureEvent never fire

## Package versions
1.8.0

- React:
- React Native:
- React Native Gesture Handler:

**Comment by jakub-gonet** [comment]
I'm not sure what you mean by "outside". Using Gesture Handler outside of React Navigation tree isn't possible because it can't forward touches to GH. Use EnabledRootView to wrap those components.

Also, repro is missing so I'm closing this issue until one is provided.

**Comment by aanklewicz92** [comment]
I experience the same issue and want to use that `EnabledRootView`, but I can't find it anywhere. Even Google seems to have problems with finding such thing. Where is this view? Which library has it?

**Comment by aanklewicz92** [comment]
Found it! One needs to add: 
```
import com.facebook.react.ReactActivityDelegate;
import com.facebook.react.ReactRootView;
import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;

---

@Override
protected ReactActivityDelegate createReactActivityDelegate() {
    return new ReactActivityDelegate(this, getMainComponentName()) {
        @Override
        protected ReactRootView createRootView() {
            return new RNGestureHandlerEnabledRootView(MainActivity.this);
        }
    };
}
```
to `MainActivity.java`

**Comment by jakub-gonet** [comment]
It's mentioned in [our docs](https://docs.swmansion.com/react-native-gesture-handler/docs/#updating-mainactivityjava), in the Getting started section.

**Comment by superyarik** [comment]
facing this in React-Navigation 4. as i understand now there is no need to modify MainActivity.java but problem exist
