### ISSUE TITLE
ScrollView inside PanGestureHandler doesn't respond sometimes

### ISSUE THREAD

**Issue by samuelpetroline** [software-mansion/react-native-gesture-handler#1203]
## Description

When using the package's ScrollView inside a PanGestureHandler, the ScrollView stops responding sometimes, like it is stuck.

### Expected behavior

The ScrollView shouldn't stop responding

## Snack or minimal code example

https://snack.expo.io/@samuelpetroline/scrollview-inside-pangesturehandler

Note that it doesn't always shows this behaviour. If it is working correctly, reopen the menu and start scrolling up and down. Eventually it will get stuck.

## Package versions

- React: 16.13.1
- React Native: 0.63.0
- React Native Gesture Handler: ^1.7.0

**Comment by samuelpetroline** [comment]
Well, I got my problem solved by adding a View inside ScrollView with responder props:

```js
<PanGestureHandler>
   <ScrollView>
     <View
        onStartShouldSetResponder={() => true}
        onStartShouldSetResponderCapture={() => true}
        onMoveShouldSetResponderCapture={() => true}
        onMoveShouldSetResponder={() => true}
      >
       {children}
    </View>
  </ScrollView>
</PanGestureHandler>
```

**Comment by ShaMan123** [comment]
I think #1034 should fix this. Try passing `waitFor`
