### ISSUE TITLE
TapGestureHandler doesn't work when nested within an SVG

### ISSUE THREAD

**Issue by harveyconnor** [software-mansion/react-native-gesture-handler#1206]
## Description
So I've tried to nest a `TapGestureHandler` component inside of an SVG element however it isn't recognising the touch events on the handler. (Using react-native-svg).

I have also tried with `AnimatedG` and `G` but with no success.

## Steps To Reproduce

1. Clone the repo: https://github.com/harveyconnor/TapGestureHandlerSvgBug
2. `cd TapGestureHandlerSvgBug`
3. `npm install`
4. `npx pod-install`
5. `npx react-native run-android` or run in xcode for ios
6. Take a look at /App.tsx for main source code

### Expected behavior
Tap events would get sent to the `tapHandler` function.

### Actual behavior
No events are being sent.

## Package versions
- React: 16.13.1
- React Native: 0.63.2
- React Native Gesture Handler: ^1.8.0

**Comment by jakub-gonet** [comment]
Could please update steps to reproduce to include **entire** code that can be pasted and tested?

**Comment by harveyconnor** [comment]
@jakub-gonet So it appears that `G` doesn't work with touch events, I need them to work please take a look at the repo provided here: https://github.com/harveyconnor/TapGestureHandlerSvgBug/blob/master/App.tsx
Cheers

**Comment by j-piasecki** [comment]
Hi! I ran the code from your repo but I'm not sure what the `TapGestureHandler` is supposed to do, as it's not present in the code. If this issue still affects you could you check if it's solved by updating to the newest versions of Gesture Handler and Reanimated? If that doesn't work, could you update the repository you've linked?
