### ISSUE TITLE
RNGestureHandlerManager's _rootViews causes memory leak

### ISSUE THREAD

**Issue by Norcy** [software-mansion/react-native-gesture-handler#1207]
## Description

In `RNGestureHandlerManager.m`, `_rootViews` is a `NSMutableSet` which will retain the elements.

```
NSMutableSet<UIView*> *_rootViews;
```

In fact, the element in _rootViews is `RCTRootContentView`.

When a `RCTRootView` is created, the `RCTRootContentView` will be pushed into the `_rootViews`.

In my case, `RCTBridge` is cached after remove a `RCTRootView`.  `RCTRootView` will dealloc, but `RCTRootContentView` will not dealloc.

Then I allocate a new `RCTRootView` which is inited by my cached `RCTBridge`, a new `RCTRootContentView` will be allocated and it will also be retained by `RNGestureHandlerManager`. At present, the `_rootViews` has two `RCTRootContentView` element, the old and the new. 

I think that the `_rootViews` should not strong retain the element.

In my opinion, the solution is that using `NSHashTable` instead of `NSMutableSet`

```
NSHashTable<UIView *> *_rootViews;
_rootViews = [NSHashTable hashTableWithOptions:NSPointerFunctionsWeakMemory];
```

## Steps To Reproduce

1.

### Expected behavior

When a `RCTRootView` is removed, during the `RCTBridge` is cached, the `RCTRootContentView` should be dealloced

### Actual behavior

When a `RCTRootView` is removed, during the `RCTBridge` is cached, the `RCTRootContentView` did not be dealloced

## Package versions

- React: 16.11.0
- React Native: 0.62.2
- React Native Gesture Handler: 1.7.0

**Comment by 17554265585** [comment]
Finally found the culprit of the memory leak, you are great

**Comment by jkadamczyk** [comment]
Hi! Thanks for the issue!
Would it be possible for you to test the HashSet solution and submit a pull request? That would be a great help, but nevertheless, we will try to look into this.

**Comment by Norcy** [comment]
> Hi! Thanks for the issue!
> Would it be possible for you to test the HashSet solution and submit a pull request? That would be a great help, but nevertheless, we will try to look into this.

HaseSet? Do you mean NSHashTable? I will submit a PR later.
