### ISSUE TITLE
Inverted Flatlist scrolling wrong direction when flicking at bottom

### ISSUE THREAD

**Issue by hardcodet** [software-mansion/react-native-gesture-handler#1209]
This may be a regression of https://github.com/software-mansion/react-native-gesture-handler/issues/171

Repro (Android 10):

Scroll to the end (bottom) of an inverted FlatList. When at the end, perform a few flicks further towards the bottom. Expected behavior here is that nothing would happen. What happens though is that the list suddenly scrolls back up.

Workaround: Replacing RNGH FlatList with RN FlatList fixes the issue.

## Package versions

RNGH: 1.7.0
Expo SDK 39

**Comment by jakub-gonet** [comment]
Could you please provide some small repro?

**Comment by kirillpisarev** [comment]
Have the same issue with 
"react-native-gesture-handler": "^1.8.0"
"react-native": "0.63.2"

inverted FlatList from react-native works fine as mentioned above.

code to reproduce:
```
import React from "react"
import { View } from "react-native"
import { FlatList } from "react-native-gesture-handler"

export const MessageList = () => {
	return (
		<FlatList
			inverted
			data={Array(50).fill(1)}
			renderItem={() => <View style={{ height: 100, backgroundColor: "red" }} />}
		/>
	)
}
```

illustration what happens (i'm trying to scroll down):

![1](https://user-images.githubusercontent.com/1886908/99658862-1bbd6480-2a71-11eb-8694-9d05e7199867.gif)

**Comment by nickksm** [comment]
Same issue here like @kirillpisarev

**Comment by tomekzaw** [comment]
Hello! Did you manage to resolve this issue? If not, can you please check if this issue still occurs on the latest version of react-native-gesture-handler and some newer version of react-native?

After activation, `NativeViewGestureHandler` will send touch events directly to `ScrollView` from react-native so the workaround from https://github.com/facebook/react-native/pull/21117 should be applied automatically. Nevertheless, we will need to delve into this issue.
