### ISSUE TITLE
No discrimination of onHandlerStateChange in nested Pan- and PinchGestureHandler components in Android emulator

### ISSUE THREAD

**Issue by albran** [software-mansion/react-native-gesture-handler#1212]
## Description / Actual behaviour

On Android emulator, all onHandlerStateChange functions are called when performing either pan or pinch gestures using nested handler components. Not tested on a physical device.

### Expected behaviour

Only onHandlerStateChange functions relevant to corresponding gestures should fire.

## Snack or minimal code example

Both console logs fire when either panning or pinching with the below code:

```
import React from "react";
import { PanGestureHandler, PinchGestureHandler } from "react-native-gesture-handler";
import Animated from "react-native-reanimated";


const App = () => {
  const onPanHandlerStateChange = () => console.log("pan gesture state change");
  const onPinchHandlerStateChange = () => console.log("pinch gesture state change");

  return (
    <PanGestureHandler
      onHandlerStateChange={onPanHandlerStateChange}
      minPointers={1}
      maxPointers={1}
    >
      <Animated.View style={{flex: 1}}>
        <PinchGestureHandler
          onHandlerStateChange={onPinchHandlerStateChange}
          minPointers={2}
          maxPointers={2}
        >
          <Animated.View style={{ width: "100%", height: "100%" }} />
        </PinchGestureHandler>
      </Animated.View>
    </PanGestureHandler>
  );
}

export default App;
```

## Package versions
```
"react": "16.13.1",
"react-native": "0.63.3",
"react-native-gesture-handler": "^1.8.0",
"react-native-reanimated": "^1.13.1"
```

**Comment by j-piasecki** [comment]
This is working as intended. When you place the first finger on the screen we cannot yet determine whether you will pan or pinch, so we assume it could be both and both handlers move to the `BEGAN` state where pan waits for the finger to move and the pinch waits for another finger to be placed. Then you can either move your finger activating pan gesture which will in turn cancel pinch, or you can place the second finger on the screen which will cause the pan to fail as it has `maxPointers` set to 1.
