### ISSUE TITLE
Swipeable child doesn't adjust when actions change their own width

### ISSUE THREAD

**Issue by charles-goode** [software-mansion/react-native-gesture-handler#1219]
## Description

Say I have a right action that is pressable and when its pressed, its expands to take up more horizontal space. When it adjusts its width, the component wrapped in the swipeable does not move out of the way, so it just overlaps. Calling openRight doesn't refresh anything (I'm guessing it checks if the right is open already and then does nothing instead of properly refreshing).

## Steps To Reproduce

1.

## Snack or minimal code example
```
const ExpandingAction = () => {
    const [expanded, setExpanded] = useState(false);
    return (
        <TouchableWithoutFeedback onPress={() => setExpanded(!expanded)}>
            <View style={{width: expanded ? 160 : 80}} />
        </TouchableWithoutFeedback>
    )
}

const Swiper = () => {
 return (
   <Swipeable renderRightActions={ExpandingAction}>
      {/* children*/}
   </Swipeable>
  )
}
```

## Package versions

- React: 16.11
- React Native: 0.62
- React Native Gesture Handler: 1.6

**Comment by jakub-gonet** [comment]
Could you please prepare a **runnable** code example?

**Comment by piaskowyk** [comment]
This issue seems to be inactive, so I'm closing 😔
