### ISSUE TITLE
Ignore TapGestureHandler if over Button

### ISSUE THREAD

**Issue by alpha0010** [software-mansion/react-native-gesture-handler#1223]
## Description

My screen is wrapped in a `TapGestureHandler`.  On the screen I have several `Button` components (from react native, however switch to `RectButton` from RNGH has the same result).  If I press the button, both the button *and* `TapGestureHandler` are triggered.

Is there a way to disable the `TapGestureHandler` if the tap was over a button?

### Package versions

- React: 16.13.1
- React Native: 0.63.3
- React Native Gesture Handler: 1.8.0
- React Native Navigation: 7.2.0

**Comment by adbl** [comment]
Also seeing this issue...

**Comment by adbl** [comment]
My use case is a modal UI with buttons, and a tap handler across the background to hide it.

My debug logging for ios shows the following:
```
TapGestureHandlerStateChangeEvent onHandlerStateChange 2
RectButton onHandlerStateChange 4
TapGestureHandlerStateChangeEvent onHandlerStateChange 4
TapGestureHandlerStateChangeEvent onHandlerStateChange 5
RectButton onHandlerStateChange 3
```

Whereas for android:
```
RectButton onHandlerStateChange 2
TapGestureHandlerStateChangeEvent onHandlerStateChange 2
RectButton onHandlerStateChange 4
RectButton onHandlerStateChange 5
TapGestureHandlerStateChangeEvent onHandlerStateChange 4
TapGestureHandlerStateChangeEvent onHandlerStateChange 5
```

**Comment by adbl** [comment]
Same issue as #346

**Comment by pihomeserver** [comment]
Same issue with latest release. Can't find a way to solve that

**Comment by piaskowyk** [comment]
Hey, should use Gesture Handler Button instead React Button, or you can wrap this button with a gesture handler native wrapper. Let me know if it doesn't work still.
