### ISSUE TITLE
NativeViewGestureHandler android bug

### ISSUE THREAD

**Issue by maystrenkoYurii** [software-mansion/react-native-gesture-handler#1224]
NativeViewGestureHandler work incorrect after start pan gesture translate handled onScroll only android
![ClientPanel](https://user-images.githubusercontent.com/23016311/98113683-b1bb9180-1eac-11eb-8070-ae7476614c6c.gif)

**Comment by jakub-gonet** [comment]
Could you please fill the issue template? We can't help you with that scarce info about this issue.
