### ISSUE TITLE
How to get RotationGestureHandler work with functional component

### ISSUE THREAD

**Issue by udarts** [software-mansion/react-native-gesture-handler#1232]
I have been trying to get the RotationGestureHandler working with functional component. But since the original from the doc is written in class format.

This is the code I currently changed, but got an error:

    const _rotate = useState(new Animated.Value(0));
    const _rotateStr = _rotate.interpolate({
        inputRange: [-360, 360],
        outputRange: ['-360rad', '360rad'],
    });
    const _lastRotate = 0;
    const _onRotateGestureEvent = Animated.event(
        [{ nativeEvent: { rotation: _rotate } }],
        { useNativeDriver: false }
    );
    const _onRotateHandlerStateChange = (event) => {
        if (event.nativeEvent.oldState === State.ACTIVE) {
            _lastRotate += event.nativeEvent.rotation;
            _rotate.setOffset(_lastRotate);
            _rotate.setValue(0);
        }
    };

    return (
        <RotationGestureHandler
            onGestureEvent={_onRotateGestureEvent}
            onHandlerStateChange={_onRotateHandlerStateChange}>
            <Animated.View
                key={id}
                style={{
                    transform: [
                        { translateX: pan.x },  // this is for moving the image
                        { translateY: pan.y },   // this is for moving the image
                        { rotate: _rotateStr }
                    ],
                    alignSelf: 'flex-start',
                    // position: 'absolute',
                    elevation: 2 
                    // left: 20, 
                    // top: 40
                }}
                {...panResponder.panHandlers}
            >
                <ContextMenu actions={[
                    {
                        title: `Delete ${imgTitle}`,
                        systemIcon: 'trash',
                        destructive: true,
                    },
                ]} onPress={onPress}>
                    <TouchableHighlight onLongPress={() => setConextMenuOpen(true)} activeOpacity={0.7} underlayColor="transparent">
                        <Image source={stageimage} style={{height: 100,width: 100}} resizeMode='contain' />
                    </TouchableHighlight>
                </ContextMenu>
            </Animated.View>
        </RotationGestureHandler>
    );

The error I am getting:

    TypeError: _rotate.interpolate is not a function. (In '_rotate.interpolate({
      inputRange: [-360, 360],
      outputRange: ['-360rad', '360rad']
    })', '_rotate.interpolate' is undefined)

Maybe I made a silly mistake, so if someone can take a look and see if I changed it correctly.

Cheers

**Comment by jakub-gonet** [comment]
`_rotate = useState(new Animated.Value(0));`
`const _rotateStr = _rotate.interpolate({
    inputRange: [-360, 360],
    outputRange: ['-360rad', '360rad'],
});`

`useState` returns **an array**, not a value. You should probably use `useMemo` or similar to memoize `Animated.Value` (using new Value outside of a function will create a new value on every rerender).


Closing as unrelated to RNGH.
