### ISSUE TITLE
Increasing hitSlop does not increase touch area

### ISSUE THREAD

**Issue by LouiseBC** [software-mansion/react-native-gesture-handler#1242]
## Description

I added hitSlop to buttons on iOS and it works perfectly, but the touch area isn't increased on Android.
It seems to be an issue with react-native-gesture-handler: We're using a `BorderlessButton`, but when I replace it with `TouchableOpactiy` from react-native it works just fine. Using RNGH's TouchableOpacity once again doesn't work, and besides that it seems to calculate different touch areas.

### Screenshots         
![Screenshot 2020-11-27 at 09 55 18](https://user-images.githubusercontent.com/21264029/100430230-c8619c80-3096-11eb-8cd0-eb2ce352575a.png)
This is what the touch area looks like using TouchableOpacity from RN, or using BorderlessButton from RNGH. When using TouchableOpacity from RN the touch area indicated here works. When using BorderlessButton only the red area (padding) is touchable.

![Screenshot 2020-11-27 at 09 55 27](https://user-images.githubusercontent.com/21264029/100430391-052d9380-3097-11eb-9177-ff65aca7ac91.png)
This is what the touch area looks like using TouchableOpacity from RNGH

## Snack or minimal code example

```
    <TouchableOpacity    // or BorderlessButton
      ...
      hitSlop={{top: 16, bottom: 16, left: 8, right: 0}}>
      ...
    </TouchableOpacity>
```

## Package versions

- React: 16.13.1
- React Native: 0.63.3
- React Native Gesture Handler: 1.9.0

**Comment by Thavry** [comment]
Any news about this issue?

**Comment by VictorPullzz** [comment]
Any news about this issue?

**Comment by leepowellnbs** [comment]
Same issue - this seems to work correctly for RN's implementation of TouchableOpacity, but not RNGH in Android.
