### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by dcboy** [software-mansion/react-native-gesture-handler#1246]
## Description

11-27 09:56:06.323 E/VOS|App (31135): -----Crash Log Begin-----
11-27 09:56:06.323 E/VOS|App (31135): length=12; index=12
11-27 09:56:06.323 W/System.err(31135): java.lang.ArrayIndexOutOfBoundsException: length=12; index=12
11-27 09:56:06.323 W/System.err(31135): 	at com.swmansion.gesturehandler.GestureHandler.startTrackingPointer(GestureHandler.java:219)
11-27 09:56:06.324 W/System.err(31135): 	at com.swmansion.gesturehandler.GestureHandlerOrchestrator.recordViewHandlersForPointer(GestureHandlerOrchestrator.java:390)
11-27 09:56:06.324 W/System.err(31135): 	at com.swmansion.gesturehandler.GestureHandlerOrchestrator.traverseWithPointerEvents(GestureHandlerOrchestrator.java:466)
11-27 09:56:06.324 W/System.err(31135): 	at com.swmansion.gesturehandler.GestureHandlerOrchestrator.extractGestureHandlers(GestureHandlerOrchestrator.java:403)
11-27 09:56:06.324 W/System.err(31135): 	at com.swmansion.gesturehandler.GestureHandlerOrchestrator.onTouchEvent(GestureHandlerOrchestrator.java:97)
11-27 09:56:06.324 W/System.err(31135): 	at com.swmansion.gesturehandler.react.RNGestureHandlerRootHelper.dispatchTouchEvent(RNGestureHandlerRootHelper.java:126)
11-27 09:56:06.324 W/System.err(31135): 	at com.swmansion.gesturehandler.react.RNGestureHandlerRootView.dispatchTouchEvent(RNGestureHandlerRootView.java:63)
11-27 09:56:06.324 W/System.err(31135): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
11-27 09:56:06.324 W/System.err(31135): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
11-27 09:56:06.324 W/System.err(31135): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
11-27 09:56:06.324 W/System.err(31135): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
11-27 09:56:06.324 W/System.err(31135): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
11-27 09:56:06.324 W/System.err(31135): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
11-27 09:56:06.324 W/System.err(31135): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
11-27 09:56:06.324 W/System.err(31135): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
11-27 09:56:06.324 W/System.err(31135): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
11-27 09:56:06.324 W/System.err(31135): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
11-27 09:56:06.324 W/System.err(31135): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
11-27 09:56:06.324 W/System.err(31135): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
11-27 09:56:06.324 W/System.err(31135): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2537)
11-27 09:56:06.324 W/System.err(31135): 	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1818)
11-27 09:56:06.324 W/System.err(31135): 	at android.app.Activity.dispatchTouchEvent(Activity.java:2784)
11-27 09:56:06.324 W/System.err(31135): 	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
11-27 09:56:06.324 W/System.err(31135): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2498)
11-27 09:56:06.324 W/System.err(31135): 	at android.view.View.dispatchPointerEvent(View.java:8746)
11-27 09:56:06.324 W/System.err(31135): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchPointerEvent(PhoneWindow.java:2483)
11-27 09:56:06.324 W/System.err(31135): 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4403)
11-27 09:56:06.324 W/System.err(31135): 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4250)
11-27 09:56:06.324 W/System.err(31135): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3805)
11-27 09:56:06.324 W/System.err(31135): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3858)
11-27 09:56:06.324 W/System.err(31135): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3824)
11-27 09:56:06.324 W/System.err(31135): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3941)
11-27 09:56:06.324 W/System.err(31135): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3832)
11-27 09:56:06.324 W/System.err(31135): 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3998)
11-27 09:56:06.324 W/System.err(31135): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3805)
11-27 09:56:06.324 W/System.err(31135): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3858)
11-27 09:56:06.324 W/System.err(31135): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3824)
11-27 09:56:06.324 W/System.err(31135): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3832)
11-27 09:56:06.324 W/System.err(31135): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3805)
11-27 09:56:06.324 W/System.err(31135): 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6120)
11-27 09:56:06.324 W/System.err(31135): 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6094)
11-27 09:56:06.324 W/System.err(31135): 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6065)
11-27 09:56:06.324 W/System.err(31135): 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6210)
11-27 09:56:06.324 W/System.err(31135): 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
11-27 09:56:06.324 W/System.err(31135): 	at android.os.MessageQueue.nativePollOnce(Native Method)
11-27 09:56:06.324 W/System.err(31135): 	at android.os.MessageQueue.next(MessageQueue.java:143)
11-27 09:56:06.324 W/System.err(31135): 	at android.os.Looper.loop(Looper.java:122)
11-27 09:56:06.324 W/System.err(31135): 	at android.app.ActivityThread.main(ActivityThread.java:5321)
11-27 09:56:06.324 W/System.err(31135): 	at java.lang.reflect.Method.invoke(Native Method)
11-27 09:56:06.324 W/System.err(31135): 	at java.lang.reflect.Method.invoke(Method.java:372)
11-27 09:56:06.324 W/System.err(31135): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
11-27 09:56:06.324 W/System.err(31135): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)

## Steps To Reproduce

1.

## Package versions

- React: 16.13.1
- React Native: 0.63.3
- React Native Gesture Handler: 1.9.0

**Comment by jakub-gonet** [comment]
Could you describe what device are you using and do you interact with it? Seems like you have more than 12 pointers (which is the internal limit of active pointers in gesture handler).

**Comment by dcboy** [comment]
> Could you describe what device are you using and do you interact with it? Seems like you have more than 12 pointers (which is the internal limit of active pointers in gesture handler).

my device is RK3288 Android 5.1 
how to get device info what you need? I can cooperate

**Comment by jakub-gonet** [comment]
I don't really need much more info about the device, was just curious how do you use it. Is it a screen intended for many people to use it simultaneously?

In the meantime, you can patch RNGH via [patch-package](https://www.npmjs.com/package/patch-package) by increasing `MAX_POINTERS_COUNT`, like in [this PR](https://github.com/software-mansion/react-native-gesture-handler/pull/1175/files).

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
If you need further help please reply.

**Comment by Arman-Zohrabyan** [comment]
Same problom.

**Comment by Arman-Zohrabyan** [comment]
Same problem.

Device: Rk3288

**Comment by rusty120** [comment]
This is currently our top crash report on Crashlytics. Almost all from ActivPanel devices, which I imagine is a classroom panel-type device where multiple users interact with the screen at once leading to more than 12 simultaneous touch events.

For our specific case, I think I can patch `react-native-gesture-handler` to simply ignore all touch events, since our app doesn't need gestures at all. We use `react-navigation/stack`, which has a dependency on this package even with gestures disabled.

I guess the ideal fix would be to either remove the hard coded limit? Or maybe simply ignoring touch events after 12 will be sufficient?

**Comment by dhavaln** [comment]
We faced a similar issue for our RN application running on 75" touch screens. 
We patched the library to allow a (very) higher limit.
