### ISSUE TITLE
__DEV__ const breaks the app in bare setup

### ISSUE THREAD

**Issue by ElForastero** [software-mansion/react-native-gesture-handler#1247]
`__DEV__` const is typical for RN environment, but not for the web.

**Error source**
https://github.com/software-mansion/react-native-gesture-handler/blob/8809501f5095045bb5d9454a0ef858a68ea5bc5a/src/handlers/Gestures.js#L221-L223

Maybe we can document this little thing and require setting up a DefinePlugin?

**Fix**
```js
new webpack.DefinePlugin({
    __DEV__: process.env.NODE_ENV === 'development',
})
```

**Error**

![image](https://user-images.githubusercontent.com/5102818/100522929-e24dcd00-31c5-11eb-8eed-09f8b16da9ce.png)

**Comment by jakub-gonet** [comment]
> Maybe we can document this little thing and require setting up a DefinePlugin?

Not really fond of this solution, RNGH is hard to set up already.

So, the only way to check for development env is to check the `NODE_ENV` env variable?

**Comment by j-piasecki** [comment]
For me it seems to be working. If you still have a problem with this issue, could you provide some instructions on how to reproduce it?
