### ISSUE TITLE
TouchableHightLight onMoveOut scope

### ISSUE THREAD

**Issue by maestrolsj** [software-mansion/react-native-gesture-handler#1248]
## Description

onMoveOut scope is **too Wide**
Click and hold  TouchableHightLight > UNDETERMINED > MOVED_OUTSIDE

## Motivation

Normally  Holding should be **released** and clicking should be **canceled** when finger holding a button moved out of Button

It would be nice it provides **releaseSlop** like hitSlop 
## Code example

    <TouchableHighlight onPress={} >
      {children}
    </TouchableHighlight>

**Comment by j-piasecki** [comment]
If this is still affecting you, please open a new issue with a more detailed description.
