### ISSUE TITLE
Cannot trigger PinchGestureHandler unless it covers center/bottom half on the iOS simulator

### ISSUE THREAD

**Issue by codypearce** [software-mansion/react-native-gesture-handler#1254]
## Description

I cannot seem to trigger the PinchGestureHandler unless it covers the center/bottom half on the iOS simulator. 

### Screenshots

Here's a short gif showing that the event doesn't get called with a simple object that's above, but does get called if I change the height of the object to go past the center of the device.

https://gfycat.com/biodegradablewarlikearrowworm

## Steps To Reproduce

Checkout the example here https://github.com/codypearce/rngesturetest or:

1. set up a new react native project
2. setup a simple PinchGestureHandler, for example:

```
 import React from 'react';
  import {View, Animated} from 'react-native';
  import {PinchGestureHandler, State} from 'react-native-gesture-handler';

  const App = () => {
    const scale = new Animated.Value(1);
    const onGestureEvent = Animated.event([{nativeEvent: {scale: scale}}], {
      useNativeDriver: true,
    });
    const onPinchStateChange = (event) => {
      console.log('called');
      if (event.nativeEvent.oldState === State.ACTIVE) {
        Animated.spring(scale, {toValue: 1, useNativeDriver: true}).start();
      }
    };

    return (
      <View>
        <PinchGestureHandler
          onGestureEvent={onGestureEvent}
          onHandlerStateChange={onPinchStateChange}>
          <Animated.View
--          style={{
              height: 300,
              width: 500,
              backgroundColor: 'black',
              transform: [{scale: scale}],
            }}
          />
        </PinchGestureHandler>
      </View>
    );
  };

  export default App;
```
3. start up an iOS simulator
4. use option key on the simulator to simulate the pinch gesture, it shouldn't fire the gesture
5. change the height on the <Animated.View> to something like 800
6. use option key on the simulator to simulate the pinch gesture, it should fire the gesture

### Expected behavior

Pinching anywhere on the pinch object should trigger the event.

### Actual behavior

Can only pinch if object extends to the middle/bottom part of the screen

## Snack or minimal code example

https://github.com/codypearce/rngesturetest

## Package versions

- React: 16.13.1
- React Native: 0.63.4
- React Native Gesture Handler: ^1.9.0
- iOS Simulator: 13.2.2

**Comment by jakub-gonet** [comment]
RNGH is working correctly here. Notice that only the inner view is wrapped in PinchGH so it only can interact with it. After you increased the size, both pointers are over the inner view so it works.


https://user-images.githubusercontent.com/12465392/130389527-898da539-5243-42b5-860e-ff64378dfa7a.mov
