### ISSUE TITLE
@react-native-picker cannot be clicked if inside TapGestureHandler

### ISSUE THREAD

**Issue by ndbeyer** [software-mansion/react-native-gesture-handler#1255]
## Description

When nesting `ReactNativePicker` in a `TapGestureHandler`, `ReactNativePicker` won't react on click events, so the modal of `ReactNativePicker` won't open (observed in Android, not tried on ios).

However, long-pressing on `ReactNativePicker` opens the the modal. 
Also, nesting `ReactNativePicker` in a `TouchableOpacity` instead works as expected

```
import React from 'react';
import styled from 'styled-native-components';
import { TouchableOpacity, Text } from 'react-native';
import { TapGestureHandler } from 'react-native-gesture-handler';
import { Picker } from '@react-native-community/picker';

const Wrapper = styled.View`
	align-self: stretch;
	flex: 1;
	justify-content: center;
	align-items: center;
	background-color: white;
`;

const StyledPicker = styled(Picker)`
	height: 100;
	width: 100;
	color: black;
`;

const Screen = ()=> {
	return (
		<Wrapper>
			<Wrapper>
				<TapGestureHandler>
					<Wrapper>
						<Text style={{ fontSize: 20 }}>Picker in TapGestureHandler</Text>
						<StyledPicker>
							<Picker.Item label="1" value={1} />
							<Picker.Item label="2" value={2} />
						</StyledPicker>
					</Wrapper>
				</TapGestureHandler>
			</Wrapper>
			<Wrapper>
				<TouchableOpacity>
					<Wrapper>
						<Text style={{ fontSize: 20 }}>Picker in TouchableOpacity</Text>
						<StyledPicker>
							<Picker.Item label="1" value={1} />
							<Picker.Item label="2" value={2} />
						</StyledPicker>
					</Wrapper>
				</TouchableOpacity>
			</Wrapper>
		</Wrapper>
	);
};

```
### Screenshots

left Screenshot: clicked on Picker in TapGestureHandler
right Screenshot: clicked on Picker in TouchableOpacity

<div align="center"><img width='350' src='https://user-images.githubusercontent.com/33200064/100997235-55569b00-355a-11eb-88f3-f2d206d31e99.png'/>
<img width='350' src='https://user-images.githubusercontent.com/33200064/100997187-4839ac00-355a-11eb-8e72-1bb21b6a0cb8.png'/></div>

## Steps To Reproduce

--> code

### Expected behavior

right Screenshot

### Actual behavior

left Screenshot

## Snack or minimal code example

--> code

## Package versions

- React: 16.13.1
- React Native: 0.63.0
- React Native Gesture Handler: 1.7.0

**Comment by jakub-gonet** [comment]
Sorry for the late response.

This happens due to TapGH redirecting events to itself. There are `createNativeWrapper()` and `NativeViewGestureHandler` to allow adding custom components to RNGH gesture system. Wrapping ReactNativePicker in it should solve the problem.

Closing since this is likely resolved already. If you still experience this issue, please reply.
