### ISSUE TITLE
[Android] TextInput behind Absolutely positioned Views are focusable when you touch on the overlaid View  ?

### ISSUE THREAD

**Issue by a-eid** [software-mansion/react-native-gesture-handler#1265]
## Description

When covering some inputs with an absolute positioned View, they are focusable when you click on that View, it doesn't matter if that's a `View` `ScrollView` or a `Touchable` component

### Expected behavior

touches should be contained inside of the View, like on IOS

### Actual behavior

touches pass the view to the underlying views

I can reproduce this on android version 9

- React: 16.13.1
- React Native: 16.13.1
- React Native Gesture Handler: ^1.9.0

**Comment by mashish584** [comment]
@a-eid I'm facing the same issue. How you solved it?
