### ISSUE TITLE
Absolutely positioned ScrollView over another ScrollView dismisses the keyboard when scrolling the top ScrollView ?

### ISSUE THREAD

**Issue by a-eid** [software-mansion/react-native-gesture-handler#1269]
## Description

this might be a bit confusing, however when placing 2 scrollView over each others, & trying to scroll the top scrollView the keyboard dismisses, ( touches seem to be passing from the top scrollview to the bottom one some how .), this issue seem to happen only on ios. 

update:: actually it doesn't need to be absolutely positioned.

### Screenshots

![ghb](https://user-images.githubusercontent.com/19273413/101888363-b60f5480-3ba6-11eb-9f52-bc9329ed1253.gif)

notice as soon as I start scrolling the inner scrollview the keyboard dismissed, which is not the case for the outer scrollview.

## Steps To Reproduce

1. position one scrollview absolutely over the top of another scrollview. 
2. place an input adjacent to the absolutely positioned scrollview. 
3. try to scroll the inner scrollview when the input is focued, 

### Expected behavior

the keyboard should not dismiss as long as the interaction is scroll. 

### Actual behavior

the keyboard dismisses.

## Snack or minimal code example

https://snack.expo.io/kpX7CIchx

## Package versions

- React: 16.3.1
- React Native: 63.4
- React Native Gesture Handler: ^1.9.0

**Comment by kmagiera** [comment]
Hey @a-eid – thank you for reporting. I'm not entirely sure if this bug is really related to gesture-handler library. Can you confirm that the issue does not happen when importing ScrollView direclty from react-native and not gesture-handler? If so I'd also suggest playing with `keyboardDismissMode` props

**Comment by a-eid** [comment]
@kmagiera yes it does happen with RN 'scrollView'

**Comment by kmagiera** [comment]
if it happens with react-native's scroll view component it is unlikely this is an issue with gesture-handler library. Can you maybe post this issue on react-naitve's core repo then?
