### ISSUE TITLE
ios  build fail

### ISSUE THREAD

**Issue by Staryixing** [software-mansion/react-native-gesture-handler#1297]
The following build commands failed:
        CompileC /Users/macos/pro/newEnergyAndroid/ios/build/newEnergyAndroid/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNGestureHandler.build/Objects-normal/x86_64/RNPanHandler.o /Users/macos/pro/newEnergyAndroid/node_modules/react-native-gesture-handler/ios/Handlers/RNPanHandler.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

## Steps To Reproduce

1. npx react-native init AwesomeProject --version X.XX.X
2. npm install react-navigation
3. npm install react-native-reanimated react-native-gesture-handler react-native-screens react-native-safe-area-context @react-native-community/masked-view
4. cd ios; pod install
5. yarn react-native run-ios

## Package versions

- React:16.8.6
- React Native:0.60.5
- React Native Gesture Handler: 1.2.0

**Comment by jakub-gonet** [comment]
You have a fairly old version of RNGH. Check the latest version, there's high chance it was fixed in the next releases.

**Comment by sudheerpal** [comment]
I am also getting similar error, anyone can help me in solving this?

![image](https://user-images.githubusercontent.com/7983141/104154184-48a34d80-540a-11eb-9d57-9e19afd1b2d4.png)

**Comment by jakub-gonet** [comment]
@sudheerpal, could you post your RN, Xcode, and RNGH versions as well as the entire log **as text** (not only error you have in the screenshot) from `xcodebuild`?

**Comment by sudheerpal** [comment]
@jakub-gonet  Thanks, but i have resolved the issue by upgrading the xcode version.

I have a suggestion, the error should be self explanatory that version is causing issue. It took me a lot time to figure our the issue.

**Comment by jakub-gonet** [comment]
Sorry to hear that, but this error is related to Xcode build issue and you didn't post the error message, but information about files that failed to compile. We don't have any control of compile-time warnings so we can't make them more developer-friendly.
