### ISSUE TITLE
Swipeable used with FlatList, Animated, RectButton is not rending correctly after rotating the device (Portrait to Landscape, and back!)

### ISSUE THREAD

**Issue by fadmal** [software-mansion/react-native-gesture-handler#1304]
Swipeable (used with FlatList, Animated, and RectButton) is not rending correctly after rotating the device (Portrait to Landscape, and back!)... once the all is loaded in portrait mode, then the device is rotated to landscape, all is good till this stage... however, after rotating back the device to portrait again, on Android, the height of the listitems change with gaps shown in betwee, and on iOS some of the flatlist devider disappear!

- React: ~16.13.0
- React Native: 0.63.4
- React Native Gesture Handler: ~1.8.0

https://user-images.githubusercontent.com/74373075/104133061-cecb7f80-5389-11eb-9cda-77d92306578a.mp4

**Comment by Fcguedes** [comment]
I have the same error and don´t find any solution.

**Comment by Fcguedes** [comment]
@fadmal 
Hello man !
You can set Orientation.lockToPortrait(), for you, i think this resolve.
In my case i call other screen using navigation and i resolved using useIsFocused(import useIsFocused from '@react-navigation/native') and wait until screen finish loading.

For exemple:
```javascript 
const isFocused = useIsFocused();

isFocused && "my view content"
```

**Comment by j-piasecki** [comment]
Hi! I couldn't reproduce it on the Example app using the latest Gesture Handler ([4fb4e79](https://github.com/software-mansion/react-native-gesture-handler/commit/4fb4e794411c20e134ab2d73eb9a01c98d313c13)). If this still affects you, could you prepare a repository with a reproduction?
