### ISSUE TITLE
Unable to find node on an unmounted component error

### ISSUE THREAD

**Issue by zaharzagrava** [software-mansion/react-native-gesture-handler#1305]
=== Open the issue

### Screenshots

![image](https://user-images.githubusercontent.com/31539383/104320041-76f85a00-54ea-11eb-94f0-f8cf0140278e.png)

## Steps To Reproduce

1. Install the libraries listed below
2. Follow the [jest expo guideline](https://docs.expo.io/guides/testing-with-jest/)
3. Create two files below
4. Run jest

### Expected behavior

To render `TouchableOpacity`. `TouchableOpacity` from `react-native` renders just fine.

### Actual behavior

Throws error provided in Screenshots section.

## Minimal code example

Test file:

``` tsx
import React from 'react';
import { cleanup, render } from '@testing-library/react-native';
import { Gesture } from '../Gesture';

describe('HeaderRightButton filter', () => {
  afterEach(() => {
    jest.clearAllMocks();
    cleanup();
  });

  it('should render', () => {
    const { getByTestId } = render(<Gesture/>);
  });
});
```
Component file:

```tsx
import React, { FC } from 'react';
import { View, Text } from 'react-native';
import { TouchableOpacity } from 'react-native-gesture-handler';

export const Gesture: FC = () => {
  return (
    <View>
      <TouchableOpacity
        onPress={() => console.log('@1')}
      >
        <Text>asdf</Text>
      </TouchableOpacity>
    </View>
  );
};
```

## Package versions

- React: 16.13.1
- React Native: "react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz",
- React Native Gesture Handler: 1.8.0
- Ubuntu 20
- expo 40.0.0
- jest-expo: 40.0.1
- @testing-library/react-native: "7.1.0"
- react-test-renderer: 17.0.1
=== Open the issue

**Comment by tdekoning** [comment]
We have the exact same behavior.

**Comment by honia19** [comment]
The same

**Comment by hansdesmedt** [comment]
same here

**Comment by hansdesmedt** [comment]
I solved this issue by solving the warning using 'act'

`import { act } from 'react-test-renderer';`

`describe('When rendering xxx', () => {
  describe('With a random state', () => {
    beforeAll(() => {
      **act**(() => {
        store.dispatch(xxx.update(xxxMock));
        store.dispatch(yyy.update(yyyMock));
      });
    });
    it('should render it correctly', () => {
      expectToMatchSnapshot({ component: <xxx />, store });
    });
  });
});`

**Comment by jakub-gonet** [comment]
This problem is caused by missing rngh mocks. You can mock rngh components by yourself as a workaround.

**Comment by anlai2** [comment]
Any update on this? Are there specific rngh mocks that are missing that need to be added?

**Comment by iaurg** [comment]
I was facing the same issue, so I've updated `react-test-renderer` to version 17.0.2 and worked.

**Comment by anlai2** [comment]
@iaurg That worked for us, thanks!!

**Comment by GautierArcin** [comment]
Any update on it @jakub-gonet , @iaurg  ? I'm experiencing the exact same problem. Upgrading `react-test-renderer` to version `17.0.2` didn't worked. 😕

**My package version:**

    React: 17.0.2
    React Native: "react-native": "https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz",
    React Native Gesture Handler: 1.10.3
    Ubuntu 20
    expo 41.0.1
    jest-expo: 42.0.0
    @testing-library/react-native: "7.2.0"
    react-test-renderer: 17.0.2

**Comment by subhankarmaiti** [comment]
@iaurg upgrading `react-test-renderer` to the latest version (^17.0.2) works for me. But I was using `enzyme-adapter-react-16`. So I updated with [@wojtekmaj/enzyme-adapter-react-17](https://github.com/wojtekmaj/enzyme-adapter-react-17)

**Comment by WoLewicki** [comment]
Are you using the mocks, as documented here: https://docs.swmansion.com/react-native-gesture-handler/docs/guides/testing ?

**Comment by eprice122** [comment]
> Are you using the mocks, as documented here: https://docs.swmansion.com/react-native-gesture-handler/docs/guides/testing ?

This did not solve the problem for me.

**Comment by j-piasecki** [comment]
Hi! I tried the snippet from the post on Expo 44, but it seems to be working fine for me. If you are still experiencing this problem could you prepare a new reproduction?

Specific versions that I've used:
- expo@44.0.6
- jest-expo@44.0.1
- jest@26.6.3
- react-dom@17.0.1
- react-native-gesture-handler@2.1.3
- react-native@0.64.3
- react-test-renderer@17.0.2
- react@17.0.1

**Comment by marklanham** [comment]
One thing to check is that you’re using the latest syntax when trying to call `getByTestId`, instead use `findByTestId` as shown here: 
https://testing-library.com/docs/react-native-testing-library/example-intro/

The other thing thats caught me out a few times where I've needed to write multiple tests for a single component thats also thrown the error `Unable to find node on an unmounted component` was due to me placing the render function on the outside of the `it` function. It should in fact be inside the actual test itself, so for example if you're using `describe` and `it` then it should be like this:

```
import React from 'react';
import { render, screen } from '@testing-library/react-native';
import { ExampleComponent } from './ExampleComponent';

const props = {
  title: 'Example Title',
  body: 'Example body text',
};

describe('Example Component', () => {
  it('should match snapshot', async () => {
    render(<ExampleComponent {...props} />);
    expect(screen.toJSON()).toMatchSnapshot();
  });

  it('should render title', async () => {
    render(<ExampleComponent {...props} />);
    const exampleComponentTitle = await screen.findByTestId('example-component-title');
    expect(exampleComponentTitle).toBeDefined();
  });

  it('should render body', async () => {
    render(<ExampleComponent {...props} />);
    const exampleComponentBody = await screen.findByTestId('example-component-body');
    expect(exampleComponentBody).toBeDefined();
  });
});
```

**Comment by aghilann** [comment]
> I was facing the same issue, so I've updated `react-test-renderer` to version 17.0.2 and worked.

Thank you so much for this comment.
