### ISSUE TITLE
MacOS error

### ISSUE THREAD

**Issue by lh9403** [software-mansion/react-native-gesture-handler#1324]
TypeError: null is not an object (evaluating '_RNGestureHandlerModule.default.Direction')

    "react-native": "^0.63.4",
    "react-native-macos": "^0.63.4",
    "react-native-gesture-handler": "^1.9.0",

MacOS is not supported at this time？

**Comment by jim-at-jibba** [comment]
I am getting the same error. Any ideas?

**Comment by jim-at-jibba** [comment]
I had to clear all my caches, build etc and then it worked.

**Comment by jakub-gonet** [comment]
We don't support macOS directly but it should use web implementation.
