### ISSUE TITLE
FlingGestureHandler reports wrong coordinates on iOS

### ISSUE THREAD

**Issue by gianmarcotoso** [software-mansion/react-native-gesture-handler#1326]
I'm trying to implement swipe detection using FlingGestureHandler and, while working correctly on Android, I'm unable to get it to work on iOS as the `nativeEvent`'s properties `absoluteX` and `absoluteY` are always 0, and `x` and `y` always contain the same coordinates regardless of the state (if I swipe from left to right, for example, I would expect a different x value when the `status` is `ACTIVE` and when it's `END`). 

RN Version: 0.63.4
iOS Version: 14.3

```
function handleFling(event) {
    console.log(event.nativeEvent.x, event.nativeEvent.absoluteX, event.nativeEvent.status) 
    // Always the same x, absoluteX always 0!
}

return (
    <FlingGestureHandler
        direction={Directions.LEFT | Directions.RIGHT}
        onGestureEvent={handleFling}
        onHandlerStateChange={handleFling}>
         <View  style={{height: 300, width: 300, backgroundColor: 'red'}} />
    </FlingGestureHandler>
)
```

**Comment by judemorrissey** [comment]
hi team! +1 here, I experience the same issue as @gianmarcotoso, i would like to add that adding logging to my handler like
```
const onHandlerStateChange = useCallback(
    ({nativeEvent}) => {
      const {absoluteX, state} = nativeEvent;
      console.log('handler state', absoluteX, state, State);
      ...
```
yields the following on recognized flings:
```
[Wed Feb 24 2021 12:07:05.461]  LOG      handler state 0 4
[Wed Feb 24 2021 12:07:05.462]  LOG      handler state 0 5
[Wed Feb 24 2021 12:07:14.903]  LOG      handler state 0 4
[Wed Feb 24 2021 12:07:14.903]  LOG      handler state 0 5
```

notice how `State.BEGAN` nor `State.FAILED` never fire, only `State.ACTIVE` and `State.ENDED` as expected. Hope this is useful, thanks!

**Comment by gianmarcotoso** [comment]
@judemorrissey Thank you, I'll check it out!

**Comment by ShivamJoker** [comment]
This seems to work 
```js
<FlingGestureHandler
      direction={Directions.RIGHT}
      onHandlerStateChange={onSwipeRightHandlerStateChange}>
      <FlingGestureHandler
        direction={Directions.LEFT}
        onHandlerStateChange={onSwipeLeftHandlerStateChange}>
```

**Comment by walterholohan** [comment]
@ShivamJoker @judemorrissey does the above workaround work for you on Android?

**Comment by ShivamJoker** [comment]
@walterholohan no the above code doesn't work on android (works on iOS)

let me know if you have any solutions for that.

**Comment by judemorrissey** [comment]
@walterholohan @ShivamJoker most certainly works for our RN app on both Android and iOS

we are using react-native 0.63.3, react-native-gesture-handler 1.9.0

**Comment by ShivamJoker** [comment]
@judemorrissey I am wrapping it to a text input. Any workarounds ?

**Comment by judemorrissey** [comment]
@ShivamJoker using my sample code
```js
return (
    <View
      style={{
        backgroundColor: 'steelblue',
        flex: 1,
        alignItems: 'stretch',
        justifyContent: 'center',
      }}>
      <FlingGestureHandler
        direction={Directions.RIGHT}
        onHandlerStateChange={onSwipeRightHandlerStateChange}>
        <FlingGestureHandler
          direction={Directions.LEFT}
          onHandlerStateChange={onSwipeLeftHandlerStateChange}>
          <Text
            style={[
              styles.text,
              {backgroundColor: 'black'},
            ]}>{`Super long text to illustrate a point, we are at index ${currentIndex}`}</Text>
```

it worked great on Android emulator and on a physical device, so i would highly recommend double checking your package versions

https://user-images.githubusercontent.com/5974771/116736633-0005a500-a9a5-11eb-9d46-1ceb94c648da.mov

https://user-images.githubusercontent.com/5974771/116736871-58d53d80-a9a5-11eb-91ca-aedc9539c3d4.mp4

**Comment by judemorrissey** [comment]
@ShivamJoker ah! sorry i completely missed the `Input` part of `TextInput` -- i tried it out, but youre right, it does not work, i reckon the problem is due to the `TextInput` element having its touch handlers getting priority over the `FlingGestureRecognizer`

i tried it with `editable={false} scrollEnabled={false}` too but no luck, sorry i dont know how to resolve that specific limitation youre encountering!

**Comment by HadiKhalifeh** [comment]
@ShivamJoker  @gianmarcotoso Hello,

`   <FlingGestureHandler
        direction={Directions.UP}
        onHandlerStateChange={({ nativeEvent }) => {
          if (nativeEvent.state === State.ACTIVE) {
            this.animateSearch(false);
          }
        }}>
        <FlingGestureHandler
          direction={Directions.DOWN}
          onHandlerStateChange={({ nativeEvent }) => {
            if (nativeEvent.state === State.ACTIVE) {
              this.animateSearch(true);
            }
          }}>`

its working on ios devices but not for android

**Comment by ShivamJoker** [comment]
@HadiKhalifeh I know that and I told the same

**Comment by ShivamJoker** [comment]
@jakub-gonet can you please have a look ?
