### ISSUE TITLE
[TypeScript] Missing children prop on TouchableWithoutFeedback

### ISSUE THREAD

**Issue by balzdur** [software-mansion/react-native-gesture-handler#1341]
## Description

Last release introduced TS typings internals. It seems there is a miss on `TouchableWithoutFeedback` component.

> Make use of `Component<..>` or `React.PropsWithChildren` on type definition seems to raise the issue.

## Snack or minimal code example

```
import React from 'react';

import { View } from 'react-native';
import { TouchableWithoutFeedback } from 'react-native-gesture-handler';

export default () => (
  <TouchableWithoutFeedback>
    <View />
  </TouchableWithoutFeedback>
);4
```

### Expected behavior

No error, possibility to use `children` prop

### Actual behavior

TS Error raised on `TouchableWithoutFeedback`
```
Type '{ children: Element; }' has no properties in common with type 'IntrinsicAttributes & GenericTouchableProps & RefAttributes<GenericTouchable>'
```

## Package versions

- React Native Gesture Handler: `1.10.0`

**Comment by gigby** [comment]
The issue is still here:)
