### ISSUE TITLE
FlatList item is type any instead of being inferred

### ISSUE THREAD

**Issue by mcchrish** [software-mansion/react-native-gesture-handler#1349]
## Steps To Reproduce

1. Use FlatList component imported from gesture-handler

### Expected behavior
`item` parameter in `renderItem` should infer its type from `data` props.

### Actual behavior
`item` parameter in `renderItem` is type `any`.

## Snack or minimal code example

```tsx
import React from 'react'
import { View, Text } from 'react-native'
import { FlatList } from 'react-native-gesture-handler'

function Test(): React.ReactElement {
    const data = [
        {
            name: 'Hello'
        },
        {
            name: 'World'
        }
    ]
    return (
        <FlatList
            data={data} // data is { name: string }[]
            renderItem={({ item }) => { // item is any
                return (
                    <View>
                        <Text>{item.name}</Text>
                    </View>
                )
            }}
        />
    )
}
export default Test
```

## Package versions

- React: 16.13.1
- React Native: 0.63.4
- React Native Gesture Handler: 1.10.0

**Comment by jakub-gonet** [comment]
For reference: 
this is [part of the code](https://github.com/software-mansion/react-native-gesture-handler/blob/master/src/components/GestureComponents.tsx#L58-L68) that has to be changed but I don't know yet how to correctly cast it to type with a generic parameter. Currently, `React.forwardRef<RNFlatList<any>, RNFlatListProps<any>>` specify generic parameter as `any`, we need to cast forwardRef or create wrapper with generic type specified.

**Comment by mrousavy** [comment]
We summon you @wcandillon

**Comment by wcandillon** [comment]
Is there a failing test case that could be added for it? In Expo SDK the FlatList type definition looks like this:

```ts
  export class FlatList<ItemT> extends React.Component<
    NativeViewGestureHandlerProperties & FlatListProperties<ItemT>
  > {
    scrollToEnd: (params?: { animated?: boolean }) => void;
    scrollToIndex: (params: { animated?: boolean; index: number; viewOffset?: number; viewPosition?: number }) => void;
    scrollToItem: (params: { animated?: boolean; item: ItemT; viewPosition?: number }) => void;
    scrollToOffset: (params: { animated?: boolean; offset: number }) => void;
  }
```

**Comment by spyr0s** [comment]
Not sure if this commit broke something but in 1.7.0 i could use this
```
 <FlatList<number>
  {...{
  data: ids,
  keyExtractor: item => item.toString(),
  renderItem,
   }}
 />
```                    
with no problem.

In version 1.10.2 i got this error
`Expected 0 type arguments, but got 1.ts(2558)`

and the imported FLatList is of type 
`(alias) const FlatList: React.ForwardRefExoticComponent<RNFlatListProps<any> & React.RefAttributes<RNFlatList<any>>>`

in version 1.7.0 it was of type
`class FlatList<ItemT> import FlatList`

**Comment by jakub-gonet** [comment]
Yes, we migrated to TS in the codebase internally. @yfunk submitted a fix for this but it's unreleased right now. We should release a new version of RNGH in the following days.

**Comment by izakfilmalter** [comment]
This seems to still be a problem for me. Using the following:
```
"react-native": "0.63.4",
"react-native-gesture-handler": "1.10.3
```

![image](https://user-images.githubusercontent.com/5874330/139539462-75a5484d-5b86-4b38-ba0a-2f4526dd13f2.png)

**Comment by yfunk** [comment]
> This seems to still be a problem for me. Using the following:
> ```
> "react-native": "0.63.4",
> "react-native-gesture-handler": "1.10.3
> ```
> 
> ![image](https://user-images.githubusercontent.com/5874330/139539462-75a5484d-5b86-4b38-ba0a-2f4526dd13f2.png)
> 

The fix is on `master`, but there hasn't been a release in quite a while. You can try to consume the package from GitHub directly (at 9c7c91) or apply the fix in this commit using `patch-package`.
