### ISSUE TITLE
Android Crash with Tearing down gesture handler..

### ISSUE THREAD

**Issue by huurray** [software-mansion/react-native-gesture-handler#1363]
## Description

i use android simulator and suddenly app crashed
so i read android native log with 'npx react-native log-android'

and i got this error

[GESTURE HANDLER] Tearing down gesture handler registered for root view com.facebook.react.ReactRootView{8864868 V.E...... ......ID 0,0-1440,2672}

i couldn't any other problem or clue without this error message.

how can i fix this??
(i only check android simulator not real device yet)

- React: 16.13.1
- React Native: 0.63.4
- React Native Gesture Handler: 1.10.1

**Comment by jakub-gonet** [comment]
Please attach stacktrace of the crash and, if possible, small repro for it.

We log some things when initializing and removing gesture handler so this message is normal.

Closing until more information is added.

**Comment by CHANDRAMOHANnegi** [comment]
Failed to print error:  Cannot read properties of undefined (reading 'apply')

2023-05-11 19:26:31.595 31512-31512 ReactNative             com.my                     I  [GESTURE HANDLER] Tearing down gesture handler registered for root view com.facebook.react.ReactRootView{2b3512c V.E...... ......ID 0,0-1440,2420 #1} 

App unresponsive on updating to reanimated 3

react-native : "0.69.7"
"react-native-gesture-handler": "2.9.0" or "2.10.0"
"react-native-reanimated": "^3.1.0"
