### ISSUE TITLE
Jest broken: "Cannot read property 'Direction' of undefined" in 1.10.1

### ISSUE THREAD

**Issue by lukewlms** [software-mansion/react-native-gesture-handler#1368]
## Description

This issue is happening consistently in tests as of 1.10.1.  Reverting to 1.9.0, with no other changes (or a previous version) fixes the issue.

> Cannot read property 'Direction' of undefined

### Screenshots

![image](https://user-images.githubusercontent.com/19214773/108164315-e12c9c00-7133-11eb-88b5-70764c0a3811.png)

## Steps To Reproduce

1.Run Jest tests involving react-native-gesture-handler in 1.10.1?  I don't have a minimal repro but there are at least [several other users experiencing this](https://github.com/software-mansion/react-native-gesture-handler/issues/1335#issuecomment-778544112): 

### Expected behavior
Tests pass

### Actual behavior
Tests break because of this error message

## Snack or minimal code example

(I just reverted to 1.9.0 - I'm hoping this is clear enough and someone can quickly diagnose based on the diff.)

## Package versions

- React: react@16.13.1
- React Native: react-native@0.63.4
- React Native Gesture Handler: 1.10.1

**Comment by MuhammadMuzammilQadri** [comment]
I confirm this issue is indeed happening in 1.10.1. Just went back to 1.9.0

**Comment by jakub-gonet** [comment]
Does replacing `node_modules/react-native-gesture-handler/jestSetup.js` with this content:

```js
import { View, ScrollView } from 'react-native';

const NOOP = () => {
  // do nothing
};

const mockModule = {
    ScrollView,
    PanGestureHandler: View,
    attachGestureHandler: NOOP,
    createGestureHandler: NOOP,
    dropGestureHandler: NOOP,
    updateGestureHandler: NOOP,
    Direction: {
      RIGHT: 1,
      LEFT: 2,
      UP: 4,
      DOWN: 8,
    },
    State: {
      BEGAN: 'BEGAN',
      FAILED: 'FAILED',
      ACTIVE: 'ACTIVE',
      END: 'END',
      UNDETERMINED: 'UNDETERMINED',
    }};

jest.mock('./src/RNGestureHandlerModule', () => mockModule);
jest.mock('./dist/src/RNGestureHandlerModule', () => mockModule);
```
resolve this issue for you?

**Comment by joshua-smith4** [comment]
> Does replacing `node_modules/react-native-gesture-handler/jestSetup.js` with this content:
> 
> ```js
> import { View, ScrollView } from 'react-native';
> 
> const NOOP = () => {
>   // do nothing
> };
> 
> const mockModule = {
>     ScrollView,
>     PanGestureHandler: View,
>     attachGestureHandler: NOOP,
>     createGestureHandler: NOOP,
>     dropGestureHandler: NOOP,
>     updateGestureHandler: NOOP,
>     Direction: {
>       RIGHT: 1,
>       LEFT: 2,
>       UP: 4,
>       DOWN: 8,
>     },
>     State: {
>       BEGAN: 'BEGAN',
>       FAILED: 'FAILED',
>       ACTIVE: 'ACTIVE',
>       END: 'END',
>       UNDETERMINED: 'UNDETERMINED',
>     }};
> 
> jest.mock('./src/RNGestureHandlerModule', () => mockModule);
> jest.mock('./dist/src/RNGestureHandlerModule', () => mockModule);
> ```
> 
> resolve this issue for you?

This fixed the issue for me!

**Comment by lukewlms** [comment]
> Does replacing `node_modules/react-native-gesture-handler/jestSetup.js` with this content:
> 
> ```js
> import { View, ScrollView } from 'react-native';
> 
> const NOOP = () => {
>   // do nothing
> };
> 
> const mockModule = {
>     ScrollView,
>     PanGestureHandler: View,
>     attachGestureHandler: NOOP,
>     createGestureHandler: NOOP,
>     dropGestureHandler: NOOP,
>     updateGestureHandler: NOOP,
>     Direction: {
>       RIGHT: 1,
>       LEFT: 2,
>       UP: 4,
>       DOWN: 8,
>     },
>     State: {
>       BEGAN: 'BEGAN',
>       FAILED: 'FAILED',
>       ACTIVE: 'ACTIVE',
>       END: 'END',
>       UNDETERMINED: 'UNDETERMINED',
>     }};
> 
> jest.mock('./src/RNGestureHandlerModule', () => mockModule);
> jest.mock('./dist/src/RNGestureHandlerModule', () => mockModule);
> ```
> 
> resolve this issue for you?

Thanks - yes, my tests also fully pass with this patch on 1.10.1.

**Comment by honia19** [comment]
@jakub-gonet Could you create PR to fix this issue?

**Comment by jakub-gonet** [comment]
Yup, I'll try to release the fix on Mon/Tue.

**Comment by NSNJRGL** [comment]
@jakub-gonet Sorry, I did what you did but It wasn't work. Could you represent your guide?

**Comment by jakub-gonet** [comment]
Please attach logs from jest, I can't help you with that. Alternatively, you can wait with the upgrade until we release RNGH.

**Comment by jakub-gonet** [comment]
1.10.2 was released yesterday, you should try upgrading RNGH.

**Comment by NSNJRGL** [comment]
Thank you for release. It works. @jakub-gonet

**Comment by lukewlms** [comment]
Also confirmed, thanks a lot!
