### ISSUE TITLE
SectionList scrolling

### ISSUE THREAD

**Issue by karo-dc** [software-mansion/react-native-gesture-handler#1380]
## Description

Scrolling not working in SectionList component

1. I have found working examples with FlatList, but with SectionList it is not working.

### Expected behavior
Vertical scrolling.

### Actual behavior
Vertical scrolling not working.

## Snack or minimal code example
```js
<SectionList
  bounces={false}
  style={...}
  sections={options}
  renderItem={({ item }) => (
    <PanGestureHandler onGestureEvent={handler}>
      <Animated.View style={animatedStyles}>
        <TouchableWithoutFeedback onPress={onPress}>
          <View>...</View>
        </TouchableWithoutFeedback>
      </Animated.View>
    </PanGestureHandler>
  )}
  stickySectionHeadersEnabled={false}
  keyExtractor={(item) => `${item.id}`}
/>
```
## Package versions

- React:
- React Native: 0.63.4
- React Native Gesture Handler: ^1.10.1

**Comment by karo-dc** [comment]
@jakub-gonet can you please take a look?

**Comment by jakub-gonet** [comment]
So if I understand correctly, PanGH takes the touch stream to handle it by itself instead of forwarding it to the list?

What happens if you swap the scroll component with our ScrollView?

Then you can use `waitFor` in ScrollView or Pans (depends on what you want to achieve).
Below there's a sketch of how you can do it.
```js
import {ScrollView} from 'react-native-gesture-handler'
...
const [panRefs, setPanRefs] = React.useState([]);

React.useEffect(() => {
  setElRefs(elRefs => (
    Array(data).fill().map((_, i) => panRefs[i] || createRef())
  ));
}, [data]);

return (
	  <SectionList
	    bounces={false}
	    style={...}
	    sections={options}
	    renderScrollComponent={(scrollProps) => <ScrollView {...scrollProps} waitFor=panRefs/>
	    renderItem={({ item }) => (
	      <PanGestureHandler onGestureEvent={handler}>
	        <Animated.View style={animatedStyles}>
	          <TouchableWithoutFeedback onPress={onPress}>
	            <View>...</View>
	          </TouchableWithoutFeedback>
	        </Animated.View>
	      </PanGestureHandler>
	    )}
	    stickySectionHeadersEnabled={false}
	    keyExtractor={(item) => `${item.id}`}
	  />
);
```

**Comment by karo-dc** [comment]
Thanks for respond, so I have added this option to <PanGestureHandler activeOffsetX={[-10, 10]} > now it works, strange for me.

**Comment by jakub-gonet** [comment]
Oh well. I'll close the issue in that case.

**Comment by saaspeter** [comment]
@karo-dc , I use your solution, it works, Unbelievable 4 years later, this solution still works in version 2.20.2, thank you.  But I cannot understand why it works, maybe it is a bomb if I upgrade the package in future versions, maybe the bomb will come out.
