### ISSUE TITLE
This module unconditionaly includes node.d.ts for RN and this bring incorrect typings in project.

### ISSUE THREAD

**Issue by vovkasm** [software-mansion/react-native-gesture-handler#1384]
## Description

With latest update to react-native-gesture-handler@1.10.2, I discover some types errors. For example `setInterval` return type changed from `number` to `NodeJS.Timeout`.
After running fresh typescript version with `--explainFiles` option I got this:
```
node_modules/@types/node/index.d.ts
  Type library referenced via 'node' from file 'node_modules/react-native-gesture-handler/lib/typescript/components/touchables/GenericTouchable.d.ts' with packageId '@types/node/index.d.ts@14.14.31'
```
It is clearly incorrect. RN code should not be same environment as node.js )

Actual core refers to `NodeJS.Timeout` here: https://github.com/software-mansion/react-native-gesture-handler/blob/1.10.2/src/components/touchables/GenericTouchable.tsx#L58-L60
```typescript
// TODO: maybe can be better
// TODO: all clearTimeout have ! added, maybe they shouldn't ?
type Timeout = null | NodeJS.Timeout | undefined;
```

Can I, as a response to TODO comment, suggest to use this instead?
```typescript
type Timeout = ReturnType<typeof setTimeout>
```

**Comment by soh335** [comment]
@jakub-gonet I think node is still included. Can you check it ? https://github.com/software-mansion/react-native-gesture-handler/pull/1415
