### ISSUE TITLE
BaseButtonProps  is not exported from ./components/GestureButtons

### ISSUE THREAD

**Issue by florello-tbox** [software-mansion/react-native-gesture-handler#1388]
## Description

The addition of `module` in the package.json ( https://github.com/software-mansion/react-native-gesture-handler/pull/1360/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R16 ) appear to have broken my setup with react-native-web:

```
node_modules/react-native-gesture-handler/lib/module/index.js 12:0-14:91
Attempted import error: 'BaseButtonProps' is not exported from './components/GestureButtons'.
```

Just removing it is enough for me to make it work; is this an intentional breaking change?

## Package versions

- React: 17.0.1
- React Native: 0.64.0-rc.3
- React Native Gesture Handler: 1.10.2

**Comment by jakub-gonet** [comment]
Nope, this is an accidental change. `BaseButtonProps` should be export as a type only and stripped after transpiling to JS.
