### ISSUE TITLE
no such file or directory, lstat '/node_modules/react-native-gesture-handler/Swipeable.js'

### ISSUE THREAD

**Issue by orzhtml** [software-mansion/react-native-gesture-handler#1393]
## Description

no such file or directory, lstat '/node_modules/react-native-gesture-handler/Swipeable.js'

## Steps To Reproduce

1.

## Package versions

- React:
- React Native:
- React Native Gesture Handler: 1.10.3

**Comment by jakub-gonet** [comment]
Please run metro bundler with `--reset-cache` flag. This file was moved to other place and seems like your environment still tries to resolve an old one. If that doesn't solve your issue, please attach more information by filling issue template.
