### ISSUE TITLE
PanGestureHandler does not 'waitFor' LongPressGestureHandler.

### ISSUE THREAD

**Issue by GiridharKarnik** [software-mansion/react-native-gesture-handler#1400]
## Description

A view has been encapsulated with both `PanGestureHandler` and `LongPressGestureHandler`. The PanGestureHandler has a [waitFor](https://docs.swmansion.com/react-native-gesture-handler/docs/interactions#awaiting-other-handlers) pointing at the ref of the LongPressGestureHandler.

The goal was to activate panning only after the user has long pressed on the view, and I think this is what the docs suggest as well.

## Steps To Reproduce

1. Clone the repo and start the app with `yarn start` and then `yarn android`.

### Expected behavior

The 'panning' should begin only after the long press is triggered.

### Actual behavior

'panning' is enabled by default.

## Snack or minimal code example

Here is the [repo](https://github.com/GiridharKarnik/DraggableList)

## Package versions

- React: 16.13.1
- React Native: 0.63.4
- React Native Gesture Handler: 1.10.3

**Comment by j-piasecki** [comment]
Sorry for such a late answer but it's working as intended. The `waitFor` prop stands for 'wait until those handlers fail' not 'wait until those handlers activate'. In your case when you touch the screen both handlers transition to the `BEGAN` state and when you start panning the `LongPressGestureHandler` fails thus allowing `PanGestureHandler` to activate.
Unfortunately the behavior you are expecting is not possible to accomplish right now, but we are working on Gesture Handler 2.0, which will make something like you are describing possible.

**Comment by matis-dk** [comment]
@j-piasecki Do you have any estimation for when Gesture Handler 2.0 will be released?

**Comment by j-piasecki** [comment]
@matis-dk We hope to release it soon but unfortunately I do not have a solid timeframe yet.
