### ISSUE TITLE
Unable to start animation, surface is null or no children.

### ISSUE THREAD

**Issue by Yuweiai** [software-mansion/react-native-gesture-handler#1407]
## Description

When I use Swipeable for Android, it tells me "Unable to start animation, surface is null or no children". Then, the app exits from rn page, back to native page.

### Expected behavior
don't crash 

### Actual behavior
crash and exit from rn page

### Android log
03-16 13:49:42.049   822  2506 E CamX    : [ERROR][NCS    ] camxncsservice.cpp:587 EnqueueJob() Can not enqueue jobs when thread is stopped
03-16 13:49:42.049   822  2506 W CamX    : [ WARN][NCS    ] camxncsintfqsee.cpp:2289 FillSensorData() Buffer queue for sensor 7 has been freed: bufh=0x0, bufsize=1248, stride=4
03-16 13:49:42.149   822  2506 E CamX    : [ERROR][NCS    ] camxncsservice.cpp:587 EnqueueJob() Can not enqueue jobs when thread is stopped
03-16 13:49:42.149   822  2506 W CamX    : [ WARN][NCS    ] camxncsintfqsee.cpp:2289 FillSensorData() Buffer queue for sensor 7 has been freed: bufh=0x0, bufsize=1248, stride=4
03-16 13:49:42.487 15819 16465 D  [DEBUG BEGIN] softap : send success:  {"msgId":"123","version":"123","method":"searchReq"} [DEBUG END]
03-16 13:49:42.499   822  2506 E CamX    : [ERROR][NCS    ] camxncsservice.cpp:587 EnqueueJob() Can not enqueue jobs when thread is stopped
03-16 13:49:42.499   822  2506 W CamX    : [ WARN][NCS    ] camxncsintfqsee.cpp:2289 FillSensorData() Buffer queue for sensor 7 has been freed: bufh=0x0, bufsize=1248, stride=4
03-16 13:49:42.721   692 13401 D OemNetd : setLimit: enable, rate=4268869
03-16 13:49:42.729 16358 16377 I ontentextensio: ProcessProfilingInfo new_methods=0 is saved saved_to_disk=0 resolve_classes_delay=8000
03-16 13:49:42.808  1686  1756 W WindowManager:  to start animation, surface is null or no children.

- React: 16.11.0
- React Native: 0.62.0
- React Native Gesture Handler: ^1.9.0

**Comment by jakub-gonet** [comment]
Could you provide some repro example? Swipeables are working fine in our example app.

**Comment by j-piasecki** [comment]
Hi! If this is still affecting you, could you please provide a reproduction? As Jakub said, in the Example app they are working fine.
