### ISSUE TITLE
Not Working with react-native-web

### ISSUE THREAD

**Issue by learncodingforweb** [software-mansion/react-native-gesture-handler#1410]
**WARNING in ./node_modules/react-native-gesture-handler/lib/module/components/GestureHandlerButton.js 2:29-51
export 'requireNativeComponent' (imported as 'requireNativeComponent') was not found in 'react-native-web/dist/index'**

```
const HtmlWebpackPlugin = require('html-webpack-plugin');
const path = require('path');

module.exports = {
  mode: 'development',
  entry: './src/index.js',
  output: {
    path: path.resolve(__dirname, './release'),
    filename: 'bundle.js',
  },
  plugins: [
    new HtmlWebpackPlugin({
      filename: 'index.html',
      template: './index.html',
    }),
  ],
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        include: [
          path.resolve('src'),
          path.resolve('node_modules/react-native-gesture-handler'),
        ],
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['@babel/preset-env', '@babel/preset-react'],
            plugins: ['babel-plugin-react-native-web'],
          },
        },
      },
    ],
  },
  devServer: {
    contentBase: path.join(__dirname, 'release'),
    compress: true,
    port: 4000,
  },
  resolve: {
    alias: {
      'react-native$': 'react-native-web',
    },
  },
};
```

**Comment by jakub-gonet** [comment]
This is connected to your webpack config which loads `.js` before `.web.js`. Make sure you load `.web` prefixed files first.

**Comment by learncodingforweb** [comment]
Was doing wrong webpack.config, after including .web.js on top list in webpack.extension, issue get solved

**Comment by mikehardy** [comment]
Side note for anyone else that lands here from a search on the error message. My react-native-web was initialized correctly from the react-native-web+typescript template https://github.com/plaut-ro/luna but my problem was just missing the clearly documented (thank you!) step to get jest setup, so I was getting this on my jest run

https://docs.swmansion.com/react-native-gesture-handler/docs/#testing - follow the lovely docs and eliminate the error

Cheers
