### ISSUE TITLE
Documentation tips gave me the not working result

### ISSUE THREAD

**Issue by RandGor** [software-mansion/react-native-gesture-handler#1423]
I did everything according to the advices: https://docs.swmansion.com/react-native-gesture-handler/docs/#installation

But every time I have output:
```
 BUNDLE  ./index.js

 ERROR  react-native-gesture-handler module was not found. Make sure you're running your app on the native platform and your code is linked properly (cd ios && pod install && cd ..).

For installation instructions, please refer to https://docs.swmansion.com/react-native-gesture-handler/docs/#installation
```

My project was built on https://github.com/inspmoore/rnw_boilerplate_nav but I have updated every library https://github.com/RandGor/RG_rnw_boilerplate_nav

As you can see I have already updated the MainActivity class.

```
package com.rnwboilerplate;

import com.facebook.react.ReactActivity;
import com.facebook.react.ReactActivityDelegate;
import com.facebook.react.ReactRootView;
import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;

public class MainActivity extends ReactActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "rnwboilerplate";
    }

    @Override
    protected ReactActivityDelegate createReactActivityDelegate() {
        return new ReactActivityDelegate(this, getMainComponentName()) {
            @Override
            protected ReactRootView createRootView() {
                return new RNGestureHandlerEnabledRootView(MainActivity.this);
            }
        };
    }
}
```

But it didn't work for me. What do you think? Would you recommend me any external repo with the correct usage of this library?

**Comment by jakub-gonet** [comment]
Could you please share your project? It's hard to say without seeing the code but my guess are stale Gradle / metro caches. Try running `./gradlew clean` in your `android/` directory and running metro via `yarn start --reset-cache`.

**Comment by RandGor** [comment]
@jakub-gonet thank you! The problem was solved by including this library into Gradle
