### ISSUE TITLE
Cannot Archive project due to RNGestureHandlerManager pod

### ISSUE THREAD

**Issue by perdona** [software-mansion/react-native-gesture-handler#1424]
## Description

After upgrading RN to 0.64, I cannot archive my app using Xcode, as it fails while building, complaining about RNGestureHandlerManager.h

### Screenshots

![Screen Shot 2021-04-05 at 19 18 43](https://user-images.githubusercontent.com/7670956/113633685-c068c900-9643-11eb-9da7-947c994e2b9a.png)

## Steps To Reproduce

1. Update env to latest
2. Upgrade RN to 0.64
3. Update Podfile
4. Run pod install
5. Try to archive app using Xcode

### Expected behavior

Build should pass and generate archive

### Actual behavior

Build fails with error above

## Package versions

- React Native: 0.64 (latest)
- React Native Gesture Handler: 1.6.0

**Comment by vsheyanov** [comment]
@perdona I just submitted a similar issue (https://github.com/software-mansion/react-native-gesture-handler/issues/1425), I have more details if you want to check.
Did you try upgrading `react-native-gesture-handler` to `10.3`?

**Comment by jakub-gonet** [comment]
Try the standard way of removing caches from node_modules/metro/pods/ios.
[I created a new RN 64 project](https://github.com/jakub-gonet/rngh_rn_64_issue_1425) and it archives without problems.
![image](https://user-images.githubusercontent.com/12465392/113727482-73ddc600-96f5-11eb-950f-44f10e3f14c2.png)

If you can, please attach the reproduction repository so I can test it locally.

**Comment by jakub-gonet** [comment]
If you still have problems with that issue please reply in this thread.
