### ISSUE TITLE
Tap on Switch inside TouchableOpacity not working

### ISSUE THREAD

**Issue by ezhkov** [software-mansion/react-native-gesture-handler#1428]
## Description

I have TouchableOpacity row and Switch inside. When I tap on Switch nothing happens. The same thing using React Native TouchableOpacity works as expected.

### Expected behavior

Switch will change its state

### Actual behavior

Nothing happens

## Snack or minimal code example

https://snack.expo.io/@ezhkov/rngh-nested-touchable-android-bug

## Package versions

- React: 16.11.0
- React Native: 0.62.2
- React Native Gesture Handler: 1.10.3

**Comment by jakub-gonet** [comment]
Use `Switch` exported from RNGH.
