### ISSUE TITLE
unable to access 'https://github.com/naver/hammer.js.git/': Failed to connect to github.com port 443: Timed out

### ISSUE THREAD

**Issue by jinshiyi11** [software-mansion/react-native-gesture-handler#1431]
## Description
when `yarn install` react-native-gesture-handler,we got   
`fatal: unable to access 'https://github.com/naver/hammer.js.git/': Failed to connect to github.com port 443: Timed out` 
error

### Screenshots
![image](https://user-images.githubusercontent.com/3433961/115232620-815d6c00-a149-11eb-9fa2-43053663168a.png)

we can't install react-native-gesture-handler correctly in China unless use vpn.

## Package versions

- React: 16.8.6
- React Native: 0.60.5
- React Native Gesture Handler: 1.5.6

**Comment by jakub-gonet** [comment]
Try updating to a newer gesture handler (the earliest that shouldn't have this problem is 1.6.0), we use another fork of hammerjs which is located on npm instead of github.

So if I understand correctly, Github is timing out so you had to use VPN to file an issue in this repo?

**Comment by jinshiyi11** [comment]
> Try updating to a newer gesture handler (the earliest that shouldn't have this problem is 1.6.0), we use another fork of hammerjs which is located on npm instead of github.
> 
> So if I understand correctly, Github is timing out so you had to use VPN to file an issue in this repo?

After update to 1.6.0, I can install successfully.Thanks!
