### ISSUE TITLE
Module not found: Can't resolve 'react-native-web/dist/exports/Animated' in 'C:\Users\User\node_modules\react-native-gesture-handler\lib\module\components'

### ISSUE THREAD

**Issue by sareme** [software-mansion/react-native-gesture-handler#1432]
- React:
- React Native:
- React Native Gesture Handler:

**Comment by jakub-gonet** [comment]
Could you please fill out the issue template? We can't fix this error based on this message alone.

**Comment by sareme** [comment]
know it fixed. it was 2 version of package
