### ISSUE TITLE
gesture handler null ref props on expo web

### ISSUE THREAD

**Issue by vantreeseba** [software-mansion/react-native-gesture-handler#1433]
## Description

When using the PanGestureHandler component, the ref props internally is null causing the onGestureEvent to be null and fail on web builds.

### Screenshots
Code
![image](https://user-images.githubusercontent.com/316782/115302952-9970c380-a128-11eb-8c53-189cf1865bad.png)

Error output
![image](https://user-images.githubusercontent.com/316782/115303000-abeafd00-a128-11eb-9c60-32ab05c13624.png)

## Steps To Reproduce

1. Attach a PanGestureHandler to a view and try to drag.

### Expected behavior
That onGestureEvent method would be called.

### Actual behavior

onGestureEvent is null.

## Snack or minimal code example

https://snack.expo.io/@vantreeseba/web-ongestureevent-error

## Package versions

- React: 16.13.1
- React Native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz
- React Native Gesture Handler: ~1.8.0

**Comment by jakub-gonet** [comment]
Please don't screenshot code, embed it in the [code blocks](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).

Have you tried upgrading react-native-gesture-handler to 1.9.0+? I think #1220 should fix this problem.

**Comment by vantreeseba** [comment]
Good point about the code, sorry about that.

I upgraded 1.10.x and it fixed this issue.

Not sure why expo installed an older version, but everything seems to be working well now.

**Comment by jakub-gonet** [comment]
Cool, closing then.
