### ISSUE TITLE
[PanGestureHandler][FlatList]  how to let PanGestureHandler to take over when FlatList has reached the top

### ISSUE THREAD

**Issue by KingAmo** [software-mansion/react-native-gesture-handler#1436]
## Description

```
import {FlatList, PanGestureHandler} from 'react-native-gesture-handler';

 <PanGestureHandler>
  <FlatList />
 </PanGestureHandler>

```

 I want the PanGestureHandler to take over when FlatList has reached the top, any help please?

## Steps To Reproduce

1.

## Package versions

- React:
- React Native:
- React Native Gesture Handler:

**Comment by KingAmo** [comment]
in fact i want to implement a `pull-to-refresh-FlatList`, any suggestions would be appreciated?

**Comment by jakub-gonet** [comment]
Check this comment (and the entire thread):
https://github.com/software-mansion/react-native-gesture-handler/issues/420#issuecomment-837752503
