### ISSUE TITLE
Increase compileSdkVersion to 30

### ISSUE THREAD

**Issue by pvegh** [software-mansion/react-native-gesture-handler#1461]
We want to move to Java 11 in our project updating these lines:
sourceCompatibility JavaVersion.VERSION_1_8

We have a build error because react-native-gesture-handler is still compiling with < 30:
compileSdkVersion safeExtGet('compileSdkVersion', 28)

We see this error:
In order to compile Java 9+ source, please set compileSdkVersion to 30 or above

Please update compileSdkVersion to 30, so that we can use update Java 11.

Maybe also even switch to:
sourceCompatibility JavaVersion.VERSION_11

**Comment by pvegh** [comment]
Actually there is even older things in android/lib:
  compileSdkVersion 23
    buildToolsVersion '25.0.0'

**Comment by pvegh** [comment]
This seems to be the last library holding us back from switching to Java 11.

**Comment by jakub-gonet** [comment]
I'm afraid `compileSdkVersion=30` is too new. At the time of writing, the newest Android version is 12, SDK 30 was introduced in Android 11. RN officially is still Java 8 based but seems like it's Java 11 in RN 68. I'll keep this issue open when the times come but don't expect any upgrades soon. You can use [`patch-package`](https://www.npmjs.com/package/patch-package) to apply your patch locally.

**Comment by kmagiera** [comment]
hi @pvegh – gesture-handler library tries to use sdk/compile versions provided by the projects where it is being build. The part that does this is the line you posted `compileSdkVersion safeExtGet('compileSdkVersion', 28)` – it only uses version 28 if no version is provided by the project.

If you want your project to be build with version 30, you should have that version set in `ext` settings in your gradle project. See how we use it in an example app here: https://github.com/software-mansion/react-native-gesture-handler/blob/0a47981f0c32438d1a312e213869b3381e624824/example/android/build.gradle#L8

This should also resolve similar problems you may have with other libraries as this is a standard way of dealing with build tool versions across many react-native libs.
