### ISSUE TITLE
FlatList content disappears if bottom tab change during momentum scroll

### ISSUE THREAD

**Issue by noumantahir** [software-mansion/react-native-gesture-handler#1473]
## Description

When flatlist is in momentum scroll, list content disappears if tab is changed using bottom navigation and come back to initial tab. The content immediately comes back on any interaction with flatlist.

### Screenshots
https://user-images.githubusercontent.com/6298342/119342363-6af98180-bcae-11eb-8089-76c5022bc78a.mov

## Steps To Reproduce

1. Drag flat list,
2. Quickly change bottom tab while list is in momentum scroll
3. Come back to FlatList tab
4. content is disappeared

```
<FlatList
              ref={flatListRef}
              data={posts}
              showsVerticalScrollIndicator={false}
              renderItem={_renderItem}
              keyExtractor={(content, index) => `${content.author}/${content.permlink}-${index}`}
              removeClippedSubviews
              onEndReachedThreshold={1}
              maxToRenderPerBatch={9}
              initialNumToRender={9}
              windowSize={15}
              onEndReached={_onEndReached}
              onMomentumScrollBegin={() => {
                _onEndReachedCalledDuringMomentum = false;
              }}
 />
```

```
    const _renderItem = ({ item, index }:{item:any, index:number}) => {
             return (
              <PostCard
                key={`${item.author}-${item.permlink}`}
                content={item}
          />
      };
```

## Package versions

- React:16.9.0
- React Native:0.61.0
- React Native Gesture Handler:1.9.1
- react-navigation-tabs: 2.6.2

**Comment by tomekzaw** [comment]
Hello @noumantahir! Which part of this issue seems to be related to react-native-gesture-handler? Did you manage to resolve the problem? Since the flatlist doesn't appear immediately after tab change, it sounds reasonable to suspect that the issue is more likely related to react-navigation-tabs. Maybe you should try reporting the issue in their repo?
