### ISSUE TITLE
TapGestureHandler maxDist not working on Android

### ISSUE THREAD

**Issue by inferusvv** [software-mansion/react-native-gesture-handler#1483]
## Steps To Reproduce

1. Create event handler:

```
  const eventHandler = useAnimatedGestureHandler<any>({
    onStart: e => {
      pressed.value = true;
    },
    onEnd: () => {
      pressed.value = false;
    },
    onFail: () => {
      pressed.value = false;
      console.log('onFail');
    },
  });
```

2. Attach to `TapGestureHandler` and set `maxDist` prop:

```
    <TapGestureHandler maxDist={50} maxDurationMs={10000} onGestureEvent={eventHandler}>
        // ...
    </TapGestureHandler>
```

### Expected behavior

Property affects Android behaviour and onFail called if finger is far from the button

### Actual behavior

It works only on iOS. On Android onFail called right after finger goes out from button on 1px

## Package versions

- React: 17.0.1
- React Native: 0.64.1
- React Native Gesture Handler: 1.10.3

**Comment by j-piasecki** [comment]
Hi! Is this issue still affecting you? If so, could you provide a reproduction?

**Comment by inferusvv** [comment]
Hi, I'll try to check it soon

**Comment by inferusvv** [comment]
Seems to be everything is fine now. I am closing issue. Thanks
