### ISSUE TITLE
GestureHandler already initialized for root view

### ISSUE THREAD

**Issue by mezalejandro** [software-mansion/react-native-gesture-handler#1484]
## Description

In firebase I have errors that come to me about this:

### Screenshots
<img width="929" alt="Screen Shot 2021-06-14 at 14 43 13" src="https://user-images.githubusercontent.com/568141/121935532-e6cf7280-cd1e-11eb-9756-988387b25e76.png">

## Snack or minimal code example
On my index root:
`import 'react-native-gesture-handler'`

## Package versions

- React: 17.0.1
- React Native: 0.64.0
- React Native Gesture Handler: ^1.10.3

**Comment by sherif95** [comment]
@mezalejandro  I have the same issue. Did you find any solution?

**Comment by mezalejandro** [comment]
Hello @sherif95 , in my case I have installed rnfirebase and react-native-push-notifications and I think there is a conflict between these two libraries

**Comment by ikimiler** [comment]
I have the same.
System:
    OS: Windows 10 10.0.22000
    CPU: (6) x64 Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
      API Levels: 23, 27, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7322048
    Visual Studio: Not Found
  Languages:
    Java: 1.8.0_291
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.0 => 0.63.0
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by AppSphere** [comment]
I have the same issue. 
React-Native: 0.64
React Native Gesture Handler: ^1.10.3

**Comment by tomekzaw** [comment]
@mezalejandro `RNGestureHandlerEnabledRootView` caused a lot of problems and we deprecated it with Gesture Handler v2.0 in favor of `<GestureHandlerRootView>` component.

Can you please upgrade to the latest version (`^2.3.2`), place `<GestureHandlerRootView>` component in the root of your app (see instructions [here](https://docs.swmansion.com/react-native-gesture-handler/docs/installation#js)) and check if it works for you? Don't worry, React Native Gesture Handler v2 is still backward-compatible with the old API (`PanGestureHandler` etc.) so you don't need to rewrite the whole app.
