### ISSUE TITLE
RectButton doesn't call onPress callback

### ISSUE THREAD

**Issue by MarufSharifi** [software-mansion/react-native-gesture-handler#1492]
## Package versions

- React:  17.0.1
- React Native: 0.64.1
- React Native Gesture Handler: ^1.10.3

**Comment by oxilor** [comment]
Does not work only in Android? Try to wrap your code in the [`GestureHandlerRootView` component](https://docs.swmansion.com/react-native-gesture-handler/docs/#for-library-authors). I tested it a few hours ago, and it works if your `RectButtoon` is [not placed in a Modal](https://github.com/software-mansion/react-native-gesture-handler/issues/139).

**Comment by MarufSharifi** [comment]
> Does not work only in Android? Try to wrap your code in the [`GestureHandlerRootView` component](https://docs.swmansion.com/react-native-gesture-handler/docs/#for-library-authors). I tested it a few hours ago, and it works if your `RectButtoon` is [not placed in a Modal](https://github.com/software-mansion/react-native-gesture-handler/issues/139).

but it worked with React Native: 0.64.2. thanks for reply

**Comment by oxilor** [comment]
`RectButton` works well using your package versions:
* "react": "17.0.1",
* "react-native": "0.64.1",
* "react-native-gesture-handler": "^1.10.3"

See [this repo](https://github.com/oxilor/rngh-modal-bug). In the second example uses the `RectButton` that works correctly in a screen. If you try to click on this button, the `onPress` callback will be called, and the Modal will be opened.

**Comment by jakub-gonet** [comment]
It should be resolved then.
