### ISSUE TITLE
Capture touchs using `onStartShouldSetResponderCapture` doesn't prevent `PanGestureHandler`

### ISSUE THREAD

**Issue by mhammerc** [software-mansion/react-native-gesture-handler#1496]
## Description

Hello all! We've been using `react-native-gesture-handler` in many projects with great success 😋 Thanks for this project!

I am not sure what I am going to describe is a feature, an inconsistency or a bug.

I have the following which wrap my entire app (simplified for the example ofc):

```js
<View
  style={{width: '100%', height: '100%'}}
  onStartShouldSetResponderCapture={() => true}
  onMoveShouldSetResponderCapture={() => true}
>
    {children}
</View>
```

Then, I have a `PanGestureHandler` down the tree, working in pair with `react-native-reanimated`.

[`onStartShouldSetResponderCapture`](https://reactnative.dev/docs/view#onstartshouldsetrespondercapture) and [`onMoveShouldSetResponderCapture`](https://reactnative.dev/docs/view#onmoveshouldsetrespondercapture) allow respectively to capture start and move of touches, and prevent it from being passed down the tree.

It does work in the sense all my regular `Pressable` components stops responding. But my `PanGestureHandler` keeps working as usual.

Using [`pointerEvents="none"`](https://reactnative.dev/docs/view#pointerevents) does successfully prevent the `PanGestureHandler` from capturing touches!

I am unaware if this is expected behavior or not. I need this feature to allow for efficient touch captures.
Setting the prop `pointerEvents` is delayed by react `setState`; it add enough delay to allow the user to swipe for a few milliseconds and break the UI consistency.

To solve this, I think I will create a boolean ref which represent whether touches should be disabled and manually ignore the PanGestureHandler moves while it is true.

I searched for `onStartShouldSetResponderCapture` and `onMoveShouldSetResponderCapture` in previous issues without success.

I am available if I can provide any help.

Thanks,
Have a great day!

## Package versions

- Only tested this on iOS, maybe Android behave differently.
- React: `17.0.1`
- React Native: `0.64.2`
- React Native Gesture Handler: `1.10.3`
- React Native Reanimated: `2.2.0`

**Comment by j-piasecki** [comment]
Hi! Those methods are part of the [React Native's Gesture Responder System](https://reactnative.dev/docs/gesture-responder-system) and are not supported by Gesture Handler. Unfortunately, I think the workaround you mentioned will have to be enough.
