### ISSUE TITLE
React native gestures nested in PanGestureHandler

### ISSUE THREAD

**Issue by Navipro70** [software-mansion/react-native-gesture-handler#1502]
## Description

React native gesture not working in PanGestureHandler

## Steps To Reproduce

1. Wrap PanGestureHandler over React Native panResponder (in our case it slider from @miblanchard/react-native-slider).
2. Try drag slider (@miblanchard/react-native-slider use React Native Animated API).

### Expected behavior

When drag out of the area of slider, PanGestureHandler take event, but when drag slider, react native panResponder handle event (PanGestureHandler wait for it and at the same time it's disabled). 

### Actual behavior

When drag start, PanGestureHandler from react-native-gesture-handler intercepts the event of gesture, and events on slider stops.

## Snack or minimal code example

```
import React, {useRef} from 'react';
import {PanGestureHandler} from 'react-native-gesture-handler';
import Animated from 'react-native-reanimated'
import {Slider} from '@miblanchard/react-native-slider';

<PanGestureHandler onGestureEvent={onGestureEvent}>
  <Animated.View>
    <View style={{height: 200}}>
    <Slider onValueChanged={onValueChanged} />
    <View style={{height: 200}}/>
  </Animated.View>
</PanGestureHandler>

```

## Package versions

- React: 17.0.1
- React Native: 0.64.0
- React Native Gesture Handler: 1.10.3

**Comment by kuzzmi** [comment]
Same issue happens with me with these versions:

- "react-native": "0.66.0",
- "react": "16.13.1",
- "react-native-gesture-handler": "1.9.0",

**Comment by Navipro70** [comment]
@kuzzmi 
The only solution is write your own animated component with react-native-reanimated instead of react-native :(

**Comment by kuzzmi** [comment]
> @kuzzmi
> The only solution is write your own animated component with react-native-reanimated instead of react-native :(

I actually did exactly that. But because the issue is with gestures, I only used react-native-gesture-handler and Animated from react-native. This way all works well for me

**Comment by Navipro70** [comment]
If I'm correctly understood, you rewrite independent logic with react-native instead of rn-reanimated. But that a problem, I think if screen is loaded, we want to use reanimated as a part, but for this case can't

**Comment by kmagiera** [comment]
Hi all. The provided description isn't entirely clear, and apparently the code snippet is far from being a complete example. Please consider positing a full example app or link to repo / snack such that we don't need to make any guesses about the issue which would allow us to spend more time on resolving the actual problem.
