### ISSUE TITLE
react-native ios - react-native-gesture-handler module was not found

### ISSUE THREAD

**Issue by MOwais** [software-mansion/react-native-gesture-handler#1547]
## Description

react-native-gesture-handler module not found in iOS. Please see screenshot below. 

I am repeatedly getting this error in iOS despite having already installed the package a dozen times. "Module not found" is a common error and usually means the package is not installed. I have faced this error millions of times and installing the missing module makes it go away. But not in this case. I am not sure what is going on. I have deleted node_modules folder, cleaned cache and reinstalled the packages and pods more times than I can count. I have even upgraded to XCODE BETA and still I am getting the same issue. I then downgraded back to XCODE 12.5.1 and same thing.

Note - We have been using this package for several years now without issue then this just started happening recently. Also everything works fine in Android. This issue is only in iOS.

### Screenshots
<img width="323" alt="Screen Shot 2021-08-10 at 12 48 03 PM" src="https://user-images.githubusercontent.com/7787941/128900401-1c9637df-aec5-4736-ac6d-2d9b5c942ad9.png">

## Steps To Reproduce

1. npm install 
2. cd ios && pod install
2. clean build in XCODE
3. run project in XCODE to launch app on simulator/device

### Expected behavior
Module is found, app launches in iOS simulator/device.

### Actual behavior
Module is not found

## Package versions

    "react-native-gesture-handler": "^1.10.3",
	"react-native": "0.62.2",
	"react": "16.11.0",

**Comment by jakub-gonet** [comment]
>  "Module not found" is a common error and usually means the package is not installed.

In this case, means that the JS source loaded properly but RNGH didn't register its native module.
If Android is working fine I think you may have changed some configuration of your iOS project. Try deintegrating & reinstalling Pods project (`pod deintegrate && pod install`). You may also try to import RNGH on the top of your `index.js` file - it helped some people with missing RNGH native module in the past.

> Note - We have been using this package for several years now without issue then this just started happening recently.

Are you able to pinpoint when this changed? Was it after RNGH upgrade? If not, have you tried `git bisect`ing your project to find what change could break it?

**Comment by MOwais** [comment]
@jakub-gonet thanks for the prompt response. pod deintegrate definitely seems to have done something as I had not tried this before. I am no longer getting the module not found error but getting this error instead so I am back to debugging.

TypeError: null is not an object (evaluating '_RNGestureHandlerModule.default.Direction')

<global>
    Directions.js:3:15
loadModuleImplementation
    require.js:321:11
<global>
    GestureHandler.js:2
loadModuleImplementation
    require.js:321:11
<global>
    Swipeable.js:10
loadModuleImplementation
    require.js:321:11
<global>
    index.js:1
loadModuleImplementation
    require.js:321:11
<global>
    GestureHandlerNative.js:4
loadModuleImplementation
    require.js:321:11
<global>
    GestureHandler.ios.js:1
loadModuleImplementation
    require.js:321:11
<global>
    StackView.js:9
loadModuleImplementation
    require.js:321:11
<global>
    index.js:12
loadModuleImplementation
    require.js:321:11
<global>
    index.js:1
loadModuleImplementation
    require.js:321:11
<global>
    navigation.js:5
loadModuleImplementation
    require.js:321:11
<global>
    App.js:10
loadModuleImplementation
    require.js:321:11
<global>
    index.js:6
loadModuleImplementation
    require.js:321:11
guardedLoadModule
    require.js:201:44
global code
    index.bundle?platform=ios&dev=true&minify=false:272266:3

**Comment by jakub-gonet** [comment]
This means that the native module was loaded but for some reason, it can't access its functions. Try cleaning the build artefacts from XCode and running packager with `--reset-cache` flag.

**Comment by MOwais** [comment]
Still no joy. I tried the commands below, then deintegrated and reinstalled pods, cleaned xcode build and started packager with --reset-cache flag:

watchman watch-del-all && 
rm -rf $TMPDIR/react-native-packager-cache-* &&
rm -rf $TMPDIR/metro-bundler-cache-* && 
rm -rf node_modules/ 
&& npm cache clean --force &&
npm install && 
npm start -- --reset-cache

**Comment by jakub-gonet** [comment]
I'm afraid I won't be able to help without having some repro. If this project is public, please add a link to it. If it's not and if you want to, you may drop me an email (jakub.gonet at swmansion.com) so we can try resolving this outside of Github.

I'll close this one since it's most likely connected to your setup.

**Comment by MOwais** [comment]
Okay thanks for your help! It is most likely an issue specific to my local setup. I will try and create a reproducible demo app and get back to ya.
