### ISSUE TITLE
Rewrite examples

### ISSUE THREAD

**Issue by jakub-gonet** [software-mansion/react-native-gesture-handler#1564]
## Description

Current examples are really old and show random parts of API.
We need to structure them a bit and show mostly everything the library has to offer.
We don't want to abandon class components but would be nice if most of the examples were written using hooks.

Specifically, we need:
1. Learning examples
	Ones that can be copied & pasted and experimented with. Should be pretty minimal and simple but simultaneously using important RGHN APIs (interactions, refs, handler activation conditions, etc).

2. Recipes
	Showing common use-cases: creating a list with draggable items, pinch-pan-zoom-able image, dragging the scrollView when on top, pairing RNGH with Reanimated and other community libraries (like react-native-maps or bottom-sheet).

3. Showcases
	Using RNGH to the fullest, creating complex interactions between elements.

4. Test cases
	Used to manually test the library before release.

## PRs

- #1587

**Comment by WoLewicki** [comment]
Since #1587 has been merged, I think we can close it. Feel free to comment here if I am wrong and we can always reopen it then.
