### ISSUE TITLE
Remove GH native library on Android

### ISSUE THREAD

**Issue by jakub-gonet** [software-mansion/react-native-gesture-handler#1565]
## Description

We didn't release the native Android RNGH library for few versions and seems like it's not really used.
Merging Android & RN interfaces would simplify Android RNGH implementation a bit. We should also remove NativeAndroid examples.
- #1585
- #1586

**Comment by TheWirv** [comment]
What does this exactly mean? This lib won't support Android at all anymore? Also, how are you guys getting the impression that it "seems like it's not really used"?

**Comment by TheWirv** [comment]
Oooohh, well that makes a lot of sense. Thanks for the clarification! 👌🏼
