### ISSUE TITLE
failOffset / maxDelta not working

### ISSUE THREAD

**Issue by moaazassali** [software-mansion/react-native-gesture-handler#1588]
## Description
I am using the DraggableBox demo provided for some testing but both failOffset and maxDelta properties are not working. On Android, the component cannot be dragged anymore and on iOS nothing happens and it can be dragged as if the property is not set.

## Steps To Reproduce

1. Open https://snack.expo.dev/CeVXtiJFs
2. Go to the index.js file of draggable folder
3. Add failOffsetX={[-200,200]} as a prop to PanGestureHandler component
4. Try dragging the component 

### Expected behavior
I am expecting that the component should fail in recognizing the gesture after moving 200 point units and stop being dragged.

### Actual behavior
For Android, the dragging function of the component stops working and it cannot be moved anymore.
For iOS, the prop has no impact on the component and it can be dragged just like before.

## Snack or minimal code example
https://snack.expo.dev/CeVXtiJFs
Index.js file in draggable folder and follow steps to reproduce section

## Package versions

- React: react@17.0.1
- React Native: react-native@0.64.2
- React Native Gesture Handler: react-native-gesture-handler@1.10.3

**Comment by j-piasecki** [comment]
You were right that `failOffset` doesn't work properly on Android, however the expected behavior is the one you saw on the iOS. If you check the docs for the PanGestureHandler, it says:
```
When the finger moves outside this range (in points) along X axis and handler hasn't yet activated it will fail recognizing the gesture. ...
```
You can drag it just fine because the default value for `minDist` (the minimum distance the pointer has to move before the activation) is close to 0. If you were to set the `minDist` prop to something more than in the `failOffsetX` it would fail when dragged along the X axis, but would activate after dragging it diagonally or vertically.
Here's the example for that:
```ts
import React, { Component } from 'react';
import { Animated, StyleProp, StyleSheet, View, ViewStyle } from 'react-native';

import {
  PanGestureHandler,
  State,
  PanGestureHandlerStateChangeEvent,
  PanGestureHandlerGestureEvent,
} from 'react-native-gesture-handler';

type DraggableBoxProps = {
  minDist?: number;
  boxStyle?: StyleProp<ViewStyle>;
};

export class DraggableBox extends Component<DraggableBoxProps> {
  private translateX: Animated.Value;
  private translateY: Animated.Value;
  private lastOffset: { x: number; y: number };
  private onGestureEvent: (event: PanGestureHandlerGestureEvent) => void;
  constructor(props: DraggableBoxProps) {
    super(props);
    this.translateX = new Animated.Value(0);
    this.translateY = new Animated.Value(0);
    this.lastOffset = { x: 0, y: 0 };
    this.onGestureEvent = Animated.event(
      [
        {
          nativeEvent: {
            translationX: this.translateX,
            translationY: this.translateY,
          },
        },
      ],
      { useNativeDriver: true }
    );
  }
  private onHandlerStateChange = (event: PanGestureHandlerStateChangeEvent) => {
    if (event.nativeEvent.oldState === State.ACTIVE) {
      this.lastOffset.x += event.nativeEvent.translationX;
      this.lastOffset.y += event.nativeEvent.translationY;
      this.translateX.setOffset(this.lastOffset.x);
      this.translateX.setValue(0);
      this.translateY.setOffset(this.lastOffset.y);
      this.translateY.setValue(0);
    }
  };
  render() {
    return (
      <PanGestureHandler
        {...this.props}
        onGestureEvent={this.onGestureEvent}
        onHandlerStateChange={this.onHandlerStateChange}
        failOffsetX={[-200, 200]}
        minDist={220}>
        <Animated.View
          style={[
            styles.box,
            {
              transform: [
                { translateX: this.translateX },
                { translateY: this.translateY },
              ],
            },
            this.props.boxStyle,
          ]}
        />
      </PanGestureHandler>
    );
  }
}

export default class Example extends Component {
  render() {
    return (
      <View style={styles.scrollView}>
        <DraggableBox />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  scrollView: {
    flex: 1,
  },
  box: {
    width: 150,
    height: 150,
    alignSelf: 'center',
    backgroundColor: 'plum',
    margin: 10,
    zIndex: 200,
  },
});
```
