### ISSUE TITLE
Inconsistent state changes of handlers between platforms

### ISSUE THREAD

**Issue by j-piasecki** [software-mansion/react-native-gesture-handler#1590]
## Description

There are some inconsistencies between gesture handlers on Android and iOS. Most notably some gesture handlers on iOS skip the `BEGAN` state and either go directly from `UNDETERMINED` to `ACTIVE` or don't send state change event at all in case of gesture failure.

### More specific examples
`TapGestureHandler`
Android:
 - Tap: `UNDETERMINED` -> `BEGAN` -> `ACTIVE` -> `END`
 - Touch and hold: `UNDETERMINED` -> `BEGAN` -> `FAILED`
 - Touch and move: `UNDETERMINED` -> `BEGAN` -> `ACTIVE` -> `END` if the gesture is shorter than `maxDelayMs` or `UNDETERMINED` -> `BEGAN` -> `FAILED` otherwise

iOS:
 - When the finger touches the screen it goes from `UNDETERMINED` (or `END` if it's not the first touch) to `BEGAN`. Then when the finger stops touching the screen it goes: `UNDETERMINED` -> `BEGAN` -> `END`.

`LongPressGestureHandler`
Android:
 - Tap: `UNDETERMINED` -> `BEGAN` -> `FAILED`
 - Touch and hold: `UNDETERMINED` -> `BEGAN` -> `ACTIVE` -> `END`
 - Touch and hold; move before activation: `UNDETERMINED` -> `BEGAN` -> FAILED
 - Touch and hold; move after activation: `UNDETERMINED` -> 'BEGAN` -> `END` -> `CANCELLED`

iOS:
 - Tap: (nothing)
 - Touch and hold: `UNDETERMINED` -> `ACTIVE` -> `END`
 - Touch and hold; move before activation: (nothing)
 - Touch and hold; move after activation: `UNDETERMINED` -> `ACTIVE` -> `END`

`PanGestureHandler`:
Android:
 - Pan: `UNDETERMINED` -> `BEGAN` -> `ACTIVE` -> `END`
 - Tap: `UNDETERMINED` -> `BEGAN` -> `FAILED`

iOS:
 - Pan: `UNDETERMINED` -> `BEGAN` -> `ACTIVE` -> `END`
 - Tap: (nothing)

`FlingGestureHandler`
Android:
 - Fling: `UNDETERMINED` -> `BEGAN` -> `ACTIVE` -> `END`
 - Touch and hold, or move slowly: `UNDETERMINED` -> `BEGAN` -> `FAILED`

iOS:
 - Fling: `UNDETERMINED` -> `ACTIVE` -> `END`
 - nothing otherwise

`RotationGestureHandler`:
Android:
 - Rotation: `UNDETERMINED` -> `BEGAN` -> `ACTIVE` -> `END`
 - Tap with one finger: (nothing)
 - Tap with two fingers: (nothing)

iOS:
 - Rotation: `UNDETERMINED` -> `BEGAN` -> `ACTIVE` -> `END`
 - Tap with one finger: `UNDETERMINED` -> `BEGAN` -> `FAILED`
 - Tap with two fingers: `UNDETERMINED` -> `BEGAN` -> `END`

`PinchGestureHandler`:
Android:
 - Pinch: `UNDETERMINED` -> `BEGAN` -> `ACTIVE` -> `END`
 - Tap with one finger: `UNDETERMINED` -> `BEGAN` -> `FAILED`
 - Tap with two fingers: `UNDETERMINED` -> `BEGAN` -> `FAILED`

iOS:
 - Pinch: `UNDETERMINED` -> `BEGAN` -> `ACTIVE` -> `END`
 - Tap with one finger: `UNDETERMINED` -> `BEGAN` -> `FAILED`
 - Tap with two fingers: `UNDETERMINED` -> `BEGAN` -> `END`

## Package versions

- React: 17.0.2
- React Native: 0.64.1
- React Native Gesture Handler: 1.10.3

**Comment by scousino** [comment]
I'm currently not seeing Pan even fire the Undetermined state, my logs only show Began -> Active -> End

Same package versions

**Comment by j-piasecki** [comment]
The state flow has been improved with the release of Gesture Handler 2.0. Pinch and Rotation still have some differences, but overhauling them requires major changes in how gestures are handled on Android. I don't think we want to do this right now, as it has a potential to break existing interactions.
