### ISSUE TITLE
Support RN 0.65.1

### ISSUE THREAD

**Issue by maystrenkoYurii** [software-mansion/react-native-gesture-handler#1606]
in debug mode GestureHandlerRootView handled errors
<img width="706" alt="Снимок экрана 2021-08-27 в 21 03 55" src="https://user-images.githubusercontent.com/23016311/131170177-84eddf85-37b5-4e3f-9b82-cf0d4c2b6edd.png">

**Comment by aalhitennf** [comment]
I'm using "react-native-gesture-handler": "^1.10.3" with "react-native": "^0.65.1" without problems.

**Comment by maystrenkoYurii** [comment]
@aalhitennf this bug only android in debug mode

**Comment by betoharres** [comment]
i don't think this issue is related to this library. You can trigger the same errors just by creating a fresh new project and trying to use the `style` prop on a Text component while debugging on Android. 
I've already opened an issue on react-native repo

**Comment by jakub-gonet** [comment]
Adding to that, stack trace doesn't relate to RNGH at all.
