### ISSUE TITLE
TapGestureHandler blocking PinchGestureHandler 

### ISSUE THREAD

**Issue by Bayramito** [software-mansion/react-native-gesture-handler#1630]
## Description

I have TapGestureHandlers in PinchGestureHandler. To be able to double click and image and pinch zoom it.
But somehow i can zoom the image without triggering my tap gestures , everything is OK untill here. but when i double tap on it it fires the double tap event, after that i cant pinch zoom anymore.

## Snack or minimal code example

THIS IS THE DOUBLE TAP CONTENT

`
const DoubleTapContent = inject("social")(
  observer(({social, children, onDoubleTap, onSingleTap, value, pinch}) => {
    const double = useRef();
    const scale = useSharedValue(0);
    const [unlike, setUnLike] = useState(null);
    const rStyle = useAnimatedStyle(() => {
      return {
        transform: [{scale: Math.max(scale.value, 0)}],
      };
    });

    const onDoubleTapHandle = useCallback(() => {
      onDoubleTap();
      if (!value) {
        scale.value = withSpring(1, animationcConfig, isFinished => {
          if (isFinished) {
            scale.value = withDelay(500, withSpring(0, animationcConfig));
          }
        });
        setUnLike(false);
      } else {
        setUnLike(true);
      }
    }, [value]);
    return (
      <TapGestureHandler simultaneousHandlers={pinch} waitFor={double} onActivated={onSingleTap}>
        <TapGestureHandler maxDelayMs={250} ref={double} numberOfTaps={2} onActivated={onDoubleTapHandle}>
          <Animated.View style={styles().container}>
            <Animated.Image
              pointerEvents="none"
              source={imagesMain.white_heart}
              style={[styles().image, rStyle]}
              resizeMode="center"
            />
            {children}
            {unlike && <LottieView style={styles().image} source={animations.heart_break} autoPlay loop={false} />}
          </Animated.View>
        </TapGestureHandler>
      </TapGestureHandler>
    );
  }),
);
`

AND THIS IS THE PARENT OF IT THE PINCH COMPONENT WHERE I USED THE TAPS IN;

`
<PinchGestureHandler {...pinchGestureHandler}>
          <Animated.View
            style={{
              zIndex,
              width: SIZEX,
              height: SIZEY,
            }}
          >
            <DoubleTapContent value={data.like_me} onSingleTap={() => {}} onDoubleTap={handleLike}>
              <Animated.Image
                style={[
                  styles().image,
                  {
                    transform: [...translate(pinch), ...transformOrigin(origin, {scale})],
                  },
                ]}
                source={source}
              />
            </DoubleTapContent>
          </Animated.View>
  </PinchGestureHandler>
`

## Package versions
- React: 17.0.1
- React Native: 0.64.2
- React Native Gesture Handler: 1.8.0

**Comment by kmagiera** [comment]
hi @Bayramito – thanks for reporting the issue. I think the problem in your case might be that the first Tap does not have a view underneath. When nesting handlers with 1.x API you need to place views in between handler components such that each handler has a corresponding view.

This, however, has changed in gesture-handler 2.0 where you only need one GestureDetector component and can place as many handlers as you wish. Therefore I'd suggest migrating your project to the new API (it is backward compatible so you don't have to migrate it in all the places where you use gesture-handler) and if that's something you cannot do, then to try placing View's in between Tap handlers.
