### ISSUE TITLE
[Android] TouchableNativeFeedback is broken on React Native 0.65

### ISSUE THREAD

**Issue by PedroSSM2000** [software-mansion/react-native-gesture-handler#1631]
## Description

TouchableNativeFeedback doesnt unmount the overlay after consecutive presses, causing the ripple opacity to stay as if the finger never left. This also causes the other touchables to not display any ripples.
## Steps To Reproduce

Create any component with TouchableNativeFeedback

### Expected behavior

ripple opacity fades when finger leaves the button

### Actual behavior

https://gifyu.com/image/Jl0I

## Snack or minimal code example

import React from 'react';
import {SafeAreaView} from 'react-native';
import {TouchableNativeFeedback} from 'react-native-gesture-handler';

export default function App() {
  return (
    <SafeAreaView
      style={{
        flex: 1,
        alignContent: 'center',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'gray',
      }}>
      <TouchableNativeFeedback
        background={TouchableNativeFeedback.Ripple('#000000')}
        useForeground={true}
        style={{backgroundColor: 'white', width: 100, height: 100}}
      />
      <TouchableNativeFeedback
        background={TouchableNativeFeedback.Ripple('#000000')}
        useForeground={true}
        style={{backgroundColor: 'white', width: 100, height: 100}}
      />
      <TouchableNativeFeedback
        background={TouchableNativeFeedback.Ripple('#000000')}
        useForeground={true}
        style={{backgroundColor: 'white', width: 100, height: 100}}
      />
    </SafeAreaView>
  );
}

the same code works on snack because i assume it is running RN 0.63

im pretty sure regular buttons with ripple have the same problem.

## Package versions

- React: 17.0.2
- React Native: 0.65.1
- React Native Gesture Handler: 1.10.3

**Comment by PedroSSM2000** [comment]
After four hours, I "fixed" it by wrapping my app in a <GestureHandlerRootView>

It's strange because on expo you don't need to do it.

**Comment by jakub-gonet** [comment]
Expo wraps your app with the root view on the native side so you don't have to do it by yourself.
Seems resolved.
