### ISSUE TITLE
Installation instructions are not clear

### ISSUE THREAD

**Issue by aditya-keri-betterhalf** [software-mansion/react-native-gesture-handler#1634]
## Description

Tried to upgrade to the latest version of this library and found that the installation instructions are not clear.
Following are the areas that need more clarity :

1. We need to add the GestureHandlerRootView component and wrap our main component with it. But there's no mention of how to import it. I had to go to the example/ folder in the repo to find that.
2. There's a caution statement that says : _From version 2.0.0 this step isn't needed. You should use <GestureHandlerRootView /> component instead._
But the latest version is 1.10.3. Why is there a comment about version 2.0.0 ? This is very confusing.
3. If we wrap the root component with GestureHandlerRootView, are the changes to `MainActivity.java` no longer required ?
4. Do we still need to do import `'react-native-gesture-handler';` in our `index.js` even if we're using `GestureHandlerRootView` ?

I followed the installation instructions from here : https://docs.swmansion.com/react-native-gesture-handler/docs/#installation

## Package versions
1.10.3

**Comment by rafahuaman** [comment]
I also would like some clarity. Thank you 🙏🏽

**Comment by yfunk** [comment]
Seems like documentation was already updated for the currently in development `2.0.0` version of this library.

While it would definitely be helpful to have versioned docs like with Reanimated once the new version nears release, you can always check out the `docs/docs/` folder at a specific tag (e.g. [`1.10.3`](https://github.com/software-mansion/react-native-gesture-handler/tree/1.10.3/docs/docs)) for documentation on that release. 

For installation instructions its probably best to follow [`getting-started.md@1.10.3`](https://github.com/software-mansion/react-native-gesture-handler/blob/1.10.3/docs/docs/getting-started.md) right now to avoid confusion.

**Comment by smashercosmo** [comment]
I'm especially interested in the answer to the 4th question raised here:
> Do we still need to do import 'react-native-gesture-handler'; in our index.js even if we're using GestureHandlerRootView

Could somebody please clarify that? Latest version of the docs still include this step.

**Comment by smashercosmo** [comment]
@kmagiera I saw you made some changes to docs. Maybe you could clear things up?

**Comment by j-piasecki** [comment]
Hi! The docs should be cleaned up at this point. I'll close this issue, and if you see more issues with the docs, feel free to open a new one.

**Comment by smashercosmo** [comment]
@j-piasecki 
> Do we still need to do import 'react-native-gesture-handler'; in our index.js even if we're using GestureHandlerRootView ?

This is still not clear from the docs

**Comment by se1exin** [comment]
Hi, love the library, but I'm getting this error and this thread on this issue does not clarify the solution at all - apparently someone "cleanup up the docs" at some point, but that really means nothing to us in the future that stumble across this thread for the solution.

> Hi! The docs should be cleaned up at this point.

What was the change to the docs at this point? Do we, or do we not, `import 'react-native-gesture-handler;` in our index.js`?

Is there something else we need to do to fix this error?
