### ISSUE TITLE
Unable to pass testID prop to RectButton

### ISSUE THREAD

**Issue by nextlevelbeard** [software-mansion/react-native-gesture-handler#1661]
`testID` prop on `RectButton` component does not take effect.
Furthermore, `accessible` prop also appears to suffer from the same issue.
With RN 0.64.

```jsx
<RectButton testID="test">
```

**Comment by bsmith-self** [comment]
Any movement on adding one or both of these props? We are also trying to test our RN app with Appium, and this seems like a pretty simple passthrough. I might be willing to make a PR myself if the maintainers would be open to that

**Comment by fcoradini** [comment]
I am working with React Native/Appium and required the ID for my selectors.
I was able to achieve this using `accessibilityLabel` on `RectButton`.

`accessibilityLabel` on React Native generates `accessibility-id` on both Android and iOS ([ref](https://blog.stackademic.com/appium-inspector-demystified-a-guide-to-selecting-elements-on-react-native-2cd3e3c60809))

```
"react-native": "0.72.6",
"react-native-gesture-handler": "~2.12.0",
````

**Comment by dgreasi** [comment]
I am having the same using while trying to test the app with Maestro. The `testID` is available in `iOS` but not in `Android`.

I am guessing something is off.

My workaround is quite similar with the above recommendations. 

For now I am using `accessibilityLabel` in the `View` I have inside `RectButton` since the `RectButton` itself doesn't accept an `accessibilityLabel`.

```
"react-native": "0.72.5",
"react-native-gesture-handler": "^2.16.0",
```

**Comment by m-bert** [comment]
Hi @nextlevelbeard! Does this problem occur only with `appium`? I've just created new RN app and run tests right away. They did pass as expected. Could you tell us more about your setup? Or, if it would be possible, create a reproduction repository?

@bsmith-self 

> I might be willing to make a PR myself if the maintainers would be open to that

We are open to that 😅

**Comment by nextlevelbeard** [comment]
@m-bert It's been 3 years since I reported this and I am no longer working with React Native, cannot help unfortunately.

**Comment by marcin-bojar** [comment]
@m-bert what about other components? I just hit an issue where after wrapping components with `GestureDetector` all occurrences of `testID`s for `<Pressable>` components have been removed 🤦

**Comment by m-bert** [comment]
As far as I know, @latekvo is working in `Pressable` in tests 😅
