### ISSUE TITLE
Unexpected token in src/index.ts on Expo 42

### ISSUE THREAD

**Issue by bfarrgaynor** [software-mansion/react-native-gesture-handler#1663]
## Description

I am unable to run a managed expo project using Expo 42 (latest as of this writing) and gesture handler 1.10.2.

Running expo start produces this error:

```
SyntaxError: /Users/redacted/Projects/239-001/node_modules/react-native-gesture-handler/src/index.ts: Unexpected token (5:12)

  3 | export { default as gestureHandlerRootHOC } from './gestureHandlerRootHOC';
  4 | export { default as GestureHandlerRootView } from './GestureHandlerRootView';
> 5 | export type {
    |             ^
  6 |   // event types
  7 |   GestureEvent,
  8 |   HandlerStateChangeEvent,
```

## Steps To Reproduce

1.

## Package versions

- React: 16.13.1
- React Native: (expo sdk 42) 
- React Native Gesture Handler: 1.10.2

**Comment by Mihai-github** [comment]
Having the same issue... +1

**Comment by Mihai-github** [comment]
> I've also ran into this same issue when upgrading from SDK 39. Clearing the cache doesn't seem to have fixed the issue for me.

have you solved the problem?

**Comment by thahaac** [comment]
Having same issue with expo 42

**Comment by thahaac** [comment]
Updating @babel/core and @babel/runtime fixed for me as mentioned in #1374.

**Comment by Mihai-github** [comment]
> Updating `@babel/core` and `@babel/runtime` fixed for me as mentioned in #1374.

Hi, indeed I've found this 1h ago helping me in another problem and indeed it works just fine. 👍

**Comment by Lugeyoalg** [comment]
how do we update @babel/core and @babel/runtime please?

**Comment by Frontend-dev-sarah** [comment]
My problem is solved temporarily by deleting type from the package directly: which is ../node_modules/react-native-gesture-handler/src/index.ts, same to other export line (including from other files) where there is the word 'type'

before ===> 
```
`export type {
    |             ^
  6 |   // event types
  7 |   GestureEvent,
  8 |   HandlerStateChangeEvent,`
...
} from './handlers/gestureHandlerCommon';
```

after ===>  
```
export {
  6 |   // event types
  7 |   GestureEvent,
  8 |   HandlerStateChangeEvent
...
} from './handlers/gestureHandlerCommon';
```

**Comment by gonzalo-lorieto** [comment]
Having this same issue on Expo 41, after upgrading from working version in SDK 40.

**Comment by lisadreamer** [comment]
In my case was able to fix this error when: 
upgraded to 42 sdk. and did upgrades by using "expo install <package-name>" command. (In my case i used Expo install expo-updates and expo-device.) after which that error was resolved.
