### ISSUE TITLE
Invariant Violation: requireNativeComponent: "GestureHandlerRootView" was not found in the UIManager.

### ISSUE THREAD

**Issue by Humad** [software-mansion/react-native-gesture-handler#1692]
## Description
When starting the Android app, I get `Invariant Violation: requireNativeComponent: "GestureHandlerRootView" was not found in the UIManager.`

This ONLY happens when I'm building the app form Android studio, or if I'm trying to run the app through the APK. This never happens when I'm testing the app locally with expo.

This issue does not happen on iOS

## Steps To Reproduce

1. Follow instructions here https://docs.swmansion.com/react-native-gesture-handler/docs/
2. Wrap App with GestureHandlerRootView
3. Run app on Android

### Expected behavior
GestureHandlerRootView is found

### Actual behavior
GestureHandlerRootView is not found

## Snack or minimal code example
```
import React from 'react';
import { GestureHandlerRootView } from 'react-native-gesture-handler';
import NavigationContainer from './NavigationContainer';

export const App = () => (
    <GestureHandlerRootView>
        <NavigationContainer />
    </GestureHandlerRootView>
);

export default App;
```

## Package versions

- React: 16.13.1
- React Native: 0.63.4
- React Native Gesture Handler: 1.10.2

This issue has been bothering me for a week now. I have tried lots of different things, including wrapping the App with the gesture handler higher order component. I've gone through the instructions for Android multiple times. I have installed and reinstalled the packages and cleared the cache. I don't understand what is going on and its driving me insane.

**Comment by TuNguyenThanh** [comment]
+

**Comment by Titozzz** [comment]
This docs is for >2.0.0 which hasn't been released ... yet ? so follow the part where you edit the mainactivity.java in the meantime

**Comment by Titozzz** [comment]
see https://github.com/software-mansion/react-native-gesture-handler/issues/1634

**Comment by j-piasecki** [comment]
Hi! This looks like a config issue. If it's still affecting you, could you prepare a repository with a reproduction?

**Comment by Alexkozlovec** [comment]
If someone else is stuck on this problem, like me who spent more quite a few hours trying to find the cause, here's a solution that worked for me:

Try updating gradle version in android/build.gradle to 7.2.1. I had 7.4.2 previously and the release app was crashing with it, don't know why but happy that the issue is gone now.

`
dependencies {
     classpath("com.android.tools.build:gradle:7.2.1")
     ...
}`
