### ISSUE TITLE
@types/react-native should be a dependency

### ISSUE THREAD

**Issue by alamothe** [software-mansion/react-native-gesture-handler#1720]
Since this package's types depend on `@types/react-native`, it should be a dependency of this package. Please check: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

Currently, the problem will be observed with Yarn PNP (which is strict about this) where your typings are unusable.

**Comment by j-piasecki** [comment]
Since 0.71 types are bundled with React Native, so it shouldn't be necessary anymore.
