### ISSUE TITLE
PanGestureHandle doesn't work on android 10, 11, 12

### ISSUE THREAD

**Issue by hweihoh8899** [software-mansion/react-native-gesture-handler#1723]
I am currently using reanimated version 2.3.0-beta.3 and react native version 0.66.3 and following tutorials from William Candillon, here is the source code.
![1](https://user-images.githubusercontent.com/56664693/141979545-e790e1d5-3e6a-4cba-9f58-7a4d5132a0d1.png)
![2](https://user-images.githubusercontent.com/56664693/141979573-9b3e043e-2a03-47ad-8244-ae4c7488b5a8.png)
On all recent versions of android (10, 11, 12) i can't drag the item in the PanGestureHandler but everything seems ok on IOS. The clamp and withBouncing are from react-native-redash
![3](https://user-images.githubusercontent.com/56664693/141981142-b04a3654-1298-4294-b24d-a6a89f8263af.png)

**Comment by MonsterAnan** [comment]
you can see this https://github.com/software-mansion/react-native-gesture-handler/issues/1478#issuecomment-1000062141

**Comment by jakub-gonet** [comment]
This is likely caused by the missing RNGH root view. Try wrapping your app's code in `<GestureHandlerRootView style={{flex: 1}}>` component.

Also, please attach the source code in plaintext, not photos next time.
