### ISSUE TITLE
Issue when using react-native-gesture-handler with react-navigation 6

### ISSUE THREAD

**Issue by 82359hwoh** [software-mansion/react-native-gesture-handler#1734]
I am currently having this issue when using react-native-gesture-handler with react-navigation 6:
First of all, i have a menu like this:
![image](https://user-images.githubusercontent.com/94808579/143166886-401b2c9b-b8eb-4f73-b3bc-62c3a4ea46dd.png)
And when i click on the PanGesture, it will navigate to a screen which contain the PanGestureHandler:
![image](https://user-images.githubusercontent.com/94808579/143167097-81f106ca-2437-4b94-b37b-46ec510432ff.png)
And when i go back, the view inside of the PanGesture get looped instead of going back to the home screen
![image](https://user-images.githubusercontent.com/94808579/143167212-b73e0b8b-8b08-4917-883d-9bae34b3d510.png)
Here is my code:
App.tsx
![image](https://user-images.githubusercontent.com/94808579/143168848-78a08e28-aefd-4bce-99f2-6569815ae2e4.png)
PanGesture.tsx
![image](https://user-images.githubusercontent.com/94808579/143168915-dd15b435-2f5b-4f90-a8d5-bf04979f2db4.png)
![image](https://user-images.githubusercontent.com/94808579/143168933-4f46f617-b409-4a18-a0ff-4a0d63945f79.png)
I have tried placing GestureHandlerRootView inside of PanGesture.tsx to replace the <View style={styles.container}> but it won't work either
Can someone help me out with this, much appreciate

**Comment by MonsterAnan** [comment]
@82359hwoh 
Hi, I'm solved. 
You can see this https://github.com/software-mansion/react-native-gesture-handler/issues/1478#issuecomment-1000062141.
