### ISSUE TITLE
[v2.0.0][Android] Type com.swmansion.common.GestureHandlerStateManager is defined multiple times

### ISSUE THREAD

**Issue by hatem-72** [software-mansion/react-native-gesture-handler#1748]
## Description

As I saw you released a tag for long awaited `v2.0.0` yesterday I wanted to test it out in a RN application using react-native-gesture-handler and react-native-reanimated already.
Build in Android failed on `Task :app:mergeLibDexDevDebug` for reason --> `Type com.swmansion.common.GestureHandlerStateManager is defined multiple times`.

### Screenshots
![android-build-error-screenshot](https://user-images.githubusercontent.com/86654761/144573133-854ca1a1-453f-49bb-b5cd-92a466436a04.jpg)

## Steps To Reproduce

1. Init RN project
2. Install `react-native-reanimated@next`
3. Install `react-native-gesture-handler`
4. `npx react-native run-android`

### Expected behavior
Successful build

### Actual behavior
Build failure

## Package versions

- React: `17.0.2`
- React Native: `0.66.3`
- React Native Gesture Handler: `^2.0.0`
- React Native Reanimated: `^2.3.0-beta.4`

**Comment by aprilmintacpineda** [comment]
Happening to me as well.

**Comment by hukpavlo** [comment]
with react-native-reanimated 2.2.4 it works fine

**Comment by aprilmintacpineda** [comment]
But it [docs](https://docs.swmansion.com/react-native-gesture-handler/docs/#installation) says we should be using `2.3.0-beta.4` or newer.

**Comment by hatem-72** [comment]
Not tested yet but I guess https://github.com/software-mansion/react-native-gesture-handler/pull/1747 should fix the issue.

**Comment by tomekzaw** [comment]
If you get this error in 2024, please bump react-native-gesture-handler to 2.21.2 or apply this change: https://github.com/software-mansion/react-native-gesture-handler/pull/3225
