### ISSUE TITLE
gestureStateManager on react-native-web __reanimatedWorkletInit is not a function

### ISSUE THREAD

**Issue by dannyhw** [software-mansion/react-native-gesture-handler#1754]
## Description

When I import gesture handler on the web in an app with reanimated I get this error `Uncaught TypeError: __webpack_require__.g.__reanimatedWorkletInit is not a function at Object../node_modules/react-native-gesture-handler/lib/module/handlers/gestures/gestureStateManager.js `

I could be doing something wrong however I didn't have issues using gesture handler in the same way on previous versions so I'm not sure.

### Screenshots

![image](https://user-images.githubusercontent.com/3481514/145229340-49d8e71a-f324-48c5-bc9d-4166a56ecbe3.png)

<details>
<summary>
Click to here to see the error output
</summary>

```js
rnw.bundle.js:5716 Uncaught TypeError: __webpack_require__.g.__reanimatedWorkletInit is not a function
    at eval (gestureStateManager.js?:formatted:111)
    at eval (gestureStateManager.js?:formatted:113)
    at Object../node_modules/react-native-gesture-handler/lib/module/handlers/gestures/gestureStateManager.js (rnw.bundle.js:720)
    at __webpack_require__ (rnw.bundle.js:5713)
    at fn (rnw.bundle.js:5924)
    at eval (GestureDetector.js:1)
    at Object../node_modules/react-native-gesture-handler/lib/module/handlers/gestures/GestureDetector.js (rnw.bundle.js:650)
    at __webpack_require__ (rnw.bundle.js:5713)
    at fn (rnw.bundle.js:5924)
    at eval (index.js:1)
```

</details>

## Steps To Reproduce

1. create new react native app
2. setup webpack config for react native web
3. import gesture handler in code
4. run on web

I've done this for you in a reproduction here https://github.com/dannyhw/react-native-reproduction/pull/3

To clone and run the code you can run the following:

```sh
git clone --single-branch -b gesture-reanimated git@github.com:dannyhw/react-native-reproduction.git && \
  cd react-native-reproduction && \
  yarn && \
  yarn web
```

then open the dev console in the browser to see the error.

### Expected behavior

gesture handler import doesn't break on web

### Actual behavior

app breaks on web when importing gesture handler

## Snack or minimal code example

I made a reproduction here https://github.com/dannyhw/react-native-reproduction/pull/3

## Package versions

```json
    "react": "17.0.2",
    "react-native": "0.66.3",
    "react-native-gesture-handler": "^2.1.0",
    "react-native-reanimated": "^2.3.0",
    "react-native-web": "^0.17.5"
```

**Comment by j-piasecki** [comment]
Hi, I looked at your reproduction and I think it's a problem with the configuration of Reanimated. Check out [the documentation for web support](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/web-support), as it nicely highlights what you are missing right now. I'll close the issue for now, but if it doesn't fix your problem, feel free to reopen it 😄 .

**Comment by dannyhw** [comment]
@j-piasecki you were right about there being something missing, I never needed the process.env plugin before but now I needed it for some reason. Now I'm getting errors with performance.now not existing for reanimated but its unrelated to gesture handler.

Thanks for taking the time to point me in the right direction I really appreciate it 🙇
