### ISSUE TITLE
Support monorepo

### ISSUE THREAD

**Issue by HeroBanana** [software-mansion/react-native-gesture-handler#1755]
## Description

While building Android the package assume normal structure but should also support monorepo structure.

## Steps To Reproduce

1. Create a monorepo structure
2. use react native reanimated 2
3. use react native gesture handler

### Expected behavior

Allow fetching react-native-reanimated from monorepo structure

### Actual behavior

Should just compile in monorepo

## Snack or minimal code example

Cant provide but know where it goes wrong. When changing the path with extra "../../" it works.

```
// Check whether Reanimated 2.3 or higher is installed alongside Gesture Handler
def shouldUseCommonInterfaceFromReanimated() {
    if (rootProject.subprojects.find { it.name == 'react-native-reanimated' } != null) {
        def inputFile = new File(rootProject.projectDir, '../node_modules/react-native-reanimated/package.json')
        def json = new JsonSlurper().parseText(inputFile.text)
        def reanimatedVersion = json.version as String
        def (major, minor, patch) = reanimatedVersion.tokenize('.')
        return Integer.parseInt(minor) >= 3
    } else {
        return false
    }
}
```

## Package versions

- React: 17.02
- React Native: 66.3
- React Native Gesture Handler: 2.1.0

**Comment by j-piasecki** [comment]
Hi, thanks for the report. Could you please check if [this](https://github.com/software-mansion/react-native-gesture-handler/pull/1757) change fixes the problem for you?

**Comment by HeroBanana** [comment]
> Hi, thanks for the report. Could you please check if [this](https://github.com/software-mansion/react-native-gesture-handler/pull/1757) change fixes the problem for you?

will do
