### ISSUE TITLE
IOS Wrong coordinates using GestureDetector

### ISSUE THREAD

**Issue by elencho** [software-mansion/react-native-gesture-handler#1759]
## Description

So I use gesture handler usually on android and wanted to get same results on ios but it is not working as expected.I don't get correct coordinates. 

## Steps To Reproduce

1. I already tried nesting different directions as mentioned in previous issues but does't work on ios, android works fine.

### Expected behavior & Actual behavior
I wanted to get right directions but on ios device it sometimes goes right when i swipe for left and same for left.
## Snack or minimal code example

gist code 
https://gist.github.com/elencho/d2ced9f70ae819f02b2c9a10d20f7d07?fbclid=IwAR0_yWf0Yi6JkzIwTEY5MO7WfJo57XNDDtXx64g0N48lGM3z8XB-UjCF3Qs

## Package versions

    "react": "17.0.1",
    "react-native": "0.64.2",
    "react-native-gesture-handler": "~2.0.0",

**Comment by WoLewicki** [comment]
Can you provide the full reproduction code so everyone can work on it? Otherwise it worsens the debugging process and is not easy to get to the exact buggy behavior.
