### ISSUE TITLE
[v2.1.0][Android] RNGestureHandlerModule.kt: (11, 22): Unresolved reference: common

### ISSUE THREAD

**Issue by bardliu** [software-mansion/react-native-gesture-handler#1760]
New release [2.1.0](https://github.com/software-mansion/react-native-gesture-handler/releases/tag/2.1.0) (thanks to https://github.com/software-mansion/react-native-gesture-handler/pull/1747) is fixing the issue.

So I am closing this 👍

_Originally posted by @hatem-72 in https://github.com/software-mansion/react-native-gesture-handler/issues/1748#issuecomment-988172683_

#Package versions

- React: 17.0.2
- React Native: 0.66.3
- React Native Gesture Handler: ^2.1.0

Hi I got a new error like this:

react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerModule.kt: (11, 22): Unresolved reference: common

![image](https://user-images.githubusercontent.com/20809872/145971712-74f85167-6c2b-4bb7-b8ca-09a017a0d40f.png)

**Comment by samleurs247** [comment]
I have ^2.1.0 and I still have this issue. Same errors.

**Comment by zjiaxin2021** [comment]
add this
<img width="1032" alt="9d7e7115-8c02-4108-a40d-c807b14ac8b8" src="https://user-images.githubusercontent.com/87636394/146107567-1d87f336-79f9-45bb-8036-582bddbe17c2.png">
[https://docs.swmansion.com/react-native-gesture-handler/docs/#installation](react-native-gesture-handler)

**Comment by j-piasecki** [comment]
Hi, are you using `react-native-reanimated`? If so, which version?

**Comment by sebwongatnorthone** [comment]
Bumping the `react-native-reanimated` version to the latest (2.3.1) fixed it for me! Nice catch, @j-piasecki !

**Comment by TheWirv** [comment]
This issue mainly arises because the function to check whether to use Reanimated's common interface [only checks for the minor](https://github.com/software-mansion/react-native-gesture-handler/blob/057d3ae4327abc3634f562f536f924423be754da/android/build.gradle#L30), but not for the major version (thereby expecting Reanimated v2 to be installed).

that line should be something like `return Integer.parseInt(major) >= 2 && Integer.parseInt(minor) >= 3`

**Comment by cristianoccazinsp** [comment]
How do we solve this if we are using reanimated v1.x ?

**Comment by bardliu** [comment]
> Hi, are you using `react-native-reanimated`? If so, which version?

Hi @j-piasecki , Yes, I am using v1.13.3!

**Comment by bardliu** [comment]
> This issue mainly arises because the function to check whether to use Reanimated's common interface [only checks for the minor](https://github.com/software-mansion/react-native-gesture-handler/blob/057d3ae4327abc3634f562f536f924423be754da/android/build.gradle#L30), but not for the major version (thereby expecting Reanimated v2 to be installed).
> 
> that line should be something like `return Integer.parseInt(major) >= 2 && Integer.parseInt(minor) >= 3`
> 
> I am still on Reanimated v1.13.3 and was faced with the same problem. But checking for the major version too fixed it.

Thanks! It works!
However, this line needs to be modified every time `npm install` is executed 😂.

**Comment by AmauryLiet** [comment]
@bardliu you should have a look at [patch-package](https://github.com/ds300/patch-package) to update your dependencies in a safer + more permanent way :)

**Comment by bardliu** [comment]
> @bardliu you should have a look at [patch-package](https://github.com/ds300/patch-package) to update your dependencies in a safer + more permanent way :)

Thanks!

**Comment by bardliu** [comment]
some solutions:
1. upgrade `react-native-reanimated` to 2.x
2. use `patch-package` create a patch like https://github.com/software-mansion/react-native-gesture-handler/issues/1760#issuecomment-996059140.

**Comment by AmauryLiet** [comment]
recommended alternative:

upgrade to v2.2.0 that has just been released, and which include [the fix](https://github.com/software-mansion/react-native-gesture-handler/commit/f3ea85f23e60df96451ea7e92a2d85ac41b7a7ab)
