### ISSUE TITLE
iOS 2.1.0 - RCTBridge required dispatch_sync to load RNGestureHandlerModule. This may lead to deadlocks

### ISSUE THREAD

**Issue by cristianoccazinsp** [software-mansion/react-native-gesture-handler#1770]
## Description
After upgrading from 1.x to 2.1.0, the following warning shows every time the iOS app is opened:
`RCTBridge required dispatch_sync to load RNGestureHandlerModule. This may lead to deadlocks`

Note, this only seem to happen when reanimated 2 is used, no warnings with reanimated 1.

## Steps To Reproduce

1. Install "react-native-gesture-handler": "2.1.0",
2. `import 'react-native-gesture-handler';` on index.js
3. Wrap the main component in `GestureHandlerRootView`
4. Start the app on iOS and observe the warning.

### Expected behavior
No warnings.

### Actual behavior
Warnings.

## Package versions

- React: 17.0.2
- React Native: 0.66.3
- React Native Gesture Handler: 2.1.0
- React native reanimated: 2.3.1

**Comment by cristianoccazinsp** [comment]
The issue probably comes from reanimated trying to create a gesture handler instance.

<img width="1133" alt="Screen Shot 2021-12-17 at 13 10 22" src="https://user-images.githubusercontent.com/48869228/146574263-47d92055-791a-4db8-b1f5-8b7107d0adc1.png">

<img width="730" alt="Screen Shot 2021-12-17 at 13 11 45" src="https://user-images.githubusercontent.com/48869228/146574437-a31daace-df2d-475b-8a9c-bd40f5efd17e.png">

<img width="789" alt="Screen Shot 2021-12-17 at 13 12 04" src="https://user-images.githubusercontent.com/48869228/146574460-c13c9970-1bc0-45dc-a6b8-3a40e0258e13.png">

**Comment by Hirbod** [comment]
Duplicate of https://github.com/software-mansion/react-native-gesture-handler/issues/722
I also posted a solution (at least for me)

**Comment by nicode-io** [comment]
@Hirbod the author mentioned that he already wrap his app with GestureHandlerRootView, so your "solution" (just a step in docs we all follow, just don't work.

**Comment by Hirbod** [comment]
@nicode-io I also edited my answer, that the solution did not work for me either at some later point.

**Comment by 3runoDesign** [comment]
same here!

**Comment by dthomason** [comment]
yup, having the same issue here as well.

**Comment by billnbell** [comment]
This is new for me in the current version. It is not a duplicate.

**Comment by Dramex** [comment]
same

**Comment by mattahorton** [comment]
Also happening for me. I am currently ignoring this but would love to know if it's a bug.

**Comment by Saad-Bashar** [comment]
+1

**Comment by shoaib2527** [comment]
+1

**Comment by AhmadHoranieh** [comment]
+1

**Comment by hf-yevhen** [comment]
+1

How to reproduce:
1. npx react-native init MyApp
2. cd MyApp && yarn add react-native-reanimated react-native-gesture-handler
3. cd ios && pod install && cd ..
4. npx react-native run-ios

**Comment by zoobibackups** [comment]
> +1
> 
> How to reproduce:
> 
> 1. npx react-native init MyApp
> 2. cd MyApp && yarn add react-native-reanimated react-native-gesture-handler
> 3. cd ios && pod install && cd ..
> 4. npx react-native run-ios

any solution yet?

**Comment by zhenkaGo** [comment]
I changed GestureHandlerRootView to gestureHandlerRootHOC and this error is gone.

**Comment by nazrdogan** [comment]
+1
