### ISSUE TITLE
[Bug]: RNGestureHandlerModule.attachGestureHandler got 2 arguments, expected 3

### ISSUE THREAD

**Issue by myckhel** [software-mansion/react-native-gesture-handler#1771]
## Description
After upgrading to v^2 from v1, release apk crashes with error
```
com.facebook.react.bridge.NativeArgumentsParseException: RNGestureHandlerModule.attachGestureHandler got 2 arguments, expected 3
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:30)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:13)
    at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1)
    at android.os.Looper.loop(Looper.java:214)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:8)
    at java.lang.Thread.run(Thread.java:919)
```

## Steps To Reproduce

1. Upgrade rngh from v^1 to v2.1.0

## Package versions

- React: 17.0.2
- React Native: 66.4
- React Native Gesture Handler: 2.1.0

**Comment by ramiel1999** [comment]
same error

**Comment by mrdezzods** [comment]
I have the same issue

**Comment by Douglas-Hsieh** [comment]
Same issue here when upgrading react-native-gesture-handler and expo with `$ expo upgrade`

react-native-gesture-handler 2.1.0
expo 44.0.0
react native 0.64.3
react 17.0.1

Also wrapped my app in a <GestureHandlerRootView> component per gesture-handler installation instructions

**Comment by waheedakhtar694** [comment]
Same here

**Comment by bozkayaSalihX** [comment]
I have same issue please fix this issue

**Comment by alexprey** [comment]
Have the same, subscribe to wait a fix. That commes only when I try to upgrage on 2.x

**Comment by bozkayaSalihX** [comment]
okay, how can I subscribe waitlist?

**Comment by felipegmg** [comment]
+1 with this issue

**Comment by LotfiOR** [comment]
Same issue here :/ please help

**Comment by ewlkkf** [comment]
+1 issue happens to me. 
but when I rollback android build tools and gradle version, It's working right now.

> 'com.android.tools.build:gradle:**7.0.4**'
> gradle-**7.0.2**-all.zip

**Comment by mhuretski** [comment]
Same issue for me 
react-native: 0.67.2
react-native-gesture-handler: 2.2.0
react-native-reanimated: 2.4.1

It doesn't reproduce on Android emulator but reproduces on real device.

**Comment by fangwohung** [comment]
Same issue for me, pls fix this

**Comment by waheed25** [comment]
@jakub-gonet restarting the metro didn't works for me.

**Comment by nmante** [comment]
This is still an issue unfortunately. When using version 2.1.1, I get this error. Rolling back to version `1.10.3` fixes the issue for me.

**Comment by cgarcial-mx** [comment]
I tried everything on this thread and the issue is still there.

I'm working with Expo SDK 44 , react 17.0.1 and Expo CLI 5.3.0

**Comment by j-piasecki** [comment]
Hi! You can try the following steps:
- Expo:
```
rm -rf node_modules
yarn cache clean / npm cache clean -force 
yarn / npm install
expo r -c
```

- Otherwise:
```
rm -rf node_modules
yarn cache clean / npm cache clean -force 
yarn / npm install
npm start -- --reset-cache
```

**Comment by Sk47R** [comment]
```
rm -rf node_modules
yarn cache clean / npm cache clean -force 
yarn / npm install
expo r -c
```

I did the steps above. But by app crashes. If however i comment the chart component it works. im still finding for a fix.

**Comment by j-piasecki** [comment]
What do you mean by
> If i comment the chart component, it works

@Sk47R ?

**Comment by Sk47R** [comment]
I mean I have issue with the chart. Same as others. And none of the solutions worked

**Comment by Sk47R** [comment]
I found somewhere that this problem is only in android and in ios it works. For now ive used another library. But i would like to know the reason and solution

**Comment by j-piasecki** [comment]
Is this your own component or is it from some library? I asked because no one else mentioned it and it could be a lead.

**Comment by Sk47R** [comment]
Its my custom component.

**Comment by bryce0516** [comment]
in expo same issue my package.json
    "expo": "~44.0.0",
    "react-native-gesture-handler": "~1.10.2",
    "react-native-reanimated": "~2.2.0",

**Comment by bryce0516** [comment]
> 

I solved this problem. I try 'expo install react-native-gesture-handler react-native-reanimated'
, and wrapped root view with GestureHandlerRootView

**Comment by ahe99** [comment]
same here platform ios
- expo start (ok) 
- expo run:ios (err)
still finding :'(

**Comment by j-piasecki** [comment]
If you are using managed workflow, make sure you are using the correct version of Gesture Handler - 1.10 for SDK 43, 2.1 for SDK 44 and 2.2 for SDK 45.

**Comment by amitvish09** [comment]
is this fixed? or Not?

**Comment by j-piasecki** [comment]
@amitvish09 This is most likely caused by mismatched versions of Expo and Gesture Handler, please use `expo install react-native-gesture-handler` to install the correct version of GH.

**Comment by Vednus** [comment]
Weirdly, this is happening to me only on release builds on android with expo 45 and rn 68.2. I've reset the cache, deleted node_modules, reinstalled using `expo install react-native-gesture-handler`, and looked through my yarn.lock for old version dependencies to no avail.

**Comment by Vednus** [comment]
Finally got it fixed. The last thing I did was downgrade gradle following this [comment](https://github.com/facebook/react-native/issues/33716#issuecomment-1153828126) and also using [this](https://stackoverflow.com/a/71016928/7753829) gradle script to even out the kotlin versions. Not sure which one it was that did the trick.

**Comment by mickykro** [comment]
> Hi! You can try the following steps:
> 
> * Expo:
> 
> ```
> rm -rf node_modules
> yarn cache clean / npm cache clean -force 
> yarn / npm install
> expo r -c
> ```
> 
> * Otherwise:
> 
> ```
> rm -rf node_modules
> yarn cache clean / npm cache clean -force 
> yarn / npm install
> npm start -- --reset-cache
> ```

this didnt help me, I have the same issue on IOS and it shows the error only on a device and on emulator it works perfectly. 
please do anyone have a different answer ?
