### ISSUE TITLE
Horizontal gesture handler in a screen will not let you scroll vertically in a ScrollView

### ISSUE THREAD

**Issue by FaisalBinAhmed** [software-mansion/react-native-gesture-handler#1775]
## Description
After upgrading to the latest version from v1.10.2, I can't scroll vertically on a flatlist in a screen where horizontal gesture handler is also enabled. This used to work fine in v1.10.2. Basically, if you use React Navigation's Stack Screen with a horizontal iOS style gesture transition to go back, it now blocks any other scrolling event in the entire area where the gesture handler is active.

## Steps To Reproduce

1. Add a React Navigation stack screen with horizontal gesture handler. ie: CardStyleInterpolators.forHorizontalIOS,
2. Put a vertical scroll view in that screen,
3. try to scroll vertically where horizontal gesture handler is active.

### Expected behavior
The scroll view should scroll normally.

### Actual behavior
Gesture handler won't let you scroll where it is active.
## Snack or minimal code example

My Stack screen looks like this:

<Stack.Screen
				name="postview-main"
				component={PostView}
				options={{
					cardStyleInterpolator: CardStyleInterpolators.forHorizontalIOS,
					gestureEnabled: true,
					headerShown: false,
					gestureResponseDistance: 300,
					gestureDirection: "horizontal",
					detachPreviousScreen: false,
				}}
			/>

In the above '300' area, I can't scroll vertically on a ScrollView/Flatlist inside my PostView. Scrolling only works outside of this area.

## Package versions

- React: 17.0.1
- React Native: 0.64.3
- React Native Gesture Handler: 2.1.0
- Expo: 44
- React Navigation/native: 6.0.6
- React Navigation/stack: 6.0.11

**Comment by idrissakhi** [comment]
Hey 👋 ,

I have the same issue here. I resolved this by using ScrollView from RNGH and not the one from RN.

I also noticed that the issue is only present on Android devices. 

Last but not least if you are using FlatList or VirtualizedList then you can use  renderScrollComponent to render the ScrollView of RNGH

`renderScrollComponent={(props) => <ScrollView {...scrollViewProps}/>}`

**Comment by Hirbod** [comment]
Did you guys also wrapped your app with `< GestureHandlerRootView>`?

**Comment by FaisalBinAhmed** [comment]
> Did you guys also wrapped your app with `<GestureHandlerRootView>...<App /></GestureHandlerRootView>`?

yep, tried it. No improvements. AFAIK it's not required since I'm only using React Navigation built in gestures. According to their installation guide, I already included the import on the top of my entry file.

**Comment by FaisalBinAhmed** [comment]
> Hey wave ,
> 
> I have the same issue here. I resolved this by using ScrollView from RNGH and not the one from RN.
> 
> I also noticed that the issue is only present on Android devices.
> 
> Last but not least if you are using FlatList or VirtualizedList then you can use renderScrollComponent to render the ScrollView of RNGH
> 
> `renderScrollComponent={(props) => <ScrollView {...scrollViewProps}/>}`
Thanks for your suggestions.
I haven't tried it yet, but I will try it and let you know. This should be fixed by Software Mansion or React Navigation tho.

**Comment by FaisalBinAhmed** [comment]
@idrissakhi just tried your solution and it works! Fortunately I needed it on the Flatlist where I don't use any animated scroll event. If it was my other flatlist, I would be very unlucky.

I wonder why it worked perfectly on v1.10.2, I went through the changelogs since, I noticed nothing that would indicate this behavior.

**Comment by Hirbod** [comment]
You can also import FlatList from RNGH and use the renderScrollComponent there. I think you could've applied the same workaround there.

**Comment by FaisalBinAhmed** [comment]
@Hirbod are there any benefits of using the Flatlist from RNGH over RN? A few weeks ago, vscode accidentally imported it from RNGH and I remember there were some unexpected behaviors. To be fair, it was a pretty complicated, animated flatlist and I was handling scroll events.

**Comment by Hirbod** [comment]
There are only benefits when you have touch related issues. I only used them when I have issues with portals, absolute positioned or nested views. It's pretty random.

**Comment by FaisalBinAhmed** [comment]
@Hirbod @idrissakhi Update: mixing _RNGH_ `<ScrollVIew />` with _RN_ `<FlatList />` causes an issue where the scrollview will get a larger scrollheight if ithe data is updated dynamically - resulting in a lot of blank spaces at the bottom of the list. Using the `<FlatList />` from _RNGH_ directly solves this issue. No need to add a `renderScrollComponent`.

**Comment by idrissakhi** [comment]
@FaisalBinAhmed yes of course, I gave the example of renderScrollComponent when we use VirtualizedList which is not provided by RNGH

**Comment by paul-mcn** [comment]
For future viewers try adding the prop `touchAction="pan-y"`:
```
<GestureDetector gesture={...} ... touchAction="pan-y">
  ...
</GestureDetector>
```
