### ISSUE TITLE
GestureStateManager undefined

### ISSUE THREAD

**Issue by dpyeates** [software-mansion/react-native-gesture-handler#1776]
I would like to use GestureStateManager to cancel a touch event if my touch criteria are not met.
Currently I am getting GestureStateManager as undefined.

### Expected behavior
When touch event received that does not fulfil the touch location requirements, the touch event is cancelled and does nothing.

### Actual behavior
App doesn't run and red screens immediately with "TypeError: Cannot read property 'fail' of undefined"

```
import {Gesture, GestureDetector, GestureStateManager} from 'react-native-gesture-handler';

const panGesture = Gesture.Pan()
  .onStart((event) => {
    'worklet';
    if (/* touch event is not in doughnut area */) {
      GestureStateManager.fail();
    }
  })
  .onUpdate((event) => {
    'worklet';
    /* do something with the new touch event */
  });
```

- React: 17.0.2
- React Native: 0.66.4 using Hermes
- React Native Gesture Handler: 2.1.0
- React Native Reanimated: 2.3.1
- Environment: iOS

**Comment by j-piasecki** [comment]
Hi, unfortunately `GestureStateManager` is available only in the newly introduced touch events. You will receive it as an argument for the callback in `onTouchesDown`, `onTouchesMove`, `onTouchesUp`, and `onTouchesCancelled`. For example:
```js
const panGesture = Gesture.Pan()
  .onTouchesDown((event, stateManager) => {
    if (/* touch event is not in doughnut area */) {
      stateManager.fail();
    }
  });
```

**Comment by dpyeates** [comment]
Ah! That makes sense now. Thank you. I've implemented a solution using your advice and I have it working well - thank you!
