### ISSUE TITLE
Error during compilation - RNGestureHandlerModule.kt: Type mismatch: inferred type is ReactApplicationContext? but ReactApplicationContext was expected

### ISSUE THREAD

**Issue by annucy** [software-mansion/react-native-gesture-handler#1805]
## Description

I am using latest version of 2.1.0.
It throws the following error while compiling
node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerModule.kt: (17, 32): Type mismatch: inferred type is ReactApplicationContext? but ReactApplicationContext was expected

## Package versions

- React: "16.11.0",
- React Native:"0.62.0",
- React Native Gesture Handler: 2.1.0
- compileSdkVersion 31
- buildToolsVersion "30.0.3"
- targetSdkVersion 30

**Comment by Jitendra-atharva** [comment]
ReactContextBaseJavaModule(reactContext) instead of ReactContextBaseJavaModule(reactContext!!)

**Comment by annucy** [comment]
> node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerModule.kt: (17, 32):
> 
> Use ReactContextBaseJavaModule(reactContext!!) instead of ReactContextBaseJavaModule(reactContext) and try. It's working for me

True, it worked for me as well. But changing node modules shouldn't be the correct solution.

**Comment by annucy** [comment]
Any updates on this?

**Comment by devagero** [comment]
I have the same issue.

react: 17.0.2
react-native: 0.67.0
react-native-gesture-handler: 2.2.0
buildToolsVersion: 30.0.2
compileSdkVersion: 31
targetSdkVersion: 31

**Comment by OsaedYahya** [comment]
Same issue

**Comment by Jitendra-atharva** [comment]
once I upgrade react-native-gesture-handler issue resolve

**Comment by azyd3** [comment]
> once I upgrade react-native-gesture-handler issue resolve

Which version? I am at 2.2.1. still it does not work.

**Comment by laemm-line** [comment]
We ran into this error with version 2.7.0.

**Comment by gguidotti** [comment]
Just got the same issue after updating compileSdkVersion from 31 to 33. I'm running react-native-gesture-handler 2.4.2 and was able to fix this by upgrading to 2.5.0 (fix included in release notes: https://github.com/software-mansion/react-native-gesture-handler/releases/tag/2.5.0)

**Comment by jonasalexanderd** [comment]
@gguidotti this works for me, thx

**Comment by shaikhJavid786** [comment]
> For what it's worth, after experiencing this issue, we upgraded from 2.2.0 to 2.9.0 (latest at the time) and it seemed to have fixed it. Not sure which version fixed it but seems to be resolved in the latest.

Thnaks Buddy , its working.
