### ISSUE TITLE
Cannot find module '@babel/preset-typescript'

### ISSUE THREAD

**Issue by tiavina-mika** [software-mansion/react-native-gesture-handler#1806]
## Description

I've got this error:
`node_modules/react-native-gesture-handler/src/handlers/gestures/gestureStateManager.ts: /Users/mini12/Documents/Projects/yourz-mobile/node_modules/react-native-gesture-handler/src/handlers/gestures/gestureStateManager.ts: Cannot find module '@babel/preset-typescript'`

### Screenshots
![image](https://user-images.githubusercontent.com/42656064/148193024-941448f6-3dc0-4b18-b424-e3fe3fa1f32b.png)

## Steps To Reproduce

1. run `yarn ios`

### Expected behavior
the app should be launched in a simulator

### Actual behavior
get that error
## Snack or minimal code example

https://snack.expo.dev/@tiavina-mika/1da2fd

## Package versions

- React:16.13.1
- React Native:~0.63.4
- React Native Gesture Handler:^2.1.0

**Comment by tiavina-mika** [comment]
Fixed.
`yarn add @babel/preset-typescript` fixed it

**Comment by j-piasecki** [comment]
Hi! Since you have solved this problem, I'll close this issue.
