### ISSUE TITLE
Upgrade from 1.10.3 to 2.1.0

### ISSUE THREAD

**Issue by Tobinho07** [software-mansion/react-native-gesture-handler#1808]
## Description
Im trying to upgrade to newest version but after building, im getting an error:
```
error: Error: Unable to resolve module ./handlers/gestureHandlers from ******\node_modules\react-native-gesture-handler\src\index.ts:

None of these files exist:
  * node_modules\react-native-gesture-handler\src\handlers\gestureHandlers(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * node_modules\react-native-gesture-handler\src\handlers\gestureHandlers\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
> 1 | import { initialize } from './init';
  2 |
  3 | export { Directions } from './Directions';
  4 | export { State } from './State';
```
Has anyone else this error?

## Steps To Reproduce

1.

## Package versions

- React:
- React Native:
- React Native Gesture Handler:

**Comment by j-piasecki** [comment]
Hi! It looks like a cache issue, could you try to reset it (`yarn start --reset-cache`)?

**Comment by realtril** [comment]
Same issue

**Comment by Tobinho07** [comment]
I have tried npm start --reset-cache, but bug still exists. 
Is it possible that the error occurs because another npm package has a reference on an older version of RNGH < V2 ?

**Comment by anastely** [comment]
> I have tried npm start --reset-cache, but bug still exists. Is it possible that the error occurs because another npm package has a reference on an older version of RNGH < V2 ?

Did you find a way to know that package?

**Comment by GeorgeRXia** [comment]
I am also having this issue @Tobinho07 did you find a way to bypass this?

**Comment by gustavleffler** [comment]
I had the same issue,  `npm start -- --reset-cache` solved it for me

**Comment by jakub-gonet** [comment]
I'm going to close this - it's not actionable to us in any way. If clearing caches doesn't help (watchman, Metro, node_modules) and you have some repro example (in form of repository that consistently fails running the app with this error), please create a new issue.

**Comment by Shehan-lakshitha** [comment]
I am too having the same issue but `npm start -- --reset-cache` did not solve me
