### ISSUE TITLE
Cannot convert undefined value to object. StackRouter

### ISSUE THREAD

**Issue by dguard** [software-mansion/react-native-gesture-handler#1809]
## Description

Clicking on any option in menu produces error below:
![Screenshot_20220107-132253_RNGH Example](https://user-images.githubusercontent.com/1911516/148514260-f3b233cf-468b-44b3-be18-0db5a65eb770.jpg)

### Screenshots
![Screenshot_20220107-131834_RNGH Example](https://user-images.githubusercontent.com/1911516/148514150-f9927d47-0476-4f88-b7d5-a1250dd3b146.jpg)

## Steps To Reproduce

0. Join example/ directory
1. `npx react-native start`
2. `npx react-native run-android`
3. wait while build will be completed for android
4. wait while bundle will be uploaded to android 

### Expected behavior
Show next option behavior

### Actual behavior
`
Callstack
router.getStateForAction
StackRouter.tsx:368:19
`

## Snack or minimal code example
![image](https://user-images.githubusercontent.com/1911516/148516239-4636ad17-4b1b-46d7-b5ba-f8b68f0a0ee2.png)

![image](https://user-images.githubusercontent.com/1911516/148516175-1585881f-ec45-4f7a-8395-63c641d5b50e.png)

## Package versions

- React:
"react": "17.0.2",
- React Native:
"react-native": "0.64.1",

- React Native Gesture Handler:
I am inside package
"name": "react-native-gesture-handler",  "version": "2.0.0",

**Comment by j-piasecki** [comment]
Hi! Unfortunately, I wasn't able to reproduce this issue. As it happens on the Example app, would you mind checking it again but with resetting npm cache first? I.e.:
1. Run `npm cache clean --force` or `yarn cache clean`
2. Delete `node_modules` from the `react-native-gesture-handler` and `example` directories
3. Run `npm install` or `yarn` in both `react-native-gesture-handler` and `example` directories
4. Try to run the app

**Comment by dguard** [comment]
@j-piasecki 
Thanks, this works ! :+1:
