### ISSUE TITLE
[2.1.0] Pinch Gesture Scale Doesn't Go Below Certain Value

### ISSUE THREAD

**Issue by Kesmek** [software-mansion/react-native-gesture-handler#1811]
## Description

Using the Pinch gesture on Android to scale an element, the scale value of the gesture event will not go below a certain value. The value appears to depend on the initial size of the element but is usually around a scale of 0.6 - 0.8.

### Screenshots

https://user-images.githubusercontent.com/38704268/148707301-1e602ad4-88e6-411b-81d0-3b5a50d74db7.mp4

## Steps To Reproduce

1. Add a box with a pinch gesture detector
2. Scale box with pinch gesture and reanimated (code below)

### Expected behavior

The element can be scaled to values below 0.5 of it's original scale

### Actual behavior

The element's scale is prevented from going below a certain value (around 0.7)

## Snack or minimal code example

Code almost exactly the same as the [example](https://docs.swmansion.com/react-native-gesture-handler/docs/api/gestures/pinch-gesture/#example) in the documentation.
```TSX
import React from 'react';
import { StyleSheet } from 'react-native';
import {
  Gesture,
  GestureDetector,
  GestureHandlerRootView,
} from 'react-native-gesture-handler';
import Animated, {
  useAnimatedStyle,
  useSharedValue,
} from 'react-native-reanimated';

const App = () => {
  const scale = useSharedValue(1);
  const savedScale = useSharedValue(1);

  const animatedStyle = useAnimatedStyle(() => ({
    transform: [{ scale: scale.value }],
  }));

  const gesture = Gesture.Pinch()
    .onUpdate((e) => {
      scale.value = savedScale.value * e.scale;
    })
    .onEnd(() => {
      savedScale.value = scale.value;
    });

  return (
    <GestureHandlerRootView style={styles.flex}>
      <GestureDetector gesture={gesture}>
        <Animated.View style={[styles.box, animatedStyle]} />
      </GestureDetector>
    </GestureHandlerRootView>
  );
};

const styles = StyleSheet.create({
  flex: { flex: 1, backgroundColor: 'salmon' },
  box: {
    width: 250,
    height: 250,
    marginTop: 300,
    alignSelf: 'center',
    backgroundColor: 'blue',
  },
});

export default App;


```

## Package versions

- React: 17.0.2
- React Native: 0.66.4
- React Native Gesture Handler: 2.1.0
- React Native Reanimated: 2.3.1

## Environment

This issue is present on both android emulator and a real android device on API 31 (Android 12). I'm only able to verify this issue on iOS using an emulator but it appears to function as expected on iOS.

**Comment by j-piasecki** [comment]
Hi! Gesture Handler uses [ScaleGestureDetector](https://developer.android.com/reference/android/view/ScaleGestureDetector) for Pinch gesture on Android. The ScaleGestureDetector uses [`ViewConfiguration.getScaledMinimumScalingSpan()`](https://developer.android.com/reference/android/view/ViewConfiguration#getScaledMinimumScalingSpan()) as the cut-off distance when it stops recognizing the gesture and his value is set to be 27mm. I'm not sure why such a large value was chosen but we are looking into possible solutions.
