### ISSUE TITLE
1.10.3 -> 2.1.1 TextInput   On iOS, the select/copy/paste menu does not pop up after long press on TextInput

### ISSUE THREAD

**Issue by gaodeng** [software-mansion/react-native-gesture-handler#1815]
- React: 17.0.2
- React Native: 0.66.4
- React Native Gesture Handler: 2.1.1

**Comment by j-piasecki** [comment]
Hi! Are you using `@react-navigation/stack`? If so, it may be the same problem as https://github.com/software-mansion/react-native-gesture-handler/issues/1801.

**Comment by j-piasecki** [comment]
Hi! I believe this issue was solved by https://github.com/react-navigation/react-navigation/pull/10270. Could you check if that's the case? If not please provide some kind of reproduction.

**Comment by gaodeng** [comment]
thanks
