### ISSUE TITLE
FlatList can't scroll

### ISSUE THREAD

**Issue by dodicandra** [software-mansion/react-native-gesture-handler#1819]
## Description
on android component FlatList can't be scrolled, and I got warning like this
```
Warning: Cannot record touch end without a touch start.
Touch End: {"identifier":0,"pageX":0,"pageY":0,"timestamp":1641956304238}
Touch Bank: [null,{"touchActive":true,"startPageX":278.0859375,"startPageY":212.92410278320312,"startTimeStamp":1641956304179,"currentPageX":267.91754150390625,"currentPageY":213.75302124023438,"currentTimeStamp":1641956304236,"previousPageX":276.943359375,"previousPageY":212.92410278320312,"previousTimeStamp":1641956304219}]
```

when using Flatlist directly from gestureHandler and adding props `shouldActivateOnStart` it just runs and it's not wrapped with `Animated.createAnimatedComponent(FlatList)`

## Steps To Reproduce

1. Basically I just put Flatlist inside ListHeaderComponents in Flatlist.
2. wrapping the Flatlist RN component with `Animated.createAnimatedComponent(FlatList)` from reanimated

### Expected behavior
it should work as expected
### Actual behavior
component can't be scrolled and get a warning like above
## Snack or minimal code example
```js
// HeaderList.tsx
import { FlatList, FlatListProps, StyleProp, ViewStyle } from 'react-native';

import Animated from 'react-native-reanimated';

const AFlatList = Animated.createAnimatedComponent(FlatList);

const { x, scrollHandler } = useScrollHandler(); // from redash
// can't be scrolled
...
<AnimatedFlatList
          {...scrollHandler}
          data={[...]}
          keyExtractor={keyExtractor}
          horizontal
          contentContainerStyle={{ paddingVertical: 10 }}
          pagingEnabled
          decelerationRate="fast"
          showsHorizontalScrollIndicator={false}
          renderItem={renderItem}
          onMomentumScrollEnd={({ nativeEvent: { contentOffset, contentSize } }) => {
            const selected = IndicatorSlider.getSelected(contentOffset.x, contentSize.width, tiers.tiers.length);
            activeIndex.setValue(selected);
          }}
        />
...
// its works
import { FlatList } from 'react-native-gesture-handler';
<FlatList
          ListEmptyComponent={PointCardEmpty}
          data={[...]}
          keyExtractor={keyExtractor}
          horizontal
          contentContainerStyle={{ paddingVertical: 10 }}
          pagingEnabled
          shouldActivateOnStart // <- add this
          decelerationRate="fast"
          showsHorizontalScrollIndicator={false}
          renderItem={renderItem}
          onMomentumScrollEnd={({ nativeEvent: { contentOffset, contentSize } }) => {
            const selected = IndicatorSlider.getSelected(contentOffset.x, contentSize.width, tiers.tiers.length);
            activeIndex.setValue(selected);
          }}
        />
```
```js
// cartList.tsx

 <AnimatedFlatList
        ListHeaderComponent={HeaderList}
        showsVerticalScrollIndicator={false}
        initialNumToRender={100}
        data={[...]}
        renderItem={renderItem}
        ItemSeparatorComponent={() => <VBox h={2} background={colors.lineColor} mx={16} />}
        contentContainerStyle={styles.container}
        ListHeaderComponentStyle={{ marginBottom: 20 }}
      />
```

## Package versions

- React: 17.0.2
- React Native: 0.65.2
- React Native Gesture Handler: 2.0.0, 2.1.0,  2.1.1

**Comment by j-piasecki** [comment]
Hi! Unfortunately I've been unable to reproduce this issue based on what you have provided. That said, if I understood you correctly the issue only occurs when using `AnimatedFlatList` and not `FlatList` from Gesture Handler. If that is the case, you could try adding `Native` gesture to the `AnimatedFlatList` like so:
```jsx
const nativeGesture = Gesture.Native().shouldActivateOnStart(true);
...
return (
  <GestureDetector gesture={nativeGesture}>
    <AnimatedFlatList ... />
  </GestureDetector>
);
```

If I misunderstood you or wrapping the FlatList with native gesture doesn't help, could you prepare a repository with a reproduction of this problem?

**Comment by dodicandra** [comment]
> Hi! Unfortunately I've been unable to reproduce this issue based on what you have provided. That said, if I understood you correctly the issue only occurs when using `AnimatedFlatList` and not `FlatList` from Gesture Handler. If that is the case, you could try adding `Native` gesture to the `AnimatedFlatList` like so:
> 
> ```js
> const nativeGesture = Gesture.Native().shouldActivateOnStart(true);
> ...
> return (
>   <GestureDetector gesture={nativeGesture}>
>     <AnimatedFlatList ... />
>   </GestureDetector>
> );
> ```
> 
> If I misunderstood you or wrapping the FlatList with native gesture doesn't help, could you prepare a repository with a reproduction of this problem?

Yes that's correct.
from the advice you gave I will try, but I need to know why to use `Gesture.Native().shouldActivateOnStart(true)` or props `shouldActivateOnStart `

thanks

**Comment by j-piasecki** [comment]
`FlatList` from Gesture Handler is a regular FlatList wrapped with `NativeViewGestureHandler`, which incorporated a native view into Gesture Handler's touch system. `Gesture.Native()` has the same functionality but uses the new API. `shouldActivateOnStart` tells Gesture Handler that the underlying view should start receiving events as soon as possible, and possibly cancel other gestures.

Now that I think about it, it may be possible to just use `Animated.createAnimatedComponent` on a `FlatList` exported by Gesture Handler.

**Comment by dodicandra** [comment]
using `Gesture.Native()` it still doesn't work, what works is just importing `FlatList` from gestureHandler by adding  `shouldActivateOnStart` props.

after i check my app another problem appears like `TouchableOpacity` can't be touched and `TextInput` won't focus if the component is in the `Animated.View`, this makes me still unable to migrate to version 2

**Comment by j-piasecki** [comment]
Could you prepare a repository with a reproduction of these issues so I can look into it?

**Comment by dodicandra** [comment]
@j-piasecki At the moment I haven't had a chance to replicate this thing in my repo. But I got a little tip, because I used `@react-navigation/stack@6.0.1` and on `Stack.Screen` tuned `gestureEnabled` options to `true` and `gestureDirection` to `horizontal`, can make the horizontal scroll untouchable. I'm still working on the `TouchableOpacity` issue on a few pages, for now asa solution I use `TouchableOpacity` import from `gesture-handler`.

**Comment by kmagiera** [comment]
Hi @dodicandra – would be great to have that small reproducible example from you to make any progress on this issue.

On top of that, it isn't recommended to use `createAnimatedComponent` on `FlatList`. Note that `FlatList` is a "virtual" component that renders `ScrollView` under the hood, and `createAnimatedComponent` really makes sense only when run on components that map directly to native views. If you want to use animated props for the ScrollView that FlatList controlls you should use `renderScrollComponent` prop (see https://reactnative.dev/docs/virtualizedlist#renderscrollcomponent)

**Comment by 256hz** [comment]
Thanks @dodicandra, shouldActivateOnStart worked for me on a regular ScrollView that wasn't scrolling on certain Androids.

**Comment by umardev500** [comment]
just add:
`failOffsetY={[-5, 5]} activeOffsetX={[-5, 5]}` props

in PanGestureHandler of trender item

`const renderItem = () => {
       return <PanGestureHandler failOffsetY={[-5, 5]} activeOffsetX={[-5, 5]} .... />
}`

first import FlatList from 'react-native-gesture-handler'

`
 <FlatList
        contentContainerStyle={styles.listContainer}
        data={data}
        renderItem={renderItem}
      />
`
