### ISSUE TITLE
Getting RCTBridge required dispatch_sync to load Warning LogBox

### ISSUE THREAD

**Issue by billnbell** [software-mansion/react-native-gesture-handler#1820]
Latest version getting:

RCTBridge required dispatch_sync to load

**Comment by billnbell** [comment]
v.2.1.1

**Comment by j-piasecki** [comment]
Hi! Thanks for the report, but is seems to be the same issue as https://github.com/software-mansion/react-native-gesture-handler/issues/1770. I'll close this one to keep discussion in one place.
