### ISSUE TITLE
Whitelisting of the new chain API doesn't seem to always work

### ISSUE THREAD

**Issue by wcandillon** [software-mansion/react-native-gesture-handler#1821]
With the v2 API I need to had the worklet directive to the callback. Sometimes it is not required. Not sure what trigger the whitelisting to not be detected sometimes.

**Comment by j-piasecki** [comment]
Hi! I believe that Reanimated's babel plugin is configured to only workletize callbacks that are defined in gesture configuration chain. I.e. this would be workletized:
```jsx
const gesture = Gesture.Tap().onBegin(() => {
  console.log(_WORKLET);
});
```

But this wouldn't:
```jsx
const gesture = Gesture.Tap();
gesture.onBegin(() => {
  console.log(_WORKLET);
});
```

```jsx
const callback = () => {
  console.log(_WORKLET);
};
const gesture = Gesture.Tap().onBegin(callback);
```

```jsx
const callback = () => {
  console.log(_WORKLET);
};
const gesture = Gesture.Tap();
gesture.onBegin(callback);
```
