### ISSUE TITLE
Nested NativeStackNavigator Scroll Bug

### ISSUE THREAD

**Issue by jthies73** [software-mansion/react-native-gesture-handler#1823]
## Description

It is not possible to create two nested ScrollViews (or ListViews) (react-native-gesture-handler version 2.1.0) with the current version of NativeStackNavigator from '@react-navigation/native-stack'.
If you try to scroll on the nested ScrollView it happens that you always trigger the parent ScrollView only. This was not an issue in previous versions.

I have to admit that I'm not sure whether it is an issue with ReactNavigation or react-native-gesture-handler. However it also happens with the react-native implementation of ScrollView and ListView.

IMPORTANT NOTE: the Bug seems to only appear when nesting two NativeStackNavigators inside of each other and using the nested ScrollViews inside the second StackNavigator. For now I am simply using a DrawerNavigator inside the RootStackNavigator, which solves the problem for now. (see linked repo down below for an example)

## Steps To Reproduce

1. create one NativeStackNavigator
2. create another NativeStackNavigator inside the first one
3. create two nested ScrollViews from react-native-gesture-handler inside the second NativeStackNavigator
4. try to scroll the second ScrollVIew and only the first one will trigger

### Expected behavior

Each ScrollView can be scrolled independently.

### Actual behavior

When using NativeStackNavigator (inside RootStackNavigator) and dragging a nested ScrollView only the parent ScrollView responds to the gesture.

## Snack or minimal code example

bug showcase:
https://github.com/jthies73/NativeStackNavigatorIssue

last working version: (react-native-gesture-handler 1.10.3)
https://github.com/jthies73/NativeStackNavigatorIssue/tree/last_working_version

## Platform
- [ ] iOS
- [X] Android
- [ ] Web 
- [ ] Windows
- [ ] tvOS

## Workflow
- [X] Managed workflow
- [ ] Bare workflow

## Package versions
| package                                | version |
| -------------------------------------- | ------- |
| react-native                           |    0.64.3     |
| @react-navigation/native               |     6.0.6    |
| @react-navigation/native-stack         |    6.2.5     |
| react-native-screens                   |     3.10.1    |
| react-native-safe-area-context         |    3.3.2     |
| react-native-gesture-handler           |    2.1.0     |
| react-native-reanimated                |     2.3.1    |
| expo                                   |     44.0.0    |

**Comment by jthies73** [comment]
I have posted this issue in react-native-sceens and react-navigation already since I first thought it was related to the NatvieStackNavigator. However it seems the version of react-navigation/native-stack does not have an impact on the bug.
I figured out that it is most likely related to the 2.x implementation of react-native-gesture-handler since everything works fine in the 1.10.x version with expo 43.x.x. -> see  https://github.com/jthies73/NativeStackNavigatorIssue/tree/last_working_version

Also it is worth noting that the bug only happens on Android devices. I am assuming it is related to the feature of being able to scroll the parent ScrollView once the nested ScrollView is scrolled to its end. This works fine on iOS with any version of react-native-gesture-handler but does not work with 2.x.x on android.

I hope this information helps to solve the issue.

**Comment by j-piasecki** [comment]
Hi! Thanks for the detailed report and code samples. I believe this issue is somewhat correlated to the deprecation of `RNGestureHandlerEnabledRootView`. Expo 43 is still using it, while Expo 44 is not. Could you try wrapping your root application component with `GestureHandlerRootView`?

In case of the example you have provided that would mean changing `App.js`:
```tsx
export default function App() {
    return (
        <GestureHandlerRootView style={{flex: 1}}>
            <RootNavigator/>
        </GestureHandlerRootView>
    );
}
```

Or `index.js`:
```tsx
registerRootComponent(gestureHandlerRootHOC(App));
```

**Comment by jthies73** [comment]
Thank! That worked! 👍

**Comment by j-piasecki** [comment]
Great! I'll close the issue then.
