### ISSUE TITLE
RCTBridge required dispatch_sync to load RNGestureHandlerModule

### ISSUE THREAD

**Issue by billnbell** [software-mansion/react-native-gesture-handler#1825]
Latest version. Not sure why I am getting this.

RCTBridge required dispatch_sync to load RNGestureHandlerModule

**Comment by vanenshi** [comment]
Same Here

**Comment by j-piasecki** [comment]
Hi! This issue is a duplicate of https://github.com/software-mansion/react-native-gesture-handler/issues/1770. I'll close this one in order to keep the discussion in one place.
