### ISSUE TITLE
V2.2.0 New Warning: [react-native-gesture-handler] Seems like you're using an old API with gesture components, check out new Gestures system!

### ISSUE THREAD

**Issue by erez-unitronics** [software-mansion/react-native-gesture-handler#1831]
Hello,

I've been upgraded the library to the new version: 2.2.0 And now I've got this warning:
"[react-native-gesture-handler] Seems like you're using an old API with gesture components, check out new Gestures system!"

Should I do something?
Thanks!

**Comment by andybui090** [comment]
The same

**Comment by OtayNacef** [comment]
The same

**Comment by parmarravi** [comment]
Same !! any fix

**Comment by GuillermoSM5** [comment]
The same warning

**Comment by michaelypes** [comment]
For me it was the react navigation library. I upgraded from 5 to 6 but hadn't got round to updating the stacks. If you upgrade to the new stack library it should remove the warning. Tested this on Android and worked for me.

@react-navigation/stack => @react-navigation/native-stack

Also the native stack is supposedly more performant.

https://reactnavigation.org/docs/native-stack-navigator

**Comment by jensonjohn001** [comment]
facing the same issue, any fix?

**Comment by Shamia-Medcon** [comment]
The same warning for me too, any fix?

**Comment by GustavoGomesRibeiro** [comment]
@erez-unitronics Try to updated to last version: yarn add react-native-gesture-handler@2.1.1

I fixed the problem with update.

**Comment by Sepudev** [comment]
> @erez-unitronics Try update to lastest version: yarn add react-native-gesture-handler@2.1.1
> 
> I fixed the problem with update.

This solution worked perfectly for me, and fixes the warning, thank you!

**Comment by cmoztas** [comment]
> For me it was the react navigation library. I upgraded from 5 to 6 but hadn't got round to updating the stacks. If you upgrade to the new stack library it should remove the warning. Tested this on Android and worked for me.
> 
> @react-navigation/stack => @react-navigation/native-stack
> 
> Also the native stack is supposedly more performant.
> 
> https://reactnavigation.org/docs/native-stack-navigator

@michaelypes Thanks. I got the same issue and it's fixed after install native-stack package.

**Comment by Hirbod** [comment]
Guys, this is not a bug that has to be fixed. Its a simple warning/ notification
https://github.com/software-mansion/react-native-gesture-handler/pull/1817

You can easily suppress it. RNGH is still backwards compatible

**Comment by erez-unitronics** [comment]
> @erez-unitronics Try update to lastest version: yarn add react-native-gesture-handler@2.1.1
> 
> I fixed the problem with update.

@GustavoGomesRibeiro  Thanks, but I started to get this warning after is updated react-native-gesture-handler from 2.1.1 to 2.2.0.
I guess its just a simple warning like @Hirbod said

**Comment by iskanderAB** [comment]
just use this version : 2.1.1  ( yarn add react-native-gesture-handler@2.1.1 )

**Comment by michaelypes** [comment]
If you are trying to upgrade all the libraries in your app the warning is actually helpful in working out what components have been updated to use the new gesture handler.

**Comment by dezudas** [comment]
> @GustavoGomesRibeiro Thanks, but I started to get this warning after I updated react-native-gesture-handler from 2.1.1 to 2.2.0. I guess its just a simple warning like @Hirbod said


I am getting to the warning too

**Comment by armata007** [comment]
It shows for me when using Swipeable component (if I remove it the warning does not show). Is there any new api for Swipeable component we can use?

**Comment by cristianoccazinsp** [comment]
For me it comes from react-native-screens (or navigation) using PanGestureHandler.

**Comment by cm-nutrien** [comment]
We use an internal testing package that my team doesn't control. It will fail our tests if there are usages of `console.warn` or `console.error` and since I can't change the version of this library that we use I'm left with failing tests without a way to intercept the message to block it. 

The PR where this was implemented said it was supposed to be a `console.info` but it was implemented as a `console.warn`. Was that deliberate? Can it be changed to `console.info`? Better yet, can it be removed entirely?

**Comment by cristianoccazinsp** [comment]
I agree, remove the log completely and make a deprecation notice somewhere.

**Comment by Kesmek** [comment]
> What I would like to know is how to use the new Gestures system, if I'm using the old API I want to know it. I'm using the panGestureHandler component which is triggering the warning. Is panGestureHandler deprecated or something?

As far as I know, it's not deprecated (yet), but it is suggested to use the [new API](https://docs.swmansion.com/react-native-gesture-handler/docs/gesture-composition) as I assume that is the one that will receive the most development time. From what I understand the log was meant to improve discoverability of the new API since people may not know it exists but I think having a log is a somewhat crude way of accomplishing that, especially since it's currently out of many people's hands due to other libraries using the old API right now. Perhaps having a short section in the README with links to the documentation could accomplish the same goal?

@cm-nutrien You raise a good point: it was supposed to be a `console.info` and not a warning. I suggest you make a pull request or a new issue to bring it up to the RNGH team.

In case anyone missed it, I explained how to suppress the issue [above](https://github.com/software-mansion/react-native-gesture-handler/issues/1831#issuecomment-1014768871).

**Comment by n3pixowe** [comment]
As mentioned in the official Stack Navigator documents, you should also install the react-native-gesture-handler module. To install this module:
1. If you are using Expo development tool, use this command: `expo install react-native-gesture-handler`
2. If you are using bare React Native then use this command: `npm install react-native-gesture-handler`
Hope this helps.
Official documentation: [Stack Navigator](https://reactnavigation.org/docs/stack-navigator)

**Comment by pilotpirxie** [comment]
I've got the same warning. Trying 2.1.0, 2.1.1 and 2.2.0 with reinstalling all deps, Pods and Podfile.lock. Nothing helped.

Every day in React Native ecosystem is like an adventure. You never know what will happen tomorrow. Deprecation warning without info on how to fix the issue? You got it. Facebook (creators of RN) removing official SDK for login to Facebook? Why not. Auto-linking feature in most of the libs, where you still need to manually dig into native swift/java files to make it run? Of course.

**Comment by billnbell** [comment]
> As mentioned in the official [Stack Navigator documents](https://reactnavigation.org/docs/stack-navigator#installation), you should also install the react-native-gesture-handler module. To install this module:
> 
> 1. If you are using Expo development tool, use this command: `expo install react-native-gesture-handler`
> 2. If you are using bare React Native then use this command: `npm install react-native-gesture-handler`
> 
> Hope this helps.

It does not help. I have no dependencies, and v2.2.0 says this stupid message.

**Comment by michaelypes** [comment]
> 

I don't think stack navigator uses the new api. I have a lot of modules in my app that use the stack navigator and i get the error every time it renders a module using the normal stack -  "@react-navigation/native-stack": "^6.2.5".

If i change to the native-stack navigator then the error goes away. I am assuming that is because it is using the new gesture handler. Unfortunately i can't use that navigator as I need to wrap my navigators in the context api. So i have 2 questions:

1) Is the normal stack navigator (."@react-navigation/native-stack": "^6.2.5" ) using the new gesture handler and if not anyone know when.
2) Is there a way to wrap context around multiple native navigators. I use a custom navigator using the old stack navigator with a StackView but i dont think this is available in the native-stack.

**Comment by Raman-3r** [comment]
i also face this issue  when i use "@react-navigation/native": "^5.9.8",
    "@react-navigation/stack": "^5.14.9",
    "react": "17.0.2",
    "react-native": "0.66.4",
    "react-native-gesture-handler": "^2.2.0",

when i try to downgrade gesture-handler it also show an error
please anyone tell me how to fix it ?

**Comment by lucaspedronet** [comment]
@GustavoGomesRibeiro atualizei a lib para versão menciona, funcionou perfeitamente. Obrigado!

**Comment by naishe** [comment]
```json
    "@gorhom/bottom-sheet": "^4.1.5",
    "react": "17.0.2",
    "react-native": "0.66.3",
    "react-native-gesture-handler": "^2.2.0",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-reanimated": "^2.3.1",
```

I am facing this issue, even though I have updated all the libraries that indirectly depend on reanimated.

**Comment by Kesmek** [comment]
> ```json
>     "@gorhom/bottom-sheet": "^4.1.5",
>     "react": "17.0.2",
>     "react-native": "0.66.3",
>     "react-native-gesture-handler": "^2.2.0",
>     "react-native-linear-gradient": "^2.5.6",
>     "react-native-reanimated": "^2.3.1",
> ```
> 
> I am facing this issue, even though I have updated all the libraries that indirectly depend on reanimated.

[@gorhom/bottom-sheet](https://github.com/gorhom/react-native-bottom-sheet) Still uses the [old API](https://github.com/gorhom/react-native-bottom-sheet/blob/master/src/hooks/useGestureHandler.ts), make sure to notify the library maintainer of the new API. 

Also in case you are mistaken, you should check for libraries that depend on react-native-gesture-handler and not necessarily react-native-reanimated even though they are often used together.

**Comment by kodeandoec** [comment]
The problem specific is with **@react-navigation/stack**, install and use **@react-navigation/native-stack** and solve the issue...!

**Comment by billnbell** [comment]
> The problem specific is with **@react-navigation/stack**, install and use **@react-navigation/native-stack** and solve the issue...!

Not sure that is a real solution. We need a fix for @react-navigation/stack

**Comment by giladgray** [comment]
this error message is a poor developer experience because it's not _useful_ and rarely _actionable_ by the person who sees it. ideally, if you _must_ warn about this at all, there would be a link in the message to docs for how to migrate to the new API, like React's warnings with stable links to docs.
also, ideally i could turn off such warnings without having to `LogBox`-ignore it (which only works until the text is changed).

the simplest solution would be to remove this unhelpful warning entirely: avoid inflicting any headaches on your community. instead, eventually, when you decide to remove support for this old API, you can add a stronger message to encourage migration (along with a plan and a major version bump).

**Comment by michaelypes** [comment]
> 

So it is definitely the the original stack navigator which is causing the issue. Updating to the native stack is not an option as it does not support everything that the original stack does. I am assuming that this might be why it cannot or is not updated. 

See quote from react navigation: https://reactnavigation.org/docs/native-stack-navigator/

_"One thing to keep in mind is that while @react-navigation/native-stack offers native performance and exposes native features such as large title on iOS etc., it may not be as customizable as @react-navigation/stack depending on your needs. So if you need more customization than what's possible in this navigator, consider using @react-navigation/stack instead - which is a more customizable JavaScript based implementation."_

**Comment by BadrBelhiti** [comment]
I had this problem, because my IDE was auto-importing `FlatList` and `TextInput` from `react-native-gesture-handler` as opposed to `react-native`.

**Comment by UVStudio** [comment]
> For me it was the react navigation library. I upgraded from 5 to 6 but hadn't got round to updating the stacks. If you upgrade to the new stack library it should remove the warning. Tested this on Android and worked for me.
> 
> @react-navigation/stack => @react-navigation/native-stack
> 
> Also the native stack is supposedly more performant.
> 
> https://reactnavigation.org/docs/native-stack-navigator

You might've just fixed a bug that I have been working on for the last 3 full days straight. Thank you sir!

**Comment by billnbell** [comment]
> > For me it was the react navigation library. I upgraded from 5 to 6 but hadn't got round to updating the stacks. If you upgrade to the new stack library it should remove the warning. Tested this on Android and worked for me.
> > @react-navigation/stack => @react-navigation/native-stack
> > Also the native stack is supposedly more performant.
> > https://reactnavigation.org/docs/native-stack-navigator
> 
> You might've just fixed a bug that I have been working on for the last 3 full days straight. Thank you sir!

The native stack is "no an upgrade" it is different.

So I guess we narrowed it down to @react-navigation/stack

**Comment by kodeandoec** [comment]
Just install **react-native-gesture-handler": "2.1.1,** use this version and solve issue

**Comment by billnbell** [comment]
Can someone apply what works on 2.1.1 to 2.2.1?

**Comment by mostafijur-rahman299** [comment]
> @erez-unitronics Try update to lastest version: yarn add react-native-gesture-handler@2.1.1
> 
> I fixed the problem with update.

This solution worked perfectly

**Comment by Omelyan** [comment]
This warning is showing me when I use TouchableOpacity imported from 'react-native-gesture-handler'.

**Comment by featlast** [comment]
Hola. Saludos.. solucione con esto npm i react-native-gesture-handler@2.1.1

**Comment by premdasvm** [comment]
> This was mentioned in #1817 when it was added. If you are certain that you are no longer using the old API, then it likely due to one of the libraries you use that is giving you this warning. If that's the case there is nothing for you to do but let the library maintainers know and wait for them to update their libraries. #1817 also gives a work around to ignore the warning, I'll paste it here for convenience.
> 
> ```tsx
> import { LogBox } from 'react-native';
> 
> LogBox.ignoreLogs([
>   "[react-native-gesture-handler] Seems like you\'re using an old API with gesture components, check out new Gestures system!",
> ]);
> ```

This seems to ignore all the warning not just this.!

**Comment by alpha0010** [comment]
> This warning is showing me when I use TouchableOpacity imported from 'react-native-gesture-handler'.

Looks like this may be the case for all components provided by RNGH.  I am getting it from `BorderlessButton`, `Swipeable`, `ScrollView`, and others.

Not sure if they have an intended alternative.

**Comment by billnbell** [comment]
Yes same here.

**Comment by Srh07** [comment]
I'm getting this warning for using @react-navigation/stack (latest). I don't use any components provided by RNGH.
Any ideas on how to solve this?

**Comment by anwarhamr** [comment]
> For me it was the react navigation library. I upgraded from 5 to 6 but hadn't got round to updating the stacks. If you upgrade to the new stack library it should remove the warning. Tested this on Android and worked for me.
> 
> @react-navigation/stack => @react-navigation/native-stack
> 
> Also the native stack is supposedly more performant.
> 
> https://reactnavigation.org/docs/native-stack-navigator

I'm getting the above message.  We are using stack-navigator and it is the current version specified in this 'fix' so it does not work for us.
Anyone else figure it out?  We don't want to turn off any notification using LogBox.  
Cheers!

**Comment by michelazzam** [comment]
> @erez-unitronics Try update to lastest version: yarn add react-native-gesture-handler@2.1.1
> 
> I fixed the problem with update.

**To anyone who tried this version and didn't remove their warning, try removing '^' before 2.1.1 in package.json and reinstall your packages**

**Comment by konyilwin** [comment]
For me, I try expo install react-native-gesture-handler instead of yarn, npm. The warning is gone.

**Comment by anwarhamr** [comment]
> > @erez-unitronics Try update to lastest version: yarn add react-native-gesture-handler@2.1.1
> > I fixed the problem with update.
> 
> **To anyone who tried this version and didn't remove their warning, try removing '^' before 2.1.1 in package.json and reinstall your packages**

This did the trick but I'm pretty sure we'll want an upgrade at some point in the future so 2.2 would be nice.

**Comment by NensiKasundra** [comment]
I'm facing this issue with 
`"react-native-gesture-handler": "^2.3.0",`

 WARN [react-native-gesture-handler] Seems like you're using an old API with gesture components, check out new Gestures system! 

Any Solution for this!

**Comment by symplytheo** [comment]
> I'm facing this issue with `"react-native-gesture-handler": "^2.3.0",`
> 
> WARN [react-native-gesture-handler] Seems like you're using an old API with gesture components, check out new Gestures system!
> 
> Any Solution for this!

Well, it seems we are currently facing the same issue. 
````"@react-navigation/native-stack": "^6.5.0"````
````"react-native-gesture-handler": "^2.3.0",````

**Comment by symplytheo** [comment]
Well, it's just a warning so i guess you can dismiss it and move on with life and coding. I dismissed it and it hasn't popup so far

**Comment by symplytheo** [comment]
> I'm facing this issue with `"react-native-gesture-handler": "^2.3.0",`
> 
> WARN [react-native-gesture-handler] Seems like you're using an old API with gesture components, check out new Gestures system!
> 
> Any Solution for this!
````js
import { LogBox } from 'react-native';

LogBox.ignoreLogs([
  "[react-native-gesture-handler] Seems like you're using an old API with gesture components, check out new Gestures system!",
]);
````

This worked for me. I added that in my entry file ````index.js````

**Comment by NoerNova** [comment]
Warning still appears in version 2.3.1.

LogBox workaround is fine.

**Comment by EstopaceMA** [comment]
I appreciate the LogBox workaround but is there anyone who fix it on the latest version 2.3.1?

**Comment by dawid-bobowski** [comment]
@NoerNova @EstopaceMA for my project swapping from @react-navigation/stack to @react-navigation/native-stack was enough.

> For me it was the react navigation library. I upgraded from 5 to 6 but hadn't got round to updating the stacks. If you upgrade to the new stack library it should remove the warning. Tested this on Android and worked for me.
> 
> @react-navigation/stack => @react-navigation/native-stack
> 
> Also the native stack is supposedly more performant.
> 
> https://reactnavigation.org/docs/native-stack-navigator

**Comment by marcos-development-business** [comment]
> @erez-unitronics Try update to lastest version: yarn add react-native-gesture-handler@2.1.1
> 
> I fixed the problem with update.

this works perfectly form me, thanks

**Comment by billnbell** [comment]
Marcos. 2.1.1 is an OLD version. The latest is 2.3.2. So why would anyone go back to 2.1.1?

**Comment by dezudas** [comment]
> Marcos. 2.1.1 is an OLD version. The latest is 2.3.2. So why would anyone go back to 2.1.1?

Coz that’s the only way to remove the warning text.

**Comment by iamn1ck** [comment]
I have just been going through my project and updating dependencies and am encountering this error too. I tried changing my @react-navigation/stack => @react-navigation/native-stack, but now the warning is referencing the drawer nav.

` WARN  [react-native-gesture-handler] Seems like you're using an old API with gesture components, check out new Gestures system! 
    at PanGestureHandler (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.bet3000&modulesOnly=false&runModule=true:141318:38)
    at Drawer (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.bet3000&modulesOnly=false&runModule=true:148474:26)
    at DrawerViewBase (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.bet3000&modulesOnly=false&runModule=true:127380:22)`

**Comment by arthurgeron-work** [comment]
I'm dumbfounded that devs took effort to add a warning about the old API but didn't bother to actually write a migration guide. So as mentioned by @giladgray this is hardly actionable by who sees the warning.. Can we pelase get a migration guide? I'm not fund of deploying to production using a libs old API which could lead to problems, so just disabling the warning doesn't cut it.

**Comment by gabrielmoncea** [comment]
@arthurgeron-work this worked for me! Do you know if there is a migration guide for the components?

**Comment by pehagg** [comment]
Please consider removing or making this into an info level log. We have several dependencies in our app that use the old APIs. The app is now pestered with YellowBox warnings. Sure, we can suppress the warning, but hey, come on, this is not the way to promote new features, think of a better way next time. Thank you.

**Comment by j-piasecki** [comment]
@pehagg the warning has been removed in Gesture Handler 2.4.0, and that change has also been backported to 2.2.1.
