### ISSUE TITLE
RectButton inside a modal react-navigation

### ISSUE THREAD

**Issue by eduardorfreitas93** [software-mansion/react-native-gesture-handler#1837]
## Description

I'm trying to call the RectButton inside a modal of createStackNavigator(@react-navigation/stack), on android the RectButton doesn't trigger onPress, BorderlessButton works

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web

## Snack or minimal code example

```
export const Container = styled(RectButton)``;

<Container onPress={handleBack}>
      <Text>...</Text>
</Container>
```

```
<Navigator screenOptions={{ presentation: 'modal', headerShown: false }}>
      <Screen name="..." component={...} />
</Navigator>
```

## Package versions

- React: 17.0.1
- React Native: 0.64.3
- React Native Gesture Handler: ~2.1.0
- React Native Reanimated: ~2.3.1
- @react-navigation/native: ^6.0.6
- @react-navigation/stack: ^6.0.11

**Comment by eduardorfreitas93** [comment]
In version React Native Gesture Handler: ~1.10.3 it worked

**Comment by j-piasecki** [comment]
It it's working outside of modal then wrapping the modal screen with `GestureHandlerRootView` may help. If it doesn't, could you provide a repository with a reproduction?
