### ISSUE TITLE
FlatList does not have any of the scrollTo methods available on its ref 

### ISSUE THREAD

**Issue by haibert** [software-mansion/react-native-gesture-handler#1838]
## Description
FlatList ref is returning undefined for the scrollToIndex method

### Platforms

- [x ] iOS
- [x ] Android
- [ ] Web

## Steps To Reproduce

1. set up a flat list from RNGH
2. wire up a ref
3. try to call  
 
 ``` java script
 listRef.current?.scrollToIndex({
                index: YOUR_INDEX,
                animated: false,
            })
```
### Expected behavior
the method. should exist on the ref
### Actual behavior
it does not, if you console.log( typeof listRef.current?.scrollToIndex ) it returns undefined
## Snack or minimal code example

``` Java script

const listRef = useAnimatedRef()

                   <FlatList
                    ref={listRef}
                    ....
                    />
```
-->

## Package versions
"react-native-gesture-handler": "~1.10.2",
"react-native-reanimated": "~2.3.1",
<!--
Fill in your Gesture Handler and React Native versions below.

- React: "17.0.1",
- React Native: 0.64.3
- React Native Gesture Handler: 1.10.2
- React Native Reanimated: 2.3.1

**Comment by j-piasecki** [comment]
Hi! I've been unable to reproduce this bug on Gesture Handler 2.2.0, it's possible that it's been already fixed. Do you mind checking?

**Comment by haibert** [comment]
@j-piasecki right now expo has an issue with RNGH 2 so I'm hesitant to update it. 

https://github.com/expo/expo/issues/15681

**Comment by jakub-gonet** [comment]
I can confirm this works on the latest Gesture Handler.
