### ISSUE TITLE
Support for nested BorderlessButton (ButtonRect etc)

### ISSUE THREAD

**Issue by Paul-Todd** [software-mansion/react-native-gesture-handler#184]
Lets say I have a list which has a row that is clickable and in the list I have a reveal button that pops up a menu. If I nest these then the popup menu handler is never reached as the enclosing row handler grabs it first. I see from the code this is intentional and using a TapGestureHandler for the popup does work but the popup does not highlight when clicked.

Is this planning to be fixed as I see this is more of an issue in the native code than the JS code.

**Comment by Paul-Todd** [comment]
Lets say I have a list which has a row that is clickable and in the list I have a reveal button that pops up a menu. If I nest these then the popup menu handler is never reached as the enclosing row handler grabs it first. I see from the code this is intentional and using a TapGestureHandler for the popup does work but the popup does not highlight when clicked.

Is this planning to be fixed as I see this is more of an issue in the native code than the JS code.

**Comment by kmagiera** [comment]
Thanks @Paul-Todd for reporting. I'm not entirely sure if I understand your case. Would you mind sharing some simple app or a component snippet that illustrates it? This would make it much simpler for us to see what's going on.

In general for "clickable" things that have some sort of structure you should use "Button" components instead. They rely on platform specific built-in mechanism when it comes to nesting and you should not have any issue with those. "Tap" handler should be more for things like dialog overlay, things that you can interact with by tapping but they don't show any feedback.

**Comment by radex** [comment]
isn't this something that was fixed?

**Comment by kmagiera** [comment]
As mentioned in my previous comment – I'm unsure if this issue requires fixing. Would love some feedback from @Paul-Todd on it

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
If you need further help please reply.
