### ISSUE TITLE
GestureDetector not working on the web

### ISSUE THREAD

**Issue by thespacemanatee** [software-mansion/react-native-gesture-handler#1840]
## Description
When I try to use `GestureDetector` on the web, I get the following error: `Uncaught TypeError: Cannot read properties of undefined (reading 'current')`

### Platforms

- [ ] iOS
- [ ] Android
- [x] Web

### Screenshots
<img width="1091" alt="Screenshot 2022-01-24 at 10 04 05 PM" src="https://user-images.githubusercontent.com/6837599/150797123-c64bb612-e996-4a28-a56e-bb21c0b8aa94.png">

## Steps To Reproduce

1. Try to use `GestureDetector` on the web
2. Start swiping
3. `Uncaught TypeError: Cannot read properties of undefined (reading 'current')`

### Expected behavior
Events should fire as per normal

### Actual behavior
Throws `Uncaught TypeError: Cannot read properties of undefined (reading 'current')` on the web

## Snack or minimal code example
```js
const gesture = Gesture.Pan()
  .onBegin(() => {
    offset.value.x = translateX.value;
  })
  .onUpdate(({ translationX }) => {
    const newX = offset.value.x + translationX;
    translateX.value = newX;
    rotate.value = newX / 10;
  })
  .onEnd(({ velocityX }) => {
    const dest = snapPoint(translateX.value, velocityX, snapPoints);
    translateX.value = withSpring(dest, { velocity: velocityX });
    rotate.value = withTiming(0, {}, () => {
      if (dest > 0) {
        runOnJS(onSwipeRight)();
      } else if (dest < 0) {
        runOnJS(onSwipeLeft)();
      }
    });
  })
  .enabled(enabled);

<View style={styles.container} pointerEvents="box-none">
  {Platform.OS === "web" ? ( // have to use the old PanGestureHandler for web
    <PanGestureHandler onGestureEvent={onGestureEvent} enabled={enabled}>
      <Animated.View style={style}>
        <TaskCard source={source} taskIndex={taskIndex} />
      </Animated.View>
    </PanGestureHandler>
  ) : (
    <GestureDetector gesture={gesture}>
      <Animated.View style={style}>
        <TaskCard source={source} taskIndex={taskIndex} />
      </Animated.View>
    </GestureDetector>
  )}
</View>
```

## Package versions

- React: `17.0.1`
- React Native: `0.64.3`
- React Native Gesture Handler: `^2.2.0`
- React Native Reanimated: `~2.3.1`

**Comment by maxmezzomo** [comment]
I have similar issue. For example replicating the ball example from docs `https://docs.swmansion.com/react-native-gesture-handler/docs/quickstart/quickstart`. This is the error I get on initalizing an interaction:

```
Uncaught TypeError: can't access property "current", _this.propsRef is undefined
    GestureHandler GestureHandler.ts:196
    onGestureActivated GestureHandler.ts:336
    setupEvents GestureHandler.ts:318
    emit hammer.esm.js:2711
    emit hammer.esm.js:1597
    emit hammer.esm.js:1605
    emit hammer.esm.js:2027
    tryEmit hammer.esm.js:1628
    recognize hammer.esm.js:1681
    recognize hammer.esm.js:2548
    inputHandler hammer.esm.js:716
    handler hammer.esm.js:940
    node_modules bundle.js:7847
    node_modules bundle.js:7796
    each hammer.esm.js:189
    addEventListeners hammer.esm.js:739
    init hammer.esm.js:816
    Input hammer.esm.js:795
    PointerEventInput hammer.esm.js:901
    createInputInstance hammer.esm.js:1328
    Manager hammer.esm.js:2455
    setView GestureHandler.ts:267
    attachGestureHandler RNGestureHandlerModule.web.ts:50
    attachHandlers GestureDetector.tsx:145
    GestureDetector GestureDetector.tsx:454
    React 5
    unstable_runWithPriority scheduler.development.js:468
    React 3
    workLoop scheduler.development.js:417
    flushWork scheduler.development.js:390
    performWorkUntilDeadline scheduler.development.js:157
    js scheduler.development.js:180
    js scheduler.development.js:645
    Webpack 35
GestureHandler.ts:196
```
It's not clear to me if web is supported fully by this library, only on expo I see `https://docs.expo.dev/versions/latest/sdk/gesture-handler/`. From what I've been seeing there are a few issues with reactive-native-web and several libraries that I'm not sure how to resolve or avoid for now.  Perhapes downgrading some libraries.

Thse are the version I am using:
expo@44.0.5
react-native-web@0.17.1
react-native-gesture-handler@2.1.1
react-native-reanimated@2.3.1

All were installed with expo install. 

I've been finding it difficult to debug anything with expo, compared to plain react apps I usually work with, but as far as I can tell the error might have something to do with hammer.js.

Maybe related the example at `https://github.com/software-mansion/react-native-gesture-handler` also did not work on web for me, if you need more info for this I can send.

Hope some of this helps.

Best

**Comment by mrsimply** [comment]
As Expo was mentioned here and #1869, this is not an issue related to Expo. I'm facing this issue without Expo (I'm using CRA in a cross-platform setup). GestureDetector simply does not work in Web 😞
