### ISSUE TITLE
<PanGestureHandler> not working in <Modal>

### ISSUE THREAD

**Issue by Stevemoretz** [software-mansion/react-native-gesture-handler#1841]
## Description
GestureHandler stops working when put in modal (only in iOS).
I had this exact same issue on Android and not on iOS but now updating to the latest version, it works on Android and not on iOS :)

```tsx
import React from "react";
import {Modal, View} from "react-native";
import {
    gestureHandlerRootHOC,
    PanGestureHandler,
} from "react-native-gesture-handler";
import Animated, {useAnimatedGestureHandler} from "react-native-reanimated";

type Props = object;
const ExampleWithHoc = gestureHandlerRootHOC((props) => <>{props.children}</>);
const TestModalIos = (props: Props) => {
    const gestureHandler = useAnimatedGestureHandler({
        onStart: (_, ctx) => {
            console.log("triggered");
        },
        onActive: (event, ctx) => {
            console.log("triggered");
        },
        onEnd: (_) => {
            console.log("triggered");
        },
    });
    return (
        <Modal visible>
            <ExampleWithHoc>
                <PanGestureHandler onGestureEvent={gestureHandler}>
                    <Animated.View
                        style={{
                            width: 500,
                            height: 500,
                            backgroundColor: "pink",
                        }}
                    />
                </PanGestureHandler>
            </ExampleWithHoc>
        </Modal>
    );
};

export default TestModalIos;
```
The above example logs everything on android, but on iOS nothing is logged.

### Platforms

- [X ] iOS
- [ ] Android

## Steps To Reproduce

1. Just use the code above it won't log. (Be sure you have the exact package versions as mine.)

### Expected behavior
Gesture handler should work.
### Actual behavior
it doesn't.
## Snack or minimal code example

Here's a snack : 
https://snack.expo.dev/@stevemoretz/quiet-bubblegum

But it works (logs) because the snack versions are a little older (They're going to update it just haven't yet.)

```
    "react-native-gesture-handler": "~1.10.2",
    "react-native-reanimated": "~2.2.0"
```

But I'm using newer versions, and the issue occurs there.

For testing that just copy the code above or from the snack and use it with the versions that I'm using. (Latest versions probably).

## Package versions

- React: 17.0.1
- React Native: 0.64.3
- React Native Gesture Handler: ~2.1.0
- React Native Reanimated: ~2.3.1

so Basically Expo SDK 44.

**Comment by j-piasecki** [comment]
Hi! I've tried the snipped you have provided but for me it works in managed Expo 44 as well as when I ejected the project. Could you prepare a repository with a reproduction?

**Comment by Stevemoretz** [comment]
Creating a new minimal project made it work :(
Doesn't work on my real project.
Sorry for waisting your time :(
