### ISSUE TITLE
PanGestureChangeEventPayload type is not exported

### ISSUE THREAD

**Issue by gaeljoliveau** [software-mansion/react-native-gesture-handler#1845]
## Description

The type PanGestureChangeEventPayload type is not exported so I can't properly type my event using the onChange callback.

### Platforms

- [ ] iOS
- [x ] Android
- [ ] Web

### Screenshots

![image](https://user-images.githubusercontent.com/35953784/151155014-fe7598b8-3214-4c75-a633-14692b665c6d.png)

## Steps To Reproduce

1.

### Expected behavior
Being able to import the PanGestureChangeEventPayload type

### Actual behavior
I'm not able to import the PanGestureChangeEventPayload type

## Package versions

- React: 17.0.2
- React Native: 0.66.4
- React Native Gesture Handler: 2.2.0
- React Native Reanimated: not used

**Comment by jakub-gonet** [comment]
Thanks for reporting, I prepared a PR.
