### ISSUE TITLE
Swipeable not working with react-navigation/native-stack

### ISSUE THREAD

**Issue by aqmebrak** [software-mansion/react-native-gesture-handler#1858]
## Description

Hello, I recently upgraded react-navigation v4 to v6 and my `Swipeable` gesture stopped working since then. After some manual git bisect I found that passing from @react-navigation/stack to @react-navigation/native-stack was the problem. I am using Android only so I don't really know if it's not working either for iOS.

### Platforms

- [ ] iOS
- [x] Android
- [ ] Web

## Steps To Reproduce

1. Create main native stack + nested native stack
2. add a Swipeable to a screen inside that nested stack
3. Running on Expo android simulator works fine, but swipeable is not responding on real device

## Snack or minimal code example

https://snack.expo.dev/@aqmebrak/swipeable-bug

## Package versions

   "react-native-screens": "3.10.1",
    "@react-navigation/native": "^6.0.6",
    "@react-navigation/routers": "^6.1.0",
    "@react-navigation/native-stack": "^6.0.6",
    "react-native-gesture-handler": "1.10.3",
    "react-native-safe-area-context": "3.3.2"

- React: 17
- React Native: 0.64.3
- React Native Gesture Handler: 1.10.3
- React Native Reanimated: -

**Comment by davimartinsdm01** [comment]
I'm facing a similar issue, also working with stack naviagtion. Swipeable works in the android emulator but does not work in the physical device.

**Comment by ShubhamBirari** [comment]
I too am facing the similar issue. Swipeable does not work in my android emulator as well as physical device. These are my dependencies 

```
    "@react-native-community/hooks": "^2.8.1",
    "expo": "~44.0.0",
    "expo-status-bar": "~1.2.0",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-gesture-handler": "~2.1.0",
    "react-native-web": "0.17.1"
  ```

**Comment by j-piasecki** [comment]
Hi! Unfortunately, I haven't been able to reproduce this issue. I tried the snack you have provided on the emulator in the browser alongside snack, using Expo Go on a physical device and emulator, and ejected the project to see if that would change anything. The swipeable worked correctly in every case.

**Comment by aqmebrak** [comment]
Hi @j-piasecki thanks for checking my issue ! I tried again today and ran the little project I've set up instead of the snack link, and it is still not possible to swipe when using /native-stack, whereas when I switch to /stack lib it is working fine

Here is the repo, I have commented the code to quick switch between the two libraries: https://github.com/aqmebrak/native-stack-swipeable-bug

Could it be related to the Android device I am using ? It is a Zebra TC57HO with Android 8.1.0

**Comment by j-piasecki** [comment]
Could you check if wrapping your app with `GestureHandlerRootView` solves the issue for you? It can be done like so:
```diff
+ import { gestureHandlerRootHOC } from 'react-native-gesture-handler';
...
- registerRootComponent(App);
+ registerRootComponent(gestureHandlerRootHOC(App));
```

**Comment by vbro1293** [comment]
I also seem to be having a similar issue - works fine on ios but not working on android, with the following packages
    "@react-navigation/native": "^6.0.8",
    "@react-navigation/native-stack": "^6.4.0",
    "@react-navigation/bottom-tabs": "^6.2.0",
    "react-native-gesture-handler": "^2.3.1",
    
Have attempted this but I just get a blank screen on launch. 
> Could you check if wrapping your app with `GestureHandlerRootView` solves the issue for you? It can be done like so:
> 
> ```diff
> + import { gestureHandlerRootHOC } from 'react-native-gesture-handler';
> ...
> - registerRootComponent(App);
> + registerRootComponent(gestureHandlerRootHOC(App));
> ```

The only way I have managed to get it working on Android is by wrapping my `Swipeable` component with `gestureHandlerRootHOC`

**Comment by aqmebrak** [comment]
This fixes it for me too, thank you very much !

So this was a misconfiguration between the libs handling navigation and the gesture lib. 

For anyone like me who wants to understand why, it is stated here: https://docs.swmansion.com/react-native-gesture-handler/docs/1.10.3/#with-wixreact-native-navigation

> If you are using a native navigation library like [wix/react-native-navigation](https://github.com/wix/react-native-navigation) you need to follow a different setup for your Android app to work properly. The reason is that both native navigation libraries and Gesture Handler library need to use their own special subclasses of ReactRootView.

**Comment by j-piasecki** [comment]
@vbro1293 This may be issue with styling. You can try using `GestureHandlerRootView` directly and styling it appropriately:
```jsx
import { GestureHandlerRootView } from 'react-native-gesture-handler';
...
<GestureHandlerRootView style={ /* style the root view so it covers the required area */ }>
  ...
</GestureHandlerRootView>
```

**Comment by kmagiera** [comment]
Happy to hear that suggestion resolved the issue. I though that when no root view is present we detect that and show some special error, is that not the case @j-piasecki ?

Also, I understand we can consider this issue resolved, so it should be safe to close it.
