### ISSUE TITLE
RCTBridge required dispatch_sync to load RNGestureHandlerModule. This may lead to deadlocks

### ISSUE THREAD

**Issue by harensarma** [software-mansion/react-native-gesture-handler#1864]
RCTBridge required dispatch_sync to load RNGestureHandlerModule. This may lead to deadlocks

**Comment by j-piasecki** [comment]
Hi! This seems to be the same issue as https://github.com/software-mansion/react-native-gesture-handler/issues/1770. I'll close this one to keep the discussion in one place.
