### ISSUE TITLE
`GestureDetector` sometimes doesn't trigger any gesture ended events with react-native-maps `MapView`

### ISSUE THREAD

**Issue by krtejeda** [software-mansion/react-native-gesture-handler#1868]
## Description

`GestureDetector` doesn't trigger any of gesture ended events when used with MapView from `react-native-maps`. I don't think this is a react-native-maps issue since the old API works fine. Maybe the gesture handlers from that component swallow these events somehow?

### Platforms

- [x] iOS
- [ ] Android
- [ ] Web

## Steps To Reproduce

1. Fling around map 

### Expected behavior

End event is always triggered when gesture ends

### Actual behavior

'end' event does not trigger sometimes.

## Snack or minimal code example

```
import * as React from 'react';
import { Text, View, StyleSheet, useWindowDimensions } from 'react-native';
import MapView from 'react-native-maps';
import { Gesture, GestureDetector } from 'react-native-gesture-handler';

export default function App() {
  const { width, height } = useWindowDimensions();

  const fingerOnScreen = Gesture.LongPress()
    .minDuration(0)
    .maxDistance(Math.max(width, height))
    .onStart(() => {
      console.log('start');
    })
    .onEnd(() => {
      console.log('end');
    });

  return (
    <GestureDetector gesture={gesture}>
      <MapView
        style={StyleSheet.absoluteFill}
        initialRegion={{
          latitude: 37.78825,
          longitude: -122.4324,
          latitudeDelta: 0.0922,
          longitudeDelta: 0.0421,
        }}></MapView>
    </GestureDetector>
  );
}
```

## Package versions

- React: 17.0.1
- React Native: 64.2
- React Native Gesture Handler: 2.2.0
- React Native Reanimated: 2.3.1
- react-native-maps: 0.30.1

**Comment by j-piasecki** [comment]
Hi! Unfortunately I haven't been able to reproduce this issue using the code you have provided. It may be due to some specific configuration or a misunderstanding on my part. Would you mind preparing a repository with a reproduction?

**Comment by krtejeda** [comment]
Hmm I can't anymore either. I'll close this and reopen a new one if I come across it again. Thanks!
