### ISSUE TITLE
Cannot use library on Android

### ISSUE THREAD

**Issue by timoisalive** [software-mansion/react-native-gesture-handler#1873]
## Description

Trying to make the library working in an Expo project on Android without success.

### Platforms

- [ ] iOS
- [x] Android
- [ ] Web

## Steps To Reproduce

1. Create a new blank Managed Expo project
2. Add a basic gesture handler
3. Log gesture events

### Expected behavior
Logs are printed in console.

### Actual behavior
No logs are seen on Android, whereas on iOS logs are printed as expected.

## Snack or minimal code example

```
// App.tsx

import { StyleSheet, View } from "react-native";
import {
  Gesture,
  GestureDetector,
  TapGestureHandler,
} from "react-native-gesture-handler";

export default function App() {
  return (
    <View style={styles.container}>
      <GestureDetector
        gesture={Gesture.Tap().onBegin(() => {
          console.log("GestureDetector onBegin");
        })}
      >
        <View style={styles.blue} />
      </GestureDetector>

      <TapGestureHandler
        onBegan={() => {
          console.log("TapGestureHandler onBegan");
        }}
      >
        <View style={styles.red} />
      </TapGestureHandler>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  blue: { width: 300, height: 300, backgroundColor: "blue" },
  red: { width: 300, height: 300, backgroundColor: "red" },
});
```

## Package versions

- Expo: ~44.0.0
- React: 17.0.1
- React Native: 0.64.3
- React Native Gesture Handler: ~2.1.0
- React Native Reanimated: I assume this is not necessary, but tried with ~2.3.1, no luck

**Comment by timoisalive** [comment]
Ok, found the problem, I hadn't wrapped the app in `GestureHandlerRootView`.

It might be a good idea to mention this wrapper in the "Get started" section of the documentation. It is now mentioned only in the "Introduction", among the library installation instructions.

Also, it is interesting that the library works without the `GestureHandlerRootView` on iOS. Maybe the library could print a warning when it is being used without the expected root view!

**Comment by fh-thudson** [comment]
Can I get an example of that import and how you wrapped that?  When I wrap the app in the GestureHandlerRootView the app doesn't even work.  

Everything works great on ios but android doesn't work at all.
