### ISSUE TITLE
NSInvalidArgumentException Crash

### ISSUE THREAD

**Issue by LeviWilliams** [software-mansion/react-native-gesture-handler#1883]
## Description
App is crashing from RNGestureHandlerEvents.m while using gesture detector 

### Platforms

- [ ] iOS

## Stacktrace
Hardware Model:     iPad7,5 (Also various other models of iPhone)
Role:               Foreground
OS Version:         iOS 15.3.1

NSInvalidArgumentExceptionRNGestureHandlerEvents.m:248
*** -[__NSDictionaryM setObject:forKey:]: object cannot be nil (key: target)

0  CoreFoundation          ___exceptionPreprocess
1  libobjc.A.dylib         _objc_exception_throw
2  CoreFoundation          __CFThrowFormattedException
3  CoreFoundation          -[__NSDictionaryM setObject:forKey:].cold.2
4  CoreFoundation          -[__NSDictionaryM setObject:forKey:]
5  app -[RNGestureHandlerStateChange arguments] (RNGestureHandlerEvents.m:248:5)
6  app -[RNGestureHandlerManager sendStateChangeDeviceEvent:] (RNGestureHandlerManager.m:217:34)
7  app -[RNGestureHandler sendStateChangeEvent:] (RNGestureHandler.m)
8  app -[RNGestureHandler sendEventsInState:forViewWithTag:withExtraData:] (RNGestureHandler.m:223:9)
9  app -[RNGestureHandler handleGesture:] (RNGestureHandler.m:194:5)
10 app -[RNBetterTapGestureRecognizer triggerAction] (RNTapHandler.m:64:3)
11 app -[RNBetterTapGestureRecognizer reset] (RNTapHandler.m:175:5)
12 UIKitCore               -[UIGestureRecognizer _resetGestureRecognizer]
13 UIKitCore               ____UIGestureEnvironmentUpdateGestureGraph_block_invoke_2
14 UIKitCore               __UIGestureEnvironmentUpdate
15 CoreFoundation          ___CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
16 CoreFoundation          ___CFRunLoopDoObservers
17 CoreFoundation          ___CFRunLoopRun
18 CoreFoundation          _CFRunLoopRunSpecific
19 GraphicsServices        _GSEventRunModal
20 UIKitCore               -[UIApplication _run]
21 UIKitCore               _UIApplicationMain
22 app main (main.m:14:12)

## Steps To Reproduce
Using gesture handler with tap/longpress as provided in gist, we're seeing this crash in production a good bit. 

## Snack or minimal code example

We have a straightforward gesture detector that handles tap and long presses:
https://gist.github.com/LeviWilliams/36034a8e9f76ae225336eaefb38f5ad0

## Package versions

- React: 17.0.2
- React Native: 0.66.4
- React Native Gesture Handler: 2.2.0
- React Native Reanimated: n/a

**Comment by LeviWilliams** [comment]
Gist provided, not missing info

**Comment by jakub-gonet** [comment]
I wasn't able to repro it using your gist, this is the code I was using:
```jsx
import React from 'react';
import {View} from 'react-native';
import {
  Gesture,
  GestureDetector,
  GestureHandlerRootView,
  State,
} from 'react-native-gesture-handler';

const CustomHandler = ({
  hitSlop,
  maxDist,
  onLongPress,
  onPressOut,
  onTap,
  onTapOut,
  children,
}) => {
  const longPressHandler = Gesture.LongPress()
    .hitSlop(hitSlop || {})
    .minDuration(100)
    .maxDistance(maxDist)
    .onStart(event => {
      if (event.state === State.ACTIVE) {
        onLongPress?.();
      }
    })
    .onEnd(event => {
      if (
        event.state === State.CANCELLED ||
        event.state === State.FAILED ||
        event.state === State.END ||
        event.state === State.UNDETERMINED
      ) {
        onPressOut?.();
      }
    });

  const tapHandler = Gesture.Tap()
    .maxDuration(100)
    .onStart(event => {
      if (event.state === State.ACTIVE) {
        onTap?.();
      }
    })
    .onEnd(event => {
      if (
        event.state === State.CANCELLED ||
        event.state === State.FAILED ||
        event.state === State.END ||
        event.state === State.UNDETERMINED
      ) {
        onTapOut?.();
      }
    });

  const composed = Gesture.Exclusive(longPressHandler, tapHandler);

  return <GestureDetector gesture={composed}>{children}</GestureDetector>;
};

function App() {
  return (
    <GestureHandlerRootView style={{flex: 1, backgroundColor: 'pink'}}>
      <CustomHandler>
        <View style={{backgroundColor: 'orange', width: 100, height: 100}} />
      </CustomHandler>
    </GestureHandlerRootView>
  );
}

export default App;
```

(`delayLongPress` was missing so I hardcoded `100` as a value)

https://user-images.githubusercontent.com/12465392/154977342-5ef54228-da8c-415a-ba53-fa82d36e62b4.mov

This is likely related to sending events via device events system while receiving views are unmounted - this code crashes:
```objc
- (NSArray *)arguments
{
    NSMutableDictionary *body = [NSMutableDictionary dictionaryWithDictionary:_extraData.data];
    [body setObject:_viewTag forKey:@"target"]; // here - RNGestureHandlerEvents.m:248:5
    [body setObject:_handlerTag forKey:@"handlerTag"];
    [body setObject:@(_state) forKey:@"state"];
    [body setObject:@(_prevState) forKey:@"oldState"];
    return @[self.viewTag, @"onGestureHandlerStateChange", body];
}
```

/cc @j-piasecki

**Comment by LeviWilliams** [comment]
Not sure what other info is helpful here, this is a new crash for us since we upgraded to the new api (>2.0). We're not doing anything inherently unique, we do have just a plain touchable that is being hidden/shown based off state so that would make sense based off your above comment.

**Comment by j-piasecki** [comment]
Unfortunately, I haven't been able to reproduce it either, but since the problem comes from `viewTag` of the target being `nil`, I believe we can just ignore them. This patch should fix the problem for now:
```diff
diff --git a/node_modules/react-native-gesture-handler/ios/RNGestureHandler.m b/node_modules/react-native-gesture-handler/ios/RNGestureHandler.m
index 32b4bc9..2014ec6 100644
--- a/node_modules/react-native-gesture-handler/ios/RNGestureHandler.m
+++ b/node_modules/react-native-gesture-handler/ios/RNGestureHandler.m
@@ -189,6 +189,10 @@ - (RNGestureHandlerEventExtraData *)eventExtraData:(UIGestureRecognizer *)recogn
 
 - (void)handleGesture:(UIGestureRecognizer *)recognizer
 {
+    if (recognizer.view.reactTag == nil) {
+        return;
+    }
+    
     _state = [self recognizerState];
     RNGestureHandlerEventExtraData *eventData = [self eventExtraData:recognizer];
     [self sendEventsInState:self.state forViewWithTag:recognizer.view.reactTag withExtraData:eventData];
diff --git a/node_modules/react-native-gesture-handler/ios/RNGestureHandlerPointerTracker.m b/node_modules/react-native-gesture-handler/ios/RNGestureHandlerPointerTracker.m
index 57f487f..5ab5b80 100644
--- a/node_modules/react-native-gesture-handler/ios/RNGestureHandlerPointerTracker.m
+++ b/node_modules/react-native-gesture-handler/ios/RNGestureHandlerPointerTracker.m
@@ -227,7 +227,7 @@ - (void)cancelPointers
 
 - (void)sendEvent
 {
-  if (!_gestureHandler.needsPointerData) {
+  if (!_gestureHandler.needsPointerData || _gestureHandler.recognizer.view.reactTag == nil) {
     return;
   }
   
```

Could you share some more info about the tap handler you mentioned?

**Comment by LeviWilliams** [comment]
I will throw that patch in and see if it resolves, thank you! 

My tap handler is just shown/hidden based on a prop which is set upstream after the tap handler is tapped. In practice, the handler is hidden almost immediately after being tapped.

```
{tapButtonShown ? (
      <TapGestureHandler
        onHandlerStateChange={onTap}
		>
          <View>
		...
          </View>
      </TapGestureHandler>
) : ...}
```
