### ISSUE TITLE
LongPressGestureHandler does not work on Chrome on mobile (Web)

### ISSUE THREAD

**Issue by AlexButeau** [software-mansion/react-native-gesture-handler#1890]
## Description

Working with `Expo` and `react-native-web`

I am using a library (`react-native-drax`) that uses `react-native-gesture-handler` to create a Drag and Drop system.
The draggable item is created thanks to a `LongPressGestureHandler`.  Everything works fine on android, ios, and on the web in most browsers, but not in Chrome on mobile (or in "responsive" mode when testing from a laptop).
The long press event does not seem to be recognised properly, and ends almost instantly, making it impossible to drag the item.

I know the `LongPressGestureHandler` extends `PressGestureHandler`, which itself extends a `DiscreteGestureHandler` on the web, so I thought the issue could be related to that, but:
1. from what I can see on this repo, a MR was merged in 2020 to fix any issue linked to this specificity on web
2. everything works fine in other browsers, and even on Chrome when not on mobile/in responsive mode.

I unfortunately lack the necessary experience to try and explore this any further, so any help would be greatly appreciated.

My current workaround is to replace the `LongPressGestureHandler` by a `PanGestureHandler`, but the pan gesture is sometimes not detected if the mouse movement is too quick and goes out of the animated view before the pan move is triggered.

### Platforms

- [ ] iOS
- [ ] Android
- [x] Web

### Screenshots
https://streamable.com/nv0dqc

## Steps To Reproduce

1. Use specifically in Chrome - mobile

## Snack or minimal code example

Note that this Snack actually works perfectly on most platforms, since the issue is very specific to one browser, and only on mobile. 
https://snack.expo.dev/@alexbuteau/longpresshandler-web

+ snippet of code from the `DraxView` component

```
<LongPressGestureHandler
			maxDist={Number.MAX_SAFE_INTEGER}
			shouldCancelWhenOutside={false}
			minDurationMs={0}
			onHandlerStateChange={onHandlerStateChange}
			onGestureEvent={
				onGestureEvent as any /* Workaround incorrect typings. */
			}
			enabled={draggable} /* true in this case */
		>
			<Animated.View
				{...props}
				style={combinedStyle}
				ref={setViewRefs}
				onLayout={onLayout}
				collapsable={false}
			>
				{renderedChildren}
			</Animated.View>
		</LongPressGestureHandler>
```

## Package versions

- React: 17.0.1
- React Native: 0.64.3
- React Native Gesture Handler: 2.1.1
- React Native Reanimated: 2.3.1
- expo: ~44.0.6
- react-native-drax: 0.9.3

**Comment by m-bert** [comment]
Hi @AlexButeau! Do you still experience this issue? Since [2.10.0](https://github.com/software-mansion/react-native-gesture-handler/releases/tag/2.10.0) new web implementation is enabled by default. This may solve the problem.
