### ISSUE TITLE
[2.3.0] testID's are being removed/replaced by handlerTag & handlerType

### ISSUE THREAD

**Issue by TheWirv** [software-mansion/react-native-gesture-handler#1914]
## Description
After upgrading from `2.2.0` to `2.3.0` I suddenly got broken jest tests because my snapshots didn't match anymore. Turns out that somehow the essential `testID` property is missing, and instead there are now the `handlerTag` and `handlerType` properties. Kind of perplexed by this news, and thinking, "maybe this is by design", I just updated the snapshot. But although it properly updated the snapshot, the test (understandably) failed because jest couldn't find the test IDs I mentioned in my tests.

### Platforms

- [X] iOS
- [X] Android
- [ ] Web

### Screenshots
![image](https://user-images.githubusercontent.com/4397989/156743819-e86e4560-863b-433a-90ef-64696448641d.png)

## Steps To Reproduce

1. Have `Touchable*`s in your project
2. Give them a testID
3. Upgrade from e.g. `2.2.0` to `2.3.0`

### Expected behavior
Test IDs remain and tests finish successfully.

### Actual behavior
Test IDs are missing and tests fail.

## Snack or minimal code example

I have created a reproducible example, based off of a fresh project via `npx react-native init`. Please have a look into the two most recent commits.

Here's the repo: https://github.com/TheWirv/rngh-testid-repro

## Package versions

- React: `17.0.2`
- React Native: `0.67.3`
- React Native Gesture Handler: `2.3.0`
- React Native Reanimated: `2.4.1`

**Comment by TheWirv** [comment]
> e

I have added a repro repo.

**Comment by j-piasecki** [comment]
Hi! This should be fixed by https://github.com/software-mansion/react-native-gesture-handler/pull/1910. Could you please check if updating to `react-native-gesture-handler` 2.3.1 solves the problem for you?

**Comment by TheWirv** [comment]
Fixed in #1910, thanks @virdesai!
