### ISSUE TITLE
react-native-gesture-handler does not work with react-native-macos anymore

### ISSUE THREAD

**Issue by hsjoberg** [software-mansion/react-native-gesture-handler#1927]
## Description

Hi!
This lib used to work with react-native-macos, but since 2.0.0 it's crashing because [it's trying to call a native module function (which doesn't exist for macos target)](https://github.com/software-mansion/react-native-gesture-handler/blob/9569b56f31aed5c9e0bafc6d193e7accf0414883/src/handlers/createHandler.ts#L91).

Reusing the web version seems to be working, what do you think about reusing it?
FY it's logging a lot of warnings, but looks like this is [intended behavior](https://github.com/software-mansion/react-native-gesture-handler/blob/9569b56f31aed5c9e0bafc6d193e7accf0414883/src/RNGestureHandlerModule.web.ts#L25-L30). I don't see them in react-native-web though.

### Platforms

- [x] macOS (react-native-macos)

## Steps To Reproduce

1. Create a react-native-macos project
2. Wrap `<GestureHandlerRootView>`
3. Run application and click somewhere

### Expected behavior

No error should be seen.

### Actual behavior

App is crashes on call to `handleSetJSResponder` because there is no native module for macOS target.

## Snack or minimal code example

```JSX
import React from "react";
import { AppRegistry } from "react-native";
import { GestureHandlerRootView } from "react-native-gesture-handler";
import { name as appName } from "./app.json";

function App() {
  return (
    <GestureHandlerRootView />
  );
};

AppRegistry.registerComponent(appName, () => App);
```

## Package versions

- React: 17.0.2 but shouldn't matter
- React Native: 0.67.3 but shouldn't matter
- React Native macOS: 0.66.31 but shouldn't matter
- React Native Gesture Handler: 2.3.1
- React Native Reanimated: 1.13.3 but shouldn't matter

**Comment by hsjoberg** [comment]
> The issue doesn't seem to contain a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example).

I've addressed this now.

**Comment by j-piasecki** [comment]
Hi! That's weird, because the function you mentioned has been there since the beginning ([here's version 1.0.0](https://github.com/software-mansion/react-native-gesture-handler/blob/0b987e4609839f08aed8ceff208230876309c936/createHandler.js#L50)).
I'm not sure I understand what you mean by 'reusing the web version', but since you managed to get it to work would you mind creating a repo with it?

**Comment by piaskowyk** [comment]
It looks inactive so I'm crossing 😔 Feel free to reopen.
