### ISSUE TITLE
I have an issue with RNGestureHandlerModule.attachGestureHandler was call 2 arguments but expects 3 arguments

### ISSUE THREAD

**Issue by phuongit0301** [software-mansion/react-native-gesture-handler#1935]
![Simulator Screen Shot - iPhone 13 - 2022-03-17 at 06 48 13](https://user-images.githubusercontent.com/3425152/158719248-58be5c1d-81fd-4e65-b8af-763e98394e81.png)

How can I fix it?

**Comment by j-piasecki** [comment]
Hi! This looks like an issue with cache. You can try clearing the Metro cache (`yarn start --reset-cache`), and if that doesn't help you could delete `node_modules` and install your dependencies again.

**Comment by mickykro** [comment]
I have the same issue on IOS device, on emulator i don't get this error.
