### ISSUE TITLE
[RESOLVED] Swipeable is not working 

### ISSUE THREAD

**Issue by IsaRodz** [software-mansion/react-native-gesture-handler#1943]
## Description
Using the `Swipeable` component from `react-native-gesture-handler` doesn't work  
I imported the component as it is shown in the documentation, wrap a `View` into the component but when trying to swipe it does nothing. Althoug I do can open the swipeable using a ref and calling its `open` method. Code in the below image and example code section.

### Platforms

- [ ] iOS (I don't have a device to test this in Iphone)
- [ x] Android
- [ ] Web

### Screenshots
![code](https://user-images.githubusercontent.com/54281481/159136849-cdb37fa8-0827-4e79-9965-5a5a05633063.png)

## Snack or minimal code example
Cant reproduce this on Snack since the Expo SDK version on Snack (43) is not compatible with the react-native-gesture-handler version (2.1.0). Older RNGH versions work fine. However you can try with the code below.
```
import Swipeable from 'react-native-gesture-handler/Swipeable';
// ...
function ListItem(item: { id: string | number }) {
  const swipeable = useRef<Swipeable>(null);
  return (
    <Swipeable
      ref={swipeable}
      onSwipeableOpen={() => {
        console.log('first');
      }}
      renderRightActions={() => {
        return (
          <View style={{ justifyContent: 'center', padding: 20 }}>
            <Feather name="trash-2" size={24} color="#ef5350" />
          </View>
        );
      }}
    >
      <Animated.View
        style={styles.item}
        // ...
        // onTouchEnd={() => swipeable.current?.openRight()}
      >
      </Animated.View>
    </Swipeable>
  );
}

```

## Package versions
"react": "17.0.1",
"react-native": "0.64.3",
"react-native-reanimated": "~2.3.1",
"react-native-gesture-handler": "~2.1.0",

- React:
- React Native:
- React Native Gesture Handler:
- React Native Reanimated:

**Comment by j-piasecki** [comment]
Hi! This looks like a missing `GestureHandlerRootView`, could you try wrapping your app with it to see it it solves the problem? Keep in mind that it behaves the same as `View` so it may need to be styled to display correctly.

**Comment by IsaRodz** [comment]
> Hi! This looks like a missing `GestureHandlerRootView`, could you try wrapping your app with it to see it it solves the problem? Keep in mind that it behaves the same as `View` so it may need to be styled to display correctly.

Yes, you were right... Reading the docs again I realized that this was after the installation. In older versions it wasn't so, I thing that's why I didn't wrap my app within the `GestureHandlerRootView`
