### ISSUE TITLE
App.js hung after upgrading to 2.3.0 with wrapping of <GestureHandlerRootView>{/* content */}</GestureHandlerRootView>;

### ISSUE THREAD

**Issue by emclab** [software-mansion/react-native-gesture-handler#1955]
## Description
Just upgraded from 1.2.x to 2.3.0 and adding wrapping `<GestureHandlerRootView>{/* content */}</GestureHandlerRootView>;` in App.js. The app won't start and hung with blank page. After removing the wrapping above, the app launches itself successfully. 

Here is the App.js:

```
 import React, {useState, useContext, Component} from 'react';
 import { GestureHandlerRootView } from 'react-native-gesture-handler';
 import { NavigationContainer } from '@react-navigation/native';
 import { createStackNavigator } from '@react-navigation/stack';
 import { SafeAreaProvider } from 'react-native-safe-area-context';
 import SplashScreen from './src/components/splashscreen/SplashScreen';
 import SysError from './src/components/app/SysError';
 import Verif1 from './src/components/signup/Verif1';
 import Signup from './src/components/signup/Signup';
 import AppScreen from "./src/components/app/AppScreen";
 
 const Stack = createStackNavigator();
 
 export default function App() {
   return (
    <GestureHandlerRootView >. //<<==page hung after wrapping. Removing it works fine.
     <SafeAreaProvider>
       <NavigationContainer>
         <Stack.Navigator InitialRouteName="AppSplash">
           <Stack.Screen name="AppSplash" component={SplashScreen} options={{headerShown:false}}/>
           <Stack.Screen name="AppSysError" component={SysError} options={{headerShown:false}} />
           <Stack.Screen name="AppScreen" component={AppScreen} options={{headerShown:false}} />
           <Stack.Screen name="AppVerif1" component={Verif1} options={{headerShown:false}} />
           <Stack.Screen name="AppSignup" component={Signup} options={{headerShown:false}} />
         </Stack.Navigator>
       </NavigationContainer>
     </SafeAreaProvider>
     </GestureHandlerRootView >
   );
 };
```

None of the screens above uses `react-native-gesture-handler`. The app is just rebuilt with some modules upgraded including RN gesture handler and reanimated.

### Platforms

It is Android 2021.1.1 patch 2 emulator running on Big Sur. 
- [ ] iOS
- [x ] Android
- [ ] Web

## Steps To Reproduce

1.

## Package versions

- React:17.0.2
- React Native: 0.67.4
- React Native Gesture Handler: 2.3.0
- React Native Reanimated: 2.5.0

**Comment by emclab** [comment]
It is a large app and it is hard to crate a meaningful snack. Code which causes error has been provided. Before wrapping in gesture handler, it has been wrapped in react-navigation 6.x. May there be a conflict between the 2 wrappers?

**Comment by j-piasecki** [comment]
Hi! Could you try adding `style={{ flex: 1 }}` to `GestureHandlerRootView`, i.e.: `<GestureHandlerRootView style={{ flex: 1 }}>`?

**Comment by Yudawardana94** [comment]
> Hi! Could you try adding `style={{ flex: 1 }}` to `GestureHandlerRootView`, i.e.: `<GestureHandlerRootView style={{ flex: 1 }}>`?

It works.
I have the same issue with `GestureHandlerRootView` after implementation it shows nothing.
after i try this it works like usual

**Comment by mohsn-mirzaei** [comment]
> Hi! Could you try adding `style={{ flex: 1 }}` to `GestureHandlerRootView`, i.e.: `<GestureHandlerRootView style={{ flex: 1 }}>
It worked, thank you :)
