### ISSUE TITLE
Type 'Timeout' is not assignable to type 'number'

### ISSUE THREAD

**Issue by hamidhadi** [software-mansion/react-native-gesture-handler#1958]
## Description
After upgrading to the latest version, all the `setTimeout`s and `SetInterval`s types are broken. 
It turned out that somehow `RN-Gesture-Handler` picks the `Node` types as default instead of the `RN` types.
Also, these are related to this issue:
- https://github.com/software-mansion/react-native-gesture-handler/pull/1420

- https://github.com/software-mansion/react-native-gesture-handler/issues/1384

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web

### Screenshots
<img width="533" alt="Screenshot 2022-03-28 at 11 55 41" src="https://user-images.githubusercontent.com/6258297/160373911-13ce47f0-5fe0-4aa3-ae93-4a2acdeffe5b.png">

## Steps To Reproduce

1. Clone the latest version
2. install `node_modules` for both root directory and the example project 
3. Add this snippet to the `App.tsx`
```ts
  const myTimer = React.useRef(0);

  React.useEffect(() => {
    myTimer.current = setTimeout(() => {
      console.log('Hello');
    }, 1000);
  }, []);
```
4. You will get this error:
```
Type 'Timeout' is not assignable to type 'number'
```
5. Go to root directory and open the `tsconfig.json`
6. Change the types value from `["node", "jest"]` to `[]`
7. The error will disappear 

### Expected behavior
It should respect RN types

### Actual behavior
It uses `node` types

## Package versions

- React: `17.0.2`
- React Native: `0.65.2`
- React Native Gesture Handler: `2.3.2`
- React Native Reanimated: `2.4.1`

**Comment by hamidhadi** [comment]
Hey @j-piasecki, 
I still have the same issue even after upgrading to `2.4.0` ☹️

**Comment by j-piasecki** [comment]
Hi @hamidhadi,
Are you sure it's because of Gesture Handler 😅 ? I'm asking because I just tried, and I got this error on a fresh RN 0.68 app without installing any additional libraries (it went away after I added `"types": []` to `tsconfig.json`), while it's fine in the Example app.

**Comment by hamidhadi** [comment]
Yes! I can confirm that this is now the case 🤔

**Comment by j-piasecki** [comment]
@hamidhadi Could you clarify what you mean? I'm not sure whether it's that you got the same result as I did (error on the fresh app) or that you're sure it's because of Gesture Handler.
