### ISSUE TITLE
Gradle sync failed: Plugin with id 'com.facebook.react' not found.

### ISSUE THREAD

**Issue by jeet-dhandha-lio** [software-mansion/react-native-gesture-handler#1977]
## ERROR:
-  Gradle sync failed: Plugin with id 'com.facebook.react' not found.
## PACKAGES:
"@notifee/react-native": "^4.0.1",
    "@react-native-async-storage/async-storage": "^1.15.13",
    "@react-native-community/checkbox": "^0.5.9",
    "@react-native-community/clipboard": "^1.5.1",
    "@react-native-community/datetimepicker": "^4.0.0",
    "@react-native-community/google-signin": "^5.0.0",
    "@react-native-community/netinfo": "6.0.0",
    "@react-native-community/slider": "^4.1.12",
    "@react-native-community/voice": "^1.1.9",
    "@react-native-firebase/analytics": "^13.0.1",
    "@react-native-firebase/app": "^13.0.1",
    "@react-native-firebase/auth": "^13.0.1",
    "@react-native-firebase/crashlytics": "^13.0.1",
    "@react-native-firebase/database": "^13.0.1",
    "@react-native-firebase/firestore": "^13.0.1",
    "@react-native-firebase/functions": "^13.0.1",
    "@react-native-firebase/messaging": "^13.0.1",
    "@react-native-firebase/perf": "^13.0.1",
    "@react-native-firebase/remote-config": "^13.0.1",
    "@react-native-firebase/storage": "^13.0.1",
    "@react-native-picker/picker": "^2.2.1",
    "@react-navigation/drawer": "5.7.0",
    "@react-navigation/native": "5.7.0",
    "@react-navigation/stack": "5.7.0",
    "@sentry/react-native": "^3.2.3",
    "add": "^2.0.6",
    "clevertap-react-native": "^0.6.0",
    "expo-image-manipulator": "^8.4.0",
    "expo-local-authentication": "^11.1.1",
    "exponential-backoff": "^3.1.0",
    "lodash": "^4.17.21",
    "lottie-ios": "3.2.3",
    "lottie-react-native": "4.0.3",
    "mathjs": "^10.0.0",
    "moment": "^2.29.1",
    "prop-types": "15.7.2",
    "rb-redux": "0.0.2",
    "react": "17.0.2",
    "react-native": "^0.68.0-rc.1",
    "react-native-animatable": "^1.3.3",
    "react-native-audio-recorder-player": "^3.2.1",
    "react-native-branch": "^5.2.1",
    "react-native-camera": "^4.2.1",
    "react-native-carrier-info": "^1.1.2",
    "react-native-code-push": "^7.0.1",
    "react-native-contacts": "^7.0.2",
    "react-native-country-picker-modal": "^2.0.0",
    "react-native-default-preference": "^1.4.3",
    "react-native-device-info": "^8.4.8",
    "react-native-document-picker": "^7.1.1",
    "react-native-dotenv": "^3.2.0",
    "react-native-draggable-flatlist": "^2.6.2",
    "react-native-fast-image": "^8.5.11",
    "react-native-fbsdk": "^2.0.0",
    "react-native-fs": "^2.18.0",
    "react-native-gesture-handler": "^2.3.0",
    "react-native-get-location": "^2.1.2",
    "react-native-google-places-autocomplete": "^2.4.1",
    "react-native-image-crop-picker": "^0.37.2",
    "react-native-image-marker": "^0.6.3",
    "react-native-image-viewing": "^0.2.1",
    "react-native-maps": "^0.29.4",
    "react-native-modal": "^13.0.0",
    "react-native-permissions": "^3.1.0",
    "react-native-picker-select": "^8.0.4",
    "react-native-reanimated": "^2.3.0",
    "react-native-safe-area-context": "3.3.2",
    "react-native-safe-area-view": "1.1.1",
    "react-native-screens": "2.9.0",
    "react-native-share": "^7.3.0",
    "react-native-simple-toast": "^1.1.3",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-unimodules": "^0.13.3",
    "react-native-ux-cam": "^5.3.4",
    "react-native-vector-icons": "9.0.0",
    "react-native-view-pdf": "^0.12.2",
    "react-native-webview": "^11.14.4",
    "react-redux": "^7.2.6",
    "redux": "^4.1.2",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.4.1",
    "shorthash": "^0.0.2",
    "surveysparrow-react-native-sdk": "^0.1.1",
    "values.js": "^2.0.0",
    "xlsx": "^0.17.4"

**Comment by jeet-dhandha-lio** [comment]
i am trying to open my project with new architechture enabled but this issue keep persist in "react-native-gesture-handler" in "build.gradle" file.

**Comment by j-piasecki** [comment]
Hi! It looks like you are missing the React Gradle Plugin, make sure you've followed all the steps for enabling the new architecture in your app - https://reactnative.dev/docs/next/new-architecture-app-intro.

**Comment by jeet-dhandha-lio** [comment]
Yes probably thats the main cause of this issue.

**Comment by j-piasecki** [comment]
Did installing the plugin solve the problem?

**Comment by meycon1** [comment]
Any?

**Comment by MLawlz** [comment]
Facing the same issue as @anuragkumarjsk in V0.70.2

**Comment by j-piasecki** [comment]
Could you prepare a repository that would allow us to reproduce the error? Without it, it's really hard to say what's happening here.

**Comment by N3TC4T** [comment]
You probably forgot to include this line 

```classpath("com.facebook.react:react-native-gradle-plugin")``` in `android/build.gradle` file in `dependencies` section

https://github.com/facebook/react-native/blob/main/template/android/build.gradle#L19

**Comment by yogeshepam** [comment]
@N3TC4T but opting for classpath("com.facebook.react:react-native-gradle-plugin") is optional. How to resolve it without this classpath?

**Comment by jet2018** [comment]
@yogeshepam for my case, I already have it but it still throws this error

**Comment by Malik-Usman17** [comment]
From yesterday i am also getting this error, searching everywhere but yet can't find any solution.

**Comment by Bright11** [comment]
Sometimes, network issues can also cause this
