### ISSUE TITLE
NativeViewGestureHandler docs 

### ISSUE THREAD

**Issue by KakarN** [software-mansion/react-native-gesture-handler#198]
I have watched [the presentation ("React Native Touch & Gesture - Krzysztof Magiera")](https://youtu.be/V8maYc4R2G0?t=13m45s) that is recommended in the Getting started page. On the presentation, there's a section on how to [build a UI like the IOS Maps app](https://youtu.be/V8maYc4R2G0?t=13m45s). When dragging/scrolling from the bottom to top, it scrolls/drags. And after it reached the top, it continues scrolling. And vice versa on scrolling down.

It is suggested that it can be done using ScrollView by adding an empty transparent cell as the first element on the ScrollView. I have tried implementing the same which can be found in this [snack](https://snack.expo.io/@kakarn/scrollview---handler). In my case, instead of Maps, I am using a ScrollView.

But the problem is the first element (transparent element) does not allow to interact with the First ScrollView elements. I have tried with `pointerEvents` inside the first transparent view and even in its parent ScrollView. But this does not help.

I am actually trying to build UI like the "Apple Music App in android" ([youtube link](https://www.youtube.com/watch?v=3KaK_6WCIm0)). You can also check out the tried [snack link](https://snack.expo.io/@kakarn/apple-music_ui) for this. I cannot figure out how to utilize react-native-gesture-handler to implement this UI. Could you give me some pointers on how to achieve this?

**Comment by osdnk** [comment]
Hi, @KakarN 
Thank for using this library.
I understand yours problem and am conscious that it seems to be more complex problem. Maybe you'd like to take o look on  [bottom sheet](https://github.com/kmagiera/react-native-gesture-handler/blob/master/Example/bottomSheet/index.js) as I suppose it's exactly what you're looking for

**Comment by KakarN** [comment]
@osdnk Yes, I think this example is appropriate for my use case. Thank you! I will test it further and inform you. Also, could you please update the docs on how to use **NativeViewGestureHandler**, especially this section on [Using native components](https://kmagiera.github.io/react-native-gesture-handler/docs/about-handlers.html#using-native-components), also the link to NativeViewGestureHandler is broken. Because at first it was a bit confusing for me as to how to use this with native components. At first, I thought I need to use the native components (eg. ScrollView) from the react-native-gesture-handler library, but in some of the examples, it's just using the Animated components (eg. Animated.ScrollView) by wrapping inside the NativeViewGestureHandler. And further researching, I found some of the properties of NativeViewGestureHandler, i.e. `shouldActivateOnStart` and `disallowInterruption`, which are not documented on the website.

**Comment by osdnk** [comment]
@KakarN 
Thank your for this suggestion and you're absolutely right

**Comment by kulikalov** [comment]
The link is still broken btw: https://docs.swmansion.com/react-native-gesture-handler/docs/handler-native.md
