### ISSUE TITLE
项目升级后react-native-gesture-handler报invariant找不到，这怎么解决啊

### ISSUE THREAD

**Issue by r-j-q** [software-mansion/react-native-gesture-handler#1998]
### Discussed in https://github.com/software-mansion/react-native-gesture-handler/discussions/1997

<div type='discussions-op-text'>

<sup>Originally posted by **r-j-q** April 12, 2022</sup>
![image](https://user-images.githubusercontent.com/38770972/162865639-45c68a1e-27ca-400b-8098-1bb23056bc94.png)
</div>

**Comment by j-piasecki** [comment]
Hi! That's weird since `invariant` is listed as a dependency of Gesture Handler. Could you try deleting the `node_modules` and installing it again? If that doesn't help, you can try installing it manually: `yarn add invariant` or `npm install invariant`.
