### ISSUE TITLE
Memoryleak when using the Gesture object

### ISSUE THREAD

**Issue by matis-dk** [software-mansion/react-native-gesture-handler#2000]
## Description

There seems to be a memory leak when using the `Gesture` object with the `GestureDetector`, from the react-native-gesture-handler package.

This is happening for all the different `GestureObjects` (LongPress, ForceTouch, etc.), and as soon as I attach one or multiple `on` listeners (onBegin, onStart, etc.).

Is there any way, I can detach/remove a listener, when the component unmount?

### Platforms
-  iOS

### Screenshots
https://user-images.githubusercontent.com/32526593/162952109-13bfb87d-8204-4d2f-8bb4-b3cdace506ee.MP4

## Steps To Reproduce
Press the "Toggle" button a few time.

### Expected behavior
Memory consumption is steady.

### Actual behavior
Memory is building up.

## Snack or minimal code example

```
import * as React from "react";
import { Button, View, ScrollView } from "react-native";
import { Gesture, GestureDetector } from "react-native-gesture-handler";

export const Playground = () => {
  const [show, setShow] = React.useState(true);

  return (
    <ScrollView contentContainerStyle={{ paddingTop: 50 }}>
        <Button title={"Toggle"} onPress={() => setShow(!show)} />
        {show &&
          Array(100)
            .fill(true)
            .map((v, index) => <GestureBox key={index} />)}
      </ScrollView>
  );
};

function GestureBox() {
  const gesture = Gesture.LongPress().onBegin(() => {});
  return (
    <GestureDetector gesture={gesture}>
      <View
        style={[
          {
            padding: 10,
            marginHorizontal: 10,
            marginTop: 10,
            height: 50,
            backgroundColor: "skyblue",
          },
        ]}
      />
    </GestureDetector>
  );
}
```

## Package versions

- expo: 44
- react: 17.0.1
- react-native: 0.64.3
- react-native-gesture-handler: 2.3.2
- react-native-reanimated: 2.3.1

**Comment by hirbod** [comment]
I can confirm this issue. I am using GestureDetector inside my FlatList Items, and once used, memory gets never released. Overall View Counter also continues to rise and is not releasing. When I remove GestureDetector and wrap my Item with TouchableNoFeedback, things work fine

**Comment by hirbod** [comment]
Alright, I can confirm that switching to `runOnJS` fixes this issue, since its not workletized anymore. This is fine for me, since I was calling runOnJS anyway. 

Is there any news about this issue?

**Comment by gkpo** [comment]
I seem to be experiencing the same issue. Is there any news about this ? @hirbod what do you mean by switching to `runOnJS` ? do you wrap all the calls into `runOnJS` functions ? would you mind adding an example ?
Also my project is using v2.2.1, has this been addressed in a newer release ?
Thanks!

**Comment by j-piasecki** [comment]
@gkpo The fix for this problem is included in v2.5.0. As for the `runOnJS`, it's also the name of the modifier on gesture builders, which makes all callbacks run on the JS thread even if Reanimated is available (added in v2.3.0), you can use it like so:

```js
const gesture = Gesture.Tap()
  .runOnJS(true)
  .onStart(() => {
    console.log(_WORKLET);
  });
```

**Comment by alexstanbury** [comment]
I'm still seeing this issue using 2.6.0, resolved by using runOnJS.

"react-native": "^0.70.6",
"react-native-reanimated": "^2.12.0",
  "react-native-gesture-handler": "^2.6.0",

**Comment by tj-mc** [comment]
Already using hermes in our case unforunately. Been profiling production builds and screens that use RNGH retain at least 5mb memory each render.

**Comment by alexstanbury** [comment]
This is probably caused by using reanimated 2.x in your project, that has been the cause of huge memory problems for us. They have supposedly fixed them in version 3 and apparently it is backwards compatible so you may want to try upgrading to V3 and see if that helps.

**Comment by aLemonFox** [comment]
Any new solutions that don't depend on disabling reanimated? I am on Expo SDK48 which seems to have this issue when using gesture-handler and reanimated.

**Comment by tj-mc** [comment]
@aLemonFox In our case we found that `runOnJS` for all gestures did not have a noticeable impact for the user on the gesture performance, but it cut our memory usage in half. Good chance that upgrade RN + RNGH would fix this, but we can't right now.
