### ISSUE TITLE
LongPress iOS is disabling touch in other elements while pressing

### ISSUE THREAD

**Issue by joaolnpr** [software-mansion/react-native-gesture-handler#2002]
## Description

Hello,
I am facing one issue when comparing iOS/Android platforms which I would like to confirm:
Using the latest version available (v2.3. 2)

**Android** - While pressing a button to recording (long press event from GesturesDetector), I am able to touch in other elements (e.g Zoom Camera, Turn on/off flash) - Expected result

**iOS** - While pressing a button to recording, I am not able to touch in any other element while the long press event is active.

From what I can see, in iOS, when LongPress the other elements are having the touch events disabled which is not expected, since what I would like to achieve is to be able to record video using long press and zoom/turn on/off torch etc.

Any reason for this? or its a iOS limitation? Any solution?

Thanks in advance

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web

## Steps To Reproduce
Not required 

### Expected behavior
We should not block the other elements touches while LongPress event

### Actual behavior
When long press event active the other elements are having touches disabled

## Snack or minimal code example
Not required 

## Package versions

- React: 18.0.0-beta-24dd07bd2-20211208
- React Native: 0.63.4
- React Native Gesture Handler: 2.3.2
- React Native Reanimated: 2.3.1

**Comment by j-piasecki** [comment]
Hi! This issue seems to be very similar to https://github.com/software-mansion/react-native-gesture-handler/issues/2004, could you explain the difference between them in more detail? A snipped to show what's wrong would be perfect.

**Comment by j-piasecki** [comment]
It this is still relevant, please write a comment, otherwise the issue will close automatically.
