### ISSUE TITLE
TouchOpacity not touchable when other gesture is active and getting error in log - iOS

### ISSUE THREAD

**Issue by joaolnpr** [software-mansion/react-native-gesture-handler#2004]
## Description
 Using Gesture with LongPress and also TouchOpacity elements when Gesture LongPress is active, the TouchOpacity elements are not touchable, nothing happens in iOS (error bellow).  Everything works fine in Android, not in iOS.

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web

### Screenshots
Error XCode:
**"Gesture: Failed to receive system gesture state notification before next touch"**
![image](https://user-images.githubusercontent.com/48879345/163120698-26c211f7-e4fb-4e9a-9cc4-331cfc9f6cfe.png)

## Steps To Reproduce

1. GestureDetector with LongPress event active
2. TouchOpacity with OnPressIn event

### Expected behavior

When using GestorDetector for LongPress the other Touch elements should be touchable.
This works fine in Android, in iOS is getting error (check screenshot)

### Actual behavior
When LongPress is active and a Touch happens in any other Touch element, nothing happens and a error shows in XCODE

## Snack or minimal code example
```

<TouchableOpacity
              style={positionButtonStyle}
              onPressIn={() => {
                setCameraPosition((value?: string) =>
                  value === BACK_CAMERA ? FRONT_CAMERA : BACK_CAMERA,
                );
              }}>
              <CameraIcon color={cameraPositionIconColor} />
            </TouchableOpacity>

<GestureDetector
      disabled={disabled}
      gesture={pressType === 'LONG' ? gestureLongPress : gestureShortPress}>
      </GestureDetector>

 const gestureLongPress = Gesture.LongPress()
    .maxDistance(10)
    .shouldCancelWhenOutside(false)
```

## Package versions

- React: 18.0.0-beta-24dd07bd2-20211208
- React Native: 0.63.4
- React Native Gesture Handler: 2.3.2
- React Native Reanimated: 2.3.1

**Comment by johnylawrence1987** [comment]
Facing similar issue

**Comment by j-piasecki** [comment]
Hi! I looked into it and while I don't have a quick fix for this (it's enforced by iOS, native component responsible for `TouchableOpacity` doesn't receive any events when `LongPress` is active), I've noticed that double tapping `TouchableOpacity` seems to produce the desired behavior.

**Comment by joaolnpr** [comment]
@j-piasecki thanks for the feedback. 
humm.. I guess double tapping wont work for us, does the long press disables other Touch/Press events in other components? I was thinking to replace `TouchOpacity` by `Pressable`?

**Comment by j-piasecki** [comment]
Unfortunately, I don't think it will work. `Pressable` uses RN's Gesture Responder System and Gesture Handler doesn't integrate with it well. You could use `Tap` gesture to detect presses on your other components but this way you would have to implement visual feedback as well (if it's required).

**Comment by joaolnpr** [comment]
@j-piasecki I see... I guess I will check the Tap gesture and go from there, thanks for the inputs.

Do you think this is something which can be solve in a near future?

**Comment by j-piasecki** [comment]
I don't know at the moment, I'll need to look more into this to figure out why exactly it happens.

**Comment by quyle1222** [comment]
Android also has the same problem, maybe because this library is not compatible with version 0.68.0, hope everything will be resolved soon.

**Comment by quyle1222** [comment]
TapGestureHandler not working

**Comment by j-piasecki** [comment]
@quyle1222 Hi! We tested it on RN 0.68.0 and we didn't find any problems. Make sure you have [`GestureHandlerRootView`](https://docs.swmansion.com/react-native-gesture-handler/docs/installation#js) somewhere in the view hierarchy. If that doesn't help, could you prepare a repository with a reproduction and open a new issue, as it seems to be a different problem?

**Comment by j-piasecki** [comment]
@joaolnpr Could you check if adding `extraButtonProps={{ exclusive: false }}` to the `TouchableOpacity` fixes the problem for you? I've noticed that while the default value on iOS for that is `false`, Gesture Handler sets it to `true` by default. For me it looks like it's working correctly after changing it.

**Comment by j-piasecki** [comment]
Hi! If this issue is still affecting you after adding `extraButtonProps={{ exclusive: false }}`, could you write a comment explaining what's wrong? Otherwise the issue will be closed automatically.
