### ISSUE TITLE
ERROR: Unknown host CPU architecture: arm64

### ISSUE THREAD

**Issue by maximzhemerenko** [software-mansion/react-native-gesture-handler#2013]
## Description

When I build Android app (react native 0.68.1) using arm based MacBook Pro M1, I receive 'Unknown host CPU architecture: arm64' error. This happens because library uses default ndkVersion, but not custom ndkVersion from 'ext'. I propose include this line in the build.gradle file to use globally specified ndkVersion if exists.

I created merge request #2012

### Platforms

- [ ] iOS
- [^] Android
- [ ] Web

**Comment by j-piasecki** [comment]
I'll close this since https://github.com/software-mansion/react-native-gesture-handler/pull/2012 is merged.
