### ISSUE TITLE
missing dev dependencies with latest version

### ISSUE THREAD

**Issue by ethanneff** [software-mansion/react-native-gesture-handler#2027]
## Description

When updating from `"react-native-gesture-handler": "2.3.2",` to `"react-native-gesture-handler": "2.4.1",`, I ran into errors running iOS, Android and Jest.

I solved these errors by install the following dependencies.

```
    "@babel/plugin-proposal-nullish-coalescing-operator": "7.16.7",
    "@babel/plugin-proposal-optional-chaining": "7.16.7",
    "@babel/plugin-transform-arrow-functions": "7.16.7",
    "@babel/plugin-transform-shorthand-properties": "7.16.7",
    "@babel/plugin-transform-template-literals": "7.16.7",
```

### Platforms

- [x] iOS
- [x] Android
- [ ] Web

## Steps To Reproduce

1. `create-react-native-app my-project`
2. install `react-native-gesture-handler`
3. run iOS or Android
4. get error
5. install dev dependencies
6. error goes away

### Expected behavior

Not needing to install additional dependencies.

### Actual behavior

Had to install additional dependencies.

## Package versions

- React: "react": "17.0.2",
- React Native: "react-native": "0.67.4",
- React Native Gesture Handler:  "react-native-gesture-handler": "2.4.1",
- React Native Reanimated:  "react-native-reanimated": "2.8.0",

**Comment by j-piasecki** [comment]
Hi! That's strange, I've followed the steps you provided but I didn't get any errors. If you have a project where you tested them, could you publish it to GitHub so I can look into it?

**Comment by NathanNovak** [comment]
> Hi! That's strange, I've followed the steps you provided but I didn't get any errors. If you have a project where you tested them, could you publish it to GitHub so I can look into it?

I ran into the same issue and kept going down the board of missing babel modules.

**Comment by j-piasecki** [comment]
@NathanNovak In that case could you prepare a repository with a reproduction, or list the steps that I could follow? As I mentioned before, I was unable to reproduce it using the steps listed in the issue.

**Comment by bulkinav** [comment]
Today I updated the gesture-handler to v2.11.0 and also faced with this problem. But I note that there was no such problem on the version 2.9.0.

**Comment by oherst** [comment]
I've also just stumbled across this issue, presumably because of this?
https://github.com/facebook/metro/commit/322dea8dc700de70aea92cf37614d5fc50e09c6b

**Comment by Manikanta-GEP** [comment]
Any solution for this
