### ISSUE TITLE
[DrawerLayout] Android bug with native stack navigator

### ISSUE THREAD

**Issue by TommysG** [software-mansion/react-native-gesture-handler#2048]
## Description
Problem when i use @react-navigation/native-stack and react-native-gesture-handler's DrawerLayout on Android. I cannot open the Drawer from the edge of the position property and i cannot slide on it, to move it. Clicking on the backdrop (for closing drawer) doesn't work either.

### Platforms

- [ ] iOS
- [x] Android
- [ ] Web

## Steps To Reproduce

1. Create a native stack navigator
2. Put a screen with a DrawerLayout component
3. Try to slide the Drawer (open/close) or click the backdrop to close it.

### Expected behavior
Open navigator from the edge of the screen. Close navigator on slide or when you click on backdrop.

### Actual behavior
It doesn't respond to any gesture. 

## Package versions

- React: 17.0.2
- React Native: 0.67.2 
- React Native Gesture Handler: 2.1.1
- React Native Reanimated: 2.4.1

**Comment by j-piasecki** [comment]
Hi! Have you [wrapped your app with `GestureHandlerRootView`](https://docs.swmansion.com/react-native-gesture-handler/docs/installation#js)? Contrary to `@react-navigation/stack`, `@react-navigation/native-stack` doesn't rely on Gesture Handler, so you need to add it yourself.

**Comment by TommysG** [comment]
Yes thank you. It solved my problem.

**Comment by j-piasecki** [comment]
Great!
