### ISSUE TITLE
cannot pass useGestureHandlerRef  to Gesture.Simultaneous undefined is not a function

### ISSUE THREAD

**Issue by haibert** [software-mansion/react-native-gesture-handler#2052]
## Description
Before the recent API updates passing the ref of a useGestureHandlerRef to simultaneousHandlers worked. In 2.4 the app crashes with a undefined is not a function

## USED TO WORK
``` javascript 
import { useGestureHandlerRef } from '@react-navigation/stack'

const MyComponent = () => {

const cardGestureHandlerRef = useGestureHandlerRef()

    return (
      <PanGestureHandler
         simultaneousHandlers={cardGestureHandlerRef}  //< --- this used to work
         >
...
```
## DOESNT WORK 
``` javascript 
import { useGestureHandlerRef } from '@react-navigation/stack'

const MyComponent = () => {

const cardGestureHandlerRef = useGestureHandlerRef()

    const gesture = Gesture.Pan()

    const simultaneousHandlers = Gesture.Simultaneous(
        gesture,
        cardGestureHandlerRef  //<--- this crashes the app 
    )

    return (
        <GestureDetector gesture={simultaneousHandlers}>

...
``` 

### Platforms

- [ X] iOS
- [ ] Android
- [ ] Web

### Screenshots
![IMG_C39359656A04-1](https://user-images.githubusercontent.com/31780749/168450699-5488d01c-1451-4595-a369-80b5e85141d5.jpeg)

 
## Steps To Reproduce
https://gist.github.com/haibert/c99861f8c02e7e0b701c83ff2b2317ff

### Expected behavior
I want to pass the gestures to the navigation card using the simultaneous gesture handing 

### Actual behavior
the app crashes with a undefined is not a function 

## Snack or minimal code example
https://gist.github.com/haibert/c99861f8c02e7e0b701c83ff2b2317ff

## Package versions
        "react-native-gesture-handler": "2.4",
        "@react-navigation/stack": "^6.2.1",
        "react-native-reanimated": "~2.8.0",

<!--
Fill in your Gesture Handler and React Native versions below.
        "@react-navigation/stack": "^6.2.1",
        "react-native": "0.68.2",

**Comment by j-piasecki** [comment]
Hi! Gesture composition API works only with the gesture objects and `react-navigation` uses the old API. You can still accomplish this by using `simultaneousWithExternalGesture` method (in this case on `gesture`) and passing the ref as an argument to it.

**Comment by haibert** [comment]
@j-piasecki AHH.. thank you! And how would I wait for the ref of my const gesture = Pan()


``` javascript
  <NativeViewGestureHandler
                        waitFor={panGestureHandlerRef} // <--- I want to wait for the ref of my const gesture = Gesture.Pan()
                    >
```

**Comment by j-piasecki** [comment]
@haibert You can use `.withRef(panGestureHandlerRef)` method on your pan gesture.

**Comment by haibert** [comment]
@j-piasecki and lastly, is it possible to do this with the new API?  I am trying to change the activeOffsetX & etc on the fly. With thew new API I tried to set the activeOffsetX and failOffsetX through a shared value but I don't think its actually taking effect


## USED TO WORK
``` javascript 

panGestureHandlerRef.current?.setNativeProps({
            activeOffsetX: [-999, 0.1],
            failOffsetX: [-0.1, 999],
        })
        
```

## I DONT THINK THIS WORKS ? 
``` javascript 

    const activeOffsetX = useSharedValue([])
    const failOffsetX = useSharedValue([])

    const lockScrollable = () => {
           activeOffsetX.value = [-999, 0.1]
           failOffsetX.value = [-0.1, 999]
    }

    const gesture = Gesture.Pan()
        .activeOffsetX(activeOffsetX.value)
        .failOffsetX(failOffsetX.value)
        .withRef(panGestureHandlerRef)
        .simultaneousWithExternalGesture(cardGestureHandlerRef)

**Comment by j-piasecki** [comment]
@haibert Unfortunately, that's not possible at the moment. I know it's not an ideal replacement, but you could use state instead of shared value to accomplish a similar effect.

**Comment by haibert** [comment]
@j-piasecki ahhh got it. Do you think it's something that will be added in the future possibly or not sure? 

Btw I really appreciate the quick guidance you gave. Maybe the documentation should have a how to upgrade guide it's kind of confusing how everything changed.

**Comment by j-piasecki** [comment]
@haibert It's hard to tell at the moment, as we would have to implement the entire mechanism from scratch. You can, since you're already using Reanimated, use the touch events and the state manager to accomplish something similar, although with more work. [Here's](https://docs.swmansion.com/react-native-gesture-handler/docs/manual-gestures/manual-gestures) a simple example of them. You can track all pointers separately and control the state of the gesture manually.

As for the upgrade guide, it may be a good idea. I'll talk with the team about what it may look like.

**Comment by j-piasecki** [comment]
The migration guide covering the most important changes is here: https://docs.swmansion.com/react-native-gesture-handler/docs/guides/upgrading-to-2 🎉 .
