### ISSUE TITLE
`onChange` callback is not automatically workletized when `onBegin` is also specified.

### ISSUE THREAD

**Issue by elliotwaite** [software-mansion/react-native-gesture-handler#2067]
## Description

The `onChange` callback is not automatically workletized when `onBegin` is also specified. If the `'worklet'` directive is not added to the `onChange` callback, a warning is raised.

I think adding the `onBegin` callback changes whether `gesture` or `animatedGesture` is used, because removing it while the app is running causes this error: "Render Error: You cannot change whether you are using gesture or animatedGesture while the app is running."

### Platforms

- [x] iOS
- [x] Android
- [ ] Web

### Screenshots

Here's an animated GIF of it (you might have to press the play button in the top right to watch it):

<img src="https://user-images.githubusercontent.com/1767836/169362328-641f7596-95ce-4bfe-93f4-a805261d9605.gif" width="320" />

## Steps To Reproduce

1. Run the code below.
2. Drag on the different boxes.

### Expected behavior

For the `onChange` callback to always be automatically workletized.

### Actual behavior

For the `onChange` callback is not automatically workletized when an `onBegin` callback is also specified.

## Snack or minimal code example

```
import { StyleSheet, Text } from 'react-native'
import {
  Gesture,
  GestureDetector,
  GestureHandlerRootView,
} from 'react-native-gesture-handler'
import Animated from 'react-native-reanimated'

export default function App() {
  const gesture1 = Gesture.Pan().onChange(() => {})

  const gesture2 = Gesture.Pan().onChange(() => {
    'worklet'
  })

  const gesture3 = Gesture.Pan()
    .onBegin(() => {})
    .onChange(() => {})

  const gesture4 = Gesture.Pan()
    .onBegin(() => {})
    .onChange(() => {
      'worklet'
    })

  return (
    <GestureHandlerRootView style={styles.container}>
      <GestureDetector gesture={gesture1}>
        <Animated.View style={styles.box}>
          <Text style={styles.text}>{'const gesture1 = Gesture.Pan()'}</Text>
          <Text style={styles.text}>{'  .onChange(() => {'}</Text>
          <Text style={styles.text}>{'  })'}</Text>
        </Animated.View>
      </GestureDetector>

      <GestureDetector gesture={gesture2}>
        <Animated.View style={styles.box}>
          <Text style={styles.text}>{'const gesture2 = Gesture.Pan()'}</Text>
          <Text style={styles.text}>{'  .onChange(() => {'}</Text>
          <Text style={styles.text}>{"    'worklet'"}</Text>
          <Text style={styles.text}>{'  })'}</Text>
        </Animated.View>
      </GestureDetector>

      <GestureDetector gesture={gesture3}>
        <Animated.View style={styles.box}>
          <Text style={styles.text}>{'const gesture3 = Gesture.Pan()'}</Text>
          <Text style={styles.text}>{'  .onBegin(() => {'}</Text>
          <Text style={styles.text}>{'  })'}</Text>
          <Text style={styles.text}>{'  .onChange(() => {'}</Text>
          <Text style={styles.text}>{'  })'}</Text>
        </Animated.View>
      </GestureDetector>

      <GestureDetector gesture={gesture4}>
        <Animated.View style={styles.box}>
          <Text style={styles.text}>{'const gesture4 = Gesture.Pan()'}</Text>
          <Text style={styles.text}>{'  .onBegin(() => {'}</Text>
          <Text style={styles.text}>{'  })'}</Text>
          <Text style={styles.text}>{'  .onChange(() => {'}</Text>
          <Text style={styles.text}>{"    'worklet'"}</Text>
          <Text style={styles.text}>{'  })'}</Text>
        </Animated.View>
      </GestureDetector>
    </GestureHandlerRootView>
  )
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
  },
  box: {
    padding: 16,
    marginTop: 16,
    marginLeft: 16,
    marginRight: 16,
    alignSelf: 'stretch',
    backgroundColor: '#0ee',
  },
  text: {
    paddingBottom: 8,
    fontSize: 16,
    fontFamily: 'monospace',
  },
})
```

## Package versions

- React: 17.0.1
- React Native: 0.64.3
- React Native Gesture Handler: 2.2.1
- React Native Reanimated: 2.3.3

**Comment by j-piasecki** [comment]
That would be because of the Reanimated version you are using. `onChange` callback is automatically workletized since [version 2.4.0](https://github.com/software-mansion/react-native-reanimated/releases/tag/2.4.0). 
In your example it works when `onChange` is the only callback because GH runs on the JS thread when it receives non-worklets as callbacks, but as soon as you add any other callback it will be workletized and GH will switch to using Reanimated implementation. But since `onChange` is not worklet, it will result in the error you're seeing.
