### ISSUE TITLE
Error during compilation - RNGestureHandlerModule.kt: Type mismatch: inferred type is ReactApplicationContext? but ReactApplicationContext was expected

### ISSUE THREAD

**Issue by azyd3** [software-mansion/react-native-gesture-handler#2072]
## Description

I am using latest version of 2.1.0.
It throws the following error while compiling
node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerModule.kt: (17, 32): Type mismatch: inferred type is ReactApplicationContext? but ReactApplicationContext was expected

### Platforms

- [ ] Android

## Package versions
React: "16.11.0",
React Native:"0.62.0",
React Native Gesture Handler: 2.2.1
compileSdkVersion 31
buildToolsVersion "30.0.3"
targetSdkVersion 30

**Comment by j-piasecki** [comment]
Hi! It seems that `reactContext` taken as an argument in constructor for `ReactContextBaseJavaModule` can be nullable only since React Native 0.63. You could use `patch-package` to add non-null assertion here: https://github.com/software-mansion/react-native-gesture-handler/blob/12ebf36fb2254cb5961a6e09eec393fe1feb5068/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerModule.kt#L17
so it would become
```kotlin
  : ReactContextBaseJavaModule(reactContext!!), GestureHandlerStateManager {
```
which should fix the problem.

**Comment by azyd3** [comment]
How would I use patch package to do non null assertion?

**Comment by j-piasecki** [comment]
This patch should do the trick:
```diff
diff --git a/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerModule.kt b/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerModule.kt
index da7ca70..c1614b0 100644
--- a/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerModule.kt
+++ b/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerModule.kt
@@ -14,7 +14,7 @@ import java.util.*
 
 @ReactModule(name = RNGestureHandlerModule.MODULE_NAME)
 class RNGestureHandlerModule(reactContext: ReactApplicationContext?)
-  : ReactContextBaseJavaModule(reactContext), GestureHandlerStateManager {
+  : ReactContextBaseJavaModule(reactContext!!), GestureHandlerStateManager {
   private abstract class HandlerFactory<T : GestureHandler<T>> : RNGestureHandlerEventDataExtractor<T> {
     abstract val type: Class<T>
     abstract val name: String
```

**Comment by j-piasecki** [comment]
Looks like the problem has been solved, so I'll close the issue.
