### ISSUE TITLE
can not make  both parent and children could be response to press event

### ISSUE THREAD

**Issue by zhuliminl** [software-mansion/react-native-gesture-handler#2078]
### make sure both parent and children could be response to press event 

```

<TapGestureHandler
          onHandlerStateChange={({ nativeEvent }) => {
              // where I can record user press rect area data like position of container, do other specific logics
          }}
        >
          <View>
           // where I put my normal components here, surely it may contains TouchableOpacity elements 
            {this.props.children}
          </View>
        </TapGestureHandler>

```

**Comment by j-piasecki** [comment]
Hi! If this happened on iOS, you can try adding `extraButtonProps={{ exclusive: false }}` to the `TouchableOpacity` and/or `cancelsTouchesInView={false}` (added in Gesture Handler 2.4.0) to the `TapGestureHandler.

If it happened on Android or the above doesn't help, could you prepare a simple example reproducing the issue?

**Comment by zhuliminl** [comment]
> Hi! If this happened on iOS, you can try adding `extraButtonProps={{ exclusive: false }}` to the `TouchableOpacity` and/or `cancelsTouchesInView={false}` (added in Gesture Handler 2.4.0) to the `TapGestureHandler.
> 
> If it happened on Android or the above doesn't help, could you prepare a simple example reproducing the issue?

it happens at version 1.5.3

**Comment by j-piasecki** [comment]
In that case I would recommend upgrading to a newer version, as there is a possibility that it is already fixed.
