### ISSUE TITLE
Invariant Violation: Calling synchronous methods on native modules is not supported in Chrome. 

### ISSUE THREAD

**Issue by webinoo** [software-mansion/react-native-gesture-handler#2079]
## Description

With very small sample of code I'm getting Error on Android (real device and emulator).
`Invariant Violation: Calling synchronous methods on native modules is not supported in Chrome. `

### Platforms

- [ ] iOS
- [x] Android
- [ ] Web

### Screenshots

![screenshot](https://user-images.githubusercontent.com/1231050/170852389-a8320930-8526-4891-a2bd-3c1e202e14ba.jpg)

## Steps To Reproduce

1. git clone https://github.com/webinoo/swipe-error-android
2. cd swipe-error-android && yarn
3. yarn start
4. run on android emulator or android real device

### Expected behavior

Should work OK as on iOS.

### Actual behavior

Getting this Error.

## Snack or minimal code example

https://github.com/webinoo/swipe-error-android

## Package versions

- React: 17.0.2
- React Native: 0.68.2
- React Native Gesture Handler: 2.2.1
- React Native Reanimated: 2.8.0

**Comment by webinoo** [comment]
Hello @j-piasecki 

I added your suggestions about `GestureHandlerRootView` and `runOnJS`, but I was still running into issues. Then I identified the problem.

iOS Simulator - Without debugger attached - OK
iOS Simulator - With debugger attached - OK
Android device & emulator - Without debugger attached - OK
Android device & emulator - With debugger attached - NOT OK

Then I realized that importing Reanimated / RNGH with debugger enabled brings the problem.
I found a temporary solution - conditional require (if it's not debug mode and android), otherwise work without Reanimated.

You might say - Ok, but debugging (RND) with Reanimated is not possible (you recommend Flipper).
Actually it is but only on iOS Simulator (maybe device as well), at least it does not crash.

What is the background ? 
We need to have the app working with or without Reanimated, and debuggable in RND. Reanimated and RNGH is a nice addition but not the core functionality of our app, so if we want to debug our app by RND, it should be still possible. The appreciated solution would be some Warning and switched off Reanimated / RNGH functionality in that case, but not Exception thrown just by importing anything from the library.

Our priority is
- working app
- RND for development
- Reanimated / RNGH

Please let us know if the suggestion sounds reasonable or you have some different solution on this `bug`

( btw in some cases I realized that in iOS runOnJS was not necessary )

Please have a look on updated code
https://github.com/webinoo/swipe-error-android

Thank you

**Comment by j-piasecki** [comment]
I've looked into it a bit more and this problem should be fixed by https://github.com/software-mansion/react-native-reanimated/pull/3227. Until it's released, you could use `patch-package` to apply this fix and see if it solves the issue for you.

**Comment by webinoo** [comment]
It seems to be fixed. Sláva a Chwała Jakubovi. Dženki barzo (I'm Slovak). 🙏🙏🙏
