### ISSUE TITLE
Versions higher than 2.3.2 do not work with webpack 5.

### ISSUE THREAD

**Issue by criszz77** [software-mansion/react-native-gesture-handler#2080]
## Description

Hello. 

It seems to me that versions higher than 2.3.2 do not work with webpack 5?

Error here on this line of code: https://github.com/software-mansion/react-native-gesture-handler/blob/2.4.2/src/utils.ts#L1
I believe this would be the solution: https://stackoverflow.com/a/70333147/14056591

More info here: https://github.com/criszz77/luna/issues/55

### Platforms

- [ ] iOS
- [ ] Android
- [X] Web

### Screenshots

> Compiled with problems:X
> ERROR in ./node_modules/react-native-gesture-handler/lib/module/utils.js 41:31-46
> Should not import the named export 'version'.'split' (imported as 'rnVersion') from default-exporting module (only default export is available soon)

## Steps To Reproduce

```
npx react-native init MyAppName --template @criszz77/luna
yarn add react-native-gesture-handler
yarn web
```

### Expected behavior
Expected react-native-gesture-handler to work on the web with latest versions.

### Actual behavior
Fails to work with webpack 5.

### Snack or minimal code example
https://github.com/criszz77/luna

## Package versions

- React: 18.1.0
- React Native: 0.68.2
- React DOM: 18.1.0
- React Native Gesture Handler: > 2.3.2
- React Native Reanimated: 2.8.0
- React Native Web: 0.17.7
- React Scripts: 5.0.1

**Comment by j-piasecki** [comment]
Hi! This should already be fixed by https://github.com/software-mansion/react-native-gesture-handler/pull/2036.
