### ISSUE TITLE
Android run after build success with Error should be subtype of 'BaseViewManagerInterface!'

### ISSUE THREAD

**Issue by zhuliminl** [software-mansion/react-native-gesture-handler#2082]
Description
Hi,
`
Task :react-native-gesture-handler:compileDebugKotlin
e: /Users/zhuliming/dev/rn/logout/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewManager.kt: (37, 74): Type argument is not within its bounds: should be subtype of 'BaseViewManagerInterface!'
e: /Users/zhuliming/dev/rn/logout/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerModule.kt: (25, 32): Type mismatch: inferred type is ReactApplicationContext? but ReactApplicationContext was expected
e: /Users/zhuliming/dev/rn/logout/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerRootViewManager.kt: (21, 83): Type argument is not within its bounds: should be subtype of 'BaseViewManagerInterface!
> Task :react-native-gesture-handler:compileDebugKotlin FAILED
`

Platforms
 Android

Package versions
React: 16.9.0
React Native: 0.61.5
React Native Gesture Handler: 2.4.2

![Screen Shot 2022-06-01 at 4 51 42 PM](https://user-images.githubusercontent.com/20069490/171366282-4a1fa217-738f-48f1-8599-33dd8c9dd837.png)

**Comment by j-piasecki** [comment]
Hi! I believe that would be caused by the older version of React Native. Upgrading to React Native 0.63 or newer should solve the problem.

**Comment by j-piasecki** [comment]
@piscespieces If reinstalling `node_modules` and clearing android project doesn't help, could you share more details of your configuration and specific errors you're getting?
