### ISSUE TITLE
[WEB] Pan Gesture and Native Gesture do not work simultaneously!

### ISSUE THREAD

**Issue by gorhom** [software-mansion/react-native-gesture-handler#2091]
## Description

While working on supporting web for the Bottom Sheet, i noticed that the `Pan` gesture handler fails unexpectedly when interacting with a scroll view that is wrapped with `Native` gesture, this behaviour works just fine on mobile platforms ( iOS & Android ).

### Platforms

- [ ] iOS
- [ ] Android
- [x] Web

## Steps To Reproduce

- Run the provided snack
- Check the logs 
  - you will notice that the pan gesture fails at the very beginning of the interaction

### Expected behavior

Pan gesture and the scroll view should be active while interacting

### Actual behavior

Pan gesture fails early while the scroll view still active.

## Snack or minimal code example

https://snack.expo.dev/@gorhom/gh-web-issue

## Package versions

- React: 17.0.2
- React Native: 0.68.2
- React Native Gesture Handler: 2.2.1
- React Native Reanimated: 2.8.0

**Comment by AAlvarez90** [comment]
I don't know if this issue is for the web or not but it doesn't work on IOS either. I am using expo 45 with those versions.
This is a simple example that won't work:
```import React  from 'react';
import { Dimensions, StyleSheet, View } from 'react-native';
import { PanGestureHandler, GestureHandlerRootView } from 'react-native-gesture-handler';
import Animated, { 
  useSharedValue,
  useAnimatedStyle,
  useAnimatedGestureHandler,
} from 'react-native-reanimated';

const {
  width: SCREEN_WIDTH
} = Dimensions.get('window');

const SIZE = 100.0;

const MagicCircle = () => {

    const x = useSharedValue(0);
    const y = useSharedValue(0);

    const gestureEvent = useAnimatedGestureHandler({
        onStart: (event, ctx) => {
          ctx.x = x.value;
          ctx.y = y.value;
        },
        onActive: (event, ctx) => {
          console.log(event);
            x.value = ctx.x + event.translateX;
            y.value = ctx.x + event.translateY;
        },
        onEnd: (event) => {

        }
    });

    const rStyle = useAnimatedStyle(() => {
        return {
            transform: [{translateX: x.value},{translateY: y.value} ]
        }
    });

    return (
      <GestureHandlerRootView style={styles.container} pointerEvents="none">
        <PanGestureHandler onGestureEvent={gestureEvent}>
          <Animated.View style={[styles.square, rStyle]} />
        </PanGestureHandler>
      </GestureHandlerRootView>
    );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'green',
    alignItems: 'center',
    justifyContent: 'center',
  },
    square: {
      position: 'absolute',
      aspectRatio: 1,
      height: SIZE,
      height: SIZE,
      backgroundColor: 'blue',
      borderRadius: 20,
    }
});
  
export default MagicCircle;```
