### ISSUE TITLE
[Android]The real default value of LongPressGestureHandler maxDist property is not 10 points

### ISSUE THREAD

**Issue by b1tjoy** [software-mansion/react-native-gesture-handler#2094]
## Description
According to RNGH2 [documentation](https://docs.swmansion.com/react-native-gesture-handler/docs/gesture-handlers/api/longpress-gh#maxdist), the default value of maxDist is 10, expressed in points. But when long press and move finger within the initial 500ms less than 10 points on Android, LongPressGestureHandler will move to FAILED state.

The member variable which holds value for that inside LongPressGestureHandler is maxDistSq, meaning maxDist square, but expressed in pixels.

maxDistSq is initialized with:
https://github.com/software-mansion/react-native-gesture-handler/blob/94d0b52eba8db13aa185b38e43c5d9ed936d1ced/android/lib/src/main/java/com/swmansion/gesturehandler/LongPressGestureHandler.kt#L22-L23

But when we set prop maxDist of LongPressGestureHandler in React Native, maxDistSq is set to square of maxDist:
https://github.com/software-mansion/react-native-gesture-handler/blob/94d0b52eba8db13aa185b38e43c5d9ed936d1ced/android/lib/src/main/java/com/swmansion/gesturehandler/LongPressGestureHandler.kt#L32-L35

Google Pixel 5 for example, ppi is approximately 440, density independent pixel is 440 / 160 = 2.75, and the wrong default maxDistSq is set to `10 * density = 10 * 2.75 = 27.5`.
```JSX
maxDistSq: 27.5
maxDistPixel: Math.sqrt(27.5) = 5.244, expressed in pixels
maxDist: 5.244 / 2.75 = 1.907, expressed in points, MUCH SMALLER THAN 10 POINTS
```
when we move finger more than 1.907 points, the LongPressGestureHandler will fail.
https://github.com/software-mansion/react-native-gesture-handler/blob/94d0b52eba8db13aa185b38e43c5d9ed936d1ced/android/lib/src/main/java/com/swmansion/gesturehandler/LongPressGestureHandler.kt#L66-L72

The default maxDistSq should set to:
```Kotlin
defaultMaxDistSq = setMaxDist(DEFAULT_MAX_DIST_DP * context.resources.displayMetrics.density)
maxDistSq = defaultMaxDistSq
```

### Platforms
The issue has been verified on Android. After check RNGH2 source code, web may also be impacted.
- [ ] iOS
- [x] Android
- [x] Web

### Screenshots

https://user-images.githubusercontent.com/103875612/172172410-c25f599f-1df3-4e17-aa50-78ccd00c622a.mp4

## Steps To Reproduce

1. Run the code below and press the red area

2. Move finger within the initial 500ms, movement less than 10 points

3. Make sure total duration more than 500ms and then release finger

### Expected behavior
LongPressGestureHandler do not move to FAILED state.

### Actual behavior
LongPressGestureHandler move to FAILED state.

## Snack or minimal code example

```JSX
import React, { useState } from 'react';
import {
  ScrollView,
  StyleSheet,
  Text,
} from 'react-native';
import {
  GestureHandlerRootView,
  LongPressGestureHandler,
  State,
} from 'react-native-gesture-handler'

const STATE_MAP = {
  [State.UNDETERMINED]: 'UNDETERMINED',
  [State.FAILED]: 'FAILED',
  [State.BEGAN]: 'BEGAN',
  [State.CANCELLED]: 'CANCELLED',
  [State.ACTIVE]: 'ACTIVE',
  [State.END]: 'END',
}

const App = () => {
  const [logs, setLogs] = useState(['Log data:']);

  return (
    <GestureHandlerRootView>
      <LongPressGestureHandler
        onHandlerStateChange={e => { 
          setLogs(logs.concat(STATE_MAP[e.nativeEvent.state] +
            ', ' + JSON.stringify(e.nativeEvent)));
        }}
      >
        <Text style={styles.pressButton}>Long press me</Text>
      </LongPressGestureHandler>
      <ScrollView>
        {
          logs.map((item, index) =>
            <Text key={index} style={styles.logItem}>{item}</Text>
          )
        }
      </ScrollView>
    </GestureHandlerRootView>
  );
};

const styles = StyleSheet.create({
  pressButton: {
    backgroundColor: 'red',
    padding: 10,
    textAlign: 'center',
  },
  logItem: {
    marginTop: 5,
  },
});

export default App;
```

## Package versions

- React: 17.0.2
- React Native: 0.68.2
- React Native Gesture Handler: 2.4.2

**Comment by j-piasecki** [comment]
Thanks for the detailed description! You're right and the max distance was calculated wrongly, PR linked above should fix the problem. As for the web, it seems that `maxDist` prop was ignored altogether and it became active immediately when the pointer was moved. I added a commit that should fix it [in the PR that already solves some issues with it](https://github.com/software-mansion/react-native-gesture-handler/pull/2064).
