### ISSUE TITLE
Touchable Inspector is not working with React Native Gesture Handler buttons

### ISSUE THREAD

**Issue by taylorkline** [software-mansion/react-native-gesture-handler#2100]
## Description

React Native Touchable Inspector does not show React Native Gesture Handler Buttons.

This makes it very difficult to ensure `hitSlop` is applied correctly on smaller buttons.

### Platforms

- [x] iOS
- [x] Android
- [?] Web

### Screenshots

![Screenshot_20220609-173604_Expo_Go](https://user-images.githubusercontent.com/2641739/172956940-d5685cef-01bc-43a0-92a2-c752b66d36ce.png)

## Steps To Reproduce

1. Open Inspector, select Touchables

## Snack or minimal code example

Download the following snack and run on device: https://snack.expo.dev/@taylor.kline.bhw/react-native-gesture-handler-touchable-inspector

## Package versions

- React: `17.0.2`
- React Native: `0.68.2`
- React Native Gesture Handler: `2.2.1` - `2.4.2`
- React Native Reanimated: N/A

## Additional Context

It seems support for this was added in #177 by @osdnk with input from @kmagiera, but it no longer works. Perhaps they have some insight?

**Comment by BalogunofAfrica** [comment]
I have the same issue with custom buttons created using the gesture detector. When this custom button is nested within a normal pressable, the press events of both the child and the parents are fired together.

I checked the inspector, and the Gesture Detector implementation is not recognized as a touchable.

**Comment by BalogunofAfrica** [comment]
My current workaround for my situation is to wrap the custom button in another `Pressable` from react native, but the pressable doesn't have an `onPress` handler
