### ISSUE TITLE
Lib compilation issue on Android 13 (compilesdkversion = 33)

### ISSUE THREAD

**Issue by AndroidDev08** [software-mansion/react-native-gesture-handler#2108]
## Description

Library has compilation issue with Android 13 (targetsdkversion = 33)

`react-native-gesture-handler/android/lib/src/main/java/com/swmansion/gesturehandler/PanGestureHandler.kt: (57, 36): Type mismatch: inferred type is Context? but Context was expected`

### Platforms

- Android (OS Version 13)

## Steps To Reproduce

1. Issue can be simply reproduced by updating the compilesdkversion to 33 (Android 13)

### Expected behavior
App should compile without errors

### Actual behavior
Compilation error

`react-native-gesture-handler/android/lib/src/main/java/com/swmansion/gesturehandler/PanGestureHandler.kt: (57, 36): Type mismatch: inferred type is Context? but Context was expected`

## Package versions

- React Native: 0.68.1
- React Native Gesture Handler: 2.4.0
- React Native Reanimated: 1.3.2

**Comment by j-piasecki** [comment]
Hi! This has been already fixed by https://github.com/software-mansion/react-native-gesture-handler/pull/2096 and will be included in the next release.
