### ISSUE TITLE
RNGH FlatList with RefreshControl inside StackNavigator does not scroll when #items bigger than 1 screen

### ISSUE THREAD

**Issue by ByronStar** [software-mansion/react-native-gesture-handler#2118]
## Description

This is a setup, where the StackNavigator is configured to use the 'Down' gesture to go back one screen. The FlatList has added a RefreshControl to enable 'pull to refresh'. 

The hints in https://github.com/software-mansion/react-native-gesture-handler/issues/1067 have been used to make the RefreshControl working.

This setup is working as expected on iOS and fails on Android, as described
 
### Platforms

- [ ] iOS
- [x] Android
- [ ] Web

### Screenshots
The full screen scrolls up: header get offscreen and the list is not showing further items 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/7994992/177593217-4500edd7-23f8-4eb2-9af5-a9b08ee29d43.png)

## Steps To Reproduce

1. See Snack https://snack.expo.dev/@byrongd/rngh-flatlist-issue
2. Add/remove items in the list to see the working / failing list scroll behavior

### Expected behavior
The 'Back' navigation via swipe down and 'pull to refresh' keeps working
The FlatList keeps scrolling as before with the smaller #items

### Actual behavior
The touch area where the FlatList can still be scrolled shrinks towards the bottom of the screen the more items are in the list

## Snack or minimal code example
https://snack.expo.dev/@byrongd/rngh-flatlist-issue

## Package versions

We are using expo SDK45

"dependencies": {
    "@react-navigation/native": "^6.0.11",
    "@react-navigation/stack": "^6.2.2",
    "expo": "~45.0.0",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-native": "0.68.2",
    "react-native-safe-area-context": "4.2.4",
    "react-native-screens": "~3.11.1",
    "react-native-gesture-handler": "~2.2.1",
    "react-native-reanimated": "~2.8.0"
  }

- React: 17.0.2
- React Native: 0.68.2
- React Native Gesture Handler: ~2.2.1
- React Native Reanimated: ~2.8.0

**Comment by carlosalbertm** [comment]
facing same issue, any ideas?

**Comment by nzcodarnoc** [comment]
Here's my solution:

```
/**
 * JNTFlatList Module
 *
 * This module addresses a specific bug in the Android implementation of the
 * FlatList component from the React Native Gesture Handler library concerning the
 * pull-to-refresh gesture. The GestureHandlerFlatList is more performant with
 * gestures as they run on the native thread, unlike the FlatList from react-native
 * which operates on the JS thread. However, the pull-to-refresh gesture is broken
 * on Android in the GestureHandlerFlatList.
 *
 * To work around this, the module provides two exports:
 * - GestureHandlerFlatList, which is the default export, to be used when the
 *   pull-to-refresh gesture is not required.
 * - FlatListWithRefresh, to be used on Android when the pull-to-refresh gesture
 *   is required, as it falls back to the react-native's FlatList which supports
 *   this gesture on Android.
 *
 * Below are links to the reported bugs on GitHub that led to this module's creation:
 * - [Link to Bug 1](https://github.com/software-mansion/react-native-gesture-handler/issues/2118)
 * - [Link to Bug 2](https://github.com/software-mansion/react-native-gesture-handler/issues/1067)
 *
 */

/* eslint-disable no-restricted-imports */
import { FlatList, Platform } from "react-native";
import { FlatList as GestureHandlerFlatList } from "react-native-gesture-handler";

const FlatListWithRefresh =
  Platform.OS === "ios" ? GestureHandlerFlatList : FlatList;

export default GestureHandlerFlatList;
export { FlatListWithRefresh };
```
