### ISSUE TITLE
FlingGestureHandler always fails on iOS

### ISSUE THREAD

**Issue by nickdebaise** [software-mansion/react-native-gesture-handler#2142]
## Description

On iOS, the FlingGestureHandler always fails and never returns an activated state.

### Platforms

- [ X ] iOS
- [ Working ] Android
- [ Not Tested ] Web

### Screenshots

https://user-images.githubusercontent.com/27066041/180814730-20261df9-5660-4267-83db-c0b3c32c866f.mov

## Steps To Reproduce

You can clone the minimum repro GitHub repo here: https://github.com/nickdebaise/react-native-gesture-handler-test-fling-broken.git

Steps:
1. expo init test-broken-fling-behavior
2. cd test-broken-fling-behavior && yarn add react-native-gesture-handler
3. follow setup instructions for rn-gesture-handler (pod install, add import at top of index.js)

### Actual behavior
Began state is fired but fails almost immediately after swiping. Other handles work, such as PanGestureHandler & TapGestureHandler.

## Snack or minimal code example
`git clone https://github.com/nickdebaise/react-native-gesture-handler-test-fling-broken.git`
`cd ios && pod install`
run with either `yarn ios` or `npx react-native run-ios`

## Package versions

- React: 17.0.2
- React Native: 0.68.2
- Expo: 45.0.0
- Expo CLI: 5.5.1
- React Native Gesture Handler: 2.5.0
- React Native Reanimated: Not installed (tried installing with 2.8.0 and 2.9.1 and neither worked, if that helps)

**Comment by j-piasecki** [comment]
Hi! I cloned your repo and it works for me:

https://user-images.githubusercontent.com/21055725/180974674-f0e83493-7909-4842-b65a-fb75f0c952ef.mov

**Comment by tdvuanh** [comment]
same for me, fling gesture always fail on ios. 
Note I am testing with ios 17

**Comment by justynjozwiak** [comment]
same for me
``` 
fling.direction(Directions.UP | Directions.DOWN | Directions.LEFT | Directions.RIGHT);
```

left & right works, up & down doesn't trigger `onEnd` @j-piasecki
