### ISSUE TITLE
[iOS][Expo] PanGestureHandler does not get active when it has a `simultaneousHandlers`

### ISSUE THREAD

**Issue by gorhom** [software-mansion/react-native-gesture-handler#2169]
### Description

The new release of Expo 46 seemed had broken gesture-handler on iOS, where when a `PanGestureHandler` has `simultaneousHandlers` on, it will never get active. 

I have tested the same code base on Android, and it function as expected. Also tested on a bare React Native project, and it function as expected.

This issue did break [Bottom Sheet library](https://github.com/gorhom/react-native-bottom-sheet).

##### Expo

> expo 46.0.6, react-native 0.69.4, react-native-gesture-handler 2.5.0, react-native-reanimated 2.9.1

https://user-images.githubusercontent.com/4061838/184496206-8ac2e172-aa55-430b-89c0-b28b4212a063.mov

#### React Native

> react-native 0.69.4, react-native-gesture-handler 2.5.0, react-native-reanimated 2.9.1

https://user-images.githubusercontent.com/4061838/184496221-e571956e-7aee-49a1-be34-55228ddb4bae.mov

### Steps to reproduce

1. Run the snack provided on iOS
2. Scroll the list
> State won't get active

1. Run the snack provided on Android
2. Scroll the list
> State will get active

### Snack or a link to a repository

https://snack.expo.dev/@gorhom/7a1a40

### Gesture Handler version

2.5.0

### React Native version

0.69.4

### Platforms

iOS

### JavaScript runtime

JSC

### Workflow

Expo managed workflow

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

iPhone

### Acknowledgements

Yes

**Comment by hirbod** [comment]
Some more informations from my side:

- Running the code in SDK 45 works
- Being at SDK 46, we tried to downgrade RNGH to 2.2.1, 2.4.0
- Being at SDK 46, we tried to downgrade REA and RNS to 2.8.0 and 3.11.1 an 3.14.1

onActive does not trigger with Expo, while it does with bare. I also used @gorhom Repro and ported it RNGH v2, with GestureDetector. It is the same. onActive does not trigger.

**Comment by hirbod** [comment]
Lol, EVERYTHING works in release mode. Its only dev mode thats broken.

**Comment by brentvatne** [comment]
i don't believe that this is an issue in react-native-gesture-handler itself, i can only reproduce this in projects with expo-dev-client installed or in expo go.

**Comment by hirbod** [comment]
Yes, thats the same I was thinking and what I shared at twitter:

```
And I might have a GUESS what could be the issue: 3 finger long press gesture detection maybe for the dev menu, but its just a gut feeling
```

**Comment by lukmccall** [comment]
I can confirm that this issue is caused by something in the dev-client codebase and I think I'll have a solution soon ;)

**Comment by lukmccall** [comment]
If you're using the `expo-dev-client`, you can already test out the fix. Just bump the version of dev-client to `1.2.1`. The same fix will be available in Expo Go soon ;)

**Comment by hirbod** [comment]
Thanks for the quick fix. Will report back soon

**Comment by hirbod** [comment]
I can confirm that there are no issues anymore with 1.2.1!  Thanks a ton

**Comment by MarceloPrado** [comment]
We had the same issue at my company. Upgrading the dev-client to 1.2.1 solved the issue for us. If anyone's curious, here's the relevant commit: https://github.com/expo/expo/commit/0ce07b3d1cc2c59fd213982266a44d54c5715358

**Comment by erquhart** [comment]
This was driving me crazy, thanks so much for pointing out the fix!!
