### ISSUE TITLE
@shopify/FlashList does not integrate with createNativeWrapper

### ISSUE THREAD

**Issue by eeshankeni** [software-mansion/react-native-gesture-handler#2175]
### Description

Hi, I'm using [Flash-List ](https://github.com/Shopify/flash-list) on a vertical react navigation modal screen and it's not handling the vertical swipe gestures well on android. Is there a way to integrate Flash-List with react native gesture handler the way FlatlList has been?

https://github.com/Shopify/flash-list/issues/551

### Steps to reproduce

1. Create a vertical stack navigator screen using react navigation
2.  Add flashList to this screen
3. Notice how swipe gestures break on android and the modal dismisses instead of scrolling down the flash list

### Snack or a link to a repository

https://github.com/JackShannon/flashlistgesture

### Gesture Handler version

2.5.0

### React Native version

0.69.4

### Platforms

Android

### Acknowledgements

Yes

**Comment by j-piasecki** [comment]
`createNativeWrapper` works when you pass a native view to it, and FlashList is a JS component. I got it to work by slightly modifying your code:
```jsx
import {
  GestureHandlerRootView,
  PanGestureHandler,
  ScrollView,
} from 'react-native-gesture-handler';

...

export default function App() {
  const [active, setActive] = useState(false);
  const panRef = useRef();

  return (
    <GestureHandlerRootView style={{flex: 1}}>
      <SafeAreaView style={{flex: 1}}>
        <PanGestureHandler
          ref={panRef}
          onActivated={() => {
            setActive(true);
          }}
          onEnded={() => {
            setActive(false);
          }}>
          <View
            style={{flex: 1, backgroundColor: active ? 'lightgreen' : null}}>
            <FlashList
              overrideProps={{
                simultaneousHandlers: panRef,
              }}
              data={DATA}
              renderItem={({item}) => <Text>{item.title}</Text>}
              estimatedItemSize={200}
              renderScrollComponent={ScrollView}
            />
          </View>
        </PanGestureHandler>
        <Text>Gesture state: {active ? 'ACTIVE' : 'NOT ACTIVE'}</Text>
      </SafeAreaView>
    </GestureHandlerRootView>
  );
}
```

It relies on the fact that FlashList passes the content of `overrideProps` to `scrollViewProps` on `ProgressiveListView` - https://github.com/Shopify/flash-list/blob/2363e275ecbd2d47f78414d821cad9859d45411d/src/FlashList.tsx#L333

**Comment by eeshankeni** [comment]
Thank you. This actually does seem to work, 

> `createNativeWrapper` works when you pass a native view to it, and FlashList is a JS component. I got it to work by slightly modifying your code:
> 
> ```js
> import {
>   GestureHandlerRootView,
>   PanGestureHandler,
>   ScrollView,
> } from 'react-native-gesture-handler';
> 
> ...
> 
> export default function App() {
>   const [active, setActive] = useState(false);
>   const panRef = useRef();
> 
>   return (
>     <GestureHandlerRootView style={{flex: 1}}>
>       <SafeAreaView style={{flex: 1}}>
>         <PanGestureHandler
>           ref={panRef}
>           onActivated={() => {
>             setActive(true);
>           }}
>           onEnded={() => {
>             setActive(false);
>           }}>
>           <View
>             style={{flex: 1, backgroundColor: active ? 'lightgreen' : null}}>
>             <FlashList
>               overrideProps={{
>                 simultaneousHandlers: panRef,
>               }}
>               data={DATA}
>               renderItem={({item}) => <Text>{item.title}</Text>}
>               estimatedItemSize={200}
>               renderScrollComponent={ScrollView}
>             />
>           </View>
>         </PanGestureHandler>
>         <Text>Gesture state: {active ? 'ACTIVE' : 'NOT ACTIVE'}</Text>
>       </SafeAreaView>
>     </GestureHandlerRootView>
>   );
> }
> ```
> 
> It relies on the fact that FlashList passes the content of `overrideProps` to `scrollViewProps` on `ProgressiveListView` - https://github.com/Shopify/flash-list/blob/2363e275ecbd2d47f78414d821cad9859d45411d/src/FlashList.tsx#L333

Thanks, this actually seems to work for vertical gestures. Would it also be possible to detect horizontal gestures as well? Vertical gestures are working fine for me now but I also would like to be able to swipe left and right between different flashList's. Could you please tell me how I could go about doing that?

**Comment by eeshankeni** [comment]
Thank you so much, this was really helpful! Perhaps this modified FlashList could be included within RNGH the way flatlist and scrollview do!

> `createNativeWrapper` works when you pass a native view to it, and FlashList is a JS component. I got it to work by slightly modifying your code:
> 
> ```js
> import {
>   GestureHandlerRootView,
>   PanGestureHandler,
>   ScrollView,
> } from 'react-native-gesture-handler';
> 
> ...
> 
> export default function App() {
>   const [active, setActive] = useState(false);
>   const panRef = useRef();
> 
>   return (
>     <GestureHandlerRootView style={{flex: 1}}>
>       <SafeAreaView style={{flex: 1}}>
>         <PanGestureHandler
>           ref={panRef}
>           onActivated={() => {
>             setActive(true);
>           }}
>           onEnded={() => {
>             setActive(false);
>           }}>
>           <View
>             style={{flex: 1, backgroundColor: active ? 'lightgreen' : null}}>
>             <FlashList
>               overrideProps={{
>                 simultaneousHandlers: panRef,
>               }}
>               data={DATA}
>               renderItem={({item}) => <Text>{item.title}</Text>}
>               estimatedItemSize={200}
>               renderScrollComponent={ScrollView}
>             />
>           </View>
>         </PanGestureHandler>
>         <Text>Gesture state: {active ? 'ACTIVE' : 'NOT ACTIVE'}</Text>
>       </SafeAreaView>
>     </GestureHandlerRootView>
>   );
> }
> ```
> 
> It relies on the fact that FlashList passes the content of `overrideProps` to `scrollViewProps` on `ProgressiveListView` - https://github.com/Shopify/flash-list/blob/2363e275ecbd2d47f78414d821cad9859d45411d/src/FlashList.tsx#L333
