### ISSUE TITLE
Crash with async handler

### ISSUE THREAD

**Issue by nschild** [software-mansion/react-native-gesture-handler#2186]
### Description

App crashes when you have an async event handler on js

2022-08-26 15:21:06.375 27713-27713/? A/DEBUG: Abort message: 'JNI DETECTED ERROR IN APPLICATION: JNI GetObjectRefType called with pending exception java.lang.RuntimeException: Cannot read property '__callAsync' of undefined
    
    TypeError: Cannot read property '__callAsync' of undefined
        at runOnJS ...

### Steps to reproduce
```
  const singleTap = Gesture.Tap()
  .enabled(isMini)
  .maxDuration(250)
  .onStart(() => {
    runOnJS(handleTap)();
  });

const handleTap = async() => do something

render (
    <GestureDetector gesture={singleTap}>
        ...
)
```

works
```
  const singleTap = Gesture.Tap()
  .enabled(isMini)
  .maxDuration(250)
  .onStart(() => {
    runOnJS(handleTap)();
  });

const handleTap = () => {handleTap2()}
const handleTap2 = async() => do something

render (
    <GestureDetector gesture={singleTap}>
        ...
)
```

### Snack or a link to a repository

no

### Gesture Handler version

2.5.0

### React Native version

0.66.4

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

s20

### Acknowledgements

Yes

**Comment by j-piasecki** [comment]
I think it may be due to the order of declarations. You're trying to use `handleTap` function inside `onStart` callback before the `handleTap` is declared. If you change the order like so:
```jsx
const handleTap = async() => do something

const singleTap = Gesture.Tap()
  .enabled(isMini)
  .maxDuration(250)
  .onStart(() => {
    runOnJS(handleTap)();
  });

return (
    <GestureDetector gesture={singleTap}>
        ...
)
```
it should work.
