### ISSUE TITLE
Stop running 'npx react-native run-android'

### ISSUE THREAD

**Issue by UmarFarooqCA** [software-mansion/react-native-gesture-handler#2195]
### Description

Task :react-native-gesture-handler:compileDebugKotlin FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings
325 actionable tasks: 311 executed, 14 up-to-date
Note: C:\Users\DELL\Desktop\work\Trackly\node_modules\react-native-gradle-plugin\src\main\java\com\facebook\react\codegen\generator\SchemaJsonParser.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
[CXX1300] CMake '3.18.1' was not found in SDK, PATH, or by cmake.dir property.
[CXX1301] - CMake '3.10.2' found in SDK did not satisfy requested version.
[CXX1300] CMake '3.18.1' was not found in SDK, PATH, or by cmake.dir property.
[CXX1301] - CMake '3.10.2' found in SDK did not satisfy requested version.
Warning: unexpected element (uri:"", local:"extension-level"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>
Warning: unexpected element (uri:"", local:"base-extension"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>
Note: C:\Users\DELL\Desktop\work\Trackly\node_modules\@invertase\react-native-apple-authentication\android\src\main\java\com\RNAppleAuthentication\AppleAuthenticationAndroidModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\DELL\Desktop\work\Trackly\node_modules\@react-native-community\blur\android\src\main\java\com\reactnativecommunity\blurview\BlurViewManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\DELL\Desktop\work\Trackly\node_modules\@react-native-community\slider\android\src\main\java\com\reactnativecommunity\slider\ReactSliderManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: [2] Wrote GeneratedAppGlideModule with: [com.bumptech.glide.integration.okhttp3.OkHttpLibraryGlideModule, com.dylanvann.fastimage.FastImageOkHttpProgressGlideModule]
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
e: C:\Users\DELL\Desktop\work\Trackly\node_modules\react-native-gesture-handler\android\reanimated\src\main\java\com\swmansion\gesturehandler\ReanimatedEventDispatcher.kt: (5, 22): Unresolved reference: reanimated
e: C:\Users\DELL\Desktop\work\Trackly\node_modules\react-native-gesture-handler\android\reanimated\src\main\java\com\swmansion\gesturehandler\ReanimatedEventDispatcher.kt: (8, 35): Unresolved reference: ReanimatedModule
e: C:\Users\DELL\Desktop\work\Trackly\node_modules\react-native-gesture-handler\android\reanimated\src\main\java\com\swmansion\gesturehandler\ReanimatedEventDispatcher.kt: (12, 56): Not enough information to infer type variable T
e: C:\Users\DELL\Desktop\work\Trackly\node_modules\react-native-gesture-handler\android\reanimated\src\main\java\com\swmansion\gesturehandler\ReanimatedEventDispatcher.kt: (12, 72): Unresolved reference: ReanimatedModule
e: C:\Users\DELL\Desktop\work\Trackly\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerModule.kt: (14, 22): Unresolved reference: common
e: C:\Users\DELL\Desktop\work\Trackly\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerModule.kt: (25, 47): Unresolved reference: GestureHandlerStateManager
e: C:\Users\DELL\Desktop\work\Trackly\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerModule.kt: (413, 3): 'setGestureHandlerState' overrides nothing

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-gesture-handler:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 18s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
Note: C:\Users\DELL\Desktop\work\Trackly\node_modules\react-native-gradle-plugin\src\main\java\com\facebook\react\codegen\generator\SchemaJsonParser.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
[CXX1300] CMake '3.18.1' was not found in SDK, PATH, or by cmake.dir property.
[CXX1301] - CMake '3.10.2' found in SDK did not satisfy requested version.
[CXX1300] CMake '3.18.1' was not found in SDK, PATH, or by cmake.dir property.
[CXX1301] - CMake '3.10.2' found in SDK did not satisfy requested version.
Warning: unexpected element (uri:"", local:"extension-level"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>
Warning: unexpected element (uri:"", local:"base-extension"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>
Note: C:\Users\DELL\Desktop\work\Trackly\node_modules\@invertase\react-native-apple-authentication\android\src\main\java\com\RNAppleAuthentication\AppleAuthenticationAndroidModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\DELL\Desktop\work\Trackly\node_modules\@react-native-community\blur\android\src\main\java\com\reactnativecommunity\blurview\BlurViewManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\DELL\Desktop\work\Trackly\node_modules\@react-native-community\slider\android\src\main\java\com\reactnativecommunity\slider\ReactSliderManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: [2] Wrote GeneratedAppGlideModule with: [com.bumptech.glide.integration.okhttp3.OkHttpLibraryGlideModule, com.dylanvann.fastimage.FastImageOkHttpProgressGlideModule]
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
e: C:\Users\DELL\Desktop\work\Trackly\node_modules\react-native-gesture-handler\android\reanimated\src\main\java\com\swmansion\gesturehandler\ReanimatedEventDispatcher.kt: (5, 22): Unresolved reference: reanimated
e: C:\Users\DELL\Desktop\work\Trackly\node_modules\react-native-gesture-handler\android\reanimated\src\main\java\com\swmansion\gesturehandler\ReanimatedEventDispatcher.kt: (8, 35): Unresolved reference: ReanimatedModule
e: C:\Users\DELL\Desktop\work\Trackly\node_modules\react-native-gesture-handler\android\reanimated\src\main\java\com\swmansion\gesturehandler\ReanimatedEventDispatcher.kt: (12, 56): Not enough information to infer type variable T
e: C:\Users\DELL\Desktop\work\Trackly\node_modules\react-native-gesture-handler\android\reanimated\src\main\java\com\swmansion\gesturehandler\ReanimatedEventDispatcher.kt: (12, 72): Unresolved reference: ReanimatedModule
e: C:\Users\DELL\Desktop\work\Trackly\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerModule.kt: (14, 22): Unresolved reference: common
e: C:\Users\DELL\Desktop\work\Trackly\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerModule.kt: (25, 47): Unresolved reference: GestureHandlerStateManager
e: C:\Users\DELL\Desktop\work\Trackly\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerModule.kt: (413, 3): 'setGestureHandlerState' overrides nothing

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-gesture-handler:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 18s

    at makeError (C:\Users\DELL\Desktop\work\Trackly\node_modules\execa\index.js:174:9)
    at C:\Users\DELL\Desktop\work\Trackly\node_modules\execa\index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (C:\Users\DELL\Desktop\work\Trackly\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (C:\Users\DELL\Desktop\work\Trackly\node_modules\@react-native-community\cli\build\index.js:192:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Steps to reproduce

1. npx react-native run-android

### Snack or a link to a repository

It's private repo

### Gesture Handler version

2.4.2

### React Native version

0.68.2

### Platforms

Android

### JavaScript runtime

JSC

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

Samsung Galaxy A72 Android 12

### Acknowledgements

Yes

**Comment by UmarFarooqCA** [comment]
Sorry, the repo is private and I cannot create new repo because it's a large project.

**Comment by j-piasecki** [comment]
Could you check if https://github.com/software-mansion/react-native-gesture-handler/pull/2201 solves the problem for you?

**Comment by UmarFarooqCA** [comment]
thanks, @j-piasecki. I solved the issue by changing the Gradle version

**Comment by jesusgomezhdez** [comment]
@UmarFarooqCA which version do you use?

**Comment by jde8aa** [comment]
@UmarFarooqCA would love to know what fix you implemented for this issue.  I'm having the same problem.
