### ISSUE TITLE
Access locations of gesture touches

### ISSUE THREAD

**Issue by cwhenderson20** [software-mansion/react-native-gesture-handler#221]
Thanks for the great library!

I'm looking to create a system in which one gesture handler (rotation/pinch) might apply its effects to one of a few different animated views nested within it. In order to figure out which layer to affect, I'll need to access the locations of the individual touches that comprise the gesture. Unfortunately, the focalX/Y and anchorX/Y don't provide enough info for my purposes.

PanResponder from React Native exposes this feature natively, but I'd much prefer to use this declarative library.

It might look something like this:

```javascript
{
  nativeEvent: {
    // ...
    touches: [{
      x: 123,
      y: 456
    }]
  }
}
```

But ultimately, the format isn't important — as long as it's possible to access the location (and maybe other properties) of each touch on both the state change and handler events.

**Comment by osdnk** [comment]
Hi, @cwhenderson20 
Thank you for this suggestion as it might be a nice feature to be implemented. 
I think we'll take a look on it but I cannot predict when it could happen as we have another important targets now

**Comment by chirhotec** [comment]
+1 for this feature, but for a different use case. I'm having trouble getting combining Pinch and 2 finger Pan handlers (read the docs, tried the demo, still having issues). With some of this raw data it should be possible for me to use the PanGestureHandler to account for both pan and pinch.

**Comment by j-piasecki** [comment]
Hi! I believe that [touch events](https://docs.swmansion.com/react-native-gesture-handler/docs/api/gestures/touch-events) introduced in Gesture Handler 2 are fulfilling the use case you have described so I'll close the issue.

**Comment by Noitidart** [comment]
Oh thank you I will try that!
