### ISSUE TITLE
Cannot read properties of undefined (reading 'flushOperations') in rn windows c#

### ISSUE THREAD

**Issue by chGalbadrakh** [software-mansion/react-native-gesture-handler#2213]
### Description

"Windows application, Visual Studio 2019, Developed by c#"
I had updated the react-native version to 0.69.5, react-native-windows version to 0.69.6. 

After the react-native-windows updgrade, when i was debugging the following bug has occured. (See the below screenshot please.)
I tried the version 2.6.0 , 2.5.0 and 2.4.2 of **react-native-gesture-handler**, but all of them threw the same error.
To use @react-navigation/drawer library i needed to use the react-native-gesture-handler library.
The library and version i am using for react navigation is ;
 "@react-navigation/drawer": "6.4.4",
 "@react-navigation/native": "6.0.12",
 "@react-navigation/native-stack": "6.8.0",

![Screenshot 2022-09-09 181910](https://user-images.githubusercontent.com/17295812/189328673-5e06537f-0485-4e79-85ce-1c8ce9b1c84c.png)

### Steps to reproduce

1. rn upgrade, react-native-windows upgrade
2. debug

### Snack or a link to a repository

a

### Gesture Handler version

2.6.0

### React Native version

0.69.5

### Platforms

Android, iOS, Web

### Workflow

React Native (without Expo)

### Build type

Debug mode

### Device

Real device

### Device model

Windows 11

### Acknowledgements

Yes

**Comment by Warus15** [comment]
Hi! Check which causes the error was introduced in version 2.4.0, so You can try downgrading Gesture Handler to version below 2.4.0. Alternatively you can have a look at [this PR](https://github.com/software-mansion/react-native-gesture-handler/pull/2215), which should fix this problem.

**Comment by DaMrNelson** [comment]
I encountered this error while following through the UI Kitten "Configure Navigation" guide. I found that the package `react-native-gesture-handler` was not even installed and was able to resolve this issue by manually installing it ([see install docs](https://docs.swmansion.com/react-native-gesture-handler/docs/installation)).
