### ISSUE TITLE
Support for Android Gradle Plugin Version 7.30

### ISSUE THREAD

**Issue by iamarjun** [software-mansion/react-native-gesture-handler#2223]
### Description

The Android Gradle plugin supports only kotlin-android-extensions Gradle plugin version 1.6.20 and higher.
The following dependencies do not satisfy the required version:
project ':react-native-gesture-handler' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.20

### Steps to reproduce

Upgrade existing android codebase to android Gradle plugin version 7.30

### Snack or a link to a repository

any project that is updated to android gradle plugin version 7.3.0

### Gesture Handler version

2.60

### React Native version

0.69.5

### Platforms

Android

### Acknowledgements

Yes

**Comment by j-piasecki** [comment]
You can change the version of Kotlin Gesture Handler is using by setting `ext.kotlinVersion` in your project-level `build.gradle`. In your case, setting it to `1.6.20` should solve the problem.

As a sidenote, you should consider migrating off of `kotlin-android-extensions` as it's [scheduled for removal in Kotlin 1.8](https://android-developers.googleblog.com/2022/02/discontinuing-kotlin-synthetics-for-views.html).

**Comment by iamarjun** [comment]
> You can change the version of Kotlin Gesture Handler is using by setting `ext.kotlinVersion` in your project-level `build.gradle`. In your case, setting it to `1.6.20` should solve the problem.
> 
> As a sidenote, you should consider migrating off of `kotlin-android-extensions` as it's [scheduled for removal in Kotlin 1.8](https://android-developers.googleblog.com/2022/02/discontinuing-kotlin-synthetics-for-views.html).

Thanks, @j-piasecki will try this, also migration is in WIP for kotlin synthetics.

**Comment by j-piasecki** [comment]
It would be in the project-level `build.gradle`:
```groovy
buildscript {
    ext {
        buildToolsVersion = "31.0.0"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31
        kotlinVersion="1.6.20"
        ...
```

**Comment by NLanese** [comment]
That gives me the following error... 
```
Could not open cp_proj generic class cache for build file '/Users/nicklanese/Documents/GitHub/KidzNMotionDirectory/KidzNMotionNative/android/build.gradle' (/Users/nicklanese/.gradle/caches/7.5.1/scripts/1zemuiejeqx05vvvxe3i9qnv6).
   > BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 63
```
I seem to get this error (or something like it) every time I change anything to do with Kotlin, in any level build file

**Comment by j-piasecki** [comment]
A quick google suggests that it may be caused by JVM/Gradle version mismatch or cache, so you can try changing versions (see compatibility [here](https://docs.gradle.org/current/userguide/compatibility.html)) and/or clearing cache. Otherwise, I don't think I will be able to help.

**Comment by timothygorer** [comment]
> You can change the version of Kotlin Gesture Handler is using by setting `ext.kotlinVersion` in your project-level `build.gradle`. In your case, setting it to `1.6.20` should solve the problem.
> 
> As a sidenote, you should consider migrating off of `kotlin-android-extensions` as it's [scheduled for removal in Kotlin 1.8](https://android-developers.googleblog.com/2022/02/discontinuing-kotlin-synthetics-for-views.html).

How do you migrate off of kotlin-android-extensions @j-piasecki ?
