### ISSUE TITLE
PanGestureHandler.onBegan not consistent between iOS and Android

### ISSUE THREAD

**Issue by tapz** [software-mansion/react-native-gesture-handler#223]
In Android PanGestureHandler.onBegan event is sent immediately when the user touches the screen. However, in iOS the event is not sent before the user moves her finger.

Version: 1.0.5

**Comment by j-piasecki** [comment]
We made `PanGestureHandler` on iOS to follow the same state flow as on Android in https://github.com/software-mansion/react-native-gesture-handler/pull/1611. It should now fire `onBegan` when the user touches the screen.
