### ISSUE TITLE
I have a RefreshControl of my own, but when I use it，it becomes your RefreshControl

### ISSUE THREAD

**Issue by OneHangH** [software-mansion/react-native-gesture-handler#2248]
### Description

I have a RefreshControl of my own, but when I use it，it becomes your RefreshControl.
How can i use my  RefreshControl ?

### Steps to reproduce

1. import MyRefreshControl from '../component/common/RefreshControl'
2. <ScrollView refreshControl={MyRefreshControl}>...</ScrollView>
3. refreshControl no use MyRefreshControl
4. in your code:
<img width="704" alt="image" src="https://user-images.githubusercontent.com/31791685/192976718-1f74c76b-6a78-4fef-83dc-80078d90179e.png">

### Snack or a link to a repository

no

### Gesture Handler version

2.6.0

### React Native version

0.64

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Acknowledgements

Yes

**Comment by Warus15** [comment]
Hi 👋 The code that you've provided in screenshot has been changed recently. Try updating GestureHandler to version [2.6.2](https://github.com/software-mansion/react-native-gesture-handler/releases) and check whether the problem still occurs.
