### ISSUE TITLE
[Android][Windows][New Architecture][build release]  Invalid character escape '\m'

### ISSUE THREAD

**Issue by alabsi91** [software-mansion/react-native-gesture-handler#2258]
### Description

```console
  CMake Error at D:/myproject/android/app/build/generated/rncli/src/main/jni/Android-rncli.cmake:6 (add_subdirectory):
    Syntax error in cmake code at

      D:/myproject/android/app/build/generated/rncli/src/main/jni/Android-rncli.cmake:6

    when parsing string

      D:\myproject\node_modules\react-native-gesture-handler\android\build\generated\source\codegen\jni\ rngesturehandler_codegen_autolinked_build

    Invalid character escape '\m'.
  Call Stack (most recent call first):
    D:/myproject/node_modules/react-native/ReactAndroid/cmake-utils/ReactNative-application.cmake:59 (include)
    CMakeLists.txt:7 (include)
```

### Steps to reproduce

- build release for android on a Windows machine.

### Snack or a link to a repository

https://snack.expo.io/

### Gesture Handler version

2.7.0

### React Native version

0.70.2

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Release mode

### Acknowledgements

Yes

**Comment by alabsi91** [comment]
![image](https://user-images.githubusercontent.com/58077449/194068277-73d3bd4b-f50d-4319-9611-e82995e27b7f.png)

**Comment by j-piasecki** [comment]
This error comes from files that are autogenerated by React Native. I don't think I will be able to help much here but you should consider opening an issue in the react-native repo.
