### ISSUE TITLE
[Windows c#] TypeError: Cannot read properties of undefined (reading 'handleSetJSResponder')

### ISSUE THREAD

**Issue by chGalbadrakh** [software-mansion/react-native-gesture-handler#2266]
### Description

"Windows application, Visual Studio 2019, Developed by c#"
I had updated the react-native version to 0.69.5, react-native-windows version to 0.69.9, @react-navigation/native5.x->6.x
how solve this bug.
![Screenshot 2022-10-11 134918](https://user-images.githubusercontent.com/17295812/195008515-3459bf6b-22ce-4d62-a93a-1afbd640aef9.png)
![Screenshot 2022-10-11 135004](https://user-images.githubusercontent.com/17295812/195008519-01560371-340a-4a83-b82a-be9314b1ce06.png)

### Steps to reproduce

1. react navigation upgrade to last version(using native, stack, drawer)
2. react-native-gesture-handler install 2.5.0 between 2.7.0 versions
3. yarn run windows

### Snack or a link to a repository

https://github.com/software-mansion/react-native-gesture-handler/issues/2213

### Gesture Handler version

2.5.0-2.7.0

### React Native version

0.69.5

### Platforms

iOS

### Workflow

React Native (without Expo)

### Build type

Debug mode

### Device

Real device

### Device model

Windows 11 UWP

### Acknowledgements

Yes

**Comment by chGalbadrakh** [comment]
Hello. I updgraded my React Native version to 0.69.5 and accordingly i upgraded the packages i use on React Navigation.
Upgraded libraries :
react-native: 0.64.2 -> 0.69.5
react-native-windows: 0.64.2 -> 0.69.9

Libraries used on React Navigation :
@react-navigation/drawer: 5.12.3 -> 6.5.0
@react-navigation/native: 5.9.2 -> 6.0.13
@react-navigation/stack: 5.14.2 -> 6.3.1
react-native-gesture-handler: 1.10.1 -> 2.7.0
react-native-reanimated: 1.113.2 -> 2.10.0
react-native-safe-area-context: 3.1.9 -> 4.4.1
react-native-screens: 2.17.1 -> 3.18.0

When i run debugging the above error is occurring on react-native-gesture-handler. If you have any method to fix this or any advice please share with me.
On IOS, debugging and release build are working fine.
The problem is RN Windows c#.

**Comment by Warus15** [comment]
Hi 👋 We don't use windows machines so it's hard to check what's going on. However, have a look at [this PR](https://github.com/software-mansion/react-native-gesture-handler/pull/2272), I think it will help.

**Comment by praveenreddy9** [comment]
Hello,
I am also getting the same error with IOS of v0.70.3, Please help me in resolving.
