### ISSUE TITLE
shouldCancelWhenOutside default behavior doesn't agree with docs

### ISSUE THREAD

**Issue by elliotwaite** [software-mansion/react-native-gesture-handler#2284]
### Description

The docs for `shouldCancelWhenOutside()` mention:
> Default value of this property is different depending on the handler type. Most handlers' shouldCancelWhenOutside property defaults to false except for the [LongPressGesture](https://docs.swmansion.com/react-native-gesture-handler/docs/api/gestures/long-press-gesture) and [TapGesture](https://docs.swmansion.com/react-native-gesture-handler/docs/api/gestures/tap-gesture) which default to true.

However, the default value for `Tap` and `LongPress` seems to be `false`, as can be seen in this demo:

![default](https://user-images.githubusercontent.com/1767836/196841329-59e17d2d-5181-4c08-a8bf-ed90a355cc37.gif)

So far I've only tested it on Android and iOS. I'm not sure what the default behavior is on the web.

### Steps to reproduce

Load up the provided Snack in Android or iOS and test out the gestures as seen in the demo to see which gestures get canceled when the press is held and the cursor is dragged outside the buttons.

### Snack or a link to a repository

https://snack.expo.dev/@elliotwaite/rngh-shouldcancelwhenoutside-default-behavior

### Gesture Handler version

2.5.0

### React Native version

0.69.0

### Platforms

Android, iOS

### Acknowledgements

Yes

**Comment by Warus15** [comment]
Hi @elliotwaite 👋

I've checked web version and it seems to work fine. However it would be great if you could also have a look at that, maybe I've missed something.

Also, I've prepared [PR](https://github.com/software-mansion/react-native-gesture-handler/pull/2286) that should fix this issue on iOS and Android.

**Comment by elliotwaite** [comment]
Okay, sounds good. With my current setup, it's difficult to test out the web version, but if I test it out in the future and I notice that it's not working as would have expected, I'll reopen this issue.

Thanks for the quick PR!

**Comment by Warus15** [comment]
Hi! As this issue seems to be solved, I'll close it. However if you'll find out that something is not working properly, feel free to reopen it.

**Comment by elliotwaite** [comment]
Sounds good. Thanks again.
