### ISSUE TITLE
Stop using DrawerLayoutAndroid on web (Removed from react-native-web)

### ISSUE THREAD

**Issue by edkimmel** [software-mansion/react-native-gesture-handler#2304]
### Description

As of the [0.19 RNW canary](https://github.com/necolas/react-native-web/pull/2377), the DrawerLayoutAndroid export has been removed.

The previous implementation was returning UnimplementedView, so no functionality should be tied to this module on web.

### Steps to reproduce

Attempt to compile a project using react-native-gesture-handler and react-native-web@0.0.0-a825648cb.

### Snack or a link to a repository

https://github.com/necolas/react-native-web/pull/2377

### Gesture Handler version

2.8.0

### React Native version

0.69.6

### Platforms

Web

### Acknowledgements

Yes

**Comment by jonathanj** [comment]
react-native-web 0.19.0 was released ~3 weeks ago, which unfortunately means that any attempt to use RNGH with RNW now blows up.

**Comment by iamalwayswong** [comment]
Hi! Any idea when the above PR will be merged? @j-piasecki  Thanks!!
