### ISSUE TITLE
Nested TapGestureHandler with a PanGestureHandler inside

### ISSUE THREAD

**Issue by moribaleta** [software-mansion/react-native-gesture-handler#2317]
### Description

im encountering an issue with some devices 
with a having a tap function and pan gesture in a single component

currenlty

```
<ReAnimated.View
        style={[
          panAnimatedStyle,
          styles.childContainer,
          backgroundColor && { backgroundColor },
        ]}
      >
        <TapGestureHandler
          ref={tapRef}
          testID={testID}
          simultaneousHandlers={panRef}
          onHandlerStateChange={onTapGesture}
          maxDist={1}
        >
          <View>
            <PanGestureHandler
              ref={panRef}
              activeOffsetX={[-50, 20]}
              onCancelled={() => onEnd()}
              enabled={isSwipeable}
              simultaneousHandlers={tapRef}
              onGestureEvent={isSwipeable ? onGestureEvent : undefined}
              shouldCancelWhenOutside
            >
              <ReAnimated.View style={tapStyle}>{children}</ReAnimated.View>
            </PanGestureHandler>
          </View>
        </TapGestureHandler>
      </ReAnimated.View>
```

### Steps to reproduce

tapping on the content will not trigger the onPress action this is being blocked by PanGestureHandler
this worked on most devices but can encounter on some devices especially running Android 11

![Screen_Recording_20221114_140021_Pepperstone_2](https://user-images.githubusercontent.com/13190143/201567566-79bbbc3d-97d4-45ab-9d69-013aae8b2594.gif)

based on the screenrecording 
the tap gesture state is showing 2,1 which is failed 

### Snack or a link to a repository

https://snack.expo.dev/q8bSx8aeR

### Gesture Handler version

2.8.0

### React Native version

0.70.5

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Build type

Release mode

### Device

Real device

### Device model

Samsung Galaxy S22 android 12 and Sony Xperia 1 Android 11

### Acknowledgements

Yes

**Comment by j-piasecki** [comment]
I've looked at the snack but it seems to have some errors. I tried to modify it but after the changes it seems to be working correctly for me - the swipeable can be dragged left and right, and pressing it triggers the `onPress` method.

I will be able to test on more devices tomorrow, meanwhile, could you update the code so that it reproduces your issue out of the box, without the need for any changes?

**Comment by moribaleta** [comment]
> I've looked at the snack but it seems to have some errors. I tried to modify it but after the changes it seems to be working correctly for me - the swipeable can be dragged left and right, and pressing it triggers the `onPress` method.
> 
> I will be able to test on more devices tomorrow, meanwhile, could you update the code so that it reproduces your issue out of the box, without the need for any changes?

it works on debug build but on the release build the bug is only encountered by some devices not all

I used the 2.0 version of Gesture with `Gesture.Pan` and `Gesture.Tap` they work great and didn't encounter this bug
will try to change the given example to be usable out of the box

**Comment by longb1997** [comment]
+1
