### ISSUE TITLE
[IOS] reloading App crashes in Xcode

### ISSUE THREAD

**Issue by moribaleta** [software-mansion/react-native-gesture-handler#2319]
### Description

running on XCode 14.1

```
 const currState = useSharedValue<State>(State.UNDETERMINED);
const tapGesture = Gesture.Tap()
    .withTestId(`${testID}-tap`)
    .maxDistance(1)
    .onTouchesDown(() => {
      currState.value = State.BEGAN;
    })
    .onTouchesUp(() => {
      if (onPress) runOnJS(onPress)();
    })
    .onTouchesCancelled(() => {
      currState.value = State.UNDETERMINED;
    })
    .onEnd(() => {
      currState.value = State.UNDETERMINED;
    });
```

onRunJS is causing the issue
can fully replicate it 

on reload of the ios simulator xcode crashes
![Screenshot 2022-11-15 at 1 33 54 PM](https://user-images.githubusercontent.com/13190143/201834627-24e11761-0560-416b-87ab-477067e9d71e.png)

### Steps to reproduce

run Gesture function that access to shareValue variables
reload app
crash

### Snack or a link to a repository

https://snack.expo.dev/JHArrUvUm

### Gesture Handler version

2.8.0

### React Native version

0.70.5

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by sylvain-abadie** [comment]
This is also happening in the examples:
- open calculator
- press r to reload

**Comment by alexandrius** [comment]
I can reproduce also

Invoking other functions in `onChange` (or any other, worklet or not) event makes the app crash on reload.
```js
  const panGesture = Gesture.Pan().onChange(({ velocityY, translationY }) => {
    if (velocityY >= 0) {
      translateAnim.value = interpolate(translationY, [0, 400], [1, 0]);
    }
  });
```

**Comment by j-piasecki** [comment]
It's possible that this problem was fixed on the side of Reanimated with the recent rewrite of shareable values. You can try using Reanimated 3.0.0-rc.8 to see if it resolves the problem.

**Comment by ealmiladi** [comment]
> It's possible that this problem was fixed on the side of Reanimated with the recent rewrite of shareable values. You can try using Reanimated 3.0.0-rc.8 to see if it resolves the problem.

It is fixed on `reanimated@3.0.0-rc.8`, however, other bugs can be found on that version since it is an RC.

**Comment by braincore** [comment]
Is there any version of RNGH that doesn't have this issue or is it entirely a problem with reanimated?

**Comment by davidpett** [comment]
I found the issue is with the new Gesture api and using runOnJS.
a workaround is to use the old gesture api:

```js
const onTapGesture = useAnimatedGestureHandler(
  {
    onTouchesDown: () => {
      currState.value = State.BEGAN;
    },
    onTouchesUp: () => {
      if (onPress) {
        runOnJS(onPress)();
      }
    },
    onTouchesCancelled: () => {
      currState.value = State.UNDETERMINED;
    },
    onEnd: () => {
      currState.value = State.UNDETERMINED;
    },
  },
  [onPress] 
);
//...
<TapGestureHandler onGestureEvent={onTapGesture} testID={`${testID}-tap`} maxDistance={1}>
```

**Comment by j-piasecki** [comment]
You could also use `.runOnJS(true)` modifier on the gesture object, which will result in Reanimated not being used at all.

**Comment by moribaleta** [comment]
still breaks in the latest Rn-gesture-handler 2.9.0 and rn-reanimated 2.14.0

**Comment by JackCA** [comment]
fwiw, this will also crash [Detox](https://github.com/wix/Detox) since it needs to reload the app between tests.

https://github.com/software-mansion/react-native-gesture-handler/issues/2319#issuecomment-1375255933 works for me but I'm using `runOnJs(process.env.NODE_ENV === 'development')` since I don't think reloads happen outside of development

**Comment by ajsmth** [comment]
I'm fairly certain that this somewhat hack-y workaround helps - if you move the `runOnJS` call outside the gesture and use a boolean flag to trigger it

```
  const triggerJsCall = useSharedValue(false)
  
  useDerivedValue(() => {
    if (triggerJsCall.value) {
      runOnJS(myJsCall)(myAnimatedValue.value)
      triggerJsCall.value = false
    } 
  })

```

**Comment by VictorPulzz** [comment]
Sometimes it seems to me that react native consists entirely of such hacks 😄
