### ISSUE TITLE
Button Nested Inside Another Button Clips Any (Larger) Child Views

### ISSUE THREAD

**Issue by Kesmek** [software-mansion/react-native-gesture-handler#2323]
### Description

Firstly, thanks for all the work that you've done on this library so far!

If you have a button (BaseButton/RectButton/BorderlessButton) that is nested within another button, then any child view of the nested button will be clipped to the size of the button, even if `overflow: "visible"` is set. I've attached a recording that demonstrates this. You may also check the linked repository, which shows that `overflow: "visible"` is set on every button and view.

Also, potentially related, but nesting a larger button within another smaller button will force the pressable area to be the size of the parent button. I have a feeling this is intentional, but I included it as part of the demo anyway.

https://user-images.githubusercontent.com/38704268/202300319-d781ebce-daff-4af2-b871-cba9f84b4948.mp4

For reference, this is how the third view should look, without clipping (I replaced the outer button with a view)
![image](https://user-images.githubusercontent.com/38704268/202300956-3961245e-1765-468d-a48d-2b92b37996af.png)

### Steps to reproduce

1. Create any button nested inside another button.
2. Create a view inside that nested button that is *larger* than the button
3. Observe the view being clipped (even with `overflow: "visible"`)

### Snack or a link to a repository

https://github.com/Kesmek/test/tree/nested-buttons

### Gesture Handler version

2.8.0

### React Native version

0.70.6

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

Google Pixel 7 (Android 13)

### Acknowledgements

Yes

**Comment by j-piasecki** [comment]
Hi! https://github.com/software-mansion/react-native-gesture-handler/pull/2039 fixes the clipping issue. As for the reduced pressable area, I believe this is a by-product of hit-testing the view hierarchy to determine the touch target.
