### ISSUE TITLE
Auto renderRightActions on Android when having the permission popup overlay 

### ISSUE THREAD

**Issue by anhle10051996** [software-mansion/react-native-gesture-handler#2325]
### Description

Auto renderRightActions on Android when having the permission popup overlay. When the popup go away, it comeback to normal 
<img width="355" alt="Screen Shot 2022-11-18 at 15 53 00" src="https://user-images.githubusercontent.com/88309815/202663148-32daa6af-dfcc-4663-93d2-3f7f6ee4ceba.png">

### Steps to reproduce

1. Open screen that use swipeable component
2. That screen require camera permission and show popup
3. Showing renderRightActions when the popup permission show up without swipe

### Snack or a link to a repository

https://snack.expo.io/)

### Gesture Handler version

1.10.3

### React Native version

0.63.3

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

Real device

### Device model

samsung galaxy s22

### Acknowledgements

Yes

**Comment by j-piasecki** [comment]
It seems like an identical problem to https://github.com/software-mansion/react-native-gesture-handler/issues/386 so I guess the solution would be the same. Could you please verify that the problem persists on Gesture Handler 2.8.0 (and ideally on a newer version of React Native, 0.70.x would be great)?
