### ISSUE TITLE
Gesture.Pan() events trigger very slow

### ISSUE THREAD

**Issue by Willham12** [software-mansion/react-native-gesture-handler#2343]
### Description

New Pan gesture api trigger callback very slow.

### Steps to reproduce

```js
const panGesture = Gesture.Pan()
.enabled(!isDisabled)
.maxPointers(1)
.minDistance(1)
.cancelsTouchesInView(true)
.onBegin(handleGestureEvent)
.onStart(handleGestureEvent)
.onUpdate(handleGestureEvent)
.onEnd(handleGestureEvent);

### Snack or a link to a repository

https://snack.expo.dev/

### Gesture Handler version

2.8.0

### React Native version

0.70.5

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

Real device

### Device model

Pixel 5, iPhone 

### Acknowledgements

Yes

**Comment by j-piasecki** [comment]
Could you clarify what you mean by `trigger callback very slow`? Could you prepare a snack or a repository that reproduces the problem? Do you have Reanimated installed or not?

**Comment by Willham12** [comment]
Hi, it's very hard to provide example without sharing company code. We have a infinity circular progressbar.

The old code:
```js
<PanGestureHandler
enabled={!isDisabled}
maxPointers={1}
minDist={1}
onGestureEvent={handleGestureEvent}
onHandlerStateChange={handleGestureEvent}>
...
</PanGestureHandler>
```

triggers the handleGestureEvent very fast one by one

The new code:
```js
const panGesture = Gesture.Pan()
.enabled(!isDisabled)
.maxPointers(1)
.minDistance(1)
.cancelsTouchesInView(true)
.onBegin(handleGestureEvent)
.onStart(handleGestureEvent)
.onUpdate(handleGestureEvent)
.onEnd(handleGestureEvent);
```

triggers the handleGestureEvent one by one with a delay. If you change the progressbar very fast the events triggering also after few seconds until the last event is finished

**Comment by j-piasecki** [comment]
In that case, I don't have any idea off the top of my head as to what could be causing this. It will be hard to debug without more information or reproduction.

**Comment by gregbrinker** [comment]
I'm wondering if something in your callbacks are re-rendering the entire component. If that's the case, it will be creating new Gesture handlers with each re-render.

Can you try putting a `console.log()` in the `onStart` callback? If that prints out more than once, it means your component is being re-rendered.

**Comment by MicahDavid** [comment]
I"m migrating to v2, and having the slow down issue as well. 

I've isolated the problem with changing state variables inside the callback functions. The re-rendering appears to be creating the slow down. This, however, was not an issue with version 1.  Any ideas on how to get around this?

**Comment by j-piasecki** [comment]
If you're using Reanimated I can see two potential approaches:
1. If you don't need the callbacks to be run on the UI thread, you can add `.runOnJS(true)` modifier on the configuration chain.
2. You can try wrapping the `Gesture.Pan()...` invocation inside `useMemo`, this will prevent gestures to be recreated on every render

**Comment by MicahDavid** [comment]
I am using .runOnJS(true) and I tried wrapping Gesture.Pan() inside useMemo without any discernable difference.  I don't see the delay issue when I use the legacy component approach.  

On every touch and pan gesture the state is getting updated, so lots of re-renders, but this is not an issue with the legacy approach. Any other suggestions?

**Comment by Willham12** [comment]
Still the same issue with v2.15.0. Nothing wrong on my site because it's working very well with the old api.

**Comment by Vaib215** [comment]
This issue is still there and it is causing the view to re-render multiple times

**Comment by Vaib215** [comment]
Please reopen this issue
