### ISSUE TITLE
Add timestamp

### ISSUE THREAD

**Issue by sickopickle** [software-mansion/react-native-gesture-handler#2348]
### Description

I am trying to train a neural network which takes an input of a time series to predict handwriting. I looked through the api documentation for Pan, and it doesn't seem like there's an option for getting a timestamp (Unix) at which a point was drawn. Can someone please add this, or help me incorporate this into my version? Thanks!

### Steps to reproduce

n/a

### Snack or a link to a repository

n/a

### Gesture Handler version

2.50

### React Native version

0.69.0

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

Real device

### Device model

Ipad Air 4 

### Acknowledgements

Yes

**Comment by j-piasecki** [comment]
Wouldn't calling `Date.now()` in the relevant callbacks where you're processing events suffice? The events will be processed sequentially, and if you're using Reanimated synchronously, so it should produce reliable numbers.

**Comment by sickopickle** [comment]
I'm dumb

**Comment by j-piasecki** [comment]
I assume that means that the answer above solves your problem 😄 . I'll close the issue then.
