### ISSUE TITLE
Using RefreshControl from react-native-gesture-handler on Android causes flatlist scroll to press underlying touchables

### ISSUE THREAD

**Issue by dorbaruch2** [software-mansion/react-native-gesture-handler#2351]
### Description

Hello, 

I'm encountering an issue when using the RefreshControl component exported from react-native-gesture-handler. 
I have a FlatList that renders a list of cards. The cards in the list are each wrapped with TouchableOpacity and should be clickable.
When I import both the FlatList and TouchableOpacity components from react-native-gesture-handler I am able to properly scroll the list without pressing the cards during scrolling. The problem starts when I also try to implement pull-to-refresh. Using react-native's RefreshControl causes the pull-to-refresh to not work at all. 
On the other hand, when using RefreshControl from react-native-gesture-handler the pull-to-refresh does work, but when I scroll the cards in the list keep getting pressed as well during scrolling. 

This is only an issue on Android, on iOS using RefreshControl from react-native-gesture-handler works perfectly and cards and not being pressed during scrolling.
Any help on this matter would be much appreciated.

### Steps to reproduce

1. Use FlatList from react-native-gesture-handler
2. Render TouchableOpacity from react-native-gesture-handler inside the FlatList items
3. Use RefreshControl from react-native-gesture-handler

### Snack or a link to a repository

https://snack.expo.dev/@dorkhe/gesture-handler-refresh-control-issue?platform=android

### Gesture Handler version

2.8.0

### React Native version

0.70.6

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by j-piasecki** [comment]
Hi! Could you check if the following patch solves the problem for you (and doesn't break the behavior in any way)?

```diff
diff --git a/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/core/GestureHandler.kt b/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/core/GestureHandler.kt
index 2c5f4b3..c9527fb 100644
--- a/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/core/GestureHandler.kt
+++ b/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/core/GestureHandler.kt
@@ -64,7 +64,7 @@ open class GestureHandler<ConcreteGestureHandlerT : GestureHandler<ConcreteGestu
   private var shouldCancelWhenOutside = false
   var numberOfPointers = 0
     private set
-  private var orchestrator: GestureHandlerOrchestrator? = null
+  protected var orchestrator: GestureHandlerOrchestrator? = null
   private var onTouchEventListener: OnTouchEventListener? = null
   private var interactionController: GestureHandlerInteractionController? = null
 
diff --git a/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/core/GestureHandlerOrchestrator.kt b/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/core/GestureHandlerOrchestrator.kt
index 5794462..07ac44a 100644
--- a/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/core/GestureHandlerOrchestrator.kt
+++ b/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/core/GestureHandlerOrchestrator.kt
@@ -10,7 +10,7 @@ import java.util.*
 
 class GestureHandlerOrchestrator(
   private val wrapperView: ViewGroup,
-  private val handlerRegistry: GestureHandlerRegistry,
+  public val handlerRegistry: GestureHandlerRegistry,
   private val viewConfigHelper: ViewConfigurationHelper,
 ) {
   /**
diff --git a/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/core/NativeViewGestureHandler.kt b/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/core/NativeViewGestureHandler.kt
index 8d0c862..bcf4988 100644
--- a/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/core/NativeViewGestureHandler.kt
+++ b/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/core/NativeViewGestureHandler.kt
@@ -1,10 +1,14 @@
 package com.swmansion.gesturehandler.core
 
 import android.os.SystemClock
+import android.util.Log
 import android.view.MotionEvent
 import android.view.View
 import android.view.ViewConfiguration
 import android.view.ViewGroup
+import android.widget.ScrollView
+import androidx.core.view.children
+import com.facebook.react.views.swiperefresh.ReactSwipeRefreshLayout
 import com.facebook.react.views.textinput.ReactEditText
 
 class NativeViewGestureHandler : GestureHandler<NativeViewGestureHandler>() {
@@ -72,6 +76,24 @@ class NativeViewGestureHandler : GestureHandler<NativeViewGestureHandler>() {
     when (val view = view) {
       is NativeViewGestureHandlerHook -> this.hook = view
       is ReactEditText -> this.hook = EditTextHook(this, view)
+      is ReactSwipeRefreshLayout -> this.hook = object : NativeViewGestureHandlerHook {
+        override fun wantsToHandleEventBeforeActivation(): Boolean {
+          return true
+        }
+
+        override fun handleEventBeforeActivation(event: MotionEvent) {
+          val scroll = view.children.first() as? ScrollView ?: return
+
+          val scrollHandler = orchestrator?.handlerRegistry
+            ?.getHandlersForView(scroll)
+            ?.filterIsInstance<NativeViewGestureHandler>()
+            ?.first()
+
+          if (scrollHandler != null && scrollHandler.state == 4 && scroll.scrollY > 0) {
+            fail()
+          }
+        }
+      }
     }
   }
 
```

If it helps you, I will try to figure out how to do it in a less hacky way.

**Comment by dorbaruch2** [comment]
@j-piasecki Hello! I was just wondering if you got a chance to look at the issue I mentioned. I'm a bit stuck right now and I'm trying to understand if there's a chance of this being fixed any time soon, or if I should start exploring other options.  
Thanks again!

**Comment by harrisrobin** [comment]
Hi, experiencing the same issue. This makes any <FlatList/> un-useable on android with refresh-control. 

Similar to @dorbaruch2 , I use FlatList & RefreshControl from 'react-native-gesture-handler' and this is the result:

https://user-images.githubusercontent.com/3880008/220763647-cbe4e44c-32cf-4759-a704-d2245a3c2d12.mp4

When I get rid of `RefreshControl`, this issue is gone and things work as expected:

https://user-images.githubusercontent.com/3880008/220763883-40ce8696-88b5-4c93-a20d-383784864027.mp4

**Comment by janicduplessis** [comment]
@j-piasecki I also hit this issue, the patch fixes it in my case and I haven't noticed any other broken behaviors.
