### ISSUE TITLE
[RN 0.71.0-rc.5] newArchEnabled Project with path ':ReactAndroid' could not be found in project

### ISSUE THREAD

**Issue by leotm** [software-mansion/react-native-gesture-handler#2355]
### Description

`react-native-gesture-handler` builds fine w `newArchEnabled=false` but fails w `newArchEnabled=true`

```console
FAILURE: Build failed with an exception.

* Where:
Build file '/home/runner/work/RN071RC5/RN071RC5/node_modules/react-native-gesture-handler/android/build.gradle' line: 202

* What went wrong:
A problem occurred evaluating project ':react-native-gesture-handler'.
> Project with path ':ReactAndroid' could not be found in project ':react-native-gesture-handler'.
```

nb: it's with few other libs too
- https://github.com/leotm/react-native-template-new-architecture/issues/1315

cc @tomekzaw i know you're similarly looking at adding RN 0.71.0-rc.5 support too for Reanimated + new arch 🙌 in
- https://github.com/software-mansion/react-native-reanimated/pull/3745

### Steps to reproduce

https://github.com/leotm/RN071RC5/commits/master

### Snack or a link to a repository

https://github.com/leotm/RN071RC5

### Gesture Handler version

2.8.0

### React Native version

0.71.0-rc.5

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

None

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Work in progress, see #2313 which I think is mostly ready and we can merge soon 😄

**Comment by griffinshuth** [comment]
@tomekzaw do you know if this is going to be merged soon and released?  I had to upgrade to this build to get my ios turbo module to work without realizing it was going to break my android code also.
