### ISSUE TITLE
Conflict between selectable text and react-native-gesture-handler

### ISSUE THREAD

**Issue by KennyCallegari** [software-mansion/react-native-gesture-handler#2356]
### Description

I'm creating a bottom sheet with selectable text in it. When I want to scroll my bottom sheet, the text gets selected (only on Android, it works fine in IOS). I suspect it comes from how I handle the scroll.

Here is a minimal reproduction of my component on Snack, with the bug visible (use Web Version not Android/IOS)

### Steps to reproduce

1. Scroll with your finger on text
2. The text gets selected and the component scroll
3. It shouldn't select the text

### Snack or a link to a repository

https://snack.expo.dev/@kennyledev/conflict-between-selectable-text-and-react-native-gesture-handler

### Gesture Handler version

^2.8.0

### React Native version

^0.69.5

### Platforms

Android, Web

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

None

### Build type

None

### Device

Real device

### Device model

Nokia 2

### Acknowledgements

Yes

**Comment by j-piasecki** [comment]
You should be able to solve it by wrapping the `Text` component with `NativeViewGestureHandler`. Let me know if it helps you.
