### ISSUE TITLE
Calling function in Gesture.tap not working and app crashes

### ISSUE THREAD

**Issue by AntonioLi1** [software-mansion/react-native-gesture-handler#2362]
### Description

Hi everyone,
I am trying to call a function inside a Gesture.Tap().
This is my current code:
`const doubleTap = Gesture.Tap()
    .numberOfTaps(2)
    .onStart(() => {
        //console.log(item) 
        
        console.log(selectedPostId)

        console.log('doubles')
    })
    .onEnd(() => {
        
    })
    .onFinalize(() => {
        LikePost(user.uid, selectedPostId)
    })`
If I dont have the function LikePost inside onFinalize, the code runs well, and the console logs get displayed. But running with the LikePost function, the code crashes

Is there a way to call functions inside a Gesture.Tap()?

### Steps to reproduce

1. Double tap on a flatlist item
2. Calls the function inside Gesture.Tap()
3. It should call the function but doesn't, it instead crashes

### Snack or a link to a repository

https://snack.expo.dev/qnVN0VCMG

### Gesture Handler version

2.8.0

### React Native version

0.70.6

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

Android emulator

### Acknowledgements

Yes

**Comment by j-piasecki** [comment]
Gesture Handler will detect and use Reanimated when you have it installed even without explicitly using it. In this case, the gesture callbacks are automatically workletized and run on the UI thread. You can use .runOnJS(true) modifier to prevent it from happening, i.e.:

```jsx
const doubleTap = Gesture.Tap()
  .runOnJS(true)
  .numberOfTaps(2)
  .onStart(() => {
    console.log(selectedPostId)
    console.log('doubles')
  })
  .onEnd(() => {
  })
  .onFinalize(() => {
    LikePost(user.uid, selectedPostId)
  })
```

**Comment by JeremyMeissner** [comment]
I would suggest you to at least throw an error about what's wrong. Right now, it makes the app just crash without information.
