### ISSUE TITLE
When set RCT_NEW_ARCH_ENABLED=0, I got this error('react/renderer/components/rngesturehandler/ViewProps.h' file not found)

### ISSUE THREAD

**Issue by scorpion1201** [software-mansion/react-native-gesture-handler#2372]
### Description

RCT_NEW_ARCH_ENABLED=0 pod install or pod install

Show this error message('react/renderer/components/rngesturehandler/ViewProps.h' file not found) and build failed

### Steps to reproduce

1. RCT_NEW_ARCH_ENABLED=0 pod install or pod install
2. open xcworkspace file
3. build
4. build failed.

### Snack or a link to a repository

https://github.com/scorpion1201

### Gesture Handler version

2.8.0

### React Native version

0.70.6

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by BharatBhushan2907** [comment]
upgrade to react native 0.71.1, the issue is fixed there

**Comment by j-piasecki** [comment]
I'm assuming that previously you've run the command with `RCT_NEW_ARCH_ENABLED=1`, in which case the `build` folder is not cleared. So deleting that, and possibly pods, should solve the problem.
