### ISSUE TITLE
File.exists deprecated in Podspec

### ISSUE THREAD

**Issue by billnbell** [software-mansion/react-native-gesture-handler#2373]
### Description

react-native-gesture-handler+2.8.0

need to change File.exists to File.exist in Podspec.

Thanks!

### Steps to reproduce

Ruby 3 does not like File.exists?
No others

### Snack or a link to a repository

None

### Gesture Handler version

2.8.0

### React Native version

0.69.0

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by ArunGovil** [comment]
#2371

**Comment by j-piasecki** [comment]
https://github.com/software-mansion/react-native-gesture-handler/pull/2368 which fixes this issue is included in the 2.9.0!
