### ISSUE TITLE
Execution failed for task ':react-native-gesture-handler:compileDebugKotlin'. RN 0.71.0

### ISSUE THREAD

**Issue by devoren** [software-mansion/react-native-gesture-handler#2375]
### Description

I'm facing some difficulties in building my project with the new architecture enabled and it looks like the issue comes from react-native-gesture-handler. I created new React Native app in version 0.71.0 and installed react-native-gesture-handler and react-native-reanimated. 

Here is the output of the build:
`
> Configure project :react-native-reanimated
AAR for react-native-reanimated has been found
C:\Programs\rn\TarotCardV2\node_modules\react-native-reanimated\android\react-native-reanimated-71-hermes.aar

> Task :react-native-gesture-handler:processDebugManifest
package="com.swmansion.gesturehandler" found in source AndroidManifest.xml: C:\Programs\rn\TarotCardV2\node_modules\react-native-gesture-handler\android\src\main\AndroidManifest.xml.
Setting the namespace via a source AndroidManifest.xml's package attribute is deprecated.
Please instead set the namespace (or testNamespace) in the module's build.gradle file, as described here: https://developer.android.com/studio/build/configure-app-module#set-namespace
This migration can be done automatically using the AGP Upgrade Assistant, please refer to https://developer.android.com/studio/build/agp-upgrade-assistant for more information.

> Task :react-native-gesture-handler:compileDebugKotlin FAILED
37 actionable tasks: 32 executed, 5 up-to-date
e: C:\Programs\rn\TarotCardV2\node_modules\react-native-gesture-handler\android\reanimated\src\main\java\com\swmansion\gesturehandler\ReanimatedEventDispatcher.kt: (5, 22): Unresolved reference: reanimated
e: C:\Programs\rn\TarotCardV2\node_modules\react-native-gesture-handler\android\reanimated\src\main\java\com\swmansion\gesturehandler\ReanimatedEventDispatcher.kt: (8, 33): Unresolved reference: ReanimatedModule
e: C:\Programs\rn\TarotCardV2\node_modules\react-native-gesture-handler\android\reanimated\src\main\java\com\swmansion\gesturehandler\ReanimatedEventDispatcher.kt: (12, 50): Not enough information to infer type variable T
e: C:\Programs\rn\TarotCardV2\node_modules\react-native-gesture-handler\android\reanimated\src\main\java\com\swmansion\gesturehandler\ReanimatedEventDispatcher.kt: (12, 66): Unresolved reference: ReanimatedModule
e: C:\Programs\rn\TarotCardV2\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerModule.kt: (18, 22): Unresolved reference: common
e: C:\Programs\rn\TarotCardV2\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerModule.kt: (41, 45): Unresolved reference: GestureHandlerStateManager
e: C:\Programs\rn\TarotCardV2\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerModule.kt: (432, 3): 'setGestureHandlerState' overrides nothing

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-gesture-handler:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 47s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
e: C:\Programs\rn\TarotCardV2\node_modules\react-native-gesture-handler\android\reanimated\src\main\java\com\swmansion\gesturehandler\ReanimatedEventDispatcher.kt: (5, 22): Unresolved reference: reanimated
e: C:\Programs\rn\TarotCardV2\node_modules\react-native-gesture-handler\android\reanimated\src\main\java\com\swmansion\gesturehandler\ReanimatedEventDispatcher.kt: (8, 33): Unresolved reference: ReanimatedModule
e: C:\Programs\rn\TarotCardV2\node_modules\react-native-gesture-handler\android\reanimated\src\main\java\com\swmansion\gesturehandler\ReanimatedEventDispatcher.kt: (12, 50): Not enough information to infer type variable T
e: C:\Programs\rn\TarotCardV2\node_modules\react-native-gesture-handler\android\reanimated\src\main\java\com\swmansion\gesturehandler\ReanimatedEventDispatcher.kt: (12, 66): Unresolved reference: ReanimatedModule
e: C:\Programs\rn\TarotCardV2\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerModule.kt: (18, 22): Unresolved reference: common
e: C:\Programs\rn\TarotCardV2\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerModule.kt: (41, 45): Unresolved reference: GestureHandlerStateManager
e: C:\Programs\rn\TarotCardV2\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerModule.kt: (432, 3): 'setGestureHandlerState' overrides nothing

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-gesture-handler:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 47s

    at makeError (C:\Programs\rn\TarotCardV2\node_modules\execa\index.js:174:9)
    at C:\Programs\rn\TarotCardV2\node_modules\execa\index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (C:\Programs\rn\TarotCardV2\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:85:5)
    at async Command.handleAction (C:\Programs\rn\TarotCardV2\node_modules\@react-native-community\cli\build\index.js:108:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.`

### Steps to reproduce

1. Init RN071 App
2. Install react-native-gesture-handler and react-native-reanimated libraries.
3. newArchEnabled=true
4. yarn android

### Snack or a link to a repository

https://snack.expo.dev/@devoren/tarot

### Gesture Handler version

2.9.0

### React Native version

0.71.0

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

Android emulator

### Device model

Pixel 4 API 31

### Acknowledgements

Yes

**Comment by devoren** [comment]
After using version 3.0.0.rc-10 the problem is gone

**Comment by 15bedirhan** [comment]
Updating android/build.gradle sdk versions works for me:

buildscript {
  ext {
    targetSdkVersion  '33.0.0'
    buildToolsVersion = 33
    compileSdkVersion = 33
  }
}
