### ISSUE TITLE
[TouchableOpacity]: Nested TouchableOpacity components seem to be "under" the parent TouchableOpacity

### ISSUE THREAD

**Issue by nialldbarber** [software-mansion/react-native-gesture-handler#2377]
### Description

I'm unsure if this is a bug or just a limitation of the `TouchableOpacity` component along with absolute styles/maybe more a case of my weird requirements, but! 

When a nested `TouchableOpacity` is in _another_ `TouchableOpacity`, the child elements press events are ignored. It's like there is a `zIndex` issue where only the parent press events are acknowledged. 

Here's a quick example of what I mean: 

```jsx
<TouchableOpacity
  style={{
    backgroundColor: 'pink',
    height: 100,
    zIndex: 0
  }}
  onPress={() => console.log('outer')} // <- this will log
>
  <TouchableOpacity
    style={{
      backgroundColor: 'dodgerblue',
      height: 30,
      position: 'absolute',
    }}
    onPress={() => console.log('inner')} // <- this will not log (because of the `position: absolute` change
  >
    <Text>Testing</Text>
  </TouchableOpacity>
</TouchableOpacity>
```

The implication is that a component with multiple buttons and events doesn't work as intended. 

I'll also add that the only reason I am using `react-native-gesture-handler` for `TouchableOpacity` is that I am trying to add a middle button to bottom tabs (with React Navigation) and the middle button goes _above_ the tab container. This works fine on iOS but on Android any part of the button that is above the tab container is ignored. [See issue here for context](https://github.com/facebook/react-native/issues/27232#issuecomment-615282019). 

### Steps to reproduce

1. Create a `TouchableOpacity` and then nest another `TouchableOpacity` in it
2. Make sure that the nested child is positioned absolutely
3. Log both press events and notice that the child doesn't log

### Snack or a link to a repository

https://snack.expo.dev/@salvorhardin/bold-ice-cream

### Gesture Handler version

2.5.0

### React Native version

0.67.4

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

Expo bare workflow

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iOS 13 Pro

### Acknowledgements

Yes

**Comment by j-piasecki** [comment]
It seems like the issue comes from how Gesture Handler's Touchables are implemented - there is actually an additional view in between the parent and Touchable's content. You can style that view using `containerStyle` prop and moving `position: 'absolute'` there should solve the problem.
