### ISSUE TITLE
[Android] Execution failed for task ':app:mergeLibDexDebug'. RNGH conflicts with MMKV when fabric enabled

### ISSUE THREAD

**Issue by devoren** [software-mansion/react-native-gesture-handler#2382]
### Description

I'm facing some difficulties in building my project with the new architecture enabled and disabled. I created new React Native app in version 0.71 and installed RN-GH. Please let me know if you are familiar with this issue and have resolved.

Build logs: 
ERROR:C:\Programs\...\node_modules\react-native-gesture-handler\android\build\.transforms\c4565ac0bfe4bc3cd8cc31ed594058d4\transformed\classes\classes.dex: D8: Type com.facebook.react.viewmanagers.RNGestureHandlerButtonManagerDelegate is defined multiple times: C:\Programs\...\node_modules\react-native-gesture-handler\android\build\.transforms\c4565ac0bfe4bc3cd8cc31ed594058d4\transformed\classes\classes.dex, C:\Programs\...\node_modules\react-native-mmkv\android\build\.transforms\4dc488954a239fc51aa940d208820628\transformed\classes\classes.dex
com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
Type com.facebook.react.viewmanagers.RNGestureHandlerButtonManagerDelegate is defined multiple times: C:\Programs\...\node_modules\react-native-gesture-handler\android\build\.transforms\c4565ac0bfe4bc3cd8cc31ed594058d4\transformed\classes\classes.dex, C:\Programs\...\node_modules\react-native-mmkv\android\build\.transforms\4dc488954a239fc51aa940d208820628\transformed\classes\classes.dex
        at com.android.builder.dexing.D8DexArchiveMerger.getExceptionToRethrow(D8DexArchiveMerger.java:151)
        at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:138)
        at com.android.build.gradle.internal.tasks.DexMergingWorkAction.merge(DexMergingTask.kt:859)
        at com.android.build.gradle.internal.tasks.DexMergingWorkAction.run(DexMergingTask.kt:805)
        ...
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: C:\Programs\...\node_modules\react-native-gesture-handler\android\build\.transforms\c4565ac0bfe4bc3cd8cc31ed594058d4\transformed\classes\classes.dex
...
Caused by: com.android.tools.r8.internal.f: Type com.facebook.react.viewmanagers.RNGestureHandlerButtonManagerDelegate is defined multiple times: C:\Programs\...\node_modules\react-native-gesture-handler\android\build\.transforms\c4565ac0bfe4bc3cd8cc31ed594058d4\transformed\classes\classes.dex, C:\Programs\rn\SM\node_modules\react-native-mmkv\android\build\.transforms\4dc488954a239fc51aa940d208820628\transformed\classes\classes.dex
...
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeLibDexDebug'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingTaskDelegate
   > There was a failure while executing work items
      > A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingWorkAction
         > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
           Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
           Type com.facebook.react.viewmanagers.RNGestureHandlerButtonManagerDelegate is defined multiple times: C:\Programs\...\node_modules\react-native-gesture-handler\android\build\.transforms\c4565ac0bfe4bc3cd8cc31ed594058d4\transformed\classes\classes.dex, C:\Programs\...\node_modules\react-native-mmkv\android\build\.transforms\4dc488954a239fc51aa940d208820628\transformed\classes\classes.dex

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 8s

### Steps to reproduce

1. Init app
2. yarn android
3. Execution failed for task ':app:mergeLibDexDebug'.

### Snack or a link to a repository

NA

### Gesture Handler version

2.9.0

### React Native version

0.71.0

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

Android emulator

### Device model

Pixel 4 API 31

### Acknowledgements

Yes

**Comment by sshestopalov** [comment]
@devoren, how did you solve the issue?

**Comment by devoren** [comment]
@sshestopalov after updating RN to version 0.71.1 the problem disappeared, but RNGH conflicts with react-native-MMKV

**Comment by sshestopalov** [comment]
@devoren yes, I have RNGH and react-native-mmkv in my project, that must the problem. thanks!

**Comment by dennisvk001** [comment]
Having the same conflict.

**Comment by cortinico** [comment]
Just a heads up that this caused by an underlying bug in the codegen. It's addressed here: https://github.com/facebook/react-native/pull/35992

**Comment by devoren** [comment]
After upgrading RN to [v0.71.2](https://github.com/facebook/react-native/releases/tag/v0.71.2) issue was resolved

**Comment by cortinico** [comment]
Awesome :)

**Comment by DImuthuUpe** [comment]
I still see the same error in RN 0.76.5
```
Execution failed for task ':app:mergeLibDexDebug'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingTaskDelegate > There was a failure while executing work items > A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingWorkAction > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes. Type com.facebook.react.viewmanagers.RNGestureHandlerButtonManagerDelegate is defined multiple times: /Users/dwannipu/code/nitro/react-native-pdf-viewer/example/node_modules/react-native-gesture-handler/android/build/.transforms/6a0d4d7d94a1d0819e8796603ca2fe2b/transformed/bundleLibRuntimeToDirDebug/bundleLibRuntimeToDirDebug_dex/com/facebook/react/viewmanagers/RNGestureHandlerButtonManagerDelegate.dex, /Users/dwannipu/code/nitro/react-native-pdf-viewer/android/build/.transforms/9ad0f4279f29b43220ad883470f89af0/transformed/bundleLibRuntimeToDirDebug/bundleLibRuntimeToDirDebug_dex/com/facebook/react/viewmanagers/RNGestureHandlerButtonManagerDelegate.dex 
GitHub
```
