### ISSUE TITLE
Can't install podfile with expo SDK47

### ISSUE THREAD

**Issue by yoann84** [software-mansion/react-native-gesture-handler#2386]
### Description

Hi,

I cannot build my app on iOS with the latest version of expo and rn-gesture-handler.
rn gesture-handler version : 2.8.0.
Expo version : 47.0.12 and also tried the 47.0.13.

The command **npx expo run ios** resolved with the following error :

`⚠️  Something went wrong running `pod install` in the `ios` directory.
Command `pod install` failed.
└─ Cause: Invalid `Podfile` file: 
[!] Invalid `RNGestureHandler.podspec` file: undefined method `exists?' for File:Class.

from /Users/yo/Documents/dev/Tests/test-app/node_modules/react-native-gesture-handler/RNGestureHandler.podspec:5

  
 isUserApp = File.exists?(File.join(__dir__, "..", "..", "node_modules", "react-native", "package.json"))
   if isUserApp

   from /Users/yo/Documents/dev/Tests/test-app/ios/Podfile:14
    use_expo_modules!
  config = use_native_modules!`
 

### Steps to reproduce

1. Start project with :  npx create-expo-app my-app
2.  Install RN gesture-handler  with the command:  expo install react-native-gesture-handler and import it in index.js
3. Start on simulateur with npx expo run:ios

### Snack or a link to a repository

https://github.com/yoann84/fail-gesture-handler

### Gesture Handler version

2.8.0

### React Native version

0.70.5

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by paulsizer** [comment]
I also have the same issue

**Comment by paulsizer** [comment]
@yoann84 this helped me https://github.com/software-mansion/react-native-gesture-handler/issues/2367#issuecomment-1400381877

**Comment by j-piasecki** [comment]
I see that you managed to find a solution so I'll close the issue.
