### ISSUE TITLE
Every time yarn install needs to modify it, is there a better way?

### ISSUE THREAD

**Issue by oxygen-xx** [software-mansion/react-native-gesture-handler#2387]
Thank you!

_Originally posted by @j-piasecki in https://github.com/software-mansion/react-native-gesture-handler/pull/2036#pullrequestreview-985958875_
            
react-native 0.71.1
gesture-handler 2.9.0

A similar problem exists in react-native-reanimated.
checkVersion.ts
import { version as jsVersion } from '../../../package.json';
jsVersion is assigned to package.json

**Comment by j-piasecki** [comment]
I don't quite understand the problem. What exactly do you need to modify after yarn install? If you encountered any errors could you share some more details?

If you mean that you need to modify the source code of Gesture Handler, you should use [`patch-package`](https://www.npmjs.com/package/patch-package) to do it.
