### ISSUE TITLE
react-native-gesture-handler_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.

### ISSUE THREAD

**Issue by umairkhan24** [software-mansion/react-native-gesture-handler#2399]
### Description

react-native-gesture-handler_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.

### Steps to reproduce

android studio clean
rebuild project

### Snack or a link to a repository

https://stackoverflow.com/questions/67448034/module-was-compiled-with-an-incompatible-version-of-kotlin-the-binary-version

### Gesture Handler version

2.4.1

### React Native version

0.68.5

### Platforms

Android

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by j-piasecki** [comment]
You can set what version of Kotlin Gesture Handler will use like so:
https://github.com/software-mansion/react-native-gesture-handler/blob/1bd8871185220d9c98c38e0d9821aedc16973d26/example/android/build.gradle#L9
