### ISSUE TITLE
(Web) `setImmediate` is not defined

### ISSUE THREAD

**Issue by nandorojo** [software-mansion/react-native-gesture-handler#2402]
### Description

 
<img width="817" alt="Screenshot 2023-02-01 at 3 51 28 PM" src="https://user-images.githubusercontent.com/13172299/216160709-bfcc3f35-179e-49aa-b7c2-c2154388ab57.png">

`GestureDetector` breaks on Next.js for using `setimmediate`. This same thing was fixed on Reanimated by switching to `requestAnimationFrame`

### Steps to reproduce

Use `GestureDetector` in Next.js causes this. It's an old [bug](https://github.com/expo/expo/issues/7996) from Reanimated.

The fix is here: https://github.com/software-mansion/react-native-reanimated/pull/1521/files

### Snack or a link to a repository

Let me know if this is needed.

### Gesture Handler version

2.9.0

### React Native version

RNW 0.18

### Platforms

Web

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by nandorojo** [comment]
Here's a patch for anyone who needs it:

```patch
diff --git a/node_modules/react-native-gesture-handler/lib/module/handlers/gestures/GestureDetector.js b/node_modules/react-native-gesture-handler/lib/module/handlers/gestures/GestureDetector.js
index baf1ca3..0c9f50b 100644
--- a/node_modules/react-native-gesture-handler/lib/module/handlers/gestures/GestureDetector.js
+++ b/node_modules/react-native-gesture-handler/lib/module/handlers/gestures/GestureDetector.js
@@ -23,6 +23,8 @@ import { RNRenderer } from '../../RNRenderer';
 import { isExperimentalWebImplementationEnabled } from '../../EnableExperimentalWebImplementation';
 const ALLOWED_PROPS = [...baseGestureHandlerWithMonitorProps, ...tapGestureHandlerProps, ...panGestureHandlerProps, ...panGestureHandlerCustomNativeProps, ...longPressGestureHandlerProps, ...forceTouchGestureHandlerProps, ...flingGestureHandlerProps];
 
+const scheduleUpdate = Platform.OS == 'web' ? requestAnimationFrame : setImmediate;
+
 function convertToHandlerTag(ref) {
   if (typeof ref === 'number') {
     return ref;
@@ -84,7 +86,7 @@ function attachHandlers({
   // when it's ran
 
 
-  setImmediate(() => {
+  scheduleUpdate(() => {
     if (!mountedRef.current) {
       return;
     }
@@ -100,7 +102,7 @@ function attachHandlers({
   // when it's ran
 
 
-  setImmediate(() => {
+  scheduleUpdate(() => {
     if (!mountedRef.current) {
       return;
     }
@@ -163,7 +165,7 @@ function updateHandlers(preparedGesture, gestureConfig, gesture, mountedRef) {
   // in case of external relations)
 
 
-  setImmediate(() => {
+  scheduleUpdate(() => {
     if (!mountedRef.current) {
       return;
     }
```

**Comment by j-piasecki** [comment]
Thanks for providing the fix ❤️.

**Comment by alzalabany** [comment]
diff --git a/node_modules/react-native-gesture-handler/lib/module/handlers/gestures/GestureDetector.js b/node_modules/react-native-gesture-handler/lib/module/handlers/gestures/GestureDetector.js
index baf1ca3..edc3d9a 100644
--- a/node_modules/react-native-gesture-handler/lib/module/handlers/gestures/GestureDetector.js
+++ b/node_modules/react-native-gesture-handler/lib/module/handlers/gestures/GestureDetector.js
@@ -23,6 +23,8 @@ import { RNRenderer } from '../../RNRenderer';
 import { isExperimentalWebImplementationEnabled } from '../../EnableExperimentalWebImplementation';
 const ALLOWED_PROPS = [...baseGestureHandlerWithMonitorProps, ...tapGestureHandlerProps, ...panGestureHandlerProps, ...panGestureHandlerCustomNativeProps, ...longPressGestureHandlerProps, ...forceTouchGestureHandlerProps, ...flingGestureHandlerProps];
 
+const setImmediate = global.setImmediate || (fn => setTimeout(fn, 0));
+
 function convertToHandlerTag(ref) {
   if (typeof ref === 'number') {
     return ref;


this works for me
