### ISSUE TITLE
BorderlessButton ripple not displayed on LinearGradient

### ISSUE THREAD

**Issue by Luca-Rocci** [software-mansion/react-native-gesture-handler#2411]
### Description

We have some components contained in a **LinearGradient**. 
Inside these components is a **BorderlessButton**. 
In these screens when the button is pressed the **ripple animation is not shown**. 
If we replace the LinearGradient with a **View** the **effect is shown correctly**.

### Steps to reproduce

Use react-native-reanimated (~2.12.0)
Use expo-linear-gradient (~12.0.1)
Use react-native-gesture-handler (~2.8.0)

1. Make a component with <LinearGradient> 
2. Inside insert a <BorderlessButton> whith containing <Image>
3. Run on Android and press the button 
4. The ripple animation is not shown, on closer inspection it appears to be in the background

Here is a small code sample
```
export default function Content() {
  return (
    <LinearGradient
      style={{ flex: 1 }}
      colors={[COLOR...., COLOR....]}
      start={{ x: 0.0, y: 0.3 }}
      end={{ x: 0.0, y: 1 }}
    >
      <BorderlessButton borderless={true}>
        <Image source={.....} />
      </BorderlessButton>
    </LinearGradient>
  );
}
```

### Snack or a link to a repository

https://snack.expo.dev/@luca.rocci/borderlessbutton-ripple-not-displayed-on-lineargradient-

### Gesture Handler version

2.8.0

### React Native version

0.70.5

### Platforms

Android

### JavaScript runtime

None

### Workflow

Expo managed workflow

### Architecture

None

### Build type

None

### Device

Real device

### Device model

Samsung A32, Motorola Moto G, Wiko View 3, Huawei Mate 20 pro

### Acknowledgements

Yes

**Comment by j-piasecki** [comment]
> The ripple animation is not shown, on closer inspection it appears to be in the background

That's precisely the case. The `foreground` prop will make it display in the foreground.
