### ISSUE TITLE
PanGestureHandler hitSlop dont working 

### ISSUE THREAD

**Issue by VictorPulzz** [software-mansion/react-native-gesture-handler#2419]
### Description

I working with PanGestureHandler for slider, but hitSlop dont working...
<img width="362" alt="image" src="https://user-images.githubusercontent.com/23406402/219380824-96ff1225-6903-4359-9e71-2bd7b887be33.png">

### Steps to reproduce

1. Setup react native project
2. Add react-native-gesture-handler
3. Add PanGestureHandler with handler and hitSlop
Check results

### Snack or a link to a repository

-

### Gesture Handler version

~2.7.1

### React Native version

0.70.6

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 11 ios 15.2

### Acknowledgements

Yes

**Comment by j-piasecki** [comment]
Keep in mind that `hitSlop` property is intended to reduce the hit area of the gesture, not increase it. There's more information [in the docs](https://docs.swmansion.com/react-native-gesture-handler/docs/gesture-handlers/api/common-gh#hitslop) about it.

I cannot say much more without reproduction, as I'm missing the context here.

**Comment by lukebars** [comment]
@j-piasecki are there any posibilities to increase the hit area with the current api?

**Comment by imorenodev** [comment]
> @j-piasecki are there any posibilities to increase the hit area with the current api?

one solution I found was to wrap the element in a parent Animated.View (with an invisible background) and increase the size of the parent container to get the increased gesture target area I am looking for.

https://snack.expo.dev/@imorenodev/fling-gesture-with-padding
