### ISSUE TITLE
child.isClassAccessorProperty is not a function

### ISSUE THREAD

**Issue by mertuner** [software-mansion/react-native-gesture-handler#2421]
### Description

Hi,
 I've been recently getting this error using the gesture handler with the expo. 
"Failed building JavaScript bundle.
node_modules/react-native-gesture-handler/src/handlers/gestures/gesture.ts: /Users/username/Desktop/Work/project/node_modules/react-native-gesture-handler/src/handlers/gestures/gesture.ts: child.isClassAccessorProperty is not a function"

Not getting any incompatibility issue warning. Even tried to downgrade the gesture-handler version but, it did not work out.

Here is my package.json

  "dependencies": {
    "@aws-sdk/client-cognito-identity": "^3.213.0",
    "@aws-sdk/client-s3": "^3.213.0",
    "@aws-sdk/credential-provider-cognito-identity": "^3.213.0",
    "@react-native-async-storage/async-storage": "~1.17.3",
    "@react-native-community/cli-debugger-ui": "^10.0.0",
    "@react-native-community/netinfo": "9.3.5",
    "@react-navigation/bottom-tabs": "^6.5.5",
    "@react-navigation/native": "^6.1.4",
    "@react-navigation/stack": "^6.3.14",
    "@redux-devtools/extension": "^3.2.3",
    "aws-amplify": "^5.0.3",
    "axios": "^0.27.2",
    "expo": "^47.0.13",
    "expo-status-bar": "~1.4.2",
    "lottie-react-native": "5.1.4",
    "react": "18.1.0",
    "react-dom": "18.1.0",
    "react-native": "0.70.5",
    "react-native-animated-loader": "^1.0.0",
    "react-native-circular-progress-indicator": "^4.4.0",
    "react-native-color": "0.0.10",
    "react-native-config": "^1.5.0",
    "react-native-onboarding-swiper": "^1.2.0",
    "react-native-reanimated": "~2.12.0",
    "react-native-safe-area-context": "4.4.1",
    "react-native-screens": "~3.18.0",
    "react-native-svg": "13.4.0",
    "react-native-ui-lib": "^6.21.2",
    "react-native-web": "~0.18.9",
    "react-navigation-header-buttons": "^10.0.0",
    "react-redux": "^8.0.2",
    "redux": "^4.2.0",
    "redux-devtools-extension": "^2.13.9",
    "redux-thunk": "^2.4.1",
    "react-native-gesture-handler": "~2.8.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9"
  },

Any help would be appreciated.

### Steps to reproduce

1- expo start ios
2- Getting this error when building.

### Snack or a link to a repository

*

### Gesture Handler version

~2.8.0

### React Native version

0.70.5

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by j-piasecki** [comment]
I've tried to reproduce it on a freshly created Expo app with the same dependencies as you've listed, but I didn't get the error. Could you prepare a repository with a reproduction so I can look into it?
