### ISSUE TITLE
Does not build on react-native 0.71.3 but actually works on 0.71.2

### ISSUE THREAD

**Issue by lucaswitch** [software-mansion/react-native-gesture-handler#2425]
### Description

Gesture handler does not build on new react-native version 0.71.3
Details:
Hermes enabled
Fabric new arch enabled
Error stack trace following:
```
CMake Error at /Volumes/D/workspace/Projects/rnproject/android/app/build/generated/rncli/src/main/jni/Android-rncli.cmake:6 (add_subdirectory):
    add_subdirectory given source
    "/Volumes/D/workspace/Projects/rnproject/node_modules/react-native-gesture-handler/android/build/generated/source/codegen/jni/"
    which is not an existing directory.
  Call Stack (most recent call first):
    /Volumes/D/workspace/Projects/rnproject/node_modules/react-native/ReactAndroid/cmake-utils/ReactNative-application.cmake:106 (include)
    CMakeLists.txt:31 (include)
```

### Steps to reproduce

1. Install latest version of react-native with create-app, current version 0.71.3
2. Install react-native-gesture-handler version 2.9.0
3. Build de project

### Snack or a link to a repository

Just follow the steps to reproduce

### Gesture Handler version

2.9.0

### React Native version

0.71.3

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

Android emulator

### Device model

Anyone with sdk 30

### Acknowledgements

Yes

**Comment by lucaswitch** [comment]
The app builds when newArch is disabled, maybe some issue with 0.70.x and react-native-gesture-handler

**Comment by j-piasecki** [comment]
I created the fresh React Native 0.71.3 app and added `react-native-gesture-handler` but the app was built without any problems. Could you prepare a repository that would allow to reproduce the problem easily?

**Comment by lucaswitch** [comment]
Ok, i will.

**Comment by AdamSheaHewett** [comment]
Problem still exists
