### ISSUE TITLE
Execution failed for task ':react-native-gesture-handler:buildCMakeRelWithDebInfo[arm64-v8a]'

### ISSUE THREAD

**Issue by Pcpkomputer** [software-mansion/react-native-gesture-handler#2428]
### Description

Just trying to install react-native-reanimated 3.0.0-rc10 and react-native-gesture-handler 2.9.0 with newArchEnabled: true in android, encountering this issue

<img width="1147" alt="Screenshot 2023-03-01 at 16 48 38" src="https://user-images.githubusercontent.com/13756456/222104262-b8fb799f-4e0c-410e-867d-fe737d3dcaf9.png">

Dependencies

```
{
  "name": "my-react-app",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "expo": "~48.0.4",
    "expo-splash-screen": "~0.18.1",
    "expo-status-bar": "~1.4.4",
    "react": "18.2.0",
    "react-native": "0.71.3",
    "react-native-gesture-handler": "^2.9.0",
    "react-native-reanimated": "^3.0.0-rc.10"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
  "private": true
}

```

### Steps to reproduce

1. npx create-react-native-app --use-npm
2. npm install react-native-reanimated@next 
3. npm install react-native-gesture-handler
4. set jsEngine to hermes
5. set newArchEnabled true in gradle.properties
6. eas build --platform android --profile preview

### Snack or a link to a repository

https://github.com/Pcpkomputer/rn-bug1

### Gesture Handler version

2.9.0

### React Native version

0.71.3

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

Expo bare workflow

### Architecture

Fabric (New Architecture)

### Build type

Release mode

### Device

Real device

### Device model

Xiaomi Redmi Note 8

### Acknowledgements

Yes

**Comment by kylewang4929** [comment]
same issue

**Comment by j-piasecki** [comment]
Could you check if the following patch https://gist.github.com/j-piasecki/57d9d6d659cbc7380ee0b0beb7e6922a works for you?

**Comment by Pcpkomputer** [comment]
> Could you check if the following patch https://gist.github.com/j-piasecki/57d9d6d659cbc7380ee0b0beb7e6922a works for you?

Actually after I try to build my repro in my local machine, it's build sucessfully, even if I use your patch it showing error. I think the problem is from EAS environment for building android, I don't know exactly why, but it's build successfuly in my local machine. Maybe I can close this issue

**Comment by oscarcornejo** [comment]
I have the same problem, I'm working with this setup:

buildToolsVersion="33.0.0"
minSdkVersion = 21
compileSdkVersion = 33
targetSdkVersion = 33

"react-native-gesture-handler": "^2.9.0",
"react-native-reanimated": "^3.0.2",
"react": "18.2.0",
"react-native": "0.71.4",

PD: I am using a mackbook M1

**Comment by 7dp** [comment]
> Could you check if the following patch https://gist.github.com/j-piasecki/57d9d6d659cbc7380ee0b0beb7e6922a works for you?

Encountering the same issue, solved by using this fix.
Thanks! @j-piasecki
