### ISSUE TITLE
Android build fails with Gradle Configuration Cache

### ISSUE THREAD

**Issue by pvegh** [software-mansion/react-native-gesture-handler#2449]
### Description

Using Configuration Cache our build seems to fail with this error:

```
Could not evaluate onlyIf predicate for task ':react-native-gesture-handler:assertNoMultipleInstances'.
> Could not evaluate spec for 'Task satisfies onlyIf closure'.

```

The problem seems to be something in Gesture Handler not being correctly defined around here:

tasks.preBuild {
//    dependsOn assertionTask // this fixes the problem so it must be with assertionTask not being compatible
}

### Steps to reproduce

1. enable CC with:
org.gradle.unsafe.configuration-cache=true
2. Run app in Android Studio

And the first launch seems to work, but the second launch throws above exception. So when the config cache would be used the problem occures.

### Snack or a link to a repository

cant

### Gesture Handler version

2.9.0

### React Native version

0.71.4

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by pvegh** [comment]
Sorry I can't build a reproducer. It is as simple as enable build cache and keep using a project with RNGH.
Also using Gradle 7.6, it might help.

**Comment by artemis-prime** [comment]
The workaround is just to delete the cache.  I'm not sure what a fix would mean.

**Comment by pvegh** [comment]
Deleting the config cache defies the purpose of enabling it, so it's not an option.

The fix will be a mix of using APIs that supported in that environment, supporting the caching logic decide what can be reused and what needs to be re-run, and to stop using things that completely break the build when CC is enabled.

As a first step changes should be made to simply not break the whole build (by the looks of it it's what #2453 is doing).
Later some actual caching could be implemented, if applicable, to save time for every execution.

Documentation:
https://docs.gradle.org/current/userguide/configuration_cache.html
