### ISSUE TITLE
Add support for Gradle 8

### ISSUE THREAD

**Issue by pvegh** [software-mansion/react-native-gesture-handler#2458]
### Description

Kotlin 1.6 needs to be updated to 1.8 in react-native-gesture-handler.

Currently Gradle errors out with this module being incompatible with 1.8 which is needed for Gradle 8.

Gradle 8 is needed for current stable version of Android Studio Flamingo's Android Gradle Plugin

Please release a version with Kotlin 1.8 soon

### Steps to reproduce

Upgrade to gradle 8.0 in the wrapper and build

### Snack or a link to a repository

none

### Gesture Handler version

2.9.0

### React Native version

0.71.4

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by j-piasecki** [comment]
In the meantime, you can use `kotlinVersion` property in your top-level `build.gradle`, like so: https://github.com/software-mansion/react-native-gesture-handler/blob/4a223c2b993c80ad4d3d216745da3e7f7a808342/example/android/build.gradle#L9

**Comment by pvegh** [comment]
yep I think it worked I'm just not completely finished to report back. Our migration path to Gradle 8 and Java 17 was a little bumpy this time..
