### ISSUE TITLE
podspec file should not search entire repo for a react-native-gesture-handler/package.json

### ISSUE THREAD

**Issue by edhemphill** [software-mansion/react-native-gesture-handler#2459]
### Description

The following code in the .podspec file results in a bogus error being called in some situations:

`  
libInstances = %x[find ../../-name "package.json" | grep "/react-native-gesture-handler/package.json" | grep -v "/.yarn/"]
`

The issue here is when there may be another copy of react-native-gesture-handler which is entirely unrelated to the react native app build.

For instance in our CI build we place yarn's cache locally in an unversioned, hidden folder at the top level of the project folder using yarn --cache-folder. But of course there could be any reason.

Generally I don't feel like this code should be there at all. The module has no idea where it might be placed, so having a script in a podspec file which just walks through every folder two levels up may not be the best approach.

Recommend:

`  
libInstances = %x[find ../node_modules -name "package.json" | grep "/react-native-gesture-handler/package.json" | grep -v "/.yarn/"]
`

or to just not do it at all.

### Steps to reproduce

Randomly put react-native-gesture-handler somewhere else besides node_modules, for instance putting your yarn cache locally in your folder

### Snack or a link to a repository

none

### Gesture Handler version

2.9.0

### React Native version

0.71

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by m-bert** [comment]
Hi @edhemphill! From what I can see, the line that you're referring to was deleted in #2569. We also introduced some changes to our `podspec` recently. I'm closing this issue, but if you see something that should be changed feel free to reopen it.
