### ISSUE TITLE
Bleeding edge failing to assembleRelease

### ISSUE THREAD

**Issue by djMax** [software-mansion/react-native-gesture-handler#2469]
### Description

I am on the bleeding edge here (new project, and I don't want to have to rework too much to get Fabric and all the things that will be normal months from now when the project is ready). Build works fine and runs in the emulator just fine, but I can't run Fastlane (or gradlew assembleRelease). It complains like so:

```
❯ ./gradlew assembleRelease -p .

> Configure project :react-native-gesture-handler
codegenDir: /Users/memetral/dev/monorepo/mobile-apps/node_modules/react-native-codegen
reactNativeDir: /Users/memetral/dev/monorepo/mobile-apps/node_modules/react-native

> Configure project :react-native-reanimated
No AAR for react-native-reanimated found. Attempting to build from source.
Android gradle plugin: 7.4.2
Gradle: 8.0.1
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Task :react-native-gesture-handler:buildCodegenCLI FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-gesture-handler:buildCodegenCLI'.
> A problem occurred starting process 'command '/Users/memetral/dev/monorepo/mobile-apps/node_modules/react-native-codegen/scripts/oss/build.sh''
``` 

That file (scripts) doesn't exist, and react-native-codegen is not even a dependency or a real module in my project. Any ideas?

### Steps to reproduce

create react-native app, upgrade all the things. I know, this is a terrible repro, and I am getting the minimal repo checked in.

### Snack or a link to a repository

https://github.com/djMax/rn-monorepo-fabric

### Gesture Handler version

2.9.0

### React Native version

0.72.0-rc.1

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Release mode

### Device

Android emulator

### Acknowledgements

Yes

**Comment by djMax** [comment]
So, adding a top level dep to react-native-codegen does get past THIS error, I think. Instead I get:

```
2023-04-28T08:26:04.784-0400 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   /Users/memetral/.gradle/caches/transforms-3/3db8a0b0de0d827e0583d0d74395a83a/transformed/jetified-react-android-0.72.0-rc.1-release/prefab/modules/react_nativemodule_core/include/folly/small_vector.h:35:10: fatal error: 'boost/mpl/count.hpp' file not found
```

**Comment by djMax** [comment]
A little further...

```
brew install boost
export CPLUS_INCLUDE_PATH=/opt/homebrew/Cellar/boost/1.81.0_1/include
```

```
> Task :react-native-safe-area-context:generateCodegenArtifactsFromSchema FAILED
/Users/memetral/app/mobile-apps/node_modules/@react-native/codegen/lib/generators/modules/GenerateModuleH.js:249
  return Object.keys(aliasMap)
                ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at createStructsString (/Users/memetral/app/mobile-apps/node_modules/@react-native/codegen/lib/generators/modules/GenerateModuleH.js:249:17)
```

**Comment by djMax** [comment]
I also noticed that safe-area-context is using `@react-native/codegen` instead of `react-native-codegen`. I assume only one is right, and likely the former.

**Comment by j-piasecki** [comment]
You're overriding the `codegenDir` for Gesture Handler and pointing it to the wrong directory here: https://github.com/djMax/rn-monorepo-fabric/blob/main/patient-app/app/android/build.gradle#L28.
