### ISSUE TITLE
Expo managed app crashes on simulator

### ISSUE THREAD

**Issue by txnico** [software-mansion/react-native-gesture-handler#2473]
### Description

I've updated an Expo managed app from Expo sdk 45 to sdk 48 and while running it the app is now crashing as soon as it's loading. 

I've replaced my app code with just a Hello World code and just by adding the import 'react-native-gesture-handler'; the behavior is then seen. 

### Steps to reproduce

1. Install: 
`npx expo install react-native-gesture-handler`

2. Install boiler plate Hello World code to App.js:

```
import 'react-native-gesture-handler';
import { StyleSheet, Text, View } from 'react-native';

export default function App() {
  return (
    <View style={styles.container}>
      <Text>Hello world</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```
3. Build app
`npx expo run:ios`

4. Observe crash log

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x00005ffeb446bd5a   x5: 0x000000000000001a   x6: 0x0000000000000020   x7: 0x000060000214c2a0
    x8: 0x0000000105344240   x9: 0x7bca4c63b6d247e7  x10: 0x72656b6361706e55  x11: 0x656c6b726f772820
   x12: 0x6b726f7728207265  x13: 0x373936335f74656c  x14: 0x3039303233393738  x15: 0x2931363a39313a31
   x16: 0x0000000000000148  x17: 0x0000000065800000  x18: 0x0000000000000000  x19: 0x0000000000000006
   x20: 0x0000000105344240  x21: 0x0000000000000103  x22: 0x0000000105344320  x23: 0x0000000000000114
   x24: 0x0000600001f5d740  x25: 0x0000600001f5d740  x26: 0x0000000000000000  x27: 0x0000000000000000
   x28: 0x0000000000000000   fp: 0x000000016d5b5000   lr: 0x00000001b183812c
    sp: 0x000000016d5b4fe0   pc: 0x00000001b17e3fa8 cpsr: 0x40001000
   far: 0x000000014f70407c  esr: 0x56000080  Address size fault

### Snack or a link to a repository

none

### Gesture Handler version

2.9.0

### React Native version

0.71.7

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

Expo managed workflow

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by j-piasecki** [comment]
I wasn't able to reproduce the error on SDK 48, could you prepare a repository with a reproduction?

**Comment by MatrixTurtle269** [comment]
I have a similar issue, although mine only happens with the `GestureHandlerRootView` component.

THIS runs just fine:
```javascript
import React from "react";
import { View, Text } from "react-native";
import { GestureHandlerRootView } from "react-native-gesture-handler";

const App = () => {
  return (
    <View style={{ flex: 1 }}>
      <Text>Awesome</Text>
    </View>
  );
};

export default App;
```

But as soon as I wrap the return statement in `<GestureHandlerRootView>`, Expo Go crashes as soon as I load the app up, without even any errors: 
```javascript
import React from "react";
import { View, Text } from "react-native";
import { GestureHandlerRootView } from "react-native-gesture-handler";

const App = () => {
  return (
    <GestureHandlerRootView>
      <View style={{ flex: 1 }}>
        <Text>Awesome</Text>
      </View>
    </GestureHandlerRootView>
  );
};

export default App;
```

There are no other components other than `App.tsx` in my project.

Installed packages:
├── @babel/core@7.21.8
├── @gorhom/bottom-sheet@4.4.6
├── @types/react@18.0.38
├── expo-status-bar@1.4.4
├── expo@48.0.16
├── react-native-gesture-handler@2.9.0
├── react-native-reanimated@2.14.4
├── react-native@0.71.7
├── react@18.2.0
└── typescript@4.9.5

**Comment by edmsamuel** [comment]
x2 on sdk 49, on physical device :(

**Comment by skdev24** [comment]
+1 happening for me too. It was random, didn't know why in SDK 48. When the app reloads it will crash.

**Comment by edmsamuel** [comment]
i haved to downgrade to sdk48, this happend when import at the top of begin file, even with overide or resolutions for dependencies on package.json file.

**Comment by m-bert** [comment]
Hi! @MatrixTurtle269 I've just checked your configuration and it works fine on Expo Go. The problem in my case was not crash, but that nothing was visible. I've removed `<View>` tag, since `<GestureHandlerRootView>` is enough.

@edmsamuel, I've run app with SDK 49 in Expo Go and it was ok, did you also use Expo Go?

As for @txnico, I'll check on that on iOS simulator tomorow.

**Comment by m-bert** [comment]
Okay, @txnico  I've just checked that on simulator and it also works. In that case, could you provide repository with reproduction?
