### ISSUE TITLE
React native gesture handler version 210.0 making the build crash on npx react native run android. The build was running fine on react-native-gesture-handler@2.9.0.

### ISSUE THREAD

**Issue by A4Dragon** [software-mansion/react-native-gesture-handler#2480]
### Description

When i upgraded the version to 2.10.0 the build is getting crashed giving the error.
![image](https://github.com/software-mansion/react-native-gesture-handler/assets/116946817/465deeb7-781f-42e6-a948-01d89a0df9bf)

### Steps to reproduce

just create a project with react native version - 0.70.5 and with react native gesture handler version 2.10.0
The build is getting crashed with command npx react-native-run-android

### Snack or a link to a repository

https://bitbucket.org/supplymint-mobile/supplymintmobilesales/src/master/

### Gesture Handler version

2.10.0

### React Native version

0.70.5

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

None

### Architecture

None

### Build type

Debug mode

### Device

Real device

### Device model

Vivo v25 pro, Nothing Phone 1

### Acknowledgements

Yes

**Comment by A4Dragon** [comment]
Sir this is a private repo i can't provide a link to the repo just create a
new project and implement it
Thank You

**Comment by BishalftSaikia** [comment]
**Update your sdk version to 33** https://stackoverflow.com/questions/75158364/error-cannot-find-symbol-if-build-version-sdk-int-build-version-codes-tirami

**Comment by jacobira** [comment]
I am currently on Android SDK 33 and I still see this issue occurring.

**Comment by BishalftSaikia** [comment]
it was fixed as soon as i upgrade my sdk
