### ISSUE TITLE
Multiple instances of Gesture Handler were detected but they are all the same version

### ISSUE THREAD

**Issue by jahirfiquitiva** [software-mansion/react-native-gesture-handler#2481]
### Description

The project is a monorepo, and the android build fails because `Multiple instances of Gesture Handler were detected` but they are all the same version:

```
⇥  yarn why react-native-gesture-handler
├─ @company/aa@workspace:apps/AA
│  └─ react-native-gesture-handler@npm:2.9.0 [08883] (via npm:^2.9.0 [08883])
│
├─ @company/cv@workspace:packages/cv [b5f62]
│  └─ react-native-gesture-handler@npm:2.9.0 [08883] (via npm:^2.9.0 [08883])
│
├─ @company/na@workspace:apps/NA
│  └─ react-native-gesture-handler@npm:2.9.0 [08883] (via npm:^2.9.0 [08883])
│
├─ @company/nyl@workspace:apps/NYL
│  └─ react-native-gesture-handler@npm:2.9.0 [08883] (via npm:^2.9.0 [08883])
│
└─ @company/web-portal@workspace:websites/web-portal
   └─ react-native-gesture-handler@npm:2.9.0 [08883] (via npm:^2.9.0 [08883])
```

The actual mobile apps are the ones under `apps/` folder. And I'm only running one of them.

Please help me out resolving the issue.

Thanks!

### Steps to reproduce

Unsure

### Snack or a link to a repository

Can't share

### Gesture Handler version

2.9.0

### React Native version

0.71.7

### Platforms

Android

### Acknowledgements

Yes

**Comment by MissingCorner-HaoPhan** [comment]
Getting the same on Android, version 2.10.1

**Comment by MissingCorner-HaoPhan** [comment]
I migrated from @nrwl v14 to nx 16.2.2, and it fixed the error. Hope it helps you.

**Comment by enchorb** [comment]
I'm still getting the issue on `16.3.1`. For whatever reason gesture handler versions after 2.0.9 count symlinks as multiple versions

It counts symlinks as a multiple version now which many monorepo providers do (ie. Nrwl).

```
* What went wrong:
Execution failed for task ':react-native-gesture-handler:assertNoMultipleInstances'.
> 
  [react-native-gesture-handler] Multiple versions of Gesture Handler were detected. Only one instance of react-native-gesture-handler can be installed in a project. You need to resolve the conflict manually. Check out the documentation: https://docs.swmansion.com/react-native-gesture-handler/docs/troubleshooting#multiple-instances-of-gesture-handler-were-detected 
  
  Conflict between: 
  - /Users/name/Documents/Code/company/apps/mobile/app_name/node_modules/react-native-gesture-handler
  - /Users/name/Documents/Code/company/node_modules/react-native-gesture-handler
```

**Comment by enchorb** [comment]
Same issue also happens for Reanimated: https://github.com/software-mansion/react-native-reanimated/issues/4583

**Comment by hromovp** [comment]
Hello! Got this issue today, fixed refering to [original documentation](https://docs.swmansion.com/react-native-gesture-handler/docs/troubleshooting/#multiple-versions-of-gesture-handler-were-detected)

> If you use yarn you should add [resolution property](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/).
> 
```
"resolutions": {
   "react-native-gesture-handler": <Gesture Handler version>
 }
```
> 
> If you use npm you should add [overrides property](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides).
> 
```
 "overrides": {
   "react-native-gesture-handler": <Gesture Handler version>
 }
```
> 
> After that you need to run your package manager again
> 
` yarn`

**Comment by airowe** [comment]
Any fix for this?

**Comment by j-piasecki** [comment]
> It counts symlinks as a multiple version now which many monorepo providers do (ie. Nrwl).

That's weird, since we're explicitly excluding symlinks in that check:
https://github.com/software-mansion/react-native-gesture-handler/blob/04ed17e8b351098271f2ab8e40c8e91da3b087ab/android/build.gradle#L118

But since it clearly doesn't work you can add `disableMultipleInstancesCheck=true` to `gradle.properties` before we most likely remove the check entirely in the future release.

**Comment by eeshankeni** [comment]
Adding the following to package.json seems to have fixed it for me
resolutions": {
  "react-native-gesture-handler": "2.12.1"
}

https://docs.swmansion.com/react-native-gesture-handler/docs/next/troubleshooting/#:~:text=Multiple%20instances%20of%20Gesture%20Handler%20were%20detected%E2%80%8B&text=It%20can%20occur%20when%20some,install%20the%20same%20Native%20Module.

**Comment by XantreGodlike** [comment]
I fallen into the same issue with pnpm

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\Projects\work\Oone.World\trucks-driver-app\node_modules\react-native-gesture-handler\android\build.gradle' line: 149

* What went wrong:
Execution failed for task ':react-native-gesture-handler:assertNoMultipleInstances'.
>
  [react-native-gesture-handler] Multiple versions of Gesture Handler were detected. Only one instance of react-native-gesture-handler can be installed in a project. You need to resolve the conflict manually. Check out the documentation: https://docs.swmansion.com/react-native-gesture-handler/docs/troubleshooting#multiple-instances-of-gesture-handler-were-detected

  Conflict between:
  - D:\Projects\work\Oone.World\trucks-driver-app\node_modules\.pnpm\@gorhom+bottom-sheet@4.4.6_@types+react@18.2.21_react-native-gesture-handler@2.12.1_react-nat_bud27r74by5byjvgdzy5yfaflm\node_modules\react-native-gesture-handler\package.json
  - D:\Projects\work\Oone.World\trucks-driver-app\node_modules\.pnpm\@react-navigation+stack@6.3.16_patch_hash=kb34d3crim3jmxzmieay5kcery_@react-navigation+native_5ouqv6i3sxcsfh4nktamvqrqoa\node_modules\react-native-gesture-handler\package.json
  - D:\Projects\work\Oone.World\trucks-driver-app\node_modules\.pnpm\react-native-gesture-handler@2.12.1_react-native@0.72.4_react@18.2.0\node_modules\react-native-gesture-handler\package.json
  - D:\Projects\work\Oone.World\trucks-driver-app\node_modules\react-native-gesture-handler\package.json

**Comment by XantreGodlike** [comment]
This was solved by setting this in .npmrc, but it just workaround
```
shamefully-hoist=true
node-linker=hoisted
```

**Comment by 1mehdifaraji** [comment]
First delete `node_modules` and then in `package.json` add the following :

```
If NPM
"overrides": {
  "react-native-gesture-handler": <Gesture Handler version>
}

If Yarn
"resolutions": {
  "react-native-gesture-handler": <Gesture Handler version>
}
```

Then do `yarn install` and the problem will go away .

**Comment by AmitHBhagat** [comment]
> First delete `node_modules` and then in `package.json` add the following :
> 
> ```
> If NPM
> "overrides": {
>   "react-native-gesture-handler": <Gesture Handler version>
> }
> 
> If Yarn
> "resolutions": {
>   "react-native-gesture-handler": <Gesture Handler version>
> }
> ```
> 
> Then do `yarn install` and the problem will go away .

Thanks, it helped, docs for more details are here https://docs.swmansion.com/react-native-gesture-handler/docs/guides/troubleshooting/
