### ISSUE TITLE
Issue with the package setup

### ISSUE THREAD

**Issue by Srezzx** [software-mansion/react-native-gesture-handler#2484]
### Description

Hey guys, I was working on a bare react-native project and came across this issue after doing - 'yarn android'
I have checked all the links on the internet but couldn't find a solution for it, I have tried upgrading the packages but still couldn't resolve the issue. 
My package versions are - 

"react-native" : 0.64.2
"react-native-gesture-handler" - 2.10.0
"react-navigation": "^4.4.4",
"@react-navigation/bottom-tabs": "5.11.11",
"@react-navigation/material-top-tabs": "5.3.15",
"@react-navigation/native": "5.9.4",
"@react-navigation/stack": "5.14.5",

![1](https://github.com/software-mansion/react-native-gesture-handler/assets/57859035/afb0f97a-359a-4711-8b3c-44e5e3b5f440)

<img width="957" alt="image" src="https://github.com/software-mansion/react-native-gesture-handler/assets/57859035/4b18bdca-ef8e-4fe8-b9f5-f12ad34030a8">

This was the line of code that was producing the issue, I somehow managed to run the app by removing lines 199-204 entirely, app seems to run perfectly but just doesn't seem right. Can anyone suggest to me how to proceed?

Thank you in advance :)

### Steps to reproduce

1. yarn install
2. yarn android
3. Open the emulator after build successful

### Snack or a link to a repository

https://github.com/wkndinc/party-app-rn

### Gesture Handler version

2.10.0

### React Native version

0.64.2

### Platforms

Android

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

None

### Build type

Debug mode

### Device

Android emulator

### Acknowledgements

Yes

**Comment by Sagar6228** [comment]
> ### Description
> Hey guys, I was working on a bare react-native project and came across this issue after doing - 'yarn android' I have checked all the links on the internet but couldn't find a solution for it, I have tried upgrading the packages but still couldn't resolve the issue. My package versions are -
> 
> "react-native" : 0.64.2 "react-native-gesture-handler" - 2.10.0 "react-navigation": "^4.4.4", "@react-navigation/bottom-tabs": "5.11.11", "@react-navigation/material-top-tabs": "5.3.15", "@react-navigation/native": "5.9.4", "@react-navigation/stack": "5.14.5",
> 
> ![1](https://user-images.githubusercontent.com/57859035/239053273-afb0f97a-359a-4711-8b3c-44e5e3b5f440.png)
> 
> <img alt="image" width="957" src="https://user-images.githubusercontent.com/57859035/239054053-4b18bdca-ef8e-4fe8-b9f5-f12ad34030a8.png">
> This was the line of code that was producing the issue, I somehow managed to run the app by removing lines 199-204 entirely, app seems to run perfectly but just doesn't seem right. Can anyone suggest to me how to proceed?
> 
> Thank you in advance :)
> 
> ### Steps to reproduce
> 1. yarn install
> 2. yarn android
> 3. Open the emulator after build successful
> 
> ### Snack or a link to a repository
> https://github.com/wkndinc/party-app-rn
> 
> ### Gesture Handler version
> 2.10.0
> 
> ### React Native version
> 0.64.2
> 
> ### Platforms
> Android
> 
> ### JavaScript runtime
> None
> 
> ### Workflow
> React Native (without Expo)
> 
> ### Architecture
> None
> 
> ### Build type
> Debug mode
> 
> ### Device
> Android emulator
> 
> ### Device model
> _No response_
> 
> ### Acknowledgements
> Yes

I am also facing the same issue 

In My ongoing project it is shows such error

How I suppose to resolve this issue

**Comment by j-piasecki** [comment]
You should be fine removing these lines as they basically don't do anything unless you're using the new architecture, and you're not doing it.

That said, it's weird that your app works after removing them since `queueMicrotask` is used in more places, not only there.

**Comment by rayjackson13** [comment]
Hi! This issue also happened to me on Android after upgrading "react-native-gesture-handler" from v2.9.0 to v2.11.0.

**Comment by iamsolankiamit** [comment]
This happens only when hermes is disabled as `queueMicrotask` is only available in hermes

**Comment by m-bert** [comment]
Hi @Srezzx! I've just created [this PR](https://github.com/software-mansion/react-native-gesture-handler/pull/2612). Could you please check if it solves this issue?
