### ISSUE TITLE
Default compileSdkVersion causes compilation failure 

### ISSUE THREAD

**Issue by przybylski** [software-mansion/react-native-gesture-handler#2486]
### Description

RNGestureHandlerButtonViewManager is using TIRAMISU version code check to determine the value clamp.
Yet `compileSdkVersion` in the main gradle file targets SDK 28, which doesn't have this value.
If the user is targeting pre-33 SDK compilation fails.
`compileSdkVersion` is deprecated and has issues when using gradle with Kotlin scripting language, which prevents overriding.

### Steps to reproduce

1. Create app that uses compileSdkVersion 28
2. Build

### Snack or a link to a repository

n/a

### Gesture Handler version

2.10.1

### React Native version

0.71.6

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by valmirw** [comment]
+ here:

with the following versions:
`compileSdkVersion = 33
targetSdkVersion = 33
`

**Comment by bradydoll** [comment]
This looks to be the same issue as #2480

**Comment by gabrielsalvi** [comment]
I encountered a similar problem while working on a project, where I had set `compileSdkVersion = 31` and `targetSdkVersion = 31` in the buildscript of my build.gradle file. In order to resolve this issue, I upgraded the SDK versions to the latest ones and updated the versions of the sdk in the build.gradle file as bellow:

```
compileSdkVersion = 33 
targetSdkVersion = 33
```

By doing this I was able to run my app again!

**Comment by amarw** [comment]
For anyone else looking for a quick fix without updating compileSdkVersion and targetSdkVersion values, here is a patch generated using patch-package. This patch replaces the use of Build.VERSION_CODES.TIRAMISU with api version number 33. Please note this is just a temporary workaround, proper fix would be to update your app to support minimum api version 33.

```
diff --git a/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewManager.kt b/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewManager.kt
index 1bec076..e341f04 100644
--- a/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewManager.kt
+++ b/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewManager.kt
@@ -244,7 +244,7 @@ class RNGestureHandlerButtonViewManager : ViewGroupManager<ButtonViewGroup>(), R
 
       // Since Android 13, alpha channel in RippleDrawable is clamped between [128, 255]
       // see https://github.com/aosp-mirror/platform_frameworks_base/blob/c1bd0480261460584753508327ca8a0c6fc80758/graphics/java/android/graphics/drawable/RippleDrawable.java#L1012
-      if (rippleColor == Color.TRANSPARENT && Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
+      if (rippleColor == Color.TRANSPARENT && Build.VERSION.SDK_INT >= 33) {
         return null
       }
```

**Comment by m-bert** [comment]
Hi! Versions checks that @amarw is talking about were removed in [this PR](https://github.com/software-mansion/react-native-gesture-handler/pull/2575/files). Today gesture handler 2.13.0 was released, could you please check if this issue still occurs?
