### ISSUE TITLE
Swipeable doesn't work smoothly when placed on a Modal

### ISSUE THREAD

**Issue by zuhasohail18** [software-mansion/react-native-gesture-handler#2487]
### Description

I am using Modal from 'react-native-modal'. I have a FlatList rendering multiple Swipeable from react-native-gesture-handler inside that Modal. Each Swipeable has two requirements for my app:
1. It must swipe to left/right and show required options.
2. If clicked on, it must redirect to required screen.

The problem I'm facing is that both swipe and touch gestures conflict and even when I'm trying to swipe, it detects the gesture as touch and navigates to new screen.
This problem only occurs when I use Swipeable inside a modal. On simple views, it works fine.

I'm using following versions of libraries:
"react-native-modal": "13.0.1",
"react-native-gesture-handler": "2.8.0"

### Steps to reproduce

1. Make a simple Modal on a screen
2. Put a swipeable inside that modal
3. Try to swipe left/right from almost center of swipeable component.

### Snack or a link to a repository

https://snack.expo.dev/BPdkQDF5y

### Gesture Handler version

2.8.0

### React Native version

0.70.6

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by schniddsel** [comment]
Same Issue here, fix in 2.10.1 did not solve the Problem #2482 It is the same behaviour
