### ISSUE TITLE
Android 13, ANR triggered by slow operations in blamed thread

### ISSUE THREAD

**Issue by chaitu14** [software-mansion/react-native-gesture-handler#2489]
### Description

After performing few actions on bottom sheet or modal app goes to ANR state in android 13 version

OS version: android13
Model:Galaxy Tab S6 Lite
Date:May 25, 2023, 5:23:01 PM

- "react-native-reanimated": "^3.1.0",
- "react-native-gesture-handler": "2.10.1",
- "@gorhom/bottom-sheet": "4.4.6",
- "react-native": "0.71.3",

            
[https://youtu.be/7QKgvF3Zufg](            
)            
Even after removing the video inside the bottom sheet, my app still goes into an ANR state after some swipe actions. I removed the bottom sheet and used a model, but the same issue persists. However, if I render directly in the view, it works fine.

### Steps to reproduce

The parent view has a root GestureHandlerRootView, and there is a bottom sheet inside it. 

When users perform swipe-down or swipe-up gestures or click inside the bottom sheet for certain actions, the app goes into an ANR state with UI deadlock.

Even I removed bottom sheet used modal still same behaviour<img width="1450" alt="Screenshot 2023-05-25 at 11 59 44 PM" src="https://github.com/software-mansion/react-native-gesture-handler/assets/4597742/ddc376d8-b03b-46b9-8cd6-464ef3dd0a82">

### Snack or a link to a repository

https://snack.expo.dev/@chaitanya26/3bdea9

### Gesture Handler version

2.10.1

### React Native version

0.71.3

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

Real device

### Device model

Model:Galaxy Tab A8

### Acknowledgements

Yes

**Comment by chaitu14** [comment]
If I apply the patch, it works fine. However, my Gifted Chat list now appears inverted (from bottom to top), but at least the hanging issue has been resolved.

diff --git a/node_modules/react-native/Libraries/Lists/VirtualizedList.js b/node_modules/react-native/Libraries/Lists/VirtualizedList.js
index 9ec105f..a8f1d8c 100644
--- a/node_modules/react-native/Libraries/Lists/VirtualizedList.js
+++ b/node_modules/react-native/Libraries/Lists/VirtualizedList.js
@@ -11,6 +11,7 @@
 'use strict';
 
 const Batchinator = require('../Interaction/Batchinator');
+const Platform = require('../Utilities/Platform');
 const FillRateHelper = require('./FillRateHelper');
 const PropTypes = require('prop-types');
 const React = require('react');
@@ -2185,9 +2186,14 @@ function describeNestedLists(childList: {
 }
 
 const styles = StyleSheet.create({
-  verticallyInverted: {
-    transform: [{scaleY: -1}],
-  },
+  verticallyInverted:
+    Platform.OS === 'android'
+      ? {
+          scaleY: -1,
+        }
+      : {
+          transform: [{scaleY: -1}]
+        },
   horizontallyInverted: {
     transform: [{scaleX: -1}],
   },

**Comment by j-piasecki** [comment]
Sorry, but I don't really see anything that would point to Gesture Handler being the issue here. Do you have anything else to share that would allow me to look deeper into this?
