### ISSUE TITLE
Swipeable not working in top tab view inside another top tab view 

### ISSUE THREAD

**Issue by kumarsoni7999** [software-mansion/react-native-gesture-handler#2490]
### Description

Swipe not working for Top tab view inside another top tab view.

### Steps to reproduce

top tab view having 3 tabs
one tab have agian 2 top tab view 
inside that tab not working

### Snack or a link to a repository

https://github.com/

### Gesture Handler version

2.9.0

### React Native version

0.71

### Platforms

Android

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Release mode

### Device

Android emulator

### Device model

Bluestack emulator

### Acknowledgements

Yes

**Comment by shreyn1** [comment]
Are you using "@react-navigation/material-top-tabs"?

**Comment by m-bert** [comment]
Hello @kumarsoni7999! Could you please provide a reproduction so I can look at it?
