### ISSUE TITLE
ios build errors in 2.10.1

### ISSUE THREAD

**Issue by markl-vesper** [software-mansion/react-native-gesture-handler#2493]
### Description

Recently updated to RNGH 2.10.1 and RN 0.71.6

ios archive process started failing with errors relating to the .mm files in ./ios/ and ./ios/handlers dir.

xcode was looking for same file but with .m suffix. renaming the files to .m allowed the build to proceed further but breaks further down the process with below error

error: unknown type name 'constexpr' in line 41 of RNGestureHandlerManager.m

xcode version is 14.3

Was I correct to simply rename the .mm files to .m or is there a more appropriate fix?
Did that fix create the constexpr error?

Any advice on how to fix ios build is greatly appreciated

Tks

### Steps to reproduce

updated build packages - yarn install
updated pods - cd pod / pod install
xcode - clean build folder
xcode - product archive

build fails

### Snack or a link to a repository

n/a

### Gesture Handler version

2.10.1

### React Native version

0.71.6

### Platforms

Android, iOS

### JavaScript runtime

V8

### Workflow

React Native (without Expo)

### Architecture

None

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by j-piasecki** [comment]
I'm not quite sure why it's looking for `.m` file in the first place. Have you tried removing `node_modules` and `Pods` and reinstalling them? You could also try to replace
```cpp
constexpr int NEW_ARCH_NUMBER_OF_ATTACH_RETRIES = 25;
```
with
```objc
#define NEW_ARCH_NUMBER_OF_ATTACH_RETRIES 25;
```
in `RNGestureHandlerManager`.

Which versions of React Native and Gesture Handler were you using before updating?
Would it be possible for you to prepare a reproduction or share the project it's happening in, if reinstalling doesn't help?
