### ISSUE TITLE
GestureDetector is not working with SVG paths

### ISSUE THREAD

**Issue by suraj021** [software-mansion/react-native-gesture-handler#2502]
### Description

I have a use-case where I have a huge svg with multiple paths. The paths are created iteratively. I want to have Pan and Rotate gestures over each path, however I am not able to achieve it. I am doing following to create the paths iteratively and adding gestures to them.

```
const panGesture = Gesture.Pan()
    .runOnJS(true)
    .onUpdate((event) => {
      console.log(event)
    })
```

```
<GestureHandlerRootView style={{ flex: 1 }}>
   <Svg fill="#000000" width="100%" height="100%">
        {
          allPaths.map((path: string, index: number) => {
            const key: string = '' + index;
            return (
              <GestureDetector key={key} gesture={panGesture}>
                <Path d={path} />
              </GestureDetector>
            )
          })
        }
   </Svg>
</GestureHandlerRootView>
```

Initially, `panGesture` was never triggered on panning of any paths. However, on adding `onResponderMove={(_) => { }}` to the `Path` like `<Path d={path} onResponderMove={(_) => { }}/>`, I was able to trigger `panGesture`. But the problem I am facing is that the `panGesture` is being triggered on panning of the last path in `allPaths`. 

For ex: If I have 3 paths in `allPaths`, `panGesture` is being triggered only for the last path and not for other paths. The pan event for last Path is

`{"absoluteX": 711, "absoluteY": 347.6666564941406, "handlerTag": 3, "numberOfPointers": 1, "state": 4, "target": 623, "translationX": 182, "translationY": 21, "velocityX": 57.62165558611361, "velocityY": 12.67447917652239, "x": 254.66666412353516, "y": 46.666656494140625}` 

Is there a way to trigger `panGesture` on panning of each path in the Svg. Is there a way to find out on which path the panning was done?

Thanks

### Steps to reproduce

1. Let all paths be 
```
allPaths= [
  "M 0 0 L 100 0 L 100 100 L 0 100 Z",
  "M 150 150 L 250 150 L 250 250 L 150 250 Z",
  "M 300 300 L 400 300 L 400 400 L 300 400 Z"
]
```

2. Use aforementioned code to add gesture handlers to each path and try panning. You will see that `panGesture` is only being triggered for the last path.

### Snack or a link to a repository

https://snack.expo.dev/@suraj021/handle-pan-gesture

### Gesture Handler version

^2.10.2

### React Native version

0.71.8

### Platforms

iOS

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

None

### Device

iOS simulator

### Device model

Iphone 14 Pro Max

### Acknowledgements

Yes

**Comment by m-bert** [comment]
Hi @suraj021! Looking at your snack I see that at first you create `TapGesture` and then inside map you create `GestureDetectors` and assign to them previously created handler. Due to how `GestureDetector` works it may cause problems, for example only last path will react to the tap. On web app probably won't event start.

What I sugest is to move creation of gesture into the map function, like this:

```jsx
export default function App() {
  const allPaths = [
    'M 0 0 L 50 0 L 50 50 L 0 50 Z',
    'M 100 100 L 150 100 L 150 150 L 100 150 Z',
    'M 200 200 L 250 200 L 250 250 L 200 250 Z',
  ];

  return (
    <GestureHandlerRootView style={{ flex: 1 }}>
      <View style={{ paddingTop: 100, paddingLeft: 50 }}>
        <Svg fill="#000000" width="100%" height="100%">
          {allPaths.map((path: string, index: number) => {
            const key: string = '' + index;

            const tapGesture = Gesture.Tap()
              .runOnJS(true)
              .onEnd((event) => {
                console.log(event);
              });

            return (
              <GestureDetector key={key} gesture={tapGesture}>
                <Path d={path} onResponderMove={(_) => {}} />
              </GestureDetector>
            );
          })}
        </Svg>
      </View>
    </GestureHandlerRootView>
  );
}
```

Let me know if it helps!
