### ISSUE TITLE
ReferenceError: Can't find variable: queueMicrotask

### ISSUE THREAD

**Issue by abdulrafeh857** [software-mansion/react-native-gesture-handler#2505]
### Description

I am experiencing this error in react-native-gesture-handler. I don't know the cause of this error because it was working absolutely fine. 

"react-native" : 0.65.1
"react-native-gesture-handler" - 2.11.0

![Simulator Screen Shot - iPhone 11 Pro Max - 2023-06-08 at 23 01 28](https://github.com/software-mansion/react-native-gesture-handler/assets/37897250/48b390b0-0cdd-4a39-9229-6c334e9b117a)

### Sample Code

import {FlatList} from 'react-native-gesture-handler';
 <FlatList
            data={carsData}
            renderItem={renderCars}
            ref={flatListRef}
            )}
          />

### Steps to reproduce

yarn
yarn ios
Error comes as soon as i try to render a flatlist from react-native-gesture-handler

### Snack or a link to a repository

...

### Gesture Handler version

2.11.0

### React Native version

0.65.1

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 11Pro Max

### Acknowledgements

Yes

**Comment by rayjackson13** [comment]
Hi! This issue also happened to me on Android after upgrading "react-native-gesture-handler" from v2.9.0 to v2.11.0.

**Comment by abdulrafeh857** [comment]
I commented the queueMicrotask functions at these places the error went away. Don't know how it will impact the functionality or performance.

node_modules/react-native-gesture-handler/src/handlers/gestureHandlerCommon.ts
node_modules/react-native-gesture-handler/src/handlers/createHandler.tsx

**Comment by j-piasecki** [comment]
Which JavaScript runtime are you using? - JSC would be the default on those RN versions so unless you've enabled Hermes or installed `react-native-v8`, it will be that.

**Comment by cukelty** [comment]
save error when i update lib version from 1.x to 2.9.0

**Comment by Juanjojara** [comment]
I have this exact same problem on iOS. I have xcode 14.3.1, react-native 0.63.5, react-native-gesture-handler 2.9.0. 
The solution from @abdulrafeh857 worked for me but is not a real solution, it's barely a patch and I hope that it does not have any major impact on the app.

**Comment by m-bert** [comment]
Hi @abdulrafeh857! I've prepared [this PR](https://github.com/software-mansion/react-native-gesture-handler/pull/2612), could you please check if it helps?
