### ISSUE TITLE
java.lang.Double cannot be cast to java.lang.String on Android Device

### ISSUE THREAD

**Issue by usegravity** [software-mansion/react-native-gesture-handler#2506]
### Description

**java.lang.Double cannot be cast to java.lang.String** error when using ScrollView with RefreshControl on Samsung mobile with Android 13.

Works fine on iOS and iOS Simulator, ScrollView works without the RefreshControl without issue.

Have tried using ScollView from both react-native and react-native-gesture-handler. 

![issue2](https://github.com/software-mansion/react-native-gesture-handler/assets/48517384/2e5ec273-eca9-4eb2-9658-8cb4c3346022)

![issue1](https://github.com/software-mansion/react-native-gesture-handler/assets/48517384/7c1e4c09-fbc2-466e-adc0-d666b0bb8369)

### Steps to reproduce

1. Import ScrollView from react-native-gesture-handler 
2. Import RefreshControl from react-native
3. Pass RefreshControl to refreshControl prop.

### Snack or a link to a repository

https://snack.expo.dev/Zi4LSp08D

### Gesture Handler version

2.11.0

### React Native version

0.71.8

### Platforms

Android

### JavaScript runtime

None

### Workflow

Expo managed workflow

### Architecture

None

### Build type

None

### Device

Real device

### Acknowledgements

Yes

**Comment by ZuhaIT** [comment]
Hello @j-piasecki ,

Thank you for the response. I tried your suggested solution but getting the same error. :-(

**Comment by yunussheikh** [comment]
Hello @j-piasecki, 

Thank you for your reply. 

Your proposed solution is also giving the same error message on my Samsung device.

**Comment by m-bert** [comment]
Hi @yunussheikh! I've just tested this on my Samsung device with Android 13 and everything seems to work fine. In order to do that, I had to prepare my own repro. Here is the code that I used:

```jsx
import React from 'react';
import { Text, View } from 'react-native';
import { ScrollView } from '../../src/components/GestureComponents';
import { RefreshControl } from 'react-native';

export default function Test(props) {
  const [refreshing, setRefreshing] = React.useState(false);

  const onRefresh = React.useCallback(() => {
    setRefreshing(true);
    setTimeout(() => {
      setRefreshing(false);
    }, 100);
  }, []);

  return (
    <ScrollView
      refreshControl={
        <RefreshControl refreshing={refreshing} onRefresh={onRefresh} />
      }>
      <Text>Testing</Text>
    </ScrollView>
  );
}
```

If you still experience this issue, please prepare repro so we can have a look at it.

**Comment by kbqdev** [comment]
+1 same with reac-native : 0.71.6

**Comment by WellingtonSouzaAbreu** [comment]
This error appears to me only on Android. Fix this error by just removing the size of the Refresh Control.
I'm using FlatList, ScrollView and Refresh Control from 'react-native'
![Captura de Tela 2024-05-28 às 15 41 50](https://github.com/software-mansion/react-native-gesture-handler/assets/64331839/849daa13-1b70-4bce-b865-5c38eda6cc4d)

**Comment by MufeedaFi** [comment]
Why the 'size' param is causing this issue?

**Comment by MufeedaFi** [comment]
> This error appears to me only on Android. Fix this error by just removing the size of the Refresh Control. I'm using FlatList, ScrollView and Refresh Control from 'react-native' ![Captura de Tela 2024-05-28 às 15 41 50](https://private-user-images.githubusercontent.com/64331839/334554973-849daa13-1b70-4bce-b865-5c38eda6cc4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NTkxNzMsIm5iZiI6MTcyMzQ1ODg3MywicGF0aCI6Ii82NDMzMTgzOS8zMzQ1NTQ5NzMtODQ5ZGFhMTMtMWI3MC00YmNlLWI4NjUtNWMzOGVkYTZjYzRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDEwMzQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyNDgwMjNhYTU0N2NkOGZkNTVhYmZiYzJhZjc1NzQ0MTVjZTliZjNiNmI3NWEzZWFmNzBmMWMyMWQyMTg3NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TvwQf9SU_S2p1OxZNCTx9KlND3NaRaKCnES3t7MXPRM)

Why the 'size' param is causing this issue?

**Comment by m-bert** [comment]
Hi! Thanks to @WellingtonSouzaAbreu we were able to reproduce this issue.

First of all, it seems that it is not a problem with Gesture Handler itself - it crashes without any import from our library.

If you look into [docs](https://reactnative.dev/docs/refreshcontrol#size-android), you'll see that `size` takes `enum` as argument. I have no idea why TypeScript shows that it should be `number`, but it clearly doesn't work.

**Comment by AnfalHussain** [comment]
> This error appears to me only on Android. Fix this error by just removing the size of the Refresh Control. I'm using FlatList, ScrollView and Refresh Control from 'react-native' ![Captura de Tela 2024-05-28 às 15 41 50](https://private-user-images.githubusercontent.com/64331839/334554973-849daa13-1b70-4bce-b865-5c38eda6cc4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NjkyOTYsIm5iZiI6MTczNDk2ODk5NiwicGF0aCI6Ii82NDMzMTgzOS8zMzQ1NTQ5NzMtODQ5ZGFhMTMtMWI3MC00YmNlLWI4NjUtNWMzOGVkYTZjYzRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDE1NDk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyMDYyNTA0ZjNkM2ZiNzBmZWVjMzNiNjVjZjI1NWU4YWNhZDNhNGJhYjAzZWYwNWI5NTJiOTk0NGZkN2YxYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2yTPCD7BjDB3qBh56QardyEtyppuEzzilmHIvDKfJeY)

Thank you @WellingtonSouzaAbreu for saving my life. 🌟
