### ISSUE TITLE
 RNGestureHandlerModule.attachGestureHandler was called with 2 arguments but expects 3 arguments.

### ISSUE THREAD

**Issue by mickykro** [software-mansion/react-native-gesture-handler#2514]
### Description

when I run the app on an iphone device I get this error message:

>  [native] RNGestureHandlerModule.attachGestureHandler was called with 2 arguments but expects 3 arguments. If you haven't changed this method yourself, this usually means that your versions of the native code and JavaScript code are out of sync. Updating both should make this error go away.

this error doesnt show on an emulator. 

the device is an iPhone 6s plus running on ios '15.7.1' 

maybe this problem happens only on older versions, but it is a big application with 500K downloads and we cant solve this issue. 

I tried cleaning the cache, removing node modules and pods and it didnt help.

any other information I can share? 

### Steps to reproduce

1. run app on a iPhone 6s Plus, ios '15.7.1'
2. see the issue pops right after the splash screen 

### Snack or a link to a repository

https://snack.expo.dev/

### Gesture Handler version

2.11.0

### React Native version

0.71.0

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

iPhone 6S Plus, ios 15.7.1

### Acknowledgements

Yes

**Comment by j-piasecki** [comment]
Have you by any chance updated Gesture Handler before this started happening? The third argument got added around the time of 2.0 release IIRC, and as the error suggests the native and JS code versions may be out of sync. This could happen when a library you're using relies on GH as a dependency but it's incorrectly configured.

Could you paste the results of `yarn why react-native-gesture-handler` and `npm ls react-native-gesture-handler`?

**Comment by muhammadkhan0009** [comment]
Encountered this issue on ios simulator and this is how I resolved it: 
- Update the pod files. We have a script in the package.json `yarn pod`
- Deleted the existing app from the simulator
- Run the app from the xcode. 
Hope it helps.
