### ISSUE TITLE
Pointer-events does not work on GestureHandlerRootView on android

### ISSUE THREAD

**Issue by Pnlvfx** [software-mansion/react-native-gesture-handler#2515]
### Description

<GestureHandlerRootView pointerEvents="box-none" style={containerStyles}>
        <Component {...props} />
</GestureHandlerRootView>

Works on ios but doesn't work on android, I'm stuck here from more than a week, is it expected or I'm doing something wrong?

### Steps to reproduce

Think like the spotify player:
```
<Tab.Navigator
  tabBar={babyPlayer}
```
      
To use the pan gesture handler I need to wrap the component with gestureHandlerRootHOC which I've recreated like so, as the original doesn't have the options to add pointer events:
```
import React from 'react';
import {StyleProp, ViewStyle} from 'react-native';
import hoistNonReactStatics from 'hoist-non-react-statics';
import {GestureHandlerRootView} from 'react-native-gesture-handler';

export default function gestureHandlerRootHOC<
  P extends Record<string, unknown>,
>(Component: React.ComponentType<P>, containerStyles?: StyleProp<ViewStyle>) {
  function Wrapper(props: P) {
    return (
      <GestureHandlerRootView pointerEvents="box-none" style={containerStyles}>
        <Component {...props} />
      </GestureHandlerRootView>
    );
  }

  Wrapper.displayName = `gestureHandlerRootHOC(${
    Component.displayName || Component.name
  })`;

  hoistNonReactStatics(Wrapper, Component);

  return Wrapper;
}
```

and then I'm using it:
```
export const babyPlayer = gestureHandlerRootHOC(
  (props: BottomTabBarProps) => <BabyPlayer {...props} />,
  {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    top: 0,
    pointerEvents: 'none',
  },
);
```

Works fine on ios but doesn't work on android

### Snack or a link to a repository

none

### Gesture Handler version

2.12.0

### React Native version

0.72.0-rc.5

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by j-piasecki** [comment]
Could you try adding a `<View>` between the `GestureHandlerRootView` and `Component`, and set `pointer-events` prop to that? Something like this:

```jsx
<GestureHandlerRootView style={containerStyles}>
  <View pointerEvents="box-none" style={{flex: 1}}>
    <Component {...props} />
  </View>
</GestureHandlerRootView>```

**Comment by donatoaguirre24** [comment]
Hi, @Pnlvfx were you able to solve this? 

We're facing a similar issue and the workaround proposed by @j-piasecki didn't work for us

Our app uses react-native-navigation and has a toast component that is presented as an overlay. We set `interceptTouchOutside: false` in the toast, but the `GestureHandlerRootView` is stealing the touch events (`pointerEvents="box-none"` works on iOS but not on Android)

Thanks!

**Comment by Pnlvfx** [comment]
Yes, I went inside the package and I copy the content of gesture handler root view into a new file add you can add the pointer events to it.
Inviato da iPhone

On Aug 14, 2024, at 5:15 PM, Donato Aguirre ***@***.***> wrote:

﻿

Hi, @Pnlvfx<https://github.com/Pnlvfx> were you able to solve this?

We're facing a similar issue and the workaround proposed by @j-piasecki<https://github.com/j-piasecki> didn't work for us

Our app uses react-native-navigation and has a toast component that is presented as an overlay. We set interceptTouchOutside: false in the toast, but the GestureHandlerRootView is stealing the touch events (pointerEvents="box-none" works on iOS but not on Android)

Thanks!
