### ISSUE TITLE
Cannot find module '@babel/plugin-transform-shorthand-properties'

### ISSUE THREAD

**Issue by Vikasatneaxus** [software-mansion/react-native-gesture-handler#2525]
### Description

node_modules/react-native-gesture-handler/src/handlers/gestures/GestureDetector.tsx: /Users/admin/Documents/___meatventory___/node_modules/react-native-gesture-handler/src/handlers/gestures/GestureDetector.tsx: Cannot find module '@babel/plugin-transform-shorthand-properties'
Require stack:
- /Users/admin/Documents/___meatventory___/node_modules/@babel/core/lib/config/files/plugins.js
- /Users/admin/Documents/___meatventory___/node_modules/@babel/core/lib/config/files/index.js
- /Users/admin/Documents/___meatventory___/node_modules/@babel/core/lib/index.js
- /Users/admin/Documents/___meatventory___/node_modules/metro-transform-worker/src/index.js
- /Users/admin/Documents/___meatventory___/node_modules/metro/src/DeltaBundler/Worker.flow.js
- /Users/admin/Documents/___meatventory___/node_modules/metro/src/DeltaBundler/Worker.js
- /Users/admin/Documents/___meatventory___/node_modules/metro/node_modules/jest-worker/build/workers/processChild.js

### Steps to reproduce

not able to run project 

### Snack or a link to a repository

https://github.com/aksainiarun/___meatventory___

### Gesture Handler version

2.12.0

### React Native version

0.67.1

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by djaffer** [comment]
same issue.

**Comment by Vikasatneaxus** [comment]
@djaffer  
i solve this problem with this change 


I change it from:

`Build.VERSION_CODES.TIRAMISU`
to:

`Build.VERSION_CODES.LOLLIPOP`

**Comment by djaffer** [comment]
Thanks. I am using expo react native.
