### ISSUE TITLE
Android build failed with new architecture enabled in android

### ISSUE THREAD

**Issue by sushantjadhav111** [software-mansion/react-native-gesture-handler#2527]
### Description

Android build failed with new architecture enabled in android but if we switch to old one then it works .

### Steps to reproduce

1) Enable new architecture for android.
2) Clean build(in Android Studio)
3) Run (in Android Studio)
... build fails after some time

### Snack or a link to a repository

https://github.com/software-mansion/react-native-gesture-handler/issues/

### Gesture Handler version

2.9.0

### React Native version

0.69.4

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

Android emulator

### Acknowledgements

Yes

**Comment by j-piasecki** [comment]
Since the new architecture is developing rapidly and there are a lot of changes between RN versions regarding it, we only support the latest version at the moment. Could you try upgrading to React Native 0.72 and Gesture Handler 2.12 to see if the problem still exists there?
