### ISSUE TITLE
Issue Jest: Swipeable PanGestureHandler must be used as a descendant of GestureHandlerRootView.

### ISSUE THREAD

**Issue by JorgeFabris** [software-mansion/react-native-gesture-handler#2536]
### Description

When you are attempting to execute a test with Jest, and the component that you're testing employs the 'Swipeable', it may fail. This failure occurs because 'Swipeable' depends on 'PanGestureHandler' for its functioning. The 'PanGestureHandler' must be utilized as a child component (or a 'descendant') within the 'GestureHandlerRootView' for the test to run successfully. This hierarchical requirement stems from the fact that 'GestureHandlerRootView' allows the various touch events to be recognized and properly processed by the 'PanGestureHandler', which in turn enables the 'Swipeable' mechanism to work as expected. Therefore, not adhering to this specific structure of component nesting could result in testing failures with Jest.

I leave a react native app made with Expo to test it
<img width="1430" alt="image" src="https://github.com/software-mansion/react-native-gesture-handler/assets/131181860/94ecdaf5-30aa-4676-9525-3f44cb80fe27">

### Steps to reproduce

1. Create a component to test with Swipeable
2. run the test

### Gesture Handler version

2.10.0

### React Native version

0.71.7

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Repository
https://github.com/JorgeFabris/gesture_handler_swipeable_issue

### Device

None

### Acknowledgements

Yes

**Comment by j-piasecki** [comment]
This problem was fixed in [2.10.2](https://github.com/software-mansion/react-native-gesture-handler/releases/tag/2.10.2), could you try upgrading?
