### ISSUE TITLE
Crash on Android & iOS with `TypeError: Cannot set property 'config' of undefined`

### ISSUE THREAD

**Issue by nmalzieu** [software-mansion/react-native-gesture-handler#2554]
### Description

Since I added react-native-gesture-handler, I have random crashes on both iOS and Android with the following error:

`TypeError: Cannot set property 'config' of undefined`

Error occurs here: https://github.com/software-mansion/react-native-gesture-handler/blob/main/src/handlers/gestures/GestureDetector.tsx#L275

Most of the time it works perfectly.

I first had it on iOS and thought that this commit : https://github.com/software-mansion/react-native-gesture-handler/pull/2483
would fix it so I upgraded to version 2.12.0

But now I just had it on Android as well!

### Steps to reproduce

Install react-native-gesture-handler

Use it on iOS or Android and experience some random crash (might take a while)

### Snack or a link to a repository

Private repository

### Gesture Handler version

2.12.0

### React Native version

0.71.8

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

Expo bare workflow

### Architecture

None

### Build type

Release mode

### Device

Real device

### Device model

iPhone 12 Mini, iPhone 13, Android Pixel 7

### Acknowledgements

Yes

**Comment by nmalzieu** [comment]
Hi team, do you know what could cause the issue? I had to move out of RN Gesture Handler for now but that's a shame!

**Comment by m-bert** [comment]
Hi @nmalzieu! Sorry for late response.

Random crashes do not tell us much. Since you've provided a line in code that throws error, I'll try to look at it - maybe I'll find something. However, it would be great if you could prepare repro.

**Comment by nmalzieu** [comment]
Hi @m-bert . I have upgraded Expo, React Native & RNGH since and don't have the issue anymore. Unsure what caused but if no one else has the issue I think you can drop it for now!

**Comment by m-bert** [comment]
Okay, I'm glad to hear that this issue is gone!
