### ISSUE TITLE
[Web] Gesture Handler Root View error throws (unnecessarily)

### ISSUE THREAD

**Issue by nandorojo** [software-mansion/react-native-gesture-handler#2557]
### Description

<img width="799" alt="Screenshot 2023-07-30 at 5 20 02 PM" src="https://github.com/software-mansion/react-native-gesture-handler/assets/13172299/5bca3e8e-29c0-4b98-b293-7d96530db682">

This error is not necessary on Web, right? Websites are unlike apps, in that they shouldn't necessarily have a view wrapping them, as this can mess with scroll styles. If there is a provider that is going on inside of `GestureHandlerRootView`, then it should be split out as `GestureHandlerRootProvider`. If this context doesn't provide any actual benefit on Web, then this error should only be called on native.

### Steps to reproduce

Add any gesture view in a web app, without wrapping it in GestureHandlerRootView.

### Snack or a link to a repository

Let me know if this is needed.

### Gesture Handler version

2.12.0

### React Native version

0.72.3

### Platforms

Web

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by nandorojo** [comment]
Repro shouldn't be needed here, right? The cause of the issue is known.

We also shouldn't have to wrap the entire app with a gesture handler component, since this library isn't optimized for web tree shaking, which would cause every page to import the entire thing without needing to.

**Comment by m-bert** [comment]
Hi @nandorojo! Indeed, this error is not necessary on web. I've simply overlooked it during development, because our example app is wrapped in `GestureHandlerRootView`. I've removed the error in [this PR](https://github.com/software-mansion/react-native-gesture-handler/pull/2558).

**Comment by m-bert** [comment]
One more thing - someone from our team needed this asap, so it is already available in latest release [2.12.1](https://github.com/software-mansion/react-native-gesture-handler/releases/tag/2.12.1).
