### ISSUE TITLE
Gesture detector tap doesn't animate.

### ISSUE THREAD

**Issue by ZahidHasan321** [software-mansion/react-native-gesture-handler#2566]
### Description

I was trying a add bouncing animation on a pressable. It does work on long press on gesture detection but does not seem to work on tap. 

my implementation

```
const tapGesture = Gesture.Tap()
    .onStart(() => {
      pressed.value = true;
    })
    .onEnd(() => {
      pressed.value = false;
    });

  const longPressGesture = Gesture.LongPress()
    .onStart((e) => {
      pressed.value = true;
    })
    .onEnd((e, success) => {
      if (success) {
        pressed.value = false;
      }
    });

  return (
    <GestureDetector gesture={Gesture.Exclusive(longPressGesture,tapGesture)}>
      <Animated.View style={uas}>
        <Pressable
          style={({ pressed, hovered, focused }: PressableState) => [
            [styles.button, hovered && styles.focused],
          ]}
          onPress={handlePress}
          onLongPress={handlePress}
          {...restProps}
        >
          <Text>{label}</Text>
        </Pressable>
      </Animated.View>
    </GestureDetector>
  );
```

https://github.com/software-mansion/react-native-gesture-handler/assets/54740574/9a11efd2-9e04-426a-ab5f-5adefbedbc50

### Steps to reproduce

1. npm start
2.click the button

### Snack or a link to a repository

https://github.com/ZahidHasan321/foodslice

### Gesture Handler version

2.12.0

### React Native version

0.72.3

### Platforms

Android, Web

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by m-bert** [comment]
Hi @ZahidHasan321! I've looked at your code and it seems to work fine. The reason why tap handler does not trigger the animation is because it activates and ends immediately. Try putting your callback inside `onBegin` method, like this:

```jsx
  const tapGesture = Gesture.Tap()
    .onBegin(() => {
      pressed.value = true;
    })
    .onEnd(() => {
      pressed.value = false;
    });
```

This should do the trick. Let me know if it helps!

**Comment by ZahidHasan321** [comment]
> Hi @ZahidHasan321! I've looked at your code and it seems to work fine. The reason why tap handler does not trigger the animation is because it activates and ends immediately. Try putting your callback inside `onBegin` method, like this:
> 
> ```js
>   const tapGesture = Gesture.Tap()
>     .onBegin(() => {
>       pressed.value = true;
>     })
>     .onEnd(() => {
>       pressed.value = false;
>     });
> ```
> 
> This should do the trick. Let me know if it helps!

Yeah, it's working now. Thank you for the help

**Comment by ZahidHasan321** [comment]
Issue is fixed
