### ISSUE TITLE
weird animation when use TouchableHighlight in Android

### ISSUE THREAD

**Issue by frankA10019** [software-mansion/react-native-gesture-handler#2567]
### Description

After import TouchableHighlight from react-native-gesture-handler, it has a weird animation in Android simulator. It doesn't happen in original TouchableHighlight from react native. Please help.

 <TouchableHighlight
                  style={{
                    borderRadius: 10,
                    height: 30,
                  }}
                  onPress={() => {
                    console.log('press');
                  }}
                  underlayColor={theme.colors.secondary200}
                ></TouchableHighlight>

### Steps to reproduce

https://github.com/software-mansion/react-native-gesture-handler/assets/105480239/990deb19-408a-49c2-8280-58da91a7b69a

### Snack or a link to a repository

None

### Gesture Handler version

2.9.0

### React Native version

0.69.9

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by j-piasecki** [comment]
This should be fixed in 2.10.0, could you upgrade and check?

**Comment by frankA10019** [comment]
@j-piasecki  My app facing the issue with #2481

**Comment by j-piasecki** [comment]
You can add `disableMultipleInstancesCheck=true` to `gradle.properties` to disable the check.
