### ISSUE TITLE
Add AGP8 support by adding buildConfig = true to buildFeatures

### ISSUE THREAD

**Issue by pvegh** [software-mansion/react-native-gesture-handler#2571]
### Description

Upgrading to Android Gradle Plugin 8.1 and trying not to use the global flag
android.defaults.buildfeatures.buildconfig=true
which leads to slower builds than defining this only in needed modules
I'm getting the error:

```
* What went wrong:
A problem occurred configuring project ':react-native-gesture-handler'.
> defaultConfig contains custom BuildConfig fields, but the feature is disabled.
  To enable the feature, add the following to your module-level build.gradle:
  `android.buildFeatures.buildConfig true`
```

Fix: please add the flag
```
buildFeatures {
        buildConfig = true
    }
```
Other projects do something like this:
```
def agpVersion = com.android.Version.ANDROID_GRADLE_PLUGIN_VERSION
    if (agpVersion.tokenize('.')[0].toInteger() >= 7) {
        namespace "com.horcrux.svg"
    }
```
to build.gradle for AGP >= 8.1

### Steps to reproduce

1. Upgrade to AGP 8.1
2. add android.defaults.buildfeatures.buildconfig=true to gradle.properties (done by AGP upgrade wizard in AS)
3. ./gradlew assDebug

### Snack or a link to a repository

none

### Gesture Handler version

2.12.1

### React Native version

0.72.2

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by pvegh** [comment]
Can't do a repro sorry, I'm not into the RN game that much.

**Comment by pvegh** [comment]
Can you please take a look at this? I know there's no repro here but it should be straightforward anyway

**Comment by pvegh** [comment]
RN Thread about this: https://github.com/react-native-community/discussions-and-proposals/issues/671

**Comment by pvegh** [comment]
In my opinion it doesn't need a repro, it's a build simple feature with full description what is missing

**Comment by pvegh** [comment]
Created a PR, probably need some help since I don't usually do this. https://github.com/software-mansion/react-native-gesture-handler/pull/2599

**Comment by pvegh** [comment]
Would a patch version with this be possible?

**Comment by j-piasecki** [comment]
[Yes](https://github.com/software-mansion/react-native-gesture-handler/releases/tag/2.13.2) 😃

**Comment by NitinMittal08** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':firebase_auth'.
> com.android.builder.errors.EvalIssueException: defaultConfig contains custom BuildConfig fields, but the feature is disabled.
  To enable the feature, add the following to your module-level build.gradle:
  `android.buildFeatures.buildConfig true`

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 6s
Error: Gradle task assembleDebug failed with exit code 1

**Comment by j-piasecki** [comment]
@NitinMittal08 

> A problem occurred configuring project ':firebase_auth'.

This seems unrelated to Gesture Handler
