### ISSUE TITLE
react/debug/flags.h' file not found (ios build error)

### ISSUE THREAD

**Issue by uloco** [software-mansion/react-native-gesture-handler#2580]
### Description

My project is setup with the new arch, without flipper and with use_frameworks: static.
I already reinstalled all dependencies, cleared caches multiple times etc.
This error started happening after switching to the new architecture.
All my project dependencies are on the latest version.
I'm on latest react-native 0.72.4

I'm getting the following error when trying to build iOS (with rosetta enabled):

```
In file included from /Users/uloco/Source/smokeless/smokeless-react-native/node_modules/react-native-gesture-handler/ios/Handlers/RNNativeViewHandler.mm:17:
In file included from /Users/uloco/Library/Developer/Xcode/DerivedData/Smokeless-hessnrvxehuzzzbbcepctyxqzaau/Build/Products/Debug-iphonesimulator/React-RCTFabric/RCTFabric.framework/Headers/React/RCTScrollViewComponentView.h:12:
In file included from /Users/uloco/Library/Developer/Xcode/DerivedData/Smokeless-hessnrvxehuzzzbbcepctyxqzaau/Build/Products/Debug-iphonesimulator/React-RCTFabric/RCTFabric.framework/Headers/React/RCTMountingTransactionObserving.h:10:
In file included from /Users/uloco/Library/Developer/Xcode/DerivedData/Smokeless-hessnrvxehuzzzbbcepctyxqzaau/Build/Products/Debug-iphonesimulator/React-Fabric/React_Fabric.framework/Headers/react/renderer/mounting/MountingTransaction.h:10:
In file included from /Users/uloco/Library/Developer/Xcode/DerivedData/Smokeless-hessnrvxehuzzzbbcepctyxqzaau/Build/Products/Debug-iphonesimulator/React-Fabric/React_Fabric.framework/Headers/react/renderer/mounting/ShadowViewMutation.h:12:
In file included from /Users/uloco/Library/Developer/Xcode/DerivedData/Smokeless-hessnrvxehuzzzbbcepctyxqzaau/Build/Products/Debug-iphonesimulator/React-Fabric/React_Fabric.framework/Headers/react/renderer/mounting/ShadowView.h:13:
In file included from /Users/uloco/Library/Developer/Xcode/DerivedData/Smokeless-hessnrvxehuzzzbbcepctyxqzaau/Build/Products/Debug-iphonesimulator/React-Fabric/React_Fabric.framework/Headers/react/renderer/core/LayoutMetrics.h:12:
In file included from /Users/uloco/Library/Developer/Xcode/DerivedData/Smokeless-hessnrvxehuzzzbbcepctyxqzaau/Build/Products/Debug-iphonesimulator/React-Fabric/React_Fabric.framework/Headers/react/renderer/debug/DebugStringConvertible.h:17:
/Users/uloco/Library/Developer/Xcode/DerivedData/Smokeless-hessnrvxehuzzzbbcepctyxqzaau/Build/Products/Debug-iphonesimulator/React-Fabric/React_Fabric.framework/Headers/react/renderer/debug/flags.h:10:10: fatal error: 'react/debug/flags.h' file not found
#include <react/debug/flags.h>
         ^~~~~~~~~~~~~~~~~~~~~
/Users/uloco/Library/Developer/Xcode/DerivedData/Smokeless-hessnrvxehuzzzbbcepctyxqzaau/Build/Products/Debug-iphonesimulator/React-Fabric/React_Fabric.framework/Headers/react/renderer/debug/flags.h:10:10: note: did not find header 'debug/flags.h' in framework 'react' (loaded from '/Users/uloco/Library/Developer/Xcode/DerivedData/Smokeless-hessnrvxehuzzzbbcepctyxqzaau/Build/Products/Debug-iphonesimulator/React-Core')
1 error generated.
```

I created a repro project [here](https://github.com/uloco/repro-react-native-gesture-handler) and can reproduce the same error with a fresh react native project and just `react-native-gesture-handler` installed additionally.

### Steps to reproduce

1. Open the repro project at https://github.com/uloco/repro-react-native-gesture-handler
2. (optionally remove caches etc to make a clean depencency install with `npm run clean-deps`)
3. `npm install`
4. `npm run ios`
5. See error

Probably important: I am running on Apple Silicon

### Snack or a link to a repository

https://github.com/uloco/repro-react-native-gesture-handler

### Gesture Handler version

2.12.1

### React Native version

0.72.4

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by adolfogc** [comment]
Hi, I'm observing the same issue.

**Comment by m-bert** [comment]
Hi @uloco, @adolfogc! Have you tested that on `2.13.4`? We've added some changes to `podspec` and it is possible that these changes will help.

**Comment by uloco** [comment]
@m-bert I tried this and it seems to work. thank you!

**Comment by adolfogc** [comment]
Hi, thank you, yes using 2.13.4 helped!
