### ISSUE TITLE
Nested touchables do not work well with <ScrollView />

### ISSUE THREAD

**Issue by JoshuaJADaniel** [software-mansion/react-native-gesture-handler#2585]
### Description

If you have the following component structure: `Touchable` -> `ScrollView ` -> `Touchable`, scrolling causes the outer touchable to prevent touches. Users have to click once to fix the unresponsiveness, and then click again to work normally. I have attached a demo + Snack to help demonstrate this better.

NOTES:
1. I am using `BaseButton` in the demo + Snack to demonstrate what is happening more clearly; the issue here is still present when using regular touchables such as `TouchableWithoutFeedback` -- just that it is not immediately visible what the issue is.
2. I have only tested this on Android, so I am not sure if iOS also harbors this issue.

https://github.com/software-mansion/react-native-gesture-handler/assets/30093054/46327f78-c7db-4c66-b787-a88ba9aaf924

### Steps to reproduce

1. Open the Snack
2. Select Android
3. Run either locally or online
4. Scroll while holding down on one of the cards
5. Try to click on one of the cards

### Snack or a link to a repository

https://snack.expo.dev/@joshuajadaniel/need-to-click-twice-with-nested-touchables

### Gesture Handler version

~2.12.1

### React Native version

0.72.3

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

Expo managed workflow

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

Samsung Galaxy S22

### Acknowledgements

Yes

**Comment by m-bert** [comment]
Hi @JoshuaJADaniel! I've looked at the snack that you've provided and I've found out what was the problem. Here is [my PR](https://github.com/software-mansion/react-native-gesture-handler/pull/2586) that should fix this issue. Could you please give it a try and confirm that it indeed solves the problem?

**Comment by JoshuaJADaniel** [comment]
Hey @m-bert, would I have to test this change via `patch-package` with a release build?

**Comment by m-bert** [comment]
Yes. Alternatively you can install gesture handler directly from my branch - that should also work.

**Comment by JoshuaJADaniel** [comment]
Hey @m-bert, just updated to ^2.13.1, however, the issue appears to persist even with this PR.

Tested by running the same provided code locally (since Snack only allows ~2.12.0 for Expo SDK49).

**Comment by m-bert** [comment]
Have you changed something in your code? I've copied your snack, tested it on Pixel 6 emulator and my S20+ and I no longer see this issue after applying my PR.
