### ISSUE TITLE
Error on vitejs build: Could not load react-native-web/Libraries/Renderer/shims/ReactNative

### ISSUE THREAD

**Issue by jardelbordignon** [software-mansion/react-native-gesture-handler#2590]
### Description

When installing a lib in vitejs according to the doc 
https://docs.swmansion.com/react-native-gesture-handler/docs/installation/#web 
it is possible to run the application successfully, however when running the yarn build command errors are displayed.

### Steps to reproduce

1. access https://stackblitz.com/edit/vitejs-react-native-gesture-handler-k8wghi
2. open terminal, stop running and run -> yarn build

### Snack or a link to a repository

https://stackblitz.com/edit/vitejs-react-native-gesture-handler-k8wghi

### Gesture Handler version

2.12.1

### React Native version

react-native-web 0.19.8

### Platforms

Web

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by m-bert** [comment]
Okay, thanks to @kacperkapusciak we've managed to solve this. In your `vite.config.js` after `alias` you have to add `extensions`:

```
 resolve: {
      alias: {
        'react-native': 'react-native-web',
      },
      extensions: ['.web.js', '.js', '.ts', '.tsx', '.jsx'],
    },
```

That way you force bundler to look for `.web.js` files first. Let us know if it helps.

**Comment by codeion** [comment]
Hi, v2.13.0 has an issue with vitejs build.
Looks like an issue with import path (there should be` ../../State`).

`Error: Build failed with 1 error:`
`file: 'node_modules/react-native-gesture-handler/lib/module/web/handlers/HoverGestureHandler.js',`
`lineText: "import { State } from '../../../src/State';",`
`text: 'Could not resolve "../../../src/State"'`
