### ISSUE TITLE
Buttons(web): Nested Button onPress (Rect/Borderless etc) bubbles up

### ISSUE THREAD

**Issue by hirbod** [software-mansion/react-native-gesture-handler#2595]
### Description

We're using `RectButton` to create list items, so we wrap the entire component with `RectButton`. Inside the `RectButton`, there can be nested children, which are also `RectButton`'s.

While this works perfectly fine on iOS and Android (clicking the nested button does NOT activate the parent), it doesn't work as expected on the web. Nested buttons on the web will bubble up and propagate to the top.

Fixing this would have been straightforward if we had an option to trigger `event.stopImmediatePropagation` or `event.stopPropagation` for the web. However, the events from `onPress` are not the native browser events, so I am unable to implement this.

In my Snack, you can see that clicking the inner button activates both buttons and triggers both `onPress` events.
Works fine on iOS and Android.

So I think we need to introduce three props for web: shouldStopPropagation, shouldStopImmediatePropagation and shouldPreventDefault. That would be the easiest imho.

`Pressable` by react-native works out of the box on web, but has issues on Android, that's why we want to migrate to RNGH

### Steps to reproduce

Check out my Snack.

### Snack or a link to a repository

https://snack.expo.dev/@hirbod/rngh-onpress-handlers

### Gesture Handler version

2.9.0

### React Native version

0.72.3

### Platforms

Web

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by hirbod** [comment]
Our internal App uses SDK 49 and RNGH 2.12 and it breaks for us.

**Comment by hirbod** [comment]
Furthermore, I just changed from SDK 48 to 49 inside the Snack and I have to click twice for it to trigger.

**Comment by m-bert** [comment]
I've just created test app using `npx create-expo-app`. SDK version 49, I've added `gesture-handler` 2.12.1 and everything works as expected. Pressing inner button doesn't activate the outer one. I do not have much info about this issue nor can I reproduce it. 

Do you have any other idea how we can check that?

**Comment by hirbod** [comment]
I'll make some tests and report back.

**Comment by hirbod** [comment]
@m-bert, upgrading from RNGH 2.12 to 2.13.1 fixed the issue with SDK49. Thank you very much. I was aware of the issue for a while (though I didn't report it), so I didn't expect it to be fixed in the newest version. Sorry for the false alarm.

Anyway, do you think there might be cases where we'd actually want to propagate? I can imagine that having controllable propagation could be beneficial. If you disagree, feel free to close the issue.

**Comment by m-bert** [comment]
@hirbod I'm glad to hear that upgrading gesture handler fixed your problem. 

To be honest, I don't really see use case for this propagation. While I can imagine that having this option could be useful in some way, I think it also could do more harm than good and lead to strange usages vulnerable to bugs. Although I could be wrong.

If you see a valid use case for that, I'd be happy to hear about it. For now I'm gonna close this issue, since it is already gone in 2.13.1.
