### ISSUE TITLE
Build failure with new RN architecuture -  ld: symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by Manojkumar-Subramaniam** [software-mansion/react-native-gesture-handler#2598]
### Description

Build failure with new React Native Architecture. This error does not happen with old architecture.

Error:

Undefined symbols for architecture x86_64:
  "facebook::react::RNGestureHandlerButtonProps::RNGestureHandlerButtonProps(facebook::react::PropsParserContext const&, facebook::react::RNGestureHandlerButtonProps const&, facebook::react::RawProps const&)", referenced from:
      void facebook::react::RawPropsParser::prepare<facebook::react::RNGestureHandlerButtonProps>() in libRNGestureHandler.a(RNGestureHandlerButtonComponentView.o)
      std::__1::__shared_ptr_emplace<facebook::react::RNGestureHandlerButtonProps, std::__1::allocator<facebook::react::RNGestureHandlerButtonProps>>::__shared_ptr_emplace[abi:v15006]<facebook::react::PropsParserContext const&, facebook::react::RNGestureHandlerButtonProps const, facebook::react::RawProps const&>(std::__1::allocator<facebook::react::RNGestureHandlerButtonProps>, facebook::react::PropsParserContext const&, facebook::react::RNGestureHandlerButtonProps const&&, facebook::react::RawProps const&) in libRNGestureHandler.a(RNGestureHandlerButtonComponentView.o)
  "facebook::react::RNGestureHandlerButtonComponentName", referenced from:
      facebook::react::ConcreteShadowNode<&facebook::react::RNGestureHandlerButtonComponentName, facebook::react::YogaLayoutableShadowNode, facebook::react::RNGestureHandlerButtonProps, facebook::react::RNGestureHandlerButtonEventEmitter, facebook::react::RNGestureHandlerButtonState>::Handle() in libRNGestureHandler.a(RNGestureHandlerButtonComponentView.o)
      facebook::react::ConcreteShadowNode<&facebook::react::RNGestureHandlerButtonComponentName, facebook::react::YogaLayoutableShadowNode, facebook::react::RNGestureHandlerButtonProps, facebook::react::RNGestureHandlerButtonEventEmitter, facebook::react::RNGestureHandlerButtonState>::Name() in libRNGestureHandler.a(RNGestureHandlerButtonComponentView.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### Steps to reproduce

1. Upgrade to latest RN version(0.72.4)
2. Enable Latest Architecture : RCT_NEW_ARCH_ENABLED=1 bundle exec pod install
3. Build IOS app. 

npx react-native info:

System:
  OS: macOS 13.5.2
  CPU: (10) arm64 Apple M1 Pro
  Memory: 76.47 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.8.0
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 8.18.0
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2022.08.15.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/msubramaniam/.rvm/gems/ruby-2.7.5/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10671973
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.16
    path: /usr/bin/javac
  Ruby:
    version: 2.7.5
    path: /Users/msubramaniam/.rvm/rubies/ruby-2.7.5/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: true

### Snack or a link to a repository

Private repo

### Gesture Handler version

2.13.0

### React Native version

0.72.4

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by m-bert** [comment]
Hi @Manojkumar-Subramaniam! I've just bumped `react-native` version to 0.72.4 in our FabricExample app and it works fine. Also, as the message that you've provided references `RNGestureHandlerButton`, I've added one to see whether it works or not and everything is ok.

If you still experience this problem, could you please provide a reproduction, so I can check that?

**Comment by csillaj** [comment]
I have the same issue after updating react native to 0.76 and react-native-gesture-handler to 2.21.2

**Comment by francoangulo** [comment]
anyone experienced this issue? i'm having it right now and can't find a solution...
it happens when I enable the new architecture with react-native v0.81.4
react-native-gesture-handler —> 2.28.0
