### ISSUE TITLE
2.13.1 - BaseButton onPress triggering twice 

### ISSUE THREAD

**Issue by paranjothipj** [software-mansion/react-native-gesture-handler#2603]
### Description

After updating from 2.12.1 to 2.13.1 all the buttons onPress calling twice 

### Steps to reproduce

BaseButton - clicks on it

### Snack or a link to a repository

https://snack.expo.dev/

### Gesture Handler version

2.13.1

### React Native version

0.72.3

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

Samsung Galaxy s22

### Acknowledgements

Yes

**Comment by m-bert** [comment]
Hi @paranjothipj! I've just checked that and I have not noticed double callbacks. Could you please provide repro so I can have a look at it?

**Comment by kesha-antonov** [comment]
We have same problem

**Comment by m-bert** [comment]
In that case, could you provide reproduction @kesha-antonov?

**Comment by kesha-antonov** [comment]
> In that case, could you provide reproduction @kesha-antonov?

It can be reproduced only on Poco android 11 in our case
It works well on Pixel 7 or Emulator android 11/13

**Comment by KestasVenslauskas** [comment]
Same issue on Pixel 6a
