### ISSUE TITLE
Guides need to show importing

### ISSUE THREAD

**Issue by gaearon** [software-mansion/react-native-gesture-handler#2604]
### Description

I'm reading https://docs.swmansion.com/react-native-gesture-handler/docs/quickstart/ and it's frustrating that there are no import statements. So I need to guess where to get `GestureDetector`, `Animated.View`, `useSharedValue`, `Gesture`, etc, from. This is particularly thorny because these example "span" two different libraries — also it's very easy to get confused about which `Animated` is being talked about.

I suggest adding clear import sections to https://docs.swmansion.com/react-native-gesture-handler/docs/quickstart/ and other guides. Ideally examples always need to be ready to be copy pasted.

Thanks!

### Steps to reproduce

Open docs

### Snack or a link to a repository

irrelevant

### Gesture Handler version

irrelevant

### React Native version

irrelevant

### Platforms

Android, iOS, Web

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by gaearon** [comment]
(I couldn't figure out where to file docs issues so filed here)

**Comment by kacperkapusciak** [comment]
Hi @gaearon 👋 

it's a great suggestion!

We're well aware the Gesture Handler docs aren't in the best shape. A full-rewrite of the RNGH documentation is inevitable same as we did with [Reanimated docs not so long ago](https://twitter.com/kacperkapusciak/status/1689349007892492289) but it'll take some time considering our limited resources.

In the meantime, I'll try to cleanup the docs a bit and add the imports as you suggest in https://github.com/software-mansion/react-native-gesture-handler/pull/2607.

Cheers
