### ISSUE TITLE
How to track multiple finger positions?

### ISSUE THREAD

**Issue by ugurdalkiran** [software-mansion/react-native-gesture-handler#2615]
### Description

I want to capture the points where multiple fingers touch the screen and take action on them. But I understood that all the examples were prepared for just a finger touch.

For example, I think the **handlerTag** value coming from the **onBegin** function will change as 1-2-3-4 depending on the finger. But this value always remains 1.

Is it normal that I expect this value to be 2 when I touch the screen with the second finger?

```js
const pan = Gesture.Pan()
	.onBegin(e => {
		console.log("handlerTag: " + e.handlerTag + " -- numberOfPointers: " + e.numberOfPointers);
	});

<GestureDetector gesture={pan}>
	...
</GestureDetector>
```

### Steps to reproduce

1. Gesture Pan prints the data on the screen using onBegin - onStart - onUpdate.

### Snack or a link to a repository

https://github.com/software-mansion/react-native-gesture-handler/

### Gesture Handler version

2.12.0

### React Native version

0.72.3

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Android emulator

### Acknowledgements

Yes

**Comment by m-bert** [comment]
Hi @ugurdalkiran! I've just looked into it.

>Is it normal that I expect this value to be 2 when I touch the screen with the second finger?

No, with the code that you've provided it is not correct. The thing is, you expect `onBegin` to be called twice, but the handler has already been activated. 

f you use different callback, like `onChange` or `onUpdate` you will see that it in fact logs correct amount of touches.

Let me know if there is anything else that I can help you with!

**Comment by ugurdalkiran** [comment]
Thank you for your answer. @m-bert 

Actually, when I add the **onTouchStart** function to the **View** component, I can see that it is called twice. That's what I expected.

**Comment by m-bert** [comment]
I'm happy to hear that everything works fine!
