### ISSUE TITLE
Odd behavior of content overflow inside touchable

### ISSUE THREAD

**Issue by JoshuaJADaniel** [software-mansion/react-native-gesture-handler#2619]
### Description

When content within a touchable uses absolute positioning to move elements outside its boundaries, the overflowing content is hidden. In contrast, once the touchable is replaced with a view, the overflowing content becomes visible.

![b23d86b0-3e81-495d-beaa-782fdad66fef](https://github.com/software-mansion/react-native-gesture-handler/assets/30093054/b3479a49-0898-4051-bf98-5640f85e2183)

### Steps to reproduce

1. Open the Snack
2. Select Android
3. Run either locally or online

### Snack or a link to a repository

https://snack.expo.dev/@joshuajadaniel/overflow-hidden-inside-button

### Gesture Handler version

~2.12.0

### React Native version

0.72.3

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

Expo managed workflow

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

Samsung Galaxy S22

### Acknowledgements

Yes

**Comment by m-bert** [comment]
Hi @JoshuaJADaniel! I've just looked at it. 

It works on my Samsung S20+ and on Pixel 6 emulator. Also, the snack that you've provided works fine. Could you give some more information?

**Comment by JoshuaJADaniel** [comment]
Hey @m-bert, just tested again today.

In development server running through Expo Go, the issue still appears.

In release build, it works as expected.ut this time created a release build instead of running it through development server on Expo Go. Seems like it works as expected when running the release build

**Comment by JoshuaJADaniel** [comment]
That could perhaps be the case, although sometimes bumping up or down a package version does impact the Expo Go behavior, which would imply that the `package.json` versions do matter to some extent at least. In any case, since the release build is working as expected, I am closing this issue.

**Comment by j-piasecki** [comment]
> That could perhaps be the case, although sometimes bumping up or down a package version does impact the Expo Go behavior, which would imply that the package.json versions do matter to some extent at least.

That's correct, Expo Go is compiled with specific versions of libraries, but the JS code is generated by the bundler. So if changes were in the JS code they would be reflected in Expo Go, if they were in the native code, they would not.

**Comment by j-piasecki** [comment]
This issue was most likely fixed by [this](https://github.com/software-mansion/react-native-gesture-handler/pull/2039/files#diff-9820d8ba53ce8a7669a78fc938b40868e98b4d5d765d23ec0b9764d96ef78b9cR134) change.

**Comment by oleg1994** [comment]
I'm experiencing same behavior 
 "expo": "^50.0.6",
 "react-native-gesture-handler": "~2.14.0"
