### ISSUE TITLE
Foreground={true} removes background for touchables

### ISSUE THREAD

**Issue by JoshuaJADaniel** [software-mansion/react-native-gesture-handler#2632]
### Description

Not sure if this is expected behavior mentioned somewhere in the docs, but setting the `foreground` prop to `true` on any touchable causes any background styles to be discarded in Android.

![image](https://github.com/software-mansion/react-native-gesture-handler/assets/30093054/37567df3-903d-4d4a-8103-f9e5bfdc3743)

### Steps to reproduce

1. Open the Snack
2. Select Android
3. Run either locally or online

### Snack or a link to a repository

https://snack.expo.dev/@joshuajadaniel/rngh---foreground-property-effect-on-background

### Gesture Handler version

~2.12.0

### React Native version

0.72.3

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

Expo managed workflow

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Android emulator

### Acknowledgements

Yes

**Comment by m-bert** [comment]
Hi @JoshuaJADaniel! I've just created [this PR](https://github.com/software-mansion/react-native-gesture-handler/pull/2642), could you please check if it helps?

**Comment by JoshuaJADaniel** [comment]
Hey @m-bert, your changes fix the issue while testing in release build.
