### ISSUE TITLE
v2.13+ not building on tvOS

### ISSUE THREAD

**Issue by RuudBurger** [software-mansion/react-native-gesture-handler#2647]
### Description

Since #2455 was merged and v2.13 was released the project isn't building on an app that uses react-native-tvos. This is because it's trying to load iOS specific code on the tvOS target.

### Steps to reproduce

1. Build package for tvOS
2. Get "unavailable on tvOS" errors for the new hover functions

### Snack or a link to a repository
https://github.com/react-native-tvos/react-native-tvos

### Gesture Handler version

2.13.0

### React Native version

0.72.6

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by m-bert** [comment]
Hi @RuudBurger! I've made [this PR](https://github.com/software-mansion/react-native-gesture-handler/pull/2654), could you please check if it helps? I've kept it in draft for a while, but now it is ready to be tested.

**Comment by geroale** [comment]
Same issue here

**Comment by m-bert** [comment]
So could you please check @geroale if my PR allows you to build app?

**Comment by m-bert** [comment]
Okay, I've just checked comments on PR (I thought that I'll get response here rather than there). 

Seems like hover is not the only thing that breaks build on tvOS. It would be great if you could provide repro so we can check what else fails. I know that you pointed out which line doesn't work - I'll look at it, but I'd like to see which line in your code caused that error.

**Comment by RuudBurger** [comment]
There is no line in our code that is the issue. Just including the library as is gives the error mentioned. 
I currently use v2.12.1 without issues, only doing the update to v2.13 gives the mentioned issues.

**Comment by arjunsj** [comment]
same issue i faced . that PR is working fine for me thanks @m-bert

**Comment by arunpandiyanp** [comment]
Same issue I faced . That mentioned PR is working fine for me thanks @m-bert
