### ISSUE TITLE
[!] Invalid `RNGestureHandler.podspec` file: undefined method `install_dependencies' for Pod:Module

### ISSUE THREAD

**Issue by dprajapati1179** [software-mansion/react-native-gesture-handler#2652]
### Description

[!] Invalid `RNGestureHandler.podspec` file: undefined method `install_dependencies' for Pod:Module
Did you mean?  install_flipper_dependencies.

Unable to proceed for ios build as pod install not working.

### Steps to reproduce

1. Upgrade cocoapods to the latest 1.13.0.
2. Install pods by deleting node_modules & yaarn.lock or pacagejson.lock file
3. You will find the invalid pod file error like bellow,

### Snack or a link to a repository

https://snack.expo.io/

### Gesture Handler version

2.13.3

### React Native version

0.70.13

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

Paper (Old Architecture)

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by dprajapati1179** [comment]
TEMPORARY SOLUTION:

1. Change your version to 2.9.0 (without the ^)
2. Delete node_modules & package-lock.json
3. yarn && cd ios/ && pod install

package.json
"react-native-gesture-handler": "2.9.0",

**Comment by j-piasecki** [comment]
Could you install Gesture Handler 2.13.3, verify that it's still broken, and check if the following patch solves the problem?
[react-native-gesture-handler+2.13.3.patch](https://github.com/software-mansion/react-native-gesture-handler/files/13067873/react-native-gesture-handler%2B2.13.3.patch)

**Comment by geydson** [comment]
Hello, even following the recommendation to update to version 2.13.3 the error persists, exclude the node_module folder, pods, podfile.lock and yarn.lock, even so the error persists.

I followed the recommendation @dprajapati1179  to use version "2.9.0"(without the ^):

package.json
"react-native-gesture-handler": "2.9.0",

And I was able to run the project normally, in version "2.13.3" the problem still persists, I was only able to run the "pod install" command with version "2.9.0" (without the ^).


[!] Invalid `Podfile` file: 
[!] Invalid `RNGestureHandler.podspec` file: undefined method `install_dependencies' for Pod:Module.
 
#  from /Users/werike.santos/Desktop/Projetos/WebtradeMobile/node_modules/react-native-gesture-handler/RNGestureHandler.podspec:48
#  -------------------------------------------
#    else
>      install_dependencies(s, new_arch_enabled)
#    end
#  -------------------------------------------
.
 
#  from /Users/werike.santos/Desktop/Projetos/WebtradeMobile/ios/Podfile:18
#  -------------------------------------------
#    use_expo_modules!
>    config = use_native_modules!
#  

My machine configuration:
Macbook Intel i5

Gesture Handler version
2.13.3

React Native version
0.70.8

expo sdk
47.0.14

Platforms
iOS

Workflow
None

**Comment by geydson** [comment]
> Try using version 2.13.4

@j-piasecki Thank you very much, it worked version 2.13.4 worked correctly.
