### ISSUE TITLE
Events on Touchables are triggered twice since 2.13.0 on Android device only

### ISSUE THREAD

**Issue by mattijsf** [software-mansion/react-native-gesture-handler#2655]
### Description

Adding a `TouchableOpacity` (or `TouchableWithoutFeedback` etc) is calling various events such as `onPress` twice since 2.13.0 on Android only and only on a physical device. Downgrading to 2.12.1 fixed the issue.

### Steps to reproduce

1. Create a new project: `npx react-native@latest init GestureHandlerTest`
2. `npm i react-native-gesture-handler@2.13.3`
3. Add following app snippet:

```tsx
/* eslint-disable prettier/prettier */
/* eslint-disable react-native/no-inline-styles */
import React, { useState } from 'react';
import {Text, View} from 'react-native';
import {
  GestureHandlerRootView,
  TouchableOpacity,
} from 'react-native-gesture-handler';

function App(): JSX.Element {
  const [pressCount, setPressCount] = useState(0);

  return (
    <GestureHandlerRootView style={{flex: 1}}>
      <View style={{flex: 1, backgroundColor: '#000', justifyContent: 'center', alignItems: 'center', gap: 10}}>
      <Text style={{ color: '#fff' }}>Press Count: {pressCount}</Text>
        <TouchableOpacity onPress={(): void => setPressCount(c => c + 1)}>
          <View style={{backgroundColor: '#ff0000', width: 100, height: 100}} />
        </TouchableOpacity>
      </View>
    </GestureHandlerRootView>
  );
}

export default App;

```
5. `npm run android`
6. Observe the "Press Count" label when tapping the square view:

| Android Device (🐞 broken) | Android Emulator(✅ working) |
|---|---|
| <video src="https://github.com/software-mansion/react-native-gesture-handler/assets/706368/d8a9b6c2-18cf-45ea-b492-6f5dbd5c50fc" /> |  <video src="https://github.com/software-mansion/react-native-gesture-handler/assets/706368/70349843-b896-4537-89ea-eca44f137d43" /> |

### Snack or a link to a repository

https://github.com/mattijsf/gesture-handler-duplicate-events-test

### Gesture Handler version

2.13.0

### React Native version

0.72.6

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

Pixel 6 Pro

### Acknowledgements

Yes

**Comment by exentrich** [comment]
Confirm! Same problem on a physical device Android 14

**Comment by m-bert** [comment]
Hi! I think we identified what causes this issue. Do you have any accessibility settings turned on? And if so, could you please check https://github.com/software-mansion/react-native-gesture-handler/pull/2657?

**Comment by wbercx** [comment]
I have [Tasker for Android](https://tasker.joaoapps.com/) enabled on my device, which uses Accessibility features. While enabled, `onPress` does fire twice.

Your PR resolves that.

**Comment by Bruce-Ming** [comment]
@m-bert This problem reappeared in 2.13.4. I looked at the source code and found that it changed back.
![image](https://github.com/software-mansion/react-native-gesture-handler/assets/37186519/d653100c-c015-41e9-805c-5d47b2f72056)
this problem

**Comment by m-bert** [comment]
Hi @Bruce-Ming! No, it didn't reappear. Fix for that issue was merged after the 2.13.4 release, so it has not been released yet.

**Comment by CaseyDCascade** [comment]
@m-bert hello, i am seeing this issue again on version 2.20.2. my react native version is 0.73.7-1 so i am using the appropriate version. trying to use the latest version and 2.12.2 gives me react-native-gesture-handler:compileDebugKotlin errors, so i'm not sure what other version could be working for me. please let me know if there's any other information i can provide you

**Comment by m-bert** [comment]
Hi @CaseyDCascade! I've just tested that on latest _**Gesture Handler**_ (from `main` branch) on RN `0.79.0` and it seems to work fine.

0.73 is quite old, 0.80 is right around the corner. If you see this issue on latest versions you can open new issue with a minimal reproduction.
