### ISSUE TITLE
Elements not selected on tap with TalkBack on (~2.13)

### ISSUE THREAD

**Issue by antonandreyev** [software-mansion/react-native-gesture-handler#2665]
### Description

RNGH 2.13 makes Android TalkBack not able to select any element on the screen on taps. This is not the case with 2.12. Tested with RN 71 and 72 and on different Android devices in Debug and Release mode. 

See attached video: 

https://github.com/software-mansion/react-native-gesture-handler/assets/5842508/56c73fdd-f180-4c38-8e5c-90b30a927446

Must be somehow related to https://github.com/software-mansion/react-native-gesture-handler/pull/2234 included in 2.13.0

### Steps to reproduce

1. have GestureHandlerRootView around the content (maybe at the root of the App)
2. enable TalkBack
3. tap on any element on the screen
4. see it is not selected by TalkBack service

### Snack or a link to a repository

https://github.com/antonandreyev/rn-gh-talk-back-repro

### Gesture Handler version

2.13.4

### React Native version

0.72.6

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

Real device

### Device model

Samsung Galaxy A41 (Android 12)

### Acknowledgements

Yes

**Comment by m-bert** [comment]
Hi @antonandreyev! Could you please check if [this PR](https://github.com/software-mansion/react-native-gesture-handler/pull/2669) fixes that problem?

**Comment by flo-sch** [comment]
Hi, I experienced a similar issue with TalkBack when bumping also from 2.12 to 2.13.
When patching this fix locally within node_modules directly, TalkBack is happy again :)

Looking forward a new release containing this 🙏
