### ISSUE TITLE
Tap gesture example crashes in Expo Go

### ISSUE THREAD

**Issue by henrymoulton** [software-mansion/react-native-gesture-handler#2667]
### Description

https://github.com/software-mansion/react-native-gesture-handler/assets/30093692/a4b6b0f7-09f5-4a6d-be6d-e15b8738a4cd

### Steps to reproduce

1. Copy in code from https://docs.swmansion.com/react-native-gesture-handler/docs/gestures/tap-gesture#example
2. `npx create-expo-app --template`
3. npx expo install react-native-reanimated react-native-gesture-handler
4. paste in code
5. tap on view 
6. watch it crash

### Snack or a link to a repository

https://gist.github.com/henrymoulton/3f86a2a781f7bb1c814e2ff8b8c0400a
https://snack.expo.dev/@henry12345678/courageous-green-truffles?platform=ios

### Gesture Handler version

"2.12.1"

### React Native version

0.72.6

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

Expo managed workflow

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by henrymoulton** [comment]
I'd provide a Snack but it seems it doesn't use Expo v49 
<img width="725" alt="image" src="https://github.com/software-mansion/react-native-gesture-handler/assets/30093692/a2386e24-0236-490d-848b-185c72b2f8fc">

**Comment by henrymoulton** [comment]
Updated with Snack https://snack.expo.dev/@henry12345678/courageous-green-truffles?platform=ios

**Comment by henrymoulton** [comment]
https://github.com/software-mansion/react-native-gesture-handler/assets/30093692/e14815fe-fecb-4e31-9709-7be71303be75

Hmm I've got a reproduction of the crash using the provided Snack

**Comment by henrymoulton** [comment]
https://github.com/software-mansion/react-native-gesture-handler/assets/30093692/9d8bb1d7-b754-4746-bbc2-3edea847c684

I've got a reproduction of the crash using Snack, can you verify that it crashes in the Snack provided for you?

**Comment by henrymoulton** [comment]
Hmm weird, I've got a reproduction of the crash using Snack, can you verify that it crashes in the Snack provided for you?


https://github.com/software-mansion/react-native-gesture-handler/assets/30093692/36c2e273-c1cd-445e-bc26-cdfe25d0ab7b

**Comment by m-bert** [comment]
It does crash on snack, however we had many cases where something doesn't work on snack but works on other devices (physical, emulators/simulators) - that's why we double-check everything outside of snack.

**Comment by m-bert** [comment]
Okay, I've just got rid of that babel error. The app indeed crashed. Moreover it will crash outside of Expo Go.

This is due to `Alert.alert`. Our callback are workletized and there's no access to `Alert` on UI thread. To make this work, you would have to add `.runOnJS(true)` - then app won't crash. We will change it in our documentation soon.
