### ISSUE TITLE
react-native-gesture-handler module was not found. Make sure you're running your app on the native platform and your code is linked properly (cd ios && pod install && cd ..)

### ISSUE THREAD

**Issue by durejagaurav** [software-mansion/react-native-gesture-handler#2668]
### Description

[react-native-gesture-handler] react-native-gesture-handler module was not found. Make sure you're running your app on the native platform and your code is linked properly (cd ios && pod install && cd ..).

Getting this error while build for ios. Did all things

I am using:

    "react-native": "0.72.6",
    "react-native-gesture-handler": "^2.13.4",

### Steps to reproduce

[react-native-gesture-handler] react-native-gesture-handler module was not found. Make sure you're running your app on the native platform and your code is linked properly (cd ios && pod install && cd ..).

### Snack or a link to a repository

https://github.com/software-mansion/react-native-gesture-handler

### Gesture Handler version

2.13.4

### React Native version

0.72.6

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Device model

ios 14

### Acknowledgements

Yes

**Comment by mudassir333** [comment]
@durejagaurav  Please let us know how you solved this issue . I am using it with 
Gesture handler : 2.14.1
React Native : 0.72.7 ,

It will be very helpful for us.

**Comment by durejagaurav** [comment]
> @durejagaurav Please let us know how you solved this issue . I am using it with Gesture handler : 2.14.1 React Native : 0.72.7 ,
> 
> It will be very helpful for us.

I did nothing special. Just followed the instructions mentioned in https://docs.swmansion.com/react-native-gesture-handler/docs/fundamentals/installation
