### ISSUE TITLE
Swipeable on web blocks scrolling with touch, mousewheel still works.

### ISSUE THREAD

**Issue by TNAJanssen** [software-mansion/react-native-gesture-handler#2678]
### Description

When using Swipeable inside a ScrollView or Flatlist it will block scrolling using touch. The scrollwheel still works

### Steps to reproduce

1. Create Swipeable item in Flatlist
2. Open in a webbrowser using a touch device or chrome device simulator
3. Try scrolling with 

### Snack or a link to a repository

https://snack.expo.dev/@tnajanssen/swipeable-scroll-demo

### Gesture Handler version

2.13.4

### React Native version

0.72.7

### Platforms

Web

### JavaScript runtime

Hermes

### Workflow

Expo managed workflow

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

Real device

### Device model

All

### Acknowledgements

Yes

**Comment by m-bert** [comment]
Hi! I'm closing this issue since it was already reported in [this one](https://github.com/software-mansion/react-native-gesture-handler/issues/2617).
