### ISSUE TITLE
Not compatible with React Native 0.73 on Android

### ISSUE THREAD

**Issue by jeroenvanhattem** [software-mansion/react-native-gesture-handler#2681]
### Description

I have been trying to upgrade to React Native 0.73 (0.73-rc5). I have iOS running just fine. I do however receive an error related to react-native-gesture-handler when trying to build Android. 

<img width="833" alt="Screenshot 2023-11-23 at 11 01 04" src="https://github.com/software-mansion/react-native-gesture-handler/assets/15092050/0ec063f2-d146-4eac-ba7a-05ae5ed8781e">

#### Versions
- Gradle =  8.0.1
- Kotlin = 1.9.20
- compileSdkVersion = 34
- targetSdkVersion = 34
- buildToolsVersion = "34.0.0"
- minSdkVersion = 21
- ndkVersion = "25.0.8775105"

### Steps to reproduce

1. Upgrade react-native and its packages
2. Follow the [diff guide](https://react-native-community.github.io/upgrade-helper/?from=0.70.6&to=0.73.0-rc.4) for changing the project files.
3. `./gradlew clean`
4. `yarn android` or `yarn start --reset-cache` and then select Android

### Snack or a link to a repository

google.com

### Gesture Handler version

2.13.4

### React Native version

0.73.0-rc.5

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

Android emulator

### Acknowledgements

Yes

**Comment by phamhieu1412** [comment]
same error
react-native: 0.73.1
react-native-gesture/handler: 2.14.0
how to fix this error???
