### ISSUE TITLE
Document velocity values on iOS simulator not working

### ISSUE THREAD

**Issue by henrymoulton** [software-mansion/react-native-gesture-handler#2686]
### Description

See issue here https://stackoverflow.com/questions/70390265/uipangesturerecognizer-velocity-return-0-in-simulator-macbook-m1

### Steps to reproduce

1. Use iOS simulator
2. log out velocity values in a Gesture.Pan

### Snack or a link to a repository

https://snack.expo.dev/@henry12345678/witty-indigo-hummus

### Gesture Handler version

2.13.4

### React Native version

0.71

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by j-piasecki** [comment]
We tested it just now on two macs (M1 Pro with Ventura and M2 Pro with Sonoma) and the velocity seems to be alright (and is definitely not zero) on both of them. If you have any pending updates of the OS or XCode, it could be worth checking it out.

That said, if it's an issue with the simulator or the toolchain itself there's not much we can do about it 😞.
