### ISSUE TITLE
RNGestureHandlerPackage Problem is Android 

### ISSUE THREAD

**Issue by shubhanshubb** [software-mansion/react-native-gesture-handler#2716]
### Description

Previously It was working but after 2-3 days I am getting this issue and in IOS it's working perfectly
/android/app/src/main/java/com/arpitrw/wiingytutorapp/MainApplication.java:15: error: package com.swmansion.gesturehandler.react does not exist
import com.swmansion.gesturehandler.react.RNGestureHandlerPackage;
                                         ^
android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:37: error: cannot find symbol
import com.swmansion.gesturehandler.RNGestureHandlerPackage;
                                   ^
  symbol:   class RNGestureHandlerPackage
  location: package com.swmansion.gesturehandler
android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:112: error: cannot find symbol
      new RNGestureHandlerPackage(),

### Steps to reproduce

/android/app/src/main/java/com/arpitrw/wiingytutorapp/MainApplication.java:15: error: package com.swmansion.gesturehandler.react does not exist
import com.swmansion.gesturehandler.react.RNGestureHandlerPackage;
                                         ^
android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:37: error: cannot find symbol
import com.swmansion.gesturehandler.RNGestureHandlerPackage;
                                   ^
  symbol:   class RNGestureHandlerPackage
  location: package com.swmansion.gesturehandler
android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:112: error: cannot find symbol
      new RNGestureHandlerPackage(),

### Snack or a link to a repository

www.github.com/shubhanshubb

### Gesture Handler version

2.14.0

### React Native version

0.72.7

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by shubhanshubb** [comment]
/Users/shubhanshu/Desktop/demoApp/android/app/src/main/java/com/arpitrw/wiingytutorapp/MainApplication.java:15: error: package com.swmansion.gesturehandler.react does not exist
import com.swmansion.gesturehandler.react.RNGestureHandlerPackage;
                                         ^
/Users/shubhanshu/Desktop/demoApp/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:37: error: cannot find symbol
import com.swmansion.gesturehandler.RNGestureHandlerPackage;
                                   ^
  symbol:   class RNGestureHandlerPackage
  location: package com.swmansion.gesturehandler
/Users/shubhanshu/Desktop/demoApp/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:112: error: cannot find symbol
      new RNGestureHandlerPackage(),

**Comment by j-piasecki** [comment]
If you have `import com.swmansion.gesturehandler.react.RNGestureHandlerPackage;` anywhere in your java files, please change it to `import com.swmansion.gesturehandler.RNGestureHandlerPackage;`.

Otherwise, it's hard to tell exactly what's happening without a reproduction. You could also try reinstalling `node_modules` and doing a clean android build to see if it's caused by some stale cache.

**Comment by samy-tcheik** [comment]
i've just fixed it but adding these lines in l my android/build.gradle file

buildscript {
    ext {
        kotlinVersion = '1.9.0'
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.0"
    }
}
hope this comment will help anyone facing this issue
