### ISSUE TITLE
Warning with `Task :react-native-gesture-handler:processDebugManifest`

### ISSUE THREAD

**Issue by ciuliene** [software-mansion/react-native-gesture-handler#2725]
### Description

This warning occurs while building for Android

```
> Task :react-native-gesture-handler:processDebugManifest
package="com.swmansion.gesturehandler" found in source AndroidManifest.xml: /Users/gerrico/Documents/EmersonConnected/emerson-connected-app/node_modules/react-native-gesture-handler/android/src/main/AndroidManifest.xml.
Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported, and the value is ignored.
Recommendation: remove package="com.swmansion.gesturehandler" from the source AndroidManifest.xml: /Users/gerrico/Documents/EmersonConnected/emerson-connected-app/node_modules/react-native-gesture-handler/android/src/main/AndroidManifest.xml.
```

### Steps to reproduce

Just run

```sh
npm run android
```

or 

```sh
npx react-native run-android
```

### Snack or a link to a repository

Private repository

### Gesture Handler version

2.14.0

### React Native version

0.73.2

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by ciuliene** [comment]
It's not so easy, as the repository is private. I'll try to provide you with an example as soon as possible

**Comment by jacksonlevine** [comment]
Seconding this bug. Very annoying.

**Comment by latekvo** [comment]
Hi @ciuliene and @jacksonlevine 

I've opened [this PR](https://github.com/software-mansion/react-native-gesture-handler/pull/3077) to hopefully fix the issues you're encountering, please let me know if that PR fixes those issues for you.

**Comment by ciuliene** [comment]
> Hi @ciuliene and @jacksonlevine
> 
> I've opened [this PR](https://github.com/software-mansion/react-native-gesture-handler/pull/3077) to hopefully fix the issues you're encountering, please let me know if that PR fixes those issues for you.

Thank you, I will let you know as soon as I have tried it (hopefully tomorrow)
