### ISSUE TITLE
TouchableOpacity remains disabled after attempted click and state change from TextInput

### ISSUE THREAD

**Issue by nahn20** [software-mansion/react-native-gesture-handler#2730]
### Description

On web, when controlling the disabled state of a GH `TouchableOpacity` using a `TextInput` component (specifically `onChangeText`), the button becomes stuck as disabled after attempting a click. This issue only occurs after trying to click on the `TouchableOpacity` while it's disabled, and only when updating state using `TextInput`'s `onChangeText` (There's a chance it's affected by other events, but I haven't tested). `TouchableOpacity` works as intended when using another `Pressable` to change the disabled state. 

When stuck as disabled, `onPress` doesn't fire and the opacity doesn't change. This behavior is inconsistent with RN's original `TouchableOpacity` which correctly re-enables the `TouchableOpacity` after a text change. 

### Steps to reproduce

1. Attempt to click the disabled `TouchableOpacity`
2. Edit the text input (to trigger `onChangeText`)
3. Attempt to click the `TouchableOpacity` (which should be enabled)

### Snack or a link to a repository

https://snack.expo.dev/@nathan_ahn/gesture-handler-textinput-disabled-bug

### Gesture Handler version

2.14.1

### React Native version

0.72.4

### Platforms

Web

### JavaScript runtime

None

### Workflow

Expo managed workflow

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by m-bert** [comment]
Hi @nahn20! I've found out what causes that problem. Could you take a look at #2738 and confirm that it solves this issue?

**Comment by nahn20** [comment]
Thank you so much for the quick and concise fix!

I can't seem to get `react-native-gesture-handler` working locally so I can't test for myself, but given the test plan it looks like it solves this issue!

**Comment by m-bert** [comment]
In that case, I will merge it asap. I hope it will help, but if not - please get back to this issue!
