### ISSUE TITLE
IOS Unable to resolve module react-native-gesture-handler 

### ISSUE THREAD

**Issue by pilarelisii** [software-mansion/react-native-gesture-handler#2731]
### Description

The React Native App is building successfully. The splashScreen appears an then the screen turns black.
I'm running the app in Xcode, in a simulator.
This is the output in XCode: 

`2024-01-25 23:27:13.289863-0300 MyApp[36747:4003815] [native] Running application MyApp ({
    initialProps =     {
    };
    rootTag = 1;
})
2024-01-25 23:27:13.343004-0300 MyApp[36747:4003815] [native] Unable to resolve module react-native-gesture-handler from /myApp/index.ios.js: react-native-gesture-handler could not be found within the project or in these directories:
  node_modules
\^[[0m\^[[31m\^[[1m>\^[[22m\^[[39m\^[[90m 1 |\^[[39m \^[[36mimport\^[[39m \^[[32m'react-native-gesture-handler'\^[[39m\^[[33m;\^[[39m\^[[0m
\^[[0m \^[[90m   |\^[[39m         \^[[31m\^[[1m^\^[[22m\^[[39m\^[[0m
\^[[0m \^[[90m 2 |\^[[39m \^[[36mimport\^[[39m \^[[33mReact\^[[39m \^[[36mfrom\^[[39m \^[[32m'react'\^[[39m\^[[33m;\^[[39m\^[[0m
\^[[0m \^[[90m 3 |\^[[39m \^[[36mimport\^[[39m {\^[[33mAppRegistry\^[[39m} \^[[36mfrom\^[[39m \^[[32m'react-native'\^[[39m\^[[33m;\^[[39m\^[[0m
\^[[0m \^[[90m 4 |\^[[39m \^[[36mimport\^[[39m \^[[33mApp\^[[39m \^[[36mfrom\^[[39m \^[[32m'./App'\^[[39m\^[[33m;\^[[39m\^[[0m`

**index.ios.js** (index.js looks the same) :  

`import 'react-native-gesture-handler';
import React from 'react';
import {AppRegistry} from 'react-native';
import App from './App';

AppRegistry.registerComponent('myApp', () => App);`

### Steps to reproduce

1. npm install react-native-gesture-handler --save
2. cd ios/
3. pod install
4. run in Xcode (simulator)

### Snack or a link to a repository

...

### Gesture Handler version

2.12.0

### React Native version

 0.72.6

### Platforms

iOS

### JavaScript runtime

None

### Workflow

Expo bare workflow

### Architecture

None

### Build type

None

### Device

iOS simulator

### Device model

iPhone 14 pro

### Acknowledgements

Yes

**Comment by m-bert** [comment]
Hi @pilarelisii! Have you tried reinstalling node modules? `rm -rf node_modules` and then `npm install`. Also it would be great if we could look into your setup (like a link to repository) because it is hard to say what happens in your case.
