### ISSUE TITLE
Updating a SharedValue in useAnimatedScrollHandler -> onScroll does nothing

### ISSUE THREAD

**Issue by oliviercperrier** [software-mansion/react-native-gesture-handler#2756]
### Description

Updating a SharedValue in useAnimatedScrollHandler -> onScroll does nothing.

I try making a animated scrollview but my sharedValue is not changing when updating it from the onScroll callback in useAnimatedScrollHandler.

Does not work either on ios, android or web.

### Steps to reproduce

1. Scroll the scroll view
2. Noticed the scrollY.value is always 0

### Snack or a link to a repository

https://snack.expo.dev/@olivier.cperrier/healthy-blue-chip

### Gesture Handler version

2.14.0

### React Native version

0.73.4

### Platforms

Android, iOS, Web

### JavaScript runtime

None

### Workflow

Expo managed workflow

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by m-bert** [comment]
Hi! This issue should be reported in [react-native-reanimated](https://github.com/software-mansion/react-native-reanimated) because `useAnimatedScrollHandler` is not a part of Gesture Handler.
