### ISSUE TITLE
ReferenceError: __DEV__ is not defined

### ISSUE THREAD

**Issue by gozegotushar** [software-mansion/react-native-gesture-handler#2769]
### Description

__DEV__ is not defined
ReferenceError: __DEV__ is not defined
    at ./node_modules/react-native-gesture-handler/lib/module/handlers/createHandler.js 

### Steps to reproduce

- install react-native-gesture-handler in plain react-native-web app using : https://docs.swmansion.com/react-native-gesture-handler/docs/fundamentals/installation
- wrap app entry point using GestureHandlerRootView
<img width="1507" alt="Screenshot 2024-02-20 at 10 51 05 PM" src="https://github.com/software-mansion/react-native-gesture-handler/assets/98510319/3c2ad4a8-dbc8-45bb-81a2-01a9b87afcaf">

### Snack or a link to a repository

https://github.com/gozegotushar/poc_react_native_web

### Gesture Handler version

2.15.0

### React Native version

using react native web

### Platforms

Web

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by tuanlam92** [comment]
Same issue

**Comment by m-bert** [comment]
Hi @tuanlam92! Do you use `react-native` in your project?

**Comment by tuanlam92** [comment]
Hi @m-bert . I have react-native-web project. I found the solution where we can add the plugin using webpack configuration. Thank you for asking.
`
config.plugins.push(
            new webpack.DefinePlugin({
                __DEV__: isDevelopment,
            }),
        );
`

**Comment by m-bert** [comment]
Hi @tuanlam92! Thanks for this information, it seems to work! 😄

Also, as far as I can see the reproduction repository already uses it. I'm closing this issue, but feel free to reopen it if you still have this problem.
