### ISSUE TITLE
How to interact with Touchable?

### ISSUE THREAD

**Issue by baldursson** [software-mansion/react-native-gesture-handler#279]
I'm trying to detect a single tap on a TextInput, however if the user makes a long press the TextInput should handle it by selecting the text. The TextInput component is wrapped in a TouchableWithoutFeedback, and it always cancels the parent TapGestureHandler.

It is well documented how to interact between different gesture handlers, but is it possible to interact with children containing a Touchable? Or will the Touchable always "win" the touch?

**Comment by samridhgupta** [comment]
Having an issue to get an onPress event of a TouchableView which is inside a TapGestureHandler
Is there any way to pass down the touches to child views?
Can't find any solution or workaround from the document provided.

**Comment by osdnk** [comment]
@baldursson, let you try using `NaviveViewGestureHandler`. This handler just pass touches to it's children and could be interacted with another handlers. It means that you could use it simultaneously with `TapGestureHandel`
We're conscious that it calls for being better documented

**Comment by jakub-gonet** [comment]
Hi!
This issue was inactive, so I'm closing it.
If you still face this problem, please reopen.
