### ISSUE TITLE
Svg Image pointerEvents="none" not working on Android

### ISSUE THREAD

**Issue by lorenzo-ange** [software-mansion/react-native-gesture-handler#2793]
### Description

In an SVG with a transparent image I set pointerEvents="none" to allow another Image to receive the gesture events.
It is working fine on Web and on iOS.
It is not working on Android.

### Steps to reproduce

1. Using react-native-svg, create a transparent Image and another Image underneath it.
2. Add pointerEvents="none" to the transparent Image
3. Add GestureDetector to the Image underneath.
4. Try to fire gesture to the Image underneath and see that no gesture is triggered.

### Snack or a link to a repository

https://snack.expo.dev/@lorenzoangelini/rn-svg-gesture-image-gesture-swallowing

### Gesture Handler version

2.14.0

### React Native version

0.73.0

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by 471595249** [comment]
i have same issue! any solution? @lorenzo-ange

**Comment by j-piasecki** [comment]
Since the problem lies in `react-native-svg` I'll close the issue. You can follow the development in the PR linked above.
