### ISSUE TITLE
Android only: after installing the package the build fails, when the app already runs the package works and its great

### ISSUE THREAD

**Issue by Fransch97** [software-mansion/react-native-gesture-handler#2825]
### Description

After installing the package running the build command it fails.
When the app already runs the package works and its a very great package, can you guys fix it?
Commands:
`npm install react-native-gesture-handler
npx react-native run-android     
`

Error message:
`node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/core/GestureHandlerOrchestrator.kt:597:45 Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type 'com.swmansion.gesturehandler.core.GestureHandler<*>?'.`

### Steps to reproduce

npm install react-native-gesture-handler
npx react-native run-android 

More:
"react": "18.2.0",
"react-native": "0.72.0",

### Snack or a link to a repository

none

### Gesture Handler version

2.15.0

### React Native version

0.72.0

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by Fransch97** [comment]
<img width="1007" alt="Screenshot 2024-03-24 alle 22 25 18" src="https://github.com/software-mansion/react-native-gesture-handler/assets/98567653/2ab8cb4b-9e39-4810-999d-b8f64c68a612">

**Comment by Fransch97** [comment]
So i was working with the new beta Kotlin version, because I had` kotlinVersion = "1.8.10"` for now the hack fixing a version worked for me.
Hope this can help someone.      
`kotlinVersion = "1.8.10"`

**Comment by SamiYousef** [comment]
same issue , i don't want to downgrade kotlin version
