### ISSUE TITLE
Pinch gesture focalX & focalY truncated on iOS

### ISSUE THREAD

**Issue by rrebase** [software-mansion/react-native-gesture-handler#2833]
### Description

The Pinch gesture `focalX` and `focalY` values seem to be rounded / truncated on iOS as all the decimal places are zeros.
This makes it impossible to implement butter smooth panning during a pinch gesture.

Tracing the [current code](https://github.com/software-mansion/react-native-gesture-handler/blob/f4f1907eae5da6f29495c4a18ef6458a690c1f41/apple/Handlers/RNPinchHandler.m#L167) I can see that  `[locationInView:]` is used, which has this odd inaccurate behaviour.

### Steps to reproduce

```ts
import { StyleSheet } from 'react-native';
import { Gesture, GestureDetector } from 'react-native-gesture-handler';
import Animated, {
  useSharedValue,
  useAnimatedStyle,
} from 'react-native-reanimated';

export default function App() {
  const scale = useSharedValue(1);
  const savedScale = useSharedValue(1);

  const pinchGesture = Gesture.Pinch()
    .onUpdate((e) => {
      console.log("focalX", e.focalX) // 👈 logs truncated values like 70 instead of 70.123456
      scale.value = savedScale.value * e.scale;
    })
    .onEnd(() => {
      savedScale.value = scale.value;
    });

  const animatedStyle = useAnimatedStyle(() => ({
    transform: [{ scale: scale.value }],
  }));

  return (
    <GestureDetector gesture={pinchGesture}>
      <Animated.View style={[styles.box, animatedStyle]} />
    </GestureDetector>
  );
}

const styles = StyleSheet.create({
  box: {
    height: 120,
    width: 120,
    backgroundColor: '#b58df1',
    borderRadius: 20,
    marginBottom: 30,
  },
});
```

### Snack or a link to a repository

[react-native-zoom-toolkit](https://github.com/Glazzes/react-native-zoom-toolkit/blob/f692eb682d32ef40cc33db4789ba00a707dc9f13/src/commons/hooks/usePinchCommons.ts#L129-L130)

### Gesture Handler version

2.14.1

### React Native version

0.73.6

### Platforms

iOS

### Acknowledgements

Yes

**Comment by rrebase** [comment]
Possible solution: https://github.com/software-mansion/react-native-gesture-handler/pull/2834

**Comment by Glazzes** [comment]
As the author of the linked repository, you can find "run instructions" [here](https://github.com/Glazzes/react-native-zoom-toolkit/tree/main/example), I can also confirm the lack of decimal places is what makes my library jitters as described in the mentioned issue.
