### ISSUE TITLE
PinchGestureHandler doesn't always fire State.END event in iOS simulator

### ISSUE THREAD

**Issue by serhiipalash** [software-mansion/react-native-gesture-handler#284]
Hi!
I need to spring zooming animation, but `PinchGestureHandler` doesn't always emit END event to `onHandlerStateChange` callback. It took me time to understand that it doesn't work only on iOS simulator (iPhone 6, iPhone 6s, maybe more), on real device everything works fine.

```
<PinchGestureHandler
  ref={this.pinchRef}
  onGestureEvent={this._onPinchGestureEvent}
  onHandlerStateChange={this._onPinchHandlerStateChange}
  simultaneousHandlers={this.panRef}
>
  ...
</PinchGestureHandler>
```

I have tested it in our Expo-project and in your `/Example/scaleAndRotate/index.js` and result is the same.

To reproduce the bug just add `alert(event.nativeEvent.state)` here https://github.com/kmagiera/react-native-gesture-handler/blob/master/Example/scaleAndRotate/index.js#L63 and then try to pinch this screen image on iPhone 6. It fires END event only if your gesture is long, but if you start pinching and then immediately finish it, END will never fire until you touch screen again.

I am writing this in case if someone else will face the same issue in future. @kmagiera feel free to close this issue if you don't think this is a real bug.

**Comment by kmagiera** [comment]
Hey @serhiipalash ! Does it mean you are getting a BEGIN event on simulator and no END event. Or maybe you get no events at all on simulator if the interaction is too short?

**Comment by serhiipalash** [comment]
Hi @kmagiera !
I have added this in `/Example/scaleAndRotate/index.js`
<img width="731" alt="screen shot 2018-10-26 at 3 35 19 pm" src="https://user-images.githubusercontent.com/14208343/47566592-e3500880-d934-11e8-8a96-dac3b4405b57.png">
and recorded this video https://drive.google.com/file/d/1Q6r8yUuOZV3K5JUaQlLzff1SLyUMW_yX/view

It's hard to say where is the bug. It seems like if your pinch gesture is very short or if it has high velocity, simulator misses its end once in ten times. 

In your example app it is visible that gesture has not ended - two finger point are stalled on the screen, but in Expo app developer doesn't have touch animation like in your Example app and when the bug happens nothing stalls on the screen. So, it took me time to understand what is this bug about, then  time on trying to fix it, and only then I decided to test it on real device and found out that this bug only happens on iOS simulator.

P.S. My keyboard works fine and Option key doesn't fall :)

**Comment by dbecker215** [comment]
I'm getting the same issue. I'm trying to create a bounding box to indicate the image is active and I too am not getting State.END in order to remove the active styles. However, I tested it on device and it is not firing END on the device either.

**Comment by kmagiera** [comment]
hey @dbecker215 – I understand this is only happening on Android for you too?

**Comment by dbecker215** [comment]
@kmagiera I have only tried this on iOS so far.

**Comment by osdnk** [comment]
Hello,
Could any of you try if adding this do out example 
``` javascript
  last = 5;
  _onPinchHandlerStateChange = event => {
    const s = event.nativeEvent.state;
    if (!(this.last === 5 && s === 2) && !(this.last === 2 && s === 4) && !(this.last === 4 && s === 5)) {
      console.warn("ERROR")
    }
    this.last = s;
    if (event.nativeEvent.oldState === State.ACTIVE) {
      this._lastScale *= event.nativeEvent.scale;
      this._baseScale.setValue(this._lastScale);
      this._pinchScale.setValue(1);
    }
  };
```
gives a warning? I tried to make in real device and emulator with mouse and trackpad as well, but didn't manage to observe any unwanted events' cycle. 

I'm using the newest version of RNGH and RN on Mojave.

**Comment by nenjamin2405** [comment]
I'm facing the same issue, at the beginning I thought it only happens on the emulator, but when I released it on the real device, it also happens randomly, the probability to happen this is small, but it makes my animation to be very inconsistent.

**Comment by noldidrita** [comment]
I'm also having this issue, where the only event fired is State.ACTIVE and that's it. Although the gesture is released, no .END event is fired. When I touch somewhere else (or scroll a scrollView I have), then the event gets emitted.
Note: In my case, I have a PinchGestureHandler and this handler wraps around some Animated.View that has a ScrollView in its hierarchy. Just mentioning this in case ScrollView's Pan Handler could be conflicting with the Pinch. Also, I'm on iOS, latest RN and RNGH on Catalina. But it also happens on a real device. 
Let me know if I can provide any further details as this issue is conflicting with the functionality of the app, so I would be very glad to seeing it resolved :)

**Comment by DevChanQ** [comment]
Still experiencing the same problem on 2.5.0
