### ISSUE TITLE
Privacy Info

### ISSUE THREAD

**Issue by Jignesh1303** [software-mansion/react-native-gesture-handler#2857]
### Description

Please add privacy info file for usage of non public api.

Found potentially required reason API usage 'mach_absolute_time()' in './node_modules/react-native-gesture-handler/ios/Handlers/RNLongPressHandler.m'
Line numbers: 43 64

Apple wont allow app after 30th April.

### Steps to reproduce

PrivacyInfo is not found in iOS

### Snack or a link to a repository

jignesh1303

### Gesture Handler version

2.14.0

### React Native version

0.73.4

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Device model

iOS

### Acknowledgements

Yes

**Comment by m-bert** [comment]
Hi @Jignesh1303! I can see you're using Gesture Handler 2.14.0. We've recently merged #2830 which has been released in 2.16.0. It should resolve this issue.

**Comment by m-bert** [comment]
Yes, we did as you can see in #2830
