### ISSUE TITLE
Touchables do not register taps in nested FlatList on iOS

### ISSUE THREAD

**Issue by lxr-mwhite** [software-mansion/react-native-gesture-handler#2860]
### Description

Hello!

We are using react-native-gesture-handler in our project and currently working on a layout that involves Touchables and nested FlatLists. We have come across an issue on iOS and are hoping to receive some guidance. I am creating this issue because I am seeing the behaviour we expect on Android. 

A quick description of the layout is as follows:
- The screen displays a vertical list of cards to users
  - the card shows a large image, and some text description
  - tapping anywhere on the card should open a new screen with additional details
- The area on the card that shows the image is horizontal list allowing users to scroll through  

Our issue is that while both the vertical and horizontal scrolling is working, tapping in the area occupied by the FlatList does not trigger the onPress callback of the Touchable. Only touches in the area occupied by the text description will trigger the onPress callback.  

Please reference the screenshot below for a reference to the layout. The images are represented by the different color blocks.
![Simulator Screenshot - iPhone 15 Pro - 2024-04-11 at 08 29 39](https://github.com/software-mansion/react-native-gesture-handler/assets/79721789/ea5a31d4-5ac3-4d11-a3bc-117a129618cc)

### Steps to reproduce

1. Render a vertical FlatList with Touchable items
2. Render a horizontal FlatList inside of the Touchable items

See code sample below for an example:
```typescript
import React from 'react';
import { View, Text } from 'react-native';
import { GestureHandlerRootView, FlatList, TouchableOpacity } from 'react-native-gesture-handler';

const App: React.FC = () => {
  const renderItem = React.useCallback(() => {
    return (
      <View style={{ marginBottom: 20 }}>
        <TouchableOpacity
          style={{ height: 300, width: 350, borderWidth: 1, borderColor: 'grey' }}
          onPress={() => console.log('TouchableOpacity onPress called')}
        >
          <FlatList
            horizontal={true}
            pagingEnabled={true}
            data={['red', 'green', 'blue']}
            renderItem={(data) => {
              return <View style={{ backgroundColor: data.item, width: 348 }} />;
            }}
          />
          <View>
            <Text style={{ fontSize: 18 }}>Title</Text>
            <Text style={{ fontSize: 12 }}>Subtitle</Text>
          </View>
        </TouchableOpacity>
      </View>
    );
  }, []);

  return (
    <GestureHandlerRootView>
      <FlatList data={[1, 2, 3, 4, 5]} renderItem={renderItem} contentContainerStyle={{ padding: 20 }} />
    </GestureHandlerRootView>
  );
};

export default App;
```

### Snack or a link to a repository

https://snack.expo.dev/wnDDkWgK60-bO0jYdCOBZ

### Gesture Handler version

2.16.0

### React Native version

0.71.16

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

None

### Acknowledgements

Yes

**Comment by coado** [comment]
Hey, the issue is with how the `TouchableOpacity` is implemented fully on iOS. Basically, it stops hit testing on scroll view, so the touch events are not registered. The issue can be simply solved by using `Pressable` instead 😅.

**Comment by lxr-mwhite** [comment]
> Hey, the issue is with how the `TouchableOpacity` is implemented fully on iOS. Basically, it stops hit testing on scroll view, so the touch events are not registered. The issue can be simply solved by using `Pressable` instead 😅.

Thank you for the response @coado. 
While using `Pressable` does fix the issue of tapping the area of the scroll view, it unfortunately no longer lets you scroll inside the embedded scroll view.

**Comment by coado** [comment]
> > Hey, the issue is with how the `TouchableOpacity` is implemented fully on iOS. Basically, it stops hit testing on scroll view, so the touch events are not registered. The issue can be simply solved by using `Pressable` instead 😅.
> 
> Thank you for the response @coado. While using `Pressable` does fix the issue of tapping the area of the scroll view, it unfortunately no longer lets you scroll inside the embedded scroll view.

Have you tried using `Pressable` from *react-native-gesture-handler*? I see that it doesn't work with `Pressable` from `react-native`, but it should work with the one from the library.

**Comment by lxr-mwhite** [comment]
> > > Hey, the issue is with how the `TouchableOpacity` is implemented fully on iOS. Basically, it stops hit testing on scroll view, so the touch events are not registered. The issue can be simply solved by using `Pressable` instead 😅.
> > 
> > 
> > Thank you for the response @coado. While using `Pressable` does fix the issue of tapping the area of the scroll view, it unfortunately no longer lets you scroll inside the embedded scroll view.
> 
> Have you tried using `Pressable` from _react-native-gesture-handler_? I see that it doesn't work with `Pressable` from `react-native`, but it should work with the one from the library.

Oh! The version I am using does not have `Pressable`. Let me update `react-native-gesture-handler` and I'll get back to you. Thank you!

**Comment by lxr-mwhite** [comment]
@coado Thank you! Using `Pressable` from `react-native-gesture-handler` is working how I would expect it to.

**Comment by svmnikhil** [comment]
I found an annoying bug. When this component is mounted for the first time, Pressable components take two attempts to open. Any successive re-renders of this component are unproblematic and work fine. Pressable and Flatlist come from react-native-gesture-handler as well.

`
  const panGesture = Gesture.Pan()
    .onUpdate((event) => {
      const newTranslateY = Math.max(0, event.translationY);
      progress.value = 1 - (newTranslateY / SHEET_HEIGHT);
    })
    .onEnd((event) => {
      if (progress.value < 0.8 || event.velocityY > 500) {
        runOnJS(onClose)();
      } else {
        progress.value = withTiming(1, { duration: 250 });
      }
    })
    .activeOffsetY([-5, 5])
    .failOffsetX([-15, 15]);

  const composedGesture = Gesture.Simultaneous(
    panGesture,
    Gesture.Native()
  );

return(
<GestureDetector gesture={composedGesture}>                
<View className="flex-1 border border-dashed border-gray-400 rounded-lg">
                    {scannedImages.length > 0 ? (
                    <FlatList
                        horizontal
                        data={scannedImages}
                        keyExtractor={(item, index) => item.uri + index}
                        renderItem={({ item, index }) => (
                            <Pressable
                              onPress={() => handleImagePress(index)}
                              className="w-24 m-1 overflow-hidden"
                              >
                                <Image source={{ uri: item.uri }} className='w-full h-full bg-gray-200 rounded-lg' resizeMode="contain" />
                            </Pressable>
                        )}
                        showsHorizontalScrollIndicator={false}
                    />
                    ) : (
                    <View className="flex-1 justify-center items-center">
                        <Text className="text-gray-400">No images selected</Text>
                    </View>
                    )}
                </View>
            </View>
</GestureDetector/>
)`
