### ISSUE TITLE
`isFormsStackingContext(node)` does not have NativeState on react-native 0.73

### ISSUE THREAD

**Issue by mrousavy** [software-mansion/react-native-gesture-handler#2887]
### Description

The param passed into `isFormsStackingContext` (a `node`) does not have a NativeState on react-native 0.73, maybe it's still a HostObject, but RNGH tries to unwrap it causing the app to crash.

![Screenshot 2024-05-01 at 11 19 22](https://github.com/software-mansion/react-native-gesture-handler/assets/15199031/04627bc7-cf81-42a1-b5e1-43e09c2fcc48)

### Steps to reproduce

1. Create react-native 0.73 app
2. Enable new arch
3. Install rngh 
4. Run app

### Snack or a link to a repository

I'll create a repro in a sec

### Gesture Handler version

2.16.1

### React Native version

0.73.7

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 15 Pro

### Acknowledgements

Yes

**Comment by j-piasecki** [comment]
This change was made to support RN 0.74 (from `HostObject` to `NativeState`) and keeping backwards compatibility with changes like that is a pain. If you need to use RNGH on 0.73 with the new arch please use 2.15.0.

**Comment by mrousavy** [comment]
Cool, I'll upgrade to RN 0.74 then- thank you!
