### ISSUE TITLE
Throws an error "The data couldn't be read because it isn't in the correct format" in Remote debug using Expo

### ISSUE THREAD

**Issue by qaiser110** [software-mansion/react-native-gesture-handler#290]
I'm using the latest 1.0.7, I get an error an error "The data couldn't be read because it isn't in the correct format" in Remote debug mode using Expo without ejecting

This error only happens when I have "Debug Remote JS" enabled.

![image](https://user-images.githubusercontent.com/2253847/45523325-0b176100-b80c-11e8-80d7-d351cfa3b2af.png)

**Comment by ptmt** [comment]
Related: https://github.com/kmagiera/react-native-gesture-handler/issues/46

RN 0.56 / RN 0.57

**Comment by osdnk** [comment]
@qaiser110 
Could you share some context when it occurs?

**Comment by qaiser110** [comment]
I'm using expo 27.1.1 (without ejecting) with react-native 0.55.2 (react 16.3.1)

Thanks @osdnk

**Comment by osdnk** [comment]
I mean could you attach some code?

**Comment by osdnk** [comment]
What's more, could you please try with Expo 30.0.0?

**Comment by qaiser110** [comment]
Thanks @osdnk for your reply

I plan to update to Expo 30 soon, but I'm not able to a the moment. I will update how it goes.

**Comment by deepankarsandy** [comment]
Same issue is happening in my application.
I'm using RN 0.57.1
It only happens with debugger mode on and iOS 10.3 and below. On higher iOS it's working fine.[
![Screenshot 2019-03-29 at 10 58 02 AM](https://user-images.githubusercontent.com/37024019/55211345-976dfc00-5211-11e9-8289-6e83d0a0fb72.png)
](url)

**Comment by khanguslee** [comment]
I had the same issue and 'resolved' it. In my case, we would only get the error if we had the remote debugger on and logging out a certain message (with emojis). To fix this, I changed that message to something else and I can now continue to use the debugger.

**Comment by funkyfourier** [comment]
Same issue here, on iOS 10.3 and 9.2, with no use of console.log. I noticed that it would work if renderLeftActions or renderRightActions returns either null, or a View with _width_ of 0. If height is more than 0 it is ok, but with width 1 or more the error will occur.

**Comment by jakub-gonet** [comment]
Please provide some reproduction example, stack traces don't mention Gesture Handler at all here.

**Comment by jakub-gonet** [comment]
Closing until more info is provided.
