### ISSUE TITLE
GestureDetector is not responsive 

### ISSUE THREAD

**Issue by rezkiy37** [software-mansion/react-native-gesture-handler#2920]
### Description

The app uses **GestureDetector** to handle a tap on the send button. **GestureDetector** works properly when the user opens a chat screen. However, if the user opens nested chats (_threads_), returns to the 1st one, and taps on the send button, **GestureDetector** does not react to this action. The expected behavior is to have the button responsive. 

**Note:** the bug is replicated for a case when there are 2 nested screens e.g. Main chat -> Subchat -> Subchat.

There is an issue with the **Expensify** app - https://github.com/Expensify/App/issues/41528.

<details><summary>Video</summary>
<p>

https://private-user-images.githubusercontent.com/38435837/327558801-477b0ecb-6590-4b37-83ff-48170f9712e4.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMTYxMzcsIm5iZiI6MTcxNjIxNTgzNywicGF0aCI6Ii8zODQzNTgzNy8zMjc1NTg4MDEtNDc3YjBlY2ItNjU5MC00YjM3LTgzZmYtNDgxNzBmOTcxMmU0Lm1wND9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDE0MzcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxOWNiYzJhNWU1ZmI4NGE4ODY0MzdkNDQxNWFiZTAzYTU3NWQ1YmU5MjlhMGMxNjkxYmFjYzQ2Y2EyNWM5OGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.78jeDm5oanP4szGkiW4FNpX9nIm6I-o4W6X_0k5CoJY

</p>
</details> 

Looks like at some moment **GestureDetector** loses a "connection" for the initial screen send button.

I've tried to do a force update for **GestureDetector** via setting and updating a `key` when the screen is focused, and it helps. So it requires a rerender of **GestureDetector** to refresh the "connection" and handle tap events.

<details><summary>Details</summary>
<p>

<img width="588" alt="Screenshot 2024-05-20 at 16 32 24" src="https://github.com/software-mansion/react-native-gesture-handler/assets/57314631/46f82d92-6db8-48d9-8e92-22e7ad28183c">

</p>
</details> 

### Steps to reproduce

1. Launch the "**New Expensify**" app on **IOS**.
2. Click on "**+**".
3. Start a chat with someone.
4. Open the chat.
5. Click on "**+**" on the left of the input.
6. Click "**Submit expense**".
7. Submit this expense.
8. Submit one more expense.
9. Click on the newly created expense preview in the chat.
10. Click on any expense preview.
11. Go back to the main chat.
12. Enter any message.
13. Click on the send button on the right of the input.
14. Current behavior: the send button is not responsive. Expected behavior: the message is sent.

### Snack or a link to a repository

https://github.com/Expensify/App

### Gesture Handler version

2.14.1

### React Native version

0.73.4

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 15 Pro Max (IOS 17.5)

### Acknowledgements

Yes

**Comment by rezkiy37** [comment]
I've attached the link - https://github.com/Expensify/App.

**Comment by j-piasecki** [comment]
I spent some time looking into this and I managed to track it down to be caused by `react-freeze` (so essentially by `Suspense`).

This is enough to reproduce the issue:

```jsx
import {useState} from 'react';
import {Freeze} from 'react-freeze';
import {View, Button, SafeAreaView} from 'react-native';
import {
  Gesture,
  GestureDetector,
  GestureHandlerRootView,
} from 'react-native-gesture-handler';

export default function FirstScreen() {
  const [frozen, setFrozen] = useState(false);
  const tap = Gesture.Tap().onStart(() => {
    console.log('Tap');
  });

  return (
    <GestureHandlerRootView style={{flex: 1}}>
      <SafeAreaView style={{flex: 1, backgroundColor: 'red'}}>
        <Button title="Unfreeze" onPress={() => setFrozen(false)} />
        <Freeze freeze={frozen}>
          <View>
            <GestureDetector gesture={tap}>
              <View
                style={{width: 100, height: 100, backgroundColor: 'blue'}}
              />
            </GestureDetector>
            <View style={{width: 100, height: 100, backgroundColor: 'green'}} />
            <Button title="Freeze" onPress={() => setFrozen(true)} />
          </View>
        </Freeze>
      </SafeAreaView>
    </GestureHandlerRootView>
  );
}
```

It's only reproducible on iOS, because Android keeps hidden views mounted (at the moment of writing): https://github.com/facebook/react-native/blob/9dfcb9ec3ae6987a3231e4d6dd2bf8fb557440c8/packages/react-native/ReactCommon/react/renderer/mounting/Differentiator.cpp#L217-L223

I will come back to it next week, after App.js conf.

**Comment by rezkiy37** [comment]
Thank you guys! I am going to test it as well 🙂

**Comment by rezkiy37** [comment]
Btw, when can we expect the next release?

**Comment by j-piasecki** [comment]
> Btw, when can we expect the next release?

Next week at the earliest.
