### ISSUE TITLE
Nested buttons do not handle enabled properly

### ISSUE THREAD

**Issue by janicduplessis** [software-mansion/react-native-gesture-handler#294]
With 2 nested buttons, if the outside one has the prop `enabled={false}` then then inside one does not receive touch events.

Tested on iOS, not sure about Android.

Snack: https://snack.expo.io/H15lpZuFQ

**Comment by jakub-gonet** [comment]
Seems like android works alright, thanks for reporting.

**Comment by Andarius** [comment]
Still an issue today with RN 0.64 and RNGH 1.10.3

**Comment by Andarius** [comment]
Still an issue with RN 0.66 / RNGH 2.1.0
