### ISSUE TITLE
Could not create task ':react-native-gesture-handler:checkIntegrityBetweenArchitectures'.    > java.lang.reflect.UndeclaredThrowableException (no error message)

### ISSUE THREAD

**Issue by wogno** [software-mansion/react-native-gesture-handler#2952]
### Description

When I run yarn android I get this error,  when I delete but working well, but react navigation raise error of missing gesture-handler. 

I change many version of package, but still get the same error

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/sandwidimohamed/Documents/projects-software/my-projects/manage-app/top-project-app/node_modules/react-native-gesture-handler/android/build.gradle' line: 310

* What went wrong:
Execution failed for task ':tasks'.
> Could not create task ':react-native-gesture-handler:checkIntegrityBetweenArchitectures'.
   > java.lang.reflect.UndeclaredThrowableException (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 28s
error Failed to install the app. Command failed with exit code 1: ./gradlew tasks FAILURE: Build failed with an exception. * Where:
Build file '/Users/sandwidimohamed/Documents/projects-software/my-projects/manage-app/top-project-app/node_modules/react-native-gesture-handler/android/build.gradle' line: 310 * What went wrong:
Execution failed for task ':tasks'.
> Could not create task ':react-native-gesture-handler:checkIntegrityBetweenArchitectures'. > java.lang.reflect.UndeclaredThrowableException (no error message) * Try:

### Steps to reproduce

1. I just installed and yarn android, but work well on ios

### Snack or a link to a repository

not link

### Gesture Handler version

2.9.0

### React Native version

0.72.3

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Android emulator

### Acknowledgements

Yes

**Comment by palanpuricoder** [comment]
same issue

**Comment by j-piasecki** [comment]
I couldn't reproduce it locally, but I have an idea for a fix. Could you check if applying this patch solves it for you: https://gist.github.com/j-piasecki/083ef5de7230c432e4c4475a395492cb?

**Comment by hakanolgunsv** [comment]
Hi @j-piasecki 

I can confirm that your suggested patch worked. Thank you.
Now I can build with `yarn` command successfully.

Here are my versions if someone wonders:
```json
"react": "18.2.0",
"react-native": "0.72.6",
"react-native-gesture-handler": "2.17.0",
```

**Comment by j-piasecki** [comment]
Please update to Gesture Handler 2.17.1 which contains the fix from above 😃

**Comment by wogno** [comment]
> Please update to Gesture Handler 2.17.1 which contains the fix from above 😃

Thanks
