### ISSUE TITLE
Support for Kotlin 2.0

### ISSUE THREAD

**Issue by pvdmde** [software-mansion/react-native-gesture-handler#2960]
### Description

Looks like there's an issue when using Kotlin 2.0 in the app.

### Steps to reproduce

Update kotlin version to 2.0

### Snack or a link to a repository

nope

### Gesture Handler version

not up to date, but code looks similar now

### React Native version

0.73.0

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by pvdmde** [comment]
<img width="931" alt="Screenshot 2024-06-26 at 12 04 20" src="https://github.com/software-mansion/react-native-gesture-handler/assets/164357938/c583491c-e174-40a4-bfff-a6ce377eef7f">



Current line:

https://github.com/software-mansion/react-native-gesture-handler/blob/cbf270ca5c00f749790ff2d3191d190250191425/android/src/main/java/com/swmansion/gesturehandler/core/GestureHandlerOrchestrator.kt#L618

**Comment by j-piasecki** [comment]
Could you verify that https://github.com/software-mansion/react-native-gesture-handler/pull/2964 solves the problem in your case?

**Comment by pvdmde** [comment]
Confirmed. Thanks! Hope to see a release with this one :)

**Comment by pvdmde** [comment]
can we a patch release with this one, as it fixes a blocker to update?

**Comment by pvdmde** [comment]
@j-piasecki can you trigger a release to unblock upgrading projects to kotlin 2.0?

**Comment by j-piasecki** [comment]
We'll most likely release it early next week
