### ISSUE TITLE
Add a maxDeltaY to DrawerLayout

### ISSUE THREAD

**Issue by brentvatne** [software-mansion/react-native-gesture-handler#297]
If you wait for the drawer gesture to fail before beginning another gesture (eg: have a MapView wait for drawer) then it is useful to have maxDeltaY, otherwise if you swipe totally vertically the map still won't activate.

**Comment by j-piasecki** [comment]
It seems to be covered by https://github.com/software-mansion/react-native-gesture-handler/pull/381
