### ISSUE TITLE
Documentation on `onDrawerStateChanged` of Drawer Layout need to explain its second argument, `drawerWillShow: boolean`.

### ISSUE THREAD

**Issue by sinibida** [software-mansion/react-native-gesture-handler#2993]
### Description

The argument `drawerWillShow` of `onDrawerStateChanged` of `DrawerLayout` should be documented, as this is the only reliable way of telling whether the settling drawer is closing, or opening. (a.k.a if the drawer has _started_ opening or closing) The current documentation website lacks of this explanation. [#](https://docs.swmansion.com/react-native-gesture-handler/docs/components/drawer-layout/#ondrawerstatechanged)

Related Discussion: https://github.com/software-mansion/react-native-gesture-handler/discussions/1866

### Steps to reproduce

.

### Snack or a link to a repository

.

### Gesture Handler version

.

### React Native version

.

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by m-bert** [comment]
Hi @sinibida! I've just added that in #3000. Could you please check that and tell me if there is something more that you think that should be added?

**Comment by sinibida** [comment]
Nope, looks great! Thank you for your service.
