### ISSUE TITLE
ReanimatedSwipeable > Jest > getByGestureTestId fails to find component.

### ISSUE THREAD

**Issue by markaustinws** [software-mansion/react-native-gesture-handler#3032]
### Description

Trying to retrieve a swipeable component using getByGestureTestId, but it's failing.  Seems that the Test ID does not get rendered

### Steps to reproduce

  test("GetByGestureTestId", async () => {
    // const swipeable = screen.getByTestId("mySwipe");

    render(

      <Swipeable testID="abcd">
        <Text>Hello</Text>
      </Swipeable>

    );

    screen.debug();

    const swipeable = getByGestureTestId("abcd");
  });

Handler with id: 'abcd' cannot be found

Screen debug:

    <View
      collapsable={false}
      jestAnimatedStyle={
        {
          "value": {},
        }
      }
      onLayout={[Function onRowLayout]}
      style={
        {
          "overflow": "hidden",
        }
      }
    >
      <View
        collapsable={false}
        jestAnimatedStyle={
          {
            "value": {
              "pointerEvents": "auto",
              "transform": [
                {
                  "translateX": 0,
                },
              ],
            },
          }
        }
        style={
          {
            "pointerEvents": "auto",
            "transform": [
              {
                "translateX": 0,
              },
            ],
          }
        }
      >
        <Text>
          Hello
        </Text>
      </View>
    </View>

### Snack or a link to a repository

https://snack.expo.dev/@mausti/tenacious-green-tortillas

### Gesture Handler version

2.18.1

### React Native version

0.74.3

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

Expo managed workflow

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

None

### Acknowledgements

Yes

**Comment by Glazzes** [comment]
`getGestureById`method will retrieve the gesture object, it's not meant to bring components

```js
// Pan gesture in some component
const pan = Gesture.Pan().withTestID("pan")

test("some tests", () => {
  render(<SomeComponent />) // Some component with the gesture shown above
 const pan = getGestureById("pan");
})
```

With code like this you will get the pan gesture.

**Comment by markaustinws** [comment]
I'm trying to get the gesture from the Swipeable component.  Is this not possible?:

    render(<Swipeable testID="swipeable" />);
    getByGestureTestId("swipeable");
    
    Erroring with   Handler with id: 'swipeable' cannot be found

**Comment by latekvo** [comment]
Hi @markaustinws, 

please let me know if [this PR](https://github.com/software-mansion/react-native-gesture-handler/pull/3039) fixes your issue.

**Comment by proambb** [comment]
@latekvo can you please tell how to trigger `onSwipeableWillClose` on `ReanimatedSwipeable`? Are there any examples how to test it with Jest?

**Comment by latekvo** [comment]
@davoam It'll be called when you have a `ReanimatedSwipeable` that's open to either side, and then your finger swipes it such that when you lift your finger, the `ReanimatedSwipeable` will be closed without any further input.

Here's a more details step-by-step of that:

1. Have a swipeable
2. Flick it to either side
3. As soon as you lift your finger, `onSwipeableWillOpen` will be called
4. As soon as the opening animation finishes, `onSwipeableOpen` will be called
5. Flick it the other way
6. As soon as you lift your finger, `onSwipeableWillClose` will be called
7. As soon as the closing animation finishes, `onSwipeableClose` will be called
 
>Are there any examples how to test it with Jest?

You can call the swipeable [programatically](https://docs.swmansion.com/react-native-gesture-handler/docs/components/reanimated_swipeable/#methods), doing so should result in the same callbacks being called.

**Comment by proambb** [comment]
@latekvo thanks for the quick response! It seems like to test this component in Jest we have to pass a ref. But what if the component is deep in the component tree. Is there a way to test it with `testID`. For example, I'd like to trigger `onSwipeableWillClose` because this function triggers other actions in my app.
