### ISSUE TITLE
Configuration 'provided' is obsolete and has been replaced with 'compileOnly'.

### ISSUE THREAD

**Issue by tapz** [software-mansion/react-native-gesture-handler#307]
Configuration 'provided' is obsolete and has been replaced with 'compileOnly'. **It will be removed at the end of 2018**. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

**Comment by younes7programing** [comment]
Yes, I received the same error when implementing Icepick librairy,
so for the people who face this warning:
in the Gradle settings file try to replace 
**provided**    by   **compileOnly**    💯 

source link : https://developer.android.com/studio/build/dependencies?utm_source=android-studio#dependency_configurations

**Comment by jakub-gonet** [comment]
This should be resolved on newer versions of RNGH.

**Comment by aarpitgoel** [comment]
Configure project :@terrylinla_react-native-sketch-canvas
WARNING: Configuration 'provided' is obsolete and has been replaced with 'compileOnly'.
It will be removed in version 5.0 of the Android Gradle plugin.
