### ISSUE TITLE
onTouchesMove reports invalid absolute position values during pinch gesture

### ISSUE THREAD

**Issue by Glazzes** [software-mansion/react-native-gesture-handler#3073]
### Description

Hi there and thank you all for your open source efforts, I'm currently creating a zoomable image component and in order to achieve this behavior I need the absolute position (absoluteX and absoluteY values) of both fingers on the screen, however I'm getting the following issues.

- If the element to pinch **is NOT scaled**, the values reported by `onTouchesDown` and `onTouchesMove` for both pointers are all correct.
- if the element to pinch **is scaled**, the values reported by `onTouchesDown` and `onTouchesMove`  are all incorrect, for some reason one of the pointers is able to report the correct value for the x axis.

  Some other things to note about this problem, if both fingers are moved in the same horizontal direction both pointers will report valid values on the x axis.

  If you keep one finger stand still at the screen and start moving the other, you will be able to see the values reported for the stand still finger will start to increase.

I can not tell whether this problem happens on iOS as I don't own an Apple device.

### Steps to reproduce

- comment the line with the `onUpdate` callback
- pinch the orange view and look at the console, the values are correct relative to the screen.
- reload the dev server
- uncomment the line with the `onUpdate` callback
- pinch the orange view and look at the console, the values reported **are NOT correct** relative to the screen.

### Snack or a link to a repository

https://snack.expo.dev/@glazzes/d545df

### Gesture Handler version

2.16.1

### React Native version

0.74.1

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

Expo managed workflow

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

Alcatel 5044R (Android 7)

### Acknowledgements

Yes

**Comment by Glazzes** [comment]
I'd like to add something to this issue after some testing from my part, scaling the item affects the values reported as already mentioned however modifying width and height properties reports correct values.

**Comment by coado** [comment]
> I'd like to add something to this issue after some testing from my part, scaling the item affects the values reported as already mentioned however modifying width and height properties reports correct values.

Hey, thanks for your report. I've pushed the code that should fix the issue.

**Comment by Glazzes** [comment]
@coado Thank you for your work, I wonder, was this an Android only issue? As I mentioned I don't have an iPhone.

**Comment by coado** [comment]
> @coado Thank you for your work, I wonder, was this an Android only issue? As I mentioned I don't have an iPhone.

Yes, that was something specific to android implementation. The iOS handles that out of the box.
