### ISSUE TITLE
Crash on iOS when setting cursor style

### ISSUE THREAD

**Issue by hazelmeow** [software-mansion/react-native-gesture-handler#3081]
### Description

When setting `cursor: 'auto'` or `cursor: 'pointer'` in the `style` of a `RectButton`, the app crashes with `Exception thrown while executing UI block: -[RNGestureHandlerButton setCursor:]: unrecognized selector sent to instance`. I don't expect `cursor` styles to work on mobile but it probably shouldn't crash. I can reproduce the issue on the iOS simulator and on a real iPhone.

### Steps to reproduce

Create a RectButton and pass `style={{ cursor: 'auto' }}`.

### Snack or a link to a repository

https://github.com/hazelmeow/rngh-cursor-style-repro

### Gesture Handler version

2.16.1

### React Native version

0.74.5

### Platforms

iOS

### JavaScript runtime

None

### Workflow

Expo managed workflow

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by m-bert** [comment]
Hi @hazelmeow! Could you please check if [this PR](https://github.com/software-mansion/react-native-gesture-handler/pull/3097) helps?
