### ISSUE TITLE
[2.19.0] Pressable now interferes with parent's dimensions

### ISSUE THREAD

**Issue by TomCorvus** [software-mansion/react-native-gesture-handler#3085]
### Description

Since 2.19.0, when we use Pressable component from RNGH, parent is now stretched over all available space.

### Steps to reproduce

1. Install RNGH 2.19.0
2. Use this code :
```
<>
	<View style={{ backgroundColor: 'red' }}>
		<Pressable>
			<Text>Button</Text>
		</Pressable>
	</View>
	<View style={{ flex: 1, backgroundColor: 'blue' }}>
		<Text>Screen body</Text>
	</View>
</>
```

The first view will take all the screen when it should only take up the space that the button takes.

### Snack or a link to a repository

https://snack.expo.dev/@tom.corvus/rngh_pressable_2190

### Gesture Handler version

2.19.0

### React Native version

0.75.1

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

None

### Device

iOS simulator

### Device model

All devices (Emulators/Real)

### Acknowledgements

Yes

**Comment by latekvo** [comment]
Hi @TomCorvus, thank you for reporting this issue.

I've opened [this PR](https://github.com/software-mansion/react-native-gesture-handler/pull/3087) to hopefully resolve it, please let me know if it fixes the issue for you.

**Comment by TomCorvus** [comment]
Thanks @latekvo it seems to fix the problem. 💪
