### ISSUE TITLE
Transparent background removes border for touchables

### ISSUE THREAD

**Issue by JoshuaJADaniel** [software-mansion/react-native-gesture-handler#3088]
### Description

Setting `backgroundColor` to a transparent-ish value in any touchable causes border styles to be discarded in Android.

![image](https://github.com/user-attachments/assets/52c8a78c-5574-42ae-95e9-a70504985184)

### Steps to reproduce

1. Open the Snack
2. Select Android
3. Run either locally or online

### Snack or a link to a repository

https://snack.expo.dev/@joshuajadaniel/rngh---background-color-effect-on-border-rendering

### Gesture Handler version

~2.16.1

### React Native version

0.74.5

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

Expo managed workflow

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

Samsung Galaxy S22

### Acknowledgements

Yes

**Comment by kacperzolkiewski** [comment]
Hi @JoshuaJADaniel! Could you please check if [this PR](https://github.com/software-mansion/react-native-gesture-handler/pull/3096) helps?
