### ISSUE TITLE
react-native-tvOS not building

### ISSUE THREAD

**Issue by SPalkaDolby** [software-mansion/react-native-gesture-handler#3089]
### Description

After upgrade from 2.17.1 to 2.19.0 tvOS decided to stop building :) 
Also tested 2.18.1 and it is working fine.
I believe it is connected to:
Important changes: [macOS] Add LongPressGestureHandler by @m-bert in https://github.com/software-mansion/react-native-gesture-handler/pull/3014
![image](https://github.com/user-attachments/assets/db204246-923f-4950-a8c1-c06d1e2959f5)

### Steps to reproduce

1. Install 

### Snack or a link to a repository

Not needed

### Gesture Handler version

2.19.0

### React Native version

npm:react-native-tvos@0.75.2-0

### Platforms

MacOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

None

### Build type

Debug mode

### Device

None

### Acknowledgements

Yes

**Comment by latekvo** [comment]
Hey @SPalkaDolby, thank you for the report!

Please let me know if [this PR](https://github.com/software-mansion/react-native-gesture-handler/pull/3090) fixes your issue

**Comment by SPalkaDolby** [comment]
@latekvo thanks a lot for your help the fix works and lets build the app ;)

Działa!
