### ISSUE TITLE
UI Freezes with a FlatList of <Swipeable> with useNativeAnimations=true

### ISSUE THREAD

**Issue by JulianKingman** [software-mansion/react-native-gesture-handler#310]
I can't pin down what the issue is exactly, but when there's a FlatList of `<Swipeable>` components, the UI locks up. Setting `useNativeAnimations={false}` alleviates the problem, but is obviously not ideal. This is what things look like:

```javascript
<FlatList
          data={data}
          keyExtractor={item => `datapoint-${item.id}`}
          renderItem={({ item, index }) => {
            return (
              <Swipeable
                ref={c => (this.swiperRefs[item.id] = c)}
                friction={2}
                leftThreshold={80}
                rightThreshold={40}
                renderRightActions={(progress, dragX) => {
                  const scale = dragX.interpolate({
                    inputRange: [-80, 0],
                    outputRange: [1, 0],
                    extrapolate: 'clamp',
                  });
                  return (
                    <View styleName="horizontal">
                      {this.renderSwiperButton({
                        onPress: () => {
                          this.swiperRefs[item.id].close();
                          onEdit(item.id);
                        },
                        color: colors.success,
                        icon: 'pencil',
                        scale,
                      })}
                      {this.renderSwiperButton({
                        onPress: () => {
                          this.swiperRefs[item.id].close();
                          onDelete(item.id);
                        },
                        color: colors.error,
                        icon: 'delete',
                        scale,
                      })}
                    </View>
                  );
                }}
                useNativeAnimations={false}
              >
                {// content goes here}
              </Swipeable>
          }}
        />
```

```javascript
renderSwiperButton({ onPress, color, scale, icon }) {
    const { constants } = this.props;
    return (
      <RectButton onPress={onPress}>
        <View
          style={{
            backgroundColor: color,
            flex: 1,
            padding: constants.mediumGutter,
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'center',
          }}
        >
          <Animated.View style={{ transform: [{ scale }] }}>
            <Icon
              name={icon}
              size={constants.iconSize * 1.5}
              color={colors.white}
            />
          </Animated.View>
        </View>
      </RectButton>
    );
  }
```

I'm on RNGH 1.0.7

**Comment by ddzirt** [comment]
BUMP. I am having the same issue. It happens only on iOS(Android seems to be fine). UI freezes, but if you wait for 5-10m it will un-freeze.
 
"react": "16.4.1",
"react-native": "0.56.0",
"react-native-gesture-handler": "^1.0.7"

**Comment by spencercarli** [comment]
I'm seeing the same issue but only when using `renderRightActions`. When it happens the `backboardd` process goes out of control.

I created a demo of the issue on Snack, pulled from the Swipeable example.

Demo: https://snack.expo.io/@spencercarli/swipeable-crash-demo

```
 "@expo/vector-icons": "^8.0.0",
"expo": "^30.0.1",
"react": "16.3.1",
"react-native": "https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz"
```

**Comment by msageryd** [comment]
@JulianKingman I was looking for advice on how to pass item.id to the onPress function and found your post. This solves the problem, but I wonder if the Swipeable won't rerender everytime due to the inline function definition?

```
renderRightActions={(progress, dragX) => {
...
```
Is it even possible to pass item.id to a button on the revealed action panel without declaring an inline function? Wouldn't it be nice if renderRightActions also took a parameter with `extraData`?

**Comment by axlider** [comment]
@JulianKingman I adapted AppleStyleSwipeableRow from "react-native-gesture-handler/Example/". I use it in my "section-list". 
It renders without any problems (rn0.59). 
I only get into  trouble when I want to make it invisible/visible by setting opacity.
It takes much too long to render.

What you should do anyway is extract your View that you return into a function as mentioned in several performance tips.

**Comment by piaskowyk** [comment]
Hey 👋 Could you try to use the latest version of gesture-handler?
