### ISSUE TITLE
fireGestureHandler should not trigger disabled gestures

### ISSUE THREAD

**Issue by Glazzes** [software-mansion/react-native-gesture-handler#3117]
### Description

Hello, I've been trying to write some tests for my library, however I've noticed `fireGestureHandler` is capable of triggering events in gestures whose enabled method has been set to `false`, is this the expected behavior?

### Steps to reproduce

Run the following code as a Jest test, expected behavior is the second gesture is not triggered and therefore the mock is not called, however the mock it's called regardless of whether the gesture is enabled or not.

```jsx
import React from 'react';
import Animated from 'react-native-reanimated';
import {
  Gesture,
  GestureDetector,
  type TapGesture,
} from 'react-native-gesture-handler';
import {
  fireGestureHandler,
  getByGestureTestId,
} from 'react-native-gesture-handler/jest-utils';
import { render } from '@testing-library/react-native';

type ComponentProps = {
  enabled: boolean;
  callback: () => void;
};

const Component = ({ enabled, callback }: ComponentProps) => {
  const tap = Gesture.Tap()
    .withTestId('tap')
    .enabled(enabled)
    .runOnJS(true)
    .onEnd(callback);

  return (
    <GestureDetector gesture={tap}>
      <Animated.View
        style={{ width: 200, height: 200, backgroundColor: 'orange' }}
      />
    </GestureDetector>
  );
};

describe('Some Random Tests', () => {
  type TestData = {
    title: string;
    enabled: boolean;
    timesCalled: number;
  };

  it.each<TestData>([
    { title: 'should trigger callback once', enabled: true, timesCalled: 1 },
    { title: 'should not trigger callback', enabled: false, timesCalled: 0 },
  ])('$title', ({ enabled, timesCalled }) => {
    const callback = jest.fn();
    render(<Component enabled={enabled} callback={callback} />);

    fireGestureHandler<TapGesture>(getByGestureTestId('tap'));

    expect(callback).toHaveBeenCalledTimes(timesCalled);
  });
});
```

### Snack or a link to a repository

code provided above

### Gesture Handler version

2.19.0

### React Native version

0.74.1

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by m-bert** [comment]
Hi @Glazzes! Could you please check if #3119 solves this problem?

**Comment by Glazzes** [comment]
@m-bert Excuse me if it's an ignorant question, but how I do test these changes? I copied your changes pretty much to the T in my project but I do keep getting the same results.

**Comment by m-bert** [comment]
I've just run your test and it seems to work:

<img width="445" alt="image" src="https://github.com/user-attachments/assets/e1479740-d5b6-4380-9b40-eb472f17945a">


> (...) how do I test these changes?

You can install Gesture Handler directly from my branch and then run tests. Doing so may vary depending on your package manager (and its version). Here you can find out how to do this:

- [yarn](https://stackoverflow.com/questions/49992677/how-to-install-specific-branch-of-git-repository-using-yarn)
- [npm](https://stackoverflow.com/questions/39732397/install-specific-branch-from-github-using-npm)

**Comment by Glazzes** [comment]
I just tested by installing the main branch and it does indeed work, thank you for work!
