### ISSUE TITLE
Delayed second touch

### ISSUE THREAD

**Issue by louislatreille** [software-mansion/react-native-gesture-handler#312]
Hi,

I am trying to achieve the following: Touch the screen with one finger which reacts to pan evente (so I need at least a PanGestureHandler somewhere), and without releasing it, do something when a second finger touches the screen, and then do something when the second finger is removed (while the first finger is still on the screen the whole time).

I wasn't able to achieve what I want with a combination of Pan and Tap or Pan and LongPress Handlers, and playing with all their properties.

Hoping someone can help with that,
Thanks!

**Comment by osdnk** [comment]
Isb't there `numberOfPointers` property in payload for `PanGestureHandler`?

**Comment by adamgrzybowski** [comment]
Old issue without response.
