### ISSUE TITLE
Redux Re render updates causing the pan gesture handler to loose focus and stops working.

### ISSUE THREAD

**Issue by sahad00** [software-mansion/react-native-gesture-handler#3136]
### Description

I am using a package react-native-kanban-board which uses Gesture Handler 2x , when I supply a redux state for render , and update the gesture loose its focus on next render . I am trying for so long couldn't resolve it

### Steps to reproduce

Supply a redux state for a component which renders a element with Pan Gesture Handler

### Snack or a link to a repository

https://github.com/Intechnity-com/react-native-kanban-board/issues/5

### Gesture Handler version

^2.9.0

### React Native version

0.75.0

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Android emulator

### Acknowledgements

Yes

**Comment by m-bert** [comment]
Hi @sahad00!

First of all, could you check if it works on latest version of Gesture Handler? `2.9.0` is quite old 😅 

Also, could you prepare minimal reproduction? Preferably copy-pastable one.

**Comment by sahad00** [comment]
@m-bert I will make a reproduction one in few mins
