### ISSUE TITLE
`Pressable` background clipping with large border radius

### ISSUE THREAD

**Issue by mozzius** [software-mansion/react-native-gesture-handler#3137]
### Description

RNGH's Pressable component handles large border radiuses strangely. The correct behaviour is to just round as much as possible and then stop, however RNGH's Pressable seems to make the background get more and more clipped. We use a `borderRadius: 999` for our round buttons, so this means the background disappears. This is best illustrated with a screenshot (each button is 32px by 32px and the number is the border radius used):

<img width="235" alt="Screenshot 2024-10-03 at 16 05 02" src="https://github.com/user-attachments/assets/dbffdaf4-f5bb-43a2-87dd-ceb1d49e3ff5">

Appears to be iOS only

### Steps to reproduce

1. Create a Pressable with a border radius of 999 and a background color
2. Observe no background color

### Snack or a link to a repository

https://github.com/mozzius/rngh-pressable-repro

### Gesture Handler version

2.20.0

### React Native version

0.74.5

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

Expo managed workflow

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 16

### Acknowledgements

Yes

**Comment by kacperzolkiewski** [comment]
I ran your example on an Android device (Redmi Note 7), and the border radius worked perfectly. It seems the issue occurs only on iOS.
![obraz](https://github.com/user-attachments/assets/20e99fe8-3f5a-483f-ade4-a91e3a67ac9a)

**Comment by mozzius** [comment]
Thanks! I updated the issue description

**Comment by mrpmohiburrahman** [comment]
I want to work on this.
I think there are two ways,

- one is to make changes to the React Native's side.
- another one is to make changes on the native side.

( To the repo maintainer ), please, let me know which path should I take.
