### ISSUE TITLE
Bottom Sheet example does not reset to last snap point in some cases

### ISSUE THREAD

**Issue by karanjthakkar** [software-mansion/react-native-gesture-handler#314]
Moved from: https://twitter.com/geekykaran/status/1051770532365037568

> Heyy! I was trying out the bottomsheet example in the RNGH repo and I found an edge case where it starts acting weirdly. I'm unsure how to fix it. Any ideas? (This example only has two snap points but at one point it stays midway until you pull up and then move down). The way I can reproduce this is: keep the bottomsheet fully open, and the scrollview slightly scrolled. Now if you try to pull down, it should scroll to the top and then move the drawer to the last snap point. But somehow it stays midway until you pull it up and then move down.

![bug](https://user-images.githubusercontent.com/1824298/46952554-75c9ef80-d08b-11e8-8f1b-28b8c36716c9.gif)

**Comment by karanjthakkar** [comment]
FYI, this is reproducible on iOS and Android.

**Comment by sievan** [comment]
Also seeing this!

**Comment by jolortiz** [comment]
Any solutions to this? I believe I am getting the same behavior

![screen_record_072319](https://user-images.githubusercontent.com/26909311/61737061-4e036880-ad3c-11e9-8a57-9efe44c725cc.gif)

**Comment by jakub-gonet** [comment]
This is quite old and related to the example app, components from it aren't really supported by us, so I'm going to close this one.
If you need further help, please reply.
