### ISSUE TITLE
ReanimatedSwipable Delayed

### ISSUE THREAD

**Issue by enchorb** [software-mansion/react-native-gesture-handler#3147]
### Description

Tried upgrading from `Swipeable` to `ReanimatedSwipable` but had to rollback.

For some reason the `progress` value on `ReanimatedSwipable` updates delayed as to what happened on the UI, the swipeable is already open but the progess.value, onSwipeableOpen, etc all fire 1-2 seconds after. This was not an issue with `Swipeable`

### Steps to reproduce

Test side-by-side a Swipeable and ReanimatedSwipable

### Snack or a link to a repository

N/A

### Gesture Handler version

2.20.0

### React Native version

0.75.4

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

Expo bare workflow

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 16 Pro Max - iOS 18

### Acknowledgements

Yes

**Comment by latekvo** [comment]
Hi @enchorb,

Thank you for reporting this issue,

Please let me know if the following PR resolves it: ([link](https://github.com/software-mansion/react-native-gesture-handler/pull/3149))

**Comment by enchorb** [comment]
@latekvo sorry for the late reply, this solved my issue! Is this going to be released soon?
