### ISSUE TITLE
BottomSheet scrollview does not wait till pull up is complete

### ISSUE THREAD

**Issue by karanjthakkar** [software-mansion/react-native-gesture-handler#315]
Whenever I do a quick swipe, in the scroll section of the drawer, sometimes the scrollview is triggered instead of using the pan to pull up the drawer. I'm unsure if its a bug with a the example or some internals. This never happens on iOS.

![bug2](https://user-images.githubusercontent.com/1824298/47003761-46b98980-d130-11e8-9d8b-e4cf9debd391.gif)

**Comment by karanjthakkar** [comment]
Similar issue mentioned by someone else: https://github.com/kmagiera/react-native-gesture-handler/issues/264#issuecomment-408701831

**Comment by jakub-gonet** [comment]
Seems like this issue is kinda outdated. We generally don't support Examples, they _may_ contain bugs. For future readers: please use [react-native-bottom-sheet](https://github.com/osdnk/react-native-reanimated-bottom-sheet) if you want to use this component.

**Comment by sgtpsibin** [comment]
hope any update on this issue. Other bottomsheet libraries not seem to be good. Just a small fix this issue to make bottomsheet example become perfect!
