### ISSUE TITLE
Android: using any GestureHandler will dismiss keyboard

### ISSUE THREAD

**Issue by a396901990** [software-mansion/react-native-gesture-handler#317]
I have a input view with Flatlist. Input view have send button.
Add GestureHandler to send button, every time i tap/long press will dismiss keyboard first. I want keep keyboard and trigger GestureHandler

this problem only for Android, iOS is fine.

Any idea, thanks in advance~

**Comment by a396901990** [comment]
if i replace GestureHandler with React native Touchable is working fine, so i assume have some bug in GestureHandler android library native code. i try to looking into source code, so hard to find the problem. any advice

**Comment by brentvatne** [comment]
what did you set keyboardShouldPersist taps to on the flatlist? https://facebook.github.io/react-native/docs/scrollview#keyboardshouldpersisttaps

**Comment by a396901990** [comment]
i set 'always', i think my code is no problem. because if i don't use GestureHandler will working perfectly.

**Comment by kuzkokov** [comment]
the bug is still here

**Comment by jakub-gonet** [comment]
Hi,
could you guys provide some repro as a snack? It'll greatly improve time in which this issue will be resolved.

**Comment by nolliebigspin** [comment]
Hi,
I'm using `LongPressGestureHandler` trying to build a voice-message feature with a swiping gesture to delete current recording. Same like in Whatsapp or Instagram.

The problem on my side is, that the keyboard will immediately dismiss after pressing down the button which is an unwanted bahavior in this case. This happens to me on Android and ond IOS.

Anybody here with the same issues who possibly found a workaround?

Thanks for your help!

**Comment by konglomora** [comment]
Did you find a solution?

**Comment by piaskowyk** [comment]
Hey 👋 Could you provide a repo to reproduce your issue?

**Comment by jaixchaudhary** [comment]
> Hi, I'm using `LongPressGestureHandler` trying to build a voice-message feature with a swiping gesture to delete current recording. Same like in Whatsapp or Instagram.
> 
> The problem on my side is, that the keyboard will immediately dismiss after pressing down the button which is an unwanted bahavior in this case. This happens to me on Android and ond IOS.
> 
> Anybody here with the same issues who possibly found a workaround?
> 
> Thanks for your help!

@nolliebigspin did you find the solution, I had the requirement but I am not able to find the solution.
