### ISSUE TITLE
iOS crash on react-native 0.76 with new arch and react StrictMode

### ISSUE THREAD

**Issue by 0xDing** [software-mansion/react-native-gesture-handler#3184]
### Description

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Termination Reason: SIGNAL 6 Abort trap: 6
Terminating Process: hopi [1353]

Triggered by Thread:  0

Last Exception Backtrace:
0   CoreFoundation                	       0x1804b70e0 __exceptionPreprocess + 160
1   libobjc.A.dylib               	       0x18008ede8 objc_exception_throw + 72
2   Foundation                    	       0x180e73c40 -[NSMutableDictionary(NSMutableDictionary) classForCoder] + 0
3   hopi.debug.dylib              	       0x10e1eb6f0 -[RNGestureHandlerRegistry attachHandlerWithTag:toView:withActionType:] + 300
4   hopi.debug.dylib              	       0x10e1e3e48 -[RNGestureHandlerManager attachGestureHandler:toViewWithTag:withActionType:] + 1184
5   hopi.debug.dylib              	       0x10e1e3f0c __77-[RNGestureHandlerManager attachGestureHandler:toViewWithTag:withActionType:]_block_invoke + 52
6   libdispatch.dylib             	       0x180178de0 _dispatch_client_callout + 16
7   libdispatch.dylib             	       0x18017c780 _dispatch_continuation_pop + 804
8   libdispatch.dylib             	       0x18018fde0 _dispatch_source_invoke + 1620
9   libdispatch.dylib             	       0x180187ad8 _dispatch_main_queue_drain + 880
10  libdispatch.dylib             	       0x180187758 _dispatch_main_queue_callback_4CF + 40
11  CoreFoundation                	       0x18041ae3c __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
12  CoreFoundation                	       0x180415534 __CFRunLoopRun + 1944
13  CoreFoundation                	       0x180414960 CFRunLoopRunSpecific + 536
14  GraphicsServices              	       0x190183b10 GSEventRunModal + 160
15  UIKitCore                     	       0x185aa2b40 -[UIApplication _run] + 796
16  UIKitCore                     	       0x185aa6d38 UIApplicationMain + 124
17  hopi.debug.dylib              	       0x10cdf7bcc __debug_main_executable_dylib_entry_point + 112 (main.swift:11)
18  dyld_sim                      	       0x104121410 start_sim + 20
19  dyld                          	       0x104296274 start + 2840

### Steps to reproduce

ENV['RCT_NEW_ARCH_ENABLED'] = '1'

### Snack or a link to a repository

https://snack.expo.dev/@borisding/biased-indigo-pizza

### Gesture Handler version

2.20.2

### React Native version

0.76

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

Expo bare workflow

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by miridih-chyoon** [comment]
+1

**Comment by patlux** [comment]
Same issue

**Comment by m-bert** [comment]
Hi! Could you please check if [this PR](https://github.com/software-mansion/react-native-gesture-handler/pull/3247) fixes this problem?

**Comment by exzos28** [comment]
Hi. Why is the Issue closed and hasn't been published?

**Comment by m-bert** [comment]
Hi @exzos28!

> Why is the Issue closed and hasn't been published?

Issue is closed because PR that solves it was merged. It will be released soon.

**Comment by exzos28** [comment]
@m-bert Could you share plans for when it will be released?

**Comment by m-bert** [comment]
While I can't give you a specific date, I believe it should be available by the end of next week (maybe in this, but I won't promise that)
