### ISSUE TITLE
Android new arch - [CXX1429] error when building with cmake using

### ISSUE THREAD

**Issue by erie-e9** [software-mansion/react-native-gesture-handler#3193]
### Description

I just init a new RN project, install some deps including react-native-gesture-handler@2.20.2, `newArchEnabled=true` and `hermesEnabled=true`
<img width="1012" alt="Captura de pantalla 2024-10-30 a la(s) 10 20 15 p m" src="https://github.com/user-attachments/assets/8f3842b6-0667-42bf-aa33-b06fb3789fe2">

Note: I already tested with the version @2.3.0 but it throws another error, tbh I'm not sure which version should I use, @2.3.0 with Fabric support or new one @2.20.0 with 0.76.0 support, anyway, this bug is for the latest one.

### Steps to reproduce

1. Init new RN project - @0.76.0
2. Install latest version of this dep - yarn add react-native-gesture-handler@2.20.2
3. Sync gradle in android studio
4. Rebuild project: Build output will show problem.

### Snack or a link to a repository

https://github.com

### Gesture Handler version

2.20.2

### React Native version

0.76.0

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by m-bert** [comment]
Hi @erie-e9! I've just created new React Native project using 0.76.1 and it builds without any errors. Please provide a reproduction so we can take a look at this issue.

**Comment by m-bert** [comment]
Also there's a `cache` directory in the path on the scrrenshot, have you tried to clear gradle caches?

**Comment by erie-e9** [comment]
I just close this issue, 'cuz it disappears no without error but I will create another issue for `Task :react-native-gesture-handler:mergeDebugAndroidTestNativeLibs FAILED` thanks I only cleared cache and deleted remove build/ android/build and .cxx folders

**Comment by TweetyBoop1990** [comment]
> I just closed this issue, 'cuz it disappears now, but I will create another one for `Task :react-native-gesture-handler:mergeDebugAndroidTestNativeLibs FAILED` error, thank you @m-bert I only cleared cache and deleted remove build/ android/build and .cxx folders

Did you ever find a fix for this?
