### ISSUE TITLE
crashes on 0.76

### ISSUE THREAD

**Issue by philipheinser** [software-mansion/react-native-gesture-handler#3206]
### Description

crashes on 0.76
<img width="1224" alt="Screenshot 2024-11-09 at 18 09 25" src="https://github.com/user-attachments/assets/b7e9b675-5d4b-4927-8bbc-7b745f07d2a1">

### Steps to reproduce

1. setup a new arch project with react navigation 7 and use gesture handler on a screen 
2. navigate to that screen

### Snack or a link to a repository

https://snack.expo.dev/@philipheinser/gesturehandler076?platform=ios

### Gesture Handler version

2.20.2

### React Native version

0.76.0

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by ecohotels** [comment]
Same issue here

**Comment by philipheinser** [comment]
@j-piasecki Yes we are using strictmode

**Comment by m-bert** [comment]
Hi @philipheinser! If that's the case I'm closing this one as we already have this issue. We will post update under #3184 when we find something.
