### ISSUE TITLE
How should oldState behave?

### ISSUE THREAD

**Issue by msageryd** [software-mansion/react-native-gesture-handler#324]
I'm trying to grasp the flow of `event.nativeEvent.state` changes and how I should use oldState vs state.

Here is a console.log from a single tap and release:

![image](https://user-images.githubusercontent.com/4483085/47569544-28c00600-d934-11e8-9705-29ba120b6f42.png)

1. First event shows `state = 2`
2. Second event shows `oldState = 0`

Why isn't `oldState = 2` on the second event?

One thing I'm interested in is how to identify when finger is lifted, i.e. unPress.

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
If you need further help please reply.
