### ISSUE TITLE
Gesture Handler won't compile with React Native 0.77

### ISSUE THREAD

**Issue by j-piasecki** [software-mansion/react-native-gesture-handler#3245]
### Description

In https://github.com/facebook/react-native/commit/e0a5bbe309724429dc8e5ef7961c499b2f86339c some types changed to be non-nullable which will cause RNGH not to compile.

It's possible more issues will emerge during the upgrade.

### Steps to reproduce

1. Setup app with 0.77
2. Add RNGH
3. Build app

### Snack or a link to a repository

https://github.com/software-mansion/react-native-gesture-handler

### Gesture Handler version

2.21.2

### React Native version

0.77

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by j-piasecki** [comment]
> Hey! 👋
The issue doesn't seem to contain a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example).
Could you provide a [snack](https://snack.expo.dev/) or a link to a GitHub repository under your username that reproduces the problem?


Don't you dare use my own spells against me.

**Comment by don-007** [comment]
I'm also facing the same issue. Any quick hack to fix this ?
