### ISSUE TITLE
ScrollView doesn't interact properly with GestureHandlerButton on Android

### ISSUE THREAD

**Issue by janicduplessis** [software-mansion/react-native-gesture-handler#3253]
### Description

When a button inside a scroll view is activated it won't be interrupted by scrolling on Android. This seems to be a regression since it used to work fine in 2.20.0.

Current behaviour (rngh 2.21.2):

https://github.com/user-attachments/assets/8a65d72b-acc3-4f8f-a242-2356597f5ce8

Expected behaviour (rngh 2.20.0):

https://github.com/user-attachments/assets/2b92e6c5-ad4a-4c80-bf58-51c1458d0cd3

Note it doesn't repro in the snack since it uses the older 2.16.1 version

### Steps to reproduce

1. Activate the button by touching it but not releasing
2. Scroll up or down

Here the button activation should be canceled and the scroll view should scroll

### Snack or a link to a repository

https://snack.expo.dev/8zhTUCK-4AOzV2LzEJEA8

### Gesture Handler version

2.21.2

### React Native version

0.76.0

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

Android emulator

### Acknowledgements

Yes

**Comment by janicduplessis** [comment]
Narrowed it down to this commit https://github.com/software-mansion/react-native-gesture-handler/pull/3095

**Comment by latekvo** [comment]
Hey @janicduplessis please let me know if [this PR](https://github.com/software-mansion/react-native-gesture-handler/pull/3264) fixes this issue for you

**Comment by janicduplessis** [comment]
@latekvo Hello, it seems to partially fix the problem. I have a case where I have some nested scroll views and the wrong one interrupts the tap gesture now.

Something like:

```ts
<ScrollView>
  <ScrollView horizontal>
    <Button />
  </ScrollView>
</ScrollView>
```

If I tap the button then scroll horizontally the tap is not interrupted.
If I tap the button and scroll vertically the tap is properly interrupted.

Let me know if you have trouble reproducing this case.

**Comment by janicduplessis** [comment]
Current:

https://github.com/user-attachments/assets/59db9151-08af-4ce0-b607-51a950dbc72c

Expected:

https://github.com/user-attachments/assets/8c3e295a-55ac-4d56-86a0-fd5005d02629

**Comment by latekvo** [comment]
Thanks for catching that. I'll add the case to detect horizontal `ScrollView` as well.

**Comment by latekvo** [comment]
Horizontal `ScrollView` should be working in that PR now, let me know if you have any other issues
