### ISSUE TITLE
Inconsistent onEnd Behavior for LongPress Gesture on Fast Swipes (Android)

### ISSUE THREAD

**Issue by Abdullo-0901** [software-mansion/react-native-gesture-handler#3258]
### Description

When using a `LongPress` gesture with `maxDistance`, the `onEnd` callback works correctly for slow movements but fails when performing a fast swipe. Specifically, on Android devices, if the gesture is executed quickly, `onEnd` is triggered unexpectedly or behaves inconsistently.In ios working

### Steps to Reproduce
1. Implement a `LongPress` gesture with `maxDistance`.
2. Slowly press and drag — the gesture works as expected.
3. Quickly swipe while pressing — the `onEnd` callback triggers unexpectedly.

### Expected Behavior
- The `onEnd` callback should only be triggered when the gesture meets the `maxDistance` and duration requirements, regardless of swipe speed.

### Actual Behavior
- On fast swipes, `onEnd` behaves inconsistently and triggers prematurely.
### Code Example

```
  const longPressGestureCamera = Gesture.LongPress()
    .maxDistance(200)
    .onStart(() => {
      if (cameraRecorderMessage.isDeleteLoading) return
      runOnJS(setCameraRecorderMessage)({
        ...cameraRecorderMessage,
        isDeleteRecord: false,
        isLongPressActive: true,
      })
    })
    .onEnd((event) => {
      runOnJS(stopCameraRecordGesture)()
    })
```

### Steps to reproduce

**
- Create a LongPress gesture using the Gesture.LongPress() API from react-native-gesture-handler.
- Set a maxDistance (e.g., 400) for the gesture.
- Add an onStart callback to handle when the gesture starts.
- Add an onEnd callback to handle when the gesture ends.
- Run the app on an Android device.
- Slowly press and drag within the maxDistance — the onEnd works as expected.
- Now, perform a fast swipe while pressing (drag quickly) — the onEnd is triggered inconsistently or prematurely.**

### Snack or a link to a repository

https://snack.expo.dev/@abdulloh_0901/thrilled-orange-popsicle?platform=ios

### Gesture Handler version

2.19.0

### React Native version

0.75.3

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

None

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Android emulator

### Device model

Android versiya  15

### Acknowledgements

Yes

**Comment by m-bert** [comment]
Hi @Abdullo-0901! I've opened your repro and it seems to work as expected. `onEnd` callback will be called iif gesture had activated. If you perform fast swipe it is possible that `LongPress` didn't have enough time to activate, so `onEnd` won't be called. However, you can still check that in `onFinalize` callback which will be called anyway.

Also, I've noticed that you use `GestureDetector` on our `Pressable` component - I'd be careful with that as it may behave in unexpected ways.

**Comment by Abdullo-0901** [comment]
Hi @m-bert 
Thank you for your response! I appreciate the clarification.

Regarding the issue with the onEnd callback, I understand that it may not be triggered if the LongPress doesn't have enough time to activate due to a fast swipe. However, could you please provide more details about how the onFinalize callback works in this case? Specifically, how does it differ from onEnd, and how can I utilize it to handle these situations more effectively?

Also, you mentioned using GestureDetector on the Pressable component might cause unexpected behavior. Could you elaborate on this and explain what kind of issues I might encounter? I'd like to make sure that my implementation follows best practices to avoid potential problems.

Looking forward to your insights!

Thank you again!

**Comment by m-bert** [comment]
Hi @Abdullo-0901! 

>  However, could you please provide more details about how the onFinalize callback works in this case? Specifically, how does it differ from onEnd, and how can I utilize it to handle these situations more effectively?

`onFinalize` callback will be called always when gesture enters _finished_* state. `onEnd` will be called if gesture was able to enter `ACTIVE` state, and then transitioned to _finished_ state. Both of those callbacks have 2 arguments:

1. `event` - gesture event
2. `success` - this `boolean` flag represents whether gesture has finished successfully (i.e. finished in `END` state), or was it interrupted / didn't meet activation criteria (then it ended in either `FAILED` or `CANCELLED` state)

Maybe 2nd argument will help you achieve desired goals!

\* by _finished_ state I mean one of the following: `END`, `FAILED`, `CANCELLED`

> Also, you mentioned using GestureDetector on the Pressable component might cause unexpected behavior. Could you elaborate on this and explain what kind of issues I might encounter?

Sadly it is hard to say what issues can be encountered 😞 I don't say that something _will_ break - I just say it might. `Pressable` is quite new component in our library. Moreover, it is built using 3 simultaneous gestures. For example, it does have `longPress` under the hood. 

On the other hand, I see that `Pressable` is not _direct_ child of `GestureDetector`, so it _should_ work. If you encounter any issue with it, please let us know!

**Comment by Abdullo-0901** [comment]
@m-bert 
#
Thank you so much for the detailed explanation! I now clearly understand the difference between onFinalize and onEnd. Using the success argument will definitely be helpful.

I'll also keep in mind your note about potential issues with Pressable. If I encounter any problems, I'll be sure to let you know. Thanks again!"
