### ISSUE TITLE
blocksExternalGesture with Gesture.Native() does not block a ScrollView

### ISSUE THREAD

**Issue by gaearon** [software-mansion/react-native-gesture-handler#3267]
### Description

The docs led me to believe that this code would block the ScrollView.

```js
import {View} from 'react-native'
import {
  Gesture,
  GestureDetector,
  GestureHandlerRootView,
  ScrollView,
} from 'react-native-gesture-handler'

export default function App() {
  const native = Gesture.Native()
  const pan = Gesture.Pan()
    .blocksExternalGesture(native)
    .onBegin(() => {
      'worklet'
      console.log('begin')
    })
    .onUpdate(() => {
      'worklet'
      console.log('update')
    })
    .onEnd(() => {
      'worklet'
      console.log('end')
    })
    .onFinalize(() => {
      'worklet'
      console.log('finalize')
    })
  return (
    <GestureHandlerRootView>
      <GestureDetector gesture={pan}>
        <View style={{flex: 1, backgroundColor: 'blue'}}>
          <ScrollViewExample native={native} />
        </View>
      </GestureDetector>
    </GestureHandlerRootView>
  )
}

function ScrollViewExample({native}) {
  return (
    <GestureDetector gesture={native}>
      <ScrollView
        horizontal
        pagingEnabled
        style={{
          flex: 1,
          backgroundColor: 'yellow',
        }}>
        <View
          style={{
            width: 200,
            height: '100%',
            backgroundColor: 'green',
          }}
        />
        <View
          style={{
            width: 200,
            height: '100%',
            backgroundColor: 'purple',
          }}
        />
      </ScrollView>
    </GestureDetector>
  )
}
```

However, it doesn't do anything. The ScrollView is pannable despite my Pan gesture blocking it.

If this is not how the library is supposed to be used, there need be clearer docs and/or warnings. I have no idea what I'm doing wrong here. Very similar code [almost](https://github.com/software-mansion/react-native-gesture-handler/issues/3265) works with a ref, and the types say a Gesture and a Ref here are interchangeable.

### Steps to reproduce

1. Drag the scrollview around
2. It shouldn't be draggable! But it is :(

https://github.com/user-attachments/assets/32f10dd0-cc33-46ab-b2be-645608879705

### Snack or a link to a repository

https://snack.expo.dev/__gbUHQOmsdvXY1U4SPmo

### Gesture Handler version

2.20.2

### React Native version

0.76.3

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

Expo managed workflow

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Real device

### Acknowledgements

Yes

**Comment by j-piasecki** [comment]
> The docs led me to believe that this code would block the ScrollView.

That's the same issue as the https://github.com/software-mansion/react-native-gesture-handler/issues/3266. If you replace `ScrollView` from RNGH with the one from `react-native` it will work.

See https://github.com/software-mansion/react-native-gesture-handler/issues/3266#issuecomment-2527708676 for more details.

**Comment by gaearon** [comment]
Another similar issue where it doesn't work reliably.

https://github.com/software-mansion/react-native-gesture-handler/issues/3321

**Comment by gaearon** [comment]
Another similar issue, something about putting it into the child works better than keeping both in the parent.

https://github.com/software-mansion/react-native-gesture-handler/issues/3326
