### ISSUE TITLE
Swipeable  How do  Close the sideslip

### ISSUE THREAD

**Issue by SongZhaoJie** [software-mansion/react-native-gesture-handler#327]
How do  Close the sideslip，Only one sideslip，
![wechatimg36](https://user-images.githubusercontent.com/29090582/47769140-b4aba680-dd15-11e8-956b-cdfe9951e80e.jpeg)

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
If you need further help please reply.
