### ISSUE TITLE
rn 076.4 - Invariant Violation: TurboModuleRegistry.getEnforcing

### ISSUE THREAD

**Issue by GaelCO** [software-mansion/react-native-gesture-handler#3271]
### Description

Hi,

I upgrade my project to rn 0.76.4 and I obtain this error at launch on android :
(NOBRIDGE) ERROR  Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNGestureHandlerModule' could not be found. Verify that a module by this name is registered in the native binary.

No issue with rn 0.76.3.
I see no problem on iOS

This may be more an issue of the latest version of react native than of react-native-gesture-handler

### Steps to reproduce

- Update rn to 0.76.4
- launch on android

### Snack or a link to a repository

https://github.com/GaelCO/GestureIssue

### Gesture Handler version

2.21.2

### React Native version

0.76.4

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by benhandanyan** [comment]
Same issue on multiple projects, including this minimal reproduction:
https://github.com/benhandanyan/react-native-sample-app/tree/rn-gh-new-arch-test

**Comment by GaelCO** [comment]
This issue comes from react-native 0.76.4.
Fixed on react-native 0.76.5

Perhaps, link to this issue https://github.com/facebook/react-native/issues/48173
