### ISSUE TITLE
PanGestureHandler sometimes not working on ios

### ISSUE THREAD

**Issue by mldb** [software-mansion/react-native-gesture-handler#339]
hi
in iOS sometimes PanGestureHandler has conflict with back-gesture of react-navigation.
i guess `RNGestureHandlerModule.createGestureHandler` is async and in `RNGestureHandlerModule.attachGestureHandler` rootView is null.
i change cdm function of 'GestureHandler.js' to something like this and problem solved:
```js
componentDidMount() {
      this._viewTag = findNodeHandle(this._viewNode);
      this._config = filterConfig(
        this.props,
        this.constructor.propTypes,
        config
      );
      if (hasUnresolvedRefs(this.props)) {
        this._updateEnqueued = setImmediate(() => {
          this._updateEnqueued = null;
          this._update();
        });
      }
      RNGestureHandlerModule.createGestureHandler(
        handlerName,
        this._handlerTag,
        this._config
      );
      setTimeout(() => {
        RNGestureHandlerModule.attachGestureHandler(
          this._handlerTag,
          this._viewTag
        );
      }, 500);}
```
but this is just temporary...
you can add promise to "createGestureHandler" to make sure that was ended and then call "attachGestureHandler".
sorry for my english :)

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
If you need further help please reply.
