### ISSUE TITLE
Buttons do not trigger onPress if inside TapGestureHandler

### ISSUE THREAD

**Issue by Fsarmento** [software-mansion/react-native-gesture-handler#346]
I have BaseButton inside a TapGestureHandler.

In Android, pressing the button will trigger both onHandlerStateChange from TapGestureHandler and onPress & onActiveStateChange from BaseButton. 

In iOS, pressing the button triggers the onHandlerStateChange from TapGestureHandler and the onActiveStateChange from BaseButton.  However, onPress is never triggered. 

I added the waitFor but I still get the same result. Any help?

```
btnRef = React.createRef()

{...}

render() {
   return (
      <TapGestureHandler onHandlerStateChange={this.onHandlerStateChange} /* waitFor={this.btnRef} */>
         {...}
         <BaseButton
           // ref={this.btnRef}
           onPress={onPress}
           onActiveStateChange={this.onActiveStateChange}
           style={style}
           enabled={enabled}
           {...otherProps}
         >
           {this.props.children}
         </BaseButton>
         {...}
      </TapGestureHandler>
)}
```

**Comment by tomasgcs** [comment]
I am experiencing same issue. Only way to make button work is to add `disallowInterruption` but then parent Gesture handlers do not work while the button is in Active State this happens when the button is inside a ScrollView or some other gesture handler.

**Comment by cristianoccazinsp** [comment]
Have you found a fix for this? Having the same issue on both Android and IOS

**Comment by almpertis** [comment]
is there a fix?

**Comment by AndrewEastwood** [comment]
any updates ?

**Comment by vance-liu** [comment]
Facing it on IOS, Android is ok.

**Comment by RRaideRR** [comment]
Hey there,
I have a hacky workaround.

1. You render the button (or whatever the View that should recognize a click). With the `onLayout()` function you can receive the coordinates of the button:

```
myButtonRef.current!.measure((fx, fy, width, height, px, py) => {
                setMyButtonBoundaries({
                  x: px,
                  y: py,
                  width: width,
                  height: height,
                });
              });
```

2. Know you know where the button is located on the phone. Now you need to check in your TapGestureHandler e.g. in your `onHandlerChange` method if the click is on the button:

```
      const nativeEventAbsoluteX = event.nativeEvent.absoluteX;
      const nativeEventAbsoluteY = event.nativeEvent.absoluteY;

      if ((nativeEventAbsoluteX >= myButtonBoundaries.x
        && nativeEventAbsoluteX <= myButtonBoundaries.x + myButtonBoundaries.width)
        && (nativeEventAbsoluteY >= myButtonBoundaries.y
        && nativeEventAbsoluteY <= myButtonBoundaries.y + myButtonBoundaries.height)) {
        // it is a button click
      } else {
        // it is a click outside of the button
      }
```


This feels super hacky but is the only solution that worked for me.

**Comment by mardikarifqi** [comment]
Are there any updates for this?

**Comment by p-sebastian** [comment]
For anyone still looking for this:

Using the `react-native-gesture-handler` buttons, you can use the prop `disallowInterruption` which will cancel parent gesture handler events

```jsx
<GestureDetector gesture={gesture}>
  ... // some content
  <RectButton disallowInterruption>...</RectButton>
</GestureDetector>
```

**Comment by cglacet** [comment]
What if the button comes from an external source (for example a `react-native-elements` button)?
