### ISSUE TITLE
Could not resolve all files for configuration ':react-native-gesture-handler:lintClassPath'

### ISSUE THREAD

**Issue by Nocturne-FFG** [software-mansion/react-native-gesture-handler#350]
![image](https://user-images.githubusercontent.com/45280212/48946517-f6242000-ef68-11e8-9852-304d0ee3e5de.png)
I ran ". / gradlew assemble Release" and got this error

**Comment by arkhan13** [comment]
having same issues after npm install native-base

**Comment by euharrison** [comment]
I had the same issue and resolved it when fix the gradle version following this instructions
- https://github.com/wix/react-native-navigation/issues/4757#issuecomment-468133753
- and running `react-native link` after them

**Comment by jakub-gonet** [comment]
Hi @Nocturne-FFG,

I believe your problem was solved by @euharrison's comment, so I'm closing it
If you still face this problem please reply.
