### ISSUE TITLE
Add Windows/UWP support

### ISSUE THREAD

**Issue by JulianAssmann** [software-mansion/react-native-gesture-handler#382]
As the the react-navigation library now depends on this library, projects using react-navigation cannot be used on windows (see https://github.com/Microsoft/react-native-windows/issues/2033). 
Therefore it would be nice, if this library supported the UWP.

**Comment by davidpett** [comment]
This should be easy enough to at least put a placeholder class that implements:

## constants
`State` {'UNDETERMINED', 'BEGAN', 'ACTIVE', 'CANCELLED', 'FAILED', 'END'}
`Direction`: {'RIGHT', 'LEFT', 'UP', 'DOWN'}

## methods
`createGestureHandler()`
`attachGestureHandler()`
`updateGestureHandler()`
`dropGestureHandler()`
`handleSetJSResponder()`
`handleClearJSResponder()`

Once those are in place, the library should actually run without errors. Adding actual native code to do what these methods should do could be done at a later phase.

I have no C# experience or I would take this on. If you use [react-native-create-library](https://facebook.github.io/react-native/docs/native-modules-setup) on a windows machine, it will stub out the class. @JulianAssmann or @mikerodham do either of you have the knowledge to implement this?

**Comment by JulianAssmann** [comment]
Thanks @davidpett for your answer.
I have C# experience (not in React Native wrappers though), so I will try to implement this on the coming weekend.

**Comment by mikerodham** [comment]
I have absolutely no C# experience unfortunately otherwise I'd love to have helped out.

**Comment by hmheng** [comment]
may I know if this has been resolved

**Comment by MungeParty** [comment]
As a workaround, it's possible to patch the issue in a postinstall script by stubbing out the windows implementation using the web files. The following works with react-native-windows@0.57.1 and react-navigation@3.5.1:
```
[
  './node_modules/react-native-gesture-handler/createHandler.web.js',
  './node_modules/react-native-gesture-handler/Directions.web.js',
  './node_modules/react-native-gesture-handler/GestureHandlerButton.web.js',
  './node_modules/react-native-gesture-handler/PlatformConstants.web.js',
  './node_modules/react-native-gesture-handler/Swipeable.web.js',
].forEach(file => webToWindows(file));
```
Here imagine `webToWindows()` takes a path and copies the contents to the same location, replacing `.web` with `.windows`. This isn't helpful if you need actual gesture support on windows, however.

**Comment by meddyrainzo** [comment]
What is the status of this. Seems like there is no immediate interest to support Windows with actual native code. I tried to play around with this but it seems rather difficult

**Comment by creambyemute** [comment]
As above mentioned, I got it working with:

You can create yourself a script at project root, mine is called `webToWindowsRNGH.js`:

```javascript
const fs = require("fs");

function callback(err) {
    if (err) {
        throw err;
    }
    console.log("Successfull!");
}

[
    "./node_modules/react-native-gesture-handler/GestureHandlerButton.web.js",
    "./node_modules/react-native-gesture-handler/PlatformConstants.web.js",
    "./node_modules/react-native-gesture-handler/RNGestureHandlerModule.web.js"
].forEach((inputPath) => {
    const splits = inputPath.split("./node_modules/react-native-gesture-handler/");
    const newFileName = splits[1].replace(".web.js", ".windows.js");
    const outputPath = "./node_modules/react-native-gesture-handler/" + newFileName;

    console.log(`Trying to copy ${inputPath} to ${outputPath}`);
    fs.copyFile(inputPath, outputPath, callback);
});
```

After that, adapt the package.json and add the postinstall script:
```"postinstall": "node ./webToWindowsRNGH"```

**Comment by j-piasecki** [comment]
Windows implementation is not planned at the moment. We can come back to this in the future.
