### ISSUE TITLE
Handle long press gesture with RectButton

### ISSUE THREAD

**Issue by KakarN** [software-mansion/react-native-gesture-handler#384]
I am not sure whether this is an issue, or maybe a feature request for the new versions. I would like to know whether Is it possible to handle the long press gesture in RectButton? I have tried RectButton with LongPressGestureHandler. 

```
<LongPressGestureHandler
      onHandlerStateChange={({ nativeEvent }) => {
        if (nativeEvent.state === State.ACTIVE) {
          Alert.alert("I'm being pressed for so long");
        }
      }}
      minDurationMs={800}>
      <RectButton onPress={() => Alert.alert("Rect button")}>
      <View style={{backgroundColor: 'red', width: 200, height: 200}} />
      </RectButton>
  </LongPressGestureHandler>
```

However, It is very inconsistent. LongPressGestureHandler does not always seem to work, maybe because I am using it inside a Flatlist, and so scrolling 1px also cancels the state.

**Comment by jakub-gonet** [comment]
Closing as this is quite an old issue. Probably `LongPressGH` with setting bigger `maxDist` is the way to go in that case.
