### ISSUE TITLE
Problem with BottomSheet example

### ISSUE THREAD

**Issue by avet-m** [software-mansion/react-native-gesture-handler#392]
Hi

Have a problem with [BottomSheet](https://github.com/kmagiera/react-native-gesture-handler/blob/master/Example/bottomSheet/index.js) example. I am trying to change ### **this._translateY** parameter manually.

in constructor declared animation @kmagiera 
```
        this._translateY = Animated.add(
            this._translateYOffset,
            Animated.add(this._dragY, this._reverseLastScrollY),
        ).interpolate({
            inputRange: [START, END],
            outputRange: [START, END],
            extrapolate: 'clamp',
        });
```
I want to change value of this._translateY (for example onPress) in another function but don't know how to do it.

**Comment by jakub-gonet** [comment]
This is related to Reanimated and probably outdated by now. If you have further concerns please reply.
