### ISSUE TITLE
Required auto closing for open Swipeable element when press anywhere on screen

### ISSUE THREAD

**Issue by St1maSphere** [software-mansion/react-native-gesture-handler#411]
Hi to everyone

Need to have ability to select only one Swipable component or close already swiped element on move through navigation, press outside element range, etc

Thanks in advance

**Comment by deepankarsandy** [comment]
Use `ref` to get swipeable instance and then call `close` on that to close.
For navigation use navigation lifecycle methods like `onWillBlur`.

[https://kmagiera.github.io/react-native-gesture-handler/docs/component-swipeable.html#close](url)

**Comment by St1maSphere** [comment]
@deepankarsandy 
Thank you for your answer
But it will not work for me, cause of dinamic list of options and absence of reason to manage status of component using my state

Is it possible to, somehow, move this handling to 'list' level and make it stateful?

**Comment by Freddy03h** [comment]
I think it can be something like this : https://github.com/facebook/react-native/blob/master/Libraries/Experimental/SwipeableRow/SwipeableFlatList.js

**Comment by selcukoguz** [comment]
Did anyone solve this issue.
Coz I'm stuck with this!

**Comment by St1maSphere** [comment]
@selcukoguz 
Sorry for delay
For now,  I am using an alternative solution: https://github.com/dancormier/react-native-swipeout
with param:
`close={selectedId !== currentRow.id}`

**Comment by selcukoguz** [comment]
@St1maSphere thx for answer.

**Comment by deepankarsandy** [comment]
A good alternative is ### NativeBase

**Comment by swathi2378** [comment]
@St1maSphere Did you find a way?

**Comment by kopax** [comment]
All link given here are broken, I am currently testing https://github.com/jemise111/react-native-swipe-list-view but it is flaggy, is this doing better animation? (I ask because react-native-swipeout is the ancestor if react-native-swipe-list-view and I was going to try react-native-gesture-handler Swipeable component) Thanks and best!

**Comment by jakub-gonet** [comment]
This should be resolved by [second comment](https://github.com/software-mansion/react-native-gesture-handler/issues/411#issuecomment-476621580).
