### ISSUE TITLE
Is it possible with Swipeable to stop row to dissapear and return to row to original position? 

### ISSUE THREAD

**Issue by Jalson1982** [software-mansion/react-native-gesture-handler#426]
Hello. I want to make that row swipe left and right and on release to return to his original position. Is it possible to achieve it ?

**Comment by jakub-gonet** [comment]
Could please describe your use-case?

**Comment by Jalson1982** [comment]
Uff man you can close it, it was on 25.01.2019 actual ahah I can not even remember what was wrong :). But anyway thx for reply :)

**Comment by jakub-gonet** [comment]
Yeah, we recently started cleaning up old issues, sorry for necrobumping 😄 

Cheers!
