### ISSUE TITLE
How to change the current gesture handler?

### ISSUE THREAD

**Issue by krszwsk** [software-mansion/react-native-gesture-handler#434]
Hi, I'm trying to achieve a drag and drop on an element that can begin only by performing a long press. My aim is to wait for the long press handler to activate and immediately allow the pan handler to take over.
My approach seems incorrect, I cannot find any API for doing such things. How would I go about implementing such feature? Thanks a lot.

**Comment by neiker** [comment]
Hi @krszwsk have you found a solution on this?

I have the same problem https://github.com/kmagiera/react-native-gesture-handler/issues/445

**Comment by osdnk** [comment]
Hello @krszwsk @neiker 
I made an example how to achieve it:
```javascript
<TapGestureHandler
  ref={this.tapRef}
  maxDurationMs={1000}
>
  <Animated.View>
    <PanGestureHandler
      waitFor={this.tapRef}
      onGestureEvent={this._onGestureEvent}
      onHandlerStateChange={this._onHandlerStateChange}>
      <Animated.View
        style={[
          styles.box,
          {
            transform: [
              { translateX: this._translateX },
              { translateY: this._translateY },
            ],
          },
          this.props.boxStyle,
        ]}
      />
    </PanGestureHandler>
  </Animated.View>
</TapGestureHandler>
```

**Comment by neiker** [comment]
@osdnk thank you for your response, but in my case seems don't work because my press and hold elements are inside a `ScrollView`. Using `waitFor`means `PanGestureHandler` will be fired on `TapGestureHandler` failed not matter what. It's ok in the case the reason was the timeout (`maxDurationMs`) but if the reason was it failed because `maxDist` reason, it should be the `ScrollView` than receive the event.

This is my code:
```javascript
render() {
    const { widget } = this.props;
    const { dragging } = this.state;

    return (
      <TapGestureHandler
        onHandlerStateChange={this._onTapHandlerStateChange} // This will made the widget `selected`
        ref={this.tapRef}
        maxDurationMs={500}
        numberOfTaps={1}
        maxDist={5} // User move they finger so ScrollView must receive the event
      >
        <Animated.View>
          <PanGestureHandler
            onGestureEvent={this._onPanGestureEvent}
            onHandlerStateChange={this._onHandlerStateChange}
            minPointers={1}
            maxPointers={1}
            waitFor={widget.selected ? undefined : this.tapRef} // Wait only if the widget is not selected
          >
            <Animated.View
              style={[
                styles.item,
                {
                  transform: [
                    { translateX: this._translateX },
                    { translateY: this._translateY },
                  ],
                },
              ]}
            >
              <Widget widget={widget} dragging={dragging} />
            </Animated.View>
          </PanGestureHandler>
        </Animated.View>
      </TapGestureHandler>
    );
  }
```

Here is where I'm testing this:
https://github.com/neiker/canvas/commit/e13615c5a410b5c9d5d97776783bfd0b99444767

**Comment by osdnk** [comment]
So maybe try to set `minDist` same as `maxDist` (or minimally smaller). Then it will be activated for a while

**Comment by neiker** [comment]
@osdnk do you mean to set `minDist` on the `PanGestureHandler`? Don't work, `PanGestureHandler` still receive the gesture. 

```javascript
render() {
    const { widget } = this.props;
    const { dragging } = this.state;

    return (
      <TapGestureHandler
        onHandlerStateChange={this._onTapHandlerStateChange} // This will made the widget `selected`
        ref={this.tapRef}
        maxDurationMs={500}
        numberOfTaps={1}
        maxDist={10}
      >
        <Animated.View>
          <PanGestureHandler
            onGestureEvent={this._onPanGestureEvent}
            onHandlerStateChange={this._onHandlerStateChange}
            minPointers={1}
            maxPointers={1}
            waitFor={widget.selected ? undefined : this.tapRef} // Wait only if the widget is not selected
            minDist={9}
          >
            <Animated.View
              style={[
                styles.item,
                {
                  transform: [
                    { translateX: this._translateX },
                    { translateY: this._translateY },
                  ],
                },
              ]}
            >
              <Widget widget={widget} dragging={dragging} />
            </Animated.View>
          </PanGestureHandler>
        </Animated.View>
      </TapGestureHandler>
    );
  }
```

**Comment by neiker** [comment]
@osdnk can you reopen the issue so it's more visible?

**Comment by jennmueng** [comment]
I have the same issue too. The `PanGestureHandler` is within a `ScrollView` and it activates every time the `TapGestureHandler` fails. 

Alternatively, is there a method to make `PanGestureHandler` activate ONLY when `LongPressGestureHandler` is active?

**Comment by jgoodhcg** [comment]
I'm trying do some drag and drop within a scroll view initiated by long press too.
I thought I could achieve this with `simultaneousHandlers` prop but the pan gesture handler cancels before the long press activates.

**Comment by Asupkay** [comment]
> Hello @krszwsk @neiker
> I made an example how to achieve it:
> 
> ```js
> <TapGestureHandler
>   ref={this.tapRef}
>   maxDurationMs={1000}
> >
>   <Animated.View>
>     <PanGestureHandler
>       waitFor={this.tapRef}
>       onGestureEvent={this._onGestureEvent}
>       onHandlerStateChange={this._onHandlerStateChange}>
>       <Animated.View
>         style={[
>           styles.box,
>           {
>             transform: [
>               { translateX: this._translateX },
>               { translateY: this._translateY },
>             ],
>           },
>           this.props.boxStyle,
>         ]}
>       />
>     </PanGestureHandler>
>   </Animated.View>
> </TapGestureHandler>
> ```

`    return (
      <View style={styles.body}>
            <TapGestureHandler
              ref={this.tapRef}
              onHandlerStateChange={this._onTapHandlerStateChange}
              key={item.key}
              numberOfTaps={1}
              maxDurationMs={10000}
            >
              <PanGestureHandler
                waitFor={this.tapRef}
                onGestureEvent={this._onGestureEvent}
                onHandlerStateChange={this._onHandlerStateChange}>
                <Animated.View
                  style={{
                    width: Dimensions.get('window').width/3,
                    height: Dimensions.get('window').width/3,
                    transform: [
                      { translateX: this._translateX },
                      { translateY: this._translateY },
                    ]
                  }}
                >
                  <Craving info={item} showName={this.props.showNames}/>
                </Animated.View>
              </PanGestureHandler>
            </TapGestureHandler>
      </View>
    );
`

I attempted to use this without a `ScrollView` and still ran into issues where the `PanGestureHandler` does not wait for the `TapGestureHandler`. In fact they both fire. I think this is because the pan is evaluated before the tap. I put a print out in `onTapHandlerStateChange` and `onHandlerStateChange` (Pan Handler) and I can see that the `onHandlerStateChange` fires Began before the `onTapHandlerStateChange` fires began so technically the `TapGestureHandler` is in UNDETERMINED which allows the pan gesture to start.

**Comment by jgoodhcg** [comment]
I also tried playing around with `minDist` on the pan handler. I still can't get the scroll, pan, and long press to all work with the experience I want. Long press to activate then drag in one continuous press. 

Decided to swap the long press for a double tap to initiate the drag mode on elements.

**Comment by astralfalcon** [comment]
I am also looking to activate my PanHandler after a LongPress in a scroll view.

**Comment by kimdhoe** [comment]
I'm trying to achieve a similar effect: **long-press items inside `ScrollView` to drag them around**. I used `LongPressGestureHandler` and `simultaneousHandlers` like below:

```jsx
<LongPressGestureHandler
  simultaneousHandlers={this.props.panRef}
  onHandlerStateChange={this.handleLongPressStateChange}
>
  <Animated.View>
    <PanGestureHandler
      ref={this.panRef}
      maxPointers={1}
      onGestureEvent={this.handleGestureEvent}
      onHandlerStateChange={this.handleGestureEvent}
    >
      <Animated.View
        style={{ transform: [{ translateX: this.translateX }, { translateY: this.translateY }] }}
      >
        <Text style={styles.entryText}>
          Hello World
        </Text>
      </Animated.View>
    </PanGestureHandler>
  </Animated.View>
</LongPressGestureHandler>
```

Then, the condition for calculating `y` position would be:

```jsx
translateY = cond(
  and(eq(this.panState, State.ACTIVE), eq(this.longPressState, State.ACTIVE)),
  [/* ... */],
  [/* ... */],
)
```

Now, I've been stuck at the `ScrollView` part. Pan handler consumes the gesture events, so scrolling doesn't work if touch starts from inside items. Wondering if it's possible to allow scrolling work before long-press.

What I'm trying to achieve is something like reordering feature in [Any.do](https://www.any.do/) or [Todoist](https://todoist.com/?lang=en).

![any.do](https://user-images.githubusercontent.com/10362796/65824932-9d6d9400-e2ab-11e9-8986-89efdfd50149.gif)

**Comment by mxmzb** [comment]
@kimdhoe have you found a workaround by now by any chance?

**Comment by kulyk** [comment]
Hey everyone,

I've finally found a way to create a drag-and-drop on long-press inside the `FlatList`. In my case, I don't need to rearrange the list items order. I have a dropzone on a screen and I need no handle cases when users drag the list item on it.

Anyway, I hope my code snipped would help you to deal with your particular scenario.
I'm sharing the most general piece of code. If you have any specific questions, ask me

I found out it's, most likely, impossible to use both `LongPressGestureHandler` and `PanGestureHandler` when we're dealing with the `FlatList`. Looks like it's impossible to pass the gesture to `Pan` when the `LongPress` is activated.

`LongPressGestureHandler` also provides coordinates, so it's possible to use it instead of `PanGestureHandler`.

```javascript
import React from 'react'
import { Animated, FlatList, Platform, View } from 'react-native'
import { LongPressGestureHandler, State } from 'react-native-gesture-handler'
import Modal from 'react-native-modal'

const MEASURE_TIMEOUT = Platform.select({
  android: 300,
  ios: 100,
})

class DraggableList extends React.Component {

  // translateX and translateY are not calculated for LongPressGestureHandler
  // This variables are used to get them
  x0 = null
  y0 = null

  listItemRefs = {}

  listItemMeasurements = {}

  measureTimeouts = {}

  // stores the position of our dragged element
  translate = new Animated.ValueXY({ x: 0, y: 0 })

  state = {
    dragging: null,
  }

  onGestureEvent = (event) => {
    const { x, y } = event.nativeEvent
    // calculate and set translationXY variables while dragging
    const translateX = x - this.x0
    const translateY = y - this.y0
    this.translate.setValue({ x: translateX, y: translateY })
  }

  onHandlerStateChange = (event) => {
    const { state } = event.nativeEvent
    if (state === State.ACTIVE) {
      this.onDragStart(event)
    }
    if (state === State.END || state === State.CANCELLED) {
      this.onDragEnd(event)
    }
  }

  onDragStart = (event) => {
    const { dragging } = this.state
    const { x, y } = event.nativeEvent
    // Finds the dragged list item
    // and renders it's copy over the FlatList
    const itemKey = this.findTouchedItemKey(x, y)
    if (itemKey && dragging !== itemKey) {
      this.x0 = x
      this.y0 = y
      this.setState({ dragging: itemKey })
    }
  }

  onDragEnd = (event) => {
    // Handle a momement when user drop the item somewhere

    // Clear initial touch gesture coordinates
    this.x0 = null
    this.y0 = null
  }

  removeHoverComponent = () => {
    this.setState({ dragging: null })
  }

  findTouchedItemKey = (touchX, touchY) => {
    const itemKeys = Object.keys(this.listItemRefs)
    const touchedItemKey = itemKeys.find((itemKey) => {
      const shape = this.listItemMeasurements[itemKey]
      if (!shape) {
        return false
      }
      return checkPointBoxIntersection(touchX, touchY, shape)
    })
    return touchedItemKey
  }

  measureAll = () => {
    // Coordinates are recalculated once their position
    // on the viewport changes. Otherwise, it's impossible
    // to find and highlight the touched item
    const itemKeys = Object.keys(this.listItemRefs)
    itemKeys.forEach(this.measureListItem)
  }

  measureListItem = (key) => {
    // setTimeout is required, otherwise all measurements will be 0
    if (this.measureTimeouts[key]) {
      clearTimeout(this.measureTimeouts[key])
    }
    this.measureTimeouts[key] = setTimeout(
      this._measureListItem(key),
      MEASURE_TIMEOUT
    )
  }

  _measureListItem = (key) => () => {
    const { dragging } = this.state
    const element = this.listItemRefs[key]
    if (!element || dragging) {
      return
    }
    element.measureInWindow(this._onItemMeasured(key))
  }

  _onItemMeasured = (key) => (x, y, width, height) => {
    this.listItemMeasurements[key] = { x, y, width, height }
  }

  setListItemRef = (key) => (ref) => {
    this.listItemRefs[key] = ref
    // Each item is measured, so it's possible
    // to calculate which list item is actually dragged
    // In my case I have a multicolumn FlatList, so
    // I use x, y, width and height
    this.measureListItem(key)
  }

  renderItem = ({ item, index }) => {
    const { draggedItemStyle, renderItem, keyExtractor } = this.props
    const { dragging } = this.state
    const itemKey = keyExtractor(item)
    const active = itemKey === dragging
    const ListItem = renderItem({ item, index, active })
    const wrapperStyle = []
    if (active) {
      // style your dragged item
      wrapperStyle.push(draggedItemStyle)
    }
    // `collapsable` prop is a must for Android
    // without it the measureInWindow won't work
    // as the View can be removed from the UI tree
    // as an optimization
    return (
      <View
        collapsable={false}
        style={wrapperStyle}
        ref={this.setListItemRef(itemKey)}
      >
        {ListItem}
      </View>
    )
  }

  renderHoverDraggingElement = () => {
    const { data, renderItem } = this.props
    const { dragging } = this.state

    // That's a hack for my particular case
    const index = data.findIndex((i) => i.id === dragging)
    const item = data[index]

    const ListItem = renderItem({ item, index, active: true })
    const { x, y } = this.listItemMeasurements[dragging]

    const style = {
      position: 'absolute',
      left: x,
      top: y,
      transform: [...this.translate.getTranslateTransform()],
    }
    return <Animated.View style={style}>{ListItem}</Animated.View>
  }

  render() {
    const { dragging } = this.state

    // For Android maxDist is set to Number.MAX_SAFE_INTEGER
    // with default value, the drag gesture will be canceled
    // https://kmagiera.github.io/react-native-gesture-handler/docs/handler-longpress.html#maxdist

    return (
      <>
        <LongPressGestureHandler
          maxDist={Number.MAX_SAFE_INTEGER}
          onGestureEvent={this.onGestureEvent}
          onHandlerStateChange={this.onHandlerStateChange}
        >
          <FlatList
            {...this.props}
            onMomentumScrollEnd={this.measureAll}
            renderItem={this.renderItem}
          />
        </LongPressGestureHandler>
        <Modal
          isVisible={Boolean(dragging)}
          animationIn="fadeIn"
          animationOut="fadeOut"
          hasBackdrop={false}
          style={styles.modal}
        >
          {dragging ? this.renderHoverDraggingElement() : <View />}
        </Modal>
      </>
    )
  }
}
```

If you need to rearrange items order, take a look at the next repositories:  [react-native-sortable-grid](https://github.com/ollija/react-native-sortable-grid), [react-native-draggable-flatlist](https://github.com/computerjazz/react-native-draggable-flatlist). I wouldn't use them as they both look abandoned, but maybe they would help you to come out with a solution.

**Comment by lafiosca** [comment]
Thanks for the approach suggestion @kulyk ! For those using the LongPressGestureHandler on individual views, I found that for Android I also needed to add `shouldCancelWhenOutside={false}`. Otherwise, if the touch ever got outside of the view being dragged, the gesture would cancel. (This didn't happen on iOS.)

**Comment by samiede** [comment]
While I'm still stuck at the long press problematic, I might have a solution for you @kimdhoe .

For enabling scrolling while dragging, I check the scroll positions distance to the edges of the screen and then use the scrollTo method of the scrollview:

```js
cond(and(
  eq(state, State.ACTIVE), greaterOrEq(absoluteY, windowHeight - 50)),
 call(
    [currentScrollPosition],
    ([value]) => store.scrollView.getNode().scrollTo({ x: 0, y: value + 10, animated: true })
))
```

I use an Animated.Value to track the currentScrollPosition. I also add the scrollPosition to the items while scrolling so it remains on the edge of the screen visually, it works really smoothly

![untitled](https://user-images.githubusercontent.com/6050746/70522964-55d47580-1b42-11ea-886e-7fc47420af3f.gif)
