### ISSUE TITLE
Error in settings.gradle on Windows

### ISSUE THREAD

**Issue by mi5ha** [software-mansion/react-native-gesture-handler#436]
I can not run the app on Android emulator because settings.gradle contains:

`project(':react-native-gesture-handler').projectDir = new File(rootProject.projectDir, '..\node_modules\react-native-gesture-handler\android')`

instead of:

`project(':react-native-gesture-handler').projectDir = new File(rootProject.projectDir, '..\\node_modules\\react-native-gesture-handler\\android')`

Problem is solved when I fix it manually.

**Comment by mebungler** [comment]
I guess react-native 0.58 has bug. I come across with this everytime I install a package. And debugger also fails to hot load. I resolved this by reverting to older version.

**Comment by khandal007** [comment]
I cannot run the app in android device because everytime when i link something the settings.gradle always gives error
project(':react-native-camera').projectDir = new File(rootProject.projectDir, '..\node_modules\react-native-camera\android')

Please give this solution I am unable to resolve it

**Comment by jakub-gonet** [comment]
This should be resolved on newer versions.
