### ISSUE TITLE
Updating props does not affect on dropping properties

### ISSUE THREAD

**Issue by osdnk** [software-mansion/react-native-gesture-handler#440]
## Example
```javascript
activeOffsetY={this.props.allowOverscroll ? null : 1}
```

## Expected behavior
With this code I want to set or invalidate given property. 

## Current behavior
If value has been dropped, it's not being sent to native site. Since GH manager on update does not create new GHs but modifying existing ones, values are not being set back to default ones (which are given only in Obj-C/Java constructors).

Changing properties with props/state does not support dropping values so after setting `allowOverscroll` (in this case) for the first time I cannot reset in null.

**Comment by wcandillon** [comment]
I am also affected by this issues. Props in the gesture handler cannot be updated once set.
