### ISSUE TITLE
Add tvOS Static Library Build Target to Support tvOS

### ISSUE THREAD

**Issue by hufkens** [software-mansion/react-native-gesture-handler#444]
Can you add a new tvOS Static Library build target for this package? We just upgraded to react-navigation 3.0.9 and it uses your library underneath. If I can be off any help let me know. 

I found an example on how to do this in another library: react-native-community/react-native-video@bed6089

I also file an issue for your other library react-native-screens, because it looks great, but we run into the same issue.

**Comment by osdnk** [comment]
So if it's not a big deal, could you make a PR?
I'kk merge immediately :)

**Comment by hufkens** [comment]
I tried to fix it in this PR https://github.com/react-native-community/react-native-video/commit/bed6089

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it. If you want to discuss this feature further, please reply.
