### ISSUE TITLE
Support updating gesture handler props with reanimated

### ISSUE THREAD

**Issue by brentvatne** [software-mansion/react-native-gesture-handler#453]
From a discussion with @kmagiera a few weeks ago:

<img width="1122" alt="screen shot 2019-02-05 at 11 01 27 am" src="https://user-images.githubusercontent.com/90494/52297395-7ede1580-2935-11e9-8ca2-7f80e9673f01.png">

(link that was shared in that conversation: https://github.com/react-navigation/react-navigation-drawer/blob/%40brent/reanimated/src/views/DrawerLayout.js#L497)

**Comment by tomekzaw** [comment]
With react-native-gesture-handler 2.0 API we now provide a mechanism called "manual activation" (see more here: https://docs.swmansion.com/react-native-gesture-handler/docs/next/api/gestures/manual-gesture) which allows for recognition logic to be implemented in JavaScript, possibly as Reanimated worklet (executed synchronously on UI thread), using Reanimated shared values. This sounds like an ideal solution for cases just like this one.
