### ISSUE TITLE
Incorrect ripple on RectButton when placed alongside with BorderlessButton

### ISSUE THREAD

**Issue by zamotany** [software-mansion/react-native-gesture-handler#455]
## Bug description

* `react-native`: `0.57.8`
* `react-native-gesture-handler`: `1.0.15`
* Can reproduce on: Nokia 6 (Android 8.1), Pixel 2 (Android 9), OnePlus 5T (Android 9)

When `RectButton` and `BorderlessButton` are placed together, ripple of `ReactButton` dimensions of `BorderlessButton`'s ripple. The behaviour starts to be even inconsistent/weird if when `RectButton` and `BorderlessButton` have `borderRadius`. Wrong behaviour can be observed when the app is killed and started again, reloading JS bundle usually produce correct results, but starting the app does not.

### 1. No border radius -> incorrect ripple size + unnecessary rounded corners

```js
<View style={{ flex: 1, justifyContent: 'space-evenly', width: '100%' }}>
  <RectButton>
    <Text>Hello</Text>
  </RectButton>
  <View style={{ width: '50%' }}>
    <BorderlessButton borderless={false}>
      <Text>World</Text>
    </BorderlessButton>
  </View>
</View>
```

![ripple](https://user-images.githubusercontent.com/17573635/52345793-5d0c8d80-2a1e-11e9-9857-68698d77d461.gif)

### 2. Border radius on `RectButton` -> wrong ripple size + ripple on `BorderlessButton` has rounded corners (it should not have)

```js
<View style={{ flex: 1, justifyContent: 'space-evenly', width: '100%' }}>
  <RectButton style={{ borderRadius: 5 }}>
    <Text>Hello</Text>
  </RectButton>
  <View style={{ width: '50%' }}>
    <BorderlessButton borderless={false}>
      <Text>World</Text>
    </BorderlessButton>
  </View>
</View>
```

![ripple2](https://user-images.githubusercontent.com/17573635/52347967-7e23ad00-2a23-11e9-9225-bb6fabba9e99.gif)

**Comment by olegbl** [comment]
It seems like the ripple just sizes itself to the last rendered Button of any kind.

e.g.
```
<RectButton
  style={{backgroundColor: '#CCC', width: 200, height: 60}}
  rippleColor={'#666'}
/>
<RectButton
  style={{backgroundColor: '#CCC', width: 150, height: 40}}
  rippleColor={'#666'}
/>
```
reproduces this quite readily:
![ripple sizing](https://user-images.githubusercontent.com/516977/54564720-ba82eb00-4989-11e9-9935-0370a6ff5539.gif)

**Comment by KakarN** [comment]
@zamotany @olegbl Were you guys able to fix this issue?

**Comment by olegbl** [comment]
Nope, just avoided using the button part of this lib.

**Comment by KakarN** [comment]
@olegbl Okay. I think I will have to do the same.

**Comment by siderakis** [comment]
This bug is still present in:
```
    "react-native": "0.61.0",
    "react-native-gesture-handler": "^1.3.0",
```

**Comment by GuBarca** [comment]
Still present, please fix

**Comment by analogApple** [comment]
Hi,
made work around which seems to work same way as `<RectButton>` but without glitch.
I've created new component and replaced it anywhere I used `<RectButton>`

here is a code snippet:
```
const NativeButton = props => {
  const { children, style, ...others } = props;
  return Platform.OS === 'android' ? (
    <View style={{ backgroundColor: '#ffffff00' }}>{/*setting background color stops borderless ripple*/}
      <BorderlessButton {...others} style={style}>
        {children}
      </BorderlessButton>
    </View>
  ) : (
    <RectButton {...others} style={style}>
      {children}
    </RectButton>
  );
};

export default NativeButton;
```

**Comment by rcstanciu** [comment]
Still reproducing

**Comment by FRizzonelli** [comment]
This is still happening and it's kinda a pain to handle. Having a proper Touchable component to handle all this "problems" is really hard. Is it possible to support default _borderless_ property?

**Comment by alessiocancian** [comment]
Still happening in v1.10.3

@jakub-gonet  is there a chance to see this fixed somehow? It's really annoying

**Comment by kesha-antonov** [comment]
Same here

**Comment by kesha-antonov** [comment]
For me what has worked is:

```
<TouchableWithoutFeedback
    style={stylesCommon.grow}
    onPress={toggleControlsActive}
  >
   ...
   <TapGestureHandler
        onHandlerStateChange={onHandlerStateChangeTap}
      >
        <BorderlessButton
          style={buttonStyle}
          rippleColor={RIPPLE_COLOR}
        >
          ...
```

**Comment by j-piasecki** [comment]
Hi! It seems to be working correctly for me (tested on GH from `main` at a144c0ebaba3b544d3455c7eced084d66dff5d7e, 2.3.2 should also work):

https://user-images.githubusercontent.com/21055725/159732398-d5fb888e-f941-4ae7-8657-de2af256e9d2.mp4

Could you check if upgrading solves it for you?

**Comment by piaskowyk** [comment]
It seems to be fixed, please notify us if not.
