### ISSUE TITLE
Not working with react-navigation v3

### ISSUE THREAD

**Issue by vinhtq** [software-mansion/react-native-gesture-handler#459]
If we try to wrap Screen with gestureHandlerRootHOC then we always get error like: 

`Invariant Violation: Element type is invalid: expected a string (for built-in components)...`

Did anyone successfully make this work with react-navigation? Please help

**Comment by aliazizi** [comment]
Im not know about your problem but Im using with react navigation v3 and I havent any problem

**Comment by devagul93** [comment]
I am getting the same issue.

**Comment by Jason-Cooke** [comment]
@vinhtq Are you able to provide any code?

**Comment by brkrtp** [comment]
+1 same issue. Not working android but ios is ok.

**Comment by jakub-gonet** [comment]
There's too little info to resolve this issue. Please provide a full log and preferably some code example.
