### ISSUE TITLE
Fresh project results in "duplicate symbols for architecture x86_64" errors

### ISSUE THREAD

**Issue by reinvanimschoot** [software-mansion/react-native-gesture-handler#463]
Hi guys

I have a strange problem. When I set up an entirely fresh project, set the build system to legacy and do

`yarn add react-native-gesture-handler`
`react-native link react-native-gesture-handler`

It creates an entry in my Podfile as such

`pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'`

Now, when I then do pod install and try to run my project from my xworkspace in xcode, I get

`ld: 980 duplicate symbols for architecture x86_64`

Can someone tell me what I am doing wrong?

**Comment by atoraby** [comment]
Same error here

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
If you need further help please reply.
