### ISSUE TITLE
'React/RCTDefines.h' file not found when i try to run my project in iOS. Any solution will be helpful

### ISSUE THREAD

**Issue by AarshApple** [software-mansion/react-native-gesture-handler#472]
i am using cocoapods for install all libs and after running react-native-link command the RNGestureHandler is linked in library section and when i try to run the project it gives me build failed with this error

**Comment by kbarralon** [comment]
Same here

**Comment by AarshApple** [comment]
Can you give your **package.json** and **podfile** contents and see that this library is linked properly!!

**Comment by jakub-gonet** [comment]
Hi!
This issue was inactive for a while and lacks information to solve it, so I'm closing it.
If you still face this problem don't hesitate to ask.
