### ISSUE TITLE
Nested TapGestureHandlers break single tap nativeEvent values 

### ISSUE THREAD

**Issue by gtfargo** [software-mansion/react-native-gesture-handler#476]
Nesting a `doubleTap` TapGestureHandler inside a single tap handler causes the single tap coordinate values to be {x: 0, y: 0}

[Example Here](https://snack.expo.io/@gtfargo/smiling-hummus)

**Comment by piaskowyk** [comment]
Hey, could you try to run your example with API v2? It should resolve your problem.
