### ISSUE TITLE
onGestureEvent on TapGestureHandler

### ISSUE THREAD

**Issue by rvolution** [software-mansion/react-native-gesture-handler#479]
Can someone confirm if the onGestureEvent property can be used on a TapGestureHandler?

onHandlerStateChange works fine, but onGestureEvent does not seem to fire.

In the docs where it describes the "Common handler properties" it says:

> This section describes properties that can be used with all gesture handler components

**Comment by ethanshar** [comment]
I'm experiencing the same problem

**Comment by papahigh** [comment]
+1

**Comment by kristianhasselknippe** [comment]
same

**Comment by jakub-gonet** [comment]
`onGestureEvent` doesn't work on `TapGestureHandler` due to the fact that tapping is a discrete gesture which means that it doesn't send a continuous stream of `gestureEvent`s. I agree that documentation is kinda imprecise on that but we can improve that :>

**Comment by mrousavy** [comment]
@jakub-gonet just to clarify, for `<TapGestureHandler>` we should instead only listen to `onHandlerStateChange` and run our actions there, right? Why not remove `onGestureEvent` from the `<TapGestureHandler>` entirely?

**Comment by jakub-gonet** [comment]
Right.

I'm pretty sure we can remove this callback. It wasn't done earlier because it's simpler to inherit base properties in impl than customize them, but I think it can be done without breaking anything so I may get around it eventually.
