### ISSUE TITLE
Missing Docs page for NativeViewGestureHandler

### ISSUE THREAD

**Issue by EvanBacon** [software-mansion/react-native-gesture-handler#495]
In this section [using-native-components](https://kmagiera.github.io/react-native-gesture-handler/docs/about-handlers.html#using-native-components) the [NativeViewGestureHandler](https://kmagiera.github.io/react-native-gesture-handler/docs/handler-native.md) leads to a dead link. 

Possibly related: #198

**Comment by felixaa** [comment]
Is it intentionally removed or? Any ETA on getting this up to date?

**Comment by damikdk** [comment]
[Still confused](https://github.com/kmagiera/react-native-gesture-handler/issues/492#issuecomment-556036049) :(
