### ISSUE TITLE
react-native-navigation overlays intercept all touch events when wrapped with gestureHandlerRootHOC

### ISSUE THREAD

**Issue by EliSadaka** [software-mansion/react-native-gesture-handler#514]
Our app is using React Native Navigation and so we're wrapping all our screen components with `gestureHandlerRootHOC`. However, with React Native Navigation overlays need to be registered similarly to screens, but if we wrap our overlays with `gestureHandlerRootHOC` then they intercept all touch events when visible and no other part of the app can react to them. When multiple overlays are shown at once, only the top-most one reacts to touches. Even an empty overlay component will intercept all touches if it is wrapped with `gestureHandlerRootHOC`. Is there a way around this issue?

```
// registering an overlay
Navigation.registerComponentWithRedux('DashboardOverlay', () => gestureHandlerRootHOC(DashboardOverlay), Provider, store);
```
```
// showing an overlay
Navigation.showOverlay({
    component: {
        id: 'DashboardOverlay',
        name: 'DashboardOverlay',
        options: {
            overlay: {
                interceptTouchOutside: false
            }
        }
    }
});
```

**Comment by EliSadaka** [comment]
I found a workaround by passing layout props to `gestureHandlerRootHoc()` to override the default flex value of 1:

`Navigation.registerComponentWithRedux('DashboardOverlay', () => gestureHandlerRootHOC(DashboardOverlay, {flex: 0}), Provider, store);`

**Comment by kiroukou** [comment]
Hello,
I'm having the same issue here.. but your hack doesn't seem to work for me so far..
Any other feedback you can share?

Thanks !

**Comment by osdnk** [comment]
Could you attach some repro example? I'm not very familiar with RNN 😢

**Comment by kiroukou** [comment]
I would love to, but I'm using haxe language to generate the JS etc, so that would not help you much.
I'd need to isolate the pb on a full js project, I'll let you know if I can do that anytime soon.

It does work perfectly on iOS platform (simulators) but on my android phone I can see the issue.. (I can see the react component receiving the touch event, but nothing seems to be broadcasted..) (I can get the side menu to open etc, just no click/touch)

**Comment by kiroukou** [comment]
@osdnk Do you have any technical details about the implementation on Android platform so I can have a look ?
Is there any event capture system  (queuing etc.) and dispatching to subviews on the process?

**Comment by nikolas7892** [comment]
Any updates on this? Using flex: 0 will prevent any touch events for the children in that wrapped component...

**Comment by alexduckmanton** [comment]
Has anyone had any luck with this issue?

@osdnk I've made an example here: https://github.com/alexduckmanton/overlayDemo

In the example, the red square is shown in an overlay. On iOS the `interceptTouchOutside` property works and you can still scroll the text, whereas on Android scrolling is blocked.

Any thoughts on how we can resolve this one?

**Comment by e-molochko** [comment]
@alexduckmanton Hm. I have everything worked on android but not on ios. Somehow my showOverlay component wraps all the screen(even if i have set height to it).  So my component have right height, but all overlay stretched all over the screen(only on IOS)

For android u could use this
`gestureHandlerRootHOC(Overlay, {flex: 0)`

**Comment by alexduckmanton** [comment]
Thanks @e-molochko unfortunately my actual situation is a little more complex, so using `gestureHandlerRootHOC(Overlay, {flex: 0})` won't work for me. 

I'm using React Native Gesture Handler to control a bottom sheet, so the overlay needs to be able to take up the whole screen so I can transition an element from the bottom to the top.

**Comment by geroale** [comment]
Is it possible to merge these changes into the master?

**Comment by gp3gp3gp3** [comment]
This is still an issue with the latest gesture handler changes.  It may work for modals, but overlays with a `flex: 1` style will still catch all touch events.

**Comment by piaskowyk** [comment]
Hey, could you provide a repo to reproduce your issue? The version of navigation is important here, could you update the version of navigation in your project also?

**Comment by phuongwd** [comment]
@piaskowyk It's still happening on latest version.

 It caused by  [ container: { flex: 1 },](https://github.com/software-mansion/react-native-gesture-handler/blob/82e613cbed4c81946ab8e3b6bd77d79097b69972/src/gestureHandlerRootHOC.tsx#L28)

**Comment by erennyuksell** [comment]
same issue still happening on latest version.

**Comment by erennyuksell** [comment]
any updates?

**Comment by aight8** [comment]
Any ideas how to solve this?

**Comment by ninjz** [comment]
Looks like it's still a problem. Anyone figure this one out?

**Comment by james-ovens-eurostar** [comment]
This is still an issue, this issue should not be closed
