### ISSUE TITLE
Enable recommended warnings. Perform changes: Yes or no?

### ISSUE THREAD

**Issue by Steffi3rd** [software-mansion/react-native-gesture-handler#536]
<img width="1426" alt="Capture d’écran 2019-03-22 à 22 46 32" src="https://user-images.githubusercontent.com/814410/54854775-5ac37180-4cf4-11e9-9646-a036c8306dd4.png">

**Comment by radex** [comment]
@Steffi3rd Yes, do it!

**Comment by jakub-gonet** [comment]
This issue was not active for some time and it's not really actionable so I'm closing it.
If you need further help please reply.
