### ISSUE TITLE
Documentation additions

### ISSUE THREAD

**Issue by donovanhiland** [software-mansion/react-native-gesture-handler#542]
I just went through the setup process and ran into a few places where I had to do things that were not documented. Specifically on the android side. Gradle changes, and code additions in places that are not documented other than through the example project. With some direction I'd be happy to contribute that documentation.

**Comment by osdnk** [comment]
Hello, @donovanhiland 
Can you point these places? We thought that that process of installation is clear enough. 🤔

**Comment by donovanhiland** [comment]
Hi! Sorry I think the reason I was having issues following the documentation is because in the project I'm working on I'm unable to use `react-native link`. The steps I thought were missing were actually there, I just had to do it manually.

**Comment by jakub-gonet** [comment]
Hi @donovanhiland,
any update on this?
