### ISSUE TITLE
How can I close sibling swiped out item when tap an item?

### ISSUE THREAD

**Issue by wenjoy** [software-mansion/react-native-gesture-handler#543]
(1th item)  [---------------[--remove--]]
(2nd item) [------<swiping-----[--rem]]
When 2nd item swiping out, I want to close the 1st item i.e. hide remove button?
Any help would be appreciate.

**Comment by darrylyoung** [comment]
I'm also looking for an answer to this question. I have a feeling you can use refs to keep track of what's open and then, when opening another, close the rest. I haven't yet managed to get it working, though. 🤔

**Comment by swathi2378** [comment]
@wenjoy  I am looking for the same feature. Did you find a way?

**Comment by wenjoy** [comment]
@darrylyoung  yep, I finally implemented it just like your thought out. 
@swathi2378 as @darrylyoung point out the right path,  if any details needed pls let me know.

**Comment by darrylyoung** [comment]
Hi, @wenjoy. Glad to hear that you managed to get it working. I ended up not using swipeable items at all but seeing as I've seen quite a few people asking about this, it might still be worth sharing some code here for those who stumble across this in future.

**Comment by wenjoy** [comment]
As @darrylyoung said, I'k like paste primary code here in case anyone need it:
```
...

updateRef = (ref, cartItem) => {
    if (ref !== null) {
      this.swipeables.set(cartItem, ref);
    }
  };

  close = () => {
    this.swipeables.forEach((swipable) => {
      if (swipable && swipable.close && swipable.state.rowState === -1) {
        swipable.close();
      }
    });
  };
...
  <Swipeable
        ref={ref => this.updateRef(ref, item)}
        onSwipeableRightWillOpen={this.close}
        overshootRight={false}
        overshootFriction={20}
      >
...
```

**Comment by caki0915** [comment]
I ran into the same problem and took a slightly different approach. 

I added a small wrapper around `Swipeable` that adds a prop: `open`

```js
import Swipeable from 'react-native-gesture-handler/Swipeable';
import React, { useRef, useEffect } from 'react';

export default ({ open, ...props }) => {
  const ref = useRef();
  useEffect(() => {
    if (ref.current && !open) {
      ref.current.close();
    }
  }, [ref.current, open]);
  return <Swipeable ref={ref} {...props} />;
};
```

Now you can control your Swipeables in a stateful way without the need for saving a list of refs:

```js
const [open, setOpen] = useState(null);
. . .

<Swipeable
   open={item.id === open}
   onSwipeableWillOpen={() => setOpen(item.id)}
    >
. . .
```

Maybe an `open` prop can be added into the Swipeable component in the future?
