### ISSUE TITLE
There should be instructions for manual installation

### ISSUE THREAD

**Issue by jedabero** [software-mansion/react-native-gesture-handler#551]
In my project I can't run `react-native link <package-name>` because it just hangs and re-links already linked packages.

So there should be instructions for linking this package manually.

**Comment by mcchrish** [comment]
Has anyone come around with this already? `react-native link` doesn't play well with multi targets and android flavors.

**Comment by jedabero** [comment]
@mcchrish I recommend you to try the following: 
- Create a new project
- Commit any changes
- Then link the library
- Finally, with git check what are the changes after linking and apply them manually
I know this is tedius but it's the best way to avoid any issues due to linking

**Comment by joshuapinter** [comment]
It would be great if anybody could put what's required for manual installation. If I can get it working I'll post back here but any help would be appreciated.

**Comment by MadhuvanthGopalan** [comment]
On iOS, 

if you are **using Cocoapods**, add the following to the Podfile.

1. pod 'RNGestureHandler', :git => 'https://github.com/kmagiera/react-native-gesture-handler', :tag => '1.3.0'
Note- values to :tag (or you may want to specify a branch) could vary according to your need or/and the time you are doing the linking. Best way would possibly be to look at the podspec file within your /node_modules/react-native-gesture-handler/RNGestureHandler.podspec

2. Run pod install on the native side

You're good to go.

If you are **not using Cocoapods**, you will have to follow [this](https://facebook.github.io/react-native/docs/linking-libraries-ios#manual-linking) and link it manually. 

These instructions probably apply to most, if not all, of the libraries that has native dependencies.

**Comment by joshuapinter** [comment]
What about Android, though?

**Comment by MadhuvanthGopalan** [comment]
About Android- In the process of figuring out. Any help there appreciated.

**Comment by joshuapinter** [comment]
I was able to install it on a clean React Native app so I’ll try to compile the instructions and add them here and create a PR for the README.

**Comment by IanVS** [comment]
Any word on this?  I'm struggling to manually link, and it doesn't seem like the docs have any help other than to use `react-native link` (which doesn't work for me).

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
If you need further help please reply.
