### ISSUE TITLE
TouchableNativeFeedback inconsistency with React Native's

### ISSUE THREAD

**Issue by todorone** [software-mansion/react-native-gesture-handler#557]
`TouchableNativeFeedback` of RNGH is inconsistent with RN's internal component:
```
<TouchableNativeFeedback background={TouchableNativeFeedback.Ripple('white', false)}>
    <View style={{ width: 50, height: 50, marginBottom: 100 }} />
</TouchableNativeFeedback>
```
This code results in nice effect with RN's internal component, while with RNGH's component we have ripple effect not just on `View`'s area, but also on all `marginBottom`'s area, which looks ugly...

**Comment by sudiddo** [comment]
yes, please fix :(

**Comment by FRizzonelli** [comment]
@kmagiera Any news?

**Comment by todorone** [comment]
@piaskowyk Just checked. The issue is still relevant with version `2.1.0`. Seems, that RNGH's component does not take into consideration 2nd parameter of `TouchableNativeFeedback.Ripple` - `borderless`. It always acts like it's `true`, even if `false` is passed. RN's component handles properly both `borderless = true | false`.
