### ISSUE TITLE
TouchableWithoutFeedback inside of TapGestureHandler

### ISSUE THREAD

**Issue by Chehow** [software-mansion/react-native-gesture-handler#558]
I have react native TouchableWithoutFeedback inside of TapGestureHandler. If I press to TouchableWithoutFeedback  then onHandlerStateChange with 'state === State.END' is called, but what should I do if I want to skip 'tap' event if TouchableWithoutFeedback is pressed (while I still should get 'tap' in some other area is pressed)?

I tried to replace RNTouchableWithoutFeedback with GHTouchableWithoutFeedback but GHTouchableWithoutFeedback does not work inside of TapGestureHandler.

Thank you.

NOTE. I noticed this behaviour on IOS platform. On Android behaviour is different but wrong as well: RNTouchableWithoutFeedback does not work inside of TapGestureHandler.

**Comment by zsaraf** [comment]
I'm having this exact same issue. Shouldn't only one TapHandler be called at a time?

**Comment by kkafar** [comment]
Hi @Chehow,
could you provide repro? (Snack / repo / code snippet)
