### ISSUE TITLE
Swipeable interfering with ScrollView

### ISSUE THREAD

**Issue by alexthebake** [software-mansion/react-native-gesture-handler#591]
I'm trying to use the `Swipeable` component inside of a `ScrollView` to implement "swipe to delete". The swipe to delete feature and the `ScrollView` work as expected. However, if I try to scroll up and down and start a vertical gesture on a `Swipeable`, it registers a horizontal gesture instead. I thought maybe something like `friction` would fix this, but it seems like that doesn't work. Is there already a prop or solution for this? Some kind of threshold for registering the right gesture, or a common way to use `Swipeable` within a `ScrollView`?

**Comment by adamczyk777** [comment]
Hey there @alexthebake, would you mind posting some kind of a video with pointer enabled to let us see what do you exactly mean? Also in the example app, there is a scrollable list with Swipeables. If there is not enough data to scroll just copy some objects and it will be scrollable it is in dir `Example/swipeable/index.js` to be precise.

**Comment by jakub-gonet** [comment]
Hi @alexthebake!

I think this issue is outdated and @adamczyk777 provided a viable solution so I'm closing it.

**Comment by kopax** [comment]
Hello, I am facine the same issue, what's the fix please?
