### ISSUE TITLE
Swipeable extremely slow inside large FlatList

### ISSUE THREAD

**Issue by sintylapse** [software-mansion/react-native-gesture-handler#596]
Swipeable is extremely slow on first render of large FlatList (70 items) and when rotating device/simulator. When you open a screen with FlatList of Swipeable items and immediately try to swipe, the animation will be laggy. The same thing when you rotate device/simulator. 

I tried the latest example inside the repo https://github.com/kmagiera/react-native-gesture-handler/tree/master/Example , the only thing I change in code - I added 70 items instead of 8. Here is the video

![ScreenRecording20190502at2-3](https://user-images.githubusercontent.com/12295016/57103922-b3445080-6d2f-11e9-9c9c-e3ee8d1120e0.gif)

It makes impossible to use Swipeable component in real-world applications. Is there any way to use swipeable functionality in a performant way? Maybe using with react-native-reanimated?

**Comment by geroale** [comment]
Same problem here. @sintylapse have you solved this in any way?

**Comment by marf** [comment]
Same problem here, there is a performance drop with large flatlists.

**Comment by sintylapse** [comment]
@geroale, @marf I used [react-native-interactable](https://github.com/wix/react-native-interactable) instead

**Comment by marf** [comment]
Thank you bery much for your hints, with [react-native-interactable](https://github.com/wix/react-native-interactable) we do not have any performance issues!

**Comment by lander854** [comment]
Same problem here

**Comment by kidfrom** [comment]
Same problem here with only 40 items. [FlatList with Swipeable example's github repository](https://github.com/kidfrom/g2_react_native/tree/0a514989076b28cf889dcef952f2eace884ce3cb/storage)

**Comment by voids** [comment]
Same problem, but I use [Flipkart/recyclerlistview](https://github.com/Flipkart/recyclerlistview) instead FlastList it works well.

**Comment by kkafar** [comment]
Closing as #1531 duplicates this issue. Discussion can be moved there
