### ISSUE TITLE
createHandler could not be found

### ISSUE THREAD

**Issue by pvanny1124** [software-mansion/react-native-gesture-handler#597]
installed version 1.2.1 and the build succeeds but I get this 
<img width="384" alt="Screen Shot 2019-05-03 at 2 21 54 AM" src="https://user-images.githubusercontent.com/26369185/57122363-e811d100-6d4a-11e9-8118-dc11935f07db.png">

i made sure to link the library manually and nothing.
im at a loss. any ideas?

**Comment by jakub-gonet** [comment]
Hi @pvanny1124,
really sorry for the late response.

I think this issue is outdated, so I'm closing it, but if you still face this problem I'm happy to assist.
