### ISSUE TITLE
Limit PanGestureHandler to be triggered only from left or right side of the screen

### ISSUE THREAD

**Issue by cdn34** [software-mansion/react-native-gesture-handler#608]
So far I've been able to limit the area on which the swipe can be triggered by using :

```<PanGestureHandler hitSlop={{ left: 0, width: 48 }} >```

This makes it only be triggered if the gesture started from the left side of the screen, however I would like this behaviour on the right side as well, but it seems that whenever the `width` property is defined, we can't have both `left` and `right` defined simultaneously.

Any idea on how I may be able to do this ?

**Comment by Rhomennik** [comment]
up ?

**Comment by KamauIan** [comment]
> So far I've been able to limit the area on which the swipe can be triggered by using :
> 
> `<PanGestureHandler hitSlop={{ left: 0, width: 48 }} >`
> 
> This makes it only be triggered if the gesture started from the left side of the screen, however I would like this behaviour on the right side as well, but it seems that whenever the `width` property is defined, we can't have both `left` and `right` defined simultaneously.
> 
> Any idea on how I may be able to do this ?

Did you find a solution for this?

**Comment by jkadamczyk** [comment]
Could you provide a minimal reproduction for that? Like a snack?

**Comment by j-piasecki** [comment]
Hi! You can write your own custom activation criteria using `manualActivation` and `touch events` introduced in Gesture Handler 2.0. [Here's a quick tutorial on them.](https://docs.swmansion.com/react-native-gesture-handler/docs/manual-gestures/manual-gestures)
