### ISSUE TITLE
ScrollView horizontal mode getting stuck on android when releasing out of container

### ISSUE THREAD

**Issue by drewhamlett** [software-mansion/react-native-gesture-handler#612]
Might be related or similar to #560 

If I swipe and release outside the container the snapping gets stuck on Android.  This happen if snapping is on or off.  It doesn't happen with the react-native ScrollView(on Android) or on iOS with either(GH or RN).
https://snack.expo.io/@drewhamlett/vigorous-ice-cream

<img width="416" alt="Screen Shot 2019-05-25 at 9 50 43 AM" src="https://user-images.githubusercontent.com/1056587/58370281-a18b3e80-7ed2-11e9-9000-72d7c01ef91d.png">

**Comment by drewhamlett** [comment]
I guess this is related to shouldCancelWhenOutside.  I was thinking it would behave the same on ios and android?  Either way setting that to false fixes the android issue.

**Comment by yairopro** [comment]
+1

**Comment by yairopro** [comment]
> I guess this is related to shouldCancelWhenOutside. I was thinking it would behave the same on ios and android? Either way setting that to false fixes the android issue.

So `shouldCancelWhenOutside={false}` solved the problem.
Thanks @drewhamlett

**Comment by jkadamczyk** [comment]
I'll close this one as there is a workaround for that and the repro is outdated and the overall issue is old. Will reopen if this is still an issue 😄
