### ISSUE TITLE
Inconsistent buttons bug

### ISSUE THREAD

**Issue by KakarN** [software-mansion/react-native-gesture-handler#618]
I have a screen (**HomeScreen**) with a button (`RectButton`) to navigate to a different screen (**TagScreen**).

On the **TagScreen**, I have list of names which can be tagged (_usernameList_), and an empty list to contain names which will be tagged (_taggedUserList_).

Both the list (_usernameList_ and _taggedUserList_) have User items, which are wrapped inside `RectButton`, to toggle its tagged state.

However, after I have tagged/selected one User, the button does not ripple to its full height and width. It just displays a rectangular shaped ripple around the corner of the View.

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/9060759/58633163-4d82be80-8305-11e9-8bb0-a9d0b528e9eb.gif)

As you can see from the above video, after a user is selected, only the first selected user's button work properly.

I have made a snack which reproduce the same issue. [Bug Snack](https://snack.expo.io/@kakarn/button-bug).

What I have found:

1. If the TagScreen is rendered in the App.js without any navigation stuff, button seems to work fine.

2. If the _taggedUserList_ elements are removed from the TagScreen, the _usernameList_ element buttons seems to work properly.

**Comment by 4yki** [comment]
+1

**Comment by dacsang97** [comment]
Same with me.

**Comment by kesha-antonov** [comment]
I have same
Is it fixed?

**Comment by Andarius** [comment]
Any update on this ?

**Comment by sweebee** [comment]
this issue still exists.

**Comment by Andarius** [comment]
Seems to be working in 1.5.0

**Comment by Andarius** [comment]
I seems to happen only when `borderRadius` is set.
