### ISSUE TITLE
using your android lib in another project

### ISSUE THREAD

**Issue by farfromrefug** [software-mansion/react-native-gesture-handler#624]
I am working on a Nativescript module for gesture. I love the work you ve done on the android lib. I would like to use it.
There are 2 ways to do that:
- copy/paste your code which i don't really like
- release your gesture handler library so that everyone can use it.

What do you think? Would you be ok with releasing your android lib on maven? maybe using bintray?

**Comment by jakub-gonet** [comment]
We don't plan on releasing RNGH as a standalone android library, but I'm happy to merge PR configuring that.
