### ISSUE TITLE
Task :react-native-gesture-handler:checkDebugManifest FAILED

### ISSUE THREAD

**Issue by Loboa** [software-mansion/react-native-gesture-handler#626]
![Screenshot from 2019-06-05 14-10-06](https://user-images.githubusercontent.com/27291657/58955331-003a9d00-879c-11e9-8d9e-245c48a13392.png)

(Linux) - If you are experiencing this problem , just use SUDO before 'react-native run-"

**Comment by jakub-gonet** [comment]
Hi @Loboa,
I'm sorry this issue went unnoticed.

Unfortunately, your description is kinda vague and this issue is probably outdated by now, so I'm closing it.

If you still face this problem I'm happy to help you.

**Comment by Loboa** [comment]
Hi Jakub

i was saying that you have to run it as an administrator (sudo on linux)
for the error to clear
