### ISSUE TITLE
translationY and translationX can be out of Device Coordinates After Scale and Translation Animations

### ISSUE THREAD

**Issue by MehmetKaplan** [software-mansion/react-native-gesture-handler#627]
When making some heavy animations bundled with drags, the translationY and translationX values strangely comes with values out of device coordinates. 

Obviously the expectation is whatever happens, the absolute value of the translateX and translateY values should be within the device coordinates.

You can find an example snack that I prepared [here](https://snack.expo.io/@mehmetkaplan/c8a8c6). This snack simply moves a picture on the screen while dragging. If the drag reaches to the edges of the screen, it scales the picture to half size and jumps towards the opposite edge. (This is put here just to regenerate the problem.)

If you play with the image for a little while, after some certain point you'll probably see the image is off the screen and either translationX or translationY value is out of screen coordinates.

My suspicion is, the rescaling somehow effects the pan and the translation values are out of control.

Any suggestion, if this is a bug or am I doing something wrong?

**Comment by smartcris** [comment]
Dunno if my problem is related to this issue but when I drag an image on the top left corner the x and y are negative values, shouldn't be 0 instead ? Ive created a [snak expo](https://snack.expo.io/@smartcris/xy-coordinates) here if someone wanna take a look .

**Comment by MehmetKaplan** [comment]
Handled manually tracking the coordinate values.
