### ISSUE TITLE
Request to feature react-native-gesture-handler on Docusaurus users page

### ISSUE THREAD

**Issue by ericbuss** [software-mansion/react-native-gesture-handler#633]
Hello, we would like to feature your project to the Docusaurus [users](https://docusaurus.io/en/users) page.

If you are okay with it, are you able to provide a logo we can use? Additional information can be found [here](https://github.com/facebook/Docusaurus/issues/1437)

**Comment by jakub-gonet** [comment]
I guess it's a bit outdated now 😅 

We're currently using Docusaurus v2.
