### ISSUE TITLE
Swipeable does not work on Android on RN 0.59.8

### ISSUE THREAD

**Issue by pani7** [software-mansion/react-native-gesture-handler#643]
Hi, i am using gesture-handler with react-native-navigation and i followed setup for linking with that library by adding to MainApplication.java: 

-imported -` import com.swmansion.gesturehandler.react.RNGestureHandlerPackage;`;
- added - `new RNGestureHandlerPackage()`

In app i wrapped screen like this: 

`Navigation.registerComponent(
    screens.RESERVATIONS,
    () => props => (
      <Provider store={store}>
        <ReservationsScreen {...props} />
      </Provider>
    ),
    () => gestureHandlerRootHOC(ReservationsScreen)
  );`

However swipeable does not work on android. It builds without errors, works on IOS but android does not respond to swipes. What am i doing wrong?

**Comment by Aure77** [comment]
Maybe you miss these instructions for create root view on android : https://kmagiera.github.io/react-native-gesture-handler/docs/getting-started.html#android

**Comment by mushinz** [comment]
We do also have this problem, working on IOS, build without error and screen is ok on Android, but gestures don't work

**Comment by Anoxy** [comment]
any update on this ?

**Comment by bloussou** [comment]
Aure77 gave the solution

**Comment by JeremyBradshaw7** [comment]
I'm also having the issue of Swipeable not working on Android but only when it's inside a ScrollView inside a Modal. I did follow the instructions pointed to by Aure77 but only the standard instructions as I wasn't sure if "one of the native navigation libraries" referred to includes react-navigation, and what to do if it does.

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
If you need further help please reply.
