### ISSUE TITLE
App has not been registered

### ISSUE THREAD

**Issue by Lakeyour** [software-mansion/react-native-gesture-handler#646]
Hello I'm having an issue with the gesture handler and I have deducted that it is related to the gestureHandlerRootHOC

`Navigation.registerComponent('./screens/Sustainability', () =>
    gestureHandlerRootHOC(Sustainability));`

I have wrapped **all** of my screens with HOC like instructed in the docs here
> Instead of changing Java code you will need to wrap **every** screen component using **gestureHandlerRootHOC** on the JS side. This can be done for example at the stage when you register your screens.

This is the error I'm getting
<img width="326" alt="image" src="https://user-images.githubusercontent.com/25793711/59770188-deffa380-92a7-11e9-8ad3-2e140f55b876.png">

And from what I understand this line of code has not happened for the Initializing screen
Wouldn't be Sustainability in this case but its just here as an example
`Navigation.registerComponent('./screens/Sustainability', () =>
    gestureHandlerRootHOC(Sustainability));`

**Comment by Lakeyour** [comment]
This error could also be due to the registerComponent part, but I previously had this
`Navigation.registerComponent('Home', () => require('./screens/Home').default)`

And that was **not a problem**, the problem appears when I want to introduce the gestureHandlerRootHOC

**Comment by jakub-gonet** [comment]
Seems like a problem with Wix navigation.

This issue was not active for some time so I'm closing it.
If you need further help please reply.
