### ISSUE TITLE
Yellow highlight on TouchableWithoutFeedback

### ISSUE THREAD

**Issue by phillmill** [software-mansion/react-native-gesture-handler#659]
Hi all,

I'm having an issue with TouchableWithoutFeedback. 

I am using it to wrap an image (which also has gesture handlers on it to pinch to zoom/pan around). I noticed that while panning the image, if you touch the image with a second finger, the entire TouchableWithoutFeedback highlights with a yellowish background color. The highlight appears to happen on pressIn (as soon as you touch it with a second finger).

I should also note I am using several event properties of TouchableWithoutFeedback:

```
<TouchableWithoutFeedback
  onPress={this.handleOnPress}
  onLongPress={this.handleOnLongPress}
  onPressIn={this.handeOnPressIn}
>
  <Image source={require('./someimage.jpg')}></Image>
</TouchableWithoutFeedback>
```

Any ideas?

**Comment by WoLewicki** [comment]
@phillmill Is this issue still present in the newest version? If so, could you provide a full reproduction of the problem in a form of a snack or simple repo?
