### ISSUE TITLE
 error: cannot find symbol

### ISSUE THREAD

**Issue by uendar** [software-mansion/react-native-gesture-handler#662]
error: cannot find symbol
           ` String overflow = ((ReactViewGroup) view).getOverflow()`

 "react-native-gesture-handler": "^1.0.5",

**Comment by viralS-tuanlv** [comment]
just remove all that on function and return true it will fine

**Comment by jakub-gonet** [comment]
This issue was not active for some time and lacks information so I'm closing it.

Please provide more information (stack traces, full error logs, where it shows up, etc) to make this issue actionable.
