### ISSUE TITLE
Invariant Violation: Element type is invalid: expected a string

### ISSUE THREAD

**Issue by harishlalwani** [software-mansion/react-native-gesture-handler#663]
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

We are facing above error using touchable element form react-native-gesture-handler library.

Importing gesture handler - 

    import 
    {
     TouchableOpacity,
     TouchableHighlight,
     TouchableWithoutFeedback
    } 
    from 'react-native-gesture-handler';

using it
     
    <TouchableOpacity style={{flexDirection:'row', marginLeft:'3%'}} onPress={() => this.showFilter()}>
           <Text style={[styles.filterText,{}]}>{mealreviews.state.filterValue}</Text>
           <Image source={require('../../../assets/home/ic_down_arrow.png')} style={styles.filterImage}/>
      </TouchableOpacity>

React native version - 0.52
Gesture Handler Version - 1.0.14

**Comment by jakub-gonet** [comment]
This issue is quite old and missing repro example so I'm closing it.

If you still experience this problem please provide repro.
