### ISSUE TITLE
cannot find symbol    String overflow = ((ReactViewGroup) view).getOverflow();

### ISSUE THREAD

**Issue by uendar** [software-mansion/react-native-gesture-handler#666]
cannot find symbol    String overflow = ((ReactViewGroup) view).getOverflow();

**Comment by jakub-gonet** [comment]
Duplicate of #662

**Comment by TivanDev** [comment]
just run 
`npm install react-native-gesture-handler@1.0.5
`
and secend step
`npx jetify`

then react-native run-android
