### ISSUE TITLE
TouchableOpacity does not render overflow (shadows etc)

### ISSUE THREAD

**Issue by stevelizcano** [software-mansion/react-native-gesture-handler#675]
When rendering a button or anything that has an overflow, such as a shadow, the TouchableOpacity does not render (as of Expo SDK 33) any overflow. When setting overflow: 'visible" there is no change. Switching back to RN default TouchableOpacity gives normal, expected behavior (with shadows)

**Comment by rszalski** [comment]
I stumbled upon the same issue. It looks like this only affects iOS though.

@stevelizcano I was able to workaround this by wrapping the touchable in a `View` to which I applied the shadow.

Snack Repro: https://snack.expo.io/@rszalski/4d0c70

Android (works):
![rngh_android_overflow](https://user-images.githubusercontent.com/184806/61446813-15d0e400-a950-11e9-87e6-99d43c202677.jpg)

iOS (broken)
![rngh_ios_overflow](https://user-images.githubusercontent.com/184806/61446825-1bc6c500-a950-11e9-9f42-ab2d6a48ed2e.jpeg)

I also noticed that the `elevation` on Android results in deeper/multiplied shadow when applied to RNGH-equivalent touchables, but this could be moved to a separate issue.

**Comment by ITSjwags** [comment]
Just wondering if there is an idea of a fix or workaround for this? I also am seeing this overflow issue making iOS cut off the shadows, and android making the elevation multiplied. This is using a TouchableWithoutFeedback component where the button shrinks when pressed.

iOS:
![image](https://user-images.githubusercontent.com/4692878/61745285-100f4000-ad4e-11e9-980b-48a5b5a592ba.png)
left button pressed:
![image](https://user-images.githubusercontent.com/4692878/61745464-7a27e500-ad4e-11e9-9be7-7c52dedc5e49.png)


android:
![image](https://user-images.githubusercontent.com/4692878/61745317-21f0e300-ad4e-11e9-96d8-f073af0d75a6.png)
left button pressed
![image](https://user-images.githubusercontent.com/4692878/61745664-e30f5d00-ad4e-11e9-9235-8228ff240ff4.png)

**Comment by masonwolters** [comment]
For anyone stumbling upon this from Google, I fixed this by adding the prop `containerStyle={{ overflow: 'visible' }}` to `TouchableOpacity`.

The offending line is [here](https://github.com/software-mansion/react-native-gesture-handler/blob/27dfec8570b5f2fef9241d972ada51e7233a59d2/GestureButtons.js#L67) in `GestureButtons.js` where it explicitly adds `overflow: 'hidden'` which doesn't seem to be in line with the behavior of RN's default Touchables. But it's probably in there for some other reason, so you can just override it as a workaround.

**Comment by tzs007** [comment]
> For anyone stumbling upon this from Google, I fixed this by adding the prop `containerStyle={{ overflow: 'visible' }}` to `TouchableOpacity`.
> 
> The offending line is [here](https://github.com/software-mansion/react-native-gesture-handler/blob/27dfec8570b5f2fef9241d972ada51e7233a59d2/GestureButtons.js#L67) in `GestureButtons.js` where it explicitly adds `overflow: 'hidden'` which doesn't seem to be in line with the behavior of RN's default Touchables. But it's probably in there for some other reason, so you can just override it as a workaround.

What, if it does'nt work with expo SDK38? I placed overflow visible on TouchableOpacity but nothing happened... Expo is really full of bugs... So annoying...

**Comment by shuman-shen** [comment]
> For anyone stumbling upon this from Google, I fixed this by adding the prop `containerStyle={{ overflow: 'visible' }}` to `TouchableOpacity`.
> 
> The offending line is [here](https://github.com/software-mansion/react-native-gesture-handler/blob/27dfec8570b5f2fef9241d972ada51e7233a59d2/GestureButtons.js#L67) in `GestureButtons.js` where it explicitly adds `overflow: 'hidden'` which doesn't seem to be in line with the behavior of RN's default Touchables. But it's probably in there for some other reason, so you can just override it as a workaround.

Thanks. I'm with SDK 38 and this works!! Just be aware that it's `containerStyle`, not the regular `style` prop that you use for `View`.

**Comment by shuman-shen** [comment]
> > For anyone stumbling upon this from Google, I fixed this by adding the prop `containerStyle={{ overflow: 'visible' }}` to `TouchableOpacity`.
> > The offending line is [here](https://github.com/software-mansion/react-native-gesture-handler/blob/27dfec8570b5f2fef9241d972ada51e7233a59d2/GestureButtons.js#L67) in `GestureButtons.js` where it explicitly adds `overflow: 'hidden'` which doesn't seem to be in line with the behavior of RN's default Touchables. But it's probably in there for some other reason, so you can just override it as a workaround.
> 
> What, if it does'nt work with expo SDK38? I placed overflow visible on TouchableOpacity but nothing happened... Expo is really full of bugs... So annoying...

Did you go with `containerStyle` prop rather than `style` ?

**Comment by cuong1999** [comment]
https://ethercreative.github.io/react-native-shadow-generator/
this link working for me

**Comment by j-piasecki** [comment]
Hi! The offending line setting `overflow` to `hidden` seems to have been removed around the time the library was converted to TypeScript. I just checked on the snack from above and both Android and iOS seem to be working correctly.
