### ISSUE TITLE
[error] package  android.support.v4.util doesn't exist

### ISSUE THREAD

**Issue by M1seRy** [software-mansion/react-native-gesture-handler#678]
## react-native-gesture-handler error
Hi,
I follow the instruction by the react-navigation website : https://reactnavigation.org/docs/en/getting-started.html to add react-navigation:

yarn add react-navigation

yarn add react-native-gesture-handler

react-native link react-native-gesture-handler 

and successfully linked

`       
info Linking "react-native-gesture-handler" iOS dependency  
info iOS module "react-native-gesture-handler" has been successfully linked  
info Linking "react-native-gesture-handler" Android dependency  
info Android module "react-native-gesture-handler" has been successfully linked  
`

and then change the MainActivity.java like the docs it asks.

everything runs fine before adding navigation.

Then run react-native run-android emulator, and error pop up :

`
xxxx/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerEvent.java:3: error: package  android.support.v4.util doesn't exist
import android.support.v4.util.Pools;
                              ^
xxxx/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerEvent.java:19: error: package Pools doesn't exist
private static final Pools.SynchronizedPool<RNGestureHandlerEvent> EVENTS_POOL =
                            ^
`

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  ^3.11.0
| react-native     | 0.60.0
| node             | v10.14.1
| npm or yarn      | npm 6.4.1 yarn 1.16.0
| react-native-gesture-handler | ^1.3.0

I try to solve this by search in issues and stackoverflow, but non of them is working for me.
Any advice or help is needed . Thx.

**Comment by viru99** [comment]
Try : 
1. npm install --save-dev jetifier
2. npx jetify

**Comment by M1seRy** [comment]
@viru99 Hi, Thx, I have try it with jetifier, another error pop up:

`null is not an object (evaluating 'rngesturehandlermodule.default.createGestureHandler')` 

[IMG RNGestHandlerModule null error =>](https://i.loli.net/2019/07/10/5d25996d4655e23135.png)

Any solutions?

**Comment by viru99** [comment]
Try to stop Metro Bundler server and restart it react-native start
2.react-native link react-native-gesture-handler

**Comment by localnet** [comment]
@M1seRy Try the workaround for AndroidX: https://github.com/kmagiera/react-native-gesture-handler/issues/670#issuecomment-508745800

**Comment by M1seRy** [comment]
@localnet thx, I tried to click the file : node_module - react-native-gesture-handler then Refactor - Migrate to AndriodX. And rebuild but same error [error img] (https://i.loli.net/2019/07/10/5d25996d4655e23135.png) 

Still no solutions, I think Maybe I should switch RN version to under 0.60.

**Comment by localnet** [comment]
@M1seRy Sorry, I have few experience with React Native and none with Java. Only I can say it worked for me, using react-native@0.60.0

**Comment by Jayxiang** [comment]
I didn't solve it by using jetifier, but I encountered new problems.

**Comment by jdnichollsc** [comment]
Because we need to Add gradle backward-compatibility, check details here => https://github.com/kmagiera/react-native-gesture-handler/issues/743

**Comment by httol** [comment]
https://github.com/mikehardy/jetifier
>Call npx jetify run in the postinstall target of your package.json (Any time your dependencies update you have to jetify again)

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
If you need further help please reply.
