### ISSUE TITLE
componentWillUpdate is deprecated 

### ISSUE THREAD

**Issue by YajanaRao** [software-mansion/react-native-gesture-handler#683]
Getting warning in component Swipeable  `componentWillUpdate is deprecated` with react native version 0.60

**Comment by Fajrynk** [comment]
same issue

**Comment by rochapablo** [comment]
```
Warning: componentWillUpdate is deprecated and will be removed in the next major version. Use componentDidUpdate instead. As a temporary workaround, you can rename to UNSAFE_componentWillUpdate.
    
    Please update the following components: DrawerLayout
    
    Learn more about this warning here:
    https://fb.me/react-async-component-lifecycle-hooks
```

```
"react": "16.8.6",
"react-native": "0.60.3",
"react-native-progress": "^3.6.0",
```

**Comment by VenancioAvila** [comment]
same issue

**Comment by Bruno-Furtado** [comment]
+1

**Comment by AdrianoRicardo** [comment]
+1

**Comment by Gomechatronics** [comment]
+1

**Comment by dsznajder** [comment]
componentWillUpdate Is updated on master, you have to wait for next release :)

**Comment by honter36** [comment]
+1

**Comment by K0rdan** [comment]
> componentWillUpdate Is updated on master, you have to wait for next release :)

Actually, it will not rise the warning thanks to : `UNSAFE_componentWillUpdate`. It's more like a workaround than an update.
Better than nothing, we'll have to wait the following release :)

**Comment by dsznajder** [comment]
@K0rdan Sure. Look #655

**Comment by AdrianoRicardo** [comment]
Any news?

**Comment by Ovi** [comment]
+1

**Comment by cristianoccazinsp** [comment]
+1

**Comment by eddskt** [comment]
+1

**Comment by deyanmakedonski** [comment]
waiting the update

**Comment by Piero87** [comment]
same here waiting the update, thanks

**Comment by jonathanmachado** [comment]
Hi when it's new release ? thanks

**Comment by janpe** [comment]
Hoping to see a fix for this as well.

**Comment by Monstrik** [comment]
waiting the update

**Comment by Zloka** [comment]
Waiting for an update on this as well.

**Comment by butri71** [comment]
Any news on this? I'm still getting the warning message.

**Comment by jakub-gonet** [comment]
Fixed on master.
