### ISSUE TITLE
Swipeable is kinda not smooth and lags on opening in Android.

### ISSUE THREAD

**Issue by Ashkan-Oliaie** [software-mansion/react-native-gesture-handler#695]
just like https://github.com/react-navigation/react-navigation/issues/5287

I believe the component swipeable is not smooth due to using Animated from react-native,
is it possible to reproduce it using Animated from react-native-reanimated ?

**Comment by EtienneBourque** [comment]
To add to your reference to the drawer, there is a version with reanimated here: [react-navigation/drawer](https://github.com/react-navigation/drawer)

It would be nice to have Swipeable with reanimated as well.

**Comment by Piero87** [comment]
any news about this? i'm interested too

**Comment by osamaq** [comment]
I was also having sluggish drawer on Android with react-navigation 3 & 4 + RN 0.60.5 as shown [here.](https://github.com/react-navigation/react-navigation/issues/5287#issuecomment-442409232)

I ended up using [DrawerLayoutAndroid](https://facebook.github.io/react-native/docs/drawerlayoutandroid) which is super smooth. I went with a custom navigator for it. 


```jsx
import React, { Component } from "react";
import { createStackNavigator } from "react-navigation";
import { DrawerLayoutAndroid, Platform } from "react-native";
import DrawerContent from "../components/DrawerContent";
import Header from "../components/Header";
import LandingScreen from "../screens/Landing/LandingScreen";

const MainStack = createStackNavigator(
  {
    LandingScreen
  },
  {
    defaultNavigationOptions: {
      header: Header
    }
  }
);

export default class CustomDrawerNavigatorAndroid extends Component {
  static router = MainStack.router;

  render() {
    const { navigation }: any = this.props;
    return Platform.OS === "android" ? (
      <DrawerLayoutAndroid
        drawerWidth={300}
        drawerPosition={DrawerLayoutAndroid.positions.Left}
        renderNavigationView={() => DrawerContent()}
      >
        <MainStack navigation={navigation}></MainStack>
      </DrawerLayoutAndroid>
    ) : (
       // Insert stack for iOS with react-navigation drawer navigator.
    );
  }
}
```

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
If you need further help please reply.
