### ISSUE TITLE
RectButton onPress does not work

### ISSUE THREAD

**Issue by mfgabriel92** [software-mansion/react-native-gesture-handler#699]
Hi,

`RectButton`'s `onPress` doesn't work. I'm using React Native 0.60.4 inside of a Styled Component:

```javascript
export const Hour = styled(RectButton)`
  background: #fff;
  padding: 20px;
  flex: 1;
  opacity: ${props => (props.enabled ? 1 : 0.7)};
  align-items: center;
  margin: 0 10px 20px;
`
```

I've tried running `jestify`, a manual React Native link despite the recommendations, cleaning cache but nothing works. It decided not to work for NOTHING.

**Comment by thecodecafe** [comment]
The same issue I'm facing, were you able to fix this?

**Comment by 4yki** [comment]
Make sure you followed this step:

**Comment by 4yki** [comment]
![Screen Shot 2019-08-08 at 12 35 48 PM](https://user-images.githubusercontent.com/41107034/62692456-5e247480-b9d9-11e9-9c23-1f9ab308cf08.png)
Make sure you followed this insctructions

**Comment by hladf** [comment]
> ...
> Make sure you followed this insctructions

Dont worked here :(

**Comment by hladf** [comment]
![image](https://user-images.githubusercontent.com/19738608/64259213-0c4f0b80-ceff-11e9-9364-32a4de579220.png)
Resolved for me. In my case, I forgot to pass spreading props...

**Comment by hladf** [comment]
The same problem happens again...
Clean cache and run `react-native run-android` again fix the problem.

**Comment by thalesrbs** [comment]
> ![image](https://user-images.githubusercontent.com/19738608/64259213-0c4f0b80-ceff-11e9-9364-32a4de579220.png)
> Resolved for me. In my case, I forgot to pass spreading props...
Diego`s code! Rocketseat...rs
I also copied them

**Comment by Bimpong** [comment]
> ![Screen Shot 2019-08-08 at 12 35 48 PM](https://user-images.githubusercontent.com/41107034/62692456-5e247480-b9d9-11e9-9c23-1f9ab308cf08.png)
> Make sure you followed this insctructions

I'm on react-native 0.60.5 and this worked flawlessly. cheers mate.
P.S next time dont use a picture :(

**Comment by fellypsantos** [comment]
> > ![Screen Shot 2019-08-08 at 12 35 48 PM](https://user-images.githubusercontent.com/41107034/62692456-5e247480-b9d9-11e9-9c23-1f9ab308cf08.png)
> > Make sure you followed this insctructions
> 
> I'm on react-native 0.60.5 and this worked flawlessly. cheers mate.
> P.S next time dont use a picture :(

Documentation and codes in this picture.
[https://kmagiera.github.io/react-native-gesture-handler/docs/getting-started.html](url)

fortunately its working.

**Comment by trsp400** [comment]
> ![Screen Shot 2019-08-08 at 12 35 48 PM](https://user-images.githubusercontent.com/41107034/62692456-5e247480-b9d9-11e9-9c23-1f9ab308cf08.png)
> Make sure you followed this insctructions

Thank you, its working now!!
That's what we got when do not read the docs rsrsrs

**Comment by EhsanSarshar** [comment]
for me onPress trigger but ripple effect sometimes and most of the time not working. an strange behaviour

**Comment by adblanc** [comment]
> for me onPress trigger but ripple effect sometimes and most of the time not working. an strange behaviour

I have the exact same problem and I'm loosing my mind, did you ever found something ?

**Comment by jakub-gonet** [comment]
@adblanc, please don't comment on closed issues, those reports are easily missed. You can create a new issue with repro, we'll try to figure this out 😄

**Comment by lincolnBerlick** [comment]
> ![Screen Shot 2019-08-08 at 12 35 48 PM](https://user-images.githubusercontent.com/41107034/62692456-5e247480-b9d9-11e9-9c23-1f9ab308cf08.png)
> Make sure you followed this insctructions

just add  on your MainActivity.java

at the imports
`import com.facebook.react.ReactActivityDelegate;
import com.facebook. react.ReactRootView;
import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;`

and at the final 

```
  @Override
  protected ReactActivityDelegate createReactActivityDelegate() {
    return new ReactActivityDelegate(this, getMainComponentName ()) {
    @Override
    protected ReactRootView createRootView() {
    return new RNGestureHandlerEnabledRootView (MainActivity. this);
      }
    };
  }
```


 it'll look like this




`
import android.os.Bundle;
import com.facebook.react.ReactActivity;

import com.facebook.react.ReactActivityDelegate;
import com.facebook. react.ReactRootView;
import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;

public class MainActivity extends ReactActivity {
  @Override
  protected String getMainComponentName() {
    return "applicationName";
  }

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(null);
  }

  @Override
  protected ReactActivityDelegate createReactActivityDelegate() {
    return new ReactActivityDelegate(this, getMainComponentName ()) {
    @Override
    protected ReactRootView createRootView() {
    return new RNGestureHandlerEnabledRootView (MainActivity. this);
      }
    };
  }
}
`

**Comment by pedromesmer** [comment]
thanks @lincolnBerlick, this solution worked for me

**Comment by KJA-Tsx** [comment]
Hello, I am using react-native-gesture-handler version **"~2.1.0"** , I tried the above solution but then I get this new error: Possible Unhandled Promise Rejection (id: 0):Error: No native splash screen registered for provided activity. Please configure your application's main Activity to call 'SplashScreen.show' (https://github.com/expo/expo/tree/master/packages/expo-splash-screen#-configure-android). Any help?

**Comment by KJA-Tsx** [comment]
> Hello, I am using react-native-gesture-handler version **"~2.1.0"** , I tried the above solution and it works fine, but then I get this new error: Possible Unhandled Promise Rejection (id: 0):Error: No native splash screen registered for provided activity. Please configure your application's main Activity to call 'SplashScreen.show' (https://github.com/expo/expo/tree/master/packages/expo-splash-screen#-configure-android). Any help?
> 
> This what I had before :
> 
> @OverRide protected ReactActivityDelegate createReactActivityDelegate() { return new ReactActivityDelegateWrapper(this, new ReactActivityDelegate(this, getMainComponentName()) ); }
> 
> Added this as stated above :
> 
> @OverRide protected ReactActivityDelegate createReactActivityDelegate() { return new ReactActivityDelegate(this, getMainComponentName ()) { @OverRide protected ReactRootView createRootView() { return new RNGestureHandlerEnabledRootView (MainActivity.this); } }; }

Any one who has same problem with this just add this line to the onCreate function:
 SplashScreen.show(this, SplashScreenImageResizeMode.CONTAIN, ReactRootView.class, false);

**Comment by xyeres** [comment]
Be sure to [follow complete setup steps](https://docs.swmansion.com/react-native-gesture-handler/docs/next/installation#js)  for react-native-gesture-handler, including wrapping your root component in <GestureHandlerRootView>

**Comment by HenriqueVazquez** [comment]
![image](https://user-images.githubusercontent.com/14090441/171750687-f58a9baa-6c5c-4f28-910d-81c82b4cae31.png)

you need adjust of this way, involving with GestureHandlerRootView

**Comment by johntravolta1** [comment]
Involving with GestureHandlerRootView solved this issue for me
