### ISSUE TITLE
TypeError: Cannot add property resume, object is not extensible

### ISSUE THREAD

**Issue by allendol** [software-mansion/react-native-gesture-handler#704]
I am using the following code in react. It is working on other project but on this project I am getting the "TypeError: Cannot add property resume, object is not extensible" error on ref={(r) => this.resume = r}>

                    <PDFExport paperSize={'Letter'}
                        ref={(r) => this.resume = r}>
Any idea?

**Comment by jakub-gonet** [comment]
Hi @allendol,
I'm sorry this issue went unnoticed.

Do you still face this problem?

**Comment by allendol** [comment]
No, this is resolved.

**Comment by jakub-gonet** [comment]
Cool, it would be appreciated if you could shortly describe the solution

**Comment by allendol** [comment]
This was posted long time ago and I don't remember if the problem was coming from somewhere else but I know the following is working now:
<PDFExport paperSize={'Letter'} landscape={'true'} scale={.5}
ref={(r) => this.resume = r}>

**Comment by jakub-gonet** [comment]
Understandable, thanks anyway
