### ISSUE TITLE
onPress not function in any button

### ISSUE THREAD

**Issue by callmejm** [software-mansion/react-native-gesture-handler#705]
I try to use `ReactButton` or `BaseButton` ,but `onPress` nothing response , i have no idea why
 
    <RectButton style={styles.circlebtn} rippleColor={Color.rippleblueColor} onPress={()=> console.log("Create")}>
              <View accessible accessibilityRole="button">
                <Text style={styles.circlebtntt}>CREATE</Text>
              </View>
            </RectButton>

`react-native:0.59.10`
`react-native-gesture-handler:1.30`

**Comment by thecodecafe** [comment]
I'm getting the exact behaviour @callmejm were you able to figure this out?

**Comment by callmejm** [comment]
@thecodecafe sorry, i totally no idea ? I'm new using this library, but now i think i should use back `TouchableOpacity` from `react-native`

**Comment by yolpsoftware** [comment]
Did you find out anything?

**Comment by belgamo** [comment]
I'm getting the same behavior... with `TouchableOpacity` work fine.

**Comment by jakub-gonet** [comment]
This is common behavior on android when you don't replace RootView with RNGH RootVIew, [more info here](https://docs.swmansion.com/react-native-gesture-handler/docs/#android).

If you need further help, don't hesitate to ask.
