### ISSUE TITLE
Documentation for RotationGestureHandler says you can access focalX and focalY when really its anchorX and anchorY

### ISSUE THREAD

**Issue by damiansf** [software-mansion/react-native-gesture-handler#706]
~~Hello, I've been attempting to write an app which has an image that you can zoom in on, rotate and pan. Adjusting zooming to be around the focal point was fairly easy, however, while writing the logic for adjusting the image during rotation (to allow rotating around the focal point) I noticed that the focalX and focalY values returned by the rotation handler are always 0. To confirm this i printed the values via a call() method in the handlers. for rotation, I always saw 0 yet for zooming i saw correct values.~~

Turns out the documentation is just wrong for the RotationGestureHandler, after poking around the code, to access the focal points for rotation you access anchorX and anchorY rather than focalX and focalY. Will make a pr to fix this

**Comment by wcandillon** [comment]
Woah thank you @damiansf. You saved me a lot of time :)
