### ISSUE TITLE
LongPressGestureHandler is getting ended even finger is not lifted. 

### ISSUE THREAD

**Issue by iksheth** [software-mansion/react-native-gesture-handler#709]
Hi I am trying to fire another event when LongPressGesture event is in active state. But Once it is active even without lifting finger it is ENDING event. what to do ? is there any flags I can set ?

**Comment by Taylor123** [comment]
@iksheth Did you find a solution to this? I'm experiencing the same issue as well as drag coordinates that look like misfires from the LongPressGestureHandler

**Comment by iksheth** [comment]
Nop Not yet.

**Comment by Taylor123** [comment]
@iksheth I've tried a bunch of different things and think that it actually has nothing to do with the implementation of `LongPressGestureHandler`. If I remove all of my logic except for something like the following, then the state events seem to work perfectly:
```
useCode(() => [
    debug('state', dragState)
  ]
)
```

I've even been able to add a conditional `call` statement when the state is ACTIVE and it works fine. However, it starts having really odd behavior when i have a `call` statement in the else of the conditional that causes a render (i.e. set state)

```
 useCode(
    () => [
        debug('state', dragState),
        cond(
          eq(dragState, State.ACTIVE),
          [
            call([dragX], ([x]) => {
              // do something with x
            }),
          ],
          call([dragX, dragState], ([x, state]) => {
            // firing a set state here causes odd behavior
            setState(null);
          }),
        ),
      ],
  );
```

**Comment by Taylor123** [comment]
Solved my issue, i did not have a deps array on the `useCode` hook : /

surprised that eslint wasn't throwing any errors for me

Maybe yours is the same?

**Comment by iksheth** [comment]
@Taylor123 Thanks for the solution
