### ISSUE TITLE
onPress, onPressIn, onPressOut don't work in web

### ISSUE THREAD

**Issue by chrisdrackett** [software-mansion/react-native-gesture-handler#710]
I'm trying to use `TouchableWithoutFeedback` within a web project and I'm running into issues.

I have the following code:

```js
<ScrollView>
      <TouchableWithoutFeedback
        onPress={() => {
          alert('press!')
        }}
      >
        <View><Text>Foo</Text></View>
      </TouchableWithoutFeedback>
      <RectButton
        onPress={() => {
          alert('press!')
        }}
      >
        <Text>Foo</Text>
      </RectButton>
</ScrollView>
```

when I click (in chrome) on the `TouchableWithoutFeedback` text nothing happens. The `RectButton` works as expected and alerts `press!`. I'm wondering if I'm missing something basic?

if I import `TouchableWithoutFeedback` from `react-native` (really `react-native-web`) it works as expected as well.

**Comment by nandorojo** [comment]
`onPressIn` works for me, but `onPressOut` does not.

**Comment by nandorojo** [comment]
In case it helps, here's what I did:

**Touch.js**

```es6
<TouchableWithoutFeedback 
    onPressOut={props.onPressOut}
    onPressIn={props.onPressIn}
>
   <View><Text>Foo</Text></View>
</TouchableWithoutFeedback>
```

**Touch.web.js**

```es6
 <div
    onMouseDown={props.onPressIn}
    onMouseUp={props.onPressOut}
    onTouchStart={props.onPressIn}
    onTouchEnd={props.onPressOut}
  />
```

...and in another file

```es6
import Touch from './path/to/Touch' // make sure it doesn't say .web here

return <Touch onPressIn={() => console.log('hi')} onPressOut={() => console.log('bye')} />

```

**Comment by chrisdrackett** [comment]
@nandorojo yeah, we're doing something similar but ideally it would work here without a hack :)

**Comment by RWOverdijk** [comment]
Is this still the way to go about doing this? I assumed onPressIn was the same as onMouseDown and onTouchStart
