### ISSUE TITLE
Add exclusive/disallowInterruption prop for BaseGestureHandler

### ISSUE THREAD

**Issue by ShaMan123** [software-mansion/react-native-gesture-handler#712]
I suggest adding `exclusive` prop for `BaseGestureHandler` that should behave as in [`BaseButton#exclusive`](https://kmagiera.github.io/react-native-gesture-handler/docs/component-buttons.html#exclusive-ios-only)
This will complete `waitFor` and allow easier configuration of cross handler interactions.
To achieve this now AFAIK you need to change `enabled` prop on all the handlers in question.

**Comment by j-piasecki** [comment]
We're not planning to implement something like this at the moment. If that's still affecting you, please open a new issue with a description of a concrete use case where this is an issue.
