### ISSUE TITLE
Apple Pencil Support

### ISSUE THREAD

**Issue by robertherber** [software-mansion/react-native-gesture-handler#713]
It would be great if support was added for Apple Pencil. I imagine basic support could be easily added through just reporting back the [UITouch.TouchType](https://developer.apple.com/documentation/uikit/uitouch/touchtype) of the touch. This would allow for discerning between finger and pencil touches (and so trigger separate actions).

**Comment by wcandillon** [comment]
In React Native Skia, we are encouraging people to use gesture-handler whenever possible. With a Skia Canvas, knowing the touch type information seems to be quite relevant.

**Comment by laffan** [comment]
Adding my support for this feature.  Knowing whether the touch is a finger or stylus would be immediately valuable to several of my projects.

**Comment by rksangani** [comment]
@laffan have you added the support for apple pencil?

**Comment by m-bert** [comment]
Hi @robertherber! I know it's been a while, but the time has come! Support for stylus and `pointerType` has been recently added.

You can find it in these PRs:

- https://github.com/software-mansion/react-native-gesture-handler/pull/3113
- https://github.com/software-mansion/react-native-gesture-handler/pull/3111 
- https://github.com/software-mansion/react-native-gesture-handler/pull/3107
- https://github.com/software-mansion/react-native-gesture-handler/pull/2760

And read about it in docs:

- [stylusData](https://docs.swmansion.com/react-native-gesture-handler/docs/gestures/pan-gesture#stylusdata)
- [pointerType](https://docs.swmansion.com/react-native-gesture-handler/docs/gestures/pan-gesture#pointertype)

**Comment by robertherber** [comment]
Amazing news! Although I don't have a use case for it right now I'm looking forward to the opportunity to try this out, truly an enabling feature! 🙂👍

**Comment by NiuGuohui** [comment]
@m-bert Why is `stylusData` only present in pan and hover events? When clicking with a pencil, no more data can be obtained.

**Comment by m-bert** [comment]
Hi @NiuGuohui! We've decided that `Pan` and `Hover` would benefit the most from this change. Could you share with us a use-case where you use different handler?

**Comment by NiuGuohui** [comment]
> Hi @NiuGuohui! We've decided that `Pan` and `Hover` would benefit the most from this change. Could you share with us a use-case where you use different handler?

I have a scenario here: I am implementing a drawing program where only a pencil can be used for drawing. However, if the user only clicks with the pen (expecting to draw a point), we cannot receive pen data because the Pan event cannot be triggered.

**Comment by m-bert** [comment]
@NiuGuohui Okay, i see. I think that setting `minDistance` to `0` will help. Could you check that?

**Comment by NiuGuohui** [comment]
> @NiuGuohui Okay, i see. I think that setting `minDistance` to `0` will help. Could you check that?

Thank you very much!This method really works effectively!

**Comment by agathe** [comment]
In addition to the stylus data that we get in Pan and Hover events, is there a way to get the stylus button press data during those gestures (pad gesture while the stylus button is pressed)? 
I see that the stylus button information is used in parts of the code base, but is it exposed in some fashion through the API?

**Comment by m-bert** [comment]
HI @agathe! As far as I can see, stylus button is used only in `ScaleGestureDetector` on `android` so currently there's no way to access this information. 

I'll look into it :)
