### ISSUE TITLE
compile for use in web? update docs around web usage?

### ISSUE THREAD

**Issue by chrisdrackett** [software-mansion/react-native-gesture-handler#717]
Right now I can use this package in expo and get web support, but if I try and use it outside expo (storybook in my case) I ran into issues. I eventually found I need to add the following to Webpack to get things both compiled and working correctly:

```
  config.resolve.extensions = [
    '.web.ts',
    '.web.tsx',
    '.web.js',
    '.web.jsx',
    '.ts',
    '.tsx',
    '.js',
    '.json',
  ]

  config.module.rules.push({
    test: /\.jsx?$/,
    loader: 'babel-loader',

    include: [
      path.resolve(
        __dirname,
        '../node_modules/react-native-gesture-handler',
      ),
    ],
    options: {
      babelrc: false,
      plugins: ['react-native-web'],
      presets: ['module:metro-react-native-babel-preset'],
    },
  })
```

I wonder if there is a way to make the above not needed? if not, maybe the above needs to be added to a section in the docs around web usage?

**Comment by EvanBacon** [comment]
[web-packaging-for-existing-react-native-apps](https://github.com/necolas/react-native-web/blob/f7e6b43422aeab9ee0698a64c6265773dc6b9a31/docs/guides/multi-platform-apps.md#web-packaging-for-existing-react-native-apps)

> Packaging web apps is subtly different to packaging React Native apps and is complicated by the need to tree-shake and code-split non-trivial apps.

`@expo/webpack-config` is intended only for running `react-native-web` apps while considering all of the complex inner-workings of the library.
