### ISSUE TITLE
LongPressGestureHandler maxDist doesn't work

### ISSUE THREAD

**Issue by soqt** [software-mansion/react-native-gesture-handler#719]
```js
<LongPressGestureHandler
      ref={ref}
      onGestureEvent={handleLongPressGestureEvent}
      onHandlerStateChange={onLongPressHandlerStateChange}
      maxDist={1}
    >
<View />
</LongPressGestureHandler>
```
since I set maxDist to 1, gesture should be cancelled or failed if I long-pressing and move figure a little bit. However, handler state is always ACTIVE, and END when I uplift figure no matter how far my figure traveled.
This problem happens on iOS, but tested on Android yet.

**Comment by j-piasecki** [comment]
Hi! The problem you have described was happening only on iOS and should be resolved by https://github.com/software-mansion/react-native-gesture-handler/pull/1610.
