### ISSUE TITLE
The Bizarre Situation of Android Model

### ISSUE THREAD

**Issue by afeichuanqi** [software-mansion/react-native-gesture-handler#720]
This plug-in will be smooth as long as it is in debug JS remotely mode. However, as long as the debug JS remotely mode is not activated in the official version, the sliding delay is 3 seconds. On Android. Excuse me, how did it happen?

**Comment by afeichuanqi** [comment]
"react": "^16.8.6",
"react-native": "^0.59.9",
"react-native-gesture-handler": "^1.3.0",

**Comment by afeichuanqi** [comment]
"react-navigation": "^3.11.1",

**Comment by antontanderup** [comment]
Are you using Hermes? This causes slowness while on dev build and not debugging for me. All over, not just for react-native-gesture-handler.

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
If you need further help please reply.
