### ISSUE TITLE
Typescript definitions file missing LongPressGestureHandlerGestureEvent

### ISSUE THREAD

**Issue by soqt** [software-mansion/react-native-gesture-handler#723]
According to [LongPressGestureHandlerProperties ](https://github.com/kmagiera/react-native-gesture-handler/blob/master/react-native-gesture-handler.d.ts#L281). onGestureEvent has an GestureHandlerGestureEvent type. But `long press onGestureEvent` should has a `absoluteX` and `absoluteY` field. LongPressGestureHandlerGestureEvent should be implemented

**Comment by lafiosca** [comment]
I have created PR #860 to address this issue, which I also experienced.
