### ISSUE TITLE
error: package com.swmansion.gesturehandler.react does not exist

### ISSUE THREAD

**Issue by manjupriyajaintm** [software-mansion/react-native-gesture-handler#726]
Task :app:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings
43 actionable tasks: 2 executed, 41 up-to-date
D:\ddma\android\app\src\main\java\com\ddma\MainActivity.java:6: error: package com.swmansion.gesturehandler.react does not exist
import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;
                                         ^
D:\ddma\android\app\src\main\java\com\ddma\MainActivity.java:24: error: cannot find symbol
       return new RNGestureHandlerEnabledRootView(MainActivity.this);
                  ^
  symbol: class RNGestureHandlerEnabledRootView
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
D:\ddma\android\app\src\main\java\com\ddma\MainActivity.java:6: error: package com.swmansion.gesturehandler.react does not exist
import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;
                                         ^
D:\ddma\android\app\src\main\java\com\ddma\MainActivity.java:24: error: cannot find symbol
       return new RNGestureHandlerEnabledRootView(MainActivity.this);
                  ^
  symbol: class RNGestureHandlerEnabledRootView
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

    at checkExecSyncError (child_process.js:616:11)
    at execFileSync (child_process.js:634:15)
    at runOnAllDevices (D:\ddma\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:74:39)
    at buildAndRun (D:\ddma\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:158:41)
    at D:\ddma\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:125:12
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Command.handleAction (D:\ddma\node_modules\react-native\node_modules\@react-native-community\cli\build\cliEntry.js:160:7)

**Comment by tangtai** [comment]
@manjupriyajaintm i have the same problem did you get the error when using rn >= 0.60 ? did you manage to find any solutions.

**Comment by raajnadar** [comment]
Same problem did you find any fix. I tried in react native 0.61

**Comment by ashwingattani** [comment]
@kmagiera any update on this?

**Comment by raajnadar** [comment]
Forgot to update  the thing that worked for me.

I updated my react native cli to latest alpha and followed the steps in this guide http://facebook.github.io/react-native/docs/navigation

`yarn add react-navigation react-native-gesture-handler react-navigation-stack`

Configure your router and `react-native run-android`

The autolinking worked in android (No extra setup needed in java files).

**Comment by Arjorie** [comment]
I've encountered the same issue. 
This is caused by a new update I guess. 

To save you some time, downgrade your` react-native-gesture-handler` to `~1.5.0`

Don't forget to link if you are running react-native-cli <0.59

**Comment by o-pooja-o** [comment]
> @manjupriyajaintm i have the same problem did you get the error when using rn >= 0.60 ? did you manage to find any solutions.

Can't see any solution from here. Did you find the solution?

**Comment by raajnadar** [comment]
Cd in to `android` folder run `./gradlew clean` or `gradlew clean` according to your OS. Now run `yarn react-native run-android`

If that did not work remove `yarn.lock` and `node_modules` and run `yarn`

**Comment by kmagiera** [comment]
I believe this issue is related to your project's setup. I'd be happy to help but first need you to try the following:
1. Crate a fresh project, install navigation and gesture-handler library, see if the project builds correctly. If it fails with the same error, I'd be happy to help investigate. Please publish the sample repo you created and link it here
2. If the above builds corrrectly it means it is likely a problem of your project's setup. Please compare it to the sample project configuration and try to figure out what might be causing the build issue for you.

**Comment by manjupriyajaintm** [comment]
I'm Closing this issue.
