### ISSUE TITLE
RotationGestureHandler triggering onHandlerStateChange twice for END state

### ISSUE THREAD

**Issue by damiansf** [software-mansion/react-native-gesture-handler#727]
I have worked around this issue but thought it was worth mentioning.

I noticed this happening in an app I created with a panGestureHandler and a rotationGestureHandler that were simultaneous.

Occasionally, the code to handle onHandlerStateChange for the rotation handler was getting called twice, back to back, when the state was being changed from ACTIVE to END. So essentially the gesture handler was changing its state to END twice (I'm assuming). Due to this, some math I was doing in my handler on state.END was occurring twice, messing up my animated values (worked around it eventually but this seems like a bug to me).

Please let me know if I can provide any more information, or if this is the intended behavior.

**Comment by WoLewicki** [comment]
Is this issue still present in the newest version with the new API provided? I believe it could be resolved since `onHandlerStateChange` is handled differently now. If so, could you provide a full reproduction of the problem in a form of a snack or simple repo?
