### ISSUE TITLE
TouchableWithoutFeedback 0.60.5 onPress, onPressIn, onPressOut not firing

### ISSUE THREAD

**Issue by EmperorEarth** [software-mansion/react-native-gesture-handler#729]
I know RN 0.60.x support isn't live yet but I didn't see any commits addressing this.

It was a fresh-ish repo (react-native init + copy over old code that was working on RN 0.59.10) on Windows + Android.

I'll test the extent of this issue when I get the chance.

**Comment by hsource** [comment]
I'm also facing this issue! Have you managed to find a workaround?

**Comment by hsource** [comment]
Actually, in general, TouchableWithoutFeedback seems to work on 0.60.5. It only doesn't work in a modal, per your issue #731. I think this issue can be closed

**Comment by EmperorEarth** [comment]
hmm, it didn't seem to work outside of a modal for me

i'll try to localize the relevant factors

**Comment by virgil9306** [comment]
I'm not using in a modal either and facing the same issue.

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
If you need further help please reply.
