### ISSUE TITLE
State.BEGAN on PanGestureHandler behave differently on Android and iOS

### ISSUE THREAD

**Issue by jonathanatn** [software-mansion/react-native-gesture-handler#732]
State.BEGAN fire on a simple touche and State.ACTIVE fire when we start to drag on Android
but on iOS it's different State.BEGAN fire when we start to drag and State.ACTIVE follow.

It become obvious when you use minDist with a big number on the PanGestureHandler.

State.BEGAN will fire on touch on Android
State.BEGAN will fire after the minDist on iOS

BTW if someone as a hack, let me know

**Comment by gabrielchong1994** [comment]
Possibly related to this  #223 

Facing a similar issue where I've a TapGestureHandler nested inside PanGestureHandler. 

For iOS, PanGestureHander only began when finger moves on the screen. As for Android, State.BEGAN event of PanGestureHandler fires immediately when finger is pressed on the screen (without moving) which is not desirable for my use case. 

Things I've tried:
1. **Setting minDist**: PanGestureHandler still began even if my finger travel distance is lower than the minDist.
2. **waitFor**: create a tapRef with React.createRef() and have the PanGestureHandler waitFor tapRef.

Does anyone have a workaround for the PanGestureHandler in Android to work like the behaviour in iOS for this particular case? Thanks in advance

**Comment by szc602639921** [comment]
I have the same problem. When I nested PanGestureHandler within Tap GestureHandler. The problem is exactly what @jonathanatn has said. The 'Begin' State fires only when you move the finger on IOS.  Otherwise, it will fire on touch on Android.

**Comment by szc602639921** [comment]
The component is just like the following code:    
<Animated.View>
      <TapGestureHandler
        ref={Tap}
        simultaneousHandlers={imagePan}
        onHandlerStateChange={({ nativeEvent }) => {
          stateLongPress.setValue(nativeEvent.state);
          oldStateLongPress.setValue(nativeEvent.oldState);
        }}
        maxDist={20}
        maxDurationMs={500}
      >
        <Animated.View>
          <PanGestureHandler
            ref={imagePan}
            simultaneousHandlers={Tap}
            onGestureEvent={onGestureEventHandler}
            onHandlerStateChange={onHandlerStateChangeHandler}
          >

            <Animated.Image
             ........
            />
          </PanGestureHandler>
        </Animated.View>
      </TapGestureHandler>
    </Animated.View>

**Comment by drewandre** [comment]
I'm seeing the same issue. I'm unable to add a double tap to zoom on android to my photo-zoom component because of this.

**Comment by albran** [comment]
I have a workaround that involves manually checking translation values on State.END:
```
const onPanHandlerStateChange = (event) => {
  if (event.nativeEvent.state === State.END) {
    const { translationX, translationY } = event.nativeEvent;
    const minPanVal = 20;
    const belowPanThreshold =
      Math.abs(translationX) < minPanVal &&
      Math.abs(translationY) < minPanVal;
    if (belowPanThreshold) return;
    //do gesture logic...
    }
  };
```
Works for doing logic after a completed gesture but may not work if you need logic to execute mid-gesture...

**Comment by j-piasecki** [comment]
Hi, we made `PanGestureHandler` to follow the same state-flow on iOS as it does on Android in https://github.com/software-mansion/react-native-gesture-handler/pull/1611.
