### ISSUE TITLE
Swipeable not working on Android from Modal

### ISSUE THREAD

**Issue by JeremyBradshaw7** [software-mansion/react-native-gesture-handler#737]
Swipeable is not working on Android when used inside a Modal (as provided by react-native-modal), unless I set `coverScreen={false}` on the Modal but that upsets its positioning in some cases. 

I'm on RN 0.59.10 and RNGH 1.3.0 (have also tried 1.4.0).

I think this is the same issue as #139, but I'm not sure.

**Comment by yelkamel** [comment]
Same for me if someone have any idea

**Comment by cspicuzza** [comment]
No RNGH Touchables are working for me inside a modal on Android.  RN Touchables do work though

```
react-native 0.61.5
react-native-modal 11.5.3
react-native-gesture-handler 1.5.3
```

**Comment by oferRounds** [comment]
Did anyone find a solution?

**Comment by djhr** [comment]
having same issue with `PanGestureHandler` on android when inside a modal provided by react-native

**Comment by jakub-gonet** [comment]
Duplicate of #139.
