### ISSUE TITLE
How to render colors based on swipeable component's dragX property?

### ISSUE THREAD

**Issue by bahtiyara** [software-mansion/react-native-gesture-handler#739]
I want to do something like this:

```javascript
const RightOption = (progress, dragX) => {
    const color = dragX.interpolate({
        inputRange: [-100, 0],
        outputRange: ["#fff", "#000"]
    });

    return <AnimatedIcon style={{color}} name="delete" />
}
const AnimatedIcon = Animated.createAnimatedComponent(Icon);
```

Is there any support for this ?

**Comment by charles-goode** [comment]
You will need to use a [`color` node](https://github.com/kmagiera/react-native-reanimated#color) from Reanimated. You need to pass in three integer valued nodes for each of RGB; the docs say to you may use a `round` node to get integer valued nodes. Try this out:
`outputRange: [0xFFFFFF, 0x000000]`
then make the following nodes:
`const blue = modulo(color, new Value(0x100))`
`const green = sub(modulo(color, new Value(0x10000)), blue)`
`const red = sub(color, green)`
`const TransitioningColor = color(red, green,blue)`.
I'm not super familiar with either of these libraries but you're question is more of a mathematical mapping question, so I gave it a try. I'm assuming `new Value(1)` makes a constant node. Good Luck

**Comment by sweatherall** [comment]
@bahtiyara I had to do a similar thing and found a way that works for me, you can do something like this:
```
const RightOption = (progress, dragX) => {
   const { dragXValue } = this.state

   dragX.addListener(({ value }) => {
     console.log('dragX value:', value);
     this.setState({
        dragX,
        dragXValue: value,
        swipeActive: !!value
      });
    });

  const color = dragXValue > 100 ? #fff : #000

  return <AnimatedIcon style={{color}} name="delete" />
}
```

just remember to remove the listener when appropriate! (thats the main reason I store `dragX` in state - so you can later call `this.state.dragX.removeAllListeners()`)

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
If you need further help please reply.
