### ISSUE TITLE
Upgrade to 1.4.0 breaks Android build (React-Native 0.59)

### ISSUE THREAD

**Issue by chetstone** [software-mansion/react-native-gesture-handler#740]
Since AndroidX support was added in 1.4.0 this component is no longer compatible with RN < 0.60. The Getting Started Documents need to be updated to reflect this change.

**Comment by elvinas-engagecraft** [comment]
Just to double add.

It should be called 2.0.0 Because the minor version update should be backwards compatible:
https://semver.org/

> 2. MINOR version when you add functionality in a backwards compatible manner, and

And if you have something like that:
`"react-native-gesture-handler": "^1.2.0",`
It will break your builds.

**Comment by jdnichollsc** [comment]
You can Add gradle backward-compatibility if you want, check details here => https://github.com/kmagiera/react-native-gesture-handler/issues/743

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
If you need further help please reply.
