### ISSUE TITLE
Add gradle backward-compatibility with AndroidX

### ISSUE THREAD

**Issue by jdnichollsc** [software-mansion/react-native-gesture-handler#743]
It would be awesome if you can add these changes: https://twitter.com/jdnichollsc/status/1162451046544879616

The original discussion is here: https://github.com/proyecto26/react-native-inappbrowser/issues/96

Let me know if you're agree with this and I can create a Pull Request with the changes if you want, thanks guys! 👍

**Comment by matt-oakes** [comment]
@jdnichollsc Sure! Go ahead and submit a PR and I'll take a look over it 👍

**Comment by jakub-gonet** [comment]
I guess this feature request is a bit old right now so I'm going to close it. If you still interested in it, please reply.
