### ISSUE TITLE
androidx.annotation.Nullable

### ISSUE THREAD

**Issue by Ethan0007** [software-mansion/react-native-gesture-handler#749]
Hi, 

just having issue today /node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerModule.java:36: error: cannot find symbol
import androidx.annotation.Nullable;

Thanks.

**Comment by dineshchandraprasad** [comment]
I'm also getting this same error, can you please help me out of it

**Comment by Ethan0007** [comment]
Use 1.2.1 version..

**Comment by Dimon70007** [comment]
hi guys. i have added comments for maintainers of this repo - https://github.com/kmagiera/react-native-gesture-handler/commit/ed350dc475d5353e5594ff939ce2b1f667dfb111 and https://github.com/kmagiera/react-native-gesture-handler/commit/835250d22228510c811201d360fe977d79ec776e

**Comment by edritech93** [comment]
add :
android.useAndroidX=true
android.enableJetifier=true

to : ./android/gradde.properties

**Comment by Dimon70007** [comment]
> add :
> android.useAndroidX=true
> android.enableJetifier=true
> 
> to : ./android/gradde.properties

Thanks @edritech93. But it would work only for sample project. Our project could not be migrated to androidX now. 
I think it would be right to fix compatibility in minor version with old android build system and to release next major version with androidX system

**Comment by blacksheep--** [comment]
@Dimon70007 agree. Introducing breaking changes of this order of magnitude should not happen in minor and patch releases.

**Comment by SamiChab** [comment]
Any update on this?

**Comment by SamiChab** [comment]
I finally made it work...
What I did:
- unlinked react-native-gesture-handler
- uninstalled and reinstalled react-native-gesture-handler
- linked react-native-gesture-handler

Then I just followed some of the installation steps of the [react navigation docs](https://reactnavigation.org/docs/en/getting-started.html)
- `yarn add --dev jetifier`
- in package.json->scripts, add `"postinstall": "jetifier -r"`
- `yarn postinstall`

**Comment by Fox-3394** [comment]
@SamiChab thank a lot.

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
If you need further help please reply.

**Comment by piyushrajput45** [comment]
react-native build error:- package android.support.annotation does not exist

Go to the terminal and open your project

Step 1- npm install jetifier

You can use yarn

Step 2- npx jetify

Step 3- npx react-native run-android
