### ISSUE TITLE
'React/RCTEventDispatcher.h' file not found

### ISSUE THREAD

**Issue by oscargallegoglobant** [software-mansion/react-native-gesture-handler#751]
I'm getting this error when tying to run on tvOS -> RNGestureHandler-tvOS: 

react-native-gesture-handler/ios/RNGestureHandlerEvents.h:1:9:
 fatal error: 'React/RCTEventDispatcher.h' file not found
#import <React/RCTEventDispatcher.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
If you're still affected by it please reply.
