### ISSUE TITLE
DrawerLayout doesn't take all PanGestureHandler props

### ISSUE THREAD

**Issue by charles-goode** [software-mansion/react-native-gesture-handler#753]
Hello,
The component rendered inside of my drawer is getting rather complex. I am trying to put a horizontal scrolling FlatList in it, but the FlatList won't scroll. So I did some digging and found out about waitFor and simultaneousHandlers, so I switched to the gesture-handler wrapper on FlatList and added a ref of the Flatlist to the waitFor prop of the DrawerLayout since waitFor is supposed to be a common prop to all gesture handlers. Nothing changed. So I looked at the source for DrawerLayout and did a quick command-F for 'wait', 'for', 'simul' each returning 0 results. And that's when I looked down at the render and saw that the base PanGestureHandler composing the drawer doesn't implement those props.
https://github.com/kmagiera/react-native-gesture-handler/blob/6fae2e8a2d767983225eb7721f77d0c4f6392925/DrawerLayout.js#L502-L513

I'll admit I'm not too confident in my React-native so I guess I could be missing something. For one, the FlatList and the DrawerLayout are in two different files. The screen component using the Drawerlayout declares `this.listRef = React.createRef();` in its constructor. I then past that ref as prop `listRef={this.listRef}` through a number of parents of the FlatList until finally: `<FlatList ref={props.listRef} .../>`. I know I could use forwarding, but I believe this isn't the issue given the source code of DrawerLayout
I guess there may be a work-around  toggling the drawer-lock (which is virtually the same as the common enable prop) on BEGIN state in the FlatList, but I believe that waitFor should be implemented on DrawerLayout since it is considered a "common" handler prop. Thanks for reading. 

I'll throw in my versioning even though I can show that the code in the master of this repo is what I'm having an issue with. 
expo: 33.0.7
RNGH: 1.2.2
RNReanimated: 1.0.1
React: 16.8.3

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
If you need further help please reply.
