### ISSUE TITLE
Swipeable Rendering

### ISSUE THREAD

**Issue by lovecardasda6** [software-mansion/react-native-gesture-handler#760]
View panel render even a smallest swipe from either the left or right, here is my code

const renderLeftActions = (progress, dragX) => {
    const scale = dragX.interpolate({
      inputRange: [0, 100],
      outputRange: [0, 1],
      extrapolate: 'clamp',
    });
    return (
      
        <View style={styles.leftAction}>
            <Animated.Text style={[styles.actionText, { transform: [{ scale }] }]}>
            Add to Cart
            </Animated.Text>
        </View>

    );
  };

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
If you need further help please reply.
