### ISSUE TITLE
TranslateX and Rotate gestures not working simultaneously

### ISSUE THREAD

**Issue by igorbrandao** [software-mansion/react-native-gesture-handler#765]
First of all congrats for such a complete and excellent library!

My task is to translateX and slightly rotate a view at the same time.

I've read all of the docs but couldn't find a way to make that work. My implementation (see below) was based on the [example of handler interaction](https://github.com/kmagiera/react-native-gesture-handler/blob/master/Example/scaleAndRotate/index.js)

```
import React, { Component } from 'react';
import { View, StyleSheet, Animated } from 'react-native';
import { State, PanGestureHandler, RotationGestureHandler } from 'react-native-gesture-handler';

class Cards extends Component {
  panRef = React.createRef();
  rotationRef = React.createRef();

  constructor() {
    super();

    // Card Drag
    this._translateX = new Animated.Value(0);
    this._lastTranslateX = 0;
    this._onPanGestureEvent = Animated.event(
      [{ nativeEvent: { translationX: this._translateX }}],
      { useNativeDriver: true }
    );

    // Card Rotation
    this._rotate = new Animated.Value(0);
    this._rotateStr = this._rotate.interpolate({
      inputRange: [ -10, 10 ],
      outputRange: [ '-10rad', '10rad' ],
    });
    this._lastRotate = 0;
    this._onRotateGestureEvent = Animated.event(
      [{ nativeEvent: { rotation: this._rotate }}],
      { useNativeDriver: true }
    );
  }

  _onPanHandlerStateChange = ({ nativeEvent }) => {
    if (nativeEvent.oldState === State.ACTIVE) {
      console.log('this._translateX: ', this._translateX);
      this._lastTranslateX += nativeEvent.translationX;
      this._translateX.setOffset(this._lastTranslateX);
      this._translateX.setValue(0);
    }
  }

  _onRotateHandlerStateChange = ({ nativeEvent }) => {
    console.log('this._rotate: ', this._rotate);
    console.log('this._rotateStr: ', this._rotateStr);
    console.log('nativeEvent: ', nativeEvent);
    if (nativeEvent.oldState === State.ACTIVE) {
      console.log('this._rotate: ', this._rotate);
      console.log('this._rotateStr: ', this._rotateStr);
      this._lastRotate += nativeEvent.rotation;
      this._rotate.setOffset(this._lastRotate);
      this._rotate.setValue(0);
    }
  };

  render() {
    return (
      <View style={styles.container}>
        <View style={styles.margin}>
          <PanGestureHandler
            minPointers={1}
            maxPointers={1}
            ref={this.panRef}
            simultaneousHandlers={this.rotationRef}
            onGestureEvent={this._onPanGestureEvent}
            onHandlerStateChange={this._onPanHandlerStateChange}
          >
            <Animated.View>
              <RotationGestureHandler
                ref={this.rotationRef}
                simultaneousHandlers={this.panRef}
                onGestureEvent={this._onRotateGestureEvent}
                onHandlerStateChange={this._onRotateHandlerStateChange}
              >
                <Animated.View
                  style={[ styles.card, {
                    transform: [
                      { translateX: this._translateX },
                      { rotate: this._rotateStr },
                    ],
                  }]}
                >
                </Animated.View>
              </RotationGestureHandler>
            </Animated.View>
          </PanGestureHandler>
        </View>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    backgroundColor: 'white',
    flex: 1,
  },
  margin: {
    marginHorizontal: 10,
  },
  card: {
    backgroundColor: 'gray',
    height: 400,
    marginTop: 10,
    width: '100%',
  },
});

export default Cards;
```

When running the following snippet, you can see that the `console.log`s of `_onRotateHandlerStateChange` never get called, my guess is because `<PanGestureHandler />` is swallowing all of the event, despite the presence of `refs` and `simultaneousHandlers` props.

Am I missing something or this use case is currently unsupported?

Thanks in advance!

**Comment by stokesbga** [comment]
Also facing this. Did you find a solution?

**Comment by igorbrandao** [comment]
Yes, but not in code... While you can use `setState` in the `Animated.event` callback to have that rotation going, I advise against that because makes the animation slow super slow, destroying user experience. Ended up talking to customer and managed to convince him to give up on that rotation with pan, to have only panning instead.

**Comment by stokesbga** [comment]
I've noticed that if you remove the ```simultaneousHandlers``` reference between drag and rotate, everything is fine. My guess is that rotation is giving a bad value for the anchor, which is being used to calculate the delta X and Y. Will take a deeper look and get back to you

**Comment by j-piasecki** [comment]
Hi! If that's still relevant, the code from the original post wasn't working as intended because of `maxPointers={1}` prop on the `PanGestureHandler`. It was causing it to fail when the second finger (required for rotation) was touching the screen.

Also, with the release of Gesture Handler 2, the `PanGestureHandler` (and `Pan` gesture) no longer calculate translation values in the coordinate system of the view on iOS, so those are no longer affected by the rotation. On Android this was never the case.

I'll close the issue since it was inactive for a long time, but feel free to reopen it if you have any questions regarding it.
