### ISSUE TITLE
Performance issues when rendering list of Swipeable items

### ISSUE THREAD

**Issue by darrylyoung** [software-mansion/react-native-gesture-handler#767]
Hi, I've been playing around with `Swipeable` in my Expo project and the functionality is great but I've noticed performance really suffering once my list is ~10 or more. Is there something I'm missing or doing wrong? Here's an example of my custom _swipeable_ component. These are rendered in a `SectionList`.

```tsx
import * as Haptics from "expo-haptics"
import { Icon, ListItem } from "native-base"
import React from "react"
import { Animated, StyleSheet, TouchableOpacity, View } from "react-native"
import Swipeable from "react-native-gesture-handler/Swipeable"

const AnimatedIcon = Animated.createAnimatedComponent(Icon)

const toggleLightTap = () => Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light)
const toggleMediumTap = () => Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium)

const SwipeableListItem = ({ children, onPressIn, onPressRemove, disabled, id }) => {
  const RightActions = ({ progress, dragX, onPressRemove, id }) => {
    const scale = dragX.interpolate({
      inputRange: [-70, 0],
      outputRange: [1, 0],
      extrapolate: "clamp"
    })

    const handleRemove = () => {
      // Apollo Client mutation to remove item from cache
    }

    return (
      <TouchableOpacity onPress={handleRemove} onPressOut={toggleMediumTap}>
        <View style={styles.rightAction}>
          <AnimatedIcon
            name="ios-trash"
            size={30}
            color="#fff"
            style={[styles.actionIcon, { transform: [{ scale }] }]}
          />
        </View>
      </TouchableOpacity>
    )
  }

  return (
    <Swipeable
      onSwipeableRightWillOpen={toggleLightTap}
      renderRightActions={(progress, dragX) => (
        <RightActions id={id} progress={progress} onPressRemove={onPressRemove} dragX={dragX} />
      )}
    >
      <ListItem
        disabled={disabled}
        style={styles.container}
        onPressIn={onPressIn} // Apollo Client mutation to toggle this item as `checked` in the cache
        onPressOut={toggleMediumTap}
      >
        {children}
      </ListItem>
    </Swipeable>
  )
}

export default SwipeableListItem
```

If I just render a list of `ListItem` instead of `SwipeableListItem`, I can render loads and the performance is solid. Tapping an item triggers a mutation and that item then becomes _checked_. It's practically instant as it's just dealing with the local Apollo cache. When doing this through the `SwipeableListItem`, however, there's quite a delay before the mutation is complete. I'd guess 100-200ms but I can't be sure. Any suggestions?

Thanks.

**Comment by jakub-gonet** [comment]
May be related to extensive use of Animated inside Swipeable. Or anything else, hard to say without any reproduction example.

Closing, as this is likely outdated by now.

**Comment by NguyenHoangMinhkkkk** [comment]
@darrylyoung hi there. it's a long time this issue made and closed... so did you find out some solution for this issue ?
i'm here for researching about performance solution for list&scollview with these SwipeableItem.
