### ISSUE TITLE
Tag 1.3.0 does not point to the right source

### ISSUE THREAD

**Issue by darshannahar** [software-mansion/react-native-gesture-handler#770]
Looking at package.json it seems that tag 1.3.0 does not point to the right source as present in npm.
https://github.com/kmagiera/react-native-gesture-handler/blob/1.3.0/package.json

Please could we ensure tag 1.3.0 is in sync with the files available on npm?

**Comment by jakub-gonet** [comment]
It's one commit before version bump in package.json and it's safe to assume that most people don't use it any more nor need to develop RNGH 1.3.0 on their own.
