### ISSUE TITLE
Semantic versioning

### ISSUE THREAD

**Issue by nicolasrouanne** [software-mansion/react-native-gesture-handler#771]
What would you think about following [**semantic versioning**](https://semver.org/)? 🙏 

I find it dangerous and somewhat unconfortable to **make **breaking changes** in a _minor version_.** 
> **IMPORTANT!! This version is compatible with React Native @ 0.60+**
> ...
> As upgrade to 0.59 is required in order to be able to publish updates to google play store we decided to publish a release that is only compatible with 0.60 hoping for the community to update to one of the most recent versions of react native anyways.
>
>_See [release notes from `v1.4.0`](https://github.com/kmagiera/react-native-gesture-handler/releases/tag/1.4.0)_

Not everybody reads release notes from all _100+ dependencies_ of its projects, and when using _automatic dependency update tools_ such as [**_dependabot_**](https://dependabot.com/), it renders automating brittle.

**Comment by jakub-gonet** [comment]
We try to follow Expo versioning scheme (functionalities like in semantic versioning, but using minor versions for changes in native code - even when it's technically a patch version), but errors do happen.
