### ISSUE TITLE
[Android] Childviews of BorderlessButton with borderRadius don't render their background or their border in RN 0.61.1

### ISSUE THREAD

**Issue by partiellkorrekt** [software-mansion/react-native-gesture-handler#773]
In React-Native 0.61.1 the following code renders perfectly well:

```
<BorderlessButton>
  <View style={{
    width: 10,
    height: 10,
    backgroundColor: 'red'
  }} />
</BorderlessButton>
```

but as soon as you add any borderRadius (including 0) to the View, it will disappear on Android (API 28):

```
<BorderlessButton>
  <View style={{
    width: 10,
    height: 10,
    backgroundColor: 'red',
    borderRadius: 1
  }} />
</BorderlessButton>
```

Affected versions:
React-Native 0.61.1
react-native-gesture-handler 1.4.1 (latest currently)

**Comment by acollazomayer** [comment]
same here

**Comment by jkadamczyk** [comment]
I copied code to snack
https://snack.expo.io/WSdC6D!zO

I see both buttons displayed, closing the issue as it can't be reproduced
