### ISSUE TITLE
Not work on iOS when RN version is 6.0+

### ISSUE THREAD

**Issue by WWWWWWWolf** [software-mansion/react-native-gesture-handler#775]
When using RN 6.0 or 6.0+, the dependency is auto linking, but this dependency is not support for auto linking, manual link is not supported, and it's not work on iOS, Android is OK.

**Comment by calintamas** [comment]
https://github.com/kmagiera/react-native-gesture-handler/issues/686#issuecomment-510889111

**Comment by jakub-gonet** [comment]
Duplicate of #686.
