### ISSUE TITLE
FlatList(from RNGH) can not scroll anymore after nested in PanGestureHandler

### ISSUE THREAD

**Issue by pkf1994** [software-mansion/react-native-gesture-handler#791]
`render() {
        ...
        return (
                        <PanGestureHandler
                            onGestureEvent={this._onPanGestureEvent}>
                            <Animated.View style={{...}} >
                                     <FlatList data={data}
                                                    renderItem={itemData => this.renderItem(itemData)}
                                                    keyExtractor={item => "" + item.name + item.url}/>
                            </Animated.View>
                        </PanGestureHandler>
        )
    }`

**Comment by trostinsky** [comment]
I've got the same issue. FlatList/ScrollView and other scroll elements stop scrolling nested in PanGestureHandler.

**Comment by mxmzb** [comment]
also it looks like wrapping a `PanGestureHandler` inside a `ScrollView` similarily doesn't work

**Comment by yairopro** [comment]
Hi @mxmzb 
From the [GET STARTED](https://kmagiera.github.io/react-native-gesture-handler/docs/getting-started.html):

> In a nutshell, the library provides:
...
The ability to define relations between gesture handlers, e.g. when you have a pan handler in ScrollView you can make **that ScrollView wait until it knows pan won't recognize**.

So it seems the pan catches all touch events as long as it is configured to recognize it.
You can configure the pan to tell it what gesture it should recognize and which not using its props like `minDeltaX`, `maxDeltaX`, `minDist`, etc. [Have a look on the doc 😉](https://kmagiera.github.io/react-native-gesture-handler/docs/handler-pan.html).

**Comment by jkadamczyk** [comment]
I'll close this one as @yairopro explained some of this and it is also old issue, can reopen if there's a possibility.
