### ISSUE TITLE
Use hoist-non-react-static to expose static methods of wrapper components (FlatList...)

### ISSUE THREAD

**Issue by jsamr** [software-mansion/react-native-gesture-handler#794]
Basically, would allow library consumers to have access to `FlatList`, `ScrollView` and other wrapper components static methods.

This would resolve #285, and is very easy to implement. I can offer a PR if you give me the green flag.

References:

- https://reactjs.org/docs/higher-order-components.html#static-methods-must-be-copied-over
- https://github.com/mridgway/hoist-non-react-statics

**Comment by jkadamczyk** [comment]
I think this issue was solved and we were implementing some refForwarding recently as React Native also changed some of its API. I'll close as this is quite old.
