### ISSUE TITLE
Support panning with touchpads

### ISSUE THREAD

**Issue by robertherber** [software-mansion/react-native-gesture-handler#800]
When providing apps that work across touch devices and laptops with touchpads - which I guess is the common case when using Hammer - the natural way to interact is two-finger swiping to pan and swipe. I'm getting bug reports on this because people feel "swipe isn't working" as they expect, it's simply the UX one would expect (I know it applies to Macs, but I guess it applies to other platforms as well).

I personally feel this might fit best in Hammer - but there seems to be a hesitation to add this to the core library. I had a look at implementing this myself but I'm just not familiar enough with Hammer. Maybe someone that's more familiar with it could have a look? Would be much appreciated :)

**Comment by m-bert** [comment]
Hi @robertherber! Could you please check if #3163 works for you? 😅
