### ISSUE TITLE
Android app crash after Codepush update

### ISSUE THREAD

**Issue by rodrigofeijao** [software-mansion/react-native-gesture-handler#802]
After upgrading our app to use `react-native-gesture-handler@1.4.1` the android app started crashing after codepush updates.

Logcat shows: 

```
java.lang.IllegalStateException: Expected root helper to get unregistered while tearing down
        at com.swmansion.gesturehandler.react.RNGestureHandlerModule.onCatalystInstanceDestroy(RNGestureHandlerModule.java:565)
        at com.facebook.react.bridge.ModuleHolder.destroy(ModuleHolder.java:107)
        at com.facebook.react.bridge.NativeModuleRegistry.notifyJSInstanceDestroy(NativeModuleRegistry.java:84)
        at com.facebook.react.bridge.CatalystInstanceImpl$1.run(CatalystInstanceImpl.java:352)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
        at android.os.Looper.loop(Looper.java:214)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
        at java.lang.Thread.run(Thread.java:919)
```

This leads me to the `gestureHandlerRootHOC()`, and removing it and getting a new APK solves this issue. The problem is all gesture actions will crash the app. 
For example, trying to dismiss a modal from `react-navigation` using the pull down gesture hard crash the app. 

The same error we got with Codepush can be replicated when refreshing the app in debug mode. (as in, pressing double R on the simulator).

![image](https://user-images.githubusercontent.com/26038746/67563767-4c6d8600-f719-11e9-9acd-301e282adf58.png)

This is an Android only problem, and none of this could be replicated on iOS.

Packages version:
`react-native-gesture-handler`: `1.4.1`
`react-navigation`: `3.11.0`
`react-native-code-push`: `5.7.0`
`react-native`: `0.61.2`

**Comment by Christopher-May** [comment]
I've been having this problem what I did to fix it was add gestureHandlerRootHOC in my app.tsx. similar to what the [docs](https://kmagiera.github.io/react-native-gesture-handler/docs/getting-started.html#with-wix-react-native-navigation-https-githubcom-wix-react-native-navigation) suggest for wix native navigation.

`export default gestureHandlerRootHOC(codePush()(App));` <-- what fixed it for me

**Comment by rodrigofeijao** [comment]
@Christopher-May as I've explained above, that was exactly the problem. And it probably works for you because you're probably using `react-native-navigation` and not `react-navigation`.

**Comment by dvester** [comment]
@rodrigofeijao did we get any kind of resolution on this? I'm still encountering this issue. Perhaps a workaround for now?

**Comment by Frost-Zh** [comment]
Same error on android device.  
When I updated my react-navigation version from 4.x to 5.x I meet this error. And then I roll back the version of the react-navigation there is no error.

**Comment by Frost-Zh** [comment]
> Same error on android device.
> When I updated my react-navigation version from 4.x to 5.x I meet this error. And then I roll back the version of the react-navigation there is no error.

I found an issue that helped me.
https://github.com/react-navigation/react-navigation/issues/6919

**Comment by skizzo** [comment]
So, what's the solution for this?

**Comment by neeshurajput** [comment]
do we have any update on this crash ?

**Comment by nchase** [comment]
Does anyone have a solution or workaround to this problem?

**Comment by LFMAKER** [comment]
+

**Comment by kmagiera** [comment]
Hello everyone. I see that there are people commenting on the original issue which indicates that the problem may still persist on a more up-to-date versions that v 1.4 that this issue has been originally reported with. Please comment below if you still experience this problem and what version of gesture-handler are you using.
