### ISSUE TITLE
exclusive={false} prop to Touchable* on iOS

### ISSUE THREAD

**Issue by moxorama** [software-mansion/react-native-gesture-handler#803]
TouchableHighlight is multi-touch by default on Android,  and not on iOS.
This component is based on GenericTouchable,  which contains BaseButton,  with default property exclusive={true} on iOS

I think that  exclusive={false}  should be passed to BaseButton, or we should have ability to pass props to lower level components of Touchable*

**Comment by jakub-gonet** [comment]
Fixed in #454.
