### ISSUE TITLE
Using Animated.event with TapGestureHandler onHandlerStateChange doesn't work

### ISSUE THREAD

**Issue by rclai** [software-mansion/react-native-gesture-handler#815]
This is usage with `react-native-reanimated`.

I get this error:

```
Expected `onGestureHandlerStateChange` listener to be a function, instead got a value of `object` type.
```

Example:
```
const tapState = new Animated.Value(0);
const tapStateEvent = Animated.event([{ nativeEvent: { state: tapState } }]);
// ...
<TapGestureHandler onHandlerStateChange={tapStateEvent}>{...}</TapGestureHandler>
```

**Comment by mnmaraes** [comment]
For future reference I was able to solve my problem by having the GestureHandler's immediate child changed to a reanimated's `Animated.View`

**Comment by mym0404** [comment]
Thank you !

**Comment by Fr33maan** [comment]
@mnmaraes time saver !

**Comment by kotavy** [comment]
In the event that using `Animated.View` does not fix this issue, double-check your imports. I was mistakenly importing `Animated` from react-native instead of react-native-reanimated.

**Comment by CallMeProteus** [comment]
> In the event that using `Animated.View` does not fix this issue, double-check your imports. I was mistakenly importing `Animated` from react-native instead of react-native-reanimated.

this worked for me, use `import Animated, { Value } from 'react-native-reanimated'` if ur importing other modules
