### ISSUE TITLE
[info][tid:main][RNGestureHandlerManager.m:136] [GESTURE HANDLER] Initialize gesture handler for root view <RCTRootContentView: 0x7f820140c6d0; reactTag: 1; frame = (0 0; 414 896); gestureRecognizers = <NSArray: 0x600000fffc30>; layer = <CALayer: 0x6000001c1a00>>

### ISSUE THREAD

**Issue by Kaaden** [software-mansion/react-native-gesture-handler#818]
![image](https://user-images.githubusercontent.com/25861240/68004025-e0f05f00-fcaa-11e9-8015-f29384187524.png)
![image](https://user-images.githubusercontent.com/25861240/68004063-fcf40080-fcaa-11e9-9831-458703ef96f6.png)
这个是什么引起的，不知道该怎么解决

**Comment by yourihaha** [comment]
我也有這個問題，我更新expo sdk35 後發生的

**Comment by jakub-gonet** [comment]
This issue was not active for some time and lacks information so I'm closing it.
If you need further help please reply.
