### ISSUE TITLE
could not found @ReactModule annotation in com.swmansion.gesturehandler.react.RnGestureHandleModule

### ISSUE THREAD

**Issue by bigkrys** [software-mansion/react-native-gesture-handler#823]
i run command react-native run-android,and then i got the this
![image](https://user-images.githubusercontent.com/17899020/68097567-abd64d80-fef2-11e9-866c-4b00e3eb8b79.png)

React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (20) x64 Intel(R) Xeon(R) CPU E5-2660 v2 @ 2.20GHz
      Memory: 3.98 GB / 15.93 GB
    Binaries:
      Yarn: 1.19.1 - C:\Users\Administrator.SC-201910230934\AppData\Roaming\npm\yarn.CMD
      npm: 6.12.0 - C:\Program Files\nodejs\npm.CMD
react-native:0.58.6

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
If you need further help please reply.
