### ISSUE TITLE
How can I directly cancel the gesture-handler

### ISSUE THREAD

**Issue by little-buddy** [software-mansion/react-native-gesture-handler#824]
Sometimes, I want to cancel the gesture directly, But I don't find any methods can do it.
Someone can help me ? I'd be grate.

**Comment by euroclydon37** [comment]
Really want this feature for the following use case.

I want a nested ScrollView to `waitFor` an outer `<PanGestureHandler/>` that animated a bottom sheet. Once the bottom sheet hits the top of the screen, I want to manually cancel the `<PanGestureHandler/>` and let the scroll view take over.

I know that I _could_ just translate a view, but after getting this to work, I wanted to build a FlatList version to get the impression handling hooked up.

**Comment by euroclydon37** [comment]
There was some talk about it on #484.

**Comment by euroclydon37** [comment]
I wish I had time to figure out how to do this.

**Comment by jakub-gonet** [comment]
AFAIK at the moment, there's no API to do that, maybe forcing rerender could do something...

I'm gonna close this one, looks like it's been inactive for a while.
