### ISSUE TITLE
Does FlingGestureHandler work on Android?

### ISSUE THREAD

**Issue by bobber205** [software-mansion/react-native-gesture-handler#827]
Using the latest Gesture Handler (1.5.0) and FlingGestureHandler doesn't seem to be working on Android. This implementation is working perfectly on iOS.

```
                      <FlingGestureHandler
                          direction={Directions.RIGHT}
                          onHandlerStateChange={({ nativeEvent }) => {
                              if (nativeEvent.state === State.ACTIVE) {
                                  if (this.state.button_index - 1 < 0) {
                                      this.buttonSelected(this.state.searchTypes.length - 1);
                                  } else {
                                      this.buttonSelected(this.state.button_index - 1);
                                  }
                              }
                          }}>
                          <FlingGestureHandler
                              direction={Directions.LEFT}
                              onHandlerStateChange={({ nativeEvent }) => {
                                  if (nativeEvent.state === State.ACTIVE) {
                                      // go to next button 
                                      if (this.state.button_index + 1 > this.state.searchTypes.length - 1) {
                                          this.buttonSelected(0);
                                      } else {
                                          this.buttonSelected(this.state.button_index + 1);
                                      }
                                  }
                              }}>
</FlingGestureHandler>
</FlingGestureHandler>
```

Got a FlatList inside of those two handler containers. I wasn't sure how to properly detection direction so I used two FlingGestureHandlers.

Nothing happens on Android -- is this a known issue?

**Comment by stefoid** [comment]
Im also trying to use Fling.  Works on IOS, not on Android, have the main activity stuff done as detailed in the isntallation steps.  Will check some other stuff to see if it is Fling only

**Comment by bolincoln** [comment]
Same issue here, no callbacks whatsoever from any GestureHandler on Android, works fine on iOS. Really minimum app:
`    <PanGestureHandler onGestureEvent={() => {console.log("Gesture!");}} onHandlerStateChange={() => { console.log("Statechange!");}}>
    <View style={{width: "100%", height: "100%"}}>
    <Text>
      Test Gesture!
    </Text>
    </View>
  </PanGestureHandler>`
On RN 0.61.2.

**Comment by bolincoln** [comment]
Duh! It works fine if one actually follows the setup instructions for Android: https://kmagiera.github.io/react-native-gesture-handler/docs/getting-started.html#android

**Comment by bobber205** [comment]
@bolincoln This issue is about Fling only. Is Fling working for you?

**Comment by lukeforehand** [comment]
> Duh! It works fine if one actually follows the setup instructions for Android: https://kmagiera.github.io/react-native-gesture-handler/docs/getting-started.html#android

I followed these instructions and no dice, the gesture works on iOS but not Android.  Any other ideas?

**Comment by lukeforehand** [comment]
> > Duh! It works fine if one actually follows the setup instructions for Android: https://kmagiera.github.io/react-native-gesture-handler/docs/getting-started.html#android
> 
> I followed these instructions and no dice, the gesture works on iOS but not Android. Any other ideas?

Ok the event works now, to fix I had to the components around a little.  Instead of
```<FlingGestureHandler><ScrollView><Animated.View>...```

```<FlingGestureHandler><Animated.View><ScrollView>...``` worked.

**Comment by vtoupet** [comment]
@bobber205 I had the same issue as you until I found out a better way to handle right/left swipe. Instead of nesting 2 FlingGestureHandler I compare absoluteX from State.BEGAN state and State.ACTIVE. Below is an example of a Android working solution

```
const HorizontalSwipe = ({children, onLeft, onRight}: HorizontalSwipeProps) => {
  const [startX, setStartX] = React.useState<number>();

  return (
    <FlingGestureHandler
      direction={Directions.LEFT | Directions.RIGHT}
      onHandlerStateChange={({nativeEvent}) => {
        if (nativeEvent.state === State.BEGAN) {
          setStartX(nativeEvent.absoluteX);
        }
        if (nativeEvent.state === State.ACTIVE) {
          if (
            typeof startX !== 'undefined' &&
            nativeEvent.absoluteX - startX > 0
          ) {
            onLeft();
          } else {
            onRight();
          }
        }
      }}>
      {children}
    </FlingGestureHandler>
  );
};
```

I hope it will help anyone having problem on Android.

**Comment by Yrsafam** [comment]
At the moment, I'm facing an inoperable issue on android. I tried different ways. Including those presented above. The example provided in the official documentation does not work either. Can someone share links to some sources of the problem? Thanks

**Comment by ShivamJoker** [comment]
@vtoupet your solution doesn't seem to work as well. I am wrapping it on a TextInput component

**Comment by Haseeba393** [comment]
I have read the official documentation and here is the solution to everyone's problem:
From Official Docs: [https://docs.swmansion.com/react-native-gesture-handler/docs/
](url)
**"On Android RNGH does not work by default because modals are not located under React Native Root view in native hierarchy. To fix that, components need to be wrapped with gestureHandlerRootHOC (it's no-op on iOS and web)."**
So to make component responsive to your touch  events using react-native-gesture-handler just you need to wrap your component with gestureHandlerRootHOC as given in above documentation.

**Comment by kmagiera** [comment]
Hi all. Has anyone had a success with @Haseeba393's suggestion. I think the link from the comment does no longer =work so please check this one for instructions about usage with modals: https://docs.swmansion.com/react-native-gesture-handler/docs/installation/#usage-with-modals-on-android

**Comment by oguzydz** [comment]
> Hi all. Has anyone had a success with @Haseeba393's suggestion. I think the link from the comment does no longer =work so please check this one for instructions about usage with modals: https://docs.swmansion.com/react-native-gesture-handler/docs/installation/#usage-with-modals-on-android

It worked for me, I wrapped modal of react native content with "gestureHandlerRootHOC" method and it worked. No needed config.

`
"react-native": "0.71.3",
"react-native-gesture-handler": "^2.9.0",
`
