### ISSUE TITLE
DrawerLayout does not close when tapping on negative area

### ISSUE THREAD

**Issue by ospfranco** [software-mansion/react-native-gesture-handler#828]
I recently updated to RN 0.61.2 and gesture-handler 1.5.0, before the update I could close the drawer layout by tapping on the negative space (the actual content on the screen).

However after the update, the drawer is not closing any more, the only way to close it is by calling the closeDrawer() method.

Any suggestions?

Thanks!

**Comment by Fox-3394** [comment]
Same issue @.@. Please help!

**Comment by Fox-3394** [comment]
@ospfranco i have resolved my issue. Try update react-native 0.61.4

**Comment by augustocesarfmo** [comment]
If you are using RN > 0.60, you dont need use `react-native link react-native-gesture-handler`.

To correct the issue you need add the pink lines, same as bellow.

![image](https://user-images.githubusercontent.com/12482568/76568078-e5b1f480-648e-11ea-9fa9-5012d8c0d81f.png)

You can copy the lines on the [link](https://software-mansion.github.io/react-native-gesture-handler/docs/getting-started.html#android). Copy the lines and put in your `android/app/src/main/java/com/<your_project>/MainActivity.java` file and run again `react-native run-android`.

It worked for me. Thanks

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
If you need further help please reply.

**Comment by fr3nzy** [comment]
The same happened to me on android, although worked just fine on iOS. The key is to wrap the component which requires the use of gestures with `gestureHandlerRootHOC`. If you're using functional components, you can wrap the child of `DrawerLayout` like so:

```
const ChildOfDrawer = gestureHandlerRootHOC(() => {
    return <View />
})
```

**Comment by bohdan-sharkz** [comment]
https://github.com/software-mansion/react-native-gesture-handler/issues/2048#issuecomment-1124958911
Wrapping the `<DrawerLayout>` component with `<GestureHandlerRootView>` fixed the issue.
