### ISSUE TITLE
After adding top level import other libraries (mapbox) stop working

### ISSUE THREAD

**Issue by ospfranco** [software-mansion/react-native-gesture-handler#830]
I updated to RN and I'm also using mapbox in my app, after updating to RN 0.61 I was experiencing some crashes, I read on some other issues, the solution was to add a top level:

```typescript
// on index.js
import 'react-native-gesture-handler'
```

that seemed to get rid of the crashes, but I just realized that other libraries which rely on gestures, stop working, mapbox in my case has become completely unresponsive.

Any suggestions?

**Comment by ospfranco** [comment]
Monkey patch:

gesturePatch.js

```javascript
import { NativeModules } from 'react-native';

const { UIManager } = NativeModules;

if (UIManager) {
  const {
    // setJSResponder: oldSetJSResponder = () => {},
    // clearJSResponder: oldClearJSResponder = () => {},
    getConstants: oldGetConstants = () => ({}),
  } = UIManager;

  const customGHEventsConfig = {
    onGestureHandlerEvent: { registrationName: 'onGestureHandlerEvent' },
    onGestureHandlerStateChange: {
      registrationName: 'onGestureHandlerStateChange',
    },
  };

  UIManager.getConstants = () => {
    const constants = oldGetConstants();

    return {
      ...constants,
      genericDirectEventTypes: {
        ...constants.genericDirectEventTypes,
        ...customGHEventsConfig,
      },
    };
  };

  UIManager.genericDirectEventTypes = {
    ...UIManager.genericDirectEventTypes,
    ...customGHEventsConfig,
  };
}
```

and it is the first import on the main index.js file

This fixes the crash for me, while still being able to use other libraries dependent on the gestures such as mapbox, hopefully it help someone who is also having issues.

**Comment by mrousavy** [comment]
@ospfranco have you managed to get a gesture handler recognize gestures ontop of a mapbox view? I'm currently displaying a map and want to be able to let the user "swipe away" (horizontal pan gesture), but I can't manage to find a way to make it work like the user expects it to work in terms of UX. 

The horizontal swipe/pan gesture sometimes gets recognized on zoom events, and sometimes not recognized at all.

**Comment by ospfranco** [comment]
My problem was not related to map box, but rather to a top level gesture listener (in my case it was https://github.com/terrysahaidak/react-native-devmenu) after removing it everything worked fine
