### ISSUE TITLE
can not read property openDrawer of undefined

### ISSUE THREAD

**Issue by amirmn72** [software-mansion/react-native-gesture-handler#832]
<View style={styles.container}>
                <DrawerLayout
                    ref={drawer => this.NewDrawer = drawer}
                    drawerWidth={250}
                    keyboardDismissMode="on-drag"
                    drawerPosition={DrawerLayout.positions.Right}
                    drawerBackgroundColor="#ddd"
                    renderNavigationView={this.renderDrawer}
                >

                    <MyTabNavigation/>
                </DrawerLayout>
            </View>
and 
export const Screen1 = () =>
    <View style={{flex: 1, backgroundColor: 'red'}}>
        <TouchableOpacity style={{position:'absolute',top:10,right:5}}  onPress={() => 
                      this.NewDrawer.openDrawer()}>
            <Text>press</Text>
        </TouchableOpacity>
    </View>

**Comment by Markyza** [comment]
Screen1 can't 'see' this.NewDrawer. You can create fucntion and pass it to Screen1.

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
If you need further help please reply.
