### ISSUE TITLE
Add support for overriding system gestures

### ISSUE THREAD

**Issue by satya164** [software-mansion/react-native-gesture-handler#833]
iOS and Android 10 use gesture based navigation systems. Sometimes we need the gestures in our app to override system gestures. This is especially important for Android where the back navigation gesture is triggered by swiping from screen edges, which makes it impossible to implement UI such as navigation drawer which is also triggered by swiping from screen edges.

Both iOS and Android provide APIs to control this behaviour.

iOS: [`preferredScreenEdgesDeferringSystemGestures`](https://developer.apple.com/documentation/uikit/uiviewcontroller/2887512-preferredscreenedgesdeferringsys)
Android: [`setSystemGestureExclusionRects`](https://developer.android.com/reference/android/view/Window#setSystemGestureExclusionRects(java.util.List%3Candroid.graphics.Rect%3E))

cc @brentvatne

**Comment by swittk** [comment]
I'm wondering if this should be addressed here, or at https://github.com/software-mansion/react-native-screens?
[`preferredScreenEdgesDeferringSystemGestures`](https://developer.apple.com/documentation/uikit/uiviewcontroller/2887512-preferredscreenedgesdeferringsys) is a method on UIViewController so I'm not sure if we should open an issue there instead.

**Comment by jakeorbtl** [comment]
Unfortunately, I don't know how to disable system gestures altogether (without messing with native code), but there is a way to at least override the functionality of the gestures.

React Native provides an api for handling system back presses (this includes the back gesture on android). The [`BackHandler`](https://reactnative.dev/docs/backhandler) can be used to listen to system back presses and override the default functionality.

You can use it like so:
`import { BackHandler } from 'react-native';`

`BackHandler.addEventListener('hardwareBackPress', handleBackPress);`

In your `handleBackPress` callback, return `true` to prevent the default behavior after handling the back press yourself, or return `false` to allow the default behavior.

Don't forget to cleanup your listener when you are done using it. If you are using React Navigation, you can wrap everything in a `useFocusEffect` to automatically add/remove your listener when a screen enters/exits focus. The React Navigation docs provide an [example](https://reactnavigation.org/docs/custom-android-back-button-handling/) of how this can be done.

If you are using React Navigation, you can disable iOS gestures for a specific navigation screen via setting the screen option `gestureEnabled: false`.

**Comment by khlling** [comment]
Did anyone find a good solution for this on android?

**Comment by j-piasecki** [comment]
There is one significant problem with the Android API for this:

> [Note: the system will put a limit of 200dp on the vertical extent of the exclusions it takes into account. The limit does not apply while the navigation bar is stickily hidden, nor to the input method and home activity.](https://developer.android.com/reference/android/view/View#setSystemGestureExclusionRects(java.util.List%3Candroid.graphics.Rect%3E))

and when it comes to iOS the two edges where it would make sense are top and bottom I think, which do not interfere with navigation gestures.

Overall, I don't think Gesture Handler is the library that should be handling this (Screens already does something in this direction https://github.com/software-mansion/react-native-screens/blob/3ca34864e9d4e67bedef94079516b9d1e5a5b97a/ios/RNSScreen.mm#L1768). A completely new library for this purpose may make more sense.
