### ISSUE TITLE
Use useNativeDriver for Swipeable

### ISSUE THREAD

**Issue by Piero87** [software-mansion/react-native-gesture-handler#842]
Hi,
I'm using Swipeable component, but on iOS the animation is not smooth, it's possible to use useNativeDriver to make it better?

**Comment by jaysbytes** [comment]
It uses the native driver by default:
https://github.com/kmagiera/react-native-gesture-handler/blob/eeb93509e7e268a82dea89015fbe415407bba7cd/Swipeable.js#L56

**Comment by jaysbytes** [comment]
It uses the native driver by default:
https://github.com/kmagiera/react-native-gesture-handler/blob/eeb93509e7e268a82dea89015fbe415407bba7cd/Swipeable.js#L52:L57
