### ISSUE TITLE
Throw informative error if gesture-handler isn't linked properly

### ISSUE THREAD

**Issue by satya164** [software-mansion/react-native-gesture-handler#851]
If the user hasn't linked the library properly, currently the error messages aren't very useful.

e.g. If the library isn't linked, users usually get an error `null is not an object ( evaluating 'RNGestureHandlerModule.default.Direction')`. If the library is linked but no code was added to wrap the rootview, no error is thrown, but gestures don't work.

It'll be useful if the library showed a helpful error with a link to the documentation when it detects that it hasn't been linked properly.

**Comment by raajnadar** [comment]
Yes we need a warning message. I used react navigation without editing the java files the navigation worked but the gestures didn't work like the swipe between tabs didn't work.

**Comment by nathanbrachotte** [comment]
+1 I had this error because I had forgotten to run `pod install` on iOS. Took me a while to figure it out
