### ISSUE TITLE
Missing view element when swipe due to binding (this and variable)

### ISSUE THREAD

**Issue by MariShielaFurio** [software-mansion/react-native-gesture-handler#852]
Hi, Can someone help me. Im trying to bind a variable on renderLeftAction but when I add the  'this'
the display when opening swipeable view it display blank. Am i doing it wrong??

renderLeftActions={this.renderLeftActions.bind(this, event)}

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
If you need further help please reply.
