### ISSUE TITLE
Touchable* clip subchildren

### ISSUE THREAD

**Issue by todorone** [software-mansion/react-native-gesture-handler#859]
That's the snack - https://snack.expo.io/Hk2_bZEpH It uses `TouchableOpacity`, but I guess it's the same for all RNGH's Touchable*, they act as RN's internal touchables with `overflow: hidden`

Source:
```
import React from 'react'
import { View, TouchableOpacity } from 'react-native'
import { TouchableOpacity as RNGHTouchableOpacity } from 'react-native-gesture-handler'

export default class App extends React.Component {
  render() {
    return (
      <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
        <TouchableOpacity style={{ width: 100, height: 50, marginBottom: 50 }}>
          <View style={{ width: 200, height: 50, backgroundColor: 'blue' }} />
        </TouchableOpacity>
        
        <RNGHTouchableOpacity style={{ width: 100, height: 50 }}>
          <View style={{ width: 200, height: 50, backgroundColor: 'grey' }} />
        </RNGHTouchableOpacity>
      </View>
    )
  }
}
```

Result:
![Screenshot_2019-12-03-17-39-11-905_host exp exponent](https://user-images.githubusercontent.com/423701/70065600-0ba83d00-15f4-11ea-8e95-83522e1c03f1.jpg)

**Comment by piaskowyk** [comment]
Hey, you should use `containterStyle` instead of `style` property: `<RNGHTouchableOpacity containterStyle={{ width: 100, height: 50 }}>`

**Comment by Saikedo** [comment]
On Android this still does not work actually, any ideas if there is some way to address that ?
