### ISSUE TITLE
Wrong X/Y values with PanGesture + RotateGesture on iOS

### ISSUE THREAD

**Issue by Hirbod** [software-mansion/react-native-gesture-handler#863]
Hi, I am using one of the examples to drag, rotate, pan etc. Everything working fine so far, but as soon as I rotate my box, translateX and translateY behave weird. If I rotate for like 90°, swiping up/down will move my View left/right instead of up/down. This does not happen on android. I have a dirty workaround for now (I use 2 Views and I apply the rotation to the children View and the translate to the parent view. But this breaks stuff on android, so I ended up using Platform detection in order to fix this. So while I have a working solution already implemented, I don't like this dirty hacks.

What is the proper way to calculate X/Y in combination with simultanious rotation (while it doesn't matter if I do them the same time). As soon as its rotated, translation is wrong.

```js 
                        transform: [
                            {translateX: this._translateX},
                            {translateY: this._translateY},
                            {rotate: this._rotateStr},
                        ],
```

**Comment by jakub-gonet** [comment]
If it's still relevant, could please post the entire code example? Hard to say without seeing how translation values are calculated. Additionally, please provide your RNGH and RN versions.

Closing until more info is given.
