### ISSUE TITLE
Navigation not working on Release build

### ISSUE THREAD

**Issue by kbnawaz** [software-mansion/react-native-gesture-handler#868]
I have created new app with react-native version 0.61.5. But the Navigation is not working on the release build. On debug builds it works fine. 

"react": "16.9.0",
"react-native": "0.61.5",
"react-navigation": "^4.0.10",
"react-native-gesture-handler": "^1.5.1",
"react-navigation-stack": "^1.10.3",
"react-navigation-tabs": "^2.6.0",
    
I have done following as per the previous issues reported:
in index.js
import "react-native-gesture-handler";
import { AppRegistry } from "react-native";  
import App from "./src/App";
import { name as appName } from "./app.json";

**Comment by dharmendrasha** [comment]
+1

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
If you need further help please reply.
