### ISSUE TITLE
LongPressGestureHandler ios/android dragging behavior

### ISSUE THREAD

**Issue by YanisKondakov** [software-mansion/react-native-gesture-handler#869]
All of this behaviour are checked on different ios/android simulators/emulators and devices.

If i Use LongPressGestureHandler on ANDROID i have the behavior:
I press element, then state go UNDETERMINED (0) -> ACTIVE (4). Then if i start dragging element,
state is become CANCELLED (3).

If i Use LongPressGestureHandler on IOS i have the behavior:
I press element, then state go UNDETERMINED (0) -> ACTIVE (4). Then if i start dragging element,
state is still ACTIVE(4).

1) If it is exepected behavior, how is it possible to achieve ios behavior on android?

2) If it is not expected behavior, how we can drag elements after LongPressGestureHandler state is become CANCELLED (3)?

**Comment by lafiosca** [comment]
Per discussion in #574 try setting your `maxDist` higher and `shouldCancelWhenOutside={false}`

**Comment by lafiosca** [comment]
Although I'm finding now that in Android the gesture still gets cancelled if I drag the element further than the original distance to the edge of the parent view (i.e., when the item being dragged is inside of a scrollview which automatically scrolls). I'm not sure if there is a workaround for this.

**Comment by j-piasecki** [comment]
Hi! If that's still relevant: in https://github.com/software-mansion/react-native-gesture-handler/pull/1610 the behavior of `LongPressGestureHandler` has been normalized between the platforms, and now iOS behaves like Android. If you need custom behavior of a gesture, you can look into [touch events and manual gesture](https://docs.swmansion.com/react-native-gesture-handler/docs/manual-gestures/manual-gestures).

From your description it looks like you were trying to implement pan after long press. If that's the case then https://github.com/software-mansion/react-native-gesture-handler/pull/1938 will make implementing that much easier.
