### ISSUE TITLE
cannot read property 'direction' of undefined - Android Only

### ISSUE THREAD

**Issue by rezasazesh** [software-mansion/react-native-gesture-handler#878]
Hi I am using `react-native-navigation` and `"react-native-gesture-handler": "^1.5.2"`

It works fine on ios but I get `cannot read property 'direction' of undefined` on android

I have linked the library correctly I believe as it builds successfully, cannot get it to start the rootstack for my app once I include `import { gestureHandlerRootHOC } from "react-native-gesture-handler";
`

Has anyone else experienced this issue?

**Comment by mrdevguy** [comment]
I have the same issue and all the solutions related to jest that I came across didn't solve the issue for me. Did you manage to resolve this in the end?

**Comment by rezasazesh** [comment]
@mrdevguy yes I managed to solve it, I am not exactly sure what exact approach solved it but one of the things I was doing wrong was not wrapping screens around properly with `gestureHandlerRootHOC`, I also have redux so I have a function called `registerScreens` in a file called something like `screens.js` which I import in my `index.js`file. I think having the screens registered properly fixed it for me in the end



````
import React, {PureComponent} from 'react';
import {Provider} from 'react-redux';
import {Navigation} from 'react-native-navigation';
import {PersistGate} from 'redux-persist/integration/react';
import {gestureHandlerRootHOC} from 'react-native-gesture-handler';

//Import all of your screens here

import App from '../App';
import Home from '../screens/Home';


export function registerScreens(store, persistor) {
  function providerWrap(Component) {
    return function inject(props) {
      const EnhancedComponent = () => (
        <Provider store={store}>
          <PersistGate loading={null} persistor={persistor}>
            <Component {...props} />
          </PersistGate>
        </Provider>
      );

      return <EnhancedComponent />;
    };
  }

  function wrappedComponent(component) {
    return providerWrap(gestureHandlerRootHOC(component));
  }

  Navigation.registerComponent('App', () => wrappedComponent(App));
  Navigation.registerComponent('Home', () => wrappedComponent(Home));
}


````

**Comment by mrdevguy** [comment]
@rezasazesh Thanks for your response. Unfortunately it seems like I am wrapping the screens correctly. I haven't even implemented Redux at this point, so my case is even simpler. I guess the hunt for an answer continues ... Thanks again.

**Comment by mrdevguy** [comment]
This solved the issue for me: https://github.com/software-mansion/react-native-gesture-handler/issues/494#issuecomment-471164413
