### ISSUE TITLE
Web does not support SSR

### ISSUE THREAD

**Issue by slorber** [software-mansion/react-native-gesture-handler#883]
When rendering React server-side, in node env (useful in Gatsby/Next apps using RNW), this lib fails because Hammer initialization code runs early and expect to find "window".

![image](https://user-images.githubusercontent.com/749374/70866907-8f0c4b80-1f6f-11ea-850f-22d19ef3eecb.png)

I suggest we could import hammer lazily with something like `export const getHammer = () => typeof window !== "undefined" ? require('hammerjs') : undefined;`

This would also make the code more efficient, as we don't load hammer until a RNGH component is used

cc @EvanBacon

**Comment by lesmo** [comment]
As a workaround, you can try:

1. Install [`@egs/hammerjs`](https://www.npmjs.com/package/@egjs/hammerjs).
2. Alias it in ```webpack.config.js```

**Comment by slorber** [comment]
Thank, that could do the job temporarily.

**Comment by EvanBacon** [comment]
fixed with https://github.com/software-mansion/react-native-gesture-handler/pull/896

**Comment by slorber** [comment]
great! thanks :)

**Comment by slorber** [comment]
it seems to work.

however the fix is not yet published, so I'm using this temporarily:

    "react-native-gesture-handler": "https://github.com/software-mansion/react-native-gesture-handler.git#95bfb4df7ce9b1e222d50ead99eee7e27cd79043",
