### ISSUE TITLE
is it possible to have Swipeable only work for a single direction

### ISSUE THREAD

**Issue by chrisdrackett** [software-mansion/react-native-gesture-handler#885]
for example, just having a left swipe action and no action or animation on a right swipe?

**Comment by KingAmo** [comment]
the same question, i guess you have solved it because you  closed this issue,  could you help me ?

**Comment by sweatherall** [comment]
@chrisdrackett @KingAmo as long as there is nothing defined in `renderRightActions` then nothing will happen on rtl swipe.
