### ISSUE TITLE
null is not an object(evaluating '_RNGestureHandlerModule.default.handleSetJSResponder')

### ISSUE THREAD

**Issue by DucSilva** [software-mansion/react-native-gesture-handler#886]
Hi all! 
when i tap on screen I got an error as image below!  i don't know what's it? Does anyone help me fix this?
Thanks
![s](https://user-images.githubusercontent.com/46064085/71142854-38db2900-224b-11ea-8f35-782345e72cc1.png)

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
If you need further help please reply.
