### ISSUE TITLE
Evaluating Component.propTypes

### ISSUE THREAD

**Issue by JulioOrellana** [software-mansion/react-native-gesture-handler#887]
<img width="391" alt="Captura de Pantalla 2019-12-20 a la(s) 16 36 30" src="https://user-images.githubusercontent.com/10372340/71287349-ed0daa00-2346-11ea-995c-937683cb0791.png">

I am getting this error from upgrading from RN 0.59.10 to RN 0.61.5, I can't find the reason. Any clue?
Libs were unlinked and added to Pod

**Comment by dhevendhiran-adt** [comment]
hi,
I have the same issue. I am stuck in this same case (after upgraded to 0.61.5). Does anyone have any workarounds?

**Comment by JulioOrellana** [comment]
> hi,
> I have the same issue. I am stuck in this same case (after upgraded to 0.61.5). Does anyone have any workarounds?

The workaround I found on `jest test` is to mock every react-navigation library.

```js
jest.mock('react-navigation-stack', () => ({
  createStackNavigator: () => { },
  propTypes: {}
}));

jest.mock('react-navigation-tabs', () => ({
  createMaterialTopTabNavigator: () => { },
  createBottomTabNavigator: () => { },
  propTypes: {}
}));
...
```
You have to mock react-navigation libs you are using on your project

**Comment by thassis** [comment]
hi,
I don't use **jest test**, but I still have the same issue. Does you know another workarounds? 
I already downgrade the react-native version to 0.61.0 from 0.61.5 and updated the react-native-gesture-handler and react-navigation to latest version, but nothing works.

**Comment by Gerlison** [comment]
Same issue here

**Comment by 99pdl** [comment]
I had the same issue and to workaround I simply put:

`import React, { Component } from 'react';`

at the very top of `./node_modules/react-native-gesture-handler/GestureHandler.js`

Be aware that this is a temporary solution and I hope the package is fixed soon.
