### ISSUE TITLE
error fsevents@1.2.4: The platform "win32" is incompatible with this module. error Found incompatible module.

### ISSUE THREAD

**Issue by savetheearth2** [software-mansion/react-native-gesture-handler#889]
Hello, nice to meet you!
I have one error~
An error occurs while downloading the app and running "  yarn add react-native-gesture-handler"
What's the problem?

Operating system: window

![error](https://user-images.githubusercontent.com/36323955/71402007-04160a00-266f-11ea-8b05-95fd6b237c0b.PNG)

yarn add v1.21.1
[1/4] Resolving packages...
warning Resolution field "fsevents@1.2.4" is incompatible with requested version "fsevents@^1.2.7"
warning Resolution field "fsevents@1.2.4" is incompatible with requested version "fsevents@^1.2.7"
[2/4] Fetching packages...
error fsevents@1.2.4: The platform "win32" is incompatible with this module.
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

and When I did it with npm

![error 2](https://user-images.githubusercontent.com/36323955/71414581-f7a7a680-269a-11ea-8423-c731de1aad73.PNG)

C:\Users\LG\Desktop\gesture2>npm install --save react-native-gesture-handler
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "react-native-gesture-handler" under a package
npm ERR! also called "react-native-gesture-handler". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR! <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\LG\AppData\Roaming\npm-cache\_logs\2019-12-24T08_38_12_493Z-debug.log

**Comment by zero1code** [comment]
Did you resolve your problem? Can you tell me?

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
If you need further help please reply.

**Comment by ahtashamabbasse** [comment]
I'm facing the same issue, can you please suggest the solution?
