### ISSUE TITLE
Right swipe conflict between Swipeable and React Navigation

### ISSUE THREAD

**Issue by braincore** [software-mansion/react-native-gesture-handler#890]
I have a set of `Swipeable` rows in a `FlatList` based on the `AppleStyleSwipeableRow` example. The ability to "swipe right" is great. However, it makes it difficult to swipe right to move to the previous screen via react navigation. It works if my finger starts at the very edge of the screen.

Is there a way to make `Swipeable` only respond to touches toward the middle of the element so that the left side can be reserved for navigation? Currently, I've added left padding which adds a gap that navigation will respond to. But, this isn't ideal aesthetically since the sliding row no longer spans left edge to right edge due to the padding on the left side.

**Comment by savtym** [comment]
@braincore you can use `hitSlop`.

You can read about it [here](https://docs.swmansion.com/react-native-gesture-handler/docs/handler-common.html#hitslop)

For example:
```js
hitSlop={{ left: -60 }}

**Comment by braincore** [comment]
Thank you!

**Comment by sseppola** [comment]
For the record, I had a similar problem with PanGestureHandler and solved it with `activeOffsetX={[-5, 5]}`. Turns out the activation distance was shorter for the iOS "back" gesture in react-nativation.

**Comment by Kotpes** [comment]
Having `<Swipeable hitSlop={{ left: -60 }} />` fixed the issue 👍

**Comment by imransilvake** [comment]
`<Swipeable hitSlop={{ left: -60 }} />` worked. Thank you
