### ISSUE TITLE
RNGestureHandlerButtonViewManager.java uses or overrides a deprecated API

### ISSUE THREAD

**Issue by Maskedman99** [software-mansion/react-native-gesture-handler#895]
When I run ```yarn react-native run-android```,  the build fails with the following error:
```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.5/userguide/command_line_interface.html#sec:command_line_warnings
81 actionable tasks: 66 executed, 15 up-to-date
Note: /home/ubuntu/Reactnative/MyApp/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Unable to install /home/ubuntu/Reactnative/MyApp/android/app/build/outputs/apk/debug/app-debug.apk
com.android.ddmlib.InstallException: INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.myapp signatures do not match the previously installed version; ignoring!
```
Here's the dependencies: 
```
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-gesture-handler": "^1.5.2",
    "react-native-paper": "^3.4.0",
    "react-native-vector-icons": "^6.6.0",
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^1.10.3",
```
Running ``cd android && ./gradlew bundleRelease --warning-mode all`` shows no errors or warnings and the build completes successfuly.

**Comment by A-M-Alizadeh** [comment]
i'm using rn 0.59.5 and i get the same error and i can't get apk.
.\gradlew assembleRelease stops

    "@react-native-community/async-storage": "^1.3.4",
    "@react-native-community/netinfo": "^2.0.9",
    "@react-native-community/viewpager": "^3.3.0",
    "axios": "^0.18.0",
    "jetifier": "^1.6.5",
    "native-base": "^2.12.1",
    "prop-types": "^15.7.2",
    "react": "16.8.3",
    "react-native": "0.59.5",
    "react-native-extended-stylesheet": "^0.11.1",
    "react-native-gesture-handler": "1.5.2",
    "react-native-image-slider": "^2.0.3",   
    "react-native-snap-carousel": "^3.8.4",
    "react-native-swiper": "^1.5.14",
    "react-navigation": "^3.11.1",
    "react-redux": "^7.1.3",
    "redux": "^4.0.1",
    "redux-logger": "^3.0.6",
    "redux-persist": "^5.10.0",
    "redux-thunk": "^2.3.0"

**Comment by Maskedman99** [comment]
I fixed my error, the problem wasn't with RNGestureHandler, notice this line in the error
```
com.android.ddmlib.InstallException: INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.myapp signatures do not match the previously installed version; ignoring!
```
I already had a previous version of this app installed on my phone and it was conflicting with the new install, uninstalled the previous one and ran  ```yarn react-native run-android```  and now it's working.
@A-M-Alizadeh  Let me know if this solves your problem, so I can close this Issue.
