### ISSUE TITLE
onHandlerStateChange not firing sometimes on iOS

### ISSUE THREAD

**Issue by brentvatne** [software-mansion/react-native-gesture-handler#9]
# Expected behavior

On Android, the events fire as expected.

![giphy](https://user-images.githubusercontent.com/90494/28989813-b92c1616-792c-11e7-984f-bdca28b3bfaa.gif)

```
15:39:42.515: { id: 'scroll',
15:39:42.515:   oldStateName: 'UNDETERMINED',
15:39:42.515:   newStateName: 'BEGAN' }
15:39:42.519: { id: 'drawer',
15:39:42.519:   oldStateName: 'UNDETERMINED',
15:39:42.519:   newStateName: 'BEGAN' }
15:39:42.521: { id: 'masterdrawer',
15:39:42.521:   oldStateName: 'UNDETERMINED',
15:39:42.521:   newStateName: 'BEGAN' }
15:39:42.570: { id: 'drawer', oldStateName: 'BEGAN', newStateName: 'ACTIVE' }
15:39:44.797: { id: 'scroll', oldStateName: 'BEGAN', newStateName: 'ACTIVE' }
15:39:44.800: { id: 'masterdrawer',
15:39:44.800:   oldStateName: 'BEGAN',
15:39:44.800:   newStateName: 'FAILED' }
15:39:49.217: { id: 'drawer', oldStateName: 'ACTIVE', newStateName: 'END' }
15:39:49.217: 'END OFFSET', -425.2704223632812
15:39:49.235: { id: 'scroll', oldStateName: 'ACTIVE', newStateName: 'END' }
15:39:50.779: { id: 'scroll',
15:39:50.779:   oldStateName: 'UNDETERMINED',
15:39:50.779:   newStateName: 'BEGAN' }
15:39:50.781: { id: 'drawer',
15:39:50.781:   oldStateName: 'UNDETERMINED',
15:39:50.781:   newStateName: 'BEGAN' }
15:39:50.782: { id: 'masterdrawer',
15:39:50.782:   oldStateName: 'UNDETERMINED',
15:39:50.782:   newStateName: 'BEGAN' }
15:39:50.878: { id: 'drawer', oldStateName: 'BEGAN', newStateName: 'ACTIVE' }
15:39:51.589: { id: 'scroll', oldStateName: 'BEGAN', newStateName: 'END' }
15:39:51.590: { id: 'drawer', oldStateName: 'ACTIVE', newStateName: 'END' }
15:39:51.597: { id: 'masterdrawer',
15:39:51.597:   oldStateName: 'BEGAN',
15:39:51.597:   newStateName: 'FAILED' }
```

# Actual behavior

On iOS, only the inner pan is firing (@kmagiera you will know what I mean by this).

![giphy-1](https://user-images.githubusercontent.com/90494/28989828-ce5e8370-792c-11e7-9f21-c964dfa38f52.gif)

```
15:44:04: { id: 'drawer', oldStateName: 'UNDETERMINED', newStateName: 'BEGAN' }
15:44:04: { id: 'drawer', oldStateName: 'BEGAN', newStateName: 'ACTIVE' }
15:44:09: { id: 'drawer', oldStateName: 'ACTIVE', newStateName: 'END' }
15:44:09: 'END OFFSET', -436.5
```

**Comment by henrikra** [comment]
Is this still a bug? @kmagiera

**Comment by kmagiera** [comment]
Yes. But, not very major one. I havent had time to look into this

**Comment by osdnk** [comment]
+1 https://github.com/osdnk/react-native-reanimated-bottom-sheet/blob/master/index.js#L276

**Comment by vamshi9666** [comment]
same issue. pangesturehandle state is not becoming undetermined after pan finger left. but its staying in state.end

**Comment by kmagiera** [comment]
hey all! It's been a while since last activity on this issue. With the new API introduced last year, we no longer expect library users to interface with state change events (the callback is still there but no one really should be using it). Also, in the meantime we've changed a number of things under the hood so if anyone here have encountered this problem with a recent version or is willing to help by trying to repro it right now please respond in the comment.
