### ISSUE TITLE
Close already opened rows when opening a new row

### ISSUE THREAD

**Issue by swathi2378** [software-mansion/react-native-gesture-handler#903]
I need to close the all the swiped open rows when the user tries to open another swiped row.
Basically i need to close all inactive row buttons and open only active row swipe buttons.

How can i achieve this?

**Comment by jamesaspinall** [comment]
Hi Guys, I am also trying to achieve this and it would be great to hear your advice 
Thanks :)

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
If you need further help please reply.
