### ISSUE TITLE
How to pinch and pan from corners 

### ISSUE THREAD

**Issue by Steffi3rd** [software-mansion/react-native-gesture-handler#904]
Hello guys !

I try to implement a Pinchable + Draggable component.

Almost everything works fine (pinch, drag, and also pinch and drag at the same time).

There is only one problem :
When I pinch from corners (top left or top right or bottom left or bottom right), the pinch is only scale from the center and not from corners.... It's weird and makes not responsive.

When I pinch from center, we don't see this effect (looks good)

Can you help me please, how can I solve that ?

Here is the snack example : 
https://snack.expo.io/rk8d2Cjy8

I think it's about `focalY`, `focalX`, `transformsOrigin` etc...

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
If you need further help please reply.
