### ISSUE TITLE
Pressing multiple touchables not working on iOS (Works fine on Android)

### ISSUE THREAD

**Issue by JoelWi** [software-mansion/react-native-gesture-handler#906]
I've began building my app on the iOS side, and for some reason I can't press my TouchableOpacitys at the same time. Importing and using them like the docs say work correctly and I can press down on multiple TouchableOpacitys at the same time on my Android build, but for some reason the behavior doesn't seem to apply on the iOS side (can only press one touchable at a time)

If there is any example code to refer to for having multiple touchables working correctly on iOS I'll  really appreciate it!

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
If you need further help please reply.
