### ISSUE TITLE
TapGestureHandler within other TapGestureHandler throws error

### ISSUE THREAD

**Issue by kennym** [software-mansion/react-native-gesture-handler#907]
```
<TapGestureHandler onHandlerStateChange={() => console.log('Do something')}>
  <TapGestureHandler onHandlerStateChange={() => console.log('Do something')}>
  </TapGestureHandler>
</TapGestureHandler>
```

This code results in the following error:

![image](https://user-images.githubusercontent.com/160117/71744673-bf485b00-2e46-11ea-9818-64b109b27789.png)

react-native-gesture-handler v1.4.1
react-native 0.61.4

**Comment by kennym** [comment]
anyone?

**Comment by jakub-gonet** [comment]
You need to wrap inner TapGH with a component that renders a native view (e.g. `<View />`.
