### ISSUE TITLE
[Question] What happen if ForceTouchGestureHandler is not available (eg: iPhone XR) ?

### ISSUE THREAD

**Issue by Steffi3rd** [software-mansion/react-native-gesture-handler#908]
Hello guys, 

I would like to know what happen if `ForceTouchGestureHandler` is not available (eg: iPhone XR)?

Is there a fallback ? Like `LongPressGestureHandler` ? 

Or do we have to implement the fallback by ourself?

Thank you

**Comment by jakub-gonet** [comment]
Probably too late but:
we do internal check if `PlatformConstants.forceTouchAvailable` is true to create this handler. If it's not then we issue a warning and do nothing. You can use `ForceTouchGestureHandler.forceTouchAvailable` to determine if force touch is available.
