### ISSUE TITLE
Does not work with React Native 0.61.5

### ISSUE THREAD

**Issue by Tarik02** [software-mansion/react-native-gesture-handler#909]
Hello. I'm trying to use `react-navigation@next` with drawer navigation. But it does not react to any events.

Here's my dependencies list:
![Знімок екрана 2020-01-04 о 14 13 02](https://user-images.githubusercontent.com/12175048/71765361-54595b80-2efc-11ea-93bd-4ea5c86be13d.png)

I modified MainActivity according the installation guide:
![Знімок екрана 2020-01-04 о 14 14 13](https://user-images.githubusercontent.com/12175048/71765375-7e128280-2efc-11ea-92b9-e49cbbd3c527.png)

I even tried `gestureHandlerRootHOC` (this is `src/index.ts` which is just imported from `index.js`:
```typescript
import { gestureHandlerRootHOC } from 'react-native-gesture-handler';

const createApplication = () => {
	...

	const App = () => (
		<NavigationNativeContainer>
			<Provider store={store}>
				<Routes />
			</Provider>
		</NavigationNativeContainer>
	);

	return gestureHandlerRootHOC(App);
};

AppRegistry.registerComponent(appName, createApplication);
```

I can open the drawer programatically, but even then it does not react to any events.

**Comment by iv47** [comment]
I'm also experiencing the same issue, checked the documentation 👉 [getting started](https://software-mansion.github.io/react-native-gesture-handler/docs/getting-started.html), and it looks like it was last updated for RN version 0.57.2+. 

Dunno if there's a PR out there somewhere, maybe?

**Comment by venix** [comment]
I also have the same issue. Doesn't seem the getting started page to reflect to latest RN 0.60+ version. 
Let me know if you find a work around. 

I am using `"react-native-gesture-handler": "^1.5.2",` with `"react-native": "^0.61.5",`

**Comment by iv47** [comment]
> Update

Seems like version 1.4.0 works with auto linking!!

**Comment by Tarik02** [comment]
@iv47, which version exactly? 1.5.2 does not work for me.

**Comment by kayluhb** [comment]
Possibly related, I'm experiencing issues with version 1.5.3 and touchables.  When making a straight swap as per the docs, the component children do not render with the `Touchable*` components and the `Swipeable` component

```
    "react": "16.12.0",
    "react-native": "0.61.5",
    "react-native-gesture-handler": "^1.5.3",
```

**Comment by Tarik02** [comment]
React Native 0.61.1 and React Native Gesture Handler 1.6.0 works ok for me.
