### ISSUE TITLE
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually:                                       -native-gestur   - react-native-gesture-handler (to unlink run: "react-native unlink react-native-gesture-handler")

### ISSUE THREAD

**Issue by khali70** [software-mansion/react-native-gesture-handler#917]
its my first time to write a code and while i learning react native my owne i tried to install the 
**"react-native-gesture-handler": "^1.5.3",
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^2.0.15"**
and i got an error about metro port

error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually:    
- react-native-gesture-handler (to unlink run: "react-native unlink react-native-gesture-handler") 
This is likely happening when upgrading React Native from below 0.60 to 0.6dency>" and it0 or above. Going forward, you can unlink this dependency via "react-nativewith autolinki unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and noblob/master/dotify the library maintainers.
     
"version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-gesture-handler": "^1.5.3",
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^2.0.15"
  },
  "devDependencies": {
    "@babel/core": "7.7.7",
    "@babel/runtime": "7.7.7",
    "@react-native-community/eslint-config": "0.0.5",
    "babel-jest": "24.9.0",
    "eslint": "6.8.0",
    "jest": "24.9.0",
    "metro-react-native-babel-preset": "0.56.4",
    "react-test-renderer": "16.9.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by alessandro-p** [comment]
Hello @khali70 for which platform are you trying to run your code? Android or IOS? 
It seems that auto-linking is broken for Android in react-native-gesture-handler version 1.5.0... 
I managed to make it work excluding it from autolinking in react-native.config.js and linking it manually.
