### ISSUE TITLE
Add hit slop support

### ISSUE THREAD

**Issue by EvanBacon** [software-mansion/react-native-gesture-handler#924]
Doesn't seem like hammer.js supports this by default so it'll probably all need to be custom.

**Comment by Warus15** [comment]
Hit slop support was added in [2.6.1](https://github.com/software-mansion/react-native-gesture-handler/releases/tag/2.6.1)

Note that this change is available in new web implementation. To enable it, call `enableExperimentalWebImplementation()` in the root of your project.

**Comment by j-piasecki** [comment]
I'll close the issue since the new web implementation is enabled by default starting with 2.10.0.
