### ISSUE TITLE
Simple TouchEvent on PanResponder

### ISSUE THREAD

**Issue by Psiiirus** [software-mansion/react-native-gesture-handler#929]
Hi,
I implemented an draggable element which also implements an onPress behavior.
Unfortunately on iOS the PanResponder does not trigger any event if the User just "touchs" the PanResponder-Component but on Android it is woking fine.
Android gets 2 Events -> 
First Event: State: State.Begin 
Second Event: oldState: State.Begin  | (New)State: State.End 

Is this a known bug? Couldn't find anything about it.

Cheers,
Toni

**Comment by jakub-gonet** [comment]
If that's still relevant, could you please provide some small repro?
Besides, Pan responder is part of Examples and not API, so we don't really guarantee support them (however it should work correctly on both platforms).

Closing until more info is given.
