### ISSUE TITLE
How to track multiple finger positions and render on screen?

### ISSUE THREAD

**Issue by nhuesmann** [software-mansion/react-native-gesture-handler#934]
I'm looking to track multiple finger positions and render something under each finger. I've read the docs and looked through the examples and am not sure how to achieve this. I just wanted to know if there's an already known way to do this? Right now I'm using @EvanBacon's `expo-multi-touch` library, but it doesn't use reanimated and doesn't achieve 60 fps. The PanGestureHandler examples I've seen involve moving an already-rendered circle around the screen, however I want to dynamically render something under each finger once a touch is detected. I can ask this on StackOverflow if it feels more appropriate, however I just thought there might be a chance there's a simple solution or at least a way to get started. Thanks!

![touches](https://user-images.githubusercontent.com/613922/73209329-e704a900-40fc-11ea-812b-4e37f8d008e6.gif)

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
If you need further help please reply.

**Comment by ugurdalkiran** [comment]
I'm sorry to reopen the issue, but can this be done with the current package?

**Comment by Gireslopez** [comment]
@nhuesmann any update? did you mange to solve it? I'm looking for the same
