### ISSUE TITLE
Usage in android app without MainActivity

### ISSUE THREAD

**Issue by IanVS** [software-mansion/react-native-gesture-handler#936]
Hi, I have a brownfield app with multiple react native screens in use, but I don't have a `MainActivity` or `MainApplication` as assumed in the [getting started guide](https://software-mansion.github.io/react-native-gesture-handler/docs/getting-started.html#installation).  I've been searching for days trying to figure this out, but I'm not really an android developer so I'm a bit at a loss.  I believe we followed https://facebook.github.io/react-native/docs/integration-with-existing-apps when setting it up originally.  Any help would be much appreciated!

**Comment by satya164** [comment]
Follow this wix/react-native-navigation
