### ISSUE TITLE
Unable to resolve GestureHandlerRootView

### ISSUE THREAD

**Issue by paulosborne** [software-mansion/react-native-gesture-handler#941]
Just installed **1.5.4** and got the following error, goes away when i drop back down to **1.5.3**

![Screenshot 2020-02-02 at 17 05 53](https://user-images.githubusercontent.com/910163/73611931-42dc9f80-45df-11ea-9ec3-81029af36e62.png)

**Comment by nandafirmans** [comment]
I'm facing the same issues

**Comment by cambridge0427** [comment]
Same here

**Comment by danhoffman699** [comment]
I'm having the same issue

**Comment by Damidara16** [comment]
I switched back to 1.5.3. that seemed to work. "npm install react-native-gesture-handler@1.5.3" works with all other current up to date navigation packages

**Comment by swvaibhav** [comment]
Same here, I have been struggling on this from a long time now.

**Comment by ilove3q** [comment]
try version 1.5.0

**Comment by swvaibhav** [comment]
Not working, below is my package.json

```
"dependencies": {
    "@react-native-community/masked-view": "0.1.5",
    "axios": "^0.19.2",
    "expo": "~36.0.0",
    "moment": "^2.24.0",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz",
    "react-native-reanimated": "~1.4.0",
    "react-native-safe-area-context": "0.6.0",
    "react-native-screens": "2.0.0-alpha.12",
    "react-native-web": "~0.11.7",
    "react-navigation": "^4.1.0",
    "react-navigation-stack": "^2.0.16",
    "react-redux": "^7.1.3",
    "redux": "^4.0.5",
    "redux-logger": "^3.0.6",
    "redux-promise-middleware": "^6.1.2",
    "redux-thunk": "^2.3.0",
    "validator": "^12.2.0"
  },
  "devDependencies": {
    "babel-preset-expo": "~8.0.0",
    "@babel/core": "^7.0.0"
  },
```

**Comment by ygortgaleno** [comment]
Same here, I do the same, downgrade to 1.5.3 and solves the problem

**Comment by swvaibhav** [comment]
@ygortgaleno It isn't working for me, I tried downgrading the version but same result.

**Comment by Damidara16** [comment]
@ygortgaleno 
also i dont know if you tried, but first uninstall the handler already installed and then install 1.5.3
try this, this seems to stable.
  "dependencies": {
    "@react-native-community/masked-view": "^0.1.5",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-gesture-handler": "^1.5.3",
    "react-native-reanimated": "^1.4.0",
    "react-native-safe-area-context": "^0.6.2",
    "react-native-screens": "^2.0.0-alpha.22",
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^2.0.10",
    "react-navigation-tabs": "^2.7.0"
  },

**Comment by swvaibhav** [comment]
Screenshot from my emulator...
![react-error](https://user-images.githubusercontent.com/30657205/73615187-c3c18880-462b-11ea-93dc-a6e58f4d83b2.PNG)

**Comment by OscarArranz** [comment]
I got this same error, downgrading to 1.5.3 worked for me too!

**Comment by aliunco** [comment]
It seems that the issue is because of not mentioning the `GestureHandlerRootView.js` file the in `package.json` file
As a temporary solution you can go to this file: 
`/node_modules/react-native-gesture-handler/gestureHandlerRootHOC.js` and use the code below instead: 

```typescript
import React from 'react';
import { StyleSheet } from 'react-native';
import hoistNonReactStatics from 'hoist-non-react-statics';
import { View } from 'react-native';

export default function gestureHandlerRootHOC(
  Component,
  containerStyles = undefined
) {
  function Wrapper() {
    return (
      <View style={[styles.container, containerStyles]}>
        <Component {...this.props} />
      </View>
    );
  }

  Wrapper.displayName = `gestureHandlerRootHOC(${Component.displayName ||
    Component.name})`;

  hoistNonReactStatics(Wrapper, Component);

  return Wrapper;
}

const styles = StyleSheet.create({
  container: { flex: 1 },
});

```

**Comment by adrielschmitz** [comment]
Same for me. I tried `sudo rm -rf /.node_modules/` and `rm -rf /.yarn.lock`. And then `yarn install` but nothing yet... And i'm using the version ^1.5.3 of the react-native-gesture-handler.

**Comment by osdnk** [comment]
Terribly sorry for that. Just released 1.5.5 with the fix.

**Comment by adrielschmitz** [comment]
# IT WORKED  HERE!! 
Steps: In the project folder...
1. sudo `rm -rf node_modules/` and `rm -rf yarn.lock` 
2. I change the version of the react-native-gesture-handler (package.json) for 1.5.3, without `^`. 
3. And then `yarn install` and worked here.

**Comment by TXTDBR** [comment]
Me encontrei com mesmo erro e resolvi colocando a versão 1.4.0

**Comment by PauloVieirra** [comment]
Aqui apenas rodei o install sem mesmo desinstalar a versão anterior, funcionou bem. 
"npm install react-native-gesture-handler@1.5.3"
