### ISSUE TITLE
v1.5.5 not working with react-native-navigation

### ISSUE THREAD

**Issue by blueberry6401** [software-mansion/react-native-gesture-handler#942]
Code
```
Navigation.registerComponent(
  screenName,
  () => gestureHandlerRootHOC(Component),
)
```
throws
`Error: bindComponent expects a component with a componentId in props or a componentId as the second argument`

**Comment by legion-zver** [comment]
@blueberry6401 It's a kind of a tribal error of work for react... see node_modules/react-native-gesture-handler/gestureHandlerRootHOC.js:

**Comment by osdnk** [comment]
Thanks for marking!
