### ISSUE TITLE
Installation failed with "Exit code: 128" for latest "react-native-gesture-handler@1.5.6"

### ISSUE THREAD

**Issue by ajaykumar97** [software-mansion/react-native-gesture-handler#946]
I am trying to install the latest version in ``react-native-gesture-handler`` using ``yarn add react-native-gesture-handler`` but the ``yarn`` hangs out on ``hammerjs``.

Terminal output:

```
$ yarn add react-native-reanimated react-native-gesture-handler
yarn add v1.21.1
[1/4] 🔍  Resolving packages...
error Command failed.
Exit code: 128
Command: git
Arguments: clone https://github.com/naver/hammer.js.git /Users/(user-name)/Library/Caches/Yarn/v6/.tmp/9ee0a27027db93fad58e8dddb6592fbc
Directory: /Users/(user-name)/Documents/ReactNative/Projects/VacancyReward
Output:
Cloning into '/Users/(user-name)/Library/Caches/Yarn/v6/.tmp/9ee0a27027db93fad58e8dddb6592fbc'...
error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

``Dependencies``

"react": "16.9.0",
 "react-native": "0.61.5",
 "react-native-gesture-handler": "1.5.6"

For now, using the older version i.e. ``"react-native-gesture-handler": "1.5.3"``

**Comment by bruiglesias** [comment]
Same error here: 

42 error errno -4058
43 error enoent Error while executing:
43 error enoent undefined ls-remote -h -t https://github.com/naver/hammer.js.git
43 error enoent
43 error enoent
43 error enoent spawn git ENOENT
44 error enoent This is related to npm not being able to find a file.
45 verbose exit [ -4058, true ]

**Comment by MR03web** [comment]
same question

**Comment by zhengyu7664** [comment]
same question

**Comment by bruiglesias** [comment]
yarn add react-native-gesture-handler@1.4.0 solved for now.

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
If you need further help please reply.
