### ISSUE TITLE
[Android] React Native Modal + Wix Navigation don't work

### ISSUE THREAD

**Issue by samcampisi** [software-mansion/react-native-gesture-handler#947]
I commented on #139 yesterday after trying modals on the example app (#937). This worked like a charm in there but when I went to try it on a wix navigation app it did not work. I wouldn't like to use wix's modal since it does not provide the animations I need.

I managed to create a minimum reproducible example following these steps (for Android only, since iOS works fine) and uploaded it here https://github.com/samcampisi/gesture-handler-modal-example/tree/master

I don't know if there's anything else I need to do to make it work, but I really appreciate that without wix's navigation the modal already works with RectButton and the like. Thanks so much in advance.

I'm testing with:
react-native-gesture-handler on 1.5.6
react-native 0.61.5
android onePlus 6

**Comment by samcampisi** [comment]
In the end I'm just going to wait for wix's navigation version 5.x since it provides the correct modal animations. This way I can use RectButton and the like inside those views without a problem.

**Comment by oferRounds** [comment]
@samcampisi have you eventually found any solution? We also use wix’s navigation
