### ISSUE TITLE
installing 1.5.4 and beyond causes installation error.

### ISSUE THREAD

**Issue by amamiri** [software-mansion/react-native-gesture-handler#948]
"npm install react-ntive-gesture-handler@^1.5.4 --save" causes the following error:

npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/naver/hammer.js.git

Thanks
A.

**Comment by bruiglesias** [comment]
Same error here. Log file:

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   'react-native-gesture-handler'
1 verbose cli ]
2 info using npm@6.13.1
3 info using node@v13.3.0
4 verbose npm-session 7a16a1393adac319
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/react-native-gesture-handler 652ms (from cache)
8 silly pacote tag manifest for react-native-gesture-handler@latest fetched in 674ms
9 timing stage:loadCurrentTree Completed in 810ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 8ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule react-native-gesture-handler@1.5.6 checking installable status
17 silly fetchPackageMetaData error for hammerjs@git+https://github.com/naver/hammer.js.git Error while executing:
17 silly fetchPackageMetaData undefined ls-remote -h -t https://github.com/naver/hammer.js.git
17 silly fetchPackageMetaData
17 silly fetchPackageMetaData
17 silly fetchPackageMetaData spawn git ENOENT
18 http fetch GET 304 https://registry.npmjs.org/@egjs%2fhammerjs 194ms (from cache)
19 silly pacote range manifest for @egjs/hammerjs@^2.0.17 fetched in 201ms
20 silly resolveWithNewModule @egjs/hammerjs@2.0.17 checking installable status
21 http fetch GET 304 https://registry.npmjs.org/hoist-non-react-statics 331ms (from cache)
22 silly pacote range manifest for hoist-non-react-statics@^2.3.1 fetched in 336ms
23 silly resolveWithNewModule hoist-non-react-statics@2.5.5 checking installable status
24 http fetch GET 304 https://registry.npmjs.org/invariant 338ms (from cache)
25 silly pacote range manifest for invariant@^2.2.4 fetched in 341ms
26 silly resolveWithNewModule invariant@2.2.4 checking installable status
27 http fetch GET 304 https://registry.npmjs.org/prop-types 407ms (from cache)
28 silly pacote range manifest for prop-types@^15.7.2 fetched in 409ms
29 silly resolveWithNewModule prop-types@15.7.2 checking installable status
30 timing stage:rollbackFailedOptional Completed in 1ms
31 timing stage:runTopLevelLifecycles Completed in 1289ms
32 silly saveTree App
32 silly saveTree +-- @react-navigation/native@5.0.0
32 silly saveTree | `-- @react-navigation/core@5.0.0
32 silly saveTree |   +-- escape-string-regexp@2.0.0
32 silly saveTree |   +-- query-string@6.10.1
32 silly saveTree |   | +-- decode-uri-component@0.2.0
32 silly saveTree |   | +-- split-on-first@1.1.0
32 silly saveTree |   | `-- strict-uri-encode@2.0.0
32 silly saveTree |   +-- react-is@16.12.0
32 silly saveTree |   +-- shortid@2.2.15
32 silly saveTree |   | `-- nanoid@2.1.11
32 silly saveTree |   `-- use-subscription@1.3.0
32 silly saveTree |     `-- object-assign@4.1.1
32 silly saveTree +-- react-native-gesture-handler@1.5.6
32 silly saveTree | +-- @egjs/hammerjs@2.0.17
32 silly saveTree | +-- hoist-non-react-statics@2.5.5
32 silly saveTree | +-- invariant@2.2.4
32 silly saveTree | `-- prop-types@15.7.2
32 silly saveTree `-- react-native-reanimated@1.7.0
33 verbose stack Error: spawn git ENOENT
33 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:19)
33 verbose stack     at onErrorNT (internal/child_process.js:468:16)
33 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
34 verbose cwd C:\brunoiglesias\App
35 verbose Windows_NT 6.1.7601
36 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "react-native-gesture-handler"
37 verbose node v13.3.0
38 verbose npm  v6.13.1
39 error code ENOENT
40 error syscall spawn git
41 error path git
42 error errno -4058
4**3 error enoent Error while executing:
**43 error enoent undefined ls-remote -h -t https://github.com/naver/hammer.js.git
43 error enoent
43 error enoent
43 error enoent spawn git ENOENT
44 error enoent This is related to npm not being able to find a file.**
45 verbose exit [ -4058, true ]**

**Comment by diegommc** [comment]
same error any suggestion? may be the server is down

**Comment by satya164** [comment]
you need to install git on your machine

**Comment by amamiri** [comment]
> you need to install git on your machine

I did and It doesn't solve that problem. Normally, your dependencies should not require git's installation. Bad practice, I think. 

> same error any suggestion? may be the server is down

Install 1.5.3. It should work!

**Comment by DevilMayDead** [comment]
Hi,man! I also have the same problmes, do you have solve it ?

**Comment by amamiri** [comment]
> Hi,man! I also have the same problmes, do you have solve it ?

Yes. Install 1.5.3, which doesn't seem to have that problem.

**Comment by DevilMayDead** [comment]
Oh,thank u so musch, my bro

**Comment by olagregs** [comment]
> > you need to install git on your machine
> 
> I did and It doesn't solve that problem. Normally, your dependencies should not require git's installation. Bad practice, I think.
> 
> > same error any suggestion? may be the server is down
> 
> Install 1.5.3. It should work!

thank you, it worked

**Comment by bruiglesias** [comment]
yarn add react-native-gesture-handler@1.4.0  solved for me.

**Comment by jakub-gonet** [comment]
Seems resolved.
