### ISSUE TITLE
Duplicate Dependency on hammerjs?

### ISSUE THREAD

**Issue by bananer** [software-mansion/react-native-gesture-handler#949]
Your package.json contains dependencies toward  `@egjs/hammerjs` and `hammerjs`. Apparently in the pull request discussion [it was agreed](https://github.com/software-mansion/react-native-gesture-handler/pull/896/files#r362153649) that only `@egjs/hammerjs` is needed.

The entry for `hammerjs` seems to be pointing to the GitHub repository for `@egjs/hammers` which makes no sense to me.

I suppose the dependency towards `hammerjs` can and should be removed.

---

I only stumbled across this while trying to figure out why my CI build was failing. Turns out I don't have git included in the container, and the update to the latest version of this package was what made `npm install` require git. Possibly this is the same problem the people in #946 and #948 are having. I could, of coures, fix my problem by adding git to my CI images.

**Comment by bruiglesias** [comment]
yarn add react-native-gesture-handler@1.4.0 solved for me.

**Comment by bananer** [comment]
@bruiglesias Versions up to 1.5.3 work

**Comment by bananer** [comment]
Fixed in 1.6.0, thanks!
