### ISSUE TITLE
undefined ls-remote -h -t https://github.com/naver/hammer.js.git

### ISSUE THREAD

**Issue by TerrerSandman** [software-mansion/react-native-gesture-handler#952]
Having errors below when running `npm install react-native-gesture-handler`

> 45 error path git
46 error code ENOENT
47 error errno ENOENT
48 error syscall spawn git
49 error enoent Error while executing:
49 error enoent undefined ls-remote -h -t https://github.com/naver/hammer.js.git
49 error enoent
49 error enoent
49 error enoent spawn git ENOENT
50 error enoent This is related to npm not being able to find a file.

===========================================

Node v10.16.0
npm 6.9.0
RN 0.60.5
@react-navigation/native ^5.0.0

**Comment by diegommc** [comment]
same problem

**Comment by DevilMayDead** [comment]
Yep,i have no idea.It's too bad

**Comment by TerrerSandman** [comment]
Okay I've figured out the issue. It appeared that this error caused by wrong git path. If you haven't installed git yet please do so [download git here](https://gitforwindows.org/)

**Solutions**
1. Open **Environment Variables**
2. Edit **Path**
3. Find your git location that been installed in your device. Example like mine is `C:\Program Files\Git\cmd`
4. Add the git location to **Path** (make sure to add this to both **user variables** and **system variables**)
5. Apply the changes and restart your pc
6. Lastly, go back to your project and run `npm install react-native-gesture-handler`
