### ISSUE TITLE
error on installing package of react-native-gesture-handler

### ISSUE THREAD

**Issue by hafizshayanahmed** [software-mansion/react-native-gesture-handler#956]
I am trying to install package of react-native-gesture-handler but its not downloading and same error has been occurring since 2 days. Is there anyone who can advise me on this how to tackle this issue. Please see below error 

E:\milkShops>npm i react-native-gesture-handler
npm ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/naver/hammer.js.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\shaya\AppData\Roaming\npm-cache\_logs\2020-02-10T17_40_00_214Z-debug.log

**Comment by bruiglesias** [comment]
yarn add react-native-gesture-handler@1.4.0 solved for now.

**Comment by hafizshayanahmed** [comment]
> yarn add react-native-gesture-handler@1.4.0 solved for now.

Thanks. It's working now

**Comment by Ziamuhyuddin** [comment]
> yarn add react-native-gesture-handler@1.4.0

Its working <3
