### ISSUE TITLE
Swipable vs react-native-swipe-list-view

### ISSUE THREAD

**Issue by kopax** [software-mansion/react-native-gesture-handler#958]
I want to implement the Gmail Android app list:

![alt tag](https://raw.githubusercontent.com/ggomaeng/react-native-gmail/master/demo.gif)

For this I am looking for existing swipe list view and found https://github.com/jemise111/react-native-swipe-list-view/ and https://github.com/software-mansion/react-native-gesture-handler/blob/master/docs/component-swipeable.md

It seems that the first one is not using react-native-gesture-handler (https://github.com/jemise111/react-native-swipe-list-view/issues/168), this make me wonder, is this swipable more advanced and more user friendly, the first one is a bit flaggy but more users seems to use it for their list, 

did anybody tried both?

Thanks in advance,

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
If you need further help please reply.
