### ISSUE TITLE
Snack is broken

### ISSUE THREAD

**Issue by kopax** [software-mansion/react-native-gesture-handler#959]
I was reading your documentation and wanted to try the expo snack https://expo.io/@osdnk/gesturehandlerexample

After trying to open it with both android and ios expo client, I have an error:

![image](https://user-images.githubusercontent.com/1866564/74215371-769c8100-4cd3-11ea-953c-8b61b025de65.png)

It seems that the demo is deprecated, is there a way to get it updated? Thanks for sharing and best!

**Comment by jakub-gonet** [comment]
Resolved by #1131
