### ISSUE TITLE
GmailStyleSwipeableRow example crash on android

### ISSUE THREAD

**Issue by kopax** [software-mansion/react-native-gesture-handler#960]
## Description

I have read : https://github.com/software-mansion/react-native-gesture-handler/blob/master/docs/component-swipeable.md  and https://software-mansion.github.io/react-native-gesture-handler/docs/component-swipeable.html

I have copied the https://github.com/software-mansion/react-native-gesture-handler/blob/master/Example/swipeable/index.js in my project.

I have tried to downgrade from 1.5.6 to 1.4.0 but the error remain

The error happen in [`<GmailStyleSwipeableRow />`](https://github.com/software-mansion/react-native-gesture-handler/blob/master/Example/swipeable/GmailStyleSwipeableRow.js)

The error goes away if we comment:

https://github.com/software-mansion/react-native-gesture-handler/blob/d9c7553c8d7112dcff9bd498975a5f4b0a1fa9bc/Example/swipeable/GmailStyleSwipeableRow.js#L24

And:

https://github.com/software-mansion/react-native-gesture-handler/blob/d9c7553c8d7112dcff9bd498975a5f4b0a1fa9bc/Example/swipeable/GmailStyleSwipeableRow.js#L41

## Reproduction

Snack : https://snack.expo.io/@kopax/react-native-gesture-handler-issue-960

This snack work in expo, but it is not working with expo client on Samsung Galaxy S9.

## Expected

I expect the example to work on all devices

## Result

When I try to access from Android, I can a fatal error (see blow)

This is the part that causes the problem: 

```jsx
    return (
      <RectButton style={styles.rightAction} onPress={this.close}>
        <AnimatedIcon
          name="delete-forever"
          size={30}
          color="#fff"
          style={[styles.actionIcon, { transform: [{ scale }] }]}
        />
      </RectButton>
    );
  };
```

With this uncommented: 

```diff
      <RectButton style={styles.leftAction} onPress={this.close}>
        <AnimatedIcon
          name="archive"
          size={30}
          color="#fff"
-          style={[styles.actionIcon, { transform: [{ scale }] }]}
+          // style={[styles.actionIcon, { transform: [{ scale }] }]}
        />
      </RectButton>
```

I have the following error on Android:

![image](https://user-images.githubusercontent.com/1866564/74222664-96d63b00-4ce7-11ea-93f5-b168000fde68.png)

Without the animated component: 

```diff
      <RectButton style={styles.leftAction} onPress={this.close}>
-        <AnimatedIcon
+        <Icon
          name="archive"
          size={30}
          color="#fff"
          style={[styles.actionIcon, { transform: [{ scale }] }]}
        />
      </RectButton>
```

I have:

![image](https://user-images.githubusercontent.com/1866564/74283730-f9195500-4d54-11ea-8501-5ba443bf04ba.png)

What's wrong with this animation?

**Comment by jakub-gonet** [comment]
This is related to the Example component that we don't actively maintain and support so I'll close this one, sorry.

Seems like it's a bit old too.
