### ISSUE TITLE
Question: Conditionally disable pan gesture handler

### ISSUE THREAD

**Issue by dmoss18** [software-mansion/react-native-gesture-handler#964]
Is there any way to let the pan gesture handler activate only when the user is dragging on a certain part of the screen? Similar to `onStartShouldSetResponder` in react-native gestures.

For example, I have a screen where views will appear/disappear at different positions. I'd like the pan gesture handler to only activate when the user is dragging on these views. These views can be anywhere on the screen, so I'd like to use just one gesture handler to catch them all. Is this possible?

**Comment by latviancoder** [comment]
I have similar functionality and I'm using a single pan gesture handler. I'm manually tracking positions/visibility of all the draggable views and then when the pan gesture starts I'm calculating if initial gesture x/y are within view bounds.

**Comment by dmoss18** [comment]
@latviancoder So if it's not in the view's bounds, how do you cancel it?

**Comment by latviancoder** [comment]
I'm not "cancelling" in directly, I'm just not reacting to it. Only when the initial gesture x/y are within bounds do I initiate the dragging of particular view.

**Comment by zoonosis** [comment]
You just need to use the HitSlop property of the pangesturehandler

**Comment by dmoss18** [comment]
@zoonosis The problem is there are multiple views that can appear at different locations simultaneously. Hitslop only shrinks the bounds of the parent view
