### ISSUE TITLE
Question: Can you use the pan gesture to control scale instead of the pinch gesture?

### ISSUE THREAD

**Issue by zoonosis** [software-mansion/react-native-gesture-handler#965]
Hi
What im trying to do is scale an image vertically using just a pan gesture, whereas using a pinch gesture scales it in both x and y axis. I want to pan my finger up, stretching the image, and pan it down which would squash it making it very short.

Ive copied the example code from github for a pinch gesture and changed it to a pan one but im getting a malformed calls from JS field sizes are different error so its obviously more than a handler change

Can the pan gesture handler do this and Im just not a very good dev? or am I out of luck?

Thanks

**Comment by leo0grau** [comment]
Hi, did you find any way to do it?
