### ISSUE TITLE
FocalX FocalY is not available in pan gesture handler. Is that by design?

### ISSUE THREAD

**Issue by zoonosis** [software-mansion/react-native-gesture-handler#976]
Im currently using a pan gesture handler to adjust the scaleY property of an animated view. You can think of it like a slider. I move my finger in the pan gesture vertically and the scale changes.

However the pan gesture handler doesnt seem to have the focalX/Y properties that the pinch gesture handler does so when the view scales it is off centre and you lose visual of what you were seeing before it scaled

Is there a way around this? or can Focal be added to pan gesture?

**Comment by terrysahaidak** [comment]
You should wrap your view with `TapGestureHandler` to receive the "focal" point (x/y coordinates). Multiple fingers can be used to.

Let me know if this fixes the issue.

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
If you need further help please reply.
