### ISSUE TITLE
How can I close the Swipeable instantly?

### ISSUE THREAD

**Issue by kopax** [software-mansion/react-native-gesture-handler#977]
I am reading [`<Swipeable />`](https://github.com/software-mansion/react-native-gesture-handler/blob/master/Swipeable.js) component and I am trying to find a way to disable the `.close()` animation.

The use case is a swipe right to add to favorite, after 3000ms, the line is in favorite, we just close it and make a star appear within item.

How can I close the Swipeable instantly?

**Comment by buchereli** [comment]
Patch `Swipeable.js` with

```
  closeInstantly = () => {
    const { dragX, rowTranslation } = this.state;
    dragX.setValue(0);
    rowTranslation.setValue(0);
    this.setState({ rowState: Math.sign(0) });
  }
```

**Comment by kopax** [comment]
@buchereli you means to use this instead of the original `close` method?  Have you tried?

https://github.com/software-mansion/react-native-gesture-handler/blob/601581708f3d418efb60a764abf734a8adf07930/Swipeable.js#L262

So you mean this would work right?

```jsx
import React from 'react';
import { Swipeable } from "react-native-gesture-handler";

export default class MySwipeable extends Swipeable {
  close = () => {
    const { dragX, rowTranslation } = this.state;
    dragX.setValue(0);
    rowTranslation.setValue(0);
    this.setState({ rowState: Math.sign(0) });
  }
}
```

What about adding this to the core module?

**Comment by kopax** [comment]
@buchereli  thanks a lot, it is working with this thanks to your help:

```
class MySwipeable extends Swipeable {
  close = () => {
    const { onSwipeableWillClose, onSwipeableClose } = this.props;
    const { dragX, rowTranslation } = this.state;
    dragX.setValue(0);
    rowTranslation.setValue(0);
    this.setState({ rowState: Math.sign(0) });
    if (onSwipeableWillClose) {
      onSwipeableWillClose();
    }
    if (onSwipeableClose) {
      onSwipeableClose();
    }
  };
}
```
I'll close this since this is now fixed, would be nice to consider adding this to the core :)

It took time to get an answer, it's always better than never, unfortunatly if you get back here one day again, my requirement by this time have change xD and I need to close the `<Swipeable />` from the opposite side, perhaps you also know how to do it? 

I have just opened a new issue here: https://github.com/software-mansion/react-native-gesture-handler/issues/1032

**Comment by buchereli** [comment]
@kopax I added closeInstantly as a separate method so you can choose to either animate the close or just do it immediately.

**Comment by kopax** [comment]
Well noted and thanks. Did you had a chance to have a look at #1032? By any chance... Thank you.
