### ISSUE TITLE
Stack navigator inside view wont work

### ISSUE THREAD

**Issue by mathritter** [software-mansion/react-native-gesture-handler#981]
`<View style={{ flex: 1 }}>
        <View style={styles.statusBar}>
        </View>
        <DrawerLayout
          drawerWidth={300}
          drawerPosition={DrawerLayout.positions.Left}
          drawerType='front'
          drawerBackgroundColor="#121e40"
          renderNavigationView={this.renderDrawer}>

          <View style={styles.topBar}>

            <Text >
              AQUI MENU SANDUICHE
            </Text>
            <Image style={styles.icons}
              source={require('../assets/logo.png')}
            />
          </View>

          <View>
            <NavigationContainer>

              <MyStack />

            </NavigationContainer>
          </View>

        </DrawerLayout>
      </View>`

The code above won't work, code below works fine:

`<View style={{ flex: 1 }}>
        <View style={styles.statusBar}>
        </View>
        <DrawerLayout
          drawerWidth={300}
          drawerPosition={DrawerLayout.positions.Left}
          drawerType='front'
          drawerBackgroundColor="#121e40"
          renderNavigationView={this.renderDrawer}>

          <View style={styles.topBar}>

            
            <Image style={styles.icons}
              source={require('../assets/logo.png')}
            />
          </View>

          <View>
          <Text >
              AQUI MENU SANDUICHE
            </Text>
          </View>

        </DrawerLayout>
      </View>`

**Comment by jakub-gonet** [comment]
Please provide more info, namely what happens, what do you expect to happen, any stacktraces and snack with code would be appreciated.
