### ISSUE TITLE
How to detect swipe left/right?

### ISSUE THREAD

**Issue by oferRounds** [software-mansion/react-native-gesture-handler#982]
I know it’s possible, but looking on the documentation I haven’t found an example for the that – could you help?

I need to detect swipe left-right on a `Flatlist` (not interested in a specific row, but to change the the selected tab – reload the flatlist with a new data)

Thanks for this awesome library!

**Comment by oferRounds** [comment]
Is the `FlingGestureHandler` is what I need? For some reason it’s not working

**Comment by aamir-munir** [comment]
following

**Comment by simonstroh** [comment]
Yes, you are correct. You can see an example with the up swipe, left swipe, and right swipe here:

[https://github.com/software-mansion/react-native-gesture-handler/blob/master/Example/fling/index.js](url)

**Comment by simonstroh** [comment]
It worked for me!

**Comment by sturmenta** [comment]
the url of the `FlingGestureHandler` example is now this: 

https://github.com/software-mansion/react-native-gesture-handler/blob/main/example/src/release_tests/fling/index.tsx

**Comment by EKOLX** [comment]
I also have similar issue. I want to detect swipe left and right over ScrollView and update data which ScrollView uses.
Above-mentioned links are not working.
