### ISSUE TITLE
PanGestureHandler causes Animated Value to jump when using native driver

### ISSUE THREAD

**Issue by awinograd** [software-mansion/react-native-gesture-handler#984]
I'm seeing an issue with a custom slider component I've written. Sorry I can't give more information as to the root cause within rngh, but this is my best guess.

In short, PanGestureHandler seems to cause my animated value to jump unexpectedly when used in conjunction with a LayoutAnimation while causing the PanGestureHandler to hide. The bug only occurs when `onGestureEvent` is passed to an `Animated.Event` with `useNativeDriver=true`. If `useNativeDriver=false` there is no issue.

I've created a simplified reproduction in Expo snack.

Steps to reproduce:
1. Open https://snack.expo.io/@ouihealth/gesture-handler-w-layout-animation on Android or iOS
1. Drag the slider handle to somewhere in the middle of the slider
1. Click "Choose" value

Expected result: The slider state (progress bar and position of handle) should be maintained while the slider is removed from the screen.

Actual result: The slider state causes the progress bar and position of handle to jump to the far left of the slider (as if the Animated.Value is set to <= 0)

Thanks for taking a look and please let me know if there's any other information I can provide.

**Comment by flyskywhy** [comment]
Similar issue with rn 0.59.10 and https://github.com/flyskywhy/react-native-smooth-slider on some Android phone.

**Comment by jackyleehong** [comment]
same Issue happen when `useNativeDrive` is set to `true`.

**Comment by piaskowyk** [comment]
If you still have this issue on the latest version of the gesture handler, I recommend using LayoutAnimations from Reanimated, more information are here - https://docs.swmansion.com/react-native-reanimated/docs/api/LayoutAnimations/entryAnimations
