### ISSUE TITLE
Invariant Violation: WebView has been removed from React Native.

### ISSUE THREAD

**Issue by 0x01Brain** [software-mansion/react-native-gesture-handler#985]
I am getting a runtime error on Android, I have the following version of react-native-gesture-handler:
   ` "react-native-gesture-handler": "^1.6.0"`
I installed **react-native-gesture-handler** since it is required by react-navigation. react-navigation version is the following:
`    "react-navigation": "^3.0.8",`

This is the error I am getting:
`Invariant Violation: WebView has been removed from React Native. It can now be installed and imported from 'react-native-webview' instead of 'react-native'. `

So after getting this error, I tried to update **react-native-gesture-handler** , removed `node_modules `folder, clean `android/build` using `./gradlew clean`, and did `npm install` from start again. But that did not solve it, can someone tell whats going on?

My **react-native** version is `0.62.0-rc.2`

**Comment by radko93** [comment]
Why not using react-navigation v4 or even v5?

**Comment by 0x01Brain** [comment]
Cause it will require to change code in app for my navigators such as stack, drawer. I just want a fast way to test upgrading react-native 0.62 to see if it works or not.

**Comment by 0x01Brain** [comment]
@radko93 Okay, I tried and did what you said :) and the error still shows. This is the version I had after upgrading **react-navigation**:
```
    "@react-navigation/stack": "^5.0.6",
    "@react-navigation/drawer": "^5.0.7",
    "@react-navigation/native": "^5.0.6",
```

**Comment by 0x01Brain** [comment]
Anyone!??

**Comment by radko93** [comment]
Webview has been removed a year ago from this repo, so you might still have the old version installed?

**Comment by 0x01Brain** [comment]
> Webview has been removed a year ago from this repo, so you might still have the old version installed?

No, I have version 1.6.0 which is the latest I think.

**Comment by id320kmh** [comment]
I have the same error, any views?

**Comment by Osamasomy** [comment]
Im upgrading my libraries 
"react": "16.13.1",
"react-native": "0.63.2",

after that Im facing same error from stack navigator.

**Comment by jakub-gonet** [comment]
I ran a global search and didn't found any mention of string 'webview'.

Closing until a stack trace and/or repro example is provided.
