### ISSUE TITLE
PanGestureHandler how to working in different events

### ISSUE THREAD

**Issue by m-inan** [software-mansion/react-native-gesture-handler#987]
Problem I have two different events. However, both work when he fires one inside. Is this normal ?
My goal is to change the same variables from different regions. Is there a better way to do this?

I wrote the script to be an example. I can also write all script

```javascript
const firstEvent = event([{
  nativeEvent: ({ translationY }) => block([
    debug('works first event', add(translationY, 0)) // <--- it works here okey
  ])
}])


const secondEvent = event([{
  nativeEvent: ({ translationY }) => block([
    debug('works second event', add(translationY, 0)) // <--- but it works here too
  ])
}])

return (
  <View>
    {/*  when i slide here */}
    <PanGestureHandler onGestureEvent={firstEvent} onHandlerStateChange={firstEvent} />

    <PanGestureHandler onGestureEvent={secondEvent} onHandlerStateChange={secondEvent} />
  </View>
)
```

**Comment by odoland** [comment]
Similar issue with #894. 
Also occurs with multiple TapGestureHandlers

**Comment by jakub-gonet** [comment]
Could you provide a working repro? Hard to tell why it's not working without that.

Closing until repro is given.
