### ISSUE TITLE
How to handle a modal screen with a scroll inside "pattern" (like Snapchat)

### ISSUE THREAD

**Issue by ferrannp** [software-mansion/react-native-gesture-handler#991]
Basically with `react-navigation` and `react-native-gesture-handler` to try to achieve something like this:

![modal-slide](https://user-images.githubusercontent.com/774577/75450454-22e69480-596f-11ea-96f0-a209fae2dbe0.gif)

- Modal screen with a list inside
- I can scroll the list as usual
- When I am on the top of the list, I can dismiss the modal by swiping down in every point of the screen

There is an issue in `react-navigation` with some code I have been trying to figure out myself: https://github.com/react-navigation/react-navigation/issues/7154#issuecomment-591975007.

Posting it here too as it seems something for gesture handler, let me know otherwise @kmagiera.

**Comment by mikedemarais** [comment]
@ferrannp we have been working with @osdnk on the `slack-pan-sheet-react-native-experiment` package with the exact same feature requirements in mind.  https://github.com/osdnk/slack-pan-sheet-react-native-experiment

read his twitter thread for more context https://twitter.com/mosdnk/status/1233097798251425795

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
If you need further help please reply.
