### ISSUE TITLE
Example project doesn't work on iOS 13.3

### ISSUE THREAD

**Issue by wynch** [software-mansion/react-native-gesture-handler#998]
Hello,

I was just trying PanGestureHandler on a project of mine, and I kept getting errors.
So I decided to clone react-native-gesture-handler repo, and see if I could make the Example project run.

I get a list (on simulator iOS 13.3 / iPhone X, and on device iOS 13.3.1 / iPhone 7), but I'm unable to select any item on the list...

**Comment by ShaMan123** [comment]
+1
This seems to be a regression. I have a clone version 1.5.3 that works.

**Comment by ShaMan123** [comment]
This seems to be related somehow to `pointerEvents` on `RectButton`.
See [this](https://github.com/software-mansion/react-native-gesture-handler/blob/master/Example/App.js#L136). If you comment this line the example works.

**Comment by rigdern** [comment]
Here are some additional details.

This isn't specific to iOS 13. I reproed the issue with:
  - iOS 10
  - react-native 0.61.4
  - react-native-gesture 1.5.6

`RectButton` never fires `onPress` when `pointerEvents="auto"`. Here's an example:

```diff
class ButtonMain extends React.Component {
  _onPress = (pointerInside: boolean) => {
    console.log('_onPress: ' + pointerInside);
  }

  constructor(props) {
    super(props);
  }

  render() {
    return (
      <View style={styles.container}>
        <RectButton
          onPress={this._onPress}
+         pointerEvents='auto'
        >
          <Text style={{height: 50, backgroundColor: 'steelblue'}}>Tap Here</Text>
        </RectButton>
      </View>
    );
  }
}
```

The issue doesn't repro without the `pointerEvents` line.
